### PR TITLE
Add San Francisco Fire Credit Union

### PR DESCRIPTION
**Pull request by rbaumbach**
Add the San Francisco Fire Credit Union, which currently does not support two factor authentication.

### CODE REVIEW

**Comment by Carlgo11** [comment]
no document?

**Comment by dsoegijono** [comment]
@Carlgo11 It doesn't have tfa so it doesn't require doc.

**Comment by Carlgo11** [comment]
Oh my bad.

**Comment by dsoegijono** [comment]
@Carlgo11 :+1: Merging this then.

**Pull request merged**
