### PR TITLE
Add lobsters

### PR DESCRIPTION
**Pull request by stephengroat**
#2562

### CODE REVIEW

**Review by mxxcon — APPROVED** [review]
Nothing wrong with the data, but does this site fit our criteria to be listed?

**Comment by jamcat22** [comment]
@mxxcon Usually we allow all sites that _support_ 2FA, only applying the criteria to sites which _do not_ support 2FA. An exception I've seen for this is when a site which only contains a forum is submitted which supports 2FA and is not popular enough to justify adding.

**Review by Carlgo11 — DISMISSED** [review]
Too insignificant

**Comment by stephengroat** [comment]
@Carlgo11 curious why that is. it's an alexa rank ~170k. just ran a quick script, we currently have a lot of other sites about the 170k mark.

should we implement an alexa score minimum?

**Comment by RichJeanes** [comment]
Site seems to be growing. Now in the top 110k.
http://www.alexa.com/siteinfo/lobste.rs
@Carlgo11 ?

**Review by jamcat22 — APPROVED** [review]
As I said earlier, I'd likely not add this site if they did not support 2FA. But since they do, I believe they should be added.

**Comment by fpigerre** [comment]
Would it be worth adding [this link](https://lobste.rs/s/1cyltz/two_factor_authentication_now_available) as the `doc` link?

**Review by fpigerre — APPROVED** [review]

**Pull request merged**
