### PR TITLE
Add Weebly

### LINKED ISSUE #1966: Add Weebly
If you could add Weebly (weebly.com), that would be great! :smile: if you need any more info, please don't hesitate to let me know. :laughing:

### PR DESCRIPTION
**Pull request by stephengroat**
closes #1966

### CODE REVIEW

**Comment by Carlgo11** [comment]
Have you checked that they don't support 2FA?

**Comment by stephengroat** [comment]
Yup, I opened an account and didn't see any other option than change password.

screenshot from 2016-08-12 08 23 03

**Comment by Carlgo11** [comment]
ok thanks

**Comment by Carlgo11** [comment]
Guess what?
merge conflict :boom:

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
