### PR TITLE
Add Commercial Bank of Qatar

### PR DESCRIPTION
**Pull request by davchana**
I have added Commercial Bank of Qatar to the list, listed in issue #2651 

The bank requires a username/password combination on every login attempt; & then a one time 5 minute valid 6 digit long numeric code is sent via SMS to your registered local Qatari Mobile Number., along with login attempt number of the day (Attempt #1; #2; .....) Each OTP is valid for each unique attempt; & will fail if not used for that attempt.

No TOTP/Google Auth etc are supported; & Registered Mobile Number can be changed by either visiting Bank Branch with your government issued Qatar ID Card; or calling the bank support phone & identifying with certain details of account & related.

Documentation is very vaguly located in [FAQ Section of Internet Login Page](https://cbonline.cbq.qa/RIB/Common/FAQContent?key=Welcome#stay). Easiest way to find is to search for Question: "What happens if I lose my Device" as keyword. Page uses javascript & accordion to display the answer; & currently states:

> ​As there is no financially sensitive information stored on the device, no one will be able to access your accounts without your unique login password and One Time Password (OTP)(......)

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr and great explanation @davchana

**Comment by davchana** [comment]
@stephengroat Thanks for the encouraging words :) My first PR !!

**Review by Carlgo11 — COMMENTED** [review]
What about this image? It's 32x32 pixels and taken from their twitter account. There's a little less light shifting in this than the original one. 
clm_q0-8_400x400

**Comment by stephengroat** [comment]
@Carlgo11 is you image blocking on this? this pr has been open for a while

**Comment by Carlgo11** [comment]
@davchana it looks like I don't have access to add the new image myself. Could you do it instead?
It's the one I mentioned in a previous comment. ⬆️

**Comment by davchana** [comment]
@Carlgo11 I am struggling to add this image, but because of some things in life could not get it right. I have added you as collaborator in my fork, please accept invite at https://github.com/davchana/twofactorauth/invitations & add this. Thanks..

**Comment by jamcat22** [comment]
Bump @Carlgo11.

**Comment by Carlgo11** [comment]
Should be good to go. Want to do the honor @jamcat22?

**Review by jamcat22 — APPROVED** [review]

**Pull request merged**
