### PR TITLE
Adding IRS individual transcript site

### PR DESCRIPTION
**Pull request by jpvantuyl**
Brian Krebs had a good article on how crooks can start getting your IRS
transcripts and use them to perpetrate tax fraud
(https://krebsonsecurity.com/2015/03/sign-up-at-irs-gov-before-crooks-do-it-for-you/).

### CODE REVIEW

**Comment by mxxcon** [comment]
Perhaps use this icon? http://apps.irs.gov/static_assets/img/icons/favicon.ico
(for some reason in firefox it's 16x16 but in Chrome it's 32x32)

**Comment by Carlgo11** [comment]
Here's the picture in a compressed png format (and 32x32)

**Comment by mxxcon** [comment]
@jdavis This build dies...

**Comment by Carlgo11** [comment]
@mxxcon awh I thought I had fixed that. Anyways, restarting the build seems to work every time.

**Pull request merged**
