### PR TITLE
Add StackSocial

### PR DESCRIPTION
**Pull request by RobThree**

### CODE REVIEW

**Comment by Carlgo11** [comment]
I think you'll need to explain to me what that site is about. Is it like a special offers site? If so, how does it fit in to the social media category?

**Comment by RobThree** [comment]
[CEO Josh Payne explains](https://www.youtube.com/watch?v=zdhfojSndv0) it best I guess. It's part of [StackCommerce](https://stackcommerce.com/). Come to think of it (or: I don't know what I was smoking when I created this PR :stuck_out_tongue_closed_eyes: ), it maybe better goes under `Other`.

Seriously... why I put it under social is beyond me... I've updated the PR.

**Comment by Carlgo11** [comment]
Hello again Rob,
Yes I think retail would be the best category.
Would you please move SocialStack to retail?

Thank you very much!
//@Carlgo11

**Comment by RobThree** [comment]
:laughing: I just moved it to 'other'. I think it may be the even better option, don't you? If you disagree I'll be glad to move it to retail.

**Comment by Carlgo11** [comment]
@RobThree please move SocialStack to the retail category instead.
I think that fits the best.

**Comment by RobThree** [comment]
As you wish. Done! :+1:

**Pull request merged**
