### PR TITLE
Add Unify Financial Credit Union

### PR DESCRIPTION
**Pull request by ghost**
Please add Tower Federal Credit Union, they have 2FA via SMS & Phone.

### CODE REVIEW

**Comment by stephengroat** [comment]
thanks for the pr @Mustang42 

This image has no text and is a little bit smaller, could you update with it?

towerfcu

**Comment by ghost** [comment]
Sure thing! Added new png file & removed the old one.

**Comment by stephengroat** [comment]
@Mustang42 we like to have 1 entry edited per a pr

could you remove the last commit?

**Comment by stephengroat** [comment]
@Mustang42 could you make a seperate branch for the unity bank as well? i see the seperate tower branch #2621

**Comment by ghost** [comment]
@stephengroat I'm not sure how I can remove the last commit without closing this pr & opening a new one? Is there a better/easier way to do this?

I thought I was creating two separate pr's for both Tower & Unify but apparently I did it wrong & they are now combined :-(

**Comment by stephengroat** [comment]
@Mustang42 we've merged #2621 which adds Tower.

Could you remove tower from this pr and just make it unity?

**Comment by ghost** [comment]
I was able to remove TowerFCU from the YML file but I don't see a way to delete the PNG file from the pr?

**Comment by ghost** [comment]
Never mind! I figured it out & removed the TowerFCU.png - should just be Unify commits now. Thanks!

**Review by stephengroat — APPROVED** [review]
thanks for the work @Mustang42

**Comment by ghost** [comment]
Sure thing! Happy to contribute :-)

**Review by Carlgo11 — APPROVED** [review]

**Review by jamcat22 — CHANGES_REQUESTED** [review]
Are we sure Unify doesn't offer 2FA? They appear to have multiple mentions of it on the site, as well as an [article](https://www.unifyfcu.com/multi-factor-authentication-keep-bad-guys-out) about it. Usage also appears in their online banking [demo video](https://youtu.be/2m6UyZRZO5E?t=2m). It seems they support phone call, SMS, and email 2FA.

**Comment by ghost** [comment]
Unify now does offer 2FA.



________________________________

**Review by jamcat22 — APPROVED** [review]

**Pull request merged**
