### PR TITLE
Added digicert

### PR DESCRIPTION
**Pull request by NoodlesNZ**
Added digicert and sorted security websites by alpha

### CODE REVIEW

**Comment by RichJeanes** [comment]
Rearranging the entries is unnecessary. They get sorted alphabetically when the site source files are built. Also, please use spaces instead of tabs for indentation. Tabs change across platforms and can cause problems.

**Comment by NoodlesNZ** [comment]
Ok, will fix

**Comment by NoodlesNZ** [comment]
Ok, should be good now. Have replaced tabs with spaces and just added digicert at the bottom

**Comment by RichJeanes** [comment]
Looks good. Going to wait for the Travis-ci build to pass. :thumbsup:

**Pull request merged**
