### PR TITLE
Added Kickstarter

### PR DESCRIPTION
**Pull request by cedric**
This went live today and users can enable it from their account page.

### CODE REVIEW

**Comment by mxxcon** [comment]
Any `doc:` links with additional info?

**Comment by cedric** [comment]
Not yet, but I'll add it when it exists. Likely an FAQ link. I just didn't
want to link to the account page, as that would 404 for logged-out users.

**Comment by devpuppy** [comment]
LGTM :+1:

**Comment by jdavis** [comment]
Awesome guys. Keep up the great work at Kickstarter :smile:

**Comment by cedric** [comment]
Thanks!

**Pull request merged**
