### PR TITLE
Adds GOG.com

### PR DESCRIPTION
**Pull request by jrvidal**
Come on, GOG.com, let's play safe!

### CODE REVIEW

**Comment by RichJeanes** [comment]
Looks good but needs a couple quick fixes. You don't need the @ sign on the twitter handle and if you could find a 32x32 icon to match the guidelines in the ReadMe, that would be fantastic!

**Comment by jrvidal** [comment]
Done! Sorry about my sloppiness.

**Comment by RichJeanes** [comment]
Nice :thumbsup:

**Comment by computmaxer** [comment]
@jrvidal This has a merge conflict due to the changes merged in #142. You'll have to move this to the `gaming.yml` file instead of `main.yml`

**Comment by jrvidal** [comment]
Done!

**Comment by jdavis** [comment]
Thanks, @jrvidal! Sorry to pull out the rug from underneath you with those changes.

**Comment by jrvidal** [comment]
No problem! I really liked the idea :smile:

**Pull request merged**
