### PR TITLE
Add US Postal Service

### PR DESCRIPTION
**Pull request by mmomjian**
image

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
I actually think that this SVG is better suited for the USPS listing. Just remember to save it as `usps.svg` and not `usps.png` 😉

**Comment by mmomjian** [comment]
Thank you! Completed, I think.

**Review by Carlgo11 — APPROVED** [review]
Спасибо! 👏 😄

**Comment by phallobst** [comment]
This SVG logo has no unnecessary margin and is centered in its bounding box:

**Comment by Carlgo11** [comment]
> This SVG logo has no unnecessary margin and is centered in its bounding box:
> 
> 

@phallobst Illustrator stopped working for me 😓

**Review by phallobst — APPROVED** [review]

**Pull request merged**
