### PR TITLE
Add open classifieds

### PR DESCRIPTION
**Pull request by stephengroat**
#1893

### CODE REVIEW

**Comment by mxxcon** [comment]
is there docs link how people can enable 2fa?

**Comment by stephengroat** [comment]
Added a link

**Comment by mxxcon** [comment]
what's the difference between this and #1897?

**Comment by stephengroat** [comment]
From what I can tell, yclas is a hosted solution, while open classifieds is the underlying project.

Which do you think would be better to keep?

**Comment by mxxcon** [comment]
We generally don't list self-hosted projects...

**Comment by stephengroat** [comment]
No problemo

**Comment by neo22s** [comment]
Hello,

Open Classifieds is a FOSS php script that you need to host yourself, like wordpress.org. Where Yclas its a SaaS that has 2FA for customers to login to use their sites (that also have 2FA), llike wordpress.com.

Not sure if I explained myself properly xD

regards

**Comment by Carlgo11** [comment]
Thank you for clarifying that @neo22s. By the sound of it Open Classifieds does not fit our list as we don't list self hosted sites (like wordpress.org) here.

**Comment by neo22s** [comment]
aha! so do not add it heheh thanks!

**Pull request closed without merging**
