### PR TITLE
Add EngineYard

### PR DESCRIPTION
**Pull request by ilyakatz**

### CODE REVIEW

**Comment by mxxcon** [comment]
I don't like "currently in beta" part. Without any type of dating system no way to know how current this _currently_ is. Perhaps a better wording would be something like `as of late May 2014....`

**Comment by ilyakatz** [comment]
@mxxcon well isn't everything "currently in " status? For example, any site that has an "In progress" marker will become outdated when the company completes their work. So we would need to update it at that time (hopefully, the community will pick it up sooner rather than later)

**Comment by mxxcon** [comment]
True, however with the current 'in progress' there's a link to a tweet which has some sort of date reference.
Also "available by request" to where?

**Comment by ilyakatz** [comment]
Ok, makes sense. Will update in a different pull request, as well as wording of by request via a support ticket

**Comment by mxxcon** [comment]
:+1:

**Comment by jdavis** [comment]
Great point, @mxxcon. :+1:

**Pull request merged**
