### PR TITLE
update health.yml

### PR DESCRIPTION
**Pull request by ioann1s**
withings
added tfa status for withings and will upload logo

### CODE REVIEW

**Comment by RichJeanes** [comment]
Please make sure the logo is a 32x32 png added to img/health as per the README guidelines!

**Comment by ioann1s** [comment]
Here is the 32x32 png file.
withings

sorry for not going through the readme first.
Regards,
John

**Comment by RichJeanes** [comment]
Awesome. I'll make sure that makes it in. :thumbsup:

**Comment by zach-taylor** [comment]
Hi @ioann1s can you add the 32x32 file to the pull request so this can get merged in? Thanks!

**Comment by mpdavis** [comment]
I adding the withings image so this is good to go.

**Pull request merged**
