### PR TITLE
Add YourAcclaim

### PR DESCRIPTION
**Pull request by kmpoppe**
Regarding Issue #3654
Global Alexa Rank at time for checkin: 23,643.
Supports 2FA with Software token only.
No additional information is supplied by the website.

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
👍 confirmed!

**Comment by Carlgo11** [comment]
@kmpoppe When a documentation page can't be added we need some sort of documentation that the site does indeed provide 2FA. Could you send screenshots of the login/setup process? (with any personal information blurred out)

**Comment by kmpoppe** [comment]
acclaim-2fa-activation

@Carlgo11 this is the account-setup page of youracclaim with 2FA activated. What are the next steps?
... Shall I add a "notes" webpage with that image under /notes/img/ ?

**Comment by Carlgo11** [comment]
@kmpoppe and the login page?
No need to create a notes page. Leaving the screenshots here in the comments is sufficient.

**Comment by kmpoppe** [comment]
First Login (Email and Password):
grafik
Two Factor Code entry:
grafik

**Review by Carlgo11 — APPROVED** [review]
Great, thanks! 👍

**Pull request merged**
