### PR TITLE
Update Wells Fargo

### PR DESCRIPTION
**Pull request by tonybruess**

### CODE REVIEW

**Comment by tonybruess** [comment]
Is there anything to do before merging this?

**Comment by mxxcon** [comment]
Well, in your other thread you mention that it does check 2fa when you perform certain type of transactions. So it does have 2fa...not necessary for login, but it's there...

**Comment by tonybruess** [comment]
The only time it's happened is when using their direct pay service. So, it's essentially not there. Should this information be reflected at all if it's basically nonexistent?

**Comment by mxxcon** [comment]
Perhaps this should be indicated using exception, similar to Dynadot or other sites that we have listed.

**Comment by tonybruess** [comment]
I don't think this should be considered two factor auth at all, honestly.

**Comment by Carlgo11** [comment]
Since I don't have a Wells Fargo account myself, would you mind using Tor to connect to Wells Fargo.
Maybe that would trigger the TFA.

**Comment by tonybruess** [comment]
I really don't think it's going to make a difference

**Comment by Carlgo11** [comment]
I think so. Tor exit relays are often marked as malicious and so that might trigger the system to ask for TFA.

**Comment by mxxcon** [comment]
But keep in mind that some can be truly malicious and him logging in to his banking site might not be a smart idea...

**Comment by tonybruess** [comment]
Yeah, sorry, I'm not going to try. I've logged in from different IPs, airports, coffee shops, etc.... all with no tfa. I highly doubt a tor login will make a difference.

**Comment by Carlgo11** [comment]
@mxxcon if using https there's nothing anyone could do that's listening to the tor traffic.
Only the exit relay could read anything as all middle relays send traffic encrypted. Even so, https.
All they'd get is random ssl/tls noise.
EFF Tor example

There's nothing that could hurt by logging in via Tor. (Except the ISP seeing that you're connected to Tor)

For more info on the Tor network and who can see what, go to this interactive example: [Tor and HTTPS](https://www.eff.org/pages/tor-and-https)

**Comment by tonybruess** [comment]
Regardless, the fact that I can login from anywhere and transfer money/view very confidential account information... I don't see how this should even be considered some type of tfa.

**Comment by Carlgo11** [comment]
@tonybruess could you update your local branch with the remote?
The PR have some merge conflicts.

**Comment by tonybruess** [comment]
Rebased

**Comment by mxxcon** [comment]
+looks-good 

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jdavis/twofactorauth/1115)

**Comment by tonybruess** [comment]
Thanks for merging this :)

**Comment by Carlgo11** [comment]
And thank you for your additions to the project.

**Pull request merged**
