### PR TITLE
Add Internxt's X Cloud

### PR DESCRIPTION
**Pull request by fvsegarra**

### CODE REVIEW

**Review by kmpoppe — CHANGES_REQUESTED** [review]
Hello @fvsegarra and thank you for your contribution!
The automated test on the image you uploaded failed, because there is no entry in the data-files that uses it.
Could you please provide further information as to what the image shall be used for and possibly even add this entry?
Thanks!
// Kai

**Comment by fvsegarra** [comment]
Pull request for image makes reference to this pending change https://github.com/2factorauth/twofactorauth/commit/27fb909b4b1b8fd0047fa961dd5c4b9a615b3fe0 Both are to be approved

**Comment by kmpoppe** [comment]
@fvsegarra The page you want to add to the repository is not within the 200k Alexa-ranking as described in the Guidelines of this project. I'm therefore currently unable to approve this PR.

**Comment by kmpoppe** [comment]
Closed as per consultation with 2fa/members.

**Comment by fvsegarra** [comment]
Alright -will circle back once all requirements are met. Thx

**Pull request closed without merging**
