### PR TITLE
Update NordVPN

### PR DESCRIPTION
**Pull request by 40504**

### CODE REVIEW

**Comment by 40504** [comment]
Screen Shot 2021-03-23 at 01 19 11

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
@40504 I removed your screenshot as it contained an email address.

**Comment by 40504** [comment]
I know, I always use disposable emails for testing

**Comment by 40504** [comment]
What tool do you use for clean up svg files?

**Comment by Carlgo11** [comment]
@40504 I just use the text-editing feature here on GitHub. If I see something in the XML that isn't needed I remove it.

**Comment by 40504** [comment]
My flow: grab SVG file from the website if it exists, adjust it Sketch App, the exported SVG file is not optimized at all when exporting from Sketch so I have to use other tools: first https://www.svgminify.com/ to add `viewBox` attribute then optimize throught https://jakearchibald.github.io/svgomg/ and finally is not fully optimized, since you every time update my SVG file :) that's a lot of movements. I think it should be easier :) or even automatically by 2fa.directory

**Comment by Carlgo11** [comment]
Yeah that sounds like a lot of work. I just grab the icon and edit it in Illustrator before cleaning up the code manually in notepad++/nano.
@phallobst have created hundreds of SVGs for the project. Maybe he has some good workflow to recommend?

**Comment by 40504** [comment]
I saw @phallobst recommend https://vecta.io/nano but it's not done all the job plus it adds unnecessary metadata

**Comment by phallobst** [comment]
For optimization, I usually use [svgo](https://github.com/svg/svgo) on the command line, and [nano](https://vecta.io/nano) for some rare edge cases.

**Review by phallobst — APPROVED** [review]

**Pull request merged**
