### PR TITLE
Add SecurityTrails

### PR DESCRIPTION
**Pull request by DandelionSprout**
It's a site for advanced searching of domains and IP addresses.

The site deals with *Money*, in the sense that one can buy pretty expensive monthly subscriptions to its API.

The site is ranked as №14,164 on Alexa.

image

image

### CODE REVIEW

**Comment by phallobst** [comment]
It seems to me that this website rather belongs in the `domains` category instead of `other`. Any opinions on that?

**Comment by DandelionSprout** [comment]
I took a guess that `domains` was solely for sites about registering domains, not about looking them up.

**Review by ApCoder123 — CHANGES_REQUESTED** [review]
- Please use this as the doc URL: https://securitytrails.com/support/knowledge-base/two-factor-authentication-2fa-2/
- I reckon that this should go in the `security` category instead of `other`
- SVGs are the preferred image type. Please use this icon:
SecurityTrails SVG

Thanks

**Comment by DandelionSprout** [comment]
@ApCoder123 I have now done all three of those things.

**Review by ApCoder123 — APPROVED** [review]

**Review by phallobst — APPROVED** [review]

**Pull request merged**
