### PR TITLE
Add an "Insurance" category

### PR DESCRIPTION
**Pull request by hkamran80**
Dependent on 2factorauth/2fa.directory#62

The insurance category was proposed in [#8098](https://github.com/2factorauth/twofactorauth/pull/8098#issuecomment-2172082569). If any sites are missing from this list, please let me know. I have also removed some `url`s where they are not needed and updated the categories.

A few questions:
- Regarding Cigna, should we change the domain to `cigna.com` instead of `my.cigna.com` (`my.cigna.com` is the insurance portal)?
- Does [Independer](https://independer.nl) ([entry](https://github.com/2factorauth/twofactorauth/blob/master/entries/i/independer.nl.json)) count as insurance? I think it does, but I'd like to know your opinions.

### CODE REVIEW

**Comment by fletcherdodd** [comment]
Love this! I have a few more AU ones to add, and was going to make the suggestion to seperate them out 🙂

I would say Independer sits in both categories (finance and insurance) since it does offer both 'products'

**Comment by hkamran80** [comment]
> I would say Independer sits in both categories (finance and insurance) since it does offer both 'products'

Sounds good to me!

**Comment by Carlgo11** [comment]
You broke my beautiful (and barely functioning) script, @hkamran80! ☹️
screenshot

I'll just use my black magic powers and force-merge this PR.

**Comment by hkamran80** [comment]
> You broke my beautiful (and barely functioning) script, @hkamran80! ☹️

Whoops. On the bright side, found a flaw?

**Comment by Carlgo11** [comment]
The insurance category is live now. I cleared the cache for https://2fa.directory/au/ to check. The rest of the regions will slowly update.

**Pull request merged**
