### PR TITLE
Added Centrify entry and logo file

### PR DESCRIPTION
**Pull request by cybertronic**

### CODE REVIEW

**Comment by mxxcon** [comment]
@cybertronic is this 2fa to sign into Centrify service itself or for other services to integrate Centrify?

**Comment by cybertronic** [comment]
Both, we are an IDP, so we enforce MFA to login to our service and thus other SaaS based apps, as well as provide the MFA service itself.

**Comment by cybertronic** [comment]
So, can this be merged, or do you have more questions for me?

**Comment by Carlgo11** [comment]
@cybertronic the logo is waaay too big.
I compressed it down to 1kb.
Use this one instead:

**Comment by cybertronic** [comment]
Updated with your image, thanks

**Comment by jamcat22** [comment]
I think it `looks-good`!

**Comment by cybertronic** [comment]
How often does the website get refreshed from the source? I dont see the Centrify entry on there yet, even though its been merged.
Maybe I have a cached page?

**Comment by RichJeanes** [comment]
[Wiki: My Pull Request was merged but it's not showing up on the site](https://github.com/2factorauth/twofactorauth/wiki/FAQ_Merge)

**Pull request merged**
