### PR TITLE
Added rsync.net

### PR DESCRIPTION
**Pull request by jeremy-moschner**
Adding rsync.net.  Email 2FA only enabled for certain account-related changes

### CODE REVIEW

**Comment by mxxcon** [comment]
Need a logo image.
Additionally, two factor authorization is not the same as two factor authentication.
For this site authorization would be considered as 'tfa: no'.

**Comment by fpigerre** [comment]
Hello @jeremy-moschner,

Thanks for the pull request! :+1: 
For more information regarding [twofactorauth.org](https://twofactorauth.org)'s definition of "two factor authentication", please feel free to take at "[a note on definitions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions)".

Other information relating to the addition of websites can also be found on [our wiki](https://github.com/2factorauth/twofactorauth/wiki).

Thankyou,
psgs :palm_tree:

**Comment by jamcat22** [comment]
Hi @jeremy-moschner!

Could you please add a logo, and change the `backup.yml` to reflect that the website doesn't support 2FA?

Thanks!

**Comment by Carlgo11** [comment]
@jeremy-moschner Will you do push the proposed updates by @psgs and @jamcat22?
Please respond within a couple of days or I'll close this PR.

**Comment by jeremy-moschner** [comment]
Sorry, I'm not able to attend to this now.  Will reopen again and take in the comments made on this thread.

**Pull request closed without merging**
