### PR TITLE
Add section.io Content Delivery Grid

### PR DESCRIPTION
**Pull request by jstangroome**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr @jstangroome

**Comment by jstangroome** [comment]
@stephengroat Do you require further details from me to merge and publish?

**Comment by stephengroat** [comment]
@jstangroome nope, just waiting for another member of @2factorauth/collaborators to approve.

shouldn't take too much longer!

**Review by Jawshy — APPROVED** [review]
Sorry for the delay.

**Pull request merged**
