### PR TITLE
Add Larian

### PR DESCRIPTION
**Pull request by ColinHebert**
larian.com (Videogame company responsible for Divinity Original sin, Baldur's gates 3), [rank 131,933](https://www.alexa.com/siteinfo/larian.com) supports TOTP, add details about it.

### CODE REVIEW

**Comment by phallobst** [comment]
700k for the SVG icon seems a bit excessive. :wink: Please replace it with a PNG version.

**Comment by Carlgo11** [comment]
@phallobst from looking at the code I think he used a PNG to generate the SVG. In fact it looks like most of the submitted PRs use this technique.

**Comment by ColinHebert** [comment]
Correct, and can do with the replacement

**Comment by ColinHebert** [comment]
Similar to CardMarket where there is no page describing how to enable 2FA, here is a screenshot of the account management page which allows to setup 2FA

Screen Shot 2022-01-02 at 00 35 29

**Review by Carlgo11 — APPROVED** [review]
Thanks for the pull request! :+1:

**Review by ApCoder123 — APPROVED** [review]

**Pull request merged**
