### PR TITLE
Added pandora.

### PR DESCRIPTION
**Pull request by awelch83**

### CODE REVIEW

**Comment by mxxcon** [comment]
How would this site fit into our criteria? https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria

**Comment by awelch83** [comment]
Spotify fits, so this fits. That's how. Any other questions for me?

**Comment by awelch83** [comment]
How does Hulu fit, @mxxcon ?
How does last.fm fit, @mxxcon ?
How does netflix fit, @mxxcon ?
How does sling.tv fit, @mxxcon ?

How does the entertainment category as a whole fit, @mxxcon ?

**Comment by awelch83** [comment]
The question is ridiculous, @mxxcon . Does the site fit the criteria as it is currently written? No. However, neither does many of the other sites listed in that section. Someone saw fit to merge those pull requests. Pandora is no less valid then any of the others.

**Comment by mxxcon** [comment]
@awelch83 I feel some animosity and agitation towards me... I have done nothing to justify that. 
Asking a simple question warrants a flood or replies and mentions?
Perhaps you should reevaluate your attitude...

**Comment by awelch83** [comment]
The question is ridiculous, @mxxcon . Does the site fit the criteria as it is currently written? No. However, neither does many of the other sites listed in that section. Someone saw fit to merge those pull requests. Pandora is no less valid then any of the others.

How does Hulu fit?
How does last.fm fit?
How does netflix fit?
How does sling.tv fit?

How does the entertainment category as a whole fit? I don't have patience for this kind of stupidity. If Pandora doesn't fit, then neither does any of the sites that I've mentioned above. I will continue to copy and paste this exact message until you address the questions contained herein.

**Comment by Carlgo11** [comment]
@awelch83 Please keep a friendly tone with us when answering our questions. We're volunteers who dedicate a large amount of our free time to this project.
It's very very impolite to use that attitude to @mxxcon, me or any other collaborators since we've done nothing to deserve such an attitude.

If you can't keep keep the discussions friendly I recommend you stop interacting with us and this project.
Now I expect your next message to contain an apology to @mxxcon for your outburst.

**Comment by awelch83** [comment]
I owe @mxxcon nothing and will give him nothing. His question shouldn't even have been a question, for the reasons I've outlined above. Twice. As familiar as I assumed he was with this project, I am surprised he even asked it.

**Comment by mxxcon** [comment]
@awelch83 I'm sorry I do not have 100% perfect memory like you are. I'm sorry I do not remember every single site listed in every single category in this project.

**Comment by awelch83** [comment]
Seems like you forgot a whole section, to be honest. None of those sites really fit the "criteria". 

(Referring to the entertainment page)

**Pull request closed without merging**
