### PR TITLE
Adds servercow.de hosting

### PR DESCRIPTION
**Pull request by ThomasLeister**
Adds servercow.de hosting service.

### CODE REVIEW

**Review by Jawshy — COMMENTED** [review]
@ThomasLeister, does Servercow.de have any documentation that lists instructions for enabling two-factor authentication?

**Comment by ThomasLeister** [comment]
@Jawshy just had a look again. There are short instructions, but these are not visible publicly. They can be seen on the account page which also includes the activation button.

**Review by stephengroat — APPROVED** [review]
thanks for the pr @ThomasLeister

**Comment by Carlgo11** [comment]
Closing due to the Alexa rank being >200k. See CONTRIBUTING.md for reference,

**Pull request closed without merging**
