### PR TITLE
Adding Cellcom

### PR DESCRIPTION
**Pull request by wisco24**

### CODE REVIEW

**Review by mxxcon — COMMENTED** [review]
Is this site significant enough? 🤔alexa lists it at almost 400k and if I remember correctly we might try to put a cut-off at 200k+

**Comment by stephengroat** [comment]
i'd say no

**Comment by wisco24** [comment]
Where is that documented?  What are you using as a source to make that determination?

**Comment by stephengroat** [comment]
@wisco24 it's not documented (something that we're working on), but we use www.domaintally.com (and the alexa ranking) to make the determination)

**Comment by wisco24** [comment]
Company to small for now to add.

**Pull request closed without merging**
