### PR TITLE
Add cwnp

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by Jawshy** [comment]
@stephengroat, you may like to use this icon instead. It's their favicon, but at 32² pixels. 
cwnp 
Alternatively, the current icon, but slightly tweaked. 
cwnp-1

**Comment by stephengroat** [comment]
@Jawshy which do you think is better? first or second? i'll defer to your judgement

**Comment by Jawshy** [comment]
@stephengroat, first, as it lacks text.

**Comment by Carlgo11** [comment]
@Jawshy please send me your email address of choice to github@carlgo11.com.
Couldn't find an email address for you :see_no_evil:

**Comment by Jawshy** [comment]
@Carlgo11, sent. :mailbox_with_mail:

**Review by fpigerre — APPROVED** [review]

**Comment by Jawshy** [comment]
@stephengroat, would you like to add their `email_address`? 

``` ruby
      email_address: customercare@cwnp.com
```

**Pull request merged**
