### PR TITLE
Add upwork

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by mxxcon** [comment]
How would this apply to our site criteria?

**Comment by stephengroat** [comment]
Upwork is a freelancing site and has significant billing and personal information for freelancers stored with it. It also is in the Amazon Alexa Top 500

**Comment by stephengroat** [comment]
conflict resolved

**Comment by Carlgo11** [comment]
If you want to you can add `facebook: upwork` here as well. Just if you want to though.

**Comment by stephengroat** [comment]
the more ways to bother a company, the better. done

**Comment by Carlgo11** [comment]
Exactly my though!

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
