### PR TITLE
Fix desktop alignment and buttons

### PR DESCRIPTION
**Pull request by dsoegijono**
Addressing some issues mentioned by @jdavis in #3095 
- Fix icon >< name alignment on desktop
- Move text outside of buttons to make them smaller

screen shot 2019-01-13 at 8 19 20 pm

### CODE REVIEW

**Review by fpigerre — DISMISSED** [review]

**Comment by Carlgo11** [comment]
Would it be too difficult to align the `Tell them to support 2FA` texts?

**Comment by dsoegijono** [comment]
@Carlgo11 Depends on how you want them aligned. Left-aligned for all would be pretty simple, but the buttons would be left-aligned too (otherwise I think it would look weird).

Left aligned:
screen shot 2019-01-15 at 7 42 58 pm

**Comment by Carlgo11** [comment]
What I had in mind is something more in the lines of a centered div but everything inside the div is aligned to the left.

**Comment by dsoegijono** [comment]
@Carlgo11 So the `div` would have a fixed width assuming all 3 buttons are present?

**Comment by Carlgo11** [comment]
@dsoegijono yeah

**Comment by dsoegijono** [comment]
screen shot 2019-01-16 at 10 47 43 pm

@Carlgo11 updated, let me know what you think! (also need @psgs to review again)

**Comment by fpigerre** [comment]
I think this option looks a little stranger, given that the number of buttons is variable, but each set of buttons and accompanying text is centred in the same spot; meaning that the entries without all three Twitter, Facebook and Email buttons appear off centre to the left.

**Comment by Carlgo11** [comment]
@psgs so you like the first version better?
I feel it's easier to read when they're aligned.

**Comment by dsoegijono** [comment]
I prefer [left-aligned](https://user-images.githubusercontent.com/867840/51168589-d15f7f80-18fd-11e9-81dc-26fa086dfe09.png) without a div being centered

**Comment by fpigerre** [comment]
I agree with @dsoegijono I think. The div centring the text looks a bit strange.

**Comment by dsoegijono** [comment]
Updated to left-aligned.
screen shot 2019-01-20 at 6 24 22 pm

@Carlgo11 @psgs

**Review by fpigerre — APPROVED** [review]

**Review by jamcat22 — APPROVED** [review]

**Pull request merged**
