### PR TITLE
IFTTT now support 2FA

### PR DESCRIPTION
**Pull request by tswestendorp**

### CODE REVIEW

**Comment by jamcat22** [comment]
Any doc url?

**Comment by jamcat22** [comment]
Also, you can remove the `twitter` line.
And add `sms: Yes`

**Comment by tswestendorp** [comment]
Searched for it, but wasn't able to find it

They released an iOS app update mentioning 2FA support

**Comment by tswestendorp** [comment]
> Also, you can remove the twitter line.
> And add sms: Yes

done

**Comment by jamcat22** [comment]
Great. We'll just wait for Travis to finish then I think it `looks-good`

**Comment by mxxcon** [comment]
I'd like to get some more confirmation then a single line in iphone app change log that it is what we think it is...

**Comment by tswestendorp** [comment]
I immediately turned it on in my account so I can confirm that 2FA is supported now

**Comment by mxxcon** [comment]
So how does it work? What's the workflow? What `software` does it use?

**Comment by tswestendorp** [comment]
It's OTP based, so any OTP app will do. After enroll you're getting one backup code

**Comment by jamcat22** [comment]
SMS just sends you a test text then enables and gives a backup code.

OTP lets you scan the qr and enter a test code. Then it gives you a backup code.

**Comment by jamcat22** [comment]
Email sent after:

From: IFTTT <welcome@ifttt.com<mailto:welcome@ifttt.com>>
Subject: You've turned on more secure IFTTT logins

Hi [username removed],

Congratulations! You've enabled two-step verification for your IFTTT account.

While setting up two-step verification, you were assigned a unique recovery code. It's important that you save the recovery code in a secure spot. If you lose your device, change your phone number, or lose access to your authenticator app, the recovery code will be the only way you can regain access to your IFTTT account.

If you did not save the recovery code during setup, we recommend disabling two-step verification, then setting it up again.

To update your two-step verification settings, visit https://ifttt.com/settings. http://email.ifttt.com/wf/click?upn=6tNAOFwxcF8KzWlMrDEXkHoJJzUJfMNtn80ibwaQcbk-3D_76-2BcLLrecVO-2Blp2FWgBC7VktK7NTMOEpQrJxU4EbOllhTRegrt-2FXXdlNUbVEWk-2B5-2F6uxZ4RfSb28ZdIGnsQFfAYLNkRuD6e6GIP0w4uUZ6HlVMmwcnTaX1DO1LdVH3Nkhcik7uykMn0NwkIPgvkndyprkfzqQNEm9jC1hS3vCxazbe2PCo8tfi86qxvQLITD2ceWPXQc3drABDl7iuXoLrifdC7J0desYR1-2F9crOpTNonPONwEvi3DzlK673T52-2FDp8qSl5rZs-2BO6m7acmKcKWQ6W56RGMP-2Bu9lfyaACgdQ-3D
- The IFTTT Team

---

[IFTTT] http://email.ifttt.com/wf/click?upn=6tNAOFwxcF8KzWlMrDEXkMBsNv6tbjg3LZSM0iBW7bQ-3D_76-2BcLLrecVO-2Blp2FWgBC7VktK7NTMOEpQrJxU4EbOllhTRegrt-2FXXdlNUbVEWk-2B5APiKfqRu25yr5LhCKgVqTHwwDP12tyTuJfD5-2FV2mtY1ZrwJNkm6XVyGGT-2FTJQLEYAN3Dh-2FPJIA0f4e1yEHUN01BS95Wfqi47j36EqUd2RJOZPKngQS0G7RMtyf0YE-2FMqpEw3twclKNPqE0ikZs2xaoHjB6aryinlDa9YxpDSvrVgCd-2B-2FkXl1XsSrKw96HaINeGtAWDjPsZa5wgwLekBZ-2BFOpS9RZDymR5OcY5WVbCGA-3D

Put the internet to work for you.

**Comment by mxxcon** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jdavis/twofactorauth/1188)

**Comment by rugk** [comment]
As for a doc URL: What about the [blog post](http://blog.ifttt.com/post/122351757903/two-step-verification-is-now-available-for-your)?

**Pull request merged**
