### PR TITLE
Update CIBC

### LINKED ISSUE #7049: Update CIBC
### Site name

https://www.cibc.com/en/personal-banking.html

### Site URL

https://www.cibc.com/en/personal-banking.html

### Update reason

It now supports 2FA.

### Additional information

CIBC now supports 2FA

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### PR DESCRIPTION
**Pull request by Photonicsguy**
CIBC also allows use of the CIBC app for authentication

### CODE REVIEW

**Comment by jpayoung** [comment]
Would it be more precise to indicate the custom-software as "CIBC App Push Notification", since at this time it does not allow generation of TOTP in-app?

**Comment by jpayoung** [comment]
This PR duplicates some changes included in #7005.
That pull request also indicates CIBC no longer uses email 2sv, so is more complete & precise.
Should this pull request be deleted?

**Comment by jpayoung** [comment]
Duplicate of #7005

That pull request additionally indicates CIBC no longer uses email 2sv, so is more complete & precise. Should this pull request be deleted?

**Comment by jpayoung** [comment]
Duplicate of #7005

**Comment by jpayoung** [comment]
#7005 additionally indicates CIBC no longer uses email 2fa, so is more complete & precise. Should this PR be closed?

**Comment by jpayoung** [comment]
Duplicate of #7005

**Comment by jpayoung** [comment]
#7005 additionally indicates CIBC no longer uses email 2fa, so its changes are more complete & precise. Should this pull request be closed?

**Comment by Carlgo11** [comment]
@jpayoung the author of #7005 provides no proof that email 2FA no longer is support so I'm unable to approve that PR until she does.

**Review by Carlgo11 — APPROVED** [review]

**Comment by jpayoung** [comment]
Thanks @Carlgo11. I've added notes in #7005.

As for #6993, I believe this pull request should be reverted (or overridden by #7005). I’ve outlined a couple reasons below: 

1. It adds less precise language about CIBC’s mobile app:
    - #6993 lists `“CIBC App”`
    - #7005 lists `“CIBC App Push Notification”`
This distinction emphasizes the delivery of codes _only_ through push notification — users cannot retrieve time-based codes in the app.
2. Both #6993 and #7005 include out-of-date documentation.

Let me know what I should do! I’m happy to help where I can 😊

**Comment by Carlgo11** [comment]
@jpayoung thanks for your comments.
Reverting commits is not something we do as it messes up the timeline. If you see something wrong you can either make a pull request or a new issue where you provide the new data.
Furthermore the author of #7005 seemed to be inactive so the requested changes couldn’t be made leaving the PR to be closed in favor of this PR.

Regarding your outlined remarks:

1. We normally list the app and not the technology itself. As such `CIBC App` is correct.

2. If you’ve found a better documentation page you can update the documentation link by creating a new pull request.

**Comment by jpayoung** [comment]
Thanks @Carlgo11, totally makes sense. I had added documentation in comments and changes suggestions in the comments of #7005; would you prefer I work there or create a new PR?

**Comment by jpayoung** [comment]
Thanks @Carlgo11, appreciate the reply and totally makes sense (I'm not trying to be a hassle).

I'd added documentation in comments and changes suggestions in #7005, but I forgot this could cause a merge conflict. I've created a new PR: #7027

**Pull request merged**
