### PR TITLE
Use absolute paths for notes

### PR DESCRIPTION
**Pull request by ApCoder123**
Currently, any entries with a `/notes` page for their documentation use the relative path. From what I can tell (#894), this was to help test locally. However, currently, these relative paths are appearing in the API files, which is probably not the desired behaviour.

### CODE REVIEW

**Comment by ApCoder123** [comment]
Had to add an http `url` field to `internetbs.net.json`, as the curl test kept failing to reach `https://internetbs.net` with a 504 Gateway Timeout error.

**Comment by Carlgo11** [comment]
@ApCoder123 Did you figure out what happened?
I only get 504 when the -I flag is set.

**Comment by ApCoder123** [comment]
@Carlgo11 
I think their server was rejecting the `HEAD` requests that are sent with the `-I` flag. 

An alternative command to print headers without using the `HEAD` HTTP verb, but still supress the body could be:
`curl -sS -D - -o /dev/null https://url.com`

Edit: The original command in this comment was incorrect.

**Comment by Carlgo11** [comment]
The curl output may not even be needed. As long as it can connect to the site and doesn't get a 4xx or 5xx status code.

**Comment by phallobst** [comment]
Why would the relative paths not be the desired behaviour? By definition they would use the URL of the API file as the base, i.e. `https://2fa.directory/api/v3/all.json` + `/notes/chase/` = `https://2fa.directory/notes/chase/`. The same applies to `http://localhost:4000` accordingly.

Prefixing the URLs with the main domain definitely breaks testing, with no apparent advantage (at least for me).

**Comment by ApCoder123** [comment]
My thoughts were that when receiving the API data e.g.
```JSON
["Internet.bs",{"domain":"internetbs.net","tfa":["totp"],"documentation":"/notes/internetbs/","keywords":["domains"]}]
```
users may not be expecting to receive a relative path, so probably won't consider appending the domain to beginning. 

I noticed this, as the "Missing 2FA" notification for internet.bs doesn't show up in 1Password and [Bitwarden's implementation](https://github.com/bitwarden/web/blob/master/src/app/tools/inactive-two-factor-report.component.ts) doesn't append 2fa.directory to the beginning either.

I'm open to keeping the relative paths how they are, although it may be useful to add a note about this to the api.md documentation.

**Comment by Carlgo11** [comment]
I remember someone created an issue a couple of years ago complaining that the doc tags had relative paths instead of absolute paths and it messing up his program. We fixed it for the time being but it seems like the latest revision of the project removed that fix.

**Review by Carlgo11 — APPROVED** [review]

**Comment by phallobst** [comment]
`tests/validate-urls.rb` could/should be adjusted as well.

**Review by phallobst — APPROVED** [review]

**Pull request merged**
