### PR TITLE
Added site: Domains4Bitcoins.com [Domains]

### PR DESCRIPTION
**Pull request by rieven5**
As per title, added registrar Domains4Bitcoins.com to Domains section

### CODE REVIEW

**Comment by mxxcon** [comment]
I'm leaning against listing this site. It looks extremely generic, borderline shady. I couldn't find any contact information on who they are..

**Comment by rieven5** [comment]
They do look generic but have been around since 2011. A lot of people use them since they have the lowest price for .com renewals

**Comment by stephengroat** [comment]
I talked with a friend who uses the site and says it "legit"

**Comment by Carlgo11** [comment]
Here's a compressed version of your image. Please use that instead.
domains4bitcoins

**Comment by rieven5** [comment]
Thank you, I uploaded the compressed version.

**Comment by Carlgo11** [comment]
Merge conflict :person_frowning:

**Review by Carlgo11 — APPROVED** [review]
@stephengroat you can merge this when you've approved the PR again

**Comment by stephengroat** [comment]
New issue
image
image
image

**Pull request merged**
