### PR TITLE
Add Code Climate

### PR DESCRIPTION
**Pull request by calavera**

### CODE REVIEW

**Comment by JacobNinja** [comment]
:cake:

**Comment by Carlgo11** [comment]
1. logo <b>MUST</b> be 32x32px
2. No doc?

**Comment by jdavis** [comment]
Thanks for the cake, @JacobNinja. +1 to what @Carlgo11 said.

**Comment by jdavis** [comment]
I just re-ran Travis and it failed. Beautiful. @ilyakatz it works great.

**Comment by thoughtmerchant** [comment]
cc-avatar-small

Code Climate image! Here is an SVG that is even better if you want to use it: https://www.dropbox.com/s/lqz1i09qcb7eueq/code-climate-avatar.svg?dl=0

**Comment by calavera** [comment]
Adding it to the PR, thanks @thoughtmerchant.

@jdavis is the doc mandatory? We use authy, which is pretty straight forward to use.

**Comment by Carlgo11** [comment]
@calavera It's not mandatory but strongly recommended

**Comment by jamcat22** [comment]
:+1:

**Comment by mxxcon** [comment]
@calavera doc link is good so that users can quickly check how to enable it.
(and for us to see a confirmation that it's really there. :smiley: )

**Pull request merged**
