### PR TITLE
Add Sentry

### PR DESCRIPTION
**Pull request by mitsuhiko**
This adds getsentry.com

### CODE REVIEW

**Comment by Carlgo11** [comment]
No documentation link?

**Comment by mitsuhiko** [comment]
@Carlgo11 there is no documentation for 2FA other than a blog post that announces it. It's embedded in the account settings.

**Comment by Carlgo11** [comment]
Okay I just went and verified it myself. Seems good to go.
Thank you for your contribution @mitsuhiko! :smile:

**Comment by mitsuhiko** [comment]
\o/

**Comment by Carlgo11** [comment]
ヘ(^o^ヘ) ヾ(-_\- )ゞ (ノ^_^)ノ  (o´･_･)っ 〜(￣△￣〜)

**Comment by jamcat22** [comment]
I'd say we should link to their [blog post](https://blog.getsentry.com/2016/06/22/introducing-2fa.html) since we do that for a few other sites, it's very close to an official documentation, and it has instructions for enabling 2FA.

**Comment by RichJeanes** [comment]
@mitsuhiko Could you add that doc link to the blog post as well as resolve the merge conflict for us? I love that they support U2F (Yay future tech!) and would like to get them listed. Thanks!

**Pull request closed without merging**
