### PR TITLE
Add Gitea

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by kmpoppe** [comment]
Hello @simon04, the `doc:` URL looks incomplete.

// Kai

**Comment by simon04** [comment]
Hi @kmpoppe, thanks for your review and spotting the invalid URL. I fixed it.

**Comment by kmpoppe** [comment]
Alexa rank on 01.10.2019 04:43 UTC: [210,319](https://www.alexa.com/siteinfo/gitea.io)

**Comment by Carlgo11** [comment]
Unfortunately, as the site is ranked above 200K on [Alexa](https://www.alexa.com/siteinfo) it doesn't meet our guidelines of [new site additions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines).

Sorry for the inconvenience.

**Pull request closed without merging**
