### PR TITLE
Add Andrews Federal Credit Union [Banking]

### PR DESCRIPTION
**Pull request by umeditor**

### CODE REVIEW

**Comment by stephengroat** [comment]
Try using https://tinypng.com to compress the image.

**Comment by Jawshy** [comment]
@umeditor, I think this image would be better because it lacks text which is hard to read at such low resolutions. 
andrewsfederalcu

They also have a [Facebook page](https://www.facebook.com/AndrewsFederal). Would you like to add that as well? 

``` ruby
      facebook: AndrewsFederal
```

**Comment by umeditor** [comment]
I added the Facebook info and ran the image through https://tinypng.com.

**Comment by umeditor** [comment]
…and add the image without text.

**Comment by fpigerre** [comment]
Thanks for the pull request @umeditor! :+1:

**Pull request merged**
