### PR TITLE
Add Tsohost

### PR DESCRIPTION
**Pull request by IanOliver**
Daily do not support 2FA, so I'm adding them as such.

### CODE REVIEW

**Review by brycx — COMMENTED** [review]
It seems Daily has changed to Tsohost. The current url redirects to [Tsohost's site](https://www.tsohost.com/welcome/daily). Daily's Facebook seems to be down but their Twitter still up. Here's Tsohost's [Facebook](https://twitter.com/tsohost)/[Twitter](https://www.facebook.com/tsohost/).

Would you like to add Tsohost instead of Daily?

**Comment by IanOliver** [comment]
That is correct, they have recently been absorbed into Tsohost. Tsohost also do not support 2FA so I would like to add them instead - shall I create them afresh?

**Comment by brycx** [comment]
You can just modify this PR, I'll just change it's name.

**Comment by IanOliver** [comment]
Thank you. The details have now been changed from Daily to Tsohost. Looks like I need to submit a new PR for the image?

**Comment by brycx** [comment]
Can't you just delete daily.png and add another picture with a commit?

**Comment by IanOliver** [comment]
Must admit, I can't see a way to do that from here I'm afraid, sorry.

**Comment by mxxcon** [comment]
Simply commit a new logo with name of `tsohost.png` and delete the old one.

**Comment by IanOliver** [comment]
Believe I've submitted the addition of the Tsohost icon and removal of the Daily icon correctly. Let me know if there's anything else needed, thanks :)

**Comment by brycx** [comment]
@IanOliver For future PR's, you can check what is wrong, by looking at the Travis build check under "Details". If you take a look, it says 
```
<------------ ERROR ------------>
1. _data/domains.yml is not alphabetized by name
rake aborted!
```
So the entries must be in alphabetic ordering :)

**Comment by brycx** [comment]
@IanOliver Is there a specific reason you put this into `domains`? As far as I can tell Tsohost also provides hosting. Maybe the `hosting` category would be a better fit?

**Comment by IanOliver** [comment]
@brycx Ah, I see - thanks :)

The original listing for Daily was under domains, since they were more registrars than hosts I believe. But you're correct - Tsohost is probably more correct under hosting.

**Comment by brycx** [comment]
@IanOliver Could you move it to that?

**Review by mxxcon — APPROVED** [review]

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Move to hosting as requested in https://github.com/2factorauth/twofactorauth/pull/2928#issuecomment-403844812

**Comment by Carlgo11** [comment]
Closing due to inactivity.

**Pull request closed without merging**
