### PR TITLE
Added SchoolsFirst and Union Bank

### PR DESCRIPTION
**Pull request by stevenandres**
Sorry for my ignorance -- I used to be able to upload non-text (binaries) to a pull request from the Web UI but now it appears that I cannot. I have added two banks to the _data/finance.yaml but the images I cannot seem to upload. So I am including them as attachments to this comment and I hope the owner of the repo is smarter than I am about merging them. Sorry! I tried!

schoolsfirst

unionbank

### CODE REVIEW

**Comment by Carlgo11** [comment]
@stevenandres Uploading images via GitHub have never worked. You need to use a git client.

Also, those images are too big. I suggest you compress them using https://tinypng.com/

**Comment by Carlgo11** [comment]
1. Credit Unions and banks should be in banking.
2. Add twitter handles for sites. `@SchoolsFirstFCU` and `@UnionBank`

**Comment by stevenandres** [comment]
Thanks for the feedback. Didn't know about tinypng. And don't have a git client setup. I just wanted to make a small contribution to a site that I love and refer people to many times. Setting up a whole git or jekyll environment isn't what I was looking to do. Shame GitHub doesn't just allow binary uploads into the Web UI.

**Comment by Carlgo11** [comment]
No worries @stevenandres, thanks for contributing to our repo.
You don't need to set up jekyll for adding images to your PR. Just install the GitHub client for your OS.
https://desktop.github.com/

I recommend looking at our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_SITE) for help. It's a bit easier to understand than the CONTRIBUTING.md file.

Don't hesitate to ask if you need any further help!

//Carl

**Comment by mxxcon** [comment]
@stevenandres accept my pullrequest in your repo and it should show up here.

**Comment by stevenandres** [comment]
I accepted the pull. Hopefully that showed up back here. Thanks for the education!

**Pull request merged**
