### PR TITLE
Added 4 new sites

### PR DESCRIPTION
**Pull request by whatinthenameofgod**
Banking: Partners FCU
Gaming: Xbox Live
Social: Pocket
Security: AirVPN

### CODE REVIEW

**Comment by whatinthenameofgod** [comment]
Okay, this was my first time submitting a pull request. What did I do wrong? Want to learn from this.

**Comment by mxxcon** [comment]
In `banking.yml` spacing is critical.
Overall, please make separate pull requests for each site so that each one can reviewed independently.

**Comment by jamcat22** [comment]
Hello @whatinthenameofgod!

Your images were a little big, so I compressed them using [tinypng.com](https://tinypng.com). I also changed the Pocket image, as this one should be of better quality.
airvpn
partners
pocket
xbox

Thanks!

**Comment by whatinthenameofgod** [comment]
Got it! Thanks for the feedback! Will absolutely submit one per PR going forward. And I thought I compressed them, but I'll make sure to do a better job.

**Comment by jamcat22** [comment]
You need to fix the spacing in `banking.yml`, and change the pictures to the ones I have posted above.

**Comment by whatinthenameofgod** [comment]
I'll just close this and try again. I'm slowly figuring out what I'm doing... Saved your pngs. Thank you!

**Comment by jamcat22** [comment]
No prob! What matters is that you're taking the time to learn! :smile:

**Pull request closed without merging**
