### PR TITLE
Add versio.nl

### PR DESCRIPTION
**Pull request by jdeluyck**
Versio.nl (dutch hosting company) supports 2FA through OTP. Works fine with eg. Google Authenticator or Yubioath.

### CODE REVIEW

**Review by Jawshy — DISMISSED** [review]
Hi, @jdeluyck. There should be no more than one site added per pull request. Please remove the WordPress entry.

**Comment by jdeluyck** [comment]
Yeah, my mistake. Gotten extremely rusty with git.

**Comment by Jawshy** [comment]
Thanks.

**Review by mxxcon — APPROVED** [review]
I'm not familiar with NL's hosting market to judge how big/significant this site is and if it's worth listing it here. But semantically this PR is 👍.

**Pull request merged**
