### PR TITLE
Add Amundi EE

### PR DESCRIPTION
**Pull request by nagromc**
Amundi has multiple websites:
- The general one: https://www.amundi.com
    [Logo (`apple-touch-icon`)](https://static.amundi.com/amundi/extension/ez_front_builds/design/amundi_country_build/images/apple-touch-icon-180x180.png) from this website.
- A specific one (the purpose of this PR): https://www.amundi-ee.com
    I took the logo from the [Google play page](https://play.google.com/store/apps/details?id=com.amundi_ee.monEpargne). But the official website gives [another icon (`apple-touch-icon`)](https://static.amundi.com/extension/aits_ine_ext_amundi_ee/design/amundi_ee_front_design/images/apple-touch-icon-144.png).

So I took the logo that matched the most, but I can change to the [`apple-touch-icon`](https://static.amundi.com/extension/aits_ine_ext_amundi_ee/design/amundi_ee_front_design/images/apple-touch-icon-144.png) if you find it more readable.

### CODE REVIEW

**Comment by Carlgo11** [comment]
I'd say the first apple-touch-icon looks better when resized down to 32x32px.
👍

**Comment by nagromc** [comment]
Done.

Note that it is **not** the logo for the specific Amundi **EE**, but the one form the institutional and general Amundi website.

Also, I just realized there are two categories related to money: Banking, and Finance. I'm not sure to be able to make the difference between those two families. Any explanation?

**Review by Carlgo11 — DISMISSED** [review]

**Comment by mxxcon** [comment]
Finance category is more for money management sites.

**Comment by nagromc** [comment]
Well, maybe _finance_ would be more suitable.

In France, if the company had good results during the past period, its employees will earn "bonus money". This money is blocked on a special account for five years. The counterpart is the interest rate is higher that common financial products. Amundi EE (_EE_ stands for _**É**pargne **E**ntreprise_, literally _Company Saving_) allows employees to manage these special accounts.

Should I move Amundi EE to _finance_?

**Comment by Carlgo11** [comment]
Yes, move it to finance.

**Review by Carlgo11 — APPROVED** [review]

**Review by kmpoppe — APPROVED** [review]

**Pull request merged**
