### PR TITLE
Commonwealth Bank of Australia

### PR DESCRIPTION
**Pull request by adeishs**
Adding Commonwealth Bank of Australia.

### CODE REVIEW

**Comment by mxxcon** [comment]
Why is URL netbank.com.au?

**Comment by fpigerre** [comment]
In this case, the [https://www.commbank.com.au](https://commbank.com.au/) website might be a better fit.

**Comment by adeishs** [comment]
Alright. https://www.commbank.com.au/ it is. Done. Committed.

**Comment by fpigerre** [comment]
Thanks for the pull request @adeishs! :+1:

**Comment by adeishs** [comment]
You’re welcome!

**Pull request merged**
