### PR TITLE
Add Google Domains, TIAA-CREF, and edit Paypal exceptions

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by jamcat22** [comment]
PayPal 2FA does work with mobile apps, it's just a bit complicated. It only works when you use SMS 2FA. It might be better if we remove that part of the Pull Request for now, and I can explain it more (including make docs for it) in another PR.

**Comment by stephengroat** [comment]
I agree that their is a Paypal workaround (disabling, re-enabling, etc.), but right now it's definitely not officially supported.

Since this is the message that people get when trying to login, maybe that detail should be included? I only say it because it's such a pain to get it to work and it still doesn't work inside the mobile eBay app, even with the work around.

screenshot_2015-01-20-23-22-15

Great website by the way, I send everyone there to look to see which services are supported! thanks for all the work

**Comment by jamcat22** [comment]
I never said it was a workaround. The iPhone PayPal and eBay apps let you login with 2FA.

When you use hardware or software 2FA to login to the PayPal iPhone app (which the app doesn't support):
image

When you use SMS 2FA to login to the PayPal iPhone app (which the app does support):
image

When you use any type of 2FA to login to the eBay iPhone app:
image

The eBay Android app doesn't support any type of 2FA (even if you append the token).

It seems the PayPal Android app also doesn't support any type of 2FA.

I think we should not solve this in this PR. I would like to create a separate one to solve this and #580 (about how vague PayPal docs are).

This way, we will not mix up adding sites with making huge changes to existing sites.

Also, in the future please give each site its own PR.

**Comment by stephengroat** [comment]
Sorry, didn't know. I'll get them separated out today. Thanks,

Stephen

**Comment by jamcat22** [comment]
It's all good! Thanks!

**Comment by stephengroat** [comment]
Is this going to be added or should i pull it? Thanks!

Stephen

**Comment by Carlgo11** [comment]
@stephengroat Please have patience. We're all doing this on our spare time.

**Pull request merged**
