### PR TITLE
Allow SVG icons

### PR DESCRIPTION
**Pull request by Carlgo11**
And I might have cleaned up a few methods as well :sweat_smile:

### CODE REVIEW

**Comment by Carlgo11** [comment]
All done on my end. Surprisingly it looks like the mobile view doesn't use webms at all :thinking: 
Probably something to look further into

**Comment by phallobst** [comment]
The `CONTRIBUTING.md` file should be updated accordingly as well.

Edit: Maybe point to https://vecta.io/nano or a similar service.

**Comment by phallobst** [comment]
Also, is it still useful to have SVG icons cropped by the circle? For bitmap icons, it was easily possible to shrink them a bit (i.e. have a small transparent border), so no vital parts were cut off. This might not be so easy with SVG. (To be honest, I was never a fan of that cropping anyway...)

**Comment by Carlgo11** [comment]
> Also, is it still useful to have SVG icons cropped by the circle? For bitmap icons, it was easily possible to shrink them a bit (i.e. have a small transparent border), so no vital parts were cut off. This might not be so easy with SVG. (To be honest, I was never a fan of that cropping anyway...)

@2factorauth/collaborators thoughts?

**Comment by Carlgo11** [comment]
I think both the collaborator.md and possible allowance of square icons might be better fit for a new separate issue & PR.

**Comment by phallobst** [comment]
I just realized that you can set `no_img_border: true` for an entry to get rid of the cropping. You live and learn.

**Comment by Carlgo11** [comment]
@phallobst is that something I implemented? 👀 
Because it sounds familiar.

**Comment by phallobst** [comment]
Yep, it was part of https://github.com/2factorauth/twofactorauth/commit/84549c8b

**Review by phallobst — DISMISSED** [review]

**Comment by phallobst** [comment]
The image dimension check (32x32) does not apply to vector images, so it should be skipped for these.

Also, the file size limit of 2.5K will not be met for many of the more detailed icons. For example, the left part of the "Simple" bank logo alone is almost 10K even after passing it through https://vecta.io/nano...
[Official logo](https://www.simple.com/assets/images/simple-logo.svg), [Cropped and optimized](https://raw.githubusercontent.com/phallobst/resterampe/4d8ef4544d77ad1e0a42e9cde2ca53b91c197fba/simple.svg)

**Comment by phallobst** [comment]
@Carlgo11 The latest commit adds more SVG handling in the verify script. This is what I used in #5057 as well.

**Review by phallobst — APPROVED** [review]

**Review by dsoegijono — APPROVED** [review]

**Pull request merged**
