### PR TITLE
Update Home Depot

### PR DESCRIPTION
**Pull request by betsythefc**
Added sms auth to Home Depot, though they do not have any documentation.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Thanks for the pull request!

Could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
screenshot

**Comment by betsythefc** [comment]
Sure!
Screen Shot 2020-09-16 at 10 00 41

**Comment by phallobst** [comment]
@betsythefc I removed that screenshot since your mobile number was visible. If you want to re-upload, make sure it is censored.

**Comment by betsythefc** [comment]
@phallobst Ugh, thanks. I missed that. Here is the new one.
Screen Shot 2020-09-16 at 10 00 41

**Review by Carlgo11 — APPROVED** [review]

**Review by phallobst — APPROVED** [review]

**Pull request merged**
