### PR TITLE
Add Office Depot

### PR DESCRIPTION
**Pull request by Rfosu2k2**
Office Depot does not currently support 2FA.

### CODE REVIEW

**Comment by kmpoppe** [comment]
To me, it feels like they've got bigger problems than not supporting 2fa:
grafik

**Comment by phallobst** [comment]
They seem to chicken out on GDPR regulations and block visitors from Europe. Accessing the site via VPN works.

**Comment by Carlgo11** [comment]
For me it doesn’t work with a VPN but it does without 😅

**Comment by Rfosu2k2** [comment]
I don't know if they operate outside of North America, but they have many stores in each major city in the United States.  They are a direct competitor to www.staples.com

Alexa rank 3,382 https://www.alexa.com/siteinfo/officedepot.com

**Comment by kmpoppe** [comment]
It's their prerogative to be too lazy to make it work in Europe, I just can't review anything then 😅

**Comment by Rfosu2k2** [comment]
That's ok, I imagine there are a few others that will have access that can review.  Thanks for trying to circumvent their regional website for the review.

**Review by Carlgo11 — APPROVED** [review]

**Review by kmpoppe — APPROVED** [review]

**Pull request merged**
