### PR TITLE
Add Basic Attention Token

### PR DESCRIPTION
**Pull request by jonade**

### CODE REVIEW

**Review by phallobst — CHANGES_REQUESTED** [review]
The "Cryptocurrencies" category is intended to list trading platforms. This website does not fit in there. Please move it to "Other".

**Review by phallobst — COMMENTED** [review]
Should this be called "Brave Rewards" instead? I'm not quite sure.

**Comment by jamcat22** [comment]
https://creators.brave.com/ appears to go to the same page.

If we wanted to rename the entry to Brave Rewards we'd probably want to change the link as well.

**Comment by jonade** [comment]
Yeah, there are two URLs which can be used as an entry point, the second is mentioned by @jamcat22 . Both domains support TOTP/U2F, but ultimately they end up at the domain in the PR.

**Comment by phallobst** [comment]
Okay, let's leave it as it is then.

**Review by phallobst — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
