### PR TITLE
Update IRS to include SMS and software 2FA

### LINKED ISSUE #3164: IRS supports two-factor auth
https://www.irs.gov/newsroom/irs-launches-more-rigorous-eauthentication-process-and-get-transcript-online: the U.S. internal revenue service's "get transcript" site now requires two-factor auth to sign in.

Supported methods:
- SMS codes
- security code from phone app they provide (IRS2Go: https://www.irs.gov/newsroom/irs2goapp)

Sadly, they don't appear to support U2F.

### PR DESCRIPTION
**Pull request by brycx**
Fixes #3164.

### CODE REVIEW

**Comment by Carlgo11** [comment]
From what I can tell it only protects certain pages. Is this correct? (*Paging any 'mericans*)

**Comment by mxxcon** [comment]
I don't have account with them, but it does look like only some pages are protected

> Currently, the Secure Access authentication process applies to Get Transcript Online, Get an IP PIN, e-Services and online tax account.

But then how does that work? It asks for login multiple times? 🤔

**Comment by Carlgo11** [comment]
If only certain pages are protected, does that fall under two factor **authorization** then?

**Comment by brycx** [comment]
Maybe @jrn from #3164 can shed some light upon this?

**Comment by jrn** [comment]
The IRS is a large agency and probably they have multiple services online.

The only one that matters is Get Transcript, which is protected by two-factor.

**Review by mxxcon — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
