### PR TITLE
Add GMX and Mail.com

### PR DESCRIPTION
**Pull request by dsoegijono**
Add GMX, Mail.com, MailChimp

### CODE REVIEW

**Comment by dsoegijono** [comment]
I think this covers #273

**Comment by jdavis** [comment]
MailChimp is in the Communication section as is Mailgun and Sendloop. Since they aren't "email" clients, we added them there.

**Comment by dsoegijono** [comment]
@jdavis Oops! I've removed it. Are the other two good?

**Comment by jdavis** [comment]
It looks good to me. I've never used either service though so unless they use "undercover" 2FA that doesn't have documentation (which is unlikely), then I think the values of `No` are good.

**Comment by jamcat22** [comment]
I have email accounts at gmx and mail.com (and almost every other service to check for 2FA) and they do not have any form of 2FA.

**Comment by jdavis** [comment]
Cool, thanks for the info, @jamcat22. This looks good.

**Pull request merged**
