### PR TITLE
New service provider Cognalys, Inc.

### PR DESCRIPTION
**Pull request by anishmenon**
Mobile number verification via missed call based two factor authentication

https://github.com/anishmenon/twofactorauth/commit/d07f67e8e51b2ace2164a93a6d5b21d49934f531

### CODE REVIEW

**Comment by anishmenon** [comment]
Please tell me the reason of closing ...  @Carlgo11

**Comment by jdavis** [comment]
@anishmenon Because you are making a PR with commits that are already on mainline. The list of 100 commits that you see above these comments should be indication enough that your PR is wrong.

**Comment by anishmenon** [comment]
@jdavis . I'm just gonna  commit new provider.yml and its logo . So i don't wanna PR after committing right ?

**Comment by jdavis** [comment]
@anishmenon I'm not quite sure what you mean, but checkout [GitHub's Help](https://help.github.com/) for details on using GitHub. It has an article on [Pull Requests](https://help.github.com/articles/using-pull-requests/) that might help.

**Pull request closed without merging**
