### PR TITLE
Add Capital One and LastPass

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by smholloway** [comment]
There are now four pull requests that add LastPass: #161, #218, #230 (this PR), and #234 . This one seems to be the most complete with five of [LastPass' many options](https://helpdesk.lastpass.com/security-options/multifactor-authentication-options/).

**Comment by mpdavis** [comment]
I like this one as well.  @danf Can you update the images to be 32x32 and I will get this merged in?

**Comment by ghost** [comment]
I pulled the 32x32 icon from the LastPass Chrome extension.

**Comment by zach-taylor** [comment]
@danf capitalone should be 32x32 as well

**Pull request closed without merging**
