### PR TITLE
Add Boxcryptor

### PR DESCRIPTION
**Pull request by minorMismatch**

### CODE REVIEW

**Review by mxxcon — CHANGES_REQUESTED** [review]
Edit this branch to remove MLP changes. 😃

**Review by mxxcon — APPROVED** [review]

**Comment by minorMismatch** [comment]
Sorry, as you might have guessed I only used Git locally up until now :-) Thanks for your patience.

**Review by stephengroat — APPROVED** [review]
thanks for the pr @minorMismatch

**Comment by wisco24** [comment]
This PR is causing the Travis-CI process to fail.   PR #2715 fixes it.    E-mail must be a boolean value if TFA is supported over e-mail.

**Pull request merged**
