### PR TITLE
Add itch.io in gaming section

### PR DESCRIPTION
**Pull request by fasterthanlime**
We've recently deployed 2fa (using TOTP) :shipit: 

Announcement: http://blog.itch.io/post/120372786049/two-factor-authentication-now-available

### CODE REVIEW

**Comment by fasterthanlime** [comment]
Just noticed that the 'twitter' field is unnecessary for sites that do support tfa. Feel free to remove it!

Also, `jekyll serve` looks good on my side, and `rake verify` reports no errors.

**Comment by RichJeanes** [comment]
Correct, the Twitter tag is not needed. If you remove it and make another commit on the same branch, it will show up here automatically.
Also, a helpful hint for the future, making changes on a branch of your fork, instead of the master, can help prevent merge conflicts and other issues. :+1:

**Comment by fasterthanlime** [comment]
> Correct, the Twitter tag is not needed. If you remove it and make another commit on the same branch, it will show up here automatically.

Done!

> Also, a helpful hint for the future, making changes on a branch of your fork, instead of the master, can help prevent merge conflicts and other issues.

Noted! That's what Github's inline edit thing does, in fact.. curious to read more about that if you know of a doc somewhere that summarizes it.

**Comment by mxxcon** [comment]
This is just general workflow we recommend. It's somewhat similar to git-flow where master branch is production-ready code and each feature/bugfix/patch gets worked on in a separate branch. Then once its ready, you merge it back into master through pull-requests.
It's not a requirement, but very helpful when you are working on multiple things at once; you can cleanly switch between branches w/o screwing up your master branch.

**Pull request merged**
