### PR TITLE
Add OSDE (Argentina)

### PR DESCRIPTION
**Pull request by fainpablo**
This is one of the private health insurance leaders in Argentina. Through their website you can update or cancel your medical coverage, schedule medical appointments, access results of your medical studies, etc. Through their mobile app you can view your credential, which you can use to access medical appointments and get pharmacy discounts.

### CODE REVIEW

**Comment by phallobst** [comment]
Currently, health insurance companies go into the "Finance" category. I'm not sure why, but it is as it is.

**Comment by fainpablo** [comment]
Well... If you take a look at how much I pay every month to OSDE, then it begins to make sense to classify them as "Finance" :)

How about "Maccabi Healthcare Services" for example? Services offered by OSDE and Swiss Medical (#4649) are pretty similar. It's a network of doctors, pharmacies, and urgent care centers that provide services to OSDE, Swiss Medical, and others. You pay to your health insurance company every month, and -depending on the plan- you may have to pay an extra during the appointment or nothing at all.

What do you think @phallobst? Should I move them to Finance anyway

**Comment by phallobst** [comment]
If the website offers more services than just handling the financial aspects of the health insurance, it should go to _Health_. (The same applies to "Swiss Medical" as well, I guess.)

In my opinion, even health insurance companies should go there, but I am not to decide.

**Comment by fainpablo** [comment]
Yup, agreed. This is the case with OSDE as well as "Swiss Medical".

**Review by phallobst — DISMISSED** [review]

**Comment by phallobst** [comment]
Please merge the master branch into yours.

**Pull request closed without merging**
