### PR TITLE
Added Typetalk

### PR DESCRIPTION
**Pull request by gillax**

### CODE REVIEW

**Comment by gillax** [comment]
[Nulab](https://nulab.com) is already there.

**Comment by 40504** [comment]
please reopen this PR

**Comment by 40504** [comment]
I found similar service like "nulab", -> "intuit" have 3 services that are listed in "twofactorauth"

**Comment by phallobst** [comment]
Please rebase your branch to the current master.

**Comment by Carlgo11** [comment]
Unfortunately, as the site is ranked above 200K on [Alexa](https://www.alexa.com/siteinfo) it doesn't meet our guidelines of [new site additions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines).

Sorry for the inconvenience.

**Pull request closed without merging**
