### PR TITLE
Removed e-mail that was causing Travis-CI to fail.

### PR DESCRIPTION
**Pull request by wisco24**

### CODE REVIEW

**Comment by mxxcon** [comment]
I think this might be a wrong way to fix this? 🤔
I think we might have wrong logic in yaml validation...

**Comment by wisco24** [comment]
I think he intended to provide the e-mail to allow people to e-mail the company to request TFA be added like they can with Twitter/Facebook, but the current layout, uses it if a company does have e-mail TFA.

**Comment by wisco24** [comment]
found the issue.  Will resubmit the PR in a second.

**Review by stephengroat — APPROVED** [review]
thanks for the help

**Pull request merged**
