### PR TITLE
Update schwab 2fa instructions

### PR DESCRIPTION
**Pull request by DarkDimius**
There is a faster and more straightforward way to set it up now.

### CODE REVIEW

**Comment by mxxcon** [comment]
If it's so straight forward, do we even need a separate page for this? @2factorauth/collaborators

**Comment by kenman345** [comment]
Its so easy the link to Schwabs notes isnt even active right now. Take a look: https://twofactorauth.org/notes/


I have it added back in with the revision to the notes pages in PR #3242

**Comment by brycx** [comment]
@mxxcon Based on the commit and what @kenman345 said, I'd say toss it.

**Comment by kenman345** [comment]
@brycx What/if anything at all, shall I change about my PR #3242?

**Comment by brycx** [comment]
@kenman345 I'd say drop Schwab completely but before doing that, it would be nice to hear from some more members too. Also, I'll try to find time to take a closer look at that PR (if @psgs does not make it before me).

**Comment by kenman345** [comment]
So the great thing about what I did was basically made it dynamic. For any
generated page that’s a notes template it adds in a link to it. So for my
PR to remove the Schwab instructions I just remove the page and update the
docs entry on Schwab to be the url to the new/easier instructions.

I wanted to prevent us being in a state where we have a page someone worked
hard on and it doesn’t even show on the site. It’s also easier to maintain
this way.

**Comment by dsoegijono** [comment]
Since it's pretty straight-forward, I'd prefer removing the separate notes page. However, I couldn't find any doc from their website. There's [this one](https://www.schwab.com/public/schwab/nn/public-security-tips-popup.html) (point 2) that says to call them.

**Comment by DarkDimius** [comment]
Yes, I didn't find documentation on this online either.
I've got it by calling them.

**Comment by mxxcon** [comment]
@DarkDimius Perhaps update this PR to just remove this notes page completely and update the existing entry with exceptions text?

**Comment by kmpoppe** [comment]
@DarkDimius I'm setting this PR to inactive.
If you still have an account with Schwab, would you please be so kind as to
- Take screenshots of the process on how to activate it now
- Close this PR
- Add a new PR with removing the documentation from the investing.yml and providing an exception-text if necessary

Thanks!

**Comment by j2xl** [comment]
You can delete the paragraph following the numbered list about changing your password to be 8 characters or less. That's no longer appropriate.

**Comment by j2xl** [comment]
Drop-down menu containing "Security Center"
image

**Comment by j2xl** [comment]
Two-step verification setup pane
image

**Comment by j2xl** [comment]
Credential manager (redacted)
image

**Comment by j2xl** [comment]
Add security token screen (redacted)
image

**Review by kmpoppe — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
Better late than never?
The changes are live now. Thanks for the PR @DarkDimius and sorry about the waiting time 😅

**Pull request merged**
