### PR TITLE
Update o2switch

### PR DESCRIPTION
**Pull request by GeekCornerGH**

### CODE REVIEW

**Comment by hkamran80** [comment]
Do you have a link to documentation? Alternatively, please attach some screenshots of the 2FA setup process, login process, or management screen. Please blur or crop out any personal or sensitive information.

**Comment by Carlgo11** [comment]
As the requested changes haven't been resolved yet I'm going to label this PR as inactive.
> [!Warning]
> Unless there's activity within the next 7 days I'll close the PR.

**Comment by GeekCornerGH** [comment]
> Do you have a link to documentation? Alternatively, please attach some screenshots of the 2FA setup process, login process, or management screen. Please blur or crop out any personal or sensitive information.

Even better, there is the official testing account
https://pomme.o2switch:2083
user: o2cpanel
pass: testezmoi

Login process:
image

**Comment by hkamran80** [comment]
I can't access that.

**Comment by Carlgo11** [comment]
I think you forgot the TLD as `pomme.o2switch` isn't a valid FQDN.

**Review by Carlgo11 — APPROVED** [review]
Thank you for the pull request.
Your contribution will be visible in around 10 minutes. Sometimes, it takes longer to show up due to [server and browser caching](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Caching).

**Comment by GeekCornerGH** [comment]
> I think you forgot the TLD as `pomme.o2switch` isn't a valid FQDN. 

I meant o2switch.net my bad

**Pull request merged**
