### PR TITLE
Add LocalMonero

### PR DESCRIPTION
**Pull request by LocalMonero**

### CODE REVIEW

**Review by phallobst — CHANGES_REQUESTED** [review]
Please replace the icon with this optimized version:
localmonero

**Comment by LocalMonero** [comment]
@phallobst sorry about, Michael. Do we need to approve it or will the reviewers merge it by themselves?

**Comment by LocalMonero** [comment]
The tests are failing so we'll open a new request.

**Comment by LocalMonero** [comment]
Resubmitted as #5461

**Pull request closed without merging**
