### PR TITLE
Enforce normalization on urls

### PR DESCRIPTION
**Pull request by stephengroat**
Creates consistency

### CODE REVIEW

**Comment by fpigerre** [comment]
I'm a little concerned that addition of URL normalisation might make it harder for new contributors to add new sites to the repository. Contributors would have to create their pull request before seeing the TravisCI warning, then figure out why the build was failing, before finally creating a second commit that would normalise the URL.

**Comment by stephengroat** [comment]
@psgs i thought about that too.

it seems like contributors who understand why the build is failing try to address it, while others don't 100% understand and don't seem to pull back at all

**Comment by mxxcon** [comment]
Isn't this is a bit pedantic? 😉 
What does trailing / gives us? What kind of errors/mistakes would enforcing this rule address?

**Comment by stephengroat** [comment]
to me it's similar to correcting the capitalization of twitter usernames. creates verifiable consistency

**Comment by mxxcon** [comment]
If twitter names are case insensitive then to me we are being overly pedantic with that too :)

**Comment by Carlgo11** [comment]
Nah I think this is an overkill, at least for now.

**Pull request closed without merging**
