### PR TITLE
Add SecurePass provider

### PR DESCRIPTION
**Pull request by gpaterno**
Added SecurePass as a 2fa provider

### CODE REVIEW

**Comment by mxxcon** [comment]
Or should it be under https://twofactorauth.org/#identity ?

**Comment by gpaterno** [comment]
No, in identity are listed more password management, this is a more comprehensive solution and can be used as a 2FA in the cloud.

That would be http://www.bankofpasswords.ch/ that is from the same company.

**Comment by mxxcon** [comment]
Well, as you can see from the category name, it's called "Identity Management", it's more than just password managers.

**Comment by gpaterno** [comment]
Do you think it can be in both of them? If yes, I will update both.

**Comment by jdavis** [comment]
This to me looks like it belongs more in the provider section than the identity section. All I see on the site is that it supports 2FA/OTP and provides a SSO solution while making it easy to manage.

That's just what I gathered from looking through the site so I totally could be wrong. If that is the case though, I'd say this `looks good`.

**Comment by mxxcon** [comment]
¯_(ツ)_/¯

**Comment by jdavis** [comment]
@mxxcon You usually have more knowledge about these things than I do, haha. I just took a cursory look at the site so if you disagree, I'd love to hear it =]

**Pull request merged**
