### PR TITLE
Update Amazon

### PR DESCRIPTION
**Pull request by Carlgo11**
As per #1393 
Couldn't find any docs.

### CODE REVIEW

**Comment by mxxcon** [comment]
Carl, this one is cleaner `https://www.amazon.com/gp/help/customer/display.html?nodeId=201596330`
And perhaps squish your commits into 1?

**Comment by Carlgo11** [comment]
@mxxcon done.

**Comment by jdavis** [comment]
:fireworks:

**Comment by clex25** [comment]
There is a phone call option. From the page linked above:

>  You can receive this security code in a variety of ways depending on the option you select during sign up, including text message, voice call, or authenticator app.

**Comment by Carlgo11** [comment]
yup but I can't see any way to do that.
Just tried to login but it won't give me any options to get a phone call.

**Comment by jamcat22** [comment]
You can use it as a backup option, but not as the main option.
capture

**Pull request merged**
