### PR TITLE
Add FaceIT

### PR DESCRIPTION
**Pull request by Scriptkiddi**
see issue #2485

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
@Scriptkiddi 
1. Are you sure that they support TFA?
2. If they do support TFA, what kind of TFA solutions do they support?

**Comment by Scriptkiddi** [comment]
https://support.faceit.com/hc/en-us/articles/115000254670-Enabling-2-Factor-Authentication- 

What do you the call google auth kinda 2fa support 
i would categories it under software: Yes

**Comment by stephengroat** [comment]
@Scriptkiddi that's perfect!

we also have a `doc` tag that we use to link to documentation just like that, I've added it!

**Review by stephengroat — APPROVED** [review]
thanks for the pr @Scriptkiddi

**Comment by Carlgo11** [comment]
faceit
Here's a better image. It's 30% smaller

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
faceit
Here's a better image. It's 30% smaller

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
Can we get another pair of eyes here? 👀

**Comment by stephengroat** [comment]
re-reviewed the new commits, merging

**Pull request merged**
