### PR TITLE
Added Reddit to Social

### PR DESCRIPTION
**Pull request by helwy**
Including the Reddit Icon

### CODE REVIEW

**Comment by mpdavis** [comment]
@HElwy Can you find a 32x32 image?

**Comment by helwy** [comment]
@mpdavis Like this one? (I just got a 16x16 one because it seemed all the other ones under the social category were 16x16)
reddit

**Comment by mpdavis** [comment]
Yeah, that one works.  We are trying to move everything to 32x32.

**Comment by helwy** [comment]
Did I do everything correctly? My first contribution to a repository so I'm still a bit confused

**Comment by mpdavis** [comment]
Yep, looks good.  I am just waiting for the Travis build to complete and pass before merging it in.

**Comment by helwy** [comment]
Oh ok, so do you need help with the icons 32x32 conversion? I can change the social category's icons, all of them are either 16x16 or 24x24

**Comment by mpdavis** [comment]
That would be appreciated a lot.

**Comment by mpdavis** [comment]
@HElwy I didn't realize that this work is mostly done already in #143.  I would hold of on it for now.

**Pull request merged**
