### PR TITLE
Add ftsafe.com to providers.yml

### PR DESCRIPTION
**Pull request by FeitianSmartcardReader**
Add feitian provider into two auth factor web

### CODE REVIEW

**Comment by mxxcon** [comment]
@FeitianSmartcardReader why did you modify `Gemfile.lock` file?
Please point out where do you offer email, sms and voice calls.

**Comment by FeitianSmartcardReader** [comment]
Hi 

Don't need change Gemfile.lock.

I guess it auto generate when I do test, you can ignore it or do I need submit another pull issue?

**Comment by mxxcon** [comment]
(that's why it's never a good idea to create pull requests out of your own master, always use branches)
Either create a new pull request or update this one to correct that problem.

**Comment by FeitianSmartcardReader** [comment]
send another request, please check, thanks ;-)
Best Regard

Ben |Technical Specialist (GLBAL SUPPORT)
Skype: Hooben@FEITIAN | Tel: +86 (10) 62304466 ext. 575
Feitian, Inc. Floor 17th, Tower B, Huizhi Mansion, No.9 Xueqing Road, Haidian District Beijing 100085, P.R China
Smartcard Readers->http://www.ftsafe.com/product/Smart_Reader http://www.ftsafe.com/product/Smart_Reader
Online Shop->http://www.ftsafe.com/product/reader_shop http://www.ftsafe.com/product/reader_shop

This email message (including any attachments) is for the sole use of the intended recipient and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution of this information is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy the original message and all of its copies.

**Pull request closed without merging**
