### PR TITLE
update mailbox.org URL and add software 2fa

### PR DESCRIPTION
**Pull request by wallenium**

### CODE REVIEW

**Comment by wallenium** [comment]
Added runtastic as well.

**Comment by Jawshy** [comment]
It's difficult to read the text in that icon. You may wish to use this icon instead. It's the site's current favicon and has a smaller file size. 
favicon

**Comment by RichJeanes** [comment]
@wallenium If you wouldn't mind reverting your branch to your first commit, we strongly prefer one site per PR. We also recommend working on a branch of your fork, instead of the master, to avoid merge conflicts.

**Comment by Carlgo11** [comment]
Closing due to inactivity.

**Pull request closed without merging**
