### PR TITLE
Add Vitality

### PR DESCRIPTION
**Pull request by rubenarakelyan**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr @rubenarakelyan!

**Comment by mxxcon** [comment]
Hmm..Should insurance company be under _finance_ category?

**Comment by stephengroat** [comment]
the adirondack insurance exchange is under finance...

**Comment by mxxcon** [comment]
doesn't mean it's in the right spot either.. :)

**Comment by rubenarakelyan** [comment]
That was my reference point as well...

**Comment by rubenarakelyan** [comment]
Do you see insurance as needing its own category?

**Comment by mxxcon** [comment]
It's a sensible category, but does it make sense for just 2 items?

**Comment by rubenarakelyan** [comment]
Personally, I think it makes sense to split out insurance once it gets a few more links so that they don't crowd out the rest of the financial sites.

**Comment by Carlgo11** [comment]
Let's stick with finance for now and if we get some more insurance entries we can make another category for them. Just like we have with government and transportation.

**Pull request merged**
