### PR TITLE
Add Braziliex and BTC Box

### PR DESCRIPTION
**Pull request by spazvt**
add 'Braziliex' and 'BTC Box' crypto currency exchanges from fork
https://github.com/acceptbitcoincash/acceptbitcoincash

### CODE REVIEW

**Comment by spazvt** [comment]
these two websites are ranking ~100k, but [9000](https://www.alexa.com/siteinfo/btcbox.co.jp) and [5000](https://www.alexa.com/siteinfo/braziliex.com) regionally in Japan and Brazil.

**Review by mxxcon — DISMISSED** [review]

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
I suggest you change to this logo: btcbox

**Comment by spazvt** [comment]
ok, btcbox icon updated.

**Review by Carlgo11 — DISMISSED** [review]
Thanks! 😄

**Comment by spazvt** [comment]
btw, I notice that braziliex's website uses half of a Brazilian flag as the [favicon](https://braziliex.com/favicon.ico) but it's only 16x16. I can't find that image anywhere else in a larger size. (I just now figured out how to access the favicon)

The image I've submitted is still listed as "logo" in their website, so I assume we stick with that one (the colored word BRAZILIEX).

**Comment by Carlgo11** [comment]
@spazvt that was my thoughts as well. 😉

**Review by mxxcon — CHANGES_REQUESTED** [review]
@spazvt could you please rebase your branch with our latest master? There's merge conflict.

**Comment by spazvt** [comment]
@mxxcon yes I can easily rebase. I'll do it late next week when I'm back from vacation.

**Comment by Carlgo11** [comment]
Shouldn't be needed. I resolved the merge conflict.

**Review by mxxcon — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
