### PR TITLE
Recategorize Aerohive Networks as Cloud Computing

### PR DESCRIPTION
**Pull request by Stevoisiak**

### CODE REVIEW

**Comment by stephengroat** [comment]
I'm not 100% on this one. They sell HW APs and other networking equipment, not really provide public cloud services

**Comment by Stevoisiak** [comment]
They advertise themselves as providing "Cloud Networking" on the [about](http://www.aerohive.com/company/about/) page.

**Comment by stephengroat** [comment]
i know, but they primarily offer their WISMs in the cloud. the `cloud` section lists public cloud providers

**Comment by Stevoisiak** [comment]
In that case, I'll close the PR. I had based my categorization on the website's description.

**Pull request closed without merging**
