### PR TITLE
Update U2F icon

### PR DESCRIPTION
**Pull request by Carlgo11**
As there is no official U2F logo I outlined a YubiKey and exported it as a SVG to replace the current "U2F" letter-icon.
Not sure if it preferable to the old icon or not :shrug: 

screenshot_1641075152
Hovering over the icon will display the text "U2F/WebAuthn support" for clarity.
screenshot_1641075185

### CODE REVIEW

**Comment by phallobst** [comment]
Medium gray on green for the contacts is hardly visible. Was that intentional?

**Comment by Carlgo11** [comment]
The original icon I made was all different shades of gray. I didn't really think of changing the contacts as they are hardly visible when scaled down to 30px.
I could certainly change the color tho. Here's a version with gold contacts:

**Comment by phallobst** [comment]
Slightly fixed alignment on the contacts:
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 27.1 35"><path fill="#2c662d" d="M16.9.2c-.5-.4-1.5-.2-1.9.5L3.1 20.1c-.4.7-.2 1.6.5 2l.9.5-4.4 7.2c-.2.3-.1.7.2 1l6.8 4.1c.3.2.8.1 1-.2l4.4-7.2.6.4c.6.4 1.5.1 1.9-.5L26.9 7.9c.4-.6.2-1.5-.5-1.9Zm-.4 11.4a3.8 4 31.5 0 1 1.1 5.5 3.8 4 31.5 0 1-5.2 1.4 3.8 4 31.5 0 1-1.2-5.4 3.8 4 31.5 0 1 5.3-1.5z" paint-order="fill markers stroke"/><rect id="a" width="1.4" height="7" x="17.02" y="18.2" fill="#ffd500" fill-opacity=".5" paint-order="fill markers stroke" rx=".3" transform="rotate(31.5)"/><use xlink:href="#a" transform="translate(4.43 2.72)"/><use xlink:href="#a" transform="translate(1.48 .9)"/><use xlink:href="#a" transform="translate(2.95 1.81)"/></svg>
```

**Comment by Carlgo11** [comment]
Actually the contacts are already aligned. There's 1px separation between each contact.
Here's the original version:
original

And here's the proposed SVG:
proposed

Edit: I think the fault is me minifying the SVG too much. I'll reupload the original but with more decimal precision.

**Comment by phallobst** [comment]
Strange... The version I got had a visibly larger gap between the 3rd and 4th contact, but they were not distorted at all (which usually happens with smaller precision).

**Comment by Carlgo11** [comment]
Here's my original SVG if that helps:
```SVG
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 40 100"><path fill="#2c662d" d="M4 0a4 4 0 0 0-4 4.04V69.7a4.01 4.01 0 0 0 4 4.04h3v24.24A2 2 0 0 0 9 100h23a2 2 0 0 0 2-2.02V73.74h2a4 4 0 0 0 4-4.04V4.04A4.01 4.01 0 0 0 36 0Zm16 28.79A11 11.62 0 0 1 31 40.4a11 11.62 0 0 1-11 11.62A11 11.62 0 0 1 9 40.4a11 11.62 0 0 1 11-11.6Z"/><rect id="a" width="4" height="20.2" x="11" y="77.27" fill="gold" fill-opacity=".45" rx=".8"/><use xlink:href="#a" transform="translate(5)"/><use xlink:href="#a" transform="translate(10)"/><use xlink:href="#a" transform="translate(15)"/></svg>
```
Maybe padding it with a group tag and adding `transform="rotate(30)"` would be all that's needed?

**Comment by Carlgo11** [comment]
Lots of decimals due to the rotation but this may be okay?
```SVG
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="-43.07 1.46 76.07 101.41"><g transform="rotate(30)"><path fill="#2c662d" d="M4 0a4 4 0 0 0-4 4.04V69.7a4.01 4.01 0 0 0 4 4.04h3v24.24A2 2 0 0 0 9 100h23a2 2 0 0 0 2-2.02V73.74h2a4 4 0 0 0 4-4.04V4.04A4.01 4.01 0 0 0 36 0Zm16 28.79A11 11.62 0 0 1 31 40.4a11 11.62 0 0 1-11 11.62A11 11.62 0 0 1 9 40.4a11 11.62 0 0 1 11-11.6Z"/><rect id="a" width="4" height="20.2" x="11" y="77.27" fill="gold" fill-opacity=".45" rx=".8"/><use xlink:href="#a" transform="translate(5)"/><use xlink:href="#a" transform="translate(10)"/><use xlink:href="#a" transform="translate(15)"/></g></svg>
```

**Comment by Carlgo11** [comment]
I just remembered that I could just leave the original as is and rotate it using CSS :facepalm:

What do you think about the SVG now @phallobst?

**Review by phallobst — APPROVED** [review]

**Review by kmpoppe — APPROVED** [review]

**Pull request merged**
