### PR TITLE
Add Simplii Financial

### PR DESCRIPTION
**Pull request by GregoryGHarding**

### CODE REVIEW

**Comment by GregoryGHarding** [comment]
why'd it fail?

**Comment by mxxcon** [comment]
@GregoryGHarding Logos must be <2500 bytes. Your logo is ~18kb.
Please run it through PNG optimizer.

**Comment by GregoryGHarding** [comment]
corrected png, thanks

**Review by mxxcon — APPROVED** [review]
However, that doesn't look too good for them :/
https://twitter.com/SimpliiFin/status/978310129174147072

**Review by brycx — APPROVED** [review]

**Pull request merged**
