### PR TITLE
Banca Mediolanum

### PR DESCRIPTION
**Pull request by AlessioCasco**
banking --> added Banca Mediolanum

### CODE REVIEW

**Comment by mxxcon** [comment]
I can't read Italian, but I see that page talks about tokens. What is that about?

**Comment by AlessioCasco** [comment]
Hi!
Basically all the operations that contemplate moving money outside your account have to be authenticate with the token you receive via sms.
You will receive one token for each operation you want to make.

**Comment by mxxcon** [comment]
Then this is not two factor "_authentication_", it's two factor "_authorization_". Similar but different things.
See https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions

**Comment by AlessioCasco** [comment]
Yep, you're right
Sorry about that

**Comment by Carlgo11** [comment]
Closing this PR as I interpret it as invalid (as discussed by @mxxcon  in [192491591](https://github.com/2factorauth/twofactorauth/pull/1620#issuecomment-192491591).)

**Comment by mxxcon** [comment]
It could be added as `tfa: no`...

**Comment by jamcat22** [comment]
Reopening this PR on the suggestion of @mxxcon, and because the branch hasn't yet been deleted.

@AlessioCasco Could you please change Banca Mediolanum's entry to reflect it's new status of not providing 2FA?

The following changes should be made:
- The line `tfa: Yes` should be changed to `tfa: No`.
- The line `sms: Yes` should be removed.
- The line `doc: https://www.bancamediolanum.it/sicurezza` should be removed.
- A new line, `twitter: BancaMediolanum` should be added.

Thanks!

**Comment by AlessioCasco** [comment]
@jamcat22 done.
Thanks!

**Pull request merged**
