### PR TITLE
Add Nominet to domains

### PR DESCRIPTION
**Pull request by edmorley**
Nominet are the organisation who have control over the `.uk` suffix, and have an online portal for people to update their domain contact details/allow transfers etc.

Unfortunately there isn't a better page than the PDF.
On the plus side, they are auto-prompting users to set up 2FA on login.

### CODE REVIEW

**Comment by Carlgo11** [comment]
1. Twitter handle isn't needed when the site supports tfa
2. The logo is way too big. Compress it so that it's smaller than 2.5 kb. I suggest https://tinypng.com

**Comment by mxxcon** [comment]
@edmorley please use this logo, it's 731 bytes, vs 3.3kb for your image :wink: 
nominet

**Comment by Carlgo11** [comment]
@mxxcon too late! :wink:

**Comment by edmorley** [comment]
Thank you - sorry for the PNG noobness - PR updated :-)

**Comment by edmorley** [comment]
> Twitter handle isn't needed when the site supports tfa

The example given for "a site that supports 2FA" includes the twitter handle. Would you like me to open a PR that corrects the example?
https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#adding-a-site-that-supports-tfa

**Comment by Carlgo11** [comment]
That won't be needed. I just changed it myself.

**Pull request merged**
