### PR TITLE
Add VPS.ag

### PR DESCRIPTION
**Pull request by belcloud**
Hello

Please accept the PR to add https://www.vps.ag to the list.
The 2fa page looks like this:
screenshot

Thank you

### CODE REVIEW

**Comment by mxxcon** [comment]
Are they blocking visitors from US?🤨I couldn't load the site
Is there `docs:` link  you could add?

**Comment by belcloud** [comment]
Here's the announcement: https://www.vps.ag/blog/two-factor-authentication-available-on-vps-ag/

The website should load ok from US. Do you mind a traceroute?

**Comment by brycx** [comment]
Thanks for the PR @belcloud. We currently have a limitation on new additions, that require a site to be within the Alexa top 200k, which vps.ag [is sadly not](https://www.alexa.com/siteinfo/vps.ag).

**Comment by mxxcon** [comment]
@belcloud traceroute works fine, however

```
$ curl -v https://www.vps.ag/blog/two-factor-authentication-available-on-vps-ag/
*   Trying 5.104.175.114...
*   Trying 2a07:5740:300::a...
* connect to 2a07:5740:300::a port 443 failed: Connection refused
* connect to 5.104.175.114 port 443 failed: Connection refused
* Failed to connect to www.vps.ag port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to www.vps.ag port 443: Connection refused
```
```
$ curl -v http://www.vps.ag/blog/two-factor-authentication-available-on-vps-ag/
*   Trying 5.104.175.114...
*   Trying 2a07:5740:300::a...
* connect to 2a07:5740:300::a port 80 failed: Connection refused
* connect to 5.104.175.114 port 80 failed: Connection refused
* Failed to connect to www.vps.ag port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to www.vps.ag port 80: Connection refused```

**Pull request closed without merging**
