### PR TITLE
Add Surfshark

### PR DESCRIPTION
**Pull request by mr-domenico**
Add new vpn site: Surfshark

### CODE REVIEW

**Comment by mxxcon** [comment]
Thank you for the PR, but for now we are limiting sites which are ranked >200k on alexa https://www.alexa.com/siteinfo/surfshark.com

**Comment by mr-domenico** [comment]
@mxxcon Hi surfshark reached >200k on alexa (second time in period). Do i need create new pull request or it's possible to merge this one?

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Please use this logo instead. It's 74% smaller.
surfshark

**Comment by mr-domenico** [comment]
@Carlgo11 changed icon

**Review by mxxcon — APPROVED** [review]

**Review by dsoegijono — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
