### PR TITLE
Responsivetable

### PR DESCRIPTION
**Pull request by waako**
This relates to #529 (responsive tables) and also provides a rough fix for #571 (Menu bar on narrow screens)

You can see it in action [here](http://2fa.hf.ms/)

### CODE REVIEW

**Comment by mxxcon** [comment]
Is it intentional that consecutive entries lines do not have horizontal separation lines? It's visible in device screen emulation in Chrome and Firefox dev tools and in Chrome on my GS3

**Comment by waako** [comment]
nop, not intentional. will add some separation lines

**Comment by jdavis** [comment]
This looks really good so far, I see a few things that I'd clean up but I'll wait to do that after you are done. Great work so far!

**Comment by jdavis** [comment]
What's the status of this, @waako?

**Comment by waako** [comment]
sorry, quickly added separation between table rows and reduced size of icons/labels slightly.
in an ideal world would have the site name to the left with icons on same line to the right, on smaller devices.
Darn 3 weeks later, and now have merge conflicts.
Thanks for the prodding though

**Comment by jdavis** [comment]
Oh, don't worry about the merge conflicts; I'll happily manage those.

I don't mean to prod either, I just think this would be a great addition. Regardless of whether or not you can get more done, I appreciate all that you've coded up so far =]

Just let me know when you are at a state where you are ready to pass it off and I'll pull it down; make sure it looks good and merge it.

**Comment by waako** [comment]
Oh I completely appreciate the prodding, stops me forgetting.
I'm enjoying it, so more than happy to be contribute anything I can.

**Comment by Walkman100** [comment]
https://cloud.githubusercontent.com/assets/5454764/6424719/f58e957a-bf0c-11e4-833c-178bac76303a.png
Other than those separation lines, looks good :smile: :+1:
(https://twofactorauth.org/ on the left, http://2fa.hf.ms/ on the right. Chrome 40.0.2214.115 on Linux Mint 16)
Edit: Whoops, here's a screenshot with Ad Blockers disabled:
image
(Just to clarify, even with Ad Blockers disabled, the separation lines still don't show)

**Comment by mxxcon** [comment]
Is this PR still useful or should it be closed?

**Comment by waako** [comment]
Good question, probably still useful as twofactorauth.org isn't mobile friendly.
I just haven't thought about it for so long, I'll try to find the time to add divider lines soon, or someone else can.
I'm not sure how up to date 2fa.hf.ms is anyway

**Comment by jamcat22** [comment]
@waako Do you still think you can add the dividers?

**Comment by waako** [comment]
Thanks for reminding me :smile: 
I've made the small CSS change which adds a divider border to each row.

I've not tested it on my version, as not got the same local environment so don't have time right now to get new build up on github, but tested it in devtools, so should work!

**Comment by Carlgo11** [comment]
@waako could you also update your local environment with our remote branch?

**Comment by jamcat22** [comment]
Great. Updating should also remove the providers page and text on the front page about it.

**Comment by waako** [comment]
I'll see what I can do, I haven't looked at this in over a year, so a bit behind, and I'm mid-process of moving to another country, so it may take a few weeks!

**Comment by Carlgo11** [comment]
I think we can close this one as we're working on a new layout.

**Comment by fpigerre** [comment]
This issue has been resolved in issue #1368.

**Pull request closed without merging**
