### PR TITLE
Added Yandex.Disk (backup) and Yandex.Mail (email) services

### PR DESCRIPTION
**Pull request by alexkoster**
Added Yandex.Disk and Yandex.Mail to the backup and email sections respectively.  Added icons for each in subdirectories of the img diretory. Their 2FA service depends on a smartphone app so I put down both as only having software implementations.  This is my first pull request. If anything isn't right, please let me know and I'd be happy to resubmit.

### CODE REVIEW

**Comment by mxxcon** [comment]
Those logos are a bit on an ugly side.
Perhaps use one from http://img.artlebedev.com/everything/yandex/disk/process/yandex-disk-process-05.gif for .Disk
And resize this one for .Mail https://lh5.ggpht.com/lddWNEd-wUYK1qp0ZFklh0KKEzqwRR5FAlvIKLbdDKOVzLzM6hqMyI_tQdXsMPOzFA

**Comment by alexkoster** [comment]
Thanks for the feedback.  I think they look a bit better now having used higher-quality sources.  Have a look and let me know what you think.  

BTW, I find it awesome that you are out of NYC.  I'm considering relocating there after I graduate but still a bit apprehensive not knowing what its like to work in the software industry in NYC.  Would love to chat (perhaps off this thread :-) more about this if you have any advice, tips, or experience to give.

**Comment by mxxcon** [comment]
sure. if you want to, feel free to contact me

**Comment by alexkoster** [comment]
Would love to! What's the best way to reach you?

**Comment by mxxcon** [comment]
i'm on freenode and efnet

**Pull request merged**
