### PR TITLE
Add Papertrail to developer

### PR DESCRIPTION
**Pull request by edmorley**
Papertrail provides cloud-hosted log aggregation and management.
These logs can contain security sensitive information.

### CODE REVIEW

**Comment by mxxcon** [comment]
Please use this logo, it's 862 bytes vs 4kb for your logo
papertrail

**Comment by edmorley** [comment]
Thank you - PR updated :-)

**Comment by Carlgo11** [comment]
Feels like a project which is too small to be on the list.

**Comment by mxxcon** [comment]
papertrail is actually a pretty well-known project...at least I've heard about it a while ago..

**Comment by jamcat22** [comment]
I think it looks good.

**Pull request merged**
