### PR TITLE
Add hitbox.tv

### PR DESCRIPTION
**Pull request by Gol-D-Ace**
Gaming live streaming website.

### CODE REVIEW

**Comment by mxxcon** [comment]
What kind of sensitive info does it have?

**Comment by Carlgo11** [comment]
It's like Twitch.tv. A (mostly) gaming streaming service.

**Comment by RichJeanes** [comment]
I'd say if Twitch is on the list, Hitbox has a place, too.

**Comment by mxxcon** [comment]
Twitch has paid services. Does hitbox have that?

**Comment by Carlgo11** [comment]
Twitch doesn't even have https for logins. The won't change it either.

**Comment by RichJeanes** [comment]
Hitbox may not have paid services, but we've had this discussion about stream keys having value in the form of personal image. (That discussion was instigated by myself, actually. #1117)

**Comment by jamcat22** [comment]
It seems to fit our criteria in that department.

**Comment by Gol-D-Ace** [comment]
@Carlgo11 They do.
https://passport.twitch.tv/authentications/new

**Comment by Carlgo11** [comment]
Yup but go change your password under settings then tell me that's secure :yum:

**Comment by Gol-D-Ace** [comment]
Looks like a normal https page to me @Carlgo11 
https://secure.twitch.tv/user/change_password

**Comment by Gol-D-Ace** [comment]
Or do you mean the method of key exchange @Carlgo11
My knowledge lacks there.

**Pull request merged**
