### PR TITLE
Added Box

### PR DESCRIPTION
**Pull request by danieltaylor**
Added Box.com to the section "Backup."  Still needs an image.

### CODE REVIEW

**Comment by jdavis** [comment]
Would you be able to download https://www.box.com/favicon.ico and convert it to a PNG that is 16x16? I'd understand if you didn't want to =]

**Comment by danieltaylor** [comment]
@jdavis Yeah, sure.  It says I deleted some lines in the code though, do you know how I can fix that?

**Comment by danieltaylor** [comment]
@jdavis How's this?
favicon

**Comment by jdavis** [comment]
That icon's perfect! Also, regarding the lines you missed, I'd recommend just pulling in the latest from master, doing another branch, patch-2, and then just copying and pasting the changes. That way you don't recommit over re-adding it and it keeps the history clean. It's kind of a pain though =[

**Comment by danieltaylor** [comment]
Done.  Do I need to submit a new pull request from it?

I think Wells Fargo must have been added after I forked the master, because its missing from my master as well as patch-1.

**Comment by jdavis** [comment]
Yeah, that might have happened. And yeah, try a new pull request then we
can close this one. At least it is up to date as well. Thanks a lot for you
work too, sir.

**Pull request closed without merging**
