### PR TITLE
VPN providers and crypto exchanges from 'acceptbitcoincash'

### PR DESCRIPTION
**Pull request by spazvt**
* Pull in additional VPN service providers added by @deadr0ck in fork
  https://github.com/acceptbitcoincash/acceptbitcoincash
  * Anonine, CrypticVPN, ExpressVPN, IPVanish, NordVPN, Perfect Privacy VPN, ProtonVPN, PureVPN, SaferVPN, ShadeYou.

* Added a few twitter or facebook handles for existing VPN providers who don't support 2FA.

* add more crypto currency exchanges from 'acceptbitcoincash':
  * Binance, Bitcoin Vietnam, Bitflyer, Bithumb, Braziliex, BTC BOX, BTC POP, BX Thailand, CoinOne, Coinspot, Cryptopia, DSX, HitBTC, Korbit.

* The EXCLUSION list was empty, so I looked back through a few pages of commits to add the companies that have already been removed.

* btc-e.com was shutdown but 2/3 of bitcoins and userdatabase was restored and they've reorganized as WEX.nz legally based in Singapore. Therefore re-adding them.

I left in some twitter/facebook handles for companies that do support 2FA because it helps reduce differences between this 2FA repo and the AcceptBitcoinCash fork. (several errors were introduced when the original fork was created and these handles needed to be looked for again.)

### CODE REVIEW

**Comment by mxxcon** [comment]
This pull request is way too big to be reviewed as a whole.
It would be best to submit each site separately so that each site can be reviewed on its own merit, without affecting other sites.

**Comment by spazvt** [comment]
that would be 25 PRs (25 companies), likely with file merge conflicts at each step :fearful: 
Can you suggest larger chunks if you really want it broken up?  (maybe one PR per adjacent/alphabetical entries to avoid merge conflicts)

**Comment by mxxcon** [comment]
>maybe one PR per adjacent/alphabetical entries to avoid merge conflicts

At least that..

**Comment by spazvt** [comment]
I have now created 15 PRs to split up all of these additions. Therefore closing this original PR.

**Pull request closed without merging**
