### PR TITLE
Add Archive of Our Own

### LINKED ISSUE #7429: Add Archive of Our Own
### Site name

Archive of Our Own

### Site URL

https://archiveofourown.org/

### Facebook

_No response_

### Twitter

@ao3org

### Email address

_No response_

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hkamran80**
Resolves #7429

### CODE REVIEW

**Comment by Carlgo11** [comment]
I'm very skeptical about listing that site.
Not only does it contain fan fiction, a grey area in copyright law, but it also contains graphic sexual content with fictional characters from the intellectual property.

That would match the **[Illegal content](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md#illegal-content)**, **[Pornographic sites](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md#pornographic-sites)** and **[Potentially controversial sites](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md#potentially-controversial-sites)** categories in [EXCLUSIONS.md](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).

**Comment by hkamran80** [comment]
We have Wattpad and FanFiction.Net, both of which host the same type of content.

**Comment by Carlgo11** [comment]
Then they probably should be removed.

**Comment by hkamran80** [comment]
Regarding the illegality, while it may be deemed a derivative work (which U.S. copyright law says can only be created with permission from the copyright owner or if the work is in the public domain), many organizations, especially the Organization for Transformative Works (the organization behind AO3) argue that fanfiction should be considered under the fair use doctrine (see an [interview with the legal chair of OTW](https://www.syfy.com/syfy-wire/how-to-keep-fanfiction-legal-and-avoid-trouble-with-lawyers) and the [OTW Legal Advocacy page](https://www.transformativeworks.org/legal/)).

One [NYU blog](https://blog.jipel.law.nyu.edu/2021/04/is-fanfiction-legal/) described how fanfiction could be considered fair use.
> [Fair use](https://www.copyright.gov/fair-use/more-info.html) is an area of copyright law that allows for freedom of expression when using unlicensed copyrighted works in very limited and specific incidences, as established in [17 U.S.C. § 107](https://www.law.cornell.edu/uscode/text/17/107).

> Though fair use determinations involve four distinct factors, the two arguably [most relevant factors](https://www.standoutbooks.com/fan-fiction-legal/) when evaluating the legality of a fanfiction work would be: (1) the purpose and character of the use, including whether such use is of a commercial nature; and (4) the effect of the use upon the potential market for or value of the copyrighted work.

> When evaluating the first factor for a fanfiction, courts would look to the extent to which the unlicensed work was transformative in nature. This transformative use doctrine was first established quite recently in the 1994 case, [Campbell v. Acuff-Rose Music](https://www.law.cornell.edu/supct/html/92-1292.ZS.html), 510 U.S. 569 (1994). Simply stated, the Court in that case emphasized that the “transformative” nature of works — meaning the extent to which the works in question added new expression and value to the existing work — would be a significant factor in determining whether a work falls under fair use.

> This means that by adding something new to already existing works, fanfiction authors may claim that they are not infringing on the existing rights of the original author. The fourth factor is slightly more straightforward than the analysis required under the first factor — courts would just look to whether or not the work would negatively impact the current market for the existing copyrighted work. Given these two factors, [OTW claims](https://www.syfy.com/syfywire/how-to-keep-fanfiction-legal-and-avoid-trouble-with-lawyers) that fair use can be an effective shield against liability for fanfiction authors, so long as their works are “noncommercial” and “transformative.”

In regard to the pornographic aspect, the exclusion list says "sites that primarily host and serve pornographic content". AO3, along with other fanfiction hosts, doesn't **primarily** host pornographic content, but they do host a bit. Using AO3 as an example, they host over 10.5 million fanfics, but only about 750,000 contain pornography in some way.

**Comment by Carlgo11** [comment]
Unfortunately, what can be deemed legal in certain jurisdictions don’t necessarily apply to other jurisdictions.

In the case of 2FA Directory, the governing jurisdiction is ultimately a combination of national (Swedish) along with European laws and international agreements.
The United States have a much broader definition of fair use and freedom of expression than the other jurisdictions making the case a grey area at best. As the Chief Compliance Officer of 2factorauth I don’t feel comfortable knowingly approving an entry like that.
In any case the “potentially controversial” category still applies.

**Comment by hkamran80** [comment]
I see. No worries then. Thanks for explaining your reasoning!

**Pull request closed without merging**
