### PR TITLE
Adding ComEd

### PR DESCRIPTION
**Pull request by wisco24**

### CODE REVIEW

**Comment by mxxcon** [comment]
Logos have to be 32x32 and under 2.5kb in size.
You can use their favicon image from https://www.comed.com/Style%20Library/Exelon/exc-images/favicons/comed/favicon-32x32.png
😃

**Review by mxxcon — CHANGES_REQUESTED** [review]
You uploaded the new logo into the wrong folder. 😅

**Comment by wisco24** [comment]
Fixed,  sorry about that.

**Review by mxxcon — APPROVED** [review]

**Comment by jamcat22** [comment]
Duplicate of #2713.

**Pull request closed without merging**
