### PR TITLE
Test more tags in the YAML files

### PR DESCRIPTION
**Pull request by Carlgo11**
Hello,
this is a small PR to add a test of the `tfa:` tag in the verify.rb script.

It checks whether the tfa tag is true/false which yes/no is transformed to.
This means that `tfa: true` also would be okay but I opted for this as I did the pros and cons of the extra work of verifying it is in fact Yes/No and we haven't had any cases yet where people have written true/false instead of Yes/No. (To my knowledge at least)

Most of all this is to stop me from doing the error I did in #1531 again.

### CODE REVIEW

**Comment by jamcat22** [comment]
Can you have it check the other booleans too if they are included in the file?

**Comment by Carlgo11** [comment]
@jamcat22 I'm not very good at Ruby yet but I'll see what I can do.
#Got2LookNice

**Comment by jamcat22** [comment]
^ Same. That's why I made you do it. :stuck_out_tongue:

**Comment by Carlgo11** [comment]
There we go. It now also checks that `software`,  `email`, `phone`, `sms` is set to `Yes` if set and that it isn't set when `tfa` is set to `No`

**Pull request merged**
