### PR TITLE
Add Clipper, which currently doesn't support 2 factor authentication

### PR DESCRIPTION
**Pull request by rbaumbach**

### CODE REVIEW

**Comment by mxxcon** [comment]
@rbaumbach does it fit into any of these? https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria

**Comment by rbaumbach** [comment]
It's a website that controls your credits for a public transportation card.  Not sure if it would fit into anything.  I'm open to suggestions though =)

**Comment by Carlgo11** [comment]
I can't see that is fits the cafeterias.
I vote to close the PR.

**Comment by rbaumbach** [comment]
@Carlgo11 Considering that many people have Clipper cards that could contain hundreds of dollars on them and are easily lost/stolen, I think it's a good idea to add Clipper to the list to help people push for 2 factor authentication for it.

**Comment by Carlgo11** [comment]
Who the hell has hundreds of dollars on their commuter card?!

**Comment by mxxcon** [comment]
@rbaumbach does the site save your financial data or do you have to re-enter it each time? does it allow you to take money off the card?

**Comment by rbaumbach** [comment]
@Carlgo11 A lot of people.  @mxxcon, you can save credit cards and/or attach checking accounts to an account.

**Comment by Carlgo11** [comment]
So can you remove money from an account if you login to that site?
Any vulnerable information on the site?

**Comment by Carlgo11** [comment]
So should be put it to a vote? @mxxcon @dsoegijono @jdavis @ilyakatz @jamcat22? I'd love some feedback.

**Comment by jamcat22** [comment]
I think if it links to your bank account or credit card, and you can withdraw money from those, it should be added.

In my opinion, I think it fits criteria 2 and 3.

**Comment by mxxcon** [comment]
I guess it can be added.

**Comment by Carlgo11** [comment]
Yeah it's handling money but only to add money and not withdraw.

**Comment by mxxcon** [comment]
But I imagine somebody can maliciously transfer a lot of money onto it and then good luck trying to get them out...
:+1: to add it.

**Comment by Carlgo11** [comment]
okay 2vs1. you guys win ;)

**Pull request merged**
