### PR TITLE
Update TransferWise documentation, add software token.

### PR DESCRIPTION
**Pull request by Flameeyes**
The mobile app can act as a second factor with push notifications.

### CODE REVIEW

**Review by dsoegijono — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Comment by joeldrapper** [comment]
TransferWise doesn’t actually support TOTP, so this PR breaks @1password Watchtower.

**Comment by mxxcon** [comment]
@joeldrapper, `software: yes` doesn't mean exclusively TOTP. It is any kind of software 2fa implementation, such as how Steam mobile client does it or twitter or in this case TransferWise

**Comment by joeldrapper** [comment]
Right, that makes sense. I guess this isn’t the right resource for that data then. 🤔

**Comment by LloydThinks** [comment]
For the sake of services such as 1Password that are using https://twofactorauth.org/ as their source of information, shouldn't there be a separate flag for TOTP?

I came to this issue repo looking for why TransferWise was included on https://twofactorauth.org/. Now I know, but delivering information in a round-about way.

**Comment by Carlgo11** [comment]
@LloydThinks see #3222

**Pull request merged**
