### PR TITLE
Add VMware

### PR DESCRIPTION
**Pull request by rasa**
Alexa rank: [2,217](https://www.alexa.com/siteinfo/vmware.com)
Website: https://vmware.com
Login page: https://my.vmware.com/web/vmware/login

### CODE REVIEW

**Comment by phallobst** [comment]
Please rebase your branch to the current master.

**Comment by Carlgo11** [comment]
Closing due to inactivity.

**Comment by rasa** [comment]
Asked 4 days ago in https://github.com/2factorauth/twofactorauth/pull/5222#issuecomment-791010074 :
> Please rebase your branch to the current master.

It's rebased now. I tried `git rebase upstream/master` but it left 50+ commits littering this PR. So I fixed that issue by:
```
git reset --hard upstream/master
```
and then re-committed my change manually. I would prefer not to have to do that again. Can you suggest how to properly perform this action on my other PRs? Thanks.

**Comment by Carlgo11** [comment]
```PWSH
git fetch upstream master
git reset --hard upstream/master
git cherry-pick 7ae370a
git push origin vmware -f
```

**Comment by phallobst** [comment]
Superseded by #5588

**Pull request closed without merging**
