### PR TITLE
Marking PersonalCapital as supporting TFA per https://www.personalcapita...

### PR DESCRIPTION
**Pull request by pc-elavassani**
This is with the image moved to the right directory as well.

### CODE REVIEW

**Comment by Carlgo11** [comment]
@jdavis Can you look at the travis output? Seems to be something wrong with the bundle install script

**Comment by pc-elavassani** [comment]
I did another commit checking off email as well. I'm not sure about the bundle install script. I ran it locally and it looks fine.

**Comment by mxxcon** [comment]
If you do phone call and email, perhaps `software: yes` should be removed?

**Comment by jdavis** [comment]
@Carlgo11 It looks like Travis puked again like from last week. By adding another commit, it triggered the build again.

**Comment by pc-elavassani** [comment]
Is there anything I need to do here to help it move forward?

**Comment by mxxcon** [comment]
@pc-elavassani regarding my question above..?

**Comment by pc-elavassani** [comment]
Yes. And anything else that I can do to complete this pull request.

**Comment by mxxcon** [comment]
@pc-elavassani, I'll try again :smile:
If you do phone calls and email, perhaps `software: yes` should be removed?

**Comment by pc-elavassani** [comment]
Removed! git commit is 95951b2f09bcce03ea96a40f87fbc2b5440111d5

**Comment by mxxcon** [comment]
lgtm :+1:

**Pull request merged**
