### PR TITLE
Removed fixed width from container

### PR DESCRIPTION
**Pull request by mslepko**
More mobile friendly look

### CODE REVIEW

**Comment by jdavis** [comment]
For ease of merging and historical purposes, could you post a screenshot of before and after? I think mobile is important and would love to see what it looks like.

**Comment by mslepko** [comment]
It's not perfect but I think it look a lot better.

Current site
before

After my change
after

**Comment by computmaxer** [comment]
Nice. :+1: Does Semantic UI have any kind of responsive support like Bootstrap?

**Comment by jdavis** [comment]
Yes, it does a bit. I actually ripped it out because of how janky it was. It rendered the tables completely unreadable.

**Pull request merged**
