### PR TITLE
Updated Patreon

### PR DESCRIPTION
**Pull request by vlanard**
We've added sms 2fa support.

### CODE REVIEW

**Comment by fpigerre** [comment]
Thanks for the pull request @vlanard! 👍

**Review by fpigerre — APPROVED** [review]

**Comment by jamcat22** [comment]
It looks like software 2FA support is no longer an option for those without 2FA currently setup. Should we keep the `software: Yes` tag on it?

What do you think @vlanard and @2factorauth/collaborators?

**Comment by RichJeanes** [comment]
To quote the [Support page](https://patreon.zendesk.com/hc/en-us/articles/206538086-How-Do-I-Set-Up-Two-Factor-Authorization-):

> If you have enabled totp two factor (Google Authenticator) you do not need to switch to sms. If you decide to remove two factor or switch to sms you will lose access to totp two factor authentication on Patreon. Moving forward, SMS two factor authentication will be our main two factor security preference.

**Comment by stephengroat** [comment]
i'd say remove `software`

**Comment by RichJeanes** [comment]
Agreed.

**Comment by vlanard** [comment]
Will do. It felt kind of ambiguous since existing users can use Software SMS.

**Comment by RichJeanes** [comment]
While users that already have a software (TOTP) token enabled can continue to use it, users who do not have 2FA enabled are more likely to be looking at 2FA.org for what is available and will not be able to enable a software token.

**Comment by vlanard** [comment]
done !

**Review by stephengroat — APPROVED** [review]

**Pull request merged**
