### PR TITLE
Added GitLab

### PR DESCRIPTION
**Pull request by kgizdov**
#1077

### CODE REVIEW

**Comment by mxxcon** [comment]
@kgizdov "accepting pull requests" not the same as "actively working on it".

**Comment by mxxcon** [comment]
@Carlgo11 perhaps you were a bit premature closing this. @kgizdov can easily update his pull request to remove that status line.

**Comment by Carlgo11** [comment]
Ah, sorry. Should have read through it more carefully.

**Comment by kgizdov** [comment]
status removed

**Pull request merged**
