### PR TITLE
updated rackspace support for 2-factor auth

### PR DESCRIPTION
**Pull request by joesavak**

### CODE REVIEW

**Comment by mxxcon** [comment]
Hmm..I wonder if it makes sense to have 2 separate entries for Rackspace, one under Cloud Providers, and one here under Hosting/VPS.
The link @joesavak provider relates to Cloud accounts.
However, Rackspace Hosting(physical/enterprise) also has http://www.rackspace.com/knowledge_center/article/myrackspace-two-factor-authentication
While theoretically they are both SMS-based TFA, instructions to set them up are different...

**Comment by joesavak** [comment]
Yes - there are 2 portals (myRack for hosting customers and myCloud for cloud customers) - agree that Rackspace should be listed in both

**Comment by Walkman100** [comment]
See the travis build, I think if you are adding rackspace to `cloud` then you also need to copy the image to the `cloud` images folder too

**Comment by joesavak** [comment]
thanks @Walkman100 - I corrected. : )

**Pull request merged**
