### PR TITLE
Update Bitfinex

### PR DESCRIPTION
**Pull request by vvhof**
Includes U2F hardware keys

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr!

**Review by jamcat22 — APPROVED** [review]
Thanks @vvhof!

**Comment by vvhof** [comment]
Thanks for merging so swiftly +1

**Comment by Carlgo11** [comment]
And thanks for the PR! Even though your PR has been merged, it might take some time before it shows up on the website. For more information, check out our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge).

**Pull request merged**
