### PR TITLE
add accountone

### PR DESCRIPTION
**Pull request by mathe42**

### CODE REVIEW

**Comment by mathe42** [comment]
I don't understand why the CircleCI Pipeline is not running error "Could not find a usable config.yml, you may have revoked the CircleCI OAuth app."...

(Looks like an error on your side...)

**Comment by hkamran80** [comment]
Could you sign in to CircleCI? Their dashboard is saying the following.
> Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.

**Comment by hkamran80** [comment]
Hello @mathe42,

Unfortunately, as this site is below our minimum [Similarweb](https://www.similarweb.com/website/accountone.de/#overview) global rank of 200,000, this site cannot be added. This rule is in place because maintaining the lists takes time, and a list of all websites on the internet just isn't feasible. In the future, please review our [site guidelines](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) and [exclusion list](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md) before adding a site.

**Comment by MasterPuffin** [comment]
> Could you sign in to CircleCI? Their dashboard is saying the following.
> 
> > Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
> > Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.

Hello,
I'm taking over for my colleague here. Just for future requests could you specify what the CircleCI test is doing and what we have to do on our end to pass it? I couldn't find any mention of it on the contribution file.

**Comment by hkamran80** [comment]
CircleCI checks the social handles and the Similarweb ranking.

**Comment by Carlgo11** [comment]
To elaborate, the CircleCI build usually runs automatically without signing in. Sometimes though, a PR author has used CircleCI previously which means CircleCI tries to use the author's credentials instead of 2factorauth's. If the PR author's authentication token has expired the build can't run and so the auth token needs to be regenerated by signing in to CircleCI.
After signing in no further actions are required.

As to what it's doing, just as @hkamran80 mentioned, it checks social media handles and the site's ranking. If you follow the instructions in [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md), the build will pass.

**Pull request closed without merging**
