### PR TITLE
Add HotDoc

### PR DESCRIPTION
**Pull request by fletcherdodd**

### CODE REVIEW

**Review by Carlgo11 — COMMENTED** [review]
Are you sure TOTP is supported?
image

**Comment by fletcherdodd** [comment]
> Are you sure TOTP is supported? image

You are correct, [looks like](https://support.hotdoc.com.au/hc/en-gb/articles/4694311883033#h_01ET3MDYGE05W5XMWFPG9Y3JW3) the TOTP option is only available to the practice/medical staff

**Comment by Carlgo11** [comment]
@fletcherdodd want to remove totp then?

**Comment by fletcherdodd** [comment]
Oops forgot to click push :)

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
@fletcherdodd are you able to __Squash and merge__ the pull request now?

**Pull request merged**
