### PR TITLE
New service provider Cognalys Inc

### PR DESCRIPTION
**Pull request by anishmenon**
I think this is enough .

### CODE REVIEW

**Comment by Walkman100** [comment]
The line `- name: Cognalys Inc.` has wrong indentation.

**Comment by smholloway** [comment]
Cognalys does not support `sms`, `phone`, `software`, and `hardware`. At best, Cognalys supports `phone`; at worst it is not even a 2FA provider.

**Comment by anishmenon** [comment]
Did u visited the website at least so when u click on check demo button you will understand it's 2fa or not please don't tell with out knowing what cognalys provides. 

http://www.slideshare.net/mobile/cognalys/slide1-38487589

@smholloway.  Please understand I'm trying to contribute ON THIS.  Please double check before you comment

**Comment by anishmenon** [comment]
@Walkman100  I'll do the edit and commit.  Thank you

**Comment by smholloway** [comment]
Don't be rude. I've read the website and looked through the documentation. I don't think missing a phone call counts as two factor authentication--there's no possession, inherence, or knowledge there.

**Comment by anishmenon** [comment]
@smholloway  This is why what I say 

Once you request api to initiate missed call the service sent a missed call from  a random number Considering it as one time password.  The second api verify the last five digit of the missed call number right or wrong.  Cognalys Android library provides automated Mobile number verification.  

https://play.google.com/store/apps/details?id=com.matesnetwork.cogdemo

It's already integrated in so many WordPress login as two factor authentication 
http://kamleshyadav.com/mobileverifier/wp-login.php?action=register

And I found free plugin

https://wordpress.org/plugins/missed-call-mobile-number-verification-add-on-for-contactform7-cognalyscom/

Understand buddy I'm trying to make u clear not rude

**Comment by Carlgo11** [comment]
@anishmenon you're being really rude. Please mind your language or we'll ignore your pull requests.

**Comment by anishmenon** [comment]
I just tried to make him clear that cognalys is a 2fa provider.  I don't know how it became rude. May be it's bad from readers side of view.  Please understand I don't have any intention to become rude.

**Pull request closed without merging**
