### PR TITLE
Add Everyday Insurance

### PR DESCRIPTION
**Pull request by fletcherdodd**
Everyday Insurance uses different authenication details to the Everyday's [Mobile brand](https://mobile.everyday.com.au/). 

I was unable to locate a direct link but [here](https://insurance.everyday.com.au/help.html?c=54) is a the FAQ section where you can find information on 2FA, it's enabled by default and can not be turned off.

### CODE REVIEW

**Comment by hkamran80** [comment]
Hello @fletcherdodd,

Unfortunately, as this site is below our minimum [Similarweb](https://www.similarweb.com/website/insurance.everyday.com.au/#overview) global rank of 200,000, this site cannot be added. This rule is in place because maintaining the lists takes time, and a list of all websites on the internet just isn't feasible. Once it reaches the minimum, please open a pull request.

In the future, please review our [site guidelines](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) and [exclusion list](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md) before adding a site.

**Comment by fletcherdodd** [comment]
Hi @hkamran80,

Something similar happened when I added their mobile branch of the business (oringally Woolworths Mobile) in #7599. According to Similarweb both the Mobile & the Insurance subdomains have no ratings however their main website is under 100K ([see here](https://www.similarweb.com/website/everyday.com.au/#overview)). I believe the rating should be overlooked since the main website rating is so high and this is a well known brand in Australia.

**Comment by Carlgo11** [comment]
It might be a bug with SimilarWeb. I know subdomains work correctly but since the TLD is com.au, maybe that breaks the ranking system? 🤷‍♂️
Either way, I agree that it looks weird that one page is ranked so good and the other one doesn't have a rank at all.

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
And I think it's time to add an insurance category.
Maybe one of you two wanna create a PR? Or I'll do it tomorrow.

**Comment by hkamran80** [comment]
> And I think it's time to add an insurance category. Maybe one of you two wanna create a PR? Or I'll do it tomorrow.

I'll create it.

**Pull request merged**
