### PR TITLE
Add Domeneshop to domains list

### PR DESCRIPTION
**Pull request by kearva**
Domeneshop (aka Domainnameshop) supports both SMS and App-based two-factor. SMS is only supported in Norway, Sweden and Denmark.

This company is known as Domeneshop in Norway, Domæneshop in Denmark and Domänshop in Sweden. Their english brand is Domainnameshop.

https://domeneshop.no/faq?id=344

### CODE REVIEW

**Review by stephengroat — DISMISSED** [review]
Thanks for the pr @kearva

**Review by brycx — COMMENTED** [review]
Thank you for the PR @kearva. Due to a recent limitation where a site needs to be within the Alexa top 200k, I have to close this PR since Domainnameshop [is not](https://www.alexa.com/siteinfo/domainname.shop).

**Comment by kearva** [comment]
Will it help if their norwegian website is domeneshop.no? https://www.alexa.com/siteinfo/domeneshop.no

**Comment by brycx** [comment]
I don't see why not, could you please change the PR to fit that instead?

**Review by brycx — APPROVED** [review]

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
