### PR TITLE
Minor styling fixes

### PR DESCRIPTION
**Pull request by dsoegijono**
### Update README
Need to `serve` before it's accessible

### Desktop table width
The column widths were set on the `<td>` for icons only, so during search if a section has only non-tfa listed, the width wasn't set. This ensures the table headers width is fixed.

**Before**
Screen Shot 2020-06-12 at 11 14 52 pm

**After**
Screen Shot 2020-06-12 at 11 13 59 pm

### Site name overlaps exception icon

**Before**
Screen Shot 2020-06-12 at 10 46 36 pm

**After**
Screen Shot 2020-06-12 at 10 46 44 pm

### CODE REVIEW

**Comment by phallobst** [comment]
I just noticed that the sticky table headings only work in Firefox again, but not in Chrome (+Chromium-based browsers) - see also #4746.

Can you fix that as well? I was unsuccessful.

**Review by Carlgo11 — APPROVED** [review]
Love it! Is the package-lock.json needed?

**Comment by dsoegijono** [comment]
@Carlgo11 Not necessary exactly. Do you manually remove it after `npm i babel-minify`? But since this is a requirement for the site to run, I think we should add `package.json` and `package-lock.json`

@phallobst I can try looking into it but maybe in a separate PR?

**Comment by phallobst** [comment]
The column width are fixed by this. I'm okay with another PR for the "sticky" bug.

**Review by phallobst — APPROVED** [review]

**Pull request merged**
