### PR TITLE
Add Planning Center Online

### PR DESCRIPTION
**Pull request by thegeekkid**
PCO (focused around church planning and record keeping) contains personal information such as volunteer contact information, information about children being checked into the nursery, etc.  No 2fa is supported as of yet.

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]

**Comment by stephengroat** [comment]
Ranks #149,199 on Alexa (https://www.domaintally.com/www/planning.center)

@Carlgo11, what do you think?

**Comment by thegeekkid** [comment]
Just some background; while it probably has relatively low traffic (at least compared to other websites), PCO is pretty much the "standard" of church planning software, and stores some pretty sensitive data and is a payment processor.  It's mainly the type of data that presents itself as a concern and why I submitted it.  :)

**Comment by stephengroat** [comment]
@thegeekkid I'm not against adding it, i'm just adding some extra info. I'd like a general guideline setup for the minimum Alexa rank (or some other metric) for sites to be added. Just some background info, that's all. trying to start a discussion

**Comment by thegeekkid** [comment]
@stephengroat , no worries... I understood that.  Just figured I should add some more information about it since not everyone would be familiar with it.  :)

Not a bad idea about a general guideline for a minimum rank.

**Comment by stephengroat** [comment]
@2factorauth/collaborators

**Comment by fpigerre** [comment]
Given that the service seems quite polished and professional, with potential for an increase in its Alexa ranking, I think it would be a good idea if twofactorauth.org listed this website. :+1:

**Pull request merged**
