### PR TITLE
Renamed sparbanken1826 to swedbank

### PR DESCRIPTION
**Pull request by Carlgo11**
Name changes... all these name changes...

### CODE REVIEW

**Comment by mxxcon** [comment]
what's the difference between them?
(forgot to rename the logo)

**Comment by Carlgo11** [comment]
New name. Bought up and merged

**Comment by jdavis** [comment]
Also, if they bought this bank up and merged them, where do you have a source on the merging of the names? It looks like both sites still exist and the old doesn't redirect or anything.

**Comment by Carlgo11** [comment]
@jdavis It's rather complicated. Swedbank owns all "sparbanken" banks but the different banks are operating separately.

Sparbanken1829 decided to merge with a group of other "sparbanken" banks. (Now calling themselves SparbankenSkåne)
To cover all banks I decided to just rename it to Swedbank.

**Comment by jdavis** [comment]
Okay, I can't comment much else on the correctness. Would this be ready to merge then?

**Comment by Carlgo11** [comment]
Yup. ready to merge

**Pull request merged**
