### PR TITLE
Add 20i

### PR DESCRIPTION
**Pull request by jimd20i**
Two-factor just added at 20i (Account Settings -> Security Details)

```
$ time bundle exec rake
Configuration file: ./_config.yml
            Source: ./
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 1.795 seconds.
Running ["ScriptCheck", "HtmlCheck", "ImageCheck", "LinkCheck"] on ["./_site"] on *.html... 


Ran on 8 files!


HTML-Proofer finished successfully.
/usr/bin/ruby ./verify.rb
<------------ No errors. You're good to go! ------------>
Running RuboCop...
Inspecting 3 files
...

3 files inspected, no offenses detected
```

### CODE REVIEW

**Review by mxxcon — APPROVED** [review]
Should it be under `domains` or `hosting` category?

**Review by Jawshy — COMMENTED** [review]
I think 20i should also be listed under hosting.

**Comment by jimd20i** [comment]
I just put it in the same file as all of 20i's principal competitors - Fasthosts, GoDaddy, Heart Internet, UK2. All of those (20i included) are principally web/email hosting providers so it's perfectly valid to have them in "hosting". It's in the spirit of the twofactorauth.org project to have companies listed with their principal competitors so wherever it ends up it would make sense for most of the named set to be together. I note that there aren't any companies that can reasonably be considered 20i competitors in hosting.yml!

**Review by jamcat22 — APPROVED** [review]
I think `domains` makes sense since they offer domain registration. For most other domain registrars that offer hosting services, we've put them under `domains`.

**Pull request merged**
