### PR TITLE
Add ieee

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by mxxcon** [comment]
How would this fit into our criteria?

**Comment by stephengroat** [comment]
IEEE stores payment information, IEEE Collabratec is their new social professional network feature. There's more I can list if needed

**Review by fpigerre — APPROVED** [review]

**Comment by Jawshy** [comment]
They have several contact and support email addresses listed [here](https://www.ieee.org/about/contact_center/index.html?WT.mc_id=hpf_contact) and I am not sure which one - if any - would be most appropriate to include.

**Comment by fpigerre** [comment]
For an organisation as large and with as broad-ranging responsibilities as the IEEE, I think it might be best to avoid listing an email address, as social media would be better suited. Otherwise, however, the following email address could be used: `contactcenter@ieee.org`.

**Comment by stephengroat** [comment]
decided not to list email

**Pull request merged**
