### PR TITLE
Add My Study Life

### PR DESCRIPTION
**Pull request by amazansky**
After accidentally trying to make a pull to someone else's repo (oops...), I am now suggesting My Study Life for the list.

I've been using My Study Life lately, so I thought it was a good idea to ask them for 2FA!

Thanks.

### CODE REVIEW

**Comment by amazansky** [comment]
Uh-oh, seems as if my file was too large. I'll adjust it.

**Comment by amazansky** [comment]
Okay, that should do it.

**Comment by jamcat22** [comment]
Please remove the `img/mystudylife.png` file.

I'm also curious as to whether or not it fits our [criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) for non-2FA websites.
Also, would this better fit in the `education` category?

**Comment by amazansky** [comment]
Thank you for the response!
Sorry for the extra file! I seem to be out of it...

I think MSL fits the criteria because of 1 (Info), and kind of 2 (Data).
1. My Study Life has quite a bit of info about you on file (not any more than most other websites, but as the internet grows bigger, privacy is becoming more important and less achievable...)
2. For Data, this might not exactly be what you had in mind, but if MyStudyLife were to give all the info they had about you to someone else, quite a bit of info about your education would be revealed.
2 (cont). This includes school, terms, subjects, teachers, homework, exams, etc.

Thanks for your opinion.

**Comment by amazansky** [comment]
Also, if you think it's better suited for education, I'll happily move it. I was just looking at things to compare it to and found Todoist, so I thought to should go here.

**Comment by Carlgo11** [comment]
No it's fine.

**Comment by amazansky** [comment]
Actually, I think it does belong under education, if you want me to move it.

**Comment by jamcat22** [comment]
I'd say go ahead an move it, @RobotXLabs!

**Comment by amazansky** [comment]
Will do!

**Comment by amazansky** [comment]
There. I think it's ready now.

**Comment by jamcat22** [comment]
Thanks for the PR, @RobotXLabs!

**Comment by amazansky** [comment]
No problem! I may come back if I have another idea.
Thanks to all of you guys for making this possible! The list is helpful!

**Pull request merged**
