### PR TITLE
Add Binary Lane

### PR DESCRIPTION
**Pull request by trogau**
Added Binary Lane entry to hosting config file & an icon.

### CODE REVIEW

**Comment by mxxcon** [comment]
`doc:` url?

**Comment by trogau** [comment]
Sorry, wasn't sure if doc was a hard requirement (there are some entries with no doc link). I'll get some documentation done and add it to the file.

**Comment by jdavis** [comment]
@trogau We try to enforce doc links where possible. And let us know when you update it.

**Comment by Carlgo11** [comment]
@trogau are you going to add the doc link?
If not then I'll close the PR to make our PR list a little bit smaller.

**Comment by trogau** [comment]
Yes I will - sorry! Slipped my mind. I'm actually traveling at the moment
and not back home for a week or so - I've added to calendar to sort this
out then. Apologies for delay!

## 

dave

**Comment by Carlgo11** [comment]
No worries.
I'm just cleaning up old PRs.

**Comment by Carlgo11** [comment]
@trogau *aheam*

**Comment by trogau** [comment]
Done, sorry for the delay! Actually got this mostly sorted yesterday but got stuck trying to figure out how to amend the pull request - might need some double checking to make sure I didn't screw anything up. 

Thanks & sorry again for the delay.

**Comment by jamcat22** [comment]
You can remove the twitter line, as they support 2FA.

**Comment by trogau** [comment]
Oops, done, thanks.

**Pull request merged**
