### PR TITLE
Add overstock

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by Carlgo11** [comment]
pssst
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>_(merge conflict)_

**Review by Carlgo11 — APPROVED** [review]

**Comment by stephengroat** [comment]
I know this is just a merge, but we should make sure that we push cancel out the "approved" changes mark as well. I'm surprised the merge didn't catch it

**Comment by Carlgo11** [comment]
@2factorauth/collaborators

**Comment by fpigerre** [comment]
@stephengroat, It looks like there's another merge conflict. Sorry, that might have been me merging other pull requests :sweat_smile:

**Comment by Jawshy** [comment]
I found a contact email for them [here](https://help.overstock.com/app/answers/detail/a_id/5751/). @stephengroat, would you like to add that? 

``` ruby
      email_address: international@overstock.com
```

**Review by Jawshy — CHANGES_REQUESTED** [review]
Resolving the merge conflict has disordered the alphabetical order (as detected by Travis). Please correct and commit.

**Review by Jawshy — APPROVED** [review]

**Pull request merged**
