### PR TITLE
add Hetzner (no image, no twitter)

### PR DESCRIPTION
**Pull request by rmoriz**
Add hosting provider Hetzner.
- Due to copyright law I'm not allowed to contribute a logo (#1038)
- They don't have an official twitter handle

### CODE REVIEW

**Comment by Carlgo11** [comment]
You could just email them and ask for permission to use their logo.
They seem to be pretty sharing friendly based on their picture archive for press members (https://www.hetzner.de/gb/hosting/presse/bildarchiv).
If you really don't want to contact them then I guess one of us could upload the picture. I'm not under German laws, neither is any other collaborator for this project.

**Comment by LeFouineur** [comment]
Here is one if you need it.

url

**Comment by Carlgo11** [comment]
@rmoriz have you contacted them yet?

(_If I don't get a response by Friday 2015-05-08 I'm closing this PR_)

**Comment by rmoriz** [comment]
got no reply/permission

**Comment by mxxcon** [comment]
@rmoriz If they will claim copyright on the logo they might as well claim copyright on their own name outright and any mention of it anywhere would be considered copyright violation.

**Comment by rmoriz** [comment]
@mxxcon it's only the logo - of course you can write/list ther name in any way you want unless you lie/claim incorrect things to harm the company

Just add the entry without the logo or read into european copyright laws

A logo doesn't provide any value to an entry. Neither will it be more informative than the name of the company nor will it provide any useful information about the support of a two-way-auth. It's just bikeshedding and will harm the project.

**Comment by Carlgo11** [comment]
Sounds like Germans are Copyright Nazis. Anyways, you don't have to contribute if you don't want to.
When adding a site to our list you are required to add a logo. If you don't then we can't add the site.
I'm closing this PR in favor of #1113.

**Comment by rmoriz** [comment]
I've asked OVH if they are fine with their logo beeing used on the site - maybe the French are "Copyright Nazis", too. See https://github.com/jdavis/twofactorauth/issues/1038#issuecomment-87158068

**Comment by Carlgo11** [comment]
They are. France have the most complicated copyright and privacy laws on earth. You're basically not allowed to take pictures of anything that someone have created and that isn't public property.

Tom Scott made a vlog about this recently. https://youtu.be/VYH87V6EHrk

**Comment by rmoriz** [comment]
So IMHO the project and the contributors are likley to be vulnerable facing legal issues without a real benefit.

The site's main purpose is to list companies/services that don't have 2FA and don't care - they will probably also not like to be listed and prefer to hide their (poor) security levels.

Sure, if you're not easy to catch and want to play the hard way, you can hope that it will trigger the Streisand-effect or submit an angry blog post to HN. For what? Just for some useless icon?

If you're would like to provide a real benefit, then add the date of "first question about 2FA-date" to show inactivity/unwillingness of companies to implement 2FA. 2FA is not the default but ignoring customers request and the industry move towards 2FA over a significant period of time is a real argument against using a service. And it doesn't even violate the copyright laws.

**Comment by Carlgo11** [comment]
That might be true but we'll handle that when/if that happens.

**Comment by mxxcon** [comment]
@rmoriz if you'd like to, we can chat about it on https://gitter.im/jdavis/twofactorauth

**Pull request closed without merging**
