### PR TITLE
Minify CSS and JavaScript

### PR DESCRIPTION
**Pull request by fpigerre**
This pull request minifies a number of CSS and JavaScript files, particularly those utilised as third party libraries. This pull request also updates jQuery to version 2.1.1 (minified).
This pull request affects issues #480 and #575.

An amazing tool I often use for image optimization is [Shrinkray.io](https://shrinkray.io/). This tool allows users to compress .png images contained in GitHub repositories with one click. It would quite likely be very useful for optimizing images when new listings are added to twofactorauth.org.

### CODE REVIEW

**Comment by fpigerre** [comment]
A breakdown of browser actions from the time the HTTP request was sent to the time the page finished loading can be seen below. This load preview was run in chrome and the HTTP request was sent to a web server running locally.

render

**Comment by fpigerre** [comment]
> Implement Luis Almeida's <1K lazy image loading library. The JavaScript
> code is configured so that the images will be unveiled 50px before the
> image is visible, when scrolled to on the page.

``` html
<noscript><noscript/>
```

No-script tags have also been implemented, so that users with JavaScript disabled are still able to view the site's images.

**Comment by mxxcon** [comment]
@psgs Shrinkray service looks interesting, but I doubt it spends as much CPU time per image as tools like http://css-ig.net/pngslim which use most of the projects from http://css-ig.net/png-tools-overview :wink:
Btw, would it make sense to move css/js to the top or bottom of the page?
There's also https://cdnjs.com/ which might be useful.
Can't wait to see the results of your effort! :)

**Comment by fpigerre** [comment]
Hello @mxxcon,

Wow! Thanks for sharing [PNG Tools Overview](http://css-ig.net/png-tools-overview) and [CDNJs](https://cdnjs.com/)!
Moving JavaScript and CSS tags vertically changes the order in which they are loaded. Placing a JavaScript tag within the head tag of an HTML file will cause the JavaScript content to be loaded as the page loads, however, placing it at the bottom will cause the JavaScript to load after the page has fully loaded.

At the moment, [Google Developers' PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftwofactorauth.org%2F&tab=desktop) states that some CSS in the head tag is causing render blocking, however, realistically, this can't be fixed effectively, due to the size of the CSS files.

Thanks,
psgs

**Comment by fpigerre** [comment]
Any thoughts on this pull request @jdavis?

**Comment by jdavis** [comment]
I think the minimized versions for various resources are a good idea :smile: 

Should this be merged or are you looking to add more to it?

**Comment by fpigerre** [comment]
It would be awesome if this pull request could be merged :smiley:

**Comment by Carlgo11** [comment]
@psgs while you're waiting, https://www.youtube.com/user/whatever/videos

**Pull request merged**
