### PR TITLE
Adds Strava.

### PR DESCRIPTION
**Pull request by RobFreiburger**
Resolves issue #186

### CODE REVIEW

**Comment by mpdavis** [comment]
Looks good.

**Comment by jdavis** [comment]
It looks like the tabs broke the build. I know it wasn't your fault, Michael. For some reason Travis has been lagging a bit and the build status hasn't been showing up quick enough. I fixed it though, no worries.

**Comment by jdavis** [comment]
Just a note @RichJeanes @zach-taylor @mpdavis @computmaxer, for some reason Travis has been slow, don't merge until the Travis status updates here: https://travis-ci.org/jdavis/twofactorauth/pull_requests

I've made the mistake a couple times because of this =[

**Comment by computmaxer** [comment]
Duly noted!

**Pull request merged**
