### PR TITLE
Add Wasabi

### PR DESCRIPTION
**Pull request by radeksimko**
I'm aware there was a PR for Wasabi https://github.com/2factorauth/twofactorauth/pull/2998 which was closed mainly because Wasabi wasn't so popular back then.

According to current Alexa rank the site became a lot more popular in the past year and now fits within the "200k or less rank" bracket.

https://www.alexa.com/siteinfo/wasabi.com

### CODE REVIEW

**Comment by Carlgo11** [comment]
If I'm understanding the documentation page correctly 2FA is only available for a "root user".
If that's the case then an exception text would be good.
Something like 
```YAML
exception:
  - text: "2FA only available for the Root User."
```

**Comment by radeksimko** [comment]
@Carlgo11 To my knowledge MFA is available for users too:

Screenshot 2019-03-25 at 11 14 57

but I wasn't able to find any publicly-linkable documentation for it unfortunately 😞

**Comment by Carlgo11** [comment]
Ah okay. That’s fine then

**Review by jtagcat — CHANGES_REQUESTED** [review]
Image is not below 1.5kb.

**Review by jtagcat — CHANGES_REQUESTED** [review]
wasabi
png could be 60% smaller, use this

**Comment by radeksimko** [comment]
@vc7ee @Carlgo11 PTAL

**Review by jtagcat — APPROVED** [review]

**Review by kmpoppe — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
