### PR TITLE
Added Psono

### PR DESCRIPTION
**Pull request by chickahoona**

### CODE REVIEW

**Comment by hkamran80** [comment]
Hello @chickahoona,

Unfortunately, as this site is below our minimum [Similarweb](https://www.similarweb.com/website/psono.com/#overview) global rank of 200,000, this site cannot be added. This rule is in place because maintaining the lists takes time, and a list of all websites on the internet just isn't feasible. Once it reaches the minimum, please open a pull request.

In the future, please review our [site guidelines](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) and [exclusion list](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md) before adding a site.

**Comment by chickahoona** [comment]
Hm sad but okay. Regardin the checking of guidelines to make sure one has a 200.000 rank on similarweb. The service is not publicly available so how is someone supposed to check it?

**Comment by hkamran80** [comment]
The ranking is based on the primary website, in this case, `psono.com`. Additionally, this service meets the [self-hosted service exclusion](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md#self-hosted-services).

**Comment by chickahoona** [comment]
Thanks. I am not sure how that answers the "how can I check my ranking if similarweb isn't free to use". And in regards to your second point. We do have a free hosted version with https://psono.pw (and SaaS editions)

**Comment by hkamran80** [comment]
Similarweb is free to use. You may need an account, but it is free.
Given that `psono.pw` also doesn't mean our threshold, it can't be added at this time. Once either `psono.com` or `psono.pw` reach the threshold, please open a new PR.

**Pull request closed without merging**
