### PR TITLE
Add a column for account recovery documentation

### PR DESCRIPTION
**Pull request by runasand**
Two-factor authentication is great until you lose the device. I wanted to help users get through the recovery process faster by specifically linking to the recovery documentation for the different services.

### CODE REVIEW

**Comment by mxxcon** [comment]
I can't tell from the code what it'll look like. Is it another checkmark?
Also do you think users would come to this site to look for a way how to recover their account?
It's a useful information, but I'm not sure users will refer to this site when they lose their phone..I just don't have a sense this is the type of user-workflow we have(not that I know what kind of flow we do have :smile:)

**Comment by runasand** [comment]
A new column is added on the right and the icon used is the same as for "Docs."

I think the same users who use the site now would use the site to find account recovery information. It seemed silly to create a new site just for that purpose, when twofactorauth.org is already a well-known page. I know I, personally, would use it if I ever lost my phone and had to go through the process for all the services I use.

**Comment by gcochard** [comment]
This is really useful. Would have saved me hours when getting a replacement phone. If someone comes to the site to learn how to add 2fa, they will know where to go when (not if) they need to recover. :+1: :clap:

**Comment by thorsheim** [comment]
I doubt normal users will visit this site to find links to relevant account recovery docs, but for anyone developing or comparing services, this would be a great addition to the site. Also for all of us who nags service providers to improve their security, this addition will also be useful.

**Comment by Carlgo11** [comment]
We (the collaborators) will discuss whether or not to add this, but right now we're focusing on updating the site.

**Comment by Carlgo11** [comment]
Hi again Runa,
thank you for your patience and dedication towards making the site better.

We've now discussed this and come to the conclusion that this wouldn't look good for mobile users.
The current layout is a mess for mobile users and this would unfortunately make it look worse for them.

While we all think the idea behind your PR is a great idea we'll have to pass at this time.
I apologize for not being able to merge this after all the work you've done.

<i>//Carl</i> :snowman: 
<br>
<i>P.S. I like your name. It's very old school Nordic</i> :wink:

**Comment by jamcat22** [comment]
@carlgo11 I think we should merge it, because we would need the extra column to determine how to make responsive tables work.

**Comment by Carlgo11** [comment]
What, you said you agreed with Rich yesterday o.o

**Comment by jamcat22** [comment]
I said "I agree with Rich. I love the idea, but we'll need to fix responsive tables if we add it."
I meant we should add it, and then fix responsive tables.

**Comment by RichJeanes** [comment]
Also, to be clear and not give the wrong impression to the public community, I said I really like the idea, but think the site is too cumbersome on mobile to be adding more to it. If we improve the mobile performance of the site (and other usability improvements along the way would not be a bad thing), I would love to see this feature.

**Comment by jamcat22** [comment]
Hello @runasand!

We're in the process of redesigning the overall look of the site (currently the `alternate-layout` branch), so I'm sorry that there hasn't been any activity on this PR in awhile.
With the new design, we should be able to include account recovery documentation without it being cumbersome on mobile device layouts.
There's still a bit of debate on whether or not we should add this, but if we choose to, it could take anywhere from a couple weeks to a month.

Thanks!

**Review by gingerbeardman — APPROVED** [review]

**Pull request closed without merging**
