### PR TITLE
Add Cloud9

### PR DESCRIPTION
**Pull request by dsoegijono**
TFA available if you sign up using GitHub account, but not for email signups. Do we mark this as `yes` or `no`?

### CODE REVIEW

**Comment by Carlgo11** [comment]
I'd say `no`

**Comment by mxxcon** [comment]
Ya, I'd say it's a similar situation as with sites that support SSO.
Also maybe use this logo instead?
cloud9
Your current logo has white clouds on transparent background, which in our case will be white background. My picture above has a slight outline. :smile:

**Comment by dsoegijono** [comment]
@mxxcon Thanks! Image changed. They also have a blue cloud logo:
cloud9-blue

Would that be better?

**Comment by mxxcon** [comment]
yup, either one would be better than white on white :smile_cat:

**Comment by jdavis** [comment]
Feel free to swap with the blue if you don't think it looks good; there's no need for a PR either: https://twofactorauth.org/#developer

**Pull request merged**
