### PR TITLE
Facebook: more than one phone number permitted per account

### PR DESCRIPTION
**Pull request by tvierling**

### CODE REVIEW

**Comment by mxxcon** [comment]
wait, you can now add more than 1 phone number to an account?

**Comment by tvierling** [comment]
Yes, you can (and this has been true for a long time).

**Comment by jamcat22** [comment]
Yep. Even before Login Approvals were a thing. I remember when they just had Login Notifications and not Login Approvals.

**Comment by mxxcon** [comment]
@jamcat22 in #1250 you added 1 number per account. was that info wrong?

**Comment by jamcat22** [comment]
Yes. I was thinking about Twitter when I made that PR. :laughing:
Mistake on my part. They do only allow 1 account per phone number though.

**Comment by fpigerre** [comment]
Thanks for the pull request @tvierling! :+1:

**Pull request merged**
