### PR TITLE
Added Bitreserve

### PR DESCRIPTION
**Pull request by jamcat22**
Added Bitreserve to Bitcoin.
They do not support phone call verification.
See #908.

[Review on Reviewable](https://reviewable.io/reviews/jdavis/twofactorauth/1253)

### CODE REVIEW

**Comment by Carlgo11** [comment]
Wow look how much I managed to save :open_mouth: 
bitreserve 1

**Comment by Carlgo11** [comment]
Apparently allows phone calls as well.
screenshot

**Comment by mxxcon** [comment]
+looks-good 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jdavis/twofactorauth/1253)

**Comment by jamcat22** [comment]
@Carlgo11 Ok. I'll use the new logo in a bit.

When I tried their login, they don't support phone call.

**Comment by jamcat22** [comment]
image

**Comment by jamcat22** [comment]
@Carlgo See? I'm not crazy. Even if I was doing all of this at like 2am

**Comment by Carlgo11** [comment]
Not entirely at least :heart:

**Comment by RichJeanes** [comment]
So @Carlgo11 was able to request a phone call but @jamcat22 was not? What's up with that?

**Comment by Carlgo11** [comment]
no I just looked at the initial PR.
https://github.com/jdavis/twofactorauth/pull/908

**Comment by RichJeanes** [comment]
Ah, okay.

**Pull request merged**
