### PR TITLE
Add FetLife

### PR DESCRIPTION
**Pull request by reneklacan**
# Screenshots

## Login

image

## Setup

image
image

### CODE REVIEW

**Comment by Carlgo11** [comment]
We don't list explicit content on twofactorauth.org as it could harm our reputation with firewalls/content-blockers and wouldn't be fair to our maintainers who have to review the sites on our lists.

**Comment by reneklacan** [comment]
@Carlgo11

Can you please reconsider your decision? We just not just any porn site, we are a social network with [Alexa rank](https://www.alexa.com/siteinfo/fetlife.com) 501 in the US and TOP 2000 globally.

image

> We don't list explicit content on twofactorauth.org

Can you please share where do you state that you are not listing explicit content?

> it could harm our reputation with firewalls/content-blockers 

Can you please explain to me how it can harm your reputation?

> wouldn't be fair to our maintainers who have to review the sites on our lists.

I'm sure some of your maintainers are our members!

**Comment by Carlgo11** [comment]
@reneklacan the policy won't change in the near future. Sorry about the inconvenience.

**Comment by reneklacan** [comment]
@Carlgo11 Can I see the link to the policy?

**Comment by Carlgo11** [comment]
@reneklacan it's on the maintainer Slack. Writing it down publicly is on my to-do list.

**Comment by reneklacan** [comment]
@Carlgo11 While putting it together, please try to be accurate and consider doing some research on this subject because some information you provided on this thread clearly shows that personal bias is involved in the decision making and you are making things up to make it look justified.

I think, in some cases, you might be mixing up widely popular explicit sites with shady porn sites with adware.

**Pull request closed without merging**
