### PR TITLE
Add Twitter, CloudFlare, Coinbase. Add support for Authy

### PR DESCRIPTION
**Pull request by zach-taylor**
The three sites that I added still need images.

Authy is an alternative to Google Authenticator and has a lot more features so I thought it would be a  good idea to add it as well.

### CODE REVIEW

**Comment by jdavis** [comment]
For Twitter, you can generate a 2FA code with the app?

**Comment by zach-taylor** [comment]
Yeah, it seems that way

screenshot 2014-03-15 18 41 44

**Comment by jdavis** [comment]
Ahhh, I was just looking around for it but missed that. Awesome.

**Comment by jdavis** [comment]
Awesome. Before you merge into `gh-pages`, I saw a little issue with one of the tables, but I'll fix that up. Other than that, A++++ would merge again.

**Comment by zach-taylor** [comment]
Sounds good!

**Pull request merged**
