### PR TITLE
Update Boston University

### PR DESCRIPTION
**Pull request by hkamran80**
BU supports U2F through Duo

### CODE REVIEW

**Comment by Carlgo11** [comment]
I don't see any mentions of U2F on the documentation page :thinking:

**Comment by hkamran80** [comment]
They mention YubiKeys in the FAQ.
> **What is a Yubikey and how does it work with Duo?**
> A Yubikey is a small hardware device (think USB stick) that supports two-factor authentication. A Yubikey can be plugged into your computer's USB port or "tapped" on your device (if supported) to verify your login. A Yubikey is another method you can use to access Duo! Yubikeys can be purchased from Amazon or directly from the Yubico.

**Comment by Carlgo11** [comment]
It's unclear to me if that statement is about U2F or Yubico OTP as Duo supports integrations with both.

**Comment by hkamran80** [comment]
Ah

**Comment by hkamran80** [comment]
This [page](https://www.bu.edu/tech/support/duo/enroll-device/) shows "Security Keys" in Duo's enroll section.

**Comment by Carlgo11** [comment]
Thanks for the link! :+1:

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
