### PR TITLE
Adding Formstack.com to the "Other" category

### PR DESCRIPTION
**Pull request by asirota**
Formstack.com just added 2FA...

### CODE REVIEW

**Comment by mxxcon** [comment]
Should it be `other` or `developers` category?

**Comment by Carlgo11** [comment]
the url should be `https://www.formstack.com/`

**Comment by Carlgo11** [comment]
and remove `email`, `phone` and `hardware`. It's just taking up space

**Comment by asirota** [comment]
@mxxcon I don't think it's a Developer tool as there is no coding involved, but I am not sure how you all are defining the developer category of products. It's a productivity app most of all.

@Carlgo11 will fix up the other items...

**Comment by asirota** [comment]
edited @Carlgo11 suggestions

**Comment by Carlgo11** [comment]
Thank you for contributing to the project @asirota!
Your pull request looks good. When it's been merged by another contributor it will take about 1-2 days for Josh (the owner) to check that everything looks good before he merges everything to the live site.

**Comment by asirota** [comment]
Guys -- I think this is a terrific idea and very much needed. With all the problems with passwords, seems like 2FA is an absolute must for a certain subset of the websites and apps out there. Happy I can help -- we run about 7 different apps for our business and only Formstack and Google Apps are using 2FA...

**Pull request merged**
