### PR TITLE
Added Pocket to Social

### PR DESCRIPTION
**Pull request by whatinthenameofgod**

### CODE REVIEW

**Comment by whatinthenameofgod** [comment]
Looks like I accidentally added a second site to this request.

How can I keep these PR separate? Do I have to fork for every single PR?

**Comment by mxxcon** [comment]
If you make separate pull requests for each site, you'll need to create separate branches in your repo, make changes there and then create pull requests from those branches.

**Comment by jamcat22** [comment]
You might want to use [branches](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/) so that you can propose multiple changes

**Comment by whatinthenameofgod** [comment]
Got it. I'm learning! Thank you! Is this PR okay to leave even though I accidentally tossed two in or should I redo it?

**Comment by dsoegijono** [comment]
I don't know if this has been discussed before, but is Pocket really a `Social` site? I would say it fits better in `Backup & Sync`? Or even `Other`...

**Comment by whatinthenameofgod** [comment]
Yeah, backup and sync also makes sense. Although it seems they're trying to get more and more into the social arena which I don't care for at all. Stick to what you do best!

**Comment by mxxcon** [comment]
I'd think Pocket should be in `other`, and even then I'm not sure if it makes sense to list it...It's essentially a fancy bookmark site.

**Comment by jamcat22** [comment]
I'd say it should be in `Other`, as Pinboard is there also.

**Comment by Carlgo11** [comment]
Size reduced from 16kb to 654b.
pocket 1

**Comment by jamcat22** [comment]
Thanks @Carlgo11. When I resized the new image, I forgot to upload the compressed version. :laughing:

**Comment by whatinthenameofgod** [comment]
Going to kill these and resubmit as individual.

**Pull request closed without merging**
