### PR TITLE
Add Segment

### PR DESCRIPTION
**Pull request by Rowno**

### CODE REVIEW

**Comment by kmpoppe** [comment]
Hello @Rowno and thank you for your contribution. You've added Segment to the developer section, yet I fail to understand what they really do as a product. Could you please elaborate?
// Kai

**Comment by Rowno** [comment]
Segment is a service for routing user analytics data from multiple sources to multiple destinations. For example, using the Javascript library you could track some user events on the frontend and Segment will route the track events to all the third party tools you use (like Google Analytics, Mixpanel, Amplitude, Mailchimp, data warehouses, etc) without you having to go through all the complexities of integrating with each third party API.

**Review by dsoegijono — DISMISSED** [review]

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
While it's not a perfect fit, I think hosting fits Segment better than developer.
The developer category is for things like Visual Code Studio, Jetbrains, Unity, GitHub etc.

**Comment by Rowno** [comment]
Done!

**Comment by Carlgo11** [comment]
Looks like 2FA is only available for business accounts with third party authentication (such as G-suite, Okta etc). Is that correct?

**Comment by Rowno** [comment]
Nope, MFA (OTP and SMS) is available for all accounts. Only SSO (single sign on via a third party) is restricted to business tier accounts.

**Review by Carlgo11 — APPROVED** [review]

**Review by kmpoppe — APPROVED** [review]

**Pull request merged**
