### PR TITLE
List of supported carriers by Apple SMS.

### PR DESCRIPTION
**Pull request by mxxcon**
Addresses #623

### CODE REVIEW

**Comment by jdavis** [comment]
Should we format this link as clickable? Putting `<a>` tags around the link should work. It's just up to us whether or not we want that in the YAML...

**Comment by mxxcon** [comment]
I don't think clickable link will work with the current implementation.
The moment you move mouse away from ! popup disappears....people can't even copy/paste plain text from it. :/

**Comment by jdavis** [comment]
Ah yes, I forgot I picked "on hover" instead of on click. I tried out both.

The popups can be configured to either be on click or on hover: http://semantic-ui.com/modules/popup.html#/settings

**Comment by mxxcon** [comment]
Is this still relevant or was it resolved in another PR?

**Comment by jdavis** [comment]
As far as I can tell it is still relevant. I didn't merge it because I didn't know if you wanted to address the link issue. One possible solution is to allow configuration of the popover to be on click instead of on hover.

I could do this if you didn't want to; I just won't get to it until this weekend as I just started a new job on Monday. Just let me know, @mxxcon. :smile:

**Comment by mxxcon** [comment]
Can we make it so that on hover text box expands, but also be able to attach a url to it for click?
Or would that be too obscure for users to realize?

**Comment by jdavis** [comment]
What about just making it "onclick" instead of "onhover"? Then the icon would be clicked on and wouldn't go away until a click outside of the box?

Take a look at the first example with the button "Click Me": http://semantic-ui.com/modules/popup.html#/examples

**Comment by mxxcon** [comment]
Is it going to be for all or only the ones that have links?

**Comment by jdavis** [comment]
We could have it be configurable. Do you think it'll be too strange to have different behaviors for identical icons though?

**Comment by mxxcon** [comment]
Yes, perhaps. I'm just worried about discoverability of on-click action. It's hard for me to judge what a new user would experience.

**Comment by dsoegijono** [comment]
Can it be both? On-click and on-hover opens the popup, so it's the same as others but also clickable.

**Pull request closed without merging**
