### PR TITLE
Add PAYEER

### PR DESCRIPTION
**Pull request by Nicos18**

### CODE REVIEW

**Comment by stephengroat** [comment]
i cannot check without moving my ip outside of the us

**Review by mxxcon — CHANGES_REQUESTED** [review]
This logo doesn't have that white line under P.
payeer

**Review by mxxcon — COMMENTED** [review]
How did you find that sms cost $0.05? I tried browsing their site, but it's very sparse.
Also what do you mean by the word "personalizable"?

**Comment by Nicos18** [comment]
Unfortunately, these info are only reported after logging in. In the screenshots, there is the $0.05 cost for SMS, and for personalizable I intend the fact that you choose if you receive a code or not, as shown in the screenshots

payeer_2fa1
payeer_2fa2
payeer_2fa3

**Comment by mxxcon** [comment]
If it uses `Telegram` to deliver 2fa codes then I think it should also be `software: yes`

**Review by mxxcon — APPROVED** [review]

**Review by jamcat22 — APPROVED** [review]

**Pull request merged**
