### PR TITLE
Update Bendigo Bank

### PR DESCRIPTION
**Pull request by willidb**

### CODE REVIEW

**Comment by phallobst** [comment]
According to the original PR #4718, the "security token" is only used for _authorization_, but not _authentication_. Has anything changed in this regard?

**Comment by willidb** [comment]
The TOTP provided by the Security Token (Symantec VIP) may be configured by the user to be required at login in addition to User ID and Password. The Security Token is also used for step-up authentication commensurate to sensitivity of transaction. However having reviewed the PR https://github.com/2factorauth/twofactorauth/pull/2973 I now understand that the 2factorauth project defines _step-up authentication_ as a form of _authorisation_. Hopefully this definition will be amended. Irrespective of the _step-up authentication_ definition, does configurable (optional) enforcement of the Security Token at login meet guidelines?

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
>[...] does configurable (optional) enforcement of the Security Token at login meet guidelines?

Yes if it is required at the login stage it would qualify. Just make sure to link to documentation describing how to set it up and add a 'note' briefly explaining what actions need to be taken for 2FA to be used instead of 2SV.

You've added 'totp' as an option. Is it actual RFC-6238 TOTP authentication or does it require certain apps? If only certain apps are supported, change the 'totp' option to 'custom-software' and make a custom-software array containing the name(s) of the supported app(s). Read the 'custom-hardware'/'custom-software section' of [CONTRIBUTING.md#other-properties](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#other-properties) for more information on how to specify custom-software.
A Semantic VIP hardware key is also mentioned on the documentation page. Please add a 'custom-hardware' property accordingly.


Lastly, the build is failing because the contact element still is present. Please remove that section from the entry.

**Comment by Carlgo11** [comment]
As the requested changes haven't been resolved yet I'm going to label this PR as inactive.
Unless there's activity within the next week I'll close the PR.

**Comment by Carlgo11** [comment]
Closing due to inactivity.

**Pull request closed without merging**
