### PR TITLE
Rename ZenPayroll to Gusto

### PR DESCRIPTION
**Pull request by VoidingWarranties**
ZenPayroll have rebranded themselves as Gusto.
See https://zenpayroll.com/blog/introducing-gusto/

I ran `optipng -o7` on the icon, but its still one of the largest icons despite being a simple design. Oh well.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Here, try this image instead:
gusto
I ran it through [tinypng.com](https://tinypng.com/) 😉

**Comment by Jawshy** [comment]
Reading the PR number like: 
john oliver - it s 2015 right now - optimised

**Comment by VoidingWarranties** [comment]
Thanks, I amended the commit to use that file.

**Review by stephengroat — APPROVED** [review]

**Comment by fpigerre** [comment]
Thanks for the pull request @VoidingWarranties! :+1:

**Pull request merged**
