### PR TITLE
Add College of DuPage

### PR DESCRIPTION
**Pull request by thegeekkid**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]

**Comment by stephengroat** [comment]
@thegeekkid could you merge? thanks!

**Comment by thegeekkid** [comment]
@stephengroat Should be good now.  Seemed to merge without any issues on my end.

**Comment by stephengroat** [comment]
I don't know if you caught the merge that time. Try this:

```
git clone https://github.com/thegeekkid/twofactorauth -b add-cod
cd twofactorauth
git pull https://github.com/2factorauth/twofactorauth master
```

**Comment by thegeekkid** [comment]
Ahh.  Yep.  Somehow it didn't pull down CompTIA.  Must have pulled down my repo instead of the upstream by mistake.

**Comment by stephengroat** [comment]
@2factorauth/collaborators

**Pull request merged**
