### PR TITLE
Added Clio law practice software to "Other".

### PR DESCRIPTION
**Pull request by plecavalier**
As per requested, separated my PRs.

### CODE REVIEW

**Comment by RichJeanes** [comment]
You separated the sites into separate commits, but this it still one pull request. To make them into separate PRs you need to make the changes on two different branches in your local repo and submit both branches as PRs to the project.

**Comment by plecavalier** [comment]
I thought I was doing that when I pushed the separate commits...I realized
I was wrong when I pushed them and the merged into the same request. So how
do I separate the branches exactly? And while we're there, how do I reset?

Thanks! Phil
Ottawa: 613-851-2926
Cornwall: 613-703-0115

Any distribution, use or copying of this e-mail or the information it
contains by other than the intended recipient(s) is unauthorized.

**Comment by RichJeanes** [comment]
Our time spent on the project as collaborators is all volunteered and is focused on the project itself. There are lots of wonderful Git tutorials around the internet. Look into creating new branches for each then submitting the PRs should be simple once you push the repo to GitHub.
Also, looking at the Travis results, the build is failing because you are missing the img tag for Clio.
Thank you for contributing! We love to see new people joining the open-source community.

**Comment by mxxcon** [comment]
@plecavalier You should have created 2 separate branches in your repo, make each site's change in its own branch and then create 2 pull requests from those branches.

**Pull request closed without merging**
