### PR TITLE
Add Best Buy

### PR DESCRIPTION
**Pull request by Rfosu2k2**
Correct Implementation of Best Buy from #4043

### CODE REVIEW

**Comment by Rfosu2k2** [comment]
I was trying to add each new site as its own pull, but somehow they got added into this pull.

**Comment by Carlgo11** [comment]
@rfosu2k2 you've made the commits on the master branch. When you're going to make a change, make a new branch on github or on your git client.
create branch

**Comment by Carlgo11** [comment]
I cleaned up this PR.

**Comment by Rfosu2k2** [comment]
I apparently either needed to wait for the best buy commit to be merged and refresh my fork, or close this pull and start over to get any additional pulls to correctly commit without adding into this one.

**Comment by Carlgo11** [comment]
That's correct.

**Comment by Rfosu2k2** [comment]
Going to close this to avoid the mess.  Sorry for the confusion, and thanks for your patience.

**Pull request closed without merging**
