### PR TITLE
Add Tipico

### PR DESCRIPTION
**Pull request by bennetfabian**
- [ ] Check in other regions
- [ ] Find contact email

### CODE REVIEW

**Comment by bennetfabian** [comment]
Hmm, test fails saying TFA field is missing. I thought when there is a contact field there should of course not be a TFA field?

**Comment by Carlgo11** [comment]
@bennetfabian that's because you used the `notes` tag which only can be used when a `tfa` tag is present.

**Comment by bennetfabian** [comment]
> @bennetfabian that's because you used the `notes` tag which only can be used when a `tfa` tag is present.

Oops. Well the information in the notes tag might still actually be useful if not necessary.

**Comment by Carlgo11** [comment]
That may be. I'm just telling you why the build fails :shrug: 
The Twitter handle is also incorrectly capitalized and the domain is ranked above 200K on Alexa (See [guidelines](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines))

**Comment by 40504** [comment]
@bennetfabian Try `tipico.de` Alexa ranking is below 200k

**Pull request closed without merging**
