### PR TITLE
Added NBX.com

### PR DESCRIPTION
**Pull request by o-l-a-v**
Added NBX.com

### CODE REVIEW

**Comment by o-l-a-v** [comment]
image

**Comment by Carlgo11** [comment]
Hei Olav! Did you have a question or you figured it out?

**Comment by o-l-a-v** [comment]
I read the output as nbx.com did not score high enough to be added to this repo?

**Comment by hkamran80** [comment]
You're correct. Once it reaches the minimum global rank of 200,000, it can be resubmitted. Thanks for contributing!

**Pull request closed without merging**
