### PR TITLE
Add SmartBox

### PR DESCRIPTION
**Pull request by panterranetworks**
PanTerra Networks delivers SmartBox - File Sharing that Communicates.  Our service provides full 2-factor authentication and should be listed in the Backup and Storage category.

### CODE REVIEW

**Comment by mpdavis** [comment]
You have SMS marked as "no", but the document you linked seems to suggest that they do offer SMS 2FA.

**Comment by panterranetworks** [comment]
https://sbdownload.unifiedcloudit.com/olafld/czR2NGE0dTd4aTV3
smartbox.ico

 https://sbdownload.unifiedcloudit.com/olafld/czR2NGE0dTd4aTV3
https://sbdownload.unifiedcloudit.com/olafld/czR2NGE0dTd4aTV3

Start sharing with  http://www.panterranetworks.com/SmartBox/signup.php
SmartBox today!

I wasn't sure what that means?  We do not do the authentication through SMS.
We do it through email since everyone might not have their phone with them.
If that column means do we support 2FA for our SMS service then the answer
would be yes, but that' s not how I interpreted the column.

Separately I wasn't sure how to upload the smartbox icon so I'm attaching it
here (thru smartbox!)

Arthur Chang

President and CEO

artiechang@panterranetworks.com

650.980.0688 (Direct)

 http://smartbox.unifiedcloudit.com/guest smartbox_logo_only_100

 https://accounts.unifiedcloudit.com/auth/webstore/signup.jsp Signup for
14 day no risk trial or  https://smartbox.unifiedcloudit.com/guest Signup
for a FREE guest account

The most secure, business-class, cloud file sharing service with built-in
communications

Panterra_newest_logo150

PanTerra Networks, Inc. - The Unified Cloud Service Provider

http://www.panterranetworks.com http://www.panterranetworks.com/ 

4655 Old Ironsides Dr., Suite 300, Santa Clara, CA 95054

800.805.0558 (Main)  | 408.329.1683 (Fax)

This message (including any attachments) is confidential and may be
privileged. If you have received it by mistake please notify the sender by
return e-mail and delete this message from your system. Any unauthorized use
or dissemination of this message in whole or in part is strictly prohibited.
Please note that e-mails are susceptible to change. PanTerra Networks, Inc.
shall not be liable for the improper or incomplete transmission of the
information contained in this communication nor for any delay in its receipt
or damage to your system. PanTerra Networks does not guarantee that the
integrity of this communication has been maintained nor that this
communication is free of viruses, interceptions or interference.

**Comment by mpdavis** [comment]
@panterranetworks Looks like I just misunderstood the document.  

That only other thing I see is that you are referencing `smartbox.png` which doesn't actually exist.

**Comment by panterranetworks** [comment]
Can I reference the smartbox.ico file?  If not I can create a smartbox.png file.  How do I upload to github?

Thanks
Artie

Arthur Chang

President and CEO

 mailto:artiechang@panterranetworks.com artiechang@panterranetworks.com

650.980.0688 (Direct)

 http://smartbox.unifiedcloudit.com/guest smartbox_logo_only_100

 https://accounts.unifiedcloudit.com/auth/webstore/signup.jsp Signup for 14 day no risk trial or  https://smartbox.unifiedcloudit.com/guest Signup for a FREE guest account

The most secure, business-class, cloud file sharing service with built-in communications

Panterra_newest_logo150

PanTerra Networks, Inc. - The Unified Cloud Service Provider

 http://www.panterranetworks.com/ http://www.panterranetworks.com

4655 Old Ironsides Dr., Suite 300, Santa Clara, CA 95054

800.805.0558 (Main)  | 408.329.1683 (Fax)

This message (including any attachments) is confidential and may be privileged. If you have received it by mistake please notify the sender by return e-mail and delete this message from your system. Any unauthorized use or dissemination of this message in whole or in part is strictly prohibited. Please note that e-mails are susceptible to change. PanTerra Networks, Inc. shall not be liable for the improper or incomplete transmission of the information contained in this communication nor for any delay in its receipt or damage to your system. PanTerra Networks does not guarantee that the integrity of this communication has been maintained nor that this communication is free of viruses, interceptions or interference.

**Comment by mpdavis** [comment]
We would prefer a .png. 

Image files are uploaded the same way all other files are uploaded, that is checked in and pushed.  If you aren't familiar with using git, you can give me a link and I can push it for you.

**Comment by panterranetworks** [comment]
https://sbdownload.unifiedcloudit.com/olafld/MWp5Z2p6MzM4NG54dQ
smartbox_icon20.png

 https://sbdownload.unifiedcloudit.com/olafld/MWp5Z2p6MzM4NG54dQ
https://sbdownload.unifiedcloudit.com/olafld/MWp5Z2p6MzM4NG54dQ

Start sharing with  http://www.panterranetworks.com/SmartBox/signup.php
SmartBox today!

 https://sbdownload.unifiedcloudit.com/olafld/MWlleTl0Ym42bTVpOQ
smartbox_icon16.png

 https://sbdownload.unifiedcloudit.com/olafld/MWlleTl0Ym42bTVpOQ
https://sbdownload.unifiedcloudit.com/olafld/MWlleTl0Ym42bTVpOQ

Start sharing with  http://www.panterranetworks.com/SmartBox/signup.php
SmartBox today!

Hi Mike,

If you can point me to the instructions on how to check in and push I will
do it, otherwise, I have attached a 16 x 16 version and a 20 x 20 version

Thanks
Artie

Arthur Chang

President and CEO

artiechang@panterranetworks.com

650.980.0688 (Direct)

 http://smartbox.unifiedcloudit.com/guest smartbox_logo_only_100

 https://accounts.unifiedcloudit.com/auth/webstore/signup.jsp Signup for
14 day no risk trial or  https://smartbox.unifiedcloudit.com/guest Signup
for a FREE guest account

The most secure, business-class, cloud file sharing service with built-in
communications

Panterra_newest_logo150

PanTerra Networks, Inc. - The Unified Cloud Service Provider

http://www.panterranetworks.com http://www.panterranetworks.com/ 

4655 Old Ironsides Dr., Suite 300, Santa Clara, CA 95054

800.805.0558 (Main)  | 408.329.1683 (Fax)

This message (including any attachments) is confidential and may be
privileged. If you have received it by mistake please notify the sender by
return e-mail and delete this message from your system. Any unauthorized use
or dissemination of this message in whole or in part is strictly prohibited.
Please note that e-mails are susceptible to change. PanTerra Networks, Inc.
shall not be liable for the improper or incomplete transmission of the
information contained in this communication nor for any delay in its receipt
or damage to your system. PanTerra Networks does not guarantee that the
integrity of this communication has been maintained nor that this
communication is free of viruses, interceptions or interference.

**Comment by jdavis** [comment]
https://help.github.com/

If you figure it out, feel free to open up another pull request.

**Comment by panterranetworks** [comment]
Hi Michael,

I noticed the list was significantly increased recently, but our company was not added?  Is there something else you need to add us to the list?

Thanks

Artie

Arthur Chang

President and CEO

 mailto:artiechang@panterranetworks.com artiechang@panterranetworks.com

650.980.0688 (Direct)

 http://smartbox.unifiedcloudit.com/guest smartbox_logo_only_100

 https://accounts.unifiedcloudit.com/auth/webstore/signup.jsp Signup for 14 day no risk trial or  https://smartbox.unifiedcloudit.com/guest Signup for a FREE guest account

The most secure, business-class, cloud file sharing service with built-in communications

Panterra_newest_logo150

PanTerra Networks, Inc. - The Unified Cloud Service Provider

 http://www.panterranetworks.com/ http://www.panterranetworks.com

4655 Old Ironsides Dr., Suite 300, Santa Clara, CA 95054

800.805.0558 (Main)  | 408.329.1683 (Fax)

This message (including any attachments) is confidential and may be privileged. If you have received it by mistake please notify the sender by return e-mail and delete this message from your system. Any unauthorized use or dissemination of this message in whole or in part is strictly prohibited. Please note that e-mails are susceptible to change. PanTerra Networks, Inc. shall not be liable for the improper or incomplete transmission of the information contained in this communication nor for any delay in its receipt or damage to your system. PanTerra Networks does not guarantee that the integrity of this communication has been maintained nor that this communication is free of viruses, interceptions or interference.

**Pull request closed without merging**
