### PR TITLE
Fix onedrive url & remove userify status url

### PR DESCRIPTION
**Pull request by Carlgo11**
Quick fix of current Travis CI errors.
I couldn't find any other status links for userify so I just removed it.

### CODE REVIEW

**Comment by Carlgo11** [comment]
hm I actually don't know what the [onedrive error](https://travis-ci.org/jdavis/twofactorauth/builds/50495610#L208) referees to.
@jdavis is there no way to make it indicate what the url looked like when it was read?
Also, could the script possibly be blocked from the site because it's a script?
I mean, does the script listen to [robots.txt](https://en.wikipedia.org/wiki/Robots_exclusion_standard) or something similar?

**Comment by jdavis** [comment]
Ahh, sorry @Carlgo11; I didn't see this.

**Comment by Carlgo11** [comment]
@jdavis no worries. So I really can't find the ondrive link that's failing.
As the link contains /pagenotfounderror I'm guessing it's a redirected link that it's outputting. Any ideas on how to output the original one?

**Comment by LeFouineur** [comment]
I think we can close this PR now since all the changes were resolved and merged

**Pull request closed without merging**
