### PR TITLE
Correct Twitter exception.

### LINKED ISSUE #3014: Twitter no longer requires SMS for 2FA
Title.

This is listed as an exception, but this (thankfully!) isn't the case anymore.

### PR DESCRIPTION
**Pull request by brycx**
Fixes #3014.

### CODE REVIEW

**Review by Jawshy — APPROVED** [review]
Looks good. Thanks for the pull request.

**Comment by Carlgo11** [comment]
I don't know. It has to be a SMS capable phone and so you'd have to do the same steps as setting up SMS 2FA just without choosing SMS at the end.

**Comment by brycx** [comment]
> I don't know. It has to be a SMS capable phone and so you'd have to do the same steps as setting up SMS 2FA just without choosing SMS at the end.

I see what you mean. To me, saying that SMS is required for 2FA, suggest that you need both enabled and that SMS then will be a registered option to use as 2FA. I guess it's just a matter of wording.

**Comment by Carlgo11** [comment]
Geez Rick, I don't know if this is a good idea. Don't you think it would be better with something like `"SMS only available on select providers. An SMS capable phone is required to set up any 2FA. 10 accounts per phone number, 1 phone number per account."`?

(I'm not a native English speaker so maybe it would be good to have someone else look at this before committing (@2factorauth/collaborators))

**Comment by brycx** [comment]
I'm no native English speaker either, so let's do that.

**Review by fpigerre — APPROVED** [review]

**Pull request merged**
