### PR TITLE
Add EMP

### PR DESCRIPTION
**Pull request by slothtown**
At least emp.de is in similarweb top 200k

### CODE REVIEW

**Comment by phallobst** [comment]
`emp.de` has a rank of 11,563 - you might want to use that one instead.

Edit: I should start reading the original commit message... :facepalm:

**Comment by kmpoppe** [comment]
What size (KiB) is the .PNG? Would it make sense (as they are a German company) to have me ask their press office to give us a SVG?

**Comment by phallobst** [comment]
No need to ask: https://www.emp.de/on/demandware.static/-/Sites/default/dw9a8d7646/images/logos/Rockhand.svg

**Comment by slothtown** [comment]
Thanks, I somehow missed the svg. I'll edit it later!

**Comment by kmpoppe** [comment]
Magic! Thx for being "Der Finder" 😜

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
