### PR TITLE
Adding new provider - Cognalys ,Inc. Two factor authentication via missed call

### PR DESCRIPTION
**Pull request by anishmenon**
A new way of International Mobile number verification / Two factor authentication . For free
https://www.cognalys.com

### CODE REVIEW

**Comment by jamcat22** [comment]
Much better!

**Comment by anishmenon** [comment]
@jamcat22 ... thanks

**Comment by anishmenon** [comment]
@jamcat22  . can you please tell me that , when i can see this update on website 

https://twofactorauth.org/providers/

**Comment by mxxcon** [comment]
@anishmenon How does it work using "software"? If it works using missed calls, where does software come in?

**Comment by anishmenon** [comment]
@mxxcon  it provides an android library which can be integrated on client side for automated authentication , fetch user location , device details etc .

SDK
https://www.cognalys.com/media/cognalys.jar

open source :
https://github.com/cognalys/cognalys-android-library

Demo:
https://play.google.com/store/apps/details?id=com.matesnetwork.cogdemo

one of the Stackoverflow question
http://stackoverflow.com/questions/27789528/cognalys-verification-error-550-and-551

**Comment by jamcat22** [comment]
@anishmenon After the pull request is accepted, it can take about a week for it to show up on the website after we review the recent submissions.

**Comment by anishmenon** [comment]
@jamcat22   . thanks for the info :+1:

**Comment by smholloway** [comment]
How is a missed call a second factor (knowledge, inherence, or possession)?

**Comment by Carlgo11** [comment]
^

**Comment by mxxcon** [comment]
@smholloway I guess the way it works is that their system calls your verified phone number with last 4 digits of the caller being used as OTP.

**Comment by Carlgo11** [comment]
I tried the "demo" they provide using multiple numbers but didn't get a call. Are we still to add it if it doesn't work?

**Comment by anishmenon** [comment]
@Carlgo11 . its works here . friend

**Comment by anishmenon** [comment]
@mxxcon you are right .

**Comment by jamcat22** [comment]
Worked for me. Got a call that immediately hung up and entered last 4 numbers of phone number that called.

**Comment by anishmenon** [comment]
@jamcat22  :+1:

**Comment by anishmenon** [comment]
Dear @jdavis  . Any update on this . ?

**Comment by mxxcon** [comment]
@anishmenon it will happen when it'll happen. Have patience. This is a volunteer project and people work on it when they can/want. Your changes have not been merged yet.

**Comment by Carlgo11** [comment]
```
"@anishmenon After the pull request is accepted, it can take about a week for it to show up on the website after we review the recent submissions." - @jamcat22
```

**Comment by anishmenon** [comment]
It's OK guys

**Pull request merged**
