### PR TITLE
Update Heroku - tfa

### PR DESCRIPTION
**Pull request by friism**
Announcement: https://blog.heroku.com/archives/2014/5/6/two_factor_auth_in_public_beta

### CODE REVIEW

**Comment by mxxcon** [comment]
@friism please indicate that it's software implementation.

**Comment by hypatia** [comment]
It's a TOTP implementation :)

**Comment by friism** [comment]
@mxxcon I've added that - also changed status attribute to point to doc.

Thanks!

**Comment by mxxcon** [comment]
lgtm :+1:

**Comment by jdavis** [comment]
Awesome, thanks for the quick change.

**Pull request merged**
