### PR TITLE
Add Intercom

### PR DESCRIPTION
**Pull request by phallobst**
Alexa rank: 25,138

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
I'd much rather have this site in the 'other' category where Zendesk is. They provide kind of similar products.

**Comment by phallobst** [comment]
Hmm... Sounds to me like Zendesk should be in "Communication" as well. But I agree that they should be in the same category.

**Comment by szepeviktor** [comment]
@intercom is a fine company.

**Review by Jawshy — APPROVED** [review]
I agree with this site being added to the communication category.

**Comment by szepeviktor** [comment]
> I agree with this site being added to the communication category.

May I start another PR?

**Comment by Carlgo11** [comment]
I just don't think that an internal ticket and knowledge base system fits in with the rest of the services in the communications category.

**Comment by szepeviktor** [comment]
Actually in the last weeks I've became an Intercom advocate.

> internal ticket and knowledge base system

Intercom is definitely not an **internal** tool. It is used for marketing, sales and support too.
It is connected to many **external** platforms
- social media
- live chat on public websites
- Slack
- public phone network
- email
- tools to share screen and send scrrenshots

**Review by szepeviktor — APPROVED** [review]

**Comment by Carlgo11** [comment]
Right, by internal I meant used internally by staff as opposed to other services in the communications category like Discord, Google Hangouts (is that still a thing btw?), Signal, Skype, Teamspeak, Telegram, Viber, WhatsApp.

**Comment by szepeviktor** [comment]
Intercom is a customer relations platform.

**Review by jamcat22 — APPROVED** [review]
MailChimp, Mailgun, SendGrid, and Salesforce are other examples of customer relations tools listed in this category.

**Review by Carlgo11 — APPROVED** [review]

**Comment by szepeviktor** [comment]
Thanx.

**Pull request merged**
