### PR TITLE
Added sparbanken1826

### PR DESCRIPTION
**Pull request by Carlgo11**

### CODE REVIEW

**Comment by mxxcon** [comment]
@Carlgo11 that logo is not a real _.png_ file. It's ICON renamed into .png
Can you please upload image in correct format?

**Comment by Carlgo11** [comment]
@mxxcon Yup that should do it

**Comment by mxxcon** [comment]
not to nitpick, but it should be 32x32

**Comment by Carlgo11** [comment]
@mxxcon All good?

**Comment by mxxcon** [comment]
Either github is not showing correct info or there's something wrong with your commit, but to me b2a7c07 shows `W: 124px | H: 124px -> W: 133px | H: 133px` :confused:

**Comment by Carlgo11** [comment]
Ehm I'd say that's github then. I'm 100% certain I used H: 32 and W:32

**Comment by jdavis** [comment]
Yeah, it looks like it isn't 32x32.

img

**Comment by jamcat22** [comment]
Here's a 32x32 png you can use.

sparbanken1826

Here is the original picture resized.

sparbanken1826

**Comment by Carlgo11** [comment]
Thank you @jamcat22 ^_^

**Comment by jamcat22** [comment]
No problem! :)

**Comment by jdavis** [comment]
Cool, looks good.

**Pull request merged**
