### PR TITLE
Update Steam exception

### LINKED ISSUE #2936: Misinformation in Steam warning
The warning next to Steam states that "It does not support multiple accounts on the same device." which is incorrect.

### PR DESCRIPTION
**Pull request by matt-t-jones**
Fix #2936

### CODE REVIEW

**Review by Carlgo11 — APPROVED** [review]
Thank you! 😄

**Review by Jawshy — APPROVED** [review]
Looks good. 

For any future pull requests I'd recommend creating a [new branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/).

**Comment by matt-t-jones** [comment]
Thanks, will do.

**Comment by matt-t-jones** [comment]
These changes don't seem to be reflected on https://twofactorauth.org, why is that?

**Comment by Jawshy** [comment]
@matt-t-jones, the final step for a commit is being merged into [`gh-pages`](https://github.com/2factorauth/twofactorauth/tree/gh-pages) from `master`. You can read about the full process [here](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge) on our wiki.

**Pull request merged**
