### PR TITLE
Added Tibia

### PR DESCRIPTION
**Pull request by jamcat22**
Added Tibia to Gaming.
See #1047.

[Review on Reviewable](https://reviewable.io/reviews/jdavis/twofactorauth/1255)

### CODE REVIEW

**Comment by mxxcon** [comment]
Does this site have sensitive info?
(and travis seems to be finally working)

**Comment by Carlgo11** [comment]
yeah what happened with Travis? Did anyone change anything?

**Comment by jamcat22** [comment]
I swear I didn't do anything. :)

**Comment by RichJeanes** [comment]
I have to restate @mxxcon's question. Does this site belong here?

**Pull request merged**
