### PR TITLE
Make new section: Identity Management (per #384)

### PR DESCRIPTION
**Pull request by clsy**
Added CloudEntr, moved LastPass and Okta to new identity management
section. Per #384.

### CODE REVIEW

**Comment by jdavis** [comment]
This looks great.

The only thing I noticed is the icon you selected: `identity`. I couldn't find it in the Semantic list of icons: http://semantic-ui.com/elements/icon.html

We could possibly use the icon called: `user`. We are using `users` for Social but I think the singular will work in this case.

**Comment by mxxcon** [comment]
@jdavis for _Social_ you are using `Community` icon, not `Users`
How about `Hide` icon or `Id`

**Comment by jdavis** [comment]
We're using `users` for `social.yml`: https://github.com/jdavis/twofactorauth/blob/master/_data/main.yml#L4

**Comment by jdavis** [comment]
Also, the icons you are looking at @mxxcon, are part of the basic icon set.

But yes, I like that ID icon from the basic set.

To use them, the value should be:

``` yml
icon: basic id
```

**Comment by mxxcon** [comment]
Ah, yes. sorry. I was looking at "Basic" set's `Community`, which looks very similar to "Standard" set's users. :)

**Comment by jdavis** [comment]
Haha, no worries =]

But good eye with spotting the `basic id` icon. I really like it.

@clsygemalto If you could update it to `basic id`, we'll merge this. If you don't get to it before one of the collaborators that is. Either way :+1: for your changes.

**Comment by clsy** [comment]
Done. Ready for merge. Thanks.

**Pull request merged**
