### PR TITLE
Add Basecamp and Campfire

### PR DESCRIPTION
**Pull request by lateplate**

### CODE REVIEW

**Comment by jdavis** [comment]
Love it.

**Comment by jdavis** [comment]
Well I don't love this: http://dankim.org/2014/02/16/ten-rules-for-staying-secure.html

Item 5 on your list, tsk tsk.

**Comment by lateplate** [comment]
Lol. It was the first site out there, a few weeks ago. :grin:

**Comment by jdavis** [comment]
Hahah, I'm just playing.

**Pull request merged**
