### PR TITLE
Update Fio banka

### PR DESCRIPTION
**Pull request by melanger**

### CODE REVIEW

**Review by Carlgo11 — COMMENTED** [review]
This sounds like [authorization](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#authorization) rather than authentication.

**Comment by melanger** [comment]
> This sounds like [authorization](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#authorization) rather than authentication.

I see, the description on the website is not very accurate - when users log in, they have to enter 1) username + password, 2) use a second factor authentication - one of the listed methods (SMS, certificate, SMS+certificate or confirm in the banking app, which also features biometric authentication). Later, when making a payment, the second factor is repeated (unless users disable it for small payments or for a specific repeated payment).

**Comment by melanger** [comment]
@Carlgo11 Can this be merged considering it is really a 2FA, or do I have to force them to update their website to explicitly mention 2FA?

**Comment by phallobst** [comment]
The Czech version at https://www.fio.cz/bankovni-sluzby/internetbanking/zabezpeceni seems to be more up-to-date and mentions _Strong Customer Authentication_ (and the usual "trusted device" mechanism via cookies).

**Review by phallobst — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
