### PR TITLE
Add Minna no Ginko

### LINKED ISSUE #6539: Add Minna no Ginko
### Site name

Minna no Ginko

### Site URL

https://www.minna-no-ginko.com/

### Facebook

https://www.facebook.com/minnanoginko

### Twitter

@minnano_ginko

### Email address

_No response_

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

- English page: https://www.minna-no-ginko.com/?wovn=en
- Alexa: 144,157
- Keywords: banking
- Regions: jp

### PR DESCRIPTION
**Pull request by ghost**
Closes #6539 
Could you please prepare an image for me?
Image: https://www.sevenbank.co.jp/personal/atm/img/PLOGO8347_001_01_01_s.svg

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]

**Review by Carlgo11 — APPROVED** [review]
Looks fine. If you'd like to contribute with translation, [languages.yml](https://github.com/2factorauth/twofactorauth/blob/master/_data/languages.yml) stores translations of email and tweet messages and currently lacks Japanese.

**Comment by ghost** [comment]
> Looks fine. If you'd like to contribute with translation, [languages.yml](https://github.com/2factorauth/twofactorauth/blob/master/_data/languages.yml) stores translations of email and tweet messages and currently lacks Japanese.

I'm a little busy right now, so I'd like to do this when I have time.

**Comment by phallobst** [comment]
Do they have web logins, or is this app-only banking?

**Comment by ghost** [comment]
> Do they have web logins, or is this app-only banking?

This is an app only.

**Comment by ghost** [comment]
Why was this PR closed?

**Comment by phallobst** [comment]
@carbongreat13 You seem to have deleted your 2factorauth repository, so there's no way to merge any changes. This applies to the following PRs: #6549, #6554, #6573, #6578, #6579, #6580

**Pull request closed without merging**
