### PR TITLE
Add Greyhound

### PR DESCRIPTION
**Pull request by stephengroat**
Not sure whether to add their normal twitter or their "consumer related questions twitter" @GHoundBusHelp

### CODE REVIEW

**Comment by Carlgo11** [comment]
Yeah please use GHoundBusHelp instead.

So it's the equivalent of  GTA's [Dashound](http://vignette1.wikia.nocookie.net/gtawiki/images/e/e9/Dash2.jpg/revision/latest?cb=20131018093005)? :smile:

**Comment by stephengroat** [comment]
That should do it.

GTA is obviously based on real life, so [expect excitement on a Greyhound trip](http://www.canada.com/windsorstar/story.html?id=5e5e949c-989a-47f7-86da-53801510af24).

**Comment by Carlgo11** [comment]
Wow! That's almost more GTA than GTA itself. :open_mouth: 
And yes, obviously GTA is based on real life.
bus stunt
That's how express buses work, right? :smile:

**Comment by stephengroat** [comment]
Excellent use of inline gif. the link would have lost the "magic" there

**Comment by stephengroat** [comment]
Do you want me to fix conflicts or can you handle them? I think they're only those last new lines

**Comment by Carlgo11** [comment]
Sorry for the delay @stephengroat.
You can either fix the merge conflict yourself(Preferred) or we can do it for you.

**Comment by stephengroat** [comment]
Fixed the #1766. If possible, I'll do them one at a time (see #1766 for details)

**Pull request merged**
