### PR TITLE
Add Avast

### PR DESCRIPTION
**Pull request by Reprevise**
Added Avast data to security.yml and added Avast logo to the security folder in the img folder.

### CODE REVIEW

**Review by kmpoppe — APPROVED** [review]
HI @EcoGames and thank you for your contribution. As you kindly allowed edits from maintainers, I took the liberty to update the logo you provided with a compressed one.
Another maintainer will review your Pull Request soon.
// Kai

**Review by Carlgo11 — COMMENTED** [review]
What [site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) does Avast fall under?

**Comment by Reprevise** [comment]
Avast is an antivirus that also deals with money via a subscription.

**Comment by Carlgo11** [comment]
But if someone gains access to another person's account, what could they do with it?

**Comment by Reprevise** [comment]
If someone were to gain access to an avast account, if the person has Avast Anti-Theft on their device, the person could wipe their device, locate it remotely, etc.

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
