### PR TITLE
Spend Crypto Here - Crypto Superstore

### PR DESCRIPTION
**Pull request by SpendCryptoHere**
bch: true
   btc: true
   othercrypto: true
+- name: Spend Crypto Here
+  url: https://spendcryptohere.com
+  region: us
+  country: usa
+  city: Baltimore
+  bch: true
+  btc: true
+  othercrypto: true
+  doc: https://spendcryptohere.com/blogs/news/quit-hodling-and-start-using
 - name: Spend Crypto Here
   url: https:spendcryptohere.com
   img: spendcryptohere

### CODE REVIEW

**Comment by brycx** [comment]
@SpendCryptoHere Care to give a short explanation of what all this is?

**Comment by SpendCryptoHere** [comment]
Sorry, unfamiliar with the formatting here.  Was trying to add an online
store to the database, but accidentally hit post and couldn’t figure out
how to delete it.

**Comment by mxxcon** [comment]
@SpendCryptoHere you created pull request between 2 wrong repos. ;)
I think you meant to create an issue or a pull request in this repo https://github.com/acceptbitcoincash/acceptbitcoincash

**Comment by SpendCryptoHere** [comment]
Thanks a lot!  I think I followed a bad link or something.  But anyways,
looks like I need to do some more reading and practicing around here before
I go posting all willy nilly.   Thanks for the help!

**Pull request closed without merging**
