### PR TITLE
Add Revolut

### PR DESCRIPTION
**Pull request by jrc**

### CODE REVIEW

**Review by Jawshy — DISMISSED** [review]
Thanks for submitting a pull request, @jrc. 

There are a couple of corrections that I would like you to make: 
1. Could you please remove lines 656 and 657 as `twitter` and `facebook` are not required when `tfa` is `Yes`. 
2. Could you please resize the image to 32 by 32 pixels and rename it to `revolut.png`?

**Comment by Jawshy** [comment]
One more question, do you know if Revolut has any documentation about how they have implemented SMS two-factor authentication?

**Comment by jrc** [comment]
Made the changes requested. Sorry, I completely missed CONTRIBUTING.md at first!

To answer your question, I could not find any official documentation from them about 2FA, although I have used the SMS-based authentication myself, and there are some threads in the community forum suggesting improvements beyond SMS.

**Review by stephengroat — DISMISSED** [review]
Thanks for the pr @jrc

**Review by Carlgo11 — DISMISSED** [review]

**Review by brycx — COMMENTED** [review]
Do you have docs available for setting up 2FA @jrc? I couldn't find any.

**Comment by jrc** [comment]
No, I cannot find anything. As I mentioned before, they only seem to support SMS-based 2FA.

**Comment by brycx** [comment]
Could you provide screenshots of how to setup 2FA with sms? Redacting any personal information of course.

**Pull request closed without merging**
