### PR TITLE
Add Cablevision Fibertel

### PR DESCRIPTION
**Pull request by fainpablo**
Comcast-like company. Through their website you can subscribe and cancel services, request a change of address, etc.

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Here's the logo without the upscaling artifacts
logo

**Comment by fainpablo** [comment]
Thanks. Updated.

**Review by Carlgo11 — APPROVED** [review]

**Comment by phallobst** [comment]
@Carlgo11 The "workflow" check did not run here. Do you know what's up?

**Comment by Carlgo11** [comment]
CircleCI was down tonight. I sent info about it a few days ago on slack

**Comment by phallobst** [comment]
I'm getting old... Totally forgot about that.

**Review by phallobst — APPROVED** [review]

**Pull request merged**
