### PR TITLE
Add color codes to Circle CI outputs

### PR DESCRIPTION
**Pull request by Carlgo11**
* Added some color codes to make it easier to read the console output on the Circle CI tests.
* Switched to silently install gems for the Twitter test.
* Replaced the `raise` functions with `puts` & `exit` as raise doesn't support color codes.

### CODE REVIEW

**Comment by phallobst** [comment]
Does anyone really see these colors? When I view a failed CircleCI check, all I see are the ANSI codes in the output, like [here](https://app.circleci.com/pipelines/github/2factorauth/twofactorauth/1563/workflows/4c23f24c-f499-4af2-a4d9-e90a28e37963/jobs/1578).

**Comment by Carlgo11** [comment]
@phallobst that's because the script used `raise()` instead of `puts()`. This PR fixes that.

**Comment by phallobst** [comment]
Are you expecting me to read **and** understand the commit message?! That's crazy talk... :zany_face:

**Comment by Carlgo11** [comment]
@phallobst honestly don't blame you 😅

**Review by phallobst — APPROVED** [review]

**Review by dsoegijono — APPROVED** [review]

**Pull request merged**
