### PR TITLE
Add AVG

### PR DESCRIPTION
**Pull request by ondrejfuhrer**

### CODE REVIEW

**Review by brycx — DISMISSED** [review]

**Comment by mxxcon** [comment]
AVG is a locally installed antivirus app...how would 2fa apply here?

**Comment by ondrejfuhrer** [comment]
@mxxcon You can have an AVG account and log into it through the website (https://myaccount.avg.com/). I was not sure if I should include that sub domain or not.

**Comment by mxxcon** [comment]
What kind of stuff is in that account?

**Comment by ondrejfuhrer** [comment]
Hey @mxxcon ,

You manage there your orders and subscriptions for AVG products.

**Review by mxxcon — APPROVED** [review]

**Review by brycx — APPROVED** [review]

**Pull request merged**
