### PR TITLE
Add Laravel Forge

### PR DESCRIPTION
**Pull request by jakebathman**
Forge is a server provisioning, deployment, and management service. I've added the site to `cloud.yml` and included a logo.

Please let me know if there are any questions or issues. Thanks!

### CODE REVIEW

**Comment by brycx** [comment]
When I visit the doc link I get redirected to https://forge.laravel.com/#/authentication, which seems to be the same as the main site page. Are the docs only for members? If so, please post a screenshot with personal information blurred out, that documents the 2FA setup.

**Comment by jakebathman** [comment]
Yeah, there's not really a documentation page, only the settings page with the button to enable. Here's what it looks like:

forge-2fa

**Comment by mxxcon** [comment]
Wouldn't `developer` be a better category for this?

**Comment by jakebathman** [comment]
Nope, Forge is a server management/provisioning service. It's all about hosting existing projects, and fits right in line with the services in `cloud`.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
How about this logo instead?
It's from their website and transparent.
forge

**Comment by jakebathman** [comment]
I like it, I'll push the change now

edit: Updated the logo to your recommendation.

**Review by Carlgo11 — APPROVED** [review]

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
