### PR TITLE
Add VyStar

### PR DESCRIPTION
**Pull request by kevindb**

### CODE REVIEW

**Comment by Carlgo11** [comment]
The documentation page you linked to is a bit fuzzy when it comes to describing the actual system.
Is a user required to get a code from their phone on every login attempt or just on some that the system classifies as extra suspicious?

**Comment by kevindb** [comment]
I, too, am dismayed at VyStar's documentation. Great interest rates, poor security.

Prompted for SMS or telephone code based on suspicious activity, including first-time login from new browser. Subsequent logins from the same browser require only the user/password.

**Comment by Carlgo11** [comment]
Okay then it's not two factor authentication by our definition.
https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions

So either set it to `tfa: No` or close the PR.

**Comment by kevindb** [comment]
Thank you for correcting me. I misunderstood the definition that not requiring TFA _every_ time is not TFA (under your definition).
I've updated my PR to match.

P.S. Thank you for this tool. It's incredibly helpful.

**Comment by stephengroat** [comment]
I don't want to cause problems, but a LOT of the sites that are currently listed as `tfa: Yes` follow the same scheme. Dropbox, Google, and Github all use a cookie-based system for first time login from new browsers and then redo password (1factor auth) for higher sensitivity operations

**Comment by RichJeanes** [comment]
However, a lot of those sites provide user choice in the matter. For example, Google requires 2FA _at least_ every 30 days, but the user can opt to be prompted every time by simply unchecking the box at login.

Though, I will agree, the list could use an audit. That's just a rather daunting task...

**Comment by kevindb** [comment]
To clarify, in the case of VyStar, there is no user control for 2FA. Once you have logged in, you are _not_ prompted for 2FA using that browser again (likely using cookie).

I am in favor of the strictest definition of '2FA'. In fact, I support dropping SMS and automated phone calls from the definition, especially since NIST has depricated SMS:
https://pages.nist.gov/800-63-3/sp800-63b.html#out-of-band-verifiers

**Comment by stephengroat** [comment]
NIST is beginning the phase-out of SMS and phone calls, but has not officially dropped them yet. From the draft release:

```
OOB (out of band verification) using SMS is deprecated, and may no longer be allowed in future releases of this guidance.
```

**Comment by Carlgo11** [comment]
@stephengroat Yes but that doesn't have anything to do with this PR.
Try and keep off topic discussion to a minimum in PRs and Issues. 😉

**Pull request merged**
