### PR TITLE
Add Vodafone Italy.

### PR DESCRIPTION
**Pull request by Flameeyes**
Same logo as Vodafone UK, no 2FA option.

### CODE REVIEW

**Comment by RichJeanes** [comment]
Does every region of Vodafone have an independent login system? As in, if one gets 2FA, would they all? I don't know how independently the branches of the company operate. It just seems excessive to list every country they operate in if it isn't completely necessary.

**Comment by Flameeyes** [comment]
Unfortunately they all operate independently :( Effectively Vodafone does not share anything but marketing material between countries.

For example, Vodafone Italy even has a terrible website without HSTS and with a number of entrypoints for downgrades.

**Review by stephengroat — APPROVED** [review]
thanks for the pr and explanation @Flameeyes

**Review by Carlgo11 — APPROVED** [review]

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Please change the Twitter handle to `Vodafoneit`

**Comment by Flameeyes** [comment]
I've styled it the way it's styled on their twitter page (VodafoneIT). Previously I used the way it's styled on their homepage.

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
Wow, they have a valid HTTPS cert that they use to redirect users to their HTTP version... 😒

**Comment by Flameeyes** [comment]
They don't even force-redirect on pages where they ask for credit cards :|
I have been trying to get in touch with someone with a clue about their IT for a few months, but mostly gave up.

**Pull request merged**
