### PR TITLE
Add bitwarden

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Review by mxxcon — APPROVED** [review]
How popular is this service/project? It's not too small/obscure?

**Review by Jawshy — COMMENTED** [review]
#2197

**Comment by Carlgo11** [comment]
Judging from the repos on GitHub it doesn't look like very many people use the service.

**Comment by fpigerre** [comment]
The service seems quite new, as well. It might be a good idea to wait until it has matured some more before listing it on [twofactorauth.org](https://twofactorauth.org).

**Comment by Carlgo11** [comment]
Closing for now.

**Pull request closed without merging**
