### PR TITLE
Added Ping Identity to Identity Management

### PR DESCRIPTION
**Pull request by allynf**

### CODE REVIEW

**Comment by RichJeanes** [comment]
It seems that Ping is an SSO and TFA provider, correct? This site is for listing consumer websites, not providers. Unless you think that Ping is widely used enough to merit its listing for itself as a website that people will be logging in to.

**Comment by Carlgo11** [comment]
Yup. Provider.

**Comment by allynf** [comment]
Yes, Ping does SSO and TFA and competes with Okta and OneLogin, among others, which are also listed in the Identity Management section.

**Comment by RichJeanes** [comment]
Then perhaps we should look into removing them if those are the only services they provide. Thank you for pointing that out.

**Pull request closed without merging**
