### PR TITLE
Remove remaining 'software' tfa references

### PR DESCRIPTION
**Pull request by phallobst**
Followup to #4542

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Revert the api/v1/data.json part and we're good to go.

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
Noooooo 😭
I had just fixed it

**Comment by phallobst** [comment]
Oh, I thought I was meant to revert it... :man_facepalming:

**Comment by phallobst** [comment]
I hope it's correct now... If not, maybe you can commit whatever is needed, and I keep my clumsy hands away from this PR.

**Comment by Carlgo11** [comment]
It’s good now 😄

**Review by dsoegijono — APPROVED** [review]

**Pull request merged**
