### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by marcobiedermann**
image

Running all images through [ImageOptim](https://imageoptim.com/mac) saves ~13% overall.
This is covered by your [CONTRIBUTING.md](https://raw.githubusercontent.com/2factorauth/twofactorauth/master/CONTRIBUTING.md#L20) but unfortunately only a few images are optimized.

### CODE REVIEW

**Comment by mxxcon** [comment]
@marcobiedermann did you use lossless settings in imageoptim?

**Comment by marcobiedermann** [comment]
@mxxcon Yes, I did. No quality got lost!

**Comment by mxxcon** [comment]
Did you manually check all 939 images to claim that lossy compression didn't affect visual quality? 😉
My concern is by performing lossy compression it switches from alpha channel to a regular transparency layer and without verifying, that might look bad.

**Comment by mxxcon** [comment]
Hmm. Strange that your total amount is 958KB, whereas if when I run the whole `img` folder through imageoptim I get `saved 49KB out of 630KB`.

**Comment by marcobiedermann** [comment]
@mxxcon 
These are my settings in ImageOptim:

image

image

Setting optimisation level to insane will result in smaller file size. It takes a bit longer bit in my opinion it is worth it.
As mentioned no quality gets lost.

**Comment by mxxcon** [comment]
For comparison I ran the whole `img` folder through http://nikkhokkho.sourceforge.net/static.php?page=FileOptimizer using only lossless mode and end result is 900,826 bytes total.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
merge conflict ☝️

**Review by mxxcon — COMMENTED** [review]
Conflict with `/lib/*` is because we got rid of that directory in favor of using external semantic lib.
And for simpletax, update that image to the current state :)

**Comment by Carlgo11** [comment]
Closing due to inactivity

**Pull request closed without merging**
