### PR TITLE
Added ProtonMail

### PR DESCRIPTION
**Pull request by Carlgo11**
Instead of #679

### CODE REVIEW

**Comment by dsoegijono** [comment]
:+1:

**Comment by Carlgo11** [comment]
I think this was merged to the wrong branch. jdavis:patch-2. Shouldn't it be master?

**Comment by mxxcon** [comment]
indeed, looks like wrong branch

**Comment by Carlgo11** [comment]
okay I'll push it to the master branch when I get back home.

yay for collaborator powers xD

**Pull request merged**
