### PR TITLE
Added wargaming.net

### PR DESCRIPTION
**Pull request by Carlgo11**
As requested in #691

### CODE REVIEW

**Comment by mxxcon** [comment]
Your YAML mentions png, while the image is jpeg.

**Comment by Carlgo11** [comment]
oh, silly me

**Comment by jdavis** [comment]
Would you like me to merge this one and close #700?

Or would you be able to only add your changes? This could be done easily by the following commands:

``` bash
$ git checkout -b wargaming-patch master
$ git cherry-pick -n de866d6 07c9a8e 0552382
# Edit the gaming.yml and remove the Origin stuff
$ git add _data/gaming.yml
$ git commit
$ git push origin patch-4 --force
```

And this pull request would be fixed and I could merge both.

**Comment by Carlgo11** [comment]
Great! :)

**Pull request merged**
