### PR TITLE
Add Star One Credit Union

### PR DESCRIPTION
**Pull request by contextnerror**
Security questions are also advertised as a form of MFA. Not sure if it counts.

### CODE REVIEW

**Comment by Carlgo11** [comment]
No, security questions don't count as MFA :wink: 

I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
screenshot

**Comment by contextnerror** [comment]
There's info at https://www.starone.org/security/, but it's all the way at the bottom in a collapsed menu. I can't seem to link to the important part directly.

Enabling 2FA is done by default during account signup.

**Comment by Carlgo11** [comment]
Although the page you linked to did provide a good laugh it didn't provide much relevant information.
What is some kind of proof of 2FA. Either as a link or as a screenshot (with personal information blurred out)

The encryption section is pure gold :laughing: 


--
This comment is protected by VeriSign RC4 encryption technology .
This encryption technology is classified by the U.S. Department of Defense. United States law forbids export of this technology to other countries. If you read this comment outside of the United States of America, please close your eyes.

**Comment by contextnerror** [comment]
Here's a screenshot.
2fa-screenshot

**Review by Carlgo11 — APPROVED** [review]
Thanks!

**Pull request merged**
