### PR TITLE
Add brightbox

### PR DESCRIPTION
**Pull request by lostick**

### CODE REVIEW

**Comment by stephengroat** [comment]
@lostick we've actually started to add a `facebook` tag as well. I added it to the PR, make sure it looks O.K.

p.s. home the maintainer edit on your branch wasn't offensive, first time i've tried it. any feedback is appreciated

**Review by stephengroat — APPROVED** [review]

**Comment by Carlgo11** [comment]
That was quick... 😮

**Comment by Carlgo11** [comment]
Btw, thanks for the PR @lostick! 😄 
Your contribution will go live once we've manually updated the site.
We/I do this about once every week but it could take longer. Anyways, it's added now so sooner or later it will show up for everyone on twofactorauth.org. 👍 

Have a good once!
//Carl

**Comment by lostick** [comment]
you guys are blazing fast!

**Comment by Carlgo11** [comment]
Sometimes *cough\* we have PRs all the way back from October 2015 still open here...

**Pull request merged**
