### PR TITLE
Add Splitwise

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mxxcon** [comment]
How does this fit into our [site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria)?

**Comment by ghost** [comment]
It features both profile images, so criteria 1
and it is used to manage debts to different people linkable to actual purchases that can be moved around. Basically a tool to manage money between people, except it's not moving actual money, it only takes stock

**Comment by mxxcon** [comment]
It's not about profile images as in pictures/avatars, but rather how you are perceived as a person. In that example, you wouldn't want your twitter account compromised by some idiot and start spewing racist crap...
A site that simply lists IOUs...I'm on the fence if it's such a sensitive area. 😄

**Comment by stephengroat** [comment]
on the [Play Store](https://play.google.com/store/apps/details?id=com.Splitwise.SplitwiseMobile), it has 50k reviews and between 1mil-5mil installs. I'd say it's big enough

**Comment by Carlgo11** [comment]
I'm with @mxxcon on this one.

**Comment by Carlgo11** [comment]
Closing because of https://github.com/2factorauth/twofactorauth/pull/2435#issuecomment-285396062 and https://github.com/2factorauth/twofactorauth/pull/2435#issuecomment-285950213

**Comment by leggomyinfo** [comment]
@Carlgo11 This is fair game now, right?

**Pull request closed without merging**
