### PR TITLE
Typo fixes in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by tmsagarofficial**
[258] acccount -> account
[383] replace -> replaces

### CODE REVIEW

**Review by phallobst — APPROVED** [review]

**Comment by phallobst** [comment]
Welcome and thank you, @tmsagarofficial!

**Comment by tmsagarofficial** [comment]
I'm making another PR with grammatical errors. Is that fine? @phallobst

**Comment by phallobst** [comment]
I think we already have enough grammatical errors, so...

(Yes, German humour is no laughing matter.)

**Comment by tmsagarofficial** [comment]
> I think we already have enough grammatical errors, so...
> 
> (Yes, German humour is no laughing matter.)

Its humor 😅 

Heheh 😆 


sure will do it separately on different files. I'm keeping typos and grammar separately for easier future reference.

**Pull request merged**
