### PR TITLE
add WebOké

### PR DESCRIPTION
**Pull request by webaweredanny**
This is my second pull request ever, pretty sure i did something wrong. Please let me know if this is the case!

### CODE REVIEW

**Comment by webaweredanny** [comment]
duimdoorzichtig

**Comment by 40504** [comment]
First, create a file called `weboke.nl.json` under this directory `../entries/w/`

Your file should look something like this: 
```json
{
  "Weboke": {
    "domain": "weboke.nl",
    "tfa": [
      "totp",
      "U2F"
    ],
    "documentation": "https://www.weboke.nl/knowledgebase/127/Hoe-schakel-ik-tweestapsverificatie-in.html",
    "keywords": [
      "hosting"
    ]
  }
}
```

Second, put image file called `weboke.nl.svg` under this directory `../img/w/`


But it will not be accepted as `weboke.nl` is above 200,000 Alexa ranking, currently: 4,700,356

**Comment by Carlgo11** [comment]
:+1: for a very creative interpretation of the contribution guidelines.

However, as @40504 says, it doesn't meet the site criteria as the site is ranked above 200K on Alexa.

**Comment by webaweredanny** [comment]
Thanks for the feedback guys! Because of this: "If a site does not meet all of these requirements, feel free to continue your issue submission.
Leave any unmet requirements unchecked, and add any additional information or questions in the "Additional information" section below. -->" i thought it was worth a try anyway.

I'll make sure we secure a position in the alexa top 200.000 first before submitting the next request :D

**Pull request closed without merging**
