### PR TITLE
Add Bitbond

### PR DESCRIPTION
**Pull request by jareknowotka**
Bitbond requires users to use 2FA when signing in from a new device. If you login from the same device twice you won’t be asked for 2F.

### CODE REVIEW

**Review by Jawshy — CHANGES_REQUESTED** [review]
Thanks for the pull request, @jareknowotka. Does Bitbond have any documentation regarding their implementation of two-factor authentication?

**Comment by jareknowotka** [comment]
Thanks for asking, unfortunately not, we don't provide documentation regarding 2FA.

**Comment by Carlgo11** [comment]
@jareknowotka if that's the case could you send some screenshots and describe how you've implemented 2FA?
What 2FA options you support and so on.

**Comment by Jawshy** [comment]
@jareknowotka https://github.com/2factorauth/twofactorauth/pull/2181#issuecomment-261291459

**Comment by stephengroat** [comment]
screenshot 2016-12-11 at 15 00 58

**Comment by jareknowotka** [comment]
Thanks for registering! The authorisation flow for a user singing in from a new device looks like that: 

screen shot 2016-11-18 at 10 30 13
screen shot 2016-11-18 at 10 30 39
screen shot 2016-11-18 at 10 30 53

The last screen requires a token from a method user has selected as his 2FA.

**Review by Jawshy — APPROVED** [review]

**Pull request merged**
