### PR TITLE
Add Yclas

### LINKED ISSUE #1894: Yclas.com
Using google authenticator.

### PR DESCRIPTION
**Pull request by alanbares**
Adds yclas site and logo. Hope the png is ok. I ran it through through optipng and it took me a bit to even get the dev environment setup on windows for testing everything.  Closes #1894

### CODE REVIEW

**Comment by fpigerre** [comment]
Thanks for the pull request @alanbares! :+1:

**Comment by mxxcon** [comment]
@Carlgo11 perhaps hold off on merging this. It seems like this and #1899 are the same thing?

**Comment by Carlgo11** [comment]
@mxxcon well this one looks good IMO. If anything I say we should hold off on merging #1899.

**Comment by neo22s** [comment]
Hello. Open Classifieds is a FOSS and yclas is a SaaS. Same docs: https://docs.yclas.com/2-step-authentication/

Thanks!!

**Pull request merged**
