### PR TITLE
Update Mojang

### PR DESCRIPTION
**Pull request by fletcherdodd**

### CODE REVIEW

**Review by Carlgo11 — APPROVED** [review]

**Comment by fletcherdodd** [comment]
@Carlgo11 U2F is available in the advanced security options of your Microsoft account while, fyi. I have 2 setup on mine.

image

**Comment by Carlgo11** [comment]
@fletcherdodd that would be FIDO2 "passwordless" authentication. See [this note](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#passwordless-authentication) on how we classify "passwordless" authentication.

**Comment by phallobst** [comment]
Maybe the main domain should be `minecraft.net` instead of `mojang.com`, with "Minecraft" as the entry name.

**Comment by fletcherdodd** [comment]
I did think that, but the only svg that was good enough was the minecraft text. The grass block logo, I couldn't get to work well so it would have to be a png file

**Comment by Carlgo11** [comment]
I replaced the entry with minecraft.net. Used their favicon as the icon. No idea why it is so large tho :unamused:

**Review by phallobst — APPROVED** [review]

**Pull request merged**
