### PR TITLE
Add Illinois Institute of Technology

### PR DESCRIPTION
**Pull request by thegeekkid**
Students have been very active in asking for the support department to enable 2 factor auth for email at the very least (since that would be easy to do with Google Apps); however, the administration has turned them down every time.  Currently not only is student email out in the open, but also the tuition payment center that stores student's bank account and credit card information.

### CODE REVIEW

**Review by stephengroat — CHANGES_REQUESTED** [review]
Can you change the url to `https://web.iit.edu`?

**Comment by stephengroat** [comment]
Thanks for the PR @thegeekkid. if you could address that one little change, this site tends to prefer linking to the home pages (from what I can tell)

@Carlgo11 any other comments on the `email` or `exception`?

**Comment by thegeekkid** [comment]
Sure.  Just changed it.

Thanks!

**Comment by stephengroat** [comment]
@thegeekkid Don't know if the push made it

**Comment by thegeekkid** [comment]
Duh.  Would help if I pushed to the correct branch.  Sorry - lol!

**Review by stephengroat — APPROVED** [review]

**Pull request merged**
