### PR TITLE
Add eBay Kleinanzeigen (DE)

### PR DESCRIPTION
**Pull request by melgu**

### CODE REVIEW

**Comment by mxxcon** [comment]
Can you use your existing ebay login with this site?

**Comment by melgu** [comment]
@mxxcon No, it's separate.

**Comment by kmpoppe** [comment]
Global Alexa rank is 236 (8 in Germany) today. ebay-KA and ebay still use different logins.

**Comment by Carlgo11** [comment]
@kmpoppe is ebay Kleinanzeigen just a German fork of ebay or is it a completely different thing?

**Comment by kmpoppe** [comment]
@Carlgo11 
eBay Kleinanzeigen (small ads/classified ads/want ads) is a completely different site from eBay, it has a different concept (no fees, direct contact between buyer and seller). Yet, it _is_ eBay because both eBay GmbH (ebay.de) and eBay Kleinanzeigen GmbH (ebay-kleinanzeigen.de) both have their registered business addresses at the same point.

**Comment by Carlgo11** [comment]
@kmpoppe so it's like craigslist? I'm just trying to understand what category it fits the best in.

**Comment by melgu** [comment]
Yes, pretty much.

**Comment by kmpoppe** [comment]
@Carlgo11 as @melgu said, yes, craigslist is a pretty good comparison.

**Review by kmpoppe — CHANGES_REQUESTED** [review]
@melgu Could you reduce the file-size of the logo? You can use OptiPNG (as described in the CONTRIBUTING.md of the project). Maintainers of the project like fast-loading images ;-)

**Comment by kmpoppe** [comment]
Bump @carlgo11

**Review by kmpoppe — DISMISSED** [review]

**Comment by melgu** [comment]
Could someone please approve the pull request?
Isn't this repo active anymore?

**Comment by kmpoppe** [comment]
Thank you for your contribution, @melgu!
This repo is active, yet all Members are volunteers doing everything in their spare time.
I have requested @Carlgo11 to review this PR as he's currently one of the most active ones.
Please be patient.

**Comment by melgu** [comment]
Thanks for your work!
I hope, I didn't come off as rude, because I didn't mean to.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
I think their favicon looks better than the logo you supplied:
logo

**Review by Carlgo11 — APPROVED** [review]

**Review by kmpoppe — APPROVED** [review]

**Pull request merged**
