### PR TITLE
Update SimpliSafe MFA options

### PR DESCRIPTION
**Pull request by neoeinstein**
SimpliSafe now supports MFA using SMS and voice calls, as well as U2F platform factors. Also, SimpliSafe primarily targets the US and UK markets, so added appropriate regional specifiers.

### CODE REVIEW

**Review by Carlgo11 — COMMENTED** [review]
Thanks for the pull request @neoeinstein,
the current documentation only mentions SMS and phone calls as MFA options.
Are you able to send proof of U2F and email being supported?
It can be in form of screenshots of the 2FA setup process and/or login process.
> **Note** Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment, like this:
screenshot

**Comment by neoeinstein** [comment]
The U2F factors supported are platform factors (think device biometrics [Face ID, Fingerprint]), not roaming tokens (like the YubiKey). The support for device biometrics is at the bottom of the documentation.

Email is not supported for new users, but is still supported for users that were previously on that factor and have yet to migrate to the full MFA flow. If the goal is to indicate what methods a new user would be have access to, then we can remove email from the supported factors.

**Comment by Carlgo11** [comment]
FaceID isn't FIDO U2F so please remove `u2f` from the list.
If email is deprecated then that should also be removed.

Thanks!

**Comment by neoeinstein** [comment]
image
image
image

**Comment by Carlgo11** [comment]
Yeah that's not U2F.

**Comment by neoeinstein** [comment]
Is there any acknowledgement in this repository for FIDO UAF?

**Comment by Carlgo11** [comment]
No.

https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#passwordless-authentication

**Comment by neoeinstein** [comment]
Ok. I dispute the definitions here, but they are yours to maintain in this repository. I'll close this then.

**Pull request closed without merging**
