### PR TITLE
Added VentraIP info

### PR DESCRIPTION
**Pull request by stephenreay**

### CODE REVIEW

**Review by mxxcon — COMMENTED** [review]
Is there a better `doc` link that describes how to enable it rather than a PR post?
What kind of `software` is it?

**Comment by stephenreay** [comment]
It's not software. It's a web host & registrar. I couldn't find anything better in their docs about their 2FA support.

**Comment by mxxcon** [comment]
You have `software: Yes`, what kind of 2fa is it? TOTP or something else?

**Comment by stephenreay** [comment]
Yes, it's regular TOTP.

**Comment by Jawshy** [comment]
I decided to send VentraIP an email asking about their documentation and support for two-factor authentication.

**Review by Jawshy — CHANGES_REQUESTED** [review]
I received a response from VentraIP. They said that they currently offer SMS and email based two-factor authentication. 

Could you update your pull request to include these changes?

**Comment by jamcat22** [comment]
Ping @Jawshy

**Review by Jawshy — APPROVED** [review]

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
