### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by NicolasFort**
added statetrust / android 2FA

### CODE REVIEW

**Comment by jdavis** [comment]
Uh oh! Your indentation breaks the build. If you could fix that as well as add an icon, that'd be awesome.

**Comment by RichJeanes** [comment]
Looks like there's still some conflict after you last commit.

**Comment by NicolasFort** [comment]
sorry Garrett, i’ll fix that asap, do you have indication what is conflicting by chance ?
thnaks a lot
/nicolas

De : Garrett Richard Jeanesmailto:notifications@github.com
Envoyé : ‎jeudi‎ ‎20‎ ‎mars‎ ‎2014 ‎20‎:‎01
À : jdavis/twofactorauthmailto:twofactorauth@noreply.github.com
Cc : Nicolas Fortmailto:Nicolas.Fort@vasco.com

Looks like there's still some conflict after you last commit.

**Comment by RichJeanes** [comment]
It looks like you are still working off a commit prior to #142. You'll pull again to get up to date then try again. Also, for the img link, you need to add the site logo to the repo. 32x32 please, as per the README Guidelines.

**Pull request closed without merging**
