### PR TITLE
Updating Coin Cafe's entry.

### PR DESCRIPTION
**Pull request by coincafeinc**

### CODE REVIEW

**Comment by mxxcon** [comment]
Please provide URL that documents presence of 2fa, also please update your commit to include what type of 2fa is supported.

**Comment by coincafeinc** [comment]
All bitcoin transfers require 2FA on coincafe.com.

The send page is here: https://coincafe.com/wallet.php?page=send

The 2FA type is software via email.

Thanks!
-Mike & Steve

**Comment by mxxcon** [comment]
That page is empty...

**Comment by coincafeinc** [comment]
You need to be signed in to access it.

**Comment by Walkman100** [comment]
https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions

> All bitcoin transfers require 2FA on coincafe.com.

&nbsp;

> A site that does not prompt you for a token upon login, but prompts you for a token when you try to perform a sensitive action would not be considered Two Factor Auth.

??

**Comment by mxxcon** [comment]
@Walkman100 what confuses you? Have you read linked discussion?

**Comment by Walkman100** [comment]
I hadn't yet. I thought that since Coin Cafe only needs 2FA for certain actions, It shouldn't be on here, but this makes sense:

> This is supposed to let people know what kind of authentication, if any, institutions have, it's also why I included the direct link to wells fargo's documentation.

However:

> I think 2FA (for this site) should be limited to logging into your account and prevention of access of any info.

**Pull request closed without merging**
