### PR TITLE
Add Authy

### LINKED ISSUE #3376: Add dashboard.authy.com
The Authy Dashboard can be added in the security category. It supports SMS and Software tokens.

### PR DESCRIPTION
**Pull request by stephengroat**
closes #3376

### CODE REVIEW

**Comment by Carlgo11** [comment]
Does it make sense from a consumer perspective to add Authy's dashboard?
If we want to aid consumers make a educated choice in what services and websites they use it's not like anyone is going to switch from a 2FA provider to another 2FA provider just because the new provider uses 2FA.
I mean, what 2FA provider isn't supporting 2FA?

**Comment by stephengroat** [comment]
so no listing of any 2fa providers? should we add that to the `CONTRIBUTING` list?

we currently list https://www.onelogin.com/product/multi-factor-authentication

**Comment by Carlgo11** [comment]
Sounds like a good idea. Especially since we've already removed them from twofactorauth.org/providers

**Comment by brycx** [comment]
I opened PRs for both things.

**Comment by stephengroat** [comment]
closing due to new Guidelines https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines

**Pull request closed without merging**
