### PR TITLE
Added Apple ID

### PR DESCRIPTION
**Pull request by realModusOperandi**
Added to retail section since 2FA only kicks in to make a purchase on their various online stores, or to manage the account itself.

### CODE REVIEW

**Comment by KevinBongart** [comment]
:+1:

**Comment by jdavis** [comment]
I'm working my way up to it. Expect it to be merged soon =]

**Comment by jdavis** [comment]
Oh shoot. I removed the Custom section because I thought you just linked it there for more info. Did you mean to have it in there for the fingerprint capability as the 2FA? I completely forgot about that.

**Comment by realModusOperandi** [comment]
I included it because you can add any ios 7 (and maybe earlier) device as a trusted device, and the code will appear on screen (not an SMS, an actual popup) when authenticating.

**Comment by jdavis** [comment]
K, that's what I thought after I deleted it. I'm re-adding it.

**Comment by realModusOperandi** [comment]
Yeah, it's a bit confusing because an OS itself is a 2FA client. Probably should have explained in the commit message, sorry.

**Comment by jdavis** [comment]
Yeah, it was my bad too. I should have looked more into it. I'm stuck on iOS 6. Damn old hardware =P

**Pull request closed without merging**
