### PR TITLE
Add Hashicorp Atlas

### PR DESCRIPTION
**Pull request by wldhx**

### CODE REVIEW

**Comment by RichJeanes** [comment]
Perhaps this for the doc link: https://atlas.hashicorp.com/help/user-accounts/authentication

There it also says that they support codes over SMS and TOTP. Could you also add `sms: Yes`

It may not be full details, but it is documentation that they support TFA and gives a link to the page you can enable it on.

**Comment by wldhx** [comment]
Sorry, did not look for docs well enough. Updated.

**Comment by RichJeanes** [comment]
Did you just modify the commit instead of adding another? How did you do that?

**Comment by wldhx** [comment]
```
// add some changes
git commit --amend
git push -f
```

**Comment by RichJeanes** [comment]
Oh. Well then. Didn't know there was an `amend` command. Neat. Thanks.

**Comment by wldhx** [comment]
Not a problem :) BTW, another way to do it would be `git rebase -i`. And yet another - providing N commits in a PR and having you `merge --squash` them (this way my version would still have N commits, while the merge target would have all changes in one commit).

**Pull request merged**
