### PR TITLE
Added Nintendo Account to the list.

### PR DESCRIPTION
**Pull request by larsenv**
[Nintendo accounts now have 2FA.](https://www.theverge.com/2017/9/23/16355268/nintendo-account-two-factor-authentication-cybersecurity) Removed "Nintendo Network" from the list and replaced it with this.

Also fixed capitalization of PlayStation Network.

### CODE REVIEW

**Comment by RichJeanes** [comment]
Your changes are not entirely accurate. The "Nintendo Account" does NOT replace the "Nintendo Network ID". To see our discussion on this topic, please see #2742. If you would like to update your PR to match the requested changes there (or close this and open a new one), that would be wonderful!

**Comment by RichJeanes** [comment]
Your changes are not entirely accurate. The "Nintendo Account" does NOT replace the "Nintendo Network ID". To see our discussion on this topic, please see #2742. If you would like to update your PR to match the requested changes there (or close this and open a new one), that would be wonderful!

**Comment by larsenv** [comment]
You can link a Nintendo Network ID to a Nintendo Account, so I don't think Nintendo will support 2FA on a Nintendo Network ID alone.

Anyway, I added it back to the list and added the doc page.

**Comment by RichJeanes** [comment]
No, the Nintendo Network ID does not support 2FA, which is why we say in [#2742](https://github.com/2factorauth/twofactorauth/issues/2742#issuecomment-331477853) that the Nintendo Account needs an exception text on it stating that the 2FA can be bypassed by a linked Nintendo Network ID. See [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#exceptions--restrictions), example number 2.

**Comment by larsenv** [comment]
Right, the Nintendo Network ID does not support 2FA, but a Nintendo Account does.

I’ll put the message up.

**Comment by larsenv** [comment]
Is the exception I added what you wanted me to put?

**Comment by larsenv** [comment]
@RichJeanes You never replied, is the exception I put what you asked for?

**Comment by RichJeanes** [comment]
Sorry about that. Thanks for the bump.

The wording is good, but the exception needs to be on the Nintendo Account entry. Saying that 2FA can be bypassed on Nintendo Network using... Nintendo Network... which doesn't have 2FA to bypass... That doesn't really make sense.

Also, perhaps we should give them different URLs.
How about https://accounts.nintendo.com for the Nintendo Account
And https://id.nintendo.net for Nintendo Network

**Comment by jamcat22** [comment]
It appears Nintendo has fixed this vulnerability, and signing in on https://account.nintendo.com with any linked accounts (including Nintendo Network IDs, Facebook, Google, and Twitter accounts) now triggers the 2FA prompt. Could someone with a Nintendo Switch verify this by attempting to link a Nintendo Account to a user account using a Nintendo Network ID login by following [these instructions](http://en-americas-support.nintendo.com/app/answers/detail/a_id/22406/~/how-to-link-a-nintendo-account-to-nintendo-switch)?

Either way, the exception placed on the Nintendo Account entry should note that child accounts cannot enable 2FA, as explained in [#2742](https://github.com/2factorauth/twofactorauth/issues/2742#issuecomment-331477853). The text could read similar to the following: `2FA not available for child accounts of users 12 years of age or younger.`

**Comment by RichJeanes** [comment]
Confirmed. Signing in to the Switch using my Nintendo Network ID directed me to the Nintendo Account 2FA verification page. Does this mean that the Nintendo Network entry should be ```tfa: Yes``` with an exception stating that it can only be enabled by linking to a Nintendo Account?

**Comment by jamcat22** [comment]
@RichJeanes I'd say no because the Nintendo Network ID itself is not protected. Logging in on https://id.nintendo.net, the Nintendo eShop, and linking a Nintendo Network ID to a 3DS or Wii U doesn't require 2FA, only logging in to the Nintendo Account _using_ a Nintendo Network ID does. Therefore, only the Nintendo Account is protected _not_ the Nintendo Network ID itself.

**Comment by RichJeanes** [comment]
Okay, that's fair.

So, @larsenv 
1) Remove the exception from Nintendo Network
2) Add an exception to Nintendo Account that reads: ```2FA not available for child accounts (users 12 years of age and younger).```
3) Change the Nintendo Account URL to https://accounts.nintendo.com
4) Change the Nintendo Network ID URL to https://id.nintendo.net

(Edited by @jamcat22 to include the URL updates. 👍)

**Comment by larsenv** [comment]
@RichJeanes OK, done. Does it look good now?

I doubt that Nintendo Network will have 2FA, because it's only used on the Wii U and 3DS, and lately the newest services by Nintendo are using a Nintendo Account, so it's not likely they are gonna put 2FA for Nintendo Network.

Miiverse, which is the something major that uses a Nintendo Network ID is gonna be discontinued on November 7.

**Review by RichJeanes — APPROVED** [review]

**Review by jamcat22 — APPROVED** [review]
Added a quick note about the new [supervised accounts](http://en-americas-support.nintendo.com/app/answers/detail/a_id/19624) not being able to enable 2FA.

**Comment by jamcat22** [comment]
Thanks for the PR @larsenv! You can read more about our merging process on our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge).

**Pull request merged**
