### PR TITLE
Add Foursquare to social.yml

### PR DESCRIPTION
**Pull request by hongchangwu**

### CODE REVIEW

**Comment by Carlgo11** [comment]
From what I can see Foursquare doesn't fit the social media category. Maybe another one?
Also, I don't think the site fits the [site criteria](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria).

**Comment by hongchangwu** [comment]
I think this fits criteria 1 since it contains personal image and detailed location information

**Comment by smholloway** [comment]
Foursquare has a lot of location data about its users, which could be bad if leaked. I agree it is worth adding to the site and the PR looks good.

**Comment by mxxcon** [comment]
Seth, but that location data is public, isn't it?

@hongchangwu "personal image" in a sense of reputation, not your avatar...What's the worst that can happen, somebody will steal your account and become a major of a strip club? :wink:

**Comment by hongchangwu** [comment]
@mxxcon location is private data. people can see who have checked in at the same place as you, but they cannot see the detailed history of the places you have been (unless they are your friends). Suppose if your friend's account is breached and then someone figure out your check-in pattern and then break in when you are not home.

**Comment by mxxcon** [comment]
I disagree with this risk assessment, just like I wouldn't consider Yelp qualified for this site, but I won't stop others if they think it's a valid entry.

**Comment by Carlgo11** [comment]
We should list the NSA on our site. That's what I call private data :eyes:

Jokes aside, 2 yeas and 2 nays. Need more voters (@jdavis @jamcat22 ?)

**Comment by Carlgo11** [comment]
Oh and social category?
Let's at least agree on that that's wrong.

**Comment by jamcat22** [comment]
I think the social category is right.

Here's what most people think of as Foursquare: https://www.swarmapp.com/

About 6 months ago, Foursquare split into two different apps. One was called Swarm (basically what Foursquare used to be) and the other was Foursquare.

Foursquare used to be an app that you would check into places with your phone (shared either publicly or privately) so that your friends could see where you were. It was basically the thing before Facebook Places (which actually stole Foursquare's old logo). Then, all of those features were moved to an app called Swarm by Foursquare. Lots and lots of people were mad (about how mad people were when Facebook forced people to download Facebook Messenger), but Foursquare stood their ground. Eventually, Foursquare turned into an app like Yelp, and Swarm was like the old Foursquare.

Both use the same account system though so it makes sense to list Foursquare under social, as when most people think of Foursquare, they are actually thinking of Swarm.

**Comment by jamcat22** [comment]
It makes sense to add Foursquare, as their app (Swarm) tracks your location and you can post almost everywhere you go. Plus, there is a private option, as most people don't want everyone knowing where they have been.

Basically, Foursquare is Facebook, but only for location. (So if we can justify adding Facebook because of their Places feature, we can justify adding Foursquare.)

**Comment by jamcat22** [comment]
https://www.swarmapp.com/ will make adding this as an entry justifiable. You should look at it. (But again, Facebook can do the same thing.)

**Comment by jamcat22** [comment]
Also, this:
image

**Comment by hongchangwu** [comment]
@Carlgo11 I'm fine with changing if there is a more suitable category (FWIW the main Foursquare app is listed in the "Travel" category in the Apple Store as of now while Swarm is listed in the "Social" category)

@jamcat22 I agree with you on Swarm. But problem is that even after one year of launching, Swam simply doesn't have the same recognition as Foursquare. When most people talk about Foursquare, they still more of less think of it as a check-in service. Also I don't think https://www.swarmapp.com/ has a separate login.

**Comment by jamcat22** [comment]
@hongchangwu That's my exactly the point I was trying to make. (Sorry that it got a bit long.)

**Comment by smholloway** [comment]
Any resolution? I'm a weak yes. The risk I see: it would be bad if, for example, a public figure was hacked then checked in at every strip club in their city during work hours.

**Comment by Carlgo11** [comment]
Okay yes it is then.

**Comment by Carlgo11** [comment]
Anyone want to add the looks-good?
I'm on my phone 🙈

**Pull request merged**
