### PR TITLE
Add VeeroTech

### PR DESCRIPTION
**Pull request by meirroth**

### CODE REVIEW

**Review by phallobst — CHANGES_REQUESTED** [review]
Please replace the icon with this optimized version:
veerotech

**Comment by meirroth** [comment]
@phallobst done.

**Comment by ApCoder123** [comment]
Hi @meirroth
It looks like you forgot to delete the old image. Also, the new image should go in `img/hosting/veerotech.png` not `img/veerotech.png` where it is at the moment. Thanks.

**Comment by meirroth** [comment]
@ApCoder123 fixed, sorry about that.

**Review by ApCoder123 — APPROVED** [review]

**Review by phallobst — APPROVED** [review]

**Pull request merged**
