### PR TITLE
Update Joyent - doc

### PR DESCRIPTION
**Pull request by LeFouineur**
Using the new url link for the documentation

### CODE REVIEW

**Comment by mxxcon** [comment]
This new url is 404 for me.

**Comment by LeFouineur** [comment]
Apparently some browsers had problems reading correctly the url at their first try in HTML encoding, so I changed it to a plain-text one

**Comment by mxxcon** [comment]
This works. :+1:

**Comment by Carlgo11** [comment]
Great your PR has been merged.
For more information on what happens next go to [our new wiki](https://github.com/jdavis/twofactorauth/wiki/FAQ_Merge)

**Pull request merged**
