### PR TITLE
Added Clio to other.

### PR DESCRIPTION
**Pull request by plecavalier**

### CODE REVIEW

**Comment by jamcat22** [comment]
Please don't remove the status link for IFTTT.
Please make `Email:` all lowercase, changing it to `email:`

**Comment by jamcat22** [comment]
Your PR interferes with another website on the list.
Look at the changes in the [Files changed](https://github.com/jdavis/twofactorauth/pull/1018/files) tab to see what I mean.

**Comment by jamcat22** [comment]
You can also remove the `twitter:` line if you would like. That is only used when a website does not support 2FA.

**Comment by mxxcon** [comment]
@plecavalier you should create separate branches for your changes. otherwise, if you work from the same `master` branch, your changes to one pull request will show up in the other.

**Comment by plecavalier** [comment]
@Jacob Sorry that wasn't my intention. I'll fix that.

@mxxcon Yeah I just learnt that yesterday. Dealing with source code is
clearing not my strong point. I'll get the hang of it eventually...

Thanks! Phil
Ottawa: 613-851-2926
Cornwall: 613-703-0115

Any distribution, use or copying of this e-mail or the information it
contains by other than the intended recipient(s) is unauthorized.

**Comment by Carlgo11** [comment]
uhm there's a `-` on every line you've added. There should only be a `-` in front of `name:`

**Pull request closed without merging**
