### PR TITLE
Add BEE Plugin

### PR DESCRIPTION
**Pull request by 40504**

### CODE REVIEW

**Review by Carlgo11 — COMMENTED** [review]
Looks like a better fit for the communications category along with all the other email creation and customer outreach sites.

**Comment by 40504** [comment]
> Looks like a better fit for the communications category along with all the other email creation and customer outreach sites.

they use different login details for this https://beefree.io/ and this https://developers.beefree.io/
https://beefree.io/ is suitable for communications category and there is no 2FA option, at least for free users, but for https://developers.beefree.io/ I successfully enabled two-factor authentication.

**Comment by Carlgo11** [comment]
So what does the developer sub domain offer?

**Comment by Carlgo11** [comment]
I'm not certain it should be listed then. We don't list things like [developer.twitter.com](https://developer.twitter.com) and [developers.facebook.com/](https://developers.facebook.com/).
If the main business is to design emails it doesn't make much sense to list their side-business. It will probably confuse more than it would help.

**Pull request closed without merging**
