### PR TITLE
Add more checks in verify.rb

### PR DESCRIPTION
**Pull request by Carlgo11**
Hello,

This PR adds more tag checks in verify.rb and organizes the functions.

**This PR (#1565) is built upon #1564.**

//@Carlgo11 :tay:

### CODE REVIEW

**Comment by jamcat22** [comment]
Do we have a check for making sure there's not a `doc` tag when `tfa: No` exists? I don't see one right now...

**Comment by Carlgo11** [comment]
@jamcat22 I will add this in a couple of minutes.

**Comment by jamcat22** [comment]
@Carlgo11 Wow! Thanks for complimenting my suggestion.

**Comment by Carlgo11** [comment]
The power of editing someone's messages. :tay:

**Comment by mxxcon** [comment]
@Carlgo11 2 images in this PR?

**Comment by Carlgo11** [comment]
@mxxcon screenshot

If #1564 is merged then they'll disappear from the 'Changes' tab.

**Comment by Carlgo11** [comment]
@jamcat22 I can't seem to get the `doc` link check to work...

**Comment by Carlgo11** [comment]
To clarify, I won't add the `doc` tag check in this PR but in another PR.
This PR looks good on my end.

**Comment by Carlgo11** [comment]
I have added the `doc` link check to this PR.

**Comment by jamcat22** [comment]
It most certainly does @Carlgo11!

**Comment by Carlgo11** [comment]
@jamcat22 lay down the editing pen please.

:tay: :tay: :tay:

**Comment by jamcat22** [comment]
I will after this issue.

**Comment by dsoegijono** [comment]
:+1:

**Pull request merged**
