### PR TITLE
Webde

### PR DESCRIPTION
**Pull request by luh2**
add web.de mailer

### CODE REVIEW

**Comment by Carlgo11** [comment]
I suggest you use this image instead.
It's a bit less pixely 😉 
fsie74o2

**Comment by luh2** [comment]
done

**Comment by stephengroat** [comment]
Do we want to add the `lang: de` tag to this as well?

**Comment by Carlgo11** [comment]
Yeah that sounds like a good idea

**Comment by Carlgo11** [comment]
Since this is the #1989:th PR here's an obligatory Tay Tay gif 😄

**Comment by Jawshy** [comment]
~~~~

**Pull request merged**
