### PR TITLE
Added Dashlane, Keeper, Persowna, and SecureSafe

### PR DESCRIPTION
**Pull request by jamcat22**
I couldn't find an image for Persowna. See #448

### CODE REVIEW

**Comment by mxxcon** [comment]
For Persowna you can probably use Mozilla's persona logo https://people.mozilla.org/~smartell/persona/assets/persona-logo.png

(also it would be great if each site was submitted as a separate branch/pull request so that each one can be evaluated/merged independently)

**Comment by jdavis** [comment]
Yeah, in the future, be sure to keep each site in its own pull request.

**Comment by jdavis** [comment]
I get an SSL error when I try going to https://dashlane.com ...

**Comment by jamcat22** [comment]
@jdavis Crap. Let me add a www.
@mxxcon Was just going off of what you said on #448. I already setup all of my requests a while ago. If you want, I can redo them all. Might take a little while...

**Comment by jdavis** [comment]
Is this good to go, @jamcat22?

**Comment by jamcat22** [comment]
It should be done.

**Comment by jdavis** [comment]
YOU LEFT OFF THE IMAGE THAT @mxxcon GAVE, @jamcat22.

Just kidding. I added it. =]

**Pull request merged**
