### PR TITLE
Add Bank Zachodni WBK

### PR DESCRIPTION
**Pull request by NullPiotrException**
Bank Zachodni WBK is one of the biggest Polish banks.
They support SMS 2FA and used to support custom hardware 2FA for business clients only.
I've contacted the support and new business partners can't have hardware 2FA anymore. This is just an info for future contributors, just in case they wanted to set hardware 2FA.

[Alexa stats](https://www.alexa.com/siteinfo/bzwbk.pl)

Edit: It supports [English version](https://www.bzwbk.pl/english/about-bz-wbk/about-bz-wbk.html) (on the login page [too](https://www.centrum24.pl) - click the flag).

### CODE REVIEW

**Comment by stephengroat** [comment]
@einsteinsfool could you confirm that this is authentication (i.e. on login) and not simply authorization (i.e. for sensitive transactions)? I think i read that the service offered is authorization, but i want to make sure.

twofactorauth currently only lists authentication and are under the practice of list `tfa: No` for services that only provide authorization (since it's not true authentication)

**Comment by NullPiotrException** [comment]
@stephengroat Yes, I use it and can confirm that. BZWBK is unfortunately one of few (3?) banks in Poland that have SMS authentication (on login) and not only authorization (on transfers).
screenshot_20180313_212651

**Review by stephengroat — APPROVED** [review]
trusting @einsteinsfool's explanation over google translate

**Review by pawelci — APPROVED** [review]

**Comment by conorgil** [comment]
Looks good to me too when I run it locally. @stephengroat @Carlgo11 good to merge?

**Review by jamcat22 — APPROVED** [review]

**Pull request merged**
