### PR TITLE
Add PortalGuard

### PR DESCRIPTION
**Pull request by PortalGuard**
pg logo
We would like to be added to your list of 2FA Providers. 

http://www.portalguard.com

### CODE REVIEW

**Comment by mxxcon** [comment]
Your commit is missing a logo.

Also don't you think it's better suited in http://twofactorauth.org/#identity category rather than providers? It seems like it uses existing solutions like google authenticator-compatible TOTP, yubikey, etc.. rather than being a 2FA provider in its own.

**Comment by PortalGuard** [comment]
Hey MXXCON,
Thanks for getting back to me. 
I can see where you would think that, but we actually integrate with those things as well as provide 2FA separately. Check out http://www.portalguard.com/passwordhead.html. This is our registered trade mark product.

**Comment by mxxcon** [comment]
@PortalGuard do you know how to upload images with regular git client and append commits in github?

Correct if I'm wrong, from what I see you have your own 2FA implementation "PassiveKey" that is a custom software running on the same computer as vpn client?

**Comment by PortalGuard** [comment]
No, I am not sure how to upload images with regular git client and append commits in github.

Yes, you are correct we do have our own 2FA implementation "PassiveKey" that is our custom software. It can be running on vpn and web-based traffic.

**Comment by mxxcon** [comment]
@PortalGuard accept my pull request in your own repo and once it's merged there, it should show up here.

**Comment by PortalGuard** [comment]
Okay, I believe I merged your pull request.

**Comment by dsoegijono** [comment]
It should be "email" instead of "e-mail"

**Comment by mxxcon** [comment]
@PortalGuard Looking over this once again, if we are adding PortalGuard because of PassiveKey product, then the info should be updated to have only `software: yes`. PassiveKey does not work over `sms`, `email` or `phone`.

**Comment by PortalGuard** [comment]
@mxxcon PortalGuard is the product and PassiveKey is one of the options available with PortalGuard. We do support ams, email and phone with the PortalGuard product. http://www.portalguard.com/two-factor-authentication.html We also have 10 different OTP delivery methods, and we support hardware based tokens such as YubiKey (we recently added support for HMAC based OTP tokens and finalizing RSA SecurID) SecurAuth is one of our biggest competitors, and we do everything that they do and more, and they are on your list. 

Thank you for your help in this and being so responsive. We greatly appreciate it.

**Comment by mxxcon** [comment]
But we are adding it here into the `providers` section. This section is specifically designed to list TFA providers...Like Google Authenticator, Duo, Yubikey, Authy, etc etc. If somebody wanted to use PassiveKey, this page would show them what kind of devices/processes it supports.
Like we discussed above, while Portalguard _supports_ other authentication methods, it provides only "PassiveKey", which is a software solution.

Alternatively, it can be listed under http://twofactorauth.org/#identity category as PortalGuard as a whole.

**Comment by PortalGuard** [comment]
Thanks for getting back . . . just to make sure, I wanted to check to make sure we are both talking about the same page. We are looking to get onto this page http://twofactorauth.org/providers/. The companies listed here (SecureAuth, Duo Security, Free OTP) are not 2FA providers either, yet they are on the list. They support them and integrate with them(just like we do), so I am just curious what credentials it takes to get onto that list? 
Thanks again for your help. Just trying to understand how a company gets onto this list.

Thanks

**Comment by mxxcon** [comment]
I guess we have a bit of a confusion on what "provider" is. :smile: 
The simplest terms would be make some type of TFA client...
For example SecureAuth makes https://play.google.com/store/apps/details?id=secureauth.android.token plus a bunch of related apps and services.
Duo has https://www.duosecurity.com/authentication-methods. They make all these clients for other services to use and integrate with.
FreeOTP is an opensource client alternative to Google Authenticator.

**Comment by PortalGuard** [comment]
Great, thanks for the provider clarification.
So it looks like having a software based application is what qualifies SecureAuth and Duo to get on your list?

We actually have two:  one being PassiveKey, our client software, two-factor application. PassiveKey is a TOTP generator that can be downloaded and used by our customers. http://www.portalguard.com/http-authentication-methods.html

Second, our own software, PortalGuard, provides two-factor for the desk top that our customers can download. http://www.portalguard.com/user-authentication.html

PortalGuard is the product: includes PassiveKey and Desktop Authenticator. The customer can choose to download either or both of these with PortalGuard.

**Comment by mxxcon** [comment]
@PortalGuard and both of those are software solutions, not sms, email or phone calls.

**Comment by PortalGuard** [comment]
Those two are software solutions. 
We also provide 9OTP delivery methods.
SMS
Voice
Email
PassiveKey
YubiKey
Google Authentication
HMAC
Helpdesk Generated OTPs
Printed

If you still have questions, you can definitely give us a call. 603-547-1200
Thanks for all your help.

**Comment by mxxcon** [comment]
Yes, you utilize them in your product. There's no dispute of that.
But those other methods are _not your own_.
`providers` category is specifically to list various TFA implementations/clients.
Do you really not see the difference between the types of companies listed in `providers` category and `identity management` category?

**Comment by Carlgo11** [comment]
@PortalGuard If you provide YubiKey support doesn't that mean you provide hardware TFA as well?

**Comment by PortalGuard** [comment]
https://play.google.com/store/apps/details?id=com.totp.main&hl=en @mxxcon Please see the link for our "own" TFA client. We also have an Apple one that will be loaded within a day or two.

**Comment by mxxcon** [comment]
@PortalGuard once again, I have no problem adding PortalGuard to `providers` list only with `software: Yes`.
I do have a problem with `sms: Yes` and `email: Yes` since it is not part of your own service but another TFA provider.

**Comment by PortalGuard** [comment]
@mxxcon Alright, that sounds good. We would like to be on the list of providers.
We will let you know as other functionalities become available.
Thanks

**Comment by Carlgo11** [comment]
@PortalGuard Either remove `sms: Yes` and `email: Yes` or close the PR.

**Comment by PortalGuard** [comment]
Do you know when PortalGuard will be placed on your lists of providers? If you have any questions please give us a call to talk to one of our in-house technicians at 603-547-1200.

**Comment by Carlgo11** [comment]
@PortalGuard I told you already to remove `sms: Yes` and `email: Yes` if you want PortalGuard to be added.

Also, I think most of us aren't in the US so calling would be quite difficult and expencive :P

**Comment by PortalGuard** [comment]
@Carlgo11: How exactly do I go in and edit to remove-  sms: Yes and email: Yes. We tried and it will not let us edit or we are doing it wrong. Thanks.

**Comment by Carlgo11** [comment]
Well since you just removed the files it's now impossible. You'll have to send a new pull request

**Comment by PortalGuard** [comment]
I removed the files? I accidentally hit delete PortalGuard: patch-1 a few minutes ago and then realized and hit restore... did that do it? I can send a new pull request.

**Comment by Carlgo11** [comment]
Oh right you did. Then just go to <a href="https://github.com/PortalGuard/twofactorauth/blob/9d510854c2476e5cdbc0aec1005610f670f404c9/_data/providers.yml"> this site</a> and press the pen tool to edit the file

**Comment by PortalGuard** [comment]
I went to that page and clicked the pen tool to edit our file but it says I must be on a branch to make or propose changes to the file.

**Comment by Carlgo11** [comment]
<a href="https://github.com/PortalGuard/twofactorauth/blob/patch-1/_data/providers.yml">This site</a> then.

**Comment by PortalGuard** [comment]
Alright, I removed sms: Yes and email: Yes .

**Pull request merged**
