### PR TITLE
Add Bitclude

### PR DESCRIPTION
**Pull request by bitclude**
Security section:
https://bitclude.com/en/security-in-bitclude

How to set google 2FA:
https://help.bitclude.com/how-to-enable-2fa-dual-authorization/

SMS authentication and E-Mail authentication is required by default.

### CODE REVIEW

**Comment by 40504** [comment]
Hi, [Alexa Rank](https://www.alexa.com/siteinfo/bitclude.com) for bitclude.com is # 204,417.
To be listed,

> the site should be ranked within the top 200,000 sites on Alexa or has a substantial social media following.

thats why **workflow** not passed and it is mean the website will not be included in the list, at the moment.

**Comment by 40504** [comment]
I will add the website in our internal websites list that support 2fa option, specifically TOTP. That list we use in this application: https://apps.apple.com/app/id/id1538761576

**Comment by phallobst** [comment]
Please rebase your branch to the current master.

**Comment by Carlgo11** [comment]
Closing due to inactivity.

**Pull request closed without merging**
