### PR TITLE
Add Planio

### PR DESCRIPTION
**Pull request by yeah**
This PR adds FOSS project management tool Redmine (where 2FA support is [in progress and scheduled for 4.1.0](https://www.redmine.org/issues/1237)). The 2FA patch was contributed by Redmine Hoster Planio where 2FA is already rolled out, so I'm adding Planio as well in the same commit.

two factor auth list 2018-01-12 17-54-50

Logos were optimized using `optipng`.

### CODE REVIEW

**Review by stephengroat — CHANGES_REQUESTED** [review]
thanks for the pr @yeah. could you remove the `redmine` entry? we tend not to list self-hosted projects as a rule of thumb

**Comment by yeah** [comment]
Sure, it's only Planio now. Thanks!

**Review by stephengroat — APPROVED** [review]
thanks for the work @yeah look good to me

**Review by Carlgo11 — DISMISSED** [review]
@yeah here's a compressed version of the logo. Please use that instead:
planio

**Comment by yeah** [comment]
I've added the compressed image, thanks. (I've also squashed the commits and rebased on current master.)

**Comment by yeah** [comment]
As said before, I've uploaded the new image, ready to merge!

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
