### PR TITLE
Add Frankdomains

### PR DESCRIPTION
**Pull request by c960657**
Frankdomains offers TFA using a hardware token.

They charge 19,99 GBP/year for this.

### CODE REVIEW

**Comment by mxxcon** [comment]
Wow. It's so pathetic of them to put a price on safety of their users... What's next, they will charge money for SSL encryption? :-1:

**Comment by Carlgo11** [comment]
Add an exception saying that you have to pay extra for the TFA service.

**Comment by mxxcon** [comment]
Carl, do we usually do that? They are pretty up-front with the cost.

**Comment by Carlgo11** [comment]
We do.

**Comment by c960657** [comment]
@Carlgo11 Done.

**Pull request merged**
