### PR TITLE
Update WhatsApp entry

### PR DESCRIPTION
**Pull request by ghost**
WhatsApp has added 2FA: https://www.whatsapp.com/faq/en/general/26000021

### CODE REVIEW

**Comment by Carlgo11** [comment]
I don't really see why it's necessary with an exception text for this.

**Comment by jamcat22** [comment]
I agree with Carl here. The doc page explains how to setup 2FA, so I don't think the exception is necessary.

**Comment by ghost** [comment]
When I first visited twofactorauth.org, I interpreted the tables so that the columns that are on the right side of the docs column are what each service uses as the secondary form of authentication. Some services like WhatsApp use SMS codes for single-factor authentication, and optional user-defined passcodes/passwords are what ultimately complete the picture so that the users have 2FA in place.

I would like it if twofactorauth.org added two new columns: One for what each service uses for single-factor authentication and one named Passcode/Password. Then the WhatsApp entry could say SMS in the SFA column and have a check mark in the Passcode/Password column.

As long as there isn’t a separate column for what each service uses for single-factor authentication, I think it would be reasonable to add exception notes to the exceptions that use something other than user-defined passwords for single-factor authentication.

**Comment by ghost** [comment]
I think it's important to distinguish what each service uses for single-factor authentication, because there <s>are cases</s> _is one case_ where – due to the service using SMS for SFA – an attacker could get access to most if not all of the user's messaging history by intercepting a single SMS code:

https://www.fredericjacobs.com/blog/2016/01/14/sms-login/
https://www.fredericjacobs.com/blog/2016/04/29/more-on-sms-logins/

Edit: On the other hand, I can see why making this distinction wouldn't be that important in the case of WhatsApp, because they don't store their users' messages on servers like Telegram does.

**Comment by ghost** [comment]
Judging by the silence, I don't think the exception text I added is going to receive any more approval at this point, so I have now removed it.

The issue of twofactorauth.org not showing what each service uses for single-factor authentication can probably be discussed in a separate issue thread.

**Comment by mxxcon** [comment]
@echo743 silence sometimes simply means that people are busy, not always that they disagree. 😉 
However, this site is about 2FA support. _I_ think cataloging the primary login system is somewhat beyond our scope. For example, I think there was a fork of this site that was documenting password length/strength of various sites. Perhaps the info you want to include is better suited there?

**Review by stephengroat — APPROVED** [review]

**Pull request merged**
