### PR TITLE
Add Misfit to Health

### PR DESCRIPTION
**Pull request by whatinthenameofgod**
Referencing #1416

### CODE REVIEW

**Comment by mxxcon** [comment]
What is sensitive about this site that justifies it being added?

**Comment by whatinthenameofgod** [comment]
It's an activity tracker like Fitbit and you access your data through the account...

**Comment by whatinthenameofgod** [comment]
http://techcrunch.com/2015/06/16/misfit-debuts-an-online-dashboard-for-tracking-health-and-fitness-activity-across-devices/

Could this be merged? If and when it is, #1416 can be closed.

**Comment by whatinthenameofgod** [comment]
Bueller? Bueller?

**Comment by jamcat22** [comment]
Sorry for the wait @whatinthenameofgod. Thanks for the PR.

It may take some time before your PR shows up on the site. For more info, check out our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_MERGE).

**Pull request merged**
