### PR TITLE
Add Transifex

### PR DESCRIPTION
**Pull request by ch3thanhs**
Adding the localization platform Transifex.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Are you able to find an icon to use instead of the entire logo?

**Comment by ch3thanhs** [comment]
> Are you able to find an icon to use instead of the entire logo?

I couldn't find a .svg icon, hence the whole logo.

**Comment by ch3thanhs** [comment]
@Carlgo11 Replaced the logo with an icon.

**Comment by Carlgo11** [comment]
What about this one? SVGs are preferred over PNGs as they are scalable.
Logo

**Comment by ch3thanhs** [comment]
Have replaced it with the SVG.

**Review by hkamran80 — APPROVED** [review]

**Pull request merged**
