### PR TITLE
CSS fixes

### PR DESCRIPTION
**Pull request by phallobst**
* Logo scales properly (to a max size)
* Search bar is not overlapping the text anymore

### CODE REVIEW

**Review by dsoegijono — APPROVED** [review]
Before & after screenshots would be great for UI changes I think.

**Comment by phallobst** [comment]
Here are the screenshots for comparison, with 200% and 25% zoom respectively.

Before, zoomed in: Logo is not scaled, search bar overlaps the text
before-zoom-in
Before, zoomed out: Logo is not scaled, large gaps around search bar
before-zoom-out

After, zoomed in:
after-zoom-in
After, zoomed out:
after-zoom-out

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
uhm...

**Comment by phallobst** [comment]
:astonished: Was the CSS rebuilt from an old state somehow? It _did_ work before. On a local installation, I don't see the problem.

The `#logo` should _not_ have `height: 30vh` (but `20em`).

**Pull request merged**
