### PR TITLE
Add StartJOIN

### PR DESCRIPTION
**Pull request by juanda-097**
StartJOIN is a crowdfunding platform that accepts as payment crypto currencies.

I have a problem to upload startjoin logo. If someone help me upload it, I would be very grateful https://pbs.twimg.com/profile_images/378800000584095301/fd897157c1d35f17e9aba63ba2dbb7d2_400x400.png

### CODE REVIEW

**Comment by LeFouineur** [comment]
What problem do you have with uploading the pic ?

startjoin (Here is a 32x32px compressed version)

**Comment by juanda-097** [comment]
the problem I have, is that not knowing how to upload the photo. I am new to using GitHub.

Excuse me for my english.

**Comment by RichJeanes** [comment]
Images cannot be aded through the GitHub website. You will have to use a local git client (such as commandline git, the official graphical git clients, or SourceTree) to add an image to the repo.

**Comment by Carlgo11** [comment]
@juanda-097 look at [New TFA Site](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_TFA_SITE) stage 4 & 5.

**Comment by Carlgo11** [comment]
@juanda-097 are you going to add another commit to the PR?
If not then I will close the PR in a few days just to clean up the list of PRs.

**Pull request closed without merging**
