### PR TITLE
Add MrExcel

### PR DESCRIPTION
**Pull request by Rabadash8820**
Adds the [MrExcel forum](https://www.mrexcel.com/). I'm opening this PR as a draft because I didn't include an icon. I wasn't sure if you all have a system for finding the "right" SVG icon for a website. I was able to grab the favicon.ico for this site, convert it to SVG, and optimize it with SVGOMG, but the resulting SVG didn't really look anything like the original favicon...

### CODE REVIEW

**Comment by hkamran80** [comment]
Hello @Rabadash8820,

Unfortunately, forums are not allowed on 2FA Directory. In the future, please review our [site guidelines](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) and [exclusion list](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md) before adding a site.

**Comment by Rabadash8820** [comment]
Hi @hkamran80, I did read the site guidelines. I assumed this site would be acceptable because it is not a subdomain and is listed in the SimilarWeb 200k results. It is a forum devoted to technical issues with Microsoft Excel, so it's very similar to Stack Exchange or Quora, which are also included on 2FA Directory.

**Comment by hkamran80** [comment]
No forums are allowed in the directory, regardless of Similarweb ranking or domain/subdomain status.

**Comment by Rabadash8820** [comment]
Hm, I still feel like Stack Exchange, Quora, Reddit, etc. could easily be considered forums, but I'll respect your decision. 👍

**Pull request closed without merging**
