### PR TITLE
add domainFACTORY

### PR DESCRIPTION
**Pull request by matgalli**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Please don't make multiple pullrequests about the same website.

**Comment by Carlgo11** [comment]
We have several sites like this who provide both domains and webhosting. One example is <a href="https://www.loopia.com/">Loopia AB</a> that we've put under the **Domains** category.
Considering the site's name is Domain Factory I think the same should be done with this site.

Please move the site to `_data/domains.yml` and while doing it try not to create another pull request.

Thank you,
<s>@psgs :palm_tree:</s>
I mean, @Carlgo11

**Comment by matgalli** [comment]
ok, I will try

**Comment by Carlgo11** [comment]
img/domains/domainfactory.png is not 32x32px. Please change the image to 32x32px

**Comment by matgalli** [comment]
There is no icon bigger then 32x32px so I have it scaled up

**Comment by mxxcon** [comment]
@matgalli :+1: Or you could do it the other way around and scale down a larger image :wink:
But good enough either way.

**Comment by Carlgo11** [comment]
well it looks okay for the human eye. I'm giving it a go

**Pull request merged**
