### PR TITLE
Add JetBrains

### PR DESCRIPTION
**Pull request by invalidCards**
JetBrains, one of the leading developers of IDEs, does not support 2FA even though literally all a JetBrains account is used for is storing license keys.

### CODE REVIEW

**Comment by stephengroat** [comment]
@ThePsionic thanks for your PR! 2factorauth.org has started to add `facebook` tags for sites. I've included the `facebook` tag for you, make sure it looks good

**Review by stephengroat — APPROVED** [review]
went through logos, couldn't find any instance of them just using a color squiggly mark without any text

**Comment by mxxcon** [comment]
Please use this logo from their favicon.
jetbrains

**Comment by invalidCards** [comment]
@mxxcon Changed.

**Pull request merged**
