### PR TITLE
Remove providers page

### PR DESCRIPTION
**Pull request by smholloway**
This PR addresses [issue 1173](https://github.com/jdavis/twofactorauth/issues/1173) where several contributors agreed that the providers page had outlived its usefulness.

### CODE REVIEW

**Comment by mxxcon** [comment]
Perhaps remove it with a placeholder saying it was retired to prevent 404 in case somebody linked directly to it?

**Comment by smholloway** [comment]
Ah, good point. How do you feel about simply redirecting back to the homepage? A quick search shows [one redirect method using a gem](https://help.github.com/articles/redirects-on-github-pages/).

**Comment by mxxcon** [comment]
We could redirect, although that would imply that content from providers moved to the homepage, which did not..hmm, would that be a correct thing to do?

**Comment by smholloway** [comment]
Another good point. I can add a barebones providers page. Here's my first pass at the text on that page:

> The providers page was removed. To find a two factor authentication provider, please use your favorite search engine.

Feedback welcome.

**Comment by Carlgo11** [comment]
:+1:

**Comment by mxxcon** [comment]
Yup, i'm cool with that wording

**Comment by smholloway** [comment]
twofactorauth.org Providers Page

**Comment by jamcat22** [comment]
Should we say "The providers page has been removed." instead of "The providers page was removed."?

**Comment by jamcat22** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- _data/providers.yml @ r1
- _includes/header.html @ r1
- _includes/note-header.html @ r1
- CONTRIBUTING.md @ r1
- img/providers/alterego.png @ r1
- img/providers/authenticatorplus.png @ r1
- img/providers/authentify.png @ r1
- img/providers/authy.png @ r1
- img/providers/azure.png @ r1
- img/providers/bankid.png @ r1
- img/providers/clef.png @ r1
- img/providers/cognalys.png @ r1
- img/providers/cryptophoto.png @ r1
- img/providers/duo.png @ r1
- img/providers/exostar.png @ r1
- img/providers/freeotp.png @ r1
- img/providers/google.png @ r1
- img/providers/idopener.png @ r1
- img/providers/latch.png @ r1
- img/providers/launchkey.png @ r1
- img/providers/logintc.png @ r1
- img/providers/mepin.png @ r1
- img/providers/messente.png @ r1
- img/providers/nexmo.png @ r1
- img/providers/passbyme.png @ r1
- img/providers/pingidentity.png @ r1
- img/providers/portalguard.png @ r1
- img/providers/privacyidea.png @ r1
- img/providers/protectimus.png @ r1
- img/providers/ringcaptcha.png @ r1
- img/providers/rublon.png @ r1
- img/providers/saaspass.png @ r1
- img/providers/sat.png @ r1
- img/providers/sec-sign.png @ r1
- img/providers/secureauth.png @ r1
- img/providers/securegate.png @ r1
- img/providers/securepass.png @ r1
- img/providers/smartsign.png @ r1
- img/providers/solidpass.png @ r1
- img/providers/syferlock_gridguard.png @ r1
- img/providers/symantec.png @ r1
- img/providers/telesign.png @ r1
- img/providers/textpower.png @ r1
- img/providers/token2.png @ r1
- img/providers/toopher.png @ r1
- img/providers/totpme.png @ r1
- img/providers/transakt.png @ r1
- img/providers/vasco.png @ r1
- img/providers/veridial.png @ r1
- img/providers/wikid.png @ r1
- img/providers/wwpass.png @ r1
- img/providers/yubico.png @ r1
- index.html @ r1
- providers.html @ r2
- verify.rb @ r1

---

<sup>**[providers.html, line 24 \[r2\]](https://reviewable.io:443/reviews/jdavis/twofactorauth/1177#-Jrot7RsmHCAHcoMksso)** ([raw file](https://github.com/jdavis/twofactorauth/blob/fff9cbf5759b55e7a5200b283b52e0e73943041c/providers.html#L24)):</sup>
Maybe say "The providers page has been removed. To find a..."

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jdavis/twofactorauth/1177)

**Comment by Carlgo11** [comment]
uhm @jamcat22...?

**Comment by mxxcon** [comment]
@Carlgo11 this is what it looks like if you use Reviewable.io :)

**Comment by Carlgo11** [comment]
Is reviewable.io something new? I've seen several PRs mentioning reviewable.io
And what benefits are there?

**Comment by jamcat22** [comment]
@mxxcon I've been seeing your comments with it so I wanted to try it out...

Best decision I've made this week.

**Comment by jamcat22** [comment]
@Carlgo11 https://gitter.im/jdavis/twofactorauth

**Comment by smholloway** [comment]
@jamcat22 Wording updated.

**Comment by jamcat22** [comment]
Yay! Merge when Travis is done?

**Comment by jamcat22** [comment]
Also, sorry I'm so critical of wording. :smile:

**Comment by jamcat22** [comment]
And I'll just leave one more comment to make @Carlgo11 mad.

**Comment by jamcat22** [comment]
There.

**Comment by jamcat22** [comment]
Ok. I'll merge this now.

**Comment by Carlgo11** [comment]
@jamcat22 :broken_heart:

**Pull request merged**
