### PR TITLE
Sorting validation

### PR DESCRIPTION
**Pull request by ilyakatz**
This PR is an attempt to keep sanity in two ways
- sort all websites in each section
- add validation to the source code to make sure future pull requests keep things nice and organized

Let me know if you think either or both are an overkill

### CODE REVIEW

**Comment by jamcat22** [comment]
Thank you for making this! Helps keep me from exploding when things aren't in order :smile:.

**Comment by Carlgo11** [comment]
@ilyakatz don't forget to do the same with providers. Also, looks awesome 😃

**Comment by mxxcon** [comment]
I think fail Travis test for this is a bit of an overkill. When the page gets generated it's sorted alphabetically so that's good for users. But _requiring_ it to be the same in the source code makes contributing less user friendly. It's a "nice to have" but I wouldn't fail a check for this.

**Comment by ilyakatz** [comment]
i'm ok removing the build failures. one advantage is that since this project has a lot of contributors with various degrees of abilities/desires/patience to keep things organized it could help point people in the right direction. 

any strong opinions?

**Comment by mxxcon** [comment]
I agree, but instead of failure can Travis give warnings? A commit can still go in but if user wants they can correct that issue.
Unless I'm mistaken, malformed Yaml block will fail the same way as unsorted entry.. I think that's bit extreme.

**Comment by Carlgo11** [comment]
@mxxcon give warnings? Well that's kind of what it does already doesn't it? And you CAN merge a PR even if travis failed.

**Comment by jamcat22** [comment]
Maybe remove the failures and just have it put the unsorted items under

<------------ WARNING ------------>

instead of 

<------------ ERROR ------------>

**Comment by Carlgo11** [comment]
But does anyone really look at the Travis output if it passes?

**Comment by jamcat22** [comment]
I do ;)

**Comment by Carlgo11** [comment]
But we want to keep all the sites alphabetical don't we? And we can still merge even if travis fails. It would just be a question of how important it is to keep that specific PR alphabetical.
I think we should merge

**Comment by mxxcon** [comment]
I have no idea if travis or github supports that, but maybe instead of green checkmark we could have a yellow one? or maybe green checkmark with `*` next to it?
Or just leave it as a manual process...

**Comment by Carlgo11** [comment]
Pretty sure that's not possible. At least not in the current way github services are built

**Comment by ilyakatz** [comment]
although, i implemented it, for me personally, the order in the yml is not that important. i think of it, when i put records into database, the ordering may or may not be what i expect. what is important is what the user sees. just my two cents.

but we need some mediation here, since the house seems divided we need the executive branch, @jdavis, break the tie please. sorry, i'm influenced all the election talk in US yesterday :)

**Comment by jdavis** [comment]
I'm okay with sorting all current ones which you did in this commit: fedc5a9aee389e1f9827c74b7a8f77c4ce478c5f

Regarding sorting sites using a Jekyll plugin, that isn't possible using GitHub Pages unless we started pre-building our pages into the `gh-pages` branch. Since a Jekyll plugin is arbitrary Ruby code, GitHub doesn't support running plugins beyond what they officially support: https://help.github.com/articles/using-jekyll-plugins-with-github-pages/

Lastly, I think the sorting in `verify.rb` is good, but instead of running it every single time and requiring it for CI to pass, what if we instead made it a command line argument (say `--sort`) that looks to see if any sites are unsorted and then prints it out. That way a contributor can just run it locally, fix things, and then issue a PR instead of forcing other contributors to keep things sorted. I think contributing to 2fa.org should be easy, so as long as we validate yaml and the image, we shouldn't go beyond that as any additional stuff is to our (the collaborator's) benefit and not the user (who we should be focusing on).

**Comment by ilyakatz** [comment]
ah, I didn't realize the github pages had these limits. well, in that case, how about i close this request and we work on a different way to sort the entries in the yml files with @Carlgo11 in our secret project?

**Comment by Carlgo11** [comment]
lol "secret" :smile: 
I think all the people in this conversation have been informed about the script already :wink:

**Comment by ilyakatz** [comment]
great, secret's out, it's not fun anymore :)
anyways, closing this request. thanks for your input, everyone

**Comment by jdavis** [comment]
@ilyakatz Feel free to open a new PR with this commit: fedc5a9aee389e1f9827c74b7a8f77c4ce478c5f. You can just do:

``` bash
$ git checkout -b pr <whatever head you want here>
$ git cherry-pick fedc5a9aee389e1f9827c74b7a8f77c4ce478c5f
```

Then push it and issue a pull request.

**Comment by ilyakatz** [comment]
@jdavis that's ok, @Carlgo11 and my script will take care of this stuff, so no need to do a little patch now

**Comment by jamcat22** [comment]
But what if people don't use the script... :D

**Comment by ilyakatz** [comment]
next time someone uses it, it will reorder the file

**Pull request closed without merging**
