### PR TITLE
eBay now SMS not software/hardware

### PR DESCRIPTION
**Pull request by gingerbeardman**
See issue: https://github.com/2factorauth/twofactorauth/issues/2455

### CODE REVIEW

**Review by pepsijosh — COMMENTED** [review]
This worked for me in the UK

**Comment by Lantizia** [comment]
I can confirm that there is no longer any way to use a hardware or software token with eBay... all pages that would speak of such things (like http://pages.ebay.com/securitykey/faq.html which is listed on this site) no longer load properly.  However PayPal continues to work just fine.

See the bottom of the first post here... https://github.com/authenticatorplus/logos/issues/23

**Comment by pepsijosh** [comment]
This is not related to the hardware/software token that is not longer supported though this is to mention that this has been replaced with SMS which is working fine, despite I cannot find anything on their website to indicate this, the link in this pull request does work and I have also tested this today on another device and it does send me SMS codes when I log in.
I have uploaded the log in screen for evidance of this screen showing up after I attempt to log in.
screenshot 3

**Comment by Carlgo11** [comment]
Duplicate of #2468

**Pull request closed without merging**
