### PR TITLE
Adding Everlane and Macy's

### PR DESCRIPTION
**Pull request by trampish**
Adding my favorite online retailer and my employer. Only seems right!

### CODE REVIEW

**Comment by trampish** [comment]
Also adding Merrill Edge!

**Comment by jdavis** [comment]
Haha, putting your employer under the spotlight? Nice.

**Comment by trampish** [comment]
Indeed it does, they'll mail you a hardware token upon request/opt-in.

Also noted here: https://github.com/jdavis/twofactorauth/issues/43

This is the best direct link I can find to enroll, it's from the PDF:
https://olui2.fs.ml.com/Login/Login.aspx?sgt=3&target=https://olui2.fs.ml.com/CSLandingPage/ClientServicesIntro.aspx

On Thu, Jun 12, 2014 at 10:54 AM, Daphne Soegijono <notifications@github.com

**Comment by dsoegijono** [comment]
Hmm it seems that I accidentally deleted my previous comment. Here's the [PDF](https://olui2.fs.ml.com/Publish/Content/application/pdf/GWMOL/OnlineUsersGuide.pdf#page=9) that I linked earlier.

**Pull request merged**
