### PR TITLE
Move OpenDNS from Security to Domains

### PR DESCRIPTION
**Pull request by TraderStf**
as most DNS services are here

### CODE REVIEW

**Review by Carlgo11 — DISMISSED** [review]
You need to actually move the listing and image from security. Not just add it to the domains.yml file.

**Comment by TraderStf** [comment]
Sorry for the mess, did not saw the doc (add a line at the top of the main page), just did based on others sites.
I'll do it asap or you can do it if you want. no problemo.
thanks

**Review by brycx — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Comment by mxxcon** [comment]
I'm not sure we should've made this change...OpenDNS.
From their site
>OpenDNS is a suite of consumer products aimed at making your internet faster, safer, and more reliable.

That does not seem like a registrar service..

**Comment by Carlgo11** [comment]
Well... it doesn’t fit security either. A DNS service handles domain names so even though it’s not a domain regristrar I think domain is the best fit.

**Pull request merged**
