### PR TITLE
Added acorns

### PR DESCRIPTION
**Pull request by psmith6**

### CODE REVIEW

**Comment by RichJeanes** [comment]
Thanks for contributing! 

However, your logo that you've included is way too big! Logos need to be 32x32 and preferably under ~2.5KB. For complete guidelines, check out our [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md) and the [Wiki](https://github.com/2factorauth/twofactorauth/wiki).

**Comment by psmith6** [comment]
@RichJeanes Sorry about that. The image has been updated.

**Comment by Carlgo11** [comment]
This logo is half the size. As your logo is above 2Kb I suggest you use this one instead.

acorns

**Comment by psmith6** [comment]
The attached logo has been added

**Comment by Carlgo11** [comment]
Thank you! :smile:

**Pull request merged**
