### PR TITLE
Add new provider DigiFlak

### PR DESCRIPTION
**Pull request by Driim**

### CODE REVIEW

**Comment by mxxcon** [comment]
This service has invalid SSL cert and when I load the page all I see is:

> You were probably seeking something else, but this is all we have to offer at the moment. In all likelihood, the page that used to be here, has been moved or removed.

**Comment by Carlgo11** [comment]
@mxxcon the site looks to be parked at a domain registrar called "zone15".
I seriously hope @Driim entered the wrong url...

**Comment by Driim** [comment]
I tested site in http, https version doesn't work.

**Comment by Carlgo11** [comment]
Pro tip: If you don't support https then don't use a https url :P

**Comment by mxxcon** [comment]
I'm hesitant that a provider doesn't even have their own ssl... :/

**Comment by Driim** [comment]
But you can buy them on Amazon.

**Comment by Carlgo11** [comment]
so?

**Comment by Driim** [comment]
I mean device must work even without ssl on their site :)

**Comment by jamcat22** [comment]
The providers page is being removed. You can read more about it on #1177.

**Pull request closed without merging**
