### PR TITLE
Add Banco Galicia (AR)

### PR DESCRIPTION
**Pull request by fainpablo**

### CODE REVIEW

**Comment by phallobst** [comment]
Could you also use https://tinypng.com to compress the icon (on this and future PRs)? This often reduces the file size considerably.

**Comment by fainpablo** [comment]
> Could you also use https://tinypng.com to compress the icon (on this and future PRs)? This often reduces the file size considerably.

Sure thing. Latest file should be 1 KB.

**Comment by phallobst** [comment]
Even for seemingly small files it does matter. In this case, TinyPNG produced a virtually indistinguishable icon of only 524 bytes:
bancogalicia
Given that the twofactorauth.org list includes almost 1400 icons, this actually makes a difference in the long run.

**Comment by fainpablo** [comment]
@phallobst Makes sense. I've just uploaded the compressed file. Thanks again.

**Review by phallobst — APPROVED** [review]

**Comment by phallobst** [comment]
May I ask you to have a look at Issue #4230 as well? We are still looking for Spanish translations of the two tweets and the email subject that are in use, and you can certainly help us out there. I'm not sure whether there are significant differences for Argentinian Spanish (if that's a thing...), but it would certainly be better than nothing.

**Comment by fainpablo** [comment]
> May I ask you to have a look at Issue #4230 as well? We are still looking for Spanish translations of the two tweets that are in use, and you can certainly help us out there. I'm not sure whether there are significant differences for Argentinian Spanish (if that's a thing...), but it would certainly be better than nothing.

Absolutely. I've just submitted PR #4594. In spanish we use "two step" instead of "two factor", as you can see [here](https://www.google.com/landing/2step/?hl=es) and [here](https://www.facebook.com/help/148233965247823). While they can be considered different things, I believe it will be better to keep using "step" if we take into account the recipients of the tweets. If you prefer to use the word "factor", just let me know and I'll make the changes.

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
