### PR TITLE
Adding the PassBy[ME] provider to the list

### PR DESCRIPTION
**Pull request by paulikt**
I would like to add the PassBy[ME] provider to the list.

### CODE REVIEW

**Comment by mxxcon** [comment]
Your pull request now has merge conflicts. Please make sure your master is up to date with this repo's master.

**Comment by paulikt** [comment]
Damn. Sorry again. I think I am learning git the hard way :s
On the other hand "git pull origin master" says that I am already up to date. What am I doing wrong?

**Comment by paulikt** [comment]
OK, maybe now. (Sorry again for everything, this is the first time I am using git)

**Comment by paulikt** [comment]
This seems really odd. There are changes in this pull request that aren't mine :S
How the ... I am really confused about this..

**Comment by paulikt** [comment]
Ok I am giving up on this. I am going to reset my fork, and start over the whole process.

**Comment by mxxcon** [comment]
@paulikt instead of working in Master, after you resync your fork, create a branch in your repo and work from there.

**Pull request closed without merging**
