### PR TITLE
Add OTP banka

### PR DESCRIPTION
**Pull request by anotherus3r**

### CODE REVIEW

**Comment by kmpoppe** [comment]
@anotherus3r My Croatian is a little rusty (reads: non-existent), but despite the name "OTP token", which seems to be a PIN generator, it looks like OTP banka uses it for authorization rather than authentication. Maybe I'm reading that wrong, could you enlighten me?

**Comment by anotherus3r** [comment]
@kmpoppe It's used for both - to log in and to authorize transactions. When you want to log in, you have to enter a PIN into the token to get a one-time password with which you can log into the website.

**Comment by Carlgo11** [comment]
@anotherus3r I don't see anything mentioning software based 2fa 🤔

**Comment by anotherus3r** [comment]
@Carlgo11 The documentation for it is here: https://www.otpbanka.hr/hr/upute/otp-m-token-upute-za-koristenje

**Review by Carlgo11 — APPROVED** [review]

**Review by kmpoppe — APPROVED** [review]

**Pull request merged**
