### PR TITLE
Add SailPoint

### PR DESCRIPTION
**Pull request by adeline-chew-sp**

### CODE REVIEW

**Comment by adeline-chew-sp** [comment]
@Carlgo11 I've looked at the failed PRB and also reviewed passed ones, they look similar - Any idea why it can't find the image? Please assist :)

**Comment by Carlgo11** [comment]
Hello @adeline-chew-sp,
there was a problem with our code-verification code. (I know... it's ironical)
That has now been fixed and your PR is no longer failing 😄 

However, the image you used is rather large in byte size. I compressed it down to 900 bytes so please use this one instead:
sailpoint

**Comment by adeline-chew-sp** [comment]
Hi @Carlgo11 thank you for the update, I've updated to use the image you provided. :)

**Comment by Carlgo11** [comment]
Great! Since you haven't provided any link to a documentation page, could you please post a screenshot(s) of the 2FA setup process or login process to verify that they indeed support these 2FA options. (Remember to blur out or paint over any personal information)

**Comment by adeline-chew-sp** [comment]
Certainly! Here it is, the options are based on configuration by the Admins.
image

**Comment by RichJeanes** [comment]
@adeline-chew-sp You've indicated `hardware: Yes`, but I don't see a hardware option in the screenshot. For this project, `hardware` refers to a dedicated device (or object, à la paper) that is used to authenticate. One example of this would be a U2F security key or YubiKey. Is an option like that available or should the `hardware` entry be removed?

**Comment by adeline-chew-sp** [comment]
Hi @RichJeanes the option is based on the configuration set by Admins, SailPoint supports software or hardware integration for RSA, this doc is only available for authenticated user:
image

Here are other integration options:
image

It depends on the type of tokens a company is using, but hardware token is definitely supported. For example RSA and Symantec both support hardware tokens if that's what a company chooses to use.

**Comment by adeline-chew-sp** [comment]
Hi guys, was my explanation on hardware token acceptable? If not, I can work with you to get the site added. Please take a moment to review :)

**Comment by adeline-chew-sp** [comment]
@Carlgo11 @RichJeanes can you please review? Thank you for your time in advance :)

**Comment by mxxcon** [comment]
@adeline-chew-sp To get some clarification, are those authentication methods used to login into SailPoint account proper?
Or is it for another site were to use SailPoint as authentication provider?

**Comment by adeline-chew-sp** [comment]
Hi @mxxcon - it's both. It's used to either login to SailPoint or if another site were to use SailPoint as authentication provider. Depending on individual company's configuration.

**Review by mxxcon — APPROVED** [review]

**Comment by adeline-chew-sp** [comment]
@Carlgo11 @RichJeanes Can I please get a 2nd review from one of you? :)

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
