### PR TITLE
Add Planète OUI

### PR DESCRIPTION
**Pull request by nagromc**

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Looking at [alexa.com](https://www.alexa.com/siteinfo/planete-oui.fr) it seems like the site is rather insignificant.
Our limit is around 200k.

**Comment by nagromc** [comment]
> Carlgo11 **requested changes**

I'm not sure what you are expecting from me.

**Comment by mxxcon** [comment]
@nagromc What Carl means that this site is not high traffic enough to list. Since there are essentially infinite number of sites we try to apply some sort of filtering criteria. As such we generally list sites which are <200k on alexa.

**Comment by nagromc** [comment]
I do understand the fact the site is not popular enough to appear on twofactorauth.org

But, I don't understand what I am supposed to do with the **changes requested**.

**Pull request closed without merging**
