### PR TITLE
Add hosting WEDOS

### PR DESCRIPTION
**Pull request by Roman3349**
Signed-off-by: Roman3349 <ondracek.roman@centrum.cz>

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr @Roman3349

**Review by mxxcon — DISMISSED** [review]
@Roman3349 any chance you could find a less jaggy looking logo? 👍 You could resize this one https://porovnejhosting.cz/img/company/wedos/logo140.png

**Comment by Jawshy** [comment]
Here is an image that is ready to use, @Roman3349. It is not jaggy and uses the same blue as their [site's logo](https://hosting.wedos.com/images/layout/logo.png). 
wedos

**Comment by Roman3349** [comment]
@mxxcon Fixed.
@Jawshy Thanks.

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
