### PR TITLE
Replaced outdated icons

### LINKED ISSUE #4403: Update YNAB logo
The logo that's currently displayed is outdated. Attached is the current one :) 

YNAB Logo 32x32

### PR DESCRIPTION
**Pull request by phallobst**
Closes #4403

### CODE REVIEW

**Comment by kmpoppe** [comment]
@phallobst By merging the movement of sites from other to more fitting categories, directadmin and everlaw are now conflicted. I cannot resolve binary files on the web console, could you please move these new files to their respective new folders?
// Kai

**Comment by phallobst** [comment]
Merging master into this branch should do, I hope.

**Review by kmpoppe — CHANGES_REQUESTED** [review]
Dude, please, never let me check 144 files at once again 🤪😁
Please check 
* retail/amazon - is that picture scaled up? Looks strange!
* iot/solarweb - is that picture used for the solar.web product? Because solarweb.com shows the Fronius logo (white F on red background) as 16x16 favicon?

**Comment by phallobst** [comment]
144 - that's gross! :clown_face: (Thank you, I'll be here all week...)

The Amazon logo may have come from their favicon, but it was quite pixelated. Now it's better.

Regarding Solar.web: They don't seem to be able to make up their mind. I used the app logo as given by https://www.solarweb.com/#downloadsSection, but in the app stores it looks different. The only proper way to punish them is to revert to the company logo as it was used before, although I think it is not the best one to use.

**Review by kmpoppe — APPROVED** [review]

**Comment by kmpoppe** [comment]
I mailed solarweb as to what they'd like to happen re their logo (and if they plan on adding 2fa). Let's see what answers I get.

**Review by Jawshy — COMMENTED** [review]
For Boeing Employee Credit Union, I think the same icon as their [favicon](https://www.becu.org/images/favicon.ico) should be used. 

[DigitalOcean](https://www.digitalocean.com/) icon should be blue. 

Other than those two, the first 29 images look good to me.

**Comment by Jawshy** [comment]
Have you received a response, @kmpoppe?

**Comment by phallobst** [comment]
Digital Ocean is now blue, as requested.

For the BECU icon, I went for the one that is used on Facebook and Twitter (with the additional white edge), which looks slightly better.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Read the docs use the old logo - https://read-the-docs-guidelines.readthedocs-hosted.com/branding.html#logo-guidelines
The Fastmail logo seems a bit off. - https://www.fastmail.com/about/press/#?logo
ZOHO seems to still use the old logo - https://www.zoho.com/branding/
Loopia use the old logo as their favicon

**Comment by Carlgo11** [comment]
KdNIOZlWu8
At least I'm not using Chrome... RIP RAM

**Comment by phallobst** [comment]
I did these changes:
- Read the Docs: They don't even honour their own guidelines on their main web page (good job, folks), so I reverted that one.
- Fastmail: I erroneously used the icon for dark backgrounds which they included on their main page. Now it's the correct one.
- Zoho Mail: The "Z" cube is used for the _company_, but the _mail service_ has its own icon. However, I shrunk the one I used a tiny bit, so that it looks better inside the circle.
- Loopia: I don't know what they're thinking. They have a logo combining lettering and an icon, but still use the boring "L" as the favicon? They get a well(?)-reserved revert to the old icon.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Glesys - The new logo is just for a single service. Their twitter contains their current logo (https://twitter.com/glesysab)
AWS WorkSpaces - Not sure if this might be their new logo https://clients.amazonworkspaces.com/ (https://images-na.ssl-images-amazon.com/images/I/512NmkgumLL.png)
BT - They use the other logo as their favicon. Maybe revert it for now?
Cox - I suggest using this logo https://pbs.twimg.com/profile_images/1063064672818081793/bVIRvG3R_200x200.jpg

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
BU - https://pbs.twimg.com/profile_images/905086262746505217/TLzX_Dba_200x200.jpg
United domains, Let's just make one called united-domains.png and link both entries to it.

**Comment by phallobst** [comment]
> Glesys - The new logo is just for a single service. Their twitter contains their current logo (https://twitter.com/glesysab)
> AWS WorkSpaces - Not sure if this might be their new logo https://clients.amazonworkspaces.com/ (https://images-na.ssl-images-amazon.com/images/I/512NmkgumLL.png)

Ok, changed

> BT - They use the other logo as their favicon. Maybe revert it for now?

bt.com does not give me any favicon - the url https://www.bt.com/etc/designs/bt/portal-page-design/favicon.ico is a 404. I left my change in for now.

> Cox - I suggest using this logo https://pbs.twimg.com/profile_images/1063064672818081793/bVIRvG3R_200x200.jpg

That JPG is a bit grainy. Instead I took their favicon (128x128) and downscaled it.

> BU - https://pbs.twimg.com/profile_images/905086262746505217/TLzX_Dba_200x200.jpg

Same problem with the grainy JPG, but no better source. Oh well... Let's say it's "decent" now.

> United domains, Let's just make one called united-domains.png and link both entries to it.

Done!

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
