### PR TITLE
Add Cloudytics.com

### PR DESCRIPTION
**Pull request by NotAmaan**

### CODE REVIEW

**Comment by Carlgo11** [comment]
I don't think this site is popular enough to be listed here.
Furthermore it looks like they use cPanel and no own control panel.

**Comment by NotAmaan** [comment]
@Carlgo11 It is indeed not so popular, wasn't sure if that was an requirement but its fine. Also, I'm their designer & its control panel so its under works, but yeah, the current stage is a MVP.

**Comment by jamcat22** [comment]
@NotAmaan We usually only take into account popularity when adding a site that doesn't have 2FA, because if we didn't, we probably would need to list almost every website in existence. If the new control panel you're building will have 2FA, feel free to make another PR after it's released.

**Comment by NotAmaan** [comment]
@jamcat22 Will sure do. Thanks!

**Pull request closed without merging**
