### PR TITLE
Update Technic

### PR DESCRIPTION
**Pull request by 40504**
Useful link for account recovery if lose access to 2fa codes: https://www.technicpack.net/tfa/remove

### CODE REVIEW

**Comment by Carlgo11** [comment]
Would you like to add that recovery URI then?

**Comment by 40504** [comment]
> Would you like to add that recovery URI then?

like that:
"recovery": "https://www.technicpack.net/tfa/remove"
?

**Comment by Carlgo11** [comment]
@40504 Si :+1: 
I had to double check the [documentation](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#other-properties) to answer that and yet I'm the one who wrote the JSON schema :sweat_smile:

**Comment by 40504** [comment]
Done ✅

**Review by Carlgo11 — APPROVED** [review]

**Review by phallobst — APPROVED** [review]

**Pull request merged**
