### PR TITLE
Change planethoster domain TLD

### PR DESCRIPTION
**Pull request by NormandLemay**
Planethoster.net change is own primary domain to planethoster.com

### CODE REVIEW

**Review by mxxcon — DISMISSED** [review]

**Review by mxxcon — COMMENTED** [review]
@NormandLemay Should the urls be updated to point to English language versions or add `lang: fr`?

**Comment by NormandLemay** [comment]
I add the lang: fr

**Review by mxxcon — CHANGES_REQUESTED** [review]
Actually, I'm a dummy and don't remember our own syntax. 😅
`lang` is needed only if `tfa:no` so that template messages are in proper language. Since this site does support tfa, `lang` is not necessary.
I'm sorry for this confusion.

**Comment by NormandLemay** [comment]
It's correct push again without the lang

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
