### PR TITLE
Mint doesn't support software token for 2FA

### PR DESCRIPTION
**Pull request by vgarmash**
Read more at https://mint.lc.intuit.com/announcements/1286158

### CODE REVIEW

**Review by mxxcon — APPROVED** [review]

**Comment by jamcat22** [comment]
Mint does support software tokens in their implementation of Intuit account's 2FA. Please see #1517 for instructions on how to enable or manage various forms of Intuit 2FA, and see #1791 for more context.

This still applies to their current webapp version, as of 10/14/2016.
image

**Comment by mxxcon** [comment]
I do not have Authenticator App there...
clipboard01

**Comment by jamcat22** [comment]
@mxxcon You first have to add a phone and turn on two-step verification before you can add an authenticator app.

**Comment by vgarmash** [comment]
In the announcement about MFA they don't have any details about using 
software token for Mint.com. See here: 
https://mint.lc.intuit.com/announcements/1286158.

I searched over all the documentation for Mint and never saw anything 
about software token.

The link you provided is for intuit.com not for mint.com which has 
separate security settings. Just in case I decided to check the link 
that you gave and I don't see the software token there either (see 
attachment). When I logged in there is no software token either.

I use Mint.com myself and there is only SMS or email options for MFA.

Viacheslav

**Comment by mxxcon** [comment]
Nope, still no app. Only sms or voice

**Comment by jamcat22** [comment]
@vgarmash I'm unable to view the attachment. Could you upload it using the GitHub web interface?
@mxxcon Could you send a screenshot of your settings? This is what I see:
image
After disabling my software token, I see this screen:
image
Have you tried logging out and logging back into the Intuit account center after enabling SMS/Voice 2FA?

**Comment by mxxcon** [comment]
Ah, yes, I didn't notice authenticator app at the bottom. 👍

**Comment by vgarmash** [comment]
@jamcat22 Yes, you right. I just enabled the authenticator app in the Intuit security settings and Mint started asking for the 6 digit code! Do you have a link to the official documentation about it? Let' put it on the Mint line then.

**Comment by jamcat22** [comment]
While [Mint's documentation](https://mint.lc.intuit.com/announcements/1286158) is lacking on the software implementation instructions, Intuit's [Quickbooks documentation](https://community.intuit.com/articles/1164912-multi-factor-authentication-mfa-faq) does list this option, and the steps mostly apply to Mint. If we wanted, we could write a new doc specifically for Mint, since current docs are lacking.

**Comment by RichJeanes** [comment]
I think a custom page is a great idea, considering the circumstances. We could better explain the situation. We've done that for at least one other site, right?

**Pull request closed without merging**
