### PR TITLE
Add NASA Federal Credit Union

### PR DESCRIPTION
**Pull request by brycx**
Attempt at fixing: #2684

### CODE REVIEW

**Comment by mxxcon** [comment]
Where did you find info that it's email and sms?

**Comment by brycx** [comment]
On the site linked in the [docs](https://www.nasafcu.com/img/newebranch/ebranch_new.html), under "Advanced security features" it says "Options include mobile verification and more." That and the referenced issue. I know it's shaky but I thought since some sites don't have any doc links, I'd give it a try. I totally understand if it's not accepted.

**Comment by mxxcon** [comment]
Just making sure that we list complete and correct info. I googled for a bit but haven't found anything conclusive. 😞
I asked the original issue creator for some help on that info, hopefully they'll reply soon.

**Comment by brycx** [comment]
So I had a little chat with their support. It turns out they offer both SMS, phone and email as 2FA option. Unfortunately only required sometimes and not every time you log in.

Picture of chat

**Comment by Carlgo11** [comment]
I think we need some clarification on what "at random" means. If it's randomly presented at logins or just randomly when using their site. 🤔

**Comment by brycx** [comment]
@Carlgo11 I think by "No, it may not be required with each log in." it's meant that it's only presented at random during logins.

**Review by Carlgo11 — DISMISSED** [review]
Just contacted them and I can confirm that it's for authentication and not authorization. Also, seems to be cookie based.

**Review by Carlgo11 — APPROVED** [review]

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
