### PR TITLE
Add Figma

### PR DESCRIPTION
**Pull request by bfarooqi**
Add [Figma](https://www.figma.com/).

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr @bfarooqi

**Review by Carlgo11 — APPROVED** [review]
I have no idea how you compressed the image that good but still kept the lines so smooth. 👍

**Comment by jamcat22** [comment]
It looks as if SMS is only offered as a backup option...

@bfarooqi can you confirm that this is the case?

**Comment by bfarooqi** [comment]
@jamcat22 Figma supports both software and SMS tokens. This is our [help article](https://help.figma.com/#_two-factor-authentication) specifying both (you can also sign up for free to double check if you're interested).

**Comment by Carlgo11** [comment]
@bfarooqi

You're saying it's not a backup method?

**Pull request merged**
