### PR TITLE
Add GBAtemp

### PR DESCRIPTION
**Pull request by DandelionSprout**
It ranks [fairly high on Alexa](https://www.alexa.com/siteinfo/gbatemp.net), so that won't be a problem for this, at least.

I was however unsure if it this should be in Communication or Gaming, but I felt that the former fits it better.

As has become a recurring trend for my pull requests, I was once again unable to find public documentation of GBAtemp's 2FA support, but those out there who have GBAtemp accounts can go to https://gbatemp.net/account/two-step to verify that they support 2FA. 
image

### CODE REVIEW

**Comment by Carlgo11** [comment]
Is it just a forum or does it do anything? (#3387 :confused:)

**Comment by DandelionSprout** [comment]
It's most well-known for its forum, but also maintains a newsfeed, a wiki, and some other things. https://gbatemp.net/

Think of it as a version of XDA for Nintendo consoles. At least if you're familiar with XDA.

**Comment by jtagcat** [comment]
@DandelionSprout the real question is does it really need 2fa? What would 2fa protect?

**Comment by Carlgo11** [comment]
Closing this PR as the need for 2FA is doubtable and the site criteria questionable.

**Pull request closed without merging**
