### PR TITLE
Update finance.yml

### PR DESCRIPTION
**Pull request by NicolasFort**
Statetrust & BRD added

### CODE REVIEW

**Comment by jdavis** [comment]
Hey @NicolasFort. In order to add these, we'll need a 32x32 image =]

**Comment by NicolasFort** [comment]
32*32 uploaded !

**Comment by jdavis** [comment]
Cool. We'll merge this in after we finish #367 and #333.

**Comment by jdavis** [comment]
Hey @NicolasFort, we've updated it a bit. Take look at the README and once it matches the new style, this will be merged.

Thanks for the patience!

**Comment by juju4** [comment]
url for BRD is wrong (not hsbc)

**Comment by jdavis** [comment]
I'm closing this as it hasn't been updated for the new style. Feel free to open a new request that conforms to the new format.

**Pull request closed without merging**
