### PR TITLE
Add United Airlines

### PR DESCRIPTION
**Pull request by stephengroat**
While United "plans" to add tfa (https://www.united.com/web/en-US/content/help/PIN-password.aspx), they have not yet

### CODE REVIEW

**Comment by Carlgo11** [comment]
How about this one instead? It's 61% smaller.
united

**Comment by stephengroat** [comment]
perfect. what tool are you using? i was using the compress in gimp, but i
can use tinypng or something else if it gives a lot better results

**Comment by Carlgo11** [comment]
I use [tinypng](https://tinypng.com/).

**Comment by fpigerre** [comment]
Thanks for the pull request @stephengroat! :+1:

**Pull request merged**
