### PR TITLE
Added VPSServer.com

### PR DESCRIPTION
**Pull request by GuidoHendriks**
I added VPSServer.com to Hosting.

### CODE REVIEW

**Review by Jawshy — CHANGES_REQUESTED** [review]
Thanks for submitting a pull request, @GuidoHendriks. 

The image you uploaded is too big, both in dimensions and file size. Images need to be 32 by 32 pixels and under 2,500 bytes. Please use the image below. 
vpsserver

Does the site have any documentation for how it has implemented software two-factor authentication?

**Comment by GuidoHendriks** [comment]
Image requirements make sense, I changed the image to the one you posted. Thanks!

There's currently no documentation on the two-factor authentication.

**Comment by Jawshy** [comment]
Okay. Would you be able to attach screenshots that show the process of enabling 2FA on a VPS Server account?

**Comment by GuidoHendriks** [comment]
Of course, here you go:

screen shot 2017-01-18 at 10 19 29
screen shot 2017-01-18 at 10 20 29
screen shot 2017-01-18 at 10 21 13
screen shot 2017-01-18 at 10 21 39

Please let me know if you need any more info.

**Comment by Jawshy** [comment]
Thanks, @GuidoHendriks.

**Review by Jawshy — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
