### PR TITLE
Updated Capital One

### PR DESCRIPTION
**Pull request by JenTheMaker**

### CODE REVIEW

**Comment by stephengroat** [comment]
thanks for the pr @Juh-Jiang!

@2factorauth/collaborators capitalone and capitalone360 seems to have merged their brands more (https://capitalone360.com redirects to https://capitalone.com/bank). should we remove captialone360?

**Comment by JenTheMaker** [comment]
You're right. I'll go ahead and merge them! Otherwise is there anything else I need to post for the review process? @stephengroat

**Review by stephengroat — APPROVED** [review]

**Comment by JenTheMaker** [comment]
@stephengroat Can you merge these changes?

**Comment by stephengroat** [comment]
@Juh-Jiang we wait for 2 people to review

@2factorauth/collaborators can we get another review?

**Comment by JenTheMaker** [comment]
@mxxcon @stephengroat @jamcat22 @QuestionableChanges @boyanpeychev @Carlgo11 
I've tagged a couple of people who seem to be active, since I can't request reviewers. 
Could someone please review this so it can be merged?

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
