### PR TITLE
Adds filters for searching by TFA support

### PR DESCRIPTION
**Pull request by captn3m0**
Totally missed https://github.com/2factorauth/twofactorauth/pull/4584/files, but in case this looks like a better approach - filing this anyway.

My usecase was to filter by just one type of tfa (Hardware).

### CODE REVIEW

**Comment by phallobst** [comment]
These filters still use "software" and "hardware" as 2FA methods, but meanwhile these have been split into "u2f", "hardware", "totp" and "proprietary". (To be fair, the table headers are still "Hardware Token" and "Software Token"...)

Also, the only way I could make them work properly is to select the methods I wanted and then open a category. Flipping the checkboxes while the category is open does not have any effect for me.

Combining the checkboxes with a filter string yielded strange results as well.

(Tested with Opera, Chrome, Firefox, which all behaved the same.)

**Comment by captn3m0** [comment]
This is WIP for now. I noticed #4584 after I started working on this, and thought filing earlier would be better than finishing but not getting merged. If you think this is worth having, I'll clean it up and fix the edge cases (flipping after checkbox is open / searching etc).

On headers: I considered keeping them tech specific, but I think matching the table headers makes more sense.

I also planned for a "Show All" button next to the 5 checkboxes that opens all categories, but maybe that can be a separate PR.

**Comment by phallobst** [comment]
I see. GitHub allows you to create "Draft Pull Requests" for these cases; unfortunately, it is currently not possible to switch from a "normal" PR back to "draft". I will add "[DRAFT]" to the PR title now to reflect the current state. Once you are confident that your changes shall be reviewed for merging, you can just change it back.

You could also close this PR and open a new "draft" one if you want to.

**Comment by phallobst** [comment]
I took the liberty to convert this PR to a draft, since GitHub now allows this.

**Comment by captn3m0** [comment]
#4584 covers this much cleanly, and fulfills the usecase I had (find all sites across all categories with U2F supported)

Closing this.

**Pull request closed without merging**
