### PR TITLE
Adding Cloud Product Linode

### PR DESCRIPTION
**Pull request by kbohinski**

### CODE REVIEW

**Comment by Carlgo11** [comment]
@kbohinski you need to add a logo. Please follow the instructions on our [wiki](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_TFA_SITE)

**Comment by kbohinski** [comment]
@RichJeanes @Carlgo11 Fixed both requests

**Comment by RichJeanes** [comment]
You added a reference to an image but it appears you haven't added the image file itself.

**Comment by jamcat22** [comment]
You can also remove "sms: No" and "hardware: No"

**Comment by kbohinski** [comment]
Sorry! Its actually fully functional now!

**Pull request merged**
