### PR TITLE
Add bukkit

### PR DESCRIPTION
**Pull request by Carlgo11**

### CODE REVIEW

**Comment by mxxcon** [comment]
Does it make sense to list this site?

**Comment by Carlgo11** [comment]
Well as a developer for Minecraft plugins I'd really hate it if my account was being used by someone else on that site. They would be able to completely ruin your plugins.

**Comment by jdavis** [comment]
While I realize it is important to you, @Carlgo11, I don't think it is fit for the site and matching of the Criteria.

**Comment by Carlgo11** [comment]
okay @jdavis . closing PR

**Pull request closed without merging**
