### PR TITLE
Adding FitnessSyncer to the list of supported sites.

### PR DESCRIPTION
**Pull request by etheriau**
FitnessSyncer was just added support for 2FA, so adding it to the list.  Thanks!

### CODE REVIEW

**Comment by 40504** [comment]
Alexa rank for this site is # 420,356 -> https://www.alexa.com/siteinfo/fitnesssyncer.com

**Comment by 40504** [comment]
more about adding a new site here: https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md

**Comment by phallobst** [comment]
Please rebase your branch to the current master.

**Comment by Carlgo11** [comment]
Closing due to inactivity.

**Pull request closed without merging**
