### PR TITLE
Update Fidelity

### PR DESCRIPTION
**Pull request by Carlgo11**
As per #1320

### CODE REVIEW

**Comment by jamcat22** [comment]
Could you also change the doc file in the notes folder?
- Change the phone numbers (there are two in the doc) to 800-544-6666.
- Remove the "Note" at the bottom of "How to Setup 2FA for Fidelity"

**Comment by Carlgo11** [comment]
Oh, "at the bottom". I read that as Remove the note about "How to Setup 2FA for Fidelity"

**Comment by jamcat22** [comment]
That's better!

**Comment by Carlgo11** [comment]
Yeah, sorry about the mess. I just woke up :sleeping:

**Comment by jamcat22** [comment]
It's all good! :smile:

**Pull request merged**
