### PR TITLE
Add Valic to Finance

### PR DESCRIPTION
**Pull request by dsoegijono**
For #698. Don't see any info about them having TFA either.

Also optimized protonmail.png

### CODE REVIEW

**Comment by Carlgo11** [comment]
How is protonmail.png optimized? What changes did you do?

**Comment by mxxcon** [comment]
@Carlgo11 probably recompressed it or lowered color depth w/o losing noticeable details.?

**Comment by dsoegijono** [comment]
@Carlgo11 @mxxcon Yup, it's lossless compression. Optimized might be the wrong word?

**Comment by Carlgo11** [comment]
well, it looks good. :+1:

**Pull request merged**
