### PR TITLE
EVE Online 2FA in progress

### PR DESCRIPTION
**Pull request by okand**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Do you see what you did wrong?

You have to be careful when editing yaml files

**Comment by okand** [comment]
Weird, none of that indentation stuff shows up in notepad++
Hopefully it is correct now.

**Comment by mxxcon** [comment]
@okand Make sure you use only space and not tabs..

**Comment by Carlgo11** [comment]
This yaml tutorial is quite good: http://ess.khhq.net/wiki/YAML_Tutorial

**Pull request merged**
