### PR TITLE
Add InterNetworX to Domains

### PR DESCRIPTION
**Pull request by fhemberger**
They offer 2FA via Google Authenticator

### CODE REVIEW

**Comment by mxxcon** [comment]
You messed up dynadot's entry..

**Comment by fhemberger** [comment]
Woah, sorry for that! Fixed.

**Comment by Carlgo11** [comment]
You don't need that exception. Please remove it

**Comment by fhemberger** [comment]
Aye, done.

**Comment by Carlgo11** [comment]
Okay looks good.

Thank you for your contribution @fhemberger! It's much appreciated!
We're currently having some issues with Travis CI that verifies PRs for us. When that's fixed we'll probably merge your PR.  

When your PR is merged it will take a few days before it shows up on twofactorauth.org.

**Comment by fhemberger** [comment]
Great, thanks.

**Comment by fhemberger** [comment]
See #969

**Pull request closed without merging**
