### PR TITLE
Added SAASPASS Identity modules 

### PR DESCRIPTION
**Pull request by wakwanza**
Changes for updated API including Identity specific modules for 2fa and sms

### CODE REVIEW

**Comment by mxxcon** [comment]
it looks like saaspass is a 2fa provider, not a service that utilizes 2fa itself...

**Comment by jamcat22** [comment]
You can store passwords and authentication tokens in the app, and sync them between devices.
It looks a bit like a cross between Authy and LastPass.

**Comment by mxxcon** [comment]
that's cool, but does saaspass have 2fa to login into itself? We are no longer listing _providers_...

**Comment by jamcat22** [comment]
It does. Since their primary business is providing a solution for tokens and corporate login, it might be a provider.

Any input @wakwanza?

**Comment by zombieastronaut** [comment]
SAASPASS is an identity manager and a secure single sign-on provider that always uses two-factor authentication everywhere.  That's the core difference between other identity managers where some selectively use it.

**Comment by wakwanza** [comment]
@mxxcon  yeah, SAASPASS does provide 2fa to log into itself as well as other user linked accounts .In this instance it does self authenticate as it were.

**Comment by mxxcon** [comment]
is there a docs links how to enable it?

**Comment by jamcat22** [comment]
@mxxcon It's always enabled.

**Comment by jamcat22** [comment]
@wakwanza Can you remove the doc link (unless there's a better one), and use this smaller image?
icon

**Comment by Carlgo11** [comment]
@wakwanza Are you going to fix the things @jamcat22 requested?

**Comment by jamcat22** [comment]
@wakwanza If you don't respond in a week, I'll close this PR and add it to the `backlog`.

**Comment by wakwanza** [comment]
Updated the docs and image sizes as suggested by @jamcat22.Can reviewe the doc link and resubmit the PR if needed.

**Comment by Carlgo11** [comment]
The thing is tho, your changes weren't added to your master branch

**Comment by Carlgo11** [comment]
@jamcat22 can you confirm that this PR is good to merge?

_(As there's quite a few merge commits I don't know if it would be better to cherry-pick rather than merge the PR)_

**Comment by jamcat22** [comment]
@wakwanza could you please remove the doc link? The current link explains how SAASPASS works as a 2FA token app, not how the login process (which is what we track) works. Unless there's a link that explains how the login process to the SAASPASS app works, you can just completely remove it.

**Comment by wakwanza** [comment]
ok removed the current doc link .

**Comment by jamcat22** [comment]
Does SAASPASS support a software method for logging into the app?

**Comment by wakwanza** [comment]
Yes it does. It supports both sms based and software based two-factor authentication with randomly generated numbers. The SMS based two factor authentication is available when admins purchase it for their companies. The software based 2FA is available on both the iOS, Google Play, Blackberry and Amazon app stores.

**Pull request merged**
