### PR TITLE
Added Aha!, aTech Media, Cloud 66, and MongoHQ

### PR DESCRIPTION
**Pull request by jamcat22**
See #448

### CODE REVIEW

**Comment by mxxcon** [comment]
I'm not picking on you, but those logos are a bit blurry. :)

**Comment by jdavis** [comment]
We're putting you through Open Source + Git Bootcamp, @jamcat22, haha.

**Comment by jamcat22** [comment]
@jdavis Well, so far bootcamp seems to be teaching me a lot of things I should have already known! Thanks! (Sorry for being a n00b. Thanks for putting up with me.)

**Comment by jamcat22** [comment]
@mxxcon Apparently, I am not good at editing image files :frowning:. How do you make them look so good?

**Comment by mxxcon** [comment]
@jamcat22 I try to find native 32x32 logos, otherwise Google for decently sized logo(too large might give worse results), preferably with transparency layer. I use http://www.getpaint.net/ to crop the logo, then resize it down to 32pixels preserving aspect ratio. If the logo is not square, I increase it's canvas size to be exactly 32x32 and then make sure added canvas is also transparent, not just white. Then I use Irfanview RIOT plugin to compress image to the smallest png possible.

It's all very basic steps...takes ~5min, if not less, per image.

**Comment by jamcat22** [comment]
Are those logos better? I couldn't get the Aha! logo to work though. :frowning:

**Comment by mxxcon** [comment]
Looks good :blush:, however this pull request is pretty old now, out of sync with the site's current structure and can not be easily merged.
You'll have to resync your repo and adjust entry's locations accordingly. Alternatively, you can cancel this pull request, resync your repo and submit new pull request(preferably each site separate request.)

**Comment by jamcat22** [comment]
@mxxcon Ok. I'll close this pull request and submit another.

**Pull request closed without merging**
