### PR TITLE
Update AOL

### PR DESCRIPTION
**Pull request by mbeckerhh**
Updated AOL Mail

### CODE REVIEW

**Comment by mxxcon** [comment]
@mbeckerhh this is not your fault. There's nothing wrong with your commit.
@jamcat22 messed it up and everything should be fixed once #1460 is merged.

**Comment by jamcat22** [comment]
@mxxcon Wow way to blame everything on me. :stuck_out_tongue:
Just fell asleep while changing the file.
Sorry about that. :disappointed:

**Comment by Carlgo11** [comment]
*hugs @jamcat22 *

**Comment by jamcat22** [comment]
I love how AOL was one of the first to have 2FA, then they removed it, and now they're one of the last to support it again.

**Comment by Carlgo11** [comment]
@mbeckerhh Could you add an exception note that "2FA currently only works for U.S. customers"?

**Comment by mxxcon** [comment]
@jamcat22 i didn't blame you. it's all in the git logs. :wink: I just pointed it out.

**Comment by Carlgo11** [comment]
inb4 @jamcat22 does a push --force to hide the evidence.

**Comment by mbeckerhh** [comment]
@Carlgo11 done. 
@jamcat22 well, the circle of life ;-)

**Comment by jamcat22** [comment]
Thanks for the PR @mbeckerhh! You even added it before any news networks picked it up! (Not that many are probably monitoring AOL as a company...)

**Pull request merged**
