### PR TITLE
Updated site icons

### PR DESCRIPTION
**Pull request by RichJeanes**
Updated any images larger than 24x24 to that size since that is what is displayed on the site anyway. Any images not in png were converted to match as well.

If you find this superfluous, feel free to close the PR without merging. Just a bit of me indulging in my OCD. Even made sure to keep the changes branched from my fork master.

### CODE REVIEW

**Comment by computmaxer** [comment]
I agree that we should increase the standard icon size (see #84) but I think we should pick a size and stick with it instead of having a bunch of random sized icons.  Something like 32x32 should be fine.

**Comment by jdavis** [comment]
I'm going to leave this open until we decide on what image size to go to. If we go to 32x32, this might make this commit obsolete but when it is decided, I'll revisit this and if you redid it for 32x32, that'd be awesome.

**Comment by mpdavis** [comment]
I would agree on 32x32

**Comment by jdavis** [comment]
32x32 it is! @RichJeanes If you could update them, that'd be great. However, if you can't, no worries. I'll merge it in for right now for temporary improvement.

**Pull request merged**
