### PR TITLE
Token2

### PR DESCRIPTION
**Pull request by token2**

### CODE REVIEW

**Comment by token2** [comment]
@mxxcon , finally sorted it out :)

**Comment by dsoegijono** [comment]
`url` and `img` are incorrect.

**Comment by dsoegijono** [comment]
Should be token2.png instead of token.png

**Comment by mxxcon** [comment]
yay! :smiley: 
lgtm :+1:

**Comment by mxxcon** [comment]
Actually, wait a sec.
Does Token2 provide physical hardware dongles/keyfobs or only smartphone/desktop apps?

**Comment by token2** [comment]
Yes, hardware tokens as well- https://token2.com/?content=hwtokens

**Comment by mxxcon** [comment]
Yup, it was a bit hidden :)

**Comment by Carlgo11** [comment]
Looks good to me. Merge time?

**Comment by Carlgo11** [comment]
Congrats @token2. You finally did it ;)

**Pull request merged**
