### PR TITLE
Add PostNL

### PR DESCRIPTION
**Pull request by AlexLamond**
PostNL is the postal service company for The Netherlands, they do not at this time support 2FA

### CODE REVIEW

**Comment by phallobst** [comment]
The SVG logo is basically an embedded PNG. How about this one instead?
postnl nl

**Comment by AlexLamond** [comment]
@phallobst Where do you find/convert the SVG's for reference for further contributions I make?

(@Carlgo11 Sorry for the misstag!)

**Comment by Carlgo11** [comment]
@AlexLamond I have no idea where Phallobst found the PostNL icon but I usually find SVG logos by googling `<company name> icon filetype:svg` and clicking on the images tab. I then run the image through [SVGOMG](https://jakearchibald.github.io/svgomg/), enable all the features except "Remove xmlns", adjust the precision slider to an appropriate level and enable "Multipass".

**Review by Carlgo11 — APPROVED** [review]

**Comment by phallobst** [comment]
On the bottom of the main page there is a grey SVG icon - I just changed the color to "their" orange tone.

**Review by phallobst — APPROVED** [review]

**Pull request merged**
