### PR TITLE
Add UpCloud

### PR DESCRIPTION
**Pull request by szepeviktor**
The winner of my benchmark series: https://github.com/szepeviktor/wordpress-speedtest

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please squash my commits.

**Review by mxxcon — APPROVED** [review]

**Comment by mxxcon** [comment]
@szepeviktor yes, we normally squash all commits when merging PRs into master.

**Comment by szepeviktor** [comment]
Thanks.
Please add the [new site] tag.

**Review by Jawshy — COMMENTED** [review]
Should an exception be added that states that a phone number is required for use as a backup? 

[Two-Factor Authentication on UpCloud](https://www.upcloud.com/support/two-factor-authentication/): 
> [...] As a backup, you can have the authentication code delivered to you via an SMS or a phone call to the phone number registered to your account.

**Comment by szepeviktor** [comment]
@Jawshy All my clients are on UpCloud, and I use 2fa.

What other companies provide as a way of backup?

**Comment by Jawshy** [comment]
Tilaa - [Hardware and software tokens can be used for 2FA and an SMS-capable phone as a fallback mechanism.](http://blog.tilaa.com/post/128110588046/two-factor-authentication-and-session-management)

**Comment by szepeviktor** [comment]
Oh! UpCloud provided me a bunch of *backup* tokens in case I loose my OTP key.

**Comment by szepeviktor** [comment]
Is it OK now?

**Review by stephengroat — APPROVED** [review]

**Comment by szepeviktor** [comment]
@jgabor Look!

**Pull request merged**
