### PR TITLE
Add Union Bank (Israel)

### PR DESCRIPTION
**Pull request by danielrosehill**
Added Bank Igud (Israel) to banking page.

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Clean up your YAML 😬
And run it through http://www.yamllint.com to make sure it's valid text

**Review by danielrosehill — COMMENTED** [review]
Hi updated in upstream branch

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
you currently have 2 images added. Both of which are too large.
Use something like https://tinypng.com to compress the image you want to use.

**Comment by danielrosehill** [comment]
@Carlgo11 

Sorry to waste your time. I'm a Github rookie and I guess getting this right is beyond me. 

I reduced the image in the last commit to 32 x 32px so am not sure how it could still be too large / require compressing. 

It's a great project and although I'd love to contribute a few listing, I guess I don't have the skills :-(

**Pull request closed without merging**
