### PR TITLE
Add No Starch Press

### PR DESCRIPTION
**Pull request by clove3am**
Added: No Starch Press (NOTE: No documentation available for 2FA. Enable 2FA in Security Tab under account settings)

### CODE REVIEW

**Review by mxxcon — CHANGES_REQUESTED** [review]
logo must be 32x32

**Review by mxxcon — APPROVED** [review]

**Review by brycx — CHANGES_REQUESTED** [review]
Thanks for the PR @caltlgin. You haven't included any doc link. Please take a screenshot of the page that explains how to enable it, with any personal information blurred out.

**Comment by clove3am** [comment]
- **Uploaded:** Instructions on how to enable 2FA on No Starch Press.

2fa_no_starch_press

**Review by Carlgo11 — APPROVED** [review]

**Comment by brycx** [comment]
Thanks so much @caltlgin!

**Review by brycx — APPROVED** [review]

**Pull request merged**
