### PR TITLE
Add BBC

### PR DESCRIPTION
**Pull request by rmtsrc**

### CODE REVIEW

**Comment by Carlgo11** [comment]
What [site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) does bbc.co.uk meet?

**Comment by rmtsrc** [comment]
@Carlgo11 the BBC stores personal information, data, deals with money and is [ranked 93 on Alexa's top websites list](https://www.alexa.com/siteinfo/bbc.com).

This includes:
* Name
* Email
* Gender
* Year of birth
* Postcode
* Favourite iPlayer programs
* Ability to buy items from the BBC shop

**Comment by dsoegijono** [comment]
> What [site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) does bbc.co.uk meet?

Maybe we should provide more details for points 1 & 2 because "personal info" and "sensitive data" is very broad and subjective

**Comment by dsoegijono** [comment]
> * Ability to buy items from the BBC shop

@sebflipper Does it save payment information (e.g. credit card)?

**Comment by rmtsrc** [comment]
@dsoegijono True, it's arguable exactly "how sensitive" this data can be, but yet even something benign like Facebook/Instagram/Twitter likes can [reveal a lot about a person](https://bigthink.com/philip-perry/a-single-like-on-facebook-can-reveal-a-crucial-aspect-of-your-personality).

Also the BBC shop does have an option to save your credit card details for future payments:

screenshot 2019-02-25 at 11 11 40

**Review by jtagcat — APPROVED** [review]
Need for 2FA debatable.

**Comment by Carlgo11** [comment]
I don't think this is a site that needs to be added to twofactorauth.org. At least not at the moment.
Sorry :(

**Pull request closed without merging**
