### PR TITLE
Adds Santander UK to Finance

### PR DESCRIPTION
**Pull request by meatballs**

### CODE REVIEW

**Comment by meatballs** [comment]
Same comment as #305. I don't think the international label applies here any more than it does to an American bank.

**Comment by jdavis** [comment]
Good point, @meatballs. I pulled in the #305 change but this one has a merge conflict because we updated the format. If you update it, we'd love to pull it in.

**Comment by Carlgo11** [comment]
Hi @meatballs,
I'd need you to fix a few things in this PR or else we'll close it due to inactivity.
- Change doc link to: http://www.santander.co.uk/uk/help-support/security-centre
- Remove twitter handle as we don't need that on sites already supporting TFA.
- Update your branch with our master branch.

Please reply back if you're going to update the PR so that I don't close it by mistake :wink:

**Comment by Carlgo11** [comment]
@jamcat22 I see you assigned yourself to this PR. Does that mean you'll make a separate up-to-date-PR with Santander UK?

If so, can I close this PR?

**Comment by jamcat22** [comment]
@Carlgo11 Yep. Yep.

**Comment by Carlgo11** [comment]
Great! :smiley:

**Pull request closed without merging**
