### PR TITLE
Add LOYAL3, Bodybuilding.com, and Virgin Mobile

### PR DESCRIPTION
**Pull request by sif**

### CODE REVIEW

**Comment by jamcat22** [comment]
Currently, you have the image name as "loyal3.jpg" when it is really "loyal3.png" in your .yml. Please change this.

**Comment by sif** [comment]
It says loyal3.png on my end, let's see what went wrong here..

**Comment by mxxcon** [comment]
@ryra but your yml block says .jpg. https://github.com/jdavis/twofactorauth/pull/808/files#diff-97f3b3d0ce43462c24270f75398f77e3R35

**Comment by jamcat22** [comment]
What he said. ^

**Comment by sif** [comment]
Alright, hope that works. Thanks!

**Comment by jamcat22** [comment]
Yay! Thanks @ryra!

**Comment by Carlgo11** [comment]
Not sure about Virgin Mobile. We're currently discussing if carriers should be added in #761. I suggest we don't add any carriers until that pr is added (if that pr will be added).  

Bodybuilding.com? Not sure if this site should be added. It does fit site criteria 3 but like @jdavis have said before about other sites. We can't add all the sites on the internet. Maybe this one is too small/narrow to really fit in our list?

Also, it's often better to add just one site per PR.

**Comment by jamcat22** [comment]
Agree with @Carlgo11.

Please keep pull requests to one site. If you still want to add the other websites besides LOYAL3, please remove those sites from this pull request/branch and recreate them as separate PRs.=

**Comment by sif** [comment]
Okay, I'll update it as soon as I get some clarifications. I have a few thoughts / questions.

1.)  The only reason I included Bodybuilding.com is because it is one of the biggest health-related site on the internet, if not the biggest. It is a forum, a store and many others all combined into one. The site seems to fit all of the criterions. This plus the fact that a lot of people have issues that are very personal (for example, eating disorder) that they definitely don't want this kind of stuff hacked. I know someone with this issue and hospitalization was the result of the eating disorder. So this kind of stuff is no joke.

2.) On the same token as 1.), so I am to assume MyFitnessPal isn't something we want on here too?

3.) What about Project Euler? 

After I get some response, I'll change how I think about these websites.

**Comment by Walkman100** [comment]
I have a ProjectEuler account, and while I can say you wouldn't want anyone hacking your account, there isn't any personal data on it - just your progress/scores e.t.c., which unless you have a top score there isn't really a motive for someone hacking your account (not that having TFA on PE would be bad).

**Comment by mxxcon** [comment]
@ryra what about Project Euler? I don't quiet understand you.
Regarding bodybuilding.com and personal issues posted there, why would somebody need to hack into your account if they could simply create their own and see your posts there?
for myfitnesspal.com, what kind of sensitive info does it have? seems like it's weight, exercise and diet tracking portal?

**Comment by sif** [comment]
Hm, never mind about PE and MFP then, I saw other responses elsewhere. Bodybuilding.com has a private section that for whatever reason, can only be seen by you. Order history, private posts / data, etc.

**Comment by Carlgo11** [comment]
Hello? Anyone here? :ghost:

So regarding loyal3 the text pretty much looks good. (Except that I'd like a `tfa: No` instead of `tfa: no`)
The logos on the other hand are waaaay over the recommended size and I suggest you compress them using something like [TinyPNG](https://tinypng.com/).
Also, please update your branch with our master branch.

I suggest you put the other sites in separate PRs and we'll discuss them there instead.

**Comment by Carlgo11** [comment]
Oh and if you don't reply within ~ a week I'll close the PR as I'm trying to clean up the list of old PRs.

Thanks!
//Carl

**Comment by jamcat22** [comment]
If this PR isn't updated in a few days, I'll make a new one to make sure the site is added. Thanks!

**Comment by jamcat22** [comment]
Closing and adding to backlog of sites.

**Comment by jamcat22** [comment]
Removing from backlog, as Loyal3 and Virgin Mobile have been added, and Bodybuilding.com was determined to possibly not fit this site's criteria. If desired, a new PR can be created to discuss adding Bodybuilding.com, however this PR is no longer considered to contain content requiring a backlogged status.

Additionally, this PR contains duplicate content associated with #507, and Virgin Mobile was added in #1654.

**Pull request closed without merging**
