### PR TITLE
Add to Finance: french and canadian actors

### PR DESCRIPTION
**Pull request by juju4**
I hope this is the right format this time.

FR: BNP Paribas, Société Générale
CA: Desjardins, National Bank Canada, Scotiabank, TD Canada Trust

add images, somes icon files (favicon.ico, not sure if good)

### CODE REVIEW

**Comment by mxxcon** [comment]
all logos must be 32x32 exactly, otherwise they will look wrong on the page..

**Comment by juju4** [comment]
fixed here and other branch.
what about icon files?

**Comment by mxxcon** [comment]
Those images are not 32x32, they are 32x28...
And icon files are 16x16...gotta be 32x32
Same problem in your other pull requests..

**Comment by juju4** [comment]
it depends on company logo. do you want me just to fill the blank? what about transparency of png files, keep it or just blank?
but is the ico format good for you outside of size?

**Comment by mxxcon** [comment]
Yes, keep transparency/alpha channel. If the logo is rectangular, try to pad it or maybe find a recognizable variation of that logo that is square.
You can achieve better image compression size using png instead of ico...

**Comment by juju4** [comment]
any blocking points here?

**Comment by jdavis** [comment]
Yes. SCHOOL.

**Comment by dsoegijono** [comment]
@juju4 Take a look at [CONTRIBUTING.md](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md). See what info we need for these entries.

**Pull request closed without merging**
