### PR TITLE
Adding Trillian IM, does not have TFA

### PR DESCRIPTION
**Pull request by smarkwell**

### CODE REVIEW

**Comment by jdavis** [comment]
Hey @smarkwell. Could you upgrade this to a 32x32 icon? If so, that'd be perfect.

**Comment by computmaxer** [comment]
Does Trillian have their own service? AFAIK it is just a chat client to connect to other services like Google Chat/XMPP, IRC, etc. I'm not sure there is anything Trillian could do about those other services not supporting two-factor.

**Comment by smarkwell** [comment]
Are we upscaling in any particular way?  16x16 was the source of their favicon.

**Comment by mpdavis** [comment]
I would also argue that Trillian IM doesn't belong in the list.  They have no authority over 2FA for the people that use their software.

**Comment by jdavis** [comment]
@mpdavis and @computmaxer, keepin' my trigger happy pull requesting normalized.

I agree with them after looking into it. It doesn't look like it has its own service.

**Comment by smarkwell** [comment]
Oddly enough Trillian has both, they have both their own network and provide proxy interconnect to other chat services (AIM/ICQ/XMPP/etc).  They run their own services and store your credentials in their servers for chat services.  I'm ok not including them either way.

**Comment by jdavis** [comment]
K, let's not include them for now. If we find a compelling reason to, we can reconsider it.

**Pull request closed without merging**
