### PR TITLE
Update Airbnb

### PR DESCRIPTION
**Pull request by phallobst**

### CODE REVIEW

**Comment by kmpoppe** [comment]
The 2FA implementation is meh. I didn't manage to get asked for a second code. Strange.

**Comment by kmpoppe** [comment]
@phallobst Please rebase the change to current master, because of AirBnb now moved to hotels.yml.
Thanks
// Kai

**Comment by kmpoppe** [comment]
It feels like that didn't go as planned, because we've got a ton of commits in this PR now?

**Comment by phallobst** [comment]
Aren't these the commits that were merged into my branch? According to the [branch comparison](https://github.com/2factorauth/twofactorauth/compare/master...phallobst:airbnb), there is only the update for the Airbnb entry left.

If that still is not correct, I could easily re-branch and submit a new PR.

**Pull request closed without merging**
