### PR TITLE
Add Zalando

### PR DESCRIPTION
**Pull request by Nicos18**

### CODE REVIEW

**Review by Carlgo11 — DISMISSED** [review]
:+1:

**Comment by mxxcon** [comment]
Do all these Zalando sites have separate login systems or are they all connected?
If they are all connected then I think it's better to use a single global entry such as https://zalando.com/

**Comment by Nicos18** [comment]
I am registered on the Italian site, and I tried to login the UK site. The login system is the same, but except this, on the UK site, for example, I didn't find my Italian address and some other data that exists on the IT site.

**Comment by mxxcon** [comment]
So if the login system is shared, I think it's better to have a single entry rather than duplicating all that info.
Their `zalando` twitter and facebook accounts are in German..
@2factorauth/core feedback?

**Review by jamcat22 — DISMISSED** [review]
I agree with @mxxcon here. It's similar to an Amazon.com situation.

**Comment by Carlgo11** [comment]
@jamcat22 @mxxcon I merged it into one listing and made the url zalando.com. That url redirects the user to their own country's version of Zalando.
I also changed the Twitter handle to Their Technology dep. They're not very active there but have responded to a couple of user tweets. Hopefully by sending directly to them, it's easier for the change to be made.

**Review by brycx — APPROVED** [review]
This looks like the best solution to me. Even though the Facebook account and email address is on .co.uk domain, the facebook.com/zalando is also in german. I'd say keep it like this.

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
