### PR TITLE
New bank

### PR DESCRIPTION
**Pull request by rosshashbarger**
Add Huntington with the changes that needed to be made.

### CODE REVIEW

**Comment by smholloway** [comment]
`worksforme` :+1:

**Comment by mxxcon** [comment]
Actually it looks like it might support 2fa.. see https://www.huntington.com/Personal/online-services/mobile-banking/mobile-banking-overview/mobile-banking-faq

> What if I request a registration code be texted and do not receive it?
> 
> Answer: First, please ensure that the phone number you selected can receive text messages. Second, check the list of our participating carriers below to see if your mobile carrier is supported. Lastly, it may be because you or your carrier has blocked messages from short codes. Huntington sends these registration text messages from our short code 446622. Please call your mobile carrier and ask about short code messaging.

**Comment by jamcat22** [comment]
@mxxcon It looks like that's only for registering the mobile app, not logging in to their online banking website.

**Comment by Carlgo11** [comment]
Uhm space in the image name?

**Comment by mxxcon** [comment]
@Carlgo11 revert?

**Comment by Carlgo11** [comment]
Yes. Or change the name.
I'm currently not near a computer so I can't make a new PR.

**Pull request merged**
