### PR TITLE
Added Visual Studio Online to the 2FA Developer section

### PR DESCRIPTION
**Pull request by edblankenship**
Hope this helps!

### CODE REVIEW

**Comment by jamcat22** [comment]
Looks good! You can remove the twitter line if you would like though.

**Comment by edblankenship** [comment]
Awesome! - just removed the twitter line.

**Comment by Carlgo11** [comment]
@EdBlankenship does visualstudio provide anything else than Microsoft Account login? If not then you can remove `(w/Microsoft Account)`

**Comment by edblankenship** [comment]
> @EdBlankenship does visualstudio provide anything else than Microsoft Account login? If not then you can remove ('w/Microsoft Account')
> -- @Carlgo11

It does... You have two options as an account owner:
- You can use a Microsoft Account-based approach by default.  
- You can alternately [setup your Visual Studio Online account to be connected to an Azure Active Directory tenant](http://www.visualstudio.com/get-started/manage-organization-access-for-your-account-vs) which includes a combination of Microsoft Accounts, Active Directory accounts synchronized from on-premises, and cloud-only Azure Active Directory User Accounts.

There is also more information available on [enabling multi-factor authentication for an Azure Active Directory tenant](http://technet.microsoft.com/en-us/library/dn249466.aspx).

**Comment by mxxcon** [comment]
So then regardless which method you use, TFA is available either way?

**Comment by edblankenship** [comment]
> So then regardless which method you use, TFA is available either way?
> -- @mxxcon

That's correct.  The difference is in the details. The documentation link would be different for each option and the Azure Active Directory approach supports authentication by phone whereas the Microsoft Account approach does not.  Is the suggestion to have two different entries in the list?

**Comment by edblankenship** [comment]
Anything else you would like me to do for this PR to make it look good?

**Comment by Carlgo11** [comment]
Okay well if TFA is supported either way then why not just using the doc for using a Visual Studio Online account instead of Microsoft Account?
Also remove `(w/Microsoft Account)` if now again it is supported either way. 

Then change the `url:` to http://www.visualstudio.com/. We like to link directly to the main page of the service supporting TFA.

And thank you for contributing Ed! Great to see that Microsoft reaches out to the internet communities.

**Comment by jdavis** [comment]
:+1: to @Carlgo11's comments.

**Comment by edblankenship** [comment]
Always happy to help!  Made some changes that are getting pushed as I add this comment.  I also wrote a quick blog post about the topic in case anyone is interested in more details:  [Securing Your Visual Studio Online Account with Multi-Factor Authentication](http://www.edsquared.com/2015/01/17/Securing+Your+Visual+Studio+Online+Account+With+MultiFactor+Authentication.aspx)

**Pull request merged**
