### PR TITLE
Add email and Facebook options for contacting.

### PR DESCRIPTION
**Pull request by Carlgo11**
Hello,

I've thought about adding an email and Facebook option for some time now and yesterday I started working on it for real.

@psgs helped me a bit with the mobile layout version and yml tag names etc.

### CODE REVIEW

**Comment by mxxcon** [comment]
Why are we adding this?

**Comment by jamcat22** [comment]
@mxxcon It's an implementation of #1212.

**Comment by RichJeanes** [comment]
We will need to be careful with these to make sure that Facebook pages are actually official business pages and not just fan pages and such. Facebook is such a silly place.

**Comment by Carlgo11** [comment]
Why is this still labeled as pending?

**Comment by fpigerre** [comment]
@Carlgo11, I added the pending tag whilst the changes originally described in the pull request were overwritten by `verify.rb` changes. At present, this pull request is still missing the CSS changes, which I have yet to add. If this pull request is merged in its current state, the Facebook and Email buttons will probably appear quite bizarre, particularly when viewed from a mobile device.

**Comment by RichJeanes** [comment]
@psgs @Carlgo11 Now with #1845 merged, can the two of you give this a once over to verify.rb (:wink:)  that everything still looks good?

**Comment by Carlgo11** [comment]
@RichJeanes Don't look at me. @psgs said he wanted to do some CSS changes.
From my perspective this PR is good to go. 😜

**Pull request merged**
