### PR TITLE
add privacyidea

### PR DESCRIPTION
**Pull request by cornelinux**
privacyIDEA is an open source system to manage all kinds of tokens. 
You can run it on premise in your own data center/network.

### CODE REVIEW

**Comment by Carlgo11** [comment]
@cornelinux look at our [wiki](https://github.com/jdavis/twofactorauth/wiki/I-want-to-add-a-TFA-provider-to-the-list) on what's needed in the .yml file for providers as you seem to have copied the requirements for a site rather than provider.

**Comment by cornelinux** [comment]
seems i need to remove the tags "tfa" and "twitter".
OK will do so.

**Comment by Carlgo11** [comment]
Yes and doc as well I think

**Comment by cornelinux** [comment]
other providers also contain the tag "doc".
If it is not used, it can be removed...

**Comment by Carlgo11** [comment]
Ah yes they do. May bad.

**Pull request merged**
