### PR TITLE
Add Mojang

### PR DESCRIPTION
**Pull request by ghost**
Added Mojang (Minecraft, Scrolls, and Cobalt.)

### CODE REVIEW

**Comment by mxxcon** [comment]
What is Mojang account for?
Also need a logo.

**Comment by ghost** [comment]
Mojang accounts are for the games Minecraft, Scrolls, and Cobalt. I can't upload the logo for some reason. Never been able to directly upload files on the web version, and I'm on a public computer, so I can't install the desktop application. Is there something I'm missing?

Oh, wait! I'll just attach the logo here and see if I can do something with it.
mojang

**Comment by mxxcon** [comment]
Nope, attaching images to email doesn't work. Have to use proper git client.

**Comment by jdavis** [comment]
I manually added the image and then merged in your pull request.

Thanks for contributing!

**Comment by ghost** [comment]
Thanks for accepting! You saved me a lot of work trying to figure out the client, it's a different version than my home PC. XD Thanks again so much.

**Pull request merged**
