### PR TITLE
Refactor each section into its own data file.

### LINKED ISSUE #127: Refactor main.yml
Now the list is growing longer and longer, perhaps it's worth refactoring `main.yml` into multiple files for each category or maybe even each entry?
That will make it easier for people to contribute changes without having to constantly resync with upstream...

### PR DESCRIPTION
**Pull request by computmaxer**
Tested and working locally!

Fixes #127 

@jdavis @mpdavis @zach-taylor

### CODE REVIEW

**Comment by jdavis** [comment]
Beautiful. I was trying to put the header info (id, name, icon) into each individual file; this works way better.

**Comment by jdavis** [comment]
Oh, and we'll need to iterate over every file in the _data/ now for the verify.rb script for syntax errors because Travis saves sooo much time (at least how I was doing it).

**Comment by RichJeanes** [comment]
If you merge in my PR #143, will this this clobber the 32x32 icons with the old ones in commit ba7d138?

**Comment by computmaxer** [comment]
@jdavis I have addressed your comments in ff42e6f and 9de171d. All ready!

**Comment by jdavis** [comment]
This is great, nice job, Max.

**Pull request merged**
