### PR TITLE
Optimized PNGs with OptiPNG

### PR DESCRIPTION
**Pull request by NullPiotrException**
Optimized all possible PNGs from `img` directory with command `optipng -o7 *`.
Total number of bytes saved: 1132393-1129322=3071. I know it's not much. Did it more just for fun.

Checked all 38 images locally with jekyll. All look fine.
Ran `bundle exec rake` and got no errors.

### CODE REVIEW

**Review by mxxcon — APPROVED** [review]

**Comment by stephengroat** [comment]
should wait until #3061 is merged to get new verification checks in

**Review by stephengroat — DISMISSED** [review]
no changes requested, should wait to merge until #3061 is merged to get new img verification checks in

**Comment by NullPiotrException** [comment]
@stephengroat Good idea.
Also, do you think it would be possible to just optimize every new .png with OptiPNG automatically? So contributors wouldn't need to worry about that. Maybe with [this lib](https://github.com/martinkozak/optipng)? If so, I can make an issue about that.

**Comment by stephengroat** [comment]
@einsteinsfool i like the idea, but unless it can make a pr with the changes, i don't think its super useful.

we had a bot that was going through and doing this, but i don't know what happened to it

**Comment by mxxcon** [comment]
@stephengroat I removed @ImgBotApp because @Carlgo11 didn't like that it was creating PRs with branches in this repo rather than its own

**Comment by stephengroat** [comment]
also github is eventually going to go into a tizzy since it's not an app and it's creating prs, right? [they don't seem to like accounts that automatically create prs](http://movermeyer.com/2018-03-08-building-bots-to-mend-badges/)

i don't think apps can fork, so they'll probably have to have branches on this repo. we just protect the main

**Comment by NullPiotrException** [comment]
Ah, I get it now. It can't just optimize a file and swap it because every change has to be documented in git. So the script/bot would have to either not allow that PR (which would be too much for just a few bytes) or make another commit and that's problematic. Thanks for explaining.

**Comment by mxxcon** [comment]
Well, it's not authenticating into github on user's behalf. It is its own thing using proper bot apis. I don't think there's anything illegitimate about it https://imgbot.net/

**Comment by dabutvin** [comment]
Here's a quick overview of how ImgBot installations work. I'm going to go drop this content into the docs https://imgbot.net/docs 

After you install ImgBot into your repo, this is registered with GitHub and you are issued an *InstallationID*. ImgBot itself has an *ApplicationID* and a *private key* that is kept secret. 
With a combination of the *InstallationID*, the *ApplicationID*, and the *private key*, ImgBot can request an *Installation Token* from GitHub. 

This *Installation Token* is valid for 10 minutes at a time and provides the permissions agreed to at the time of installation. If the permissions required by ImgBot change you will be notified and have to accept before they can take affect.

ImgBot specifically uses this *Installation Token* to clone the repo, create a branch, push a commit to the branch, and open pull requests. These actions are performed on behalf of the installation with a username of 'x-access-token' and a password set to the value of the *Installation Token*.

The author and committer for these acctions are set to `ImgBotApp<ImgBotHelp@gmail.com>`. 

Furthermore, more recently, the commits pushed by ImgBot are digitally signed with a secure and registered PGP private key and password and verified against a public key registered with GitHub. This verification provides an extra level of security to ensure that commits that come into your repo are in fact coming from the authentic ImgBot. And you get the nice green verified badge in the PR.

If at anytime you want to remove ImgBot's ability to interact with your repo, you simply uninstall the application from your settings and all further action's will be immediately blocked with no access.

**Comment by stephengroat** [comment]
thanks for the great explanation @dabutvin!

**Review by fpigerre — APPROVED** [review]

**Pull request merged**
