### PR TITLE
Add Booking.com

### PR DESCRIPTION
**Pull request by Carlgo11**
This is an update to #2012 as the creator of that PR seems to be unwilling to update their PR.

### CODE REVIEW

**Review by Jawshy — CHANGES_REQUESTED** [review]
I think it is worth adding their Facebook page `bookingcom`. I think it meets the unwritten guidelines: verified, popular, active, and they respond to comments.

**Comment by Carlgo11** [comment]
@Jawshy Done

**Comment by Carlgo11** [comment]
@stephengroat RuboCop is failing the build. Why is that?

**Comment by stephengroat** [comment]
will fix, getting tons of 500 on github right now

**Review by Jawshy — APPROVED** [review]

**Comment by iphoting** [comment]
This commit/PR seems to be missing from master branch?

**Comment by Carlgo11** [comment]
whops, apparently it got automatically closed because of another PR being merged. I'll submit a new one.
Thanks for pointing it out @iphoting! 😄

**Pull request closed without merging**
