### PR TITLE
Add Token2

### PR DESCRIPTION
**Pull request by token2**
Icon added

### CODE REVIEW

**Comment by dsoegijono** [comment]
:+1:

**Comment by Carlgo11** [comment]
@token2 I think your providers.yml is outdated.

**Comment by token2** [comment]
You are right, resubmitted now

**Comment by token2** [comment]
Strange, I retried with another PR, seems like it is still not up to date.

**Comment by mxxcon** [comment]
@token2 you need to make sure that your repo is up to date with commits with this one, otherwise all your pull requests will have merge conflicts.

**Pull request closed without merging**
