### PR TITLE
Add ProtonVPN and PureVPN

### PR DESCRIPTION
**Pull request by spazvt**
add ProtonVPN and PureVPN service providers, originally added by @deadr0ck to fork
https://github.com/acceptbitcoincash/acceptbitcoincash

### CODE REVIEW

**Review by Carlgo11 — DISMISSED** [review]
```
<------------ ERROR ------------>
1. 'twitter' should NOT be present when tfa: true.
2. 'facebook' should NOT be present when tfa: true.
```

**Comment by jamcat22** [comment]
Hello @spazvt!

The primary reason we remove unused data is to reduce the probability of having inaccurate data. Sometimes companies change their contact information and having that information listed in our files when it is not actively being used increases the chance of that information being out-of-date or inaccurate.

GitHub does keep a [history](https://github.com/2factorauth/twofactorauth/commits/master/) of all files changed in the repo, which may be useful if you're looking for files that have previously had contact information that has since been removed.

Thanks,
Jacob

**Comment by Carlgo11** [comment]
Closing due to inactivity

**Comment by spazvt** [comment]
@Carlgo11 please reopen this PR and I'll remove the extra handles, now that I understand your policies better.

**Comment by brycx** [comment]
@spazvt could you please change the Twitter account to [purevpncom](https://twitter.com/purevpncom). Looks like the one in this PR got suspended.

**Comment by spazvt** [comment]
ok updated to `PureVPNcom` - that looks like their preferred capitalization per their [twitter page](https://twitter.com/purevpncom).

**Review by brycx — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
