### PR TITLE
Add Rochester Gas & Electric [Utilities]

### PR DESCRIPTION
**Pull request by tylwright**

### CODE REVIEW

**Comment by stephengroat** [comment]
thanks so much for the pr @tylwright. Could you add a `facebook: RochGandE` tag and switch the url to `url: https://www.rge.com`? That's what I get when I google "rochester gas and electic" and HTTPS is always better :)

**Comment by tylwright** [comment]
@stephengroat - Good catch!  Thanks for letting me know.  I have made the changes.

**Comment by stephengroat** [comment]
perfect. i'm sure @Carlgo11 will want some sort of gif to memorialize the 2001 issue. I'm personally a little excited for what he comes up with

**Comment by Jawshy** [comment]
@tylwright, you may like to use one of these images instead. Both have a significantly smaller file size than the current image and Two Factor Auth favours smaller files. I prefer the latter as text becomes difficult to read at these sizes. 
1. Original rge 
2. Alternative rge-alt

Edit: I also noticed that you're using the master branch on your fork. For future reference I just wanted to let you know that it's preferable to create a new branch for each site (see [CONTRIBUTING → New Sites](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#new-sites)).

**Review by stephengroat — APPROVED** [review]

**Review by stephengroat — CHANGES_REQUESTED** [review]
Could you merge with master? seems like it got a bit stale. you can merge through the web ui now!

**Review by Carlgo11 — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Review by stephengroat — APPROVED** [review]

**Pull request merged**
