### PR TITLE
Add HT Forum

### PR DESCRIPTION
**Pull request by jrbenito**
HT Forum supports 2FA in a software and email fashion.

Signed-off-by: Josenivaldo Benito Jr jrbenito@benito.qsl.br

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
Not bad on [domaintally](https://www.domaintally.com/www/htforum.com)

**Comment by fpigerre** [comment]
Hi @jrbenito,
It seems this pull request has a few merge conflicts. Would you be able to fix them by any chance?

**Comment by jrbenito** [comment]
Hi @psgs

I am on a business travel, as soon as I arrive at a hotel I do it.

Thanks

**Comment by jrbenito** [comment]
@psgs

Up merged and conflict solved.

Regards,
Benito

**Comment by Carlgo11** [comment]
Hello @jrbenito,
sorry for the delay.

I've reviewed the site and come to the conclusion that HT Forum does not fulfil our criteria for sites listed here.

There are a few reasons for this.
1. It's just a Xenforo forum and while it's a large one we generally don't list forums and instead try to make an impact on the larger sites people use every day.
2. HT Forum lacks HTTPS. For TFA to really work you need to transmit the data securely. This requires the use of transport-layer encryption. Something which HT Forum lacks.
Listing HT Forum on our site would give the user a false sense of security.

**Pull request closed without merging**
