### PR TITLE
add authy to digital ocean

### PR DESCRIPTION
**Pull request by devinschulz**

### CODE REVIEW

**Comment by jdavis** [comment]
Can I get a link to this or some sort of screenshot of configuration just to be sure?

**Comment by mxxcon** [comment]
@iDevSchulz perhaps update your commit to use this url since it's more useful than just an announcement post.. https://www.digitalocean.com/community/articles/how-to-install-authy-and-configure-two-factor-authentication-for-ssh

**Comment by jdavis** [comment]
I came across that but that's for securing your actual box SSH access with
Authy, not your actual accont on DO.

**Comment by jdavis** [comment]
If I could get a confirmation that Authy works for the actual account, I'll merge this. In the meantime, I'm setting it to pending.

**Comment by CameronBanga** [comment]
I personally use Authy with Digital Ocean, although I can't find any official blog post, etc. I'll look a bit later, but even if unofficial, DO does work with Authy currently.

**Comment by computmaxer** [comment]
Added Authy support for DigitalOcean in #266

**Pull request closed without merging**
