### PR TITLE
Add OpenDNS

### PR DESCRIPTION
**Pull request by philipithomas**

### CODE REVIEW

**Comment by mxxcon** [comment]
@philipithomas when I go to that docs url I get
"You do not have access to this topic
You do not have access to this page. Please contact the account owner of this Zendesk for further help."

**Comment by jdavis** [comment]
If you could update the doc link to public facing page, then this looks good to me.

**Comment by philipithomas** [comment]
@jdavis Would you prefer a link to our public-facing blog post or no documentation link?

http://engineering.opendns.com/2014/05/22/launching-two-step-verification/

**Comment by jdavis** [comment]
The blog link would be great; there are various other sites with a link that point to a blog post as well.

**Comment by philipithomas** [comment]
@jdavis Done

**Comment by mxxcon** [comment]
@philipithomas Is this for regular OpenDNS customers or only enterprise/Umbrella ones? When I login to my account with https://dashboard.opendns.com/ I see no mention of this..

**Comment by philipithomas** [comment]
It's currently paid customers; we're in the process of rolling it out to all users.

**Comment by jdavis** [comment]
Well hopefully it comes soon to all users then =]

**Pull request merged**
