### PR TITLE
Added porkbun.com TFA Enabled Domains

### LINKED ISSUE #2120: Domain Registrar Porkbun.com
Porkbun.com supports software token 2FA: https://porkbun.com/products/two_factor_authentication

### PR DESCRIPTION
**Pull request by adnrs96**
This PR addes [porkbun.com](https://porkbun.com/) to domains category with TFA enabled.
This PR will resolve #2120 .

### CODE REVIEW

**Comment by fpigerre** [comment]
Thanks for the pull request @adnrs96! :+1:

**Review by fpigerre — APPROVED** [review]

**Comment by Jawshy** [comment]
Shouldn't the following have been included under `tfa: Yes`? 

``` ruby
      software: Yes
```

**Comment by Carlgo11** [comment]
You're right. I'm guessing @stephengroat and @psgs didn't properly look at the PR.

**Comment by fpigerre** [comment]
Oh, sorry about that.
I didn't see it. :confused:

**Comment by Jawshy** [comment]
Mistakes happen. I shall submit a correction in a PR if someone else has not yet already started.

**Comment by adnrs96** [comment]
I am sorry, I didn't knew about that.
Is there anything else to be added? Should I create a new PR for this?

**Pull request merged**
