### PR TITLE
Add Blade & Soul

### PR DESCRIPTION
**Pull request by atomicptr**
Added Blade & Soul (coming out veeery sooon) though sadly it doesn't seem that there is a doc for it :(.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Hello @kasoki,
We don't list sites as supporting TFA until it's out for customers to use.
I suggest you wait with your PR until they've added TFA.

Thankyou for submitting a pull request,
//@Carlgo11

**Comment by atomicptr** [comment]
I'll resubmit it in a few days then ;)

**Comment by atomicptr** [comment]
@Carlgo11 the game is out by now, not sure if I should make a new PR or if you want to reopen this one.

**Comment by mxxcon** [comment]
@kasoki please use this for `doc` parameter https://support.bladeandsoul.com/hc/en-us/articles/207578553-Supported-Two-Step-OTP-Authentication-Verification-Methods

**Comment by atomicptr** [comment]
Done, they finally added a documentation \o/

**Comment by jamcat22** [comment]
Awesome! Thanks for the PR @kasoki!

It may take some time before your changes show up on the site. For more info, check out our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_MERGE).

If you have any other sites to add or update, please don't hesitate to make another PR.

Thanks!
-- jamcat22

**Pull request merged**
