### PR TITLE
Add HYPE

### PR DESCRIPTION
**Pull request by Nicos18**

### CODE REVIEW

**Comment by mxxcon** [comment]
any doc urls?

**Comment by Nicos18** [comment]
No docs available on 2FA, but I tried personally, and for every login, the system sends a SMS to the mobile number provided in the registration

**Comment by Carlgo11** [comment]
@Nicos18 Does it send a notification that someone logged in or does it send a code that's used for the login process?

**Comment by Nicos18** [comment]
@Carlgo11 it sends a SMS to the certified number for the login process

**Comment by Carlgo11** [comment]
Right but what kind of SMS does it send?

**Comment by Nicos18** [comment]
@Carlgo11 it sends a SMS with a six-digit verification code that it is necessary to complete the login in the system; just the email and password don't allow the login

**Comment by Carlgo11** [comment]
Alright, thank you.

**Review by Carlgo11 — APPROVED** [review]

**Comment by conorgil** [comment]
Bummer there are no docs. Aside from that, looks good to me. @stephengroat @Carlgo11 @mxxcon good to merge?

**Pull request merged**
