### PR TITLE
Updated Icons

### PR DESCRIPTION
**Pull request by RichJeanes**
Updated site icons to 32x32.
Updated main.yml to update logo file names.
Updated Blizzard Custom Blackberry link to "mobile" icon.
Updated README to no longer reference Google's favicon tool.
Merged in jdavis/master to ensure no conflicts.

### CODE REVIEW

**Comment by RichJeanes** [comment]
@jdavis Those icon updates you mentioned in #103? All done.

**Comment by jdavis** [comment]
Great work, Rich. For realsies. I'll have to do a manual merge but no worries.

**Comment by RichJeanes** [comment]
Thanks! Happy to help.

**Comment by RichJeanes** [comment]
Hmm, I'd be happy to get this merged in myself but I'm not sure what's causing the conflict. I have the master merged into my fork with no issues. If you like I can just update the images myself directly on the master (now that I'm a collaborator and all that).

**Comment by computmaxer** [comment]
@RichJeanes did you happen to figure that out? Can we close this?

**Comment by RichJeanes** [comment]
Looks like some of these got fixed in #236 so I'm going to close this and fix others that haven't been updated directly.

**Pull request closed without merging**
