### PR TITLE
Added Ankama

### PR DESCRIPTION
**Pull request by bouftou**
Ankama is an independent digital creation group focused on the entertainment industry.
- online gaming (Dofus and Wakfu MMORPGs...), publishing (Dofus manga), animation (Wakfu series), press (Dofus magazine), video games for seventh generation consoles, music, merchandise...

### CODE REVIEW

**Comment by Carlgo11** [comment]
1. The image is too big. 
   Here's a compressed version.
   ankama
2. You don't need to add fields with `No`. See [FAQ_New_TFA_Site](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_TFA_SITE)
3. Where does it say they support email TFA? I only see the Ankama Authenticator app.

**Comment by bouftou** [comment]
There is Ankama Authenticator (mobile application) and Ankama Shield (https://support.ankama.com/hc/en-us/sections/200274067-Ankama-Shield)

**Comment by bouftou** [comment]
is it OK ? :)

**Comment by jamcat22** [comment]
Maybe we could link to their [security kb](https://support.ankama.com/hc/en-us/categories/200093427-DOFUS-Security). That way you can see both the authenticator and the shield.

**Comment by bouftou** [comment]
I've updated the doc link

**Comment by jamcat22** [comment]
It `looks-good`!

**Comment by bouftou** [comment]
Yep, but the travis CI build could not complete...

"No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself."

May be too many external links to check ?

**Comment by jamcat22** [comment]
@bouftou Yep. We've been looking for a fix. Right now we were thinking of just having it check the links in each PR instead of the whole website. See #1265.

**Pull request merged**
