### PR TITLE
Update LastPass

### PR DESCRIPTION
**Pull request by walkerselby**
Clarify the availability of U2F, dependent on plan type.

### CODE REVIEW

**Review by Carlgo11 — COMMENTED** [review]
I'm guessing that you're referring to Yubico OTP?

I think it should be clarified that U2F works on all plans through Duo.

`Availability of 2FA options depends on your account type. U2F is available through Duo integration on all plans. Yubico OTP is available on paid plans.`

Although I don't see any reason why anyone would choose Yubico OTP instead of U2F...

**Comment by walkerselby** [comment]
Yeah, that is what I meant. Not sure why anyone would choose it over U2F either but hey -- just the messengers. Would you like me to commit that revision you wrote in the comments or do you got it? Thanks.

**Review by Carlgo11 — APPROVED** [review]

**Comment by phallobst** [comment]
While we're at it: Shouldn't `sms` be listed as well? [SecureAuth](https://support.logmeininc.com/lastpass/help/secureauth-authentication-lp010034) seems to support it.

**Comment by walkerselby** [comment]
> While we're at it: Shouldn't `sms` be listed as well? [SecureAuth](https://support.logmeininc.com/lastpass/help/secureauth-authentication-lp010034) seems to support it.

Sure, will add later. Looking into it, that seems to only be available on LastPass business/enterprise accounts and is not available on the free, premium, or family plans. I will add a note for that as well.

**Comment by Carlgo11** [comment]
I think "Availability of 2FA options depends on your account type" covers that. If we add more to the string I'm not sure it will fit the popup div.

**Review by phallobst — APPROVED** [review]

**Pull request merged**
