### PR TITLE
 Add Marcus

### PR DESCRIPTION
**Pull request by JLarky**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Thanks for the pull request @JLarky!
I added a commit removing GSBank as #2940 stated that Marcus used to be GSBank.

**Review by Carlgo11 — DISMISSED** [review]

**Comment by JLarky** [comment]
Oh, cool, I didn't know that :) thank you

**Comment by kmpoppe** [comment]
Hm, #2940 states that Marcus has SMS/EMail 2FA, yet your pull request says they don't. Did they remove it? I sure hope not?

**Comment by JLarky** [comment]
Oh, wow, you are right
image

Let me update it

**Comment by Carlgo11** [comment]
They use 128-bit SSL? That sounds bad 😟
I’d expect a bank to at least have 256-bit cipher support with TLS 1.2.

**Review by Carlgo11 — APPROVED** [review]

**Review by kmpoppe — APPROVED** [review]

**Pull request merged**
