### PR TITLE
Add GeForce (Nvidia) [Gaming]

### PR DESCRIPTION
**Pull request by Jawshy**
Changes: 
- Added: [Nvidia](http://www.nvidia.com/) under gaming. 
  - No TFA. [Account page](https://account.nvidia.com/). [Twitter handle](https://twitter.com/nvidia) and [Facebook page](https://www.facebook.com/NVIDIA).

### CODE REVIEW

**Comment by stephengroat** [comment]
@Jawshy are you referring to the authentication for their shop?

**Comment by Jawshy** [comment]
@stephengroat, no, I'm only referring to the account which can be used to log into their [GeForce Experience](http://www.geforce.com/geforce-experience) application. Their [online store](http://store.nvidia.com/store/nvidia/DisplayEditProfilePage) must require different credentials as I can't log into it when using the same credentials I would use for their application.

**Comment by stephengroat** [comment]
Maybe change the name to `GeForce` and the website url to `http://www.geforce.com/`?

Nvidia just looks like the shop

**Comment by Jawshy** [comment]
Sure, I'll change it over to `GeForce`, but could `Nvidia` (in parenthesis) also be appended at the end as people may search using "Nvidia" as the keyword?

**Comment by Jawshy** [comment]
Shall I also change the social media links from `NVIDIA` to `NVIDIAGeForce`?

**Comment by stephengroat** [comment]
Yes to both

**Comment by Jawshy** [comment]
Done.

**Pull request merged**
