### PR TITLE
Add MyFRITZ!

### PR DESCRIPTION
**Pull request by phallobst**
Supersedes #5703 

`myfritz.net` has no Alexa rank, but `sso.myfritz.net` has... :man_shrugging: 

Although the doc page refers to FRITZ!Box 7590, the MyFRITZ! login is device-independent.

### CODE REVIEW

**Review by ApCoder123 — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
Oh, what about regions?

**Comment by phallobst** [comment]
Regions should not matter here.

**Comment by Carlgo11** [comment]
But according to Wikipedia Ftitz! is available in Germany, Austria and Switzerland so shouldn't that be the regions?

**Comment by phallobst** [comment]
https://en.avm.de/service/distributors/europe/germany/

Those are just the countries with distribution partners - using a FRITZ!Box elsewhere is possible as well.

**Comment by Carlgo11** [comment]
Thanks for clearing that up :+1:

**Pull request merged**
