### PR TITLE
Add solium.com

### PR DESCRIPTION
**Pull request by maggiewhite**
Shareworks Solium supports TOTP 2FA. It's not well documented in their customer support docs, but it's mentioned a couple of times.

Screenshot:
Screen Shot 2021-08-12 at 2 47 20 PM

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Hello @maggiewhite,
thanks for the pull request!

As I'm sure you've seen, the build is failing because your PR lacks a logo.
Here's one that I took from the solium website:
```SVG
<svg xmlns="http://www.w3.org/2000/svg" fill="#009da7" viewBox="0 0 265 265"><path d="M1 132v132h263V0H1v132zm150.4-94.5c16.9 4.7 30 15.4 37.4 30.4 2.3 4.6 4.2 9.1 4.2 10 0 1.3-2.9 2.3-14.7 5-8.2 1.8-15.7 3.5-16.9 3.7-1.6.4-2.4-.3-3.8-3.4-5.2-11.5-19.9-17.3-35.8-14.3-11.5 2.3-18.8 8.4-18.8 15.9 0 10.5 11.5 18.4 43.1 29.7 43.9 15.7 62.4 35.5 58.9 63.2-1.7 13.3-6.6 22.9-16.4 32.1-12.3 11.4-26.2 16.2-49.6 16.9-13 .4-17.1.2-25.3-1.5-19.3-4-35.3-14.3-45.2-29.2-4.5-6.7-10.4-20.5-9.2-21.6.5-.5 30.1-7.4 31.8-7.4.5 0 1.8 1.9 3 4.2 3.5 6.8 11.9 14.4 20.6 18.6 7.7 3.6 8 3.7 19.8 3.7 10.4 0 12.7-.4 17.2-2.4 13.4-6 17.2-19.1 8.2-28.1-3.9-3.8-15.3-9.3-33.9-16.3-18.2-6.8-27.9-11.4-37.3-17.7-12.6-8.4-20.2-18-23.1-29.5-7.2-27.6 11.5-54.3 44-62.5 6.6-1.6 10.2-1.9 21.9-1.6 8.9.3 16.2 1 19.9 2.1z"/></svg>
```
Just paste that into `img/s/solium.com.svg`.

As the documentation page you provided is behind a login wall it can't be used. Could you please remove that line and instead post a screenshot of the documentation or setup process here? We need that for verification purposes.

**Comment by maggiewhite** [comment]
Hi @Carlgo11! Thanks for the review. Just uploaded a commit that adds a `img/s/solium.com.svg` file with the contents you specified, removed the documentation link and added an anonymized screenshot of the process.

**Review by Carlgo11 — APPROVED** [review]
Thanks @maggiewhite!
A second maintainer will look at the PR before it can be merged. Looks good to me though! :+1:

**Review by phallobst — COMMENTED** [review]
The product is called "Shareworks", and the URL redirects to "shareworks.com" as well. The site acknowledges this: "We are Shareworks by Morgan Stanley formerly Solium."

I reckon this entry should not use the old name, but rather "Shareworks" and "shareworks.com" as the main URL, maybe with "solium.com" in `additional-domains`. The file names would need to be renamed accordingly.

**Comment by maggiewhite** [comment]
@phallobst Updated it to use shareworks instead of solium. The reason I used solium is that for login and post-login the website uses:
https://shareworks.solium.com/solium/servlet/userLogin?requested_lang=en

**Comment by maggiewhite** [comment]
@phallobst bump on a re-review on this please :)

**Review by phallobst — APPROVED** [review]

**Pull request merged**
