### PR TITLE
Update js deps and move to unveil on cdn

### PR DESCRIPTION
**Pull request by stephengroat**
move to `unveil2` on `cdnjs`, update all other deps

functionality verified, should be reviewed again

### CODE REVIEW

**Review by mxxcon — COMMENTED** [review]
perhaps use jsdelivr for all scripts to minimize time spent on looking up and connecting to various cdns?

```
<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.2.13/dist/semantic.min.js" integrity="sha256-Bhi6GMQ/72uYZcJXCJ2LToOIcN3+Cx47AZnq/Bw1f7A=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/unveil2@2.0.8/src/jquery.unveil2.js" integrity="sha256-TJeKT7YYibjK/MKACXmyJbZzKgIASoiFZqYrySyh1cQ=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/jets@0.14.0/jets.min.js" integrity="sha256-0wXdZ7VL+Nng2jfkSxgChagPiF6ZzDToGwzomq/AfBw=" crossorigin="anonymous"></script>
```

**Comment by stephengroat** [comment]
@mxxcon cdnjs is more popular (higher likelyhood of cache hit), supports spdy and other, newer HTTP protocol enhancements, probably a better choice. just a move to unveil2 as a stopgap while it gets pushed to cdnjs

**Comment by stephengroat** [comment]
@mxxcon all libs now available on cdnjs

**Comment by mxxcon** [comment]
You probably wanted to use minified version?

`<script src="https://cdnjs.cloudflare.com/ajax/libs/unveil2/2.0.8/jquery.unveil2.min.js" integrity="sha256-B00tEEtJRbA9gas0viRdqVPI81EuZG+kYU978/alKt8=" crossorigin="anonymous"></script>`

**Review by mxxcon — APPROVED** [review]

**Review by fpigerre — APPROVED** [review]

**Comment by stephengroat** [comment]
@psgs i'm now seeing superbad jquery times on page processing (didn't see this before, might be something new in chrome since this came out). are you seeing the same thing? might want to revert if this is the case

screen shot 2018-03-26 at 10 05 22 am

**Comment by RichJeanes** [comment]
What did you do on the page to get that performance? I'm browsing and searching the page without issue in Firefox 59.0 32bit.

**Comment by stephengroat** [comment]
this is when it's locally loading from `bundle install && bundle exec jekyll serve` with these new merges.

i think it's not liking my local serving now (something with new jekyll or something else that i have no idea about), i just want to make sure that it's an issue confined to my local system and not something more systemic that we need to revert

**Comment by Carlgo11** [comment]
Same for me
screenshot

**Comment by stephengroat** [comment]
fixed by #3090

**Comment by fpigerre** [comment]
Hello,

It looks like the jQuery Unveil plugin is running some sort of recursive QuickSort algorithm that's chewing up resources. As the Unveil plugin is no longer maintained and doesn't seem to be versioned very well, I would suggest moving to jQuery's lazy loading library (proposed in #3090). I can confirm this issue does not present itself as of commit a917e41a65a2173b7d92f226eaef1327bf35a6c3.

screen shot 2018-04-05 at 14 02 48

Thanks,
psgs 🌴

**Pull request merged**
