### PR TITLE
Adding Northeast Credit Union

### PR DESCRIPTION
**Pull request by egon1024**
Adds Northeast Credit Union, a credit union in the northeast of the US.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Hello Cole,
thank you for contributing to the project! :smile: 

I have a few suggestions for optimizing this PR.
1. The logo looks like it's been shrunken down and then resized again making quality worse.
   I suggest you use this image instead:
     
2. We try to add some sort of social media to all sites listed as not supporting TFA. I suggest you add `facebook: northeastcu` just under `tfa: No` for NECU. optionally you could add `email_address: memberservices@necu.org` as well.

**Comment by egon1024** [comment]
Thanks for the feedback.  Yeah, the icon was just a copy of the `favicon.ico` file (resize) so the quality was definitely horrible.  I saw some entries that were making reference to twitter handles (which NECU doesn't seem to have) and wasn't aware of the other attributes that could be set.  Is there a canonical list of supported attributes somewhere?  I'll get these changes done, in the meantime.

**Comment by Carlgo11** [comment]
Hello again @egon1024,
the facebook & email_address tags have yet to be listed as they haven't been implemented yet. 
They can however still be added. The tags just won't show up on the site until the design is published. See #1838 for more info

**Comment by egon1024** [comment]
(nod)  Thanks for the info.  :smiley:

**Comment by egon1024** [comment]
@Carlgo11 - is there a next step?  Anything else I need to do in order to have this PR accepted/merged?  Or is it just a matter of waiting?

**Comment by RichJeanes** [comment]
@egon1024 Sorry for the delay, volunteers on personal time and all that. 

Did you use the logo image that Carlgo posted in his comment, or did you use your own. The one that is in the commit is over 2KB while Carlgo's is 245 bytes.

**Comment by egon1024** [comment]
No worries on the delay or anything - I just wanted to make sure that I hadn't missed any steps in submitting the update.  :)  As to the image - I swore I had updated the PR with the new image, but seemingly not.  I'll try to do that shortly.  Thanks for letting me know.

**Comment by RichJeanes** [comment]
Thank you for updating that image!

**Pull request merged**
