### PR TITLE
Add liftopia

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by fpigerre** [comment]
Hi @stephengroat :smile: 
This site ranks `202,723` according to Alexa. Do you think it fits the [site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria)?

**Comment by stephengroat** [comment]
Stores credit card info, lift tickets for skiing, etc. (this site abuses my credit card during the winter). Do we want to make a final Alexa ranking criteria?

**Comment by Carlgo11** [comment]
Nah I think it's okay but I'm a bit hesitant to the retail criteria.

**Comment by stephengroat** [comment]
Any other ideas?

**Comment by Carlgo11** [comment]
`other`

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Move to `other` as requested in [261290344](https://github.com/2factorauth/twofactorauth/pull/2050#issuecomment-261290344).

**Review by Jawshy — APPROVED** [review]
`looks-good`

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
