### PR TITLE
Add Digital Surge

### PR DESCRIPTION
**Pull request by fletcherdodd**

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Thanks for the pull request!

I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
screenshot

**Comment by fletcherdodd** [comment]
There currently doesn't seem to be any documentation anywhere on their website. I have attached some screenshots of the setup process and login screen below.

image
image
image
image
image
image
image

**Comment by Carlgo11** [comment]
From your screenshots it looks like they use SMS 2FA and require SMS 2FA in order to set up TOTP 2FA.

**Comment by fletcherdodd** [comment]
I'll edit the json 🙂

**Review by Carlgo11 — APPROVED** [review]

**Review by phallobst — APPROVED** [review]

**Pull request merged**
