### PR TITLE
Restore WiseBanyan exceptions

### PR DESCRIPTION
**Pull request by swrobel**
Because https://github.com/2factorauth/twofactorauth/pull/2032 was merged, I believe this should be restored

### CODE REVIEW

**Review by mxxcon — COMMENTED** [review]
This is considered two-factor authorization, not authentication. In such situations we consider this as 'tfa:no' and no need for exception.

**Comment by swrobel** [comment]
@mxxcon then why was #2032 accepted, the sole purpose of which is to enable exceptions for tfa:no services?

**Comment by mxxcon** [comment]
Use-cases and discussion is in your linked PR and PRs linked from it.
But also please see https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions

**Comment by swrobel** [comment]
Listen dude, you're just being an obnoxious pedant. I'm not saying we should say we support 2fa, we should just note their current policy. It at least gives context.

**Comment by Carlgo11** [comment]
Hello Stefan,
my name is Carl and I'm the chief maintainer of this project.
From my point of view, your comment seems really rude towards @mxxcon, one of our most experienced maintainer.
As with most other projects on GitHub, twofactorauth.org is entirely run by volunteers.
Volunteers who dedicate a vast amount of time to maintaining this project and so attacking a maintainer for only doing their job will not be tolerated.
I totally understand if you're having a bad day or maybe didn't intend for the comment to come out the way it did. Just try and cool down before you write anything further here 😜

Let's try and keep this, and all other discussions on this repository friendly and professional. 😉 

If you'd like to discuss this further then I'd love to hear from you!
My email is `carl _at_ twofactorauth _dot_ org` (obfuscated because of those pesky spam bots 😝)

**Pull request closed without merging**
