### PR TITLE
Add freenet.de

### PR DESCRIPTION
**Pull request by guerda**

### CODE REVIEW

**Comment by guerda** [comment]
I corrected the metadata and the logo according to the CI build.

**Comment by RichJeanes** [comment]
Does Freenet have a Twitter account that could be added to the listing? If they have a Twitter dedicated to support, that is preferable.

**Comment by guerda** [comment]
Freenet does not have a twitter account for support. They only have one-directional "news twitter feeds". So no contact with these feeds.

**Comment by Carlgo11** [comment]
@guerda Do they have some email address to turn to for support? That or Facebook page?

**Comment by guerda** [comment]
@Carlgo11 They have facebook. Is there an attribute for that? I haven't found any facebook attributes in the files.
They do not provide any support contact mail address.

**Comment by Carlgo11** [comment]
Hello again @guerda,
sorry for the late reply.

Facebook pages can be added like this:
`facebook: <facebook_page>`
so for example if the facebook page is `https://facebook.com/2factorauth/` the facebook tag would be `facebook: 2factorauth`.
Hope that helps! :smile:

**Comment by guerda** [comment]
Hi @Carlgo11 !
Thanks for the help! I added the section accordingly.

**Comment by Carlgo11** [comment]
@2factorauth/core

**Pull request merged**
