### PR TITLE
added Netflix and iTunes

### PR DESCRIPTION
**Pull request by Carlgo11**

### CODE REVIEW

**Comment by mxxcon** [comment]
Do we need itunes if we already have apple?

**Comment by Carlgo11** [comment]
uhm yeah I think so

**Comment by jdavis** [comment]
iTunes and an Apple ID are the same. I don't think iTunes should be on there.

**Comment by Carlgo11** [comment]
@jdavis Okay. Anything else?

**Comment by mxxcon** [comment]
@Carlgo11 is Netflix the logo correct? For me github shows it as broken image.

**Comment by dsoegijono** [comment]
@mxxcon Netflix logo looks right to me.

**Pull request merged**
