### PR TITLE
Fix 404 and recompress images

### PR DESCRIPTION
**Pull request by mxxcon**
[Review on Reviewable](https://reviewable.io/reviews/jdavis/twofactorauth/1125)

### CODE REVIEW

**Comment by Carlgo11** [comment]
:+1:

**Comment by jamcat22** [comment]
@mxxcon The PlayStation URL was fixed in #1105.

**Comment by RichJeanes** [comment]
Then again, were these compressed images already taken care of, too?

**Comment by mxxcon** [comment]
@RichJeanes since this PR?
@jamcat22 (i think) fixed merge conflict.

**Comment by RichJeanes** [comment]
I just remember seeing a PR that had a bunch of compressed images, just didn't remember if it was this one or another one that already got merged. I didn't know if this PR was needed or not since the other thing it fixed (the PSN link) was fixed already.

**Comment by mxxcon** [comment]
I made a similar recompress commit a couple of month ago.

**Comment by jamcat22** [comment]
Please remove all the provider images. Then it should be ok.

**Comment by mxxcon** [comment]
I think i messed up this PR :/

**Comment by jamcat22** [comment]
Yeah not totally sure what happened.

**Comment by mxxcon** [comment]
I'll make a new one tomorrow.

**Pull request closed without merging**
