### PR TITLE
Add countermail

### PR DESCRIPTION
**Pull request by Carlgo11**

### CODE REVIEW

**Comment by RichJeanes** [comment]
I don't know how I would categorize the use of a key file... it's not actually authentication hardware and can be relatively easily copied as opposed to dedicated hardware.

**Comment by mxxcon** [comment]
Is it similar to Google's https://support.google.com/accounts/topic/6103521?hl=en or more like http://keepass.info/help/base/keys.html#keyfiles ?

**Comment by Carlgo11** [comment]
It's like keepass' but requires a password as well

**Comment by RichJeanes** [comment]
So we're going to say key files constitute hardware auth because you can use key files to create your own hardware keys?

**Comment by mxxcon** [comment]
I'm personally still on the fence regarding key files...the same reason as `email` as one of the factors.

**Pull request closed without merging**
