### PR TITLE
Add Blacknight

### LINKED ISSUE #3790: Add cp.blacknight.com please
An Irish hosting and domain seller have added 2 FA to their customer login at the control panel. They use Software Tokens for 2FA, don't require a telephone number

### PR DESCRIPTION
**Pull request by kmpoppe**
Closes #3790

### CODE REVIEW

**Review by Carlgo11 — APPROVED** [review]

**Review by jtagcat — APPROVED** [review]

**Comment by Carlgo11** [comment]
@vc7ee two __members__ of 2factorauth needs to approve the PR before it can be merged. Your approvals don't count 😛

**Comment by jtagcat** [comment]
@Carlgo11 well make me a member then :stuck_out_tongue:

**Comment by Carlgo11** [comment]
@vc7ee doesn't work like that I'm afraid.

**Comment by jtagcat** [comment]
@Carlgo11 I miss the turtle :angry: 
I understand, jk..

**Review by RichJeanes — APPROVED** [review]

**Pull request merged**
