### PR TITLE
Image verification

### PR DESCRIPTION
**Pull request by ilyakatz**
Add a check to the verification script to make sure that all images are 32x32

### CODE REVIEW

**Comment by jdavis** [comment]
A great little addition that I think will help a lot. Great idea @ilyakatz.

**Comment by Carlgo11** [comment]
yay :+1:

**Comment by ilyakatz** [comment]
cool, glad you like it. i added because i messed it up every other time :)

**Comment by mxxcon** [comment]
Is it possible to somehow make those error messages different color or standout a bit more along all the other output?

**Comment by Carlgo11** [comment]
But what about providers? They are often more nooby than the people adding websites.

**Pull request merged**
