### PR TITLE
Add crowd supply

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
I even found a support email address :open_mouth: 
`support@crowdsupply.com`

**Comment by stephengroat** [comment]
Should be handled

**Comment by Carlgo11** [comment]
sorry I forgot to mention it has to use the `email_address:` tag and not `email:`.

**Comment by Carlgo11** [comment]
great! Thanks :smile:

**Comment by stephengroat** [comment]
Yeah, just figured that out. You're assuming I'm smart, big mistake on your part

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
