### PR TITLE
Add more regions

### PR DESCRIPTION
**Pull request by Carlgo11**
Adding more regions that have more than 10 entries.

The regions are:
* China (mainland)
* Chile
* Costa Rica
* South Korea
* Hong Kong
* Peru
* Slovakia
* Taiwan

### CODE REVIEW

**Comment by Carlgo11** [comment]
Unsure how China should be displayed. I'm thinking either as `China Mainland`, `Mainland China` or `China (Mainland)`

**Comment by phallobst** [comment]
Everybody knows what "China" is supposed to mean in this context, especially since "Hong Kong" and "Taiwan" are displayed as well, so just stick with that. We're not practising international politics here.

Besides, the `.dropdown-menu` should use multiple columns, as it's getting quite large already (`column-count: 2;` in CSS).
```

**Comment by Carlgo11** [comment]
@phallobst my thought was that since HK and TW are separate entries there was a need for clarification on what the CN region contained.

Regarding col-count, is this what you're after?
screenshot

**Comment by phallobst** [comment]
The two-column list look good - however, I tried this on mobile and the list was slightly shifted out of view on the right. Swapping the "About" button with the "Region" dropdown should fix this (on most devices).

**Comment by Carlgo11** [comment]
new layout:
desktop
phone

**Review by phallobst — APPROVED** [review]

**Pull request merged**
