### PR TITLE
Add LiteCoinPool

### PR DESCRIPTION
**Pull request by jabberwock**
Add LiteCoinPool.org

### CODE REVIEW

**Comment by kmpoppe** [comment]
Hi @jabberwock and thanks for your contribution. You need to supply an image in the `img:` tag. Please add this to your branch. Please read our Contribution Guidelines on how that image should be prepared.
Thanks!
// Kai

**Comment by kmpoppe** [comment]
Alexa rank: [102,484 on 22.11.2019 07:34 CET](https://www.alexa.com/siteinfo/litecoinpool.org)

**Comment by kmpoppe** [comment]
Obtaining an icon with 32x32 pixels seems to be next to impossible. Also, I can't find any official information as to who runs this site which is at least questionable. Therefore this site _could_ be potentially harmful to the reputation of twofactorauth.org.
I will, therefore, close this PR as it will not be able to adhere to our Guidelines.

**Comment by jabberwock** [comment]
This is the oldest pool for mining Litecoin although I cannot speak for its security posture. Understood about the impracticality of creating 32x32 icon given their logo.

**Pull request closed without merging**
