### PR TITLE
BofI Federal Bank

### PR DESCRIPTION
**Pull request by brianvargo**
bofifederalbank
Added BofI Federal Bank as a TFA bank

### CODE REVIEW

**Comment by RichJeanes** [comment]
Is there an online page that has the documentation instead of linking to a PDF file? PDF isn't always a friendly format for mobile users and we don't want to be surprising people with downloads.

**Comment by brianvargo** [comment]
I will check to see.  I apologize for submitting multiple pull requests as I believed the failing might have been on my end as a novice at this.  I shall be more patient in future.

Thank you.

**Comment by Carlgo11** [comment]
Doesn't look like they have anything else.
I say let's go with the PDF.

**Comment by Carlgo11** [comment]
Well... except that I can't find anything about 2FA in the PDF.

**Comment by mxxcon** [comment]
There are 2 image files in this PR. Should be only 1...

**Comment by Carlgo11** [comment]
Closing due to inactivity

**Comment by Jawshy** [comment]
See https://github.com/2factorauth/twofactorauth/pull/2018

**Pull request closed without merging**
