### PR TITLE
Add contabo.de / .com and Anycoin Direct

### PR DESCRIPTION
**Pull request by theincogtion**
Contabo does not seem to support 2FA at all.

https://de-de.facebook.com/ContaboDe/
https://twitter.com/contabocom
https://contabo.com/
SUPPORT[at]CONTABO.COM

### CODE REVIEW

**Comment by theincogtion** [comment]
https://anycoindirect.eu/ already supports 2FA via Google Authenticator

**Comment by Carlgo11** [comment]
Hello @theincogtion,
it seems that you've messed something up.
This PR tries to merge master with gh-pages. That's something that we, maintainers do.

**Comment by theincogtion** [comment]
Sorry for that. How can I report sites which should be added correctly?

**Comment by mxxcon** [comment]
@theincogtion just create a new issue listing the sites, not a pull request.
Alternatively, if you want to make our life easier, you could use this form https://docs.google.com/forms/d/e/1FAIpQLSfFQV0QPp0cSSKEx0rYXb46aXRBBOvelrEPfVV_Qhfm_DDOGw/viewform

**Comment by jamcat22** [comment]
Duplicate of #2731

**Comment by jamcat22** [comment]
Duplicate of #2732

**Pull request closed without merging**
