### PR TITLE
Update to HRMC - add Software support

### PR DESCRIPTION
**Pull request by posul1ed**
Update made to Government list to include software token as HMRC does support software tokens; I use one myself.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Hello @posul1ed,
could you provide us with proof that HMRC supports two factor authentication?

It for example be screenshots (**with personal information and QR codes obfuscated**) 

Thanks!
//Carl

**Comment by posul1ed** [comment]
Hi Carl,

Does this give you enough information?:


  1.  The logon page for HMRC via the gov.uk website
[cid:image003.png@01D3711D.31CF3610]
  2.  The request for a token from an app on the site and authenticating with my username and password.

[cid:image004.png@01D3711D.31CF3610]

  1.  A screenshot of the token app I use showing the HMRC token generating a value

[cid:image005.jpg@01D3711D.31CF3610]

After entering this I was logged on.



Many thanks

Peter

**Comment by Carlgo11** [comment]
@posul1ed email attachments don’t show up on GitHub.

**Comment by posul1ed** [comment]
How can I provide the info? Can I upload the same images by logging in directly rather than replying by email?

**Comment by Carlgo11** [comment]
Reply on GitHub rather than via Email. Then just drag the pictures to the text area.
See https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/ for more information.

**Comment by posul1ed** [comment]
Here are the images I had attached by email previously - let me know if you need anything else.

Regards

username and password
token request
hmrc token

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
Thank you!
btw, nice phone choice 😉

**Review by jamcat22 — APPROVED** [review]
Thanks @posul1ed!

**Pull request merged**
