### PR TITLE
Update BT

### PR DESCRIPTION
**Pull request by ApCoder123**
BT now offers 2FA

### CODE REVIEW

**Comment by 40504** [comment]
@ApCoder123 please add:
> exception: "2FA is not available on the app."

**Comment by 40504** [comment]
and if you want, use this .svg file:

**Comment by ApCoder123** [comment]
Thanks @40504

**Comment by 40504** [comment]
I tried to make these changes for you but didn't find how :) just tried to fork your forked repository but can't because I already have forked the original 2fa.directory repository.

**Review by phallobst — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
