### PR TITLE
Adds entry for Clever in the Education category

### PR DESCRIPTION
**Pull request by jveldridge**

### CODE REVIEW

**Comment by mxxcon** [comment]
@jveldridge i don't see mention of sms on the linked page..please confirm?

**Comment by jveldridge** [comment]
@mxxcon We're in the process of updating the page :)

**Comment by jdavis** [comment]
I wasn't able to view the page without logging in. Is there another page that you can link to instead?

**Comment by mxxcon** [comment]
@jdavis it used to work w/o login earlier today...

**Comment by jdavis** [comment]
It might have something to do with the updates that @jveldridge talked about.

**Comment by jveldridge** [comment]
Page has now been updated, and should be working without login again.

**Comment by jdavis** [comment]
Cool.

**Pull request merged**
