### PR TITLE
Add John Hancock Pensions

### PR DESCRIPTION
**Pull request by rwinikates**

### CODE REVIEW

**Review by RichJeanes — DISMISSED** [review]
Please use a 32x32 icon as listed in the contributing doc (https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)

**Comment by stephengroat** [comment]
here's a fixed image. it's their favicon, not their most recognizable logo, but it works

oie_2331649cp9guyat 1

**Review by mxxcon — APPROVED** [review]

**Comment by rwinikates** [comment]
Thanks @stephengroat. @RichJeanes do you approve now?

**Comment by rwinikates** [comment]
@RichJeanes any chance you can approve this now that your requested changes have been addressed?

**Review by Jawshy — APPROVED** [review]

**Comment by rwinikates** [comment]
@Jawshy @mxxcon either of you able to override the outdated change request?

**Pull request merged**
