### PR TITLE
Added Azure MFA

### PR DESCRIPTION
**Pull request by berga0d**
azure
I've attached "azure.png" to this change request description

### CODE REVIEW

**Comment by Carlgo11** [comment]
Could you add the logo yourself?

**Comment by Carlgo11** [comment]
Also, I don't think you can call that a provider. They only protect their own service

**Comment by mxxcon** [comment]
Azure is already listed under https://twofactorauth.org/#cloud

**Comment by jdavis** [comment]
No, @berga0d is right. Azure is providing a service specifically for 2FA: http://azure.microsoft.com/en-us/services/multi-factor-authentication/

It isn't just 2FA for their cloud, but rather for people that build on top of their cloud.

**Comment by Carlgo11** [comment]
Okay. We still need that icon though.
The png has to be exactly 32 x 32px.

Push another commit with the icon to patch-1 and the error will be fixed.

**Comment by berga0d** [comment]
Is there a way to upload it through Githib website? It seems I can only create code files.

Inviata dal mio Windows Phone

---

Da: Carlgo11mailto:notifications@github.com
Inviato: ‎11/‎09/‎2014 11:12
A: jdavis/twofactorauthmailto:twofactorauth@noreply.github.com
Cc: berga0dmailto:berga_d@hotmail.com
Oggetto: Re: [twofactorauth] Added Azure MFA (#764)

Okay. We still need that icon though.
The png has to be exactly 32 x 32px.

Push another commit with the icon to patch-1 and the error will be fixed.

---

**Comment by mxxcon** [comment]
@berga0d no, you have to use a desktop git client to do that. Their website does not allow uploading of images.

(ignore label, my mistake)

**Comment by jdavis** [comment]
I'm sure GitHub has had that request before, but we really should contact them and let them know that being able to upload files through the web interface would be super nice.

**Pull request closed without merging**
