### PR TITLE
Add ukraine.com.ua to Hosting

### PR DESCRIPTION
**Pull request by Nanotraktor**
Add hosting https://www.ukraine.com.ua/ (tfa via SMS, Google Authentificator, hardware tokens)

### CODE REVIEW

**Comment by mxxcon** [comment]
Still need logo and docs link.

**Comment by Nanotraktor** [comment]
> Still need logo and docs link.

Done.

**Comment by Carlgo11** [comment]
@Nanotraktor please see [FAQ_New_TFA_Site](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_TFA_SITE)

**Comment by jamcat22** [comment]
@Nanotraktor Please remove the unnecessary `twitter:`, `email: No`, and `phone: No` fields.

**Comment by Nanotraktor** [comment]
jamcat22, many thanks for the tip.
Done!

**Comment by jamcat22** [comment]
Great!

**Pull request merged**
