### PR TITLE
Adding the PassBy[ME] provider

### PR DESCRIPTION
**Pull request by paulikt**
This commit hopefully adds the PassBy[ME] provider to the provider list.

Sorry for messing with the previous pull requests.

### CODE REVIEW

**Comment by paulikt** [comment]
"No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself."

I have only modified the yaml and it was declared valid by the validator.

**Comment by RichJeanes** [comment]
I've restarted the build on Travis.

**Comment by Carlgo11** [comment]
Weird. I thought I had fixed that.

**Comment by paulikt** [comment]
Can I do anything to make Travis succeed or the only thing I can do is to wait?
Or in other words: Did I mess up something? Can I help you?

**Comment by RichJeanes** [comment]
No, you did nothing wrong. That's just our testing script. It has issues sometimes.

**Comment by paulikt** [comment]
Thank you for your help :) I've learned a lot while struggling these pull requests. :D

**Pull request merged**
