### PR TITLE
Add localethereum

### PR DESCRIPTION
**Pull request by localcryptosMichael**

### CODE REVIEW

**Comment by brycx** [comment]
@localethereumMichael Could you please provide a `doc` link that describes the setup of 2FA? If that's not available, please provide a screenshot of it, with any personal information blurred out.

**Comment by localcryptosMichael** [comment]
There's no docs at the moment, however 2FA is _mandatory_ and initialised at sign up.

image

**Comment by brycx** [comment]
According to that screenshot, you need to add the `email` tag.

**Comment by localcryptosMichael** [comment]
@brycx Done, thanks.

**Review by brycx — APPROVED** [review]

**Review by mxxcon — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
