### PR TITLE
Update cloud.yml

### PR DESCRIPTION
**Pull request by quella**
I have added appFog as a Cloud site which was not listed.  I have also seen that others online have asked them to add it for a year or more.  Maybe being listed on this site will help move it forward.  Thanks for the service you provide.

### CODE REVIEW

**Comment by Carlgo11** [comment]
You need to add a logo. It has to be 32 x 32 px

**Comment by quella** [comment]
I'm sorry I'm not sure how to upload the image into the IMG/Cloud/ directory for the build. As requested it is 32x32 png for AppFog Cloud service.

**Comment by jdavis** [comment]
You can't upload to the repo through GitHub's web UI. Although, do you have a 32x32 logo available that you can at least upload to a comment on GitHub? You can just use drag and drop or attach it to a new comment. It'll save the contributors time.

**Comment by quella** [comment]
appfog

Attached

**Comment by quella** [comment]
Thank you for the assistance with this.

**Comment by jdavis** [comment]
Excellent. That'll speed things along. Either myself or one of the other contributors will get to this in the next day or so.

**Comment by mxxcon** [comment]
@quella Accept my pull request in your repo and it should automatically show up here.

**Comment by quella** [comment]
Thank you all for your assistance. My first attempt and it was nice to have some help along the way.

**Pull request merged**
