### PR TITLE
Add Noddle

### PR DESCRIPTION
**Pull request by rubenarakelyan**

### CODE REVIEW

**Review by stephengroat — CHANGES_REQUESTED** [review]
Could you fix the image size? it should be 32x32

**Review by stephengroat — CHANGES_REQUESTED** [review]
could you try running the image through tinypng.com? gave me a compression of 71%

**Review by stephengroat — APPROVED** [review]

**Comment by Carlgo11** [comment]
That site doesn't respond to my requests.

```
carl@carl:~# curl http://www.noddle.co.uk/ -v
*   Trying 40.127.190.21...
* connect to 40.127.190.21 port 80 failed: Connection timed out
* Failed to connect to www.noddle.co.uk port 80: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to www.noddle.co.uk port 80: Connection timed out
```

**Comment by rubenarakelyan** [comment]
Works for me

```
curl https://www.noddle.co.uk/ -v
*   Trying 40.127.190.21...
* Connected to www.noddle.co.uk (40.127.190.21) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.noddle.co.uk
* Server certificate: thawte SSL CA - G2
* Server certificate: thawte Primary Root CA
> GET / HTTP/1.1
> Host: www.noddle.co.uk
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: private, s-maxage=0
< Content-Type: text/html; charset=utf-8
< x-frame-options: SAMEORIGIN
< Set-Cookie: __RequestVerificationToken=Wwf7OGWENB8Dm2fKvVeN7Wr8Yy0xB3yhFLnZq5i5w0frLlV8ticnnyblF9pYhFJd-SdTcINqurZTiV_2cAs5cpLPcpE1; path=/; HttpOnly; secure; httponly
< X-UA-Compatible: IE=edge,chrome=1
< Date: Fri, 02 Dec 2016 15:12:14 GMT
< Content-Length: 33433
< 
<snip>
* Connection #0 to host www.noddle.co.uk left intact
```

**Pull request merged**
