### PR TITLE
Added Riseup Mail

### PR DESCRIPTION
**Pull request by cmahns**
The Riseup Collective recently updated their webmail, and added 2FA support!

If anything is broken please feel free to yell at me :)

### CODE REVIEW

**Comment by Carlgo11** [comment]
The logo must be 32 x 32 px

**Comment by cmahns** [comment]
Heh, that was my fault. Looks like I typed in the wrong number when I was resizing the image. Should be fixed now!

**Comment by Carlgo11** [comment]
Add their twitter, <a href="https://twitter.com/riseupnet">riseupnet</a> as well.

**Comment by cmahns** [comment]
I thought I added that... Should be in there now

**Comment by Carlgo11** [comment]
Yup looks good to me.
Nice work :+1:

**Comment by cmahns** [comment]
Thanks! Third time's the charm, right? :)

**Pull request merged**
