### PR TITLE
Add UpCloud

### PR DESCRIPTION
**Pull request by cez81**

### CODE REVIEW

**Review by Jawshy — APPROVED** [review]
Thanks for submitting another pull request, @cez81.

**Comment by cez81** [comment]
As I understand it only subaccounts can use sms and phone. Main account is TOTP only. Maybe worth a note if they're added?

**Comment by stephengroat** [comment]
since sms/phone call is used for account recovery and overrides the TOTP token, I think it makes sense to include that

**Comment by cez81** [comment]
Ah yes, that's true. I agree.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
[@stephengroat](https://github.com/2factorauth/twofactorauth/pull/2281#issuecomment-269793163) I disagree. It clearly states that it's only used for recovery.
Yes one could use it instead of TOTP but TOTP is what they advertise as the only 2FA method.

**Comment by stephengroat** [comment]
alright, what about an exception with `sms is required for password
recovery`?

**Comment by Carlgo11** [comment]
Go for it

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
