### PR TITLE
Add gravatar

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by mxxcon** [comment]
Gravatar uses wordpress.com login, doesn't it?

Also is it worth listing it? It's just your avatar hosting..

**Comment by Carlgo11** [comment]
Yup, it uses wordpress.com and all you can do with it is change your profile picture. Not worth adding IMO

**Comment by stephengroat** [comment]
Changed to wordpress.

I could see a change to an offensive/problematic picture being an issue.

**Comment by jamcat22** [comment]
I'd say we should add it, since they do support 2FA. If they didn't support 2FA, I wouldn't suggest adding it, but considering how we list eight entries for Google products and five for Microsoft, I don't think adding another WordPress site would hurt.

Also, should we use https://secure.gravatar.com/ for the link if we add it?

**Comment by mxxcon** [comment]
@jamcat22 But none of the Google and Microsoft services we list are as single-purpose as avatar hosting and we already have WordPress.com listed

**Comment by stephengroat** [comment]
Gravatar's reach is far beyond simply wordpress though. it's used on
github, stackoverflow, etc.

**Comment by mxxcon** [comment]
Yes it is. But its access is covered by Wordpress.com entry

**Comment by RichJeanes** [comment]
I agree with mxx on this one. Wordpress is the only Login option for Gravatar and it is very obviously branded that way.

**Pull request closed without merging**
