### PR TITLE
Add Navy Federal Credit Union

### PR DESCRIPTION
**Pull request by Carlgo11**
As requested in #966 & #1135

### CODE REVIEW

**Comment by mxxcon** [comment]
merge conflict on this one..

**Comment by mxxcon** [comment]
@Carlgo11 Can you please update this PR to resolve merge conflicts?

**Comment by Carlgo11** [comment]
@mxxcon There. (finally)

**Comment by mxxcon** [comment]
+looks-good 

---

Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- _data/banking.yml @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jdavis/twofactorauth/1136)

**Pull request merged**
