### PR TITLE
Add Internet Slowdown banner

### PR DESCRIPTION
**Pull request by Carlgo11**
The 10th September BattleForTheNet are having a campaign on the net neutrality agenda.
Since we all love the internet I think it would be excellent to spread the word through this site.

The banner will only be shown on the 10th of sept and I can remove the script the day after.

https://www.battleforthenet.com/sept10th/

### CODE REVIEW

**Comment by jdavis** [comment]
I like the internet. I approve.

What do some of the other contributors think? Elder @mxxcon? @dsoegijono? Possibly @smholloway?

**Comment by mxxcon** [comment]
:+1:

**Comment by dsoegijono** [comment]
:+1:

**Comment by Carlgo11** [comment]
Haha I'm merging this then

**Comment by mxxcon** [comment]
@Carlgo11 Time to remove this?

**Pull request merged**
