### PR TITLE
Add ClearScore

### PR DESCRIPTION
**Pull request by ohheyrj**
ClearScore is a credit score tool provided for the UK. It is similar to Noddle which is already listed.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Maybe this logo is better? 
img

**Comment by ohheyrj** [comment]
Yup, I agree. I tried to get a image with the company name under it. But I'll update the image to that one instead 😊

**Comment by Carlgo11** [comment]
Text in the logo is often something to avoid as it will look distorted when shrunken down to 32x32 pixels.

**Comment by ohheyrj** [comment]
That should be the image updated now

**Review by Carlgo11 — APPROVED** [review]

**Review by jamcat22 — APPROVED** [review]

**Comment by jamcat22** [comment]
Thanks for the PR!

**Pull request merged**
