### PR TITLE
Added token2.com

### PR DESCRIPTION
**Pull request by token2**
Added Token2.com

### CODE REVIEW

**Comment by dsoegijono** [comment]
You should add the icon to this branch instead of creating another pull request for it.

**Comment by token2** [comment]
Oki, will readd

On Mon, Aug 25, 2014 at 10:45 AM, Daphne Soegijono <notifications@github.com

**Comment by dsoegijono** [comment]
@token2 You didn't have to close/delete branch either. Just commit the image to this branch (or commit the file change to the `patch-1` branch you have your icon on). Let me know if you need any help.

**Comment by token2** [comment]
Added providers.yml change to the same branch as logo upload.
Thanks

On Mon, Aug 25, 2014 at 10:47 AM, Daphne Soegijono <notifications@github.com

**Pull request closed without merging**
