### PR TITLE
Add Swiss Life

### LINKED ISSUE #5062: Add Swiss Life
- [x] I have searched both open and closed [issues](https://github.com/2factorauth/twofactorauth/issues). The issue I'm creating is not a duplicate of an existing issue.
- [x] I have searched both open and closed [pull requests](https://github.com/2factorauth/twofactorauth/pulls). The issue I'm creating is not a duplicate of an existing pull request.

### Information about the site to be added that supports 2FA: ###

* Site name - `SwissLife`

* Site URL - `https://www.swisslife.ch`

* Does the site support 2FA? - `Yes`

* Documentation URL - ``

### Information about what methods of 2FA the site supports: ###

* Software:
  - [ ] TOTP (RFC-6238, Google Authenticator)
  - [ ] Proprietary (Authy, Duo, etc.)

* Hardware:
  - [ ] FIDO2/U2F security keys
  - [ ] Other

- [ ] Phone calls
- [x] SMS tokens
- [ ] Email tokens

### Information about the site's eligibility to be added to twofactorauth.org: ###

- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

### PR DESCRIPTION
**Pull request by christianbumann**
Resolves #5062

### CODE REVIEW

**Comment by christianbumann** [comment]
Screenshots to 2fa were added to the issue itself

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Here's a better image:
logo

**Comment by christianbumann** [comment]
> Here's a better image:
> logo

Thanks looks good. How I can approve your requested changes?

**Comment by Carlgo11** [comment]
Sadly changes to binary files (such as PNGs) work a bit differently on GitHub. You'll have to go to the [directory](https://github.com/christianbumann/twofactorauth/tree/feature/gh-5062/img/finance) and upload the image that I attached as `swisslife.png`.

**Comment by christianbumann** [comment]
> 
> 
> Here's a better image:
> logo

@Carlgo11 image replaced. Sorry for short closing this PR :-)

**Review by Carlgo11 — APPROVED** [review]

**Review by phallobst — APPROVED** [review]

**Pull request merged**
