### PR TITLE
added betfair.com & invictuscapital.com

### PR DESCRIPTION
**Pull request by 40504**
Hi, added 2 sites: betfair.com and invictuscapital.com that meet site criteria to be listed on twofactorauth.org

### CODE REVIEW

**Comment by Carlgo11** [comment]
@40504 Please keep it to one site per pull request.

**Comment by 40504** [comment]
so I have to create a branch for each site?

**Comment by 40504** [comment]
> @40504 Please keep it to one site per pull request.



> @40504 Please keep it to one site per pull request.

so I have to create a branch for each site?

**Comment by Carlgo11** [comment]
Yes

**Pull request closed without merging**
