### PR TITLE
Changed case of E in email for clio in other.yml

### PR DESCRIPTION
**Pull request by plecavalier**

### CODE REVIEW

**Comment by mxxcon** [comment]
@plecavalier If you haven't already, you need to resync your fork again. After your previous PR was merged, you need to make sure your master is up to date.
There should not be 3 commits in this PR that changes a single letter...

**Comment by Carlgo11** [comment]
Since it's such a small change I changed this directly in  afb4fb77ba0b88611fc88b8631a0489aa3529182. Closing this PR

**Comment by plecavalier** [comment]
Thanks!

**Comment by Carlgo11** [comment]
no problem

**Comment by plecavalier** [comment]
I thought the improper case was preventing the checkmark in the email
column but now that's it's merged there's still no checkmark.

**Comment by mxxcon** [comment]
@plecavalier See https://github.com/jdavis/twofactorauth/wiki/FAQ_Merge

**Comment by plecavalier** [comment]
Oh. Sorry.

**Pull request closed without merging**
