### PR TITLE
Update Cloudinary

### PR DESCRIPTION
**Pull request by jamcat22**
Cloudinary supports 2FA.
See #962.

[Review on Reviewable](https://reviewable.io/reviews/jdavis/twofactorauth/1252)

### CODE REVIEW

**Comment by mxxcon** [comment]
+looks-good 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jdavis/twofactorauth/1252)

**Comment by Carlgo11** [comment]
The day when @jamcat22 spammed Carl's inbox.
It's "SPAMCAT22 The movie"

Starring Arnold Schwarzenegger as Jamcat, Chuck Norris as Carl and Tom Cruise as @mxxcon.

Soon in a theatre near you!

**Comment by mxxcon** [comment]
I'm not crazy. :-1:

**Comment by Carlgo11** [comment]
So who do you want to play you? Morgan Freeman? Oh I want Morgan Freeman! Want to trade Chuck Norris? :smile:

**Comment by jamcat22** [comment]
@Carlgo11 Well I had to go to sleep at some point. :smile:

Also, remember when I did this? #448
I did one of the worst things I could have possibly have done: inserted 20 sites into one pr.

**Comment by Carlgo11** [comment]
Nope I don't. Thanks for reminding me :wink:

Just did a search in my inbox. 276 mails from you :smile:

**Comment by Carlgo11** [comment]
Well I have 472 from @mxxcon and 203 from Josh. (out of 2165 sent by github)

**Pull request merged**
