### PR TITLE
Add US Veteran Affairs

### LINKED ISSUE #3356: Add Veterans Administration - US Government

### PR DESCRIPTION
**Pull request by kmpoppe**
Global Alexa Site Rank at time of checkin: 4,350
2FA only with ID.me - see in exceptions
I'd like maintainers to discuss whether this variant (duplication of ID.me 2FA options and putting in exception text) is a valid idea.
Closes #3356

### CODE REVIEW

**Review by mxxcon — APPROVED** [review]

**Comment by mxxcon** [comment]
In my opinion the current `exceptions` text is sufficient.

**Comment by kmpoppe** [comment]
Thanks for the heads up @mxxcon!

Am Mo., 4. Feb. 2019, 15:47 hat mxxcon <notifications@github.com>
geschrieben:

**Comment by mxxcon** [comment]
@kmpoppe is this PR still `WIP` or is it good to be reviewed?

**Comment by kmpoppe** [comment]
@mxxcon It's good to go now :-)

**Review by stephengroat — APPROVED** [review]

**Pull request merged**
