### PR TITLE
Updated Chase favicon and info

### PR DESCRIPTION
**Pull request by mxxcon**

### CODE REVIEW

**Comment by mpdavis** [comment]
That document link appears to point me towards enrolling in online account access, not information on their 2FA solutions.

**Comment by mxxcon** [comment]
@mpdavis grrr. Chase's stupid website. From what I've been able to figure out there, if you already have online Chase login, that link will take you to their "Identification Code" setup page. See this link for screenshots of what it looks like http://fppad.com/2011/11/29/boost-your-online-security-with-two-factor-authentication/

**Comment by mxxcon** [comment]
dang it. I'm sorry. I think I messed up this pull request. I tried to resync my fork with upstream. :/ If it invalid please let me know and I'll back out or simply reject it.

**Comment by jdavis** [comment]
Sorry for the frustration!

**Pull request closed without merging**
