### PR TITLE
Add Ripple Trade

### PR DESCRIPTION
**Pull request by ghost**
A real-time gross settlement system, currency exchange, and remittance network by Ripple Labs.

### CODE REVIEW

**Comment by ghost** [comment]
Poor Travis.

**Comment by Carlgo11** [comment]
Don't worry about Travis. #1265

**Comment by Carlgo11** [comment]
I don't know whether cryptocurrency is the right currency or something else like finance, investing or banking

**Comment by ghost** [comment]
Ripple wants the system to be more of a value exchange than focused on the internal currency. Happy to update as you guys want. 

I'm having fun with my first adventures in open source.

**Comment by ghost** [comment]
I think Finance or Crypto fits best. 

The service is not really intending to store value as with Banking.  They're mission isn't wealth creation as with Investing either. 

Finance is a good generic alternative, but the system is heavily centered around math and cryptography.  Tough one, but after thought, I stand by Cryptocurrency.

**Comment by Carlgo11** [comment]
yeah I still think Finance. Please change it to that

**Comment by ghost** [comment]
Wilco, Sir.

**Pull request merged**
