### PR TITLE
Update Co-Operative Bank

### LINKED ISSUE #6236: Update Co-Operative Bank
### Site name

Co-Operative Bank

### Site URL

https://www.co-operativebank.co.uk/

### Update reason

It now supports 2FA.

### Additional information

Co-Operative Bank UK (For personal customers) have scrapped the use of their Chip+PIN hardware card challenge+response 
OTP readers, and instead implemented SMS based OTP with email as a backup if SMS is not available. A backward step IMHO.

https://www.co-operativebank.co.uk/digital-help/2fa/

https://www.co-operativebank.co.uk/content-hub/news-and-updates/how-we-recycle-your-old-card-readers/

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### PR DESCRIPTION
**Pull request by Carlgo11**
Resolves #6236

### CODE REVIEW

**Comment by kmpoppe** [comment]
Does the warning for not being able to reach `co-operativebank.co.uk` have any particular meaning? It redirects to www.co-operativebank.co.uk, could that be incorporated in the Actions?

**Comment by Carlgo11** [comment]
That test is a bit of a hit and miss. Many sites restrict access because the traffic from the test script doesn't match normal user traffic.

**Comment by phallobst** [comment]
_(Since I did not get a response for my question on the issue, I might as well repeat it here...)_

From their documentation:
> When you're completing certain actions on your account, ...

Does this include logging in? Otherwise, this is _authorization_, but not _authentication_.

**Comment by Carlgo11** [comment]
Closing due to lack of response from original author

**Pull request closed without merging**
