### PR TITLE
Added Clio

### PR DESCRIPTION
**Pull request by plecavalier**

### CODE REVIEW

**Comment by mxxcon** [comment]
This pull request deletes entry for `fruux`...This is obviously something that we don't want to happen. Please correct that.

**Comment by plecavalier** [comment]
Sorry for all the confusion. I'm having such a hard time grasping this...I think the latest is correct. Please advise.

**Comment by mxxcon** [comment]
Yes. So far it looks good. The correct way to resolve this issue would've been to make sure that your fork of this repo is up to date and then create a branch from that current state. Alternatively, you could run some commands to _rebase_ your commits, but it's a bit involved and could really screw things up.

Are you doing this from command line or are you using some GUI git tool?

**Comment by plecavalier** [comment]
All command line. Yeah, I started with rebase and got significantly
confused. I've been using VIM for 20 years so I'd be surprised if it were
that unless there's some oddities between VIM and Gitorious that is not
obvious public knowledge?

Thanks! Phil

Any distribution, use or copying of this e-mail or the information it
contains by other than the intended recipient(s) is unauthorized.

**Comment by mxxcon** [comment]
I have no experience with VIM+git, so couldn't tell you. I personally use SourceTree and occasionally PyCharm's builtin git client for my git workflow. If you still can't figure things about, save your changes elsewhere, completely delete your repo, fork this one again and try branch+pull request again. :)

**Comment by plecavalier** [comment]
I've done that a few times already ;) So are you suggesting I re-fork or
I'm okay with what I current have committed?

Thanks! Phil

Any distribution, use or copying of this e-mail or the information it
contains by other than the intended recipient(s) is unauthorized.

**Comment by mxxcon** [comment]
As it stands, content of this pull request is fine, however it does have multiple unnecessary commits. If you are feeling adventurous, you could try to squash them into a single commit.
I think this guide explains how to do it https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by plecavalier** [comment]
Thank you. I will do just that.

Thanks! Phil

Any distribution, use or copying of this e-mail or the information it
contains by other than the intended recipient(s) is unauthorized.

**Comment by plecavalier** [comment]
Forget it. re-fork...

**Pull request closed without merging**
