### PR TITLE
Added CEX.IO

### PR DESCRIPTION
**Pull request by juliacex**

### CODE REVIEW

**Comment by Carlgo11** [comment]
I know from experience that they use google auth and Authy. And from what I remember Authy also supports phone calls.

**Comment by mxxcon** [comment]
@juliacex it seems like you messed up indentation of the 1st line.

**Comment by juliacex** [comment]
@mxxcon what's wrong with1st line?  name: CEX.IO

**Comment by mxxcon** [comment]
@juliacex now it's fine. :smile:

**Comment by juliacex** [comment]
Hi,

when this update will be online?

**Comment by Carlgo11** [comment]
It is added. Twofactorauth.org will be updated when someone have tested the new updates. Have patience

**Comment by juliacex** [comment]
oh, thanks!

**Pull request merged**
