### PR TITLE
Add search capabilities

### PR DESCRIPTION
**Pull request by hoovercj**
This is a simple implementation of a Search feature. I added a search bar to the top of the page which searches the text contents of each `td` in all the tables. If it does not match the search in any `td` in a `tr` then the `tr` is hidden. If it doesn't match a single `td` in a section then that section is hidden.

This is in reference to issue #521

### CODE REVIEW

**Comment by jdavis** [comment]
Did you write the jQuery plugin?

Edit: It doesn't [look like it](https://github.com/lloiser/jquery-searcher/). Could you add the header license info into both of the JS files?

**Comment by mxxcon** [comment]
This is what it looks like https://lloiser.github.io/jquery-searcher/

**Comment by hoovercj** [comment]
Oops, yeah. -- It is MIT licensed. Available from mxxcon's link or from here: http://plugins.jquery.com/jquery-searcher/

@jdavis: You mean just copy the MIT license from his repo as a comment at the top of both of the JS files?

**Comment by jdavis** [comment]
The `dist/` files include the license info, that's what I mean: https://github.com/lloiser/jquery-searcher/tree/master/dist

**Comment by hoovercj** [comment]
Added license info.

Also, changed it from `fadeIn()`/`fadeOut()` to `show()`/`hide()` because on the fadeOut the cell borders stay as the cell contents fade. This made it faster (without the fade time) and look a little cleaner. Not quite as 'fancy' looking, but cleaner.

**Comment by jdavis** [comment]
K, I'll have to take a look at it once I get home.

**Comment by mxxcon** [comment]
@jdavis *ahem\* :point_up:

**Comment by Carlgo11** [comment]
@mxxcon add a `\` infront of markdown characters such as * for them to show up :wink:

**Comment by Carlgo11** [comment]
@jdavis another _ahem_ :point_up:

**Comment by jamcat22** [comment]
**AHEM AHEM AHEM!!!**

**Comment by Carlgo11** [comment]
We should start a google doc with things that Josh should do :wink:

**Comment by jdavis** [comment]
@Carlgo11 @jamcat22 I approve of the Google Doc =]

**Comment by jamcat22** [comment]
!

**Comment by Carlgo11** [comment]
already created. https://docs.google.com/document/d/14rjmTsRs0pvIxeUnNLUCdhoFuF2fHVWNCYxrV9pUt3Y/edit?usp=sharing

**Comment by jamcat22** [comment]
@jdavis #1302 and #1260 and did you look at the one you just commented on?

**Comment by Carlgo11** [comment]
*Ahem*

**Comment by connorshea** [comment]
We need an "Ahem" emoji.

**Comment by Carlgo11** [comment]
indeed

**Comment by fpigerre** [comment]
This issue has been resolved in issue #1368.

**Pull request closed without merging**
