### PR TITLE
Added Northerntool to retail

### PR DESCRIPTION
**Pull request by kartik95**
Referencing #2094 

Added NorthernTool to utilities.yml

### CODE REVIEW

**Comment by stephengroat** [comment]
Your image is currently wrong (too large in pixel dimensions, should be 32x32 and in bytes)

Please use this one:
image

Also, Northern Tool is a retail store, please move to `retail`

**Review by stephengroat — CHANGES_REQUESTED** [review]
Fix image and move to retail

**Review by stephengroat — APPROVED** [review]

**Comment by kartik95** [comment]
I guess this is good to go @Carlgo11

**Comment by fpigerre** [comment]
Thanks for the pull request @kartik95! :+1:

**Pull request merged**
