### PR TITLE
Add email.cz

### PR DESCRIPTION
**Pull request by srameko**
Now with correct image size

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr @srameko

**Comment by jamcat22** [comment]
It appears the link redirects to a Seznam.cz website. Should the entry be updated to reflect this?

**Review by brycx — CHANGES_REQUESTED** [review]
Thanks for the PR @srameko. Could you please update the link, as @jamcat22 mentioned, and update to their new logo?

**Comment by Carlgo11** [comment]
Closing due to inactivity.

**Pull request closed without merging**
