### PR TITLE
Add simplicity.kiwi

### PR DESCRIPTION
**Pull request by nicholas-l**
Add Simplicity.kiwi. They do not have documentation for adding it however in the settings you can add a TOTP.﻿

### CODE REVIEW

**Comment by Carlgo11** [comment]
Hello @nicholas-l,
thanks for the pull request.

Since no documentation is available, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
screenshot

You also need to use the JSON file extension for any files in `entries/`.

**Comment by nicholas-l** [comment]
Oops didn't realise I hadn't named it .json 😅. As for the screenshots, do you want them in the PR thread, not in the PR itself?

**Comment by Carlgo11** [comment]
The screenshot(s) can be posted here as a comment.

As you fixed the file extension error, the test is now asking for a logo. Here's one that could work:

**Comment by Carlgo11** [comment]
Unfortunately, as the site is ranked above 200K on [Alexa](https://www.alexa.com/siteinfo) it doesn't meet our guidelines of [new site additions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines).

Sorry for the inconvenience.

**Pull request closed without merging**
