### PR TITLE
Update a whole lot of dependencies

### PR DESCRIPTION
**Pull request by fpigerre**
Hello!

This pull request updates a significant number of dependencies for twofactorauth.org, notably the [jQuery](https://code.jquery.com/) and [Jets.js](https://github.com/NeXTs/Jets.js) dependencies.

* jQuery has been updated from version `2.1.4` (29th of April, 2015) to `3.1.1` (23rd of September, 2016)
* Jets.js has been updated from version `0.6.0` (15th of December, 2015) to `0.13.0` (31st of October, 2016)
* Semantic UI has been updated to version `2.2.7` (December 21st, 2016) from version `2.0.7` (JavaScript) and version `2.1.4` (CSS)
* The `github-pages` Gem has been updated from version `112` to version `116`
* The version of Ruby used by TravisCI has been updated from version `2.3.0` (25th of December, 2015) to version `2.4.0` (25th of December, 2016)

Thanks,
psgs 🌴

### CODE REVIEW

**Comment by Carlgo11** [comment]
should we maybe add a hash for Jets.js as well?

**Comment by mxxcon** [comment]
@Carlgo11 We are hosting jets.js, it's not externally hosted.
If somebody manages to compromise our setup to modify jets.js, they will be able to modify the recorded hash as well, so it's pretty much moot point.

**Comment by Carlgo11** [comment]
Okay but what are the pros and cons of providing hashes for internal links?

**Comment by mxxcon** [comment]
Hashes for locally hosted files are redundant. They don't give you any extra security.
Con: larger source code
Con: false sense of security
Con: potentially slower browser since it needs to validate hash
Con: have to maintain one more thing when updating libs

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
Are you done @psgs?

**Comment by fpigerre** [comment]
@carlgo11, Yes, I am 😄

**Pull request merged**
