### PR TITLE
Add SunTrust and Scottrade to Finance category.

### PR DESCRIPTION
**Pull request by coreymatyas**
This adds SunTrust and Scottrade (both sadly without two-factor at this time) to the Finance category.

I couldn't find a higher-resolution icon for Scottrade; there's no good higher-res version of the favicon nor an intermediate size between the favicon and their full logo.

### CODE REVIEW

**Comment by computmaxer** [comment]
@coreymatyas This PR has a merge conflict, please pull in master to resolve. Thanks!

**Comment by RichJeanes** [comment]
Also please make sure icons are 32x32 as per the README guidelines!

**Comment by coreymatyas** [comment]
Resolved merge conflicts and managed to find a higher-resolution version of the Scottrade icon.

EDIT: Travis seems to be failing on _data/health.yml which I did not edit.
EDIT2: Merged again. Travis passing.

**Comment by mpdavis** [comment]
Looks good.

**Pull request merged**
