### PR TITLE
Update build status image source

### PR DESCRIPTION
**Pull request by Carlgo11**
Updated the build status image since we no longer use Travis.

### CODE REVIEW

**Comment by phallobst** [comment]
Can this be something other than "passing" if each PR has to pass the check before it is merged?

**Comment by Carlgo11** [comment]
@phallobst uhm not really. I can’t change the status messages

**Comment by phallobst** [comment]
I think you misunderstood. What I meant was:

Is it possible to have a situation where the build status is something other than "passing", given that each PR individually has to pass the checks before merging? If not, that status is not really useful.

**Comment by Carlgo11** [comment]
Ah no this build status is for the master branch. So unless we merge a PR that breaks our site it shouldn’t fail.

**Review by phallobst — APPROVED** [review]

**Review by dsoegijono — APPROVED** [review]

**Pull request merged**
