### PR TITLE
Adding Citadel Credit Union

### PR DESCRIPTION
**Pull request by eternalyperplxed**

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Thanks for the pull request @eternalyperplxed!
SVGs are preferred over PNGs and I recommend you replace your image with this one:
icon

I see that you haven't added any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, please attach some screenshots of the 2FA setup process and/or login process.
> **Note** Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment, like this:
screenshot

**Comment by eternalyperplxed** [comment]
Thanks for the feedback. I'm updating the img to the provided SVG now.  Their documentation is lackluster at best, so here is an attached screenshot of their 2FA setup screen.

citadel_2fa

**Comment by Carlgo11** [comment]
Thanks for the changes and your screenshot!

The settings panel is really confusing for me :sweat_smile: 
Does the "Two-factor authentication (2FA) at ever login"-section apply to users with Google Authenticator set up or does it have to be 2FA via call, text or email?

**Comment by eternalyperplxed** [comment]
It's a fairly awful enrollment system. If you toggle the "Require two-factor authentication at every login" it will then use the phone/email that is linked to the account from when the account was created. If you then activate Google Authenticator, it will use that over all of the other methods.

**Review by Carlgo11 — APPROVED** [review]
Thanks for the info!
Your contribution will be live within a couple of minutes although sometimes it takes longer to show up due to client and server caching.

**Pull request merged**
