### PR TITLE
Add new categories as in #395

### PR DESCRIPTION
**Pull request by jdavis**
If one or two people agree with these changes, we can merge this into the live version.

Thanks! :cat:

### CODE REVIEW

**Comment by jdavis** [comment]
Here, @mxxcon.

**Comment by jdavis** [comment]
... Okay.

**Comment by mxxcon** [comment]
@jdavis I've been meaning to comment, kept putting it off and now... too late.(hopefully not?)
`Security` category name is kinda ambiguous.. Do you see something else go there beside SSL cert vendors?
I think `Cloud Computing` and `Hosting/VPS` should be combined into the same category. They are essentially the same thing and people that know nuanced difference it doesn't matter. Or if you still think they should be separate, perhaps rename cloud computing into `PaaS/IaaS`?

**Comment by jdavis** [comment]
Yup yup, you can still make comments. No worries. I can't think of anything else that would go there but yeah, the name is a bit ambiguous.

Okay, I'll think on the `Cloud Computing` and `Hosting/VPS` sections and see what I think.

**Pull request merged**
