### PR TITLE
Add First Republic Bank

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by RichJeanes** [comment]
Do they have any publicly visible support documentation talking about their specific 2FA options and/or how to set it up on your account?

**Comment by benmccann** [comment]
The doc I linked to which discusses it is https://www.firstrepublic.com/resource/banking-online-faqs#su10
I don't see anything else besides that

**Comment by mxxcon** [comment]
This question https://www.firstrepublic.com/resource/banking-online-faqs#su8 says they support voice calls too, so please set `phone:yes`.

**Comment by benmccann** [comment]
Done. Thanks for catching that

**Comment by jamcat22** [comment]
Thanks for the PR @benmccann! Even though your PR has been merged, it may take some time before the new entry shows up on the website. For more information on this process, see our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_MERGE).

**Pull request merged**
