### PR TITLE
Update HTML-Proofer dependency to v2.1.0

### PR DESCRIPTION
**Pull request by LeFouineur**
Fix proposition to problems with checking some URLs (ie: #974, #1003) and better management of web servers redirections

### CODE REVIEW

**Comment by Carlgo11** [comment]
@jdavis I think it's best you look at this.

**Comment by LeFouineur** [comment]
Tested and passed the test. It also took in consideration the redirection for OneDrive (www.onedrive.com) as OK apparently. Same with https://onedrive.live.com

**Comment by Carlgo11** [comment]
Oh well that's great! Much appreciated :)
Let's just give @jdavis the final word before we merge.

**Comment by jdavis** [comment]
Cool, I like it.

**Comment by jdavis** [comment]
Beautiful!

```
No errors. You're good to go!
bundle exec jekyll build --drafts
Configuration file: /Users/Davis/Repositories/twofactorauth/_config.yml
            Source: /Users/Davis/Repositories/twofactorauth
       Destination: /Users/Davis/Repositories/twofactorauth/_site
      Generating... 
                    done.
 Auto-regeneration: disabled. Use --watch to enable.
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] checks on ./_site on *.html... 


Checking 843 external links...
Ran on 9 files!


HTML-Proofer finished successfully.
```

**Comment by LeFouineur** [comment]
It would/could be interesting to also update all the Gemfile.lock while we are at it

**Pull request merged**
