### PR TITLE
Add Salesforce

### PR DESCRIPTION
**Pull request by ilyakatz**
I am not entirely sure that the category is correct since SF is so many things

### CODE REVIEW

**Comment by mxxcon** [comment]
@ilyakatz Maybe use this icon? It has less jpeg compression artifacts
https://www.sfapex.com/images/sm-appexchange-icon.png

Also in the linked video it says "text message or email".

**Comment by jdavis** [comment]
Of the specific categories, I think Communication is the best. Unless we wanted to make it more general and put it into Other since Salesforce encompasses a lot...

**Comment by jamcat22** [comment]
Also, shouldn't Salesforce go before Sendgrid?

**Comment by ilyakatz** [comment]
@jamcat22 you're completely right. updated

**Comment by ilyakatz** [comment]
@jamcat22 you inspired me to do this #837

**Comment by ilyakatz** [comment]
@mxxcon updated

**Pull request merged**
