### PR TITLE
Added FogBugz and Kiln to 2FA listing

### PR DESCRIPTION
**Pull request by whimsicallyson**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Hello Allyson,
thank you for your interest in twofactorauth.org! :smiley: 

I have some questions and suggestions for the PR.
1. I see that both the sites you added are developed from Fog Creek Software and that so maybe they use the same login system? If so then maybe it's better to just merge them?
   I don't know very much about these two tools so I appreciate your feedback/thoughts on this.
2. The logos you use are too large which normally would have made this PR fail.

```
<Unnecessary tech talk>

The reason it didn't is because Travis-CI (that we use to test PRs) received a 404 error from GitHub when this PR was created.
I have discussed this with Travis-CI already and they've put their Engineering team on the task to look through this particular issue more carefully.
```

//@Carlgo11 :tay:

**Comment by mxxcon** [comment]
Yes, I think it makes sense to have just a single entry for fogcreek software site since both products use the same login system.

**Comment by whimsicallyson** [comment]
I believe your comments have been addressed, and Travis exited successfully.

**Comment by Carlgo11** [comment]
@whimsicallyson 
I think the name is a bit too long. Maybe call it just `FogBugz & Kiln`?
screenshot

**Comment by mxxcon** [comment]
Or just Fog Creek Software? :)
I imagine if they'll ever add more products they'll also use the same login system.

**Comment by Carlgo11** [comment]
Yeah. Or that

**Comment by whimsicallyson** [comment]
From internal discussion, we decided "FogBugz and Kiln" was best. Updated accordingly!

**Comment by Carlgo11** [comment]
@whimsicallyson the PR has now been merged and will go live within a couple of days.
For more information about this process see [our wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_Merge).

**Pull request merged**
