### PR TITLE
Add Fanatical.com

### PR DESCRIPTION
**Pull request by webdevian**
Including suggested change from https://github.com/2factorauth/twofactorauth/pull/4118

### CODE REVIEW

**Comment by webdevian** [comment]
Not sure why Circle is failing, looks like a ruby gem error

**Review by Jawshy — APPROVED** [review]

**Review by Carlgo11 — DISMISSED** [review]
I think the site would be better fit under the retail section. Please move it.

**Comment by phallobst** [comment]
"Humble Bundle" is also under _Gaming_ - these two should be in the same category.

**Comment by webdevian** [comment]
Yes, it should definitely be in the same category as Humble Bundle. The product range is very similar

**Review by jamcat22 — APPROVED** [review]

**Pull request merged**
