### PR TITLE
Add Ubiquiti

### PR DESCRIPTION
**Pull request by D-on-GitHub**
ubiquiti

### CODE REVIEW

**Comment by stephengroat** [comment]
@daupie this is a good idea, let me someone know if you need help!

**Comment by D-on-GitHub** [comment]
Thanks @stephengroat, it should be done now?

**Comment by stephengroat** [comment]
@daupie great initial work! 

if you look at the [travis logs](https://travis-ci.org/2factorauth/twofactorauth/builds/354534367), you're missing an image for ubiquiti in the `img/other/` directory. i've attached a 32x32 small png (required for this site) to this comment, could you add this into the `img/other` folder and make sure that it's named `ubiquiti.png`?

ubiquiti

**Comment by jamcat22** [comment]
Duplicate of #3072

**Pull request closed without merging**
