### PR TITLE
Add Cedexis

### PR DESCRIPTION
**Pull request by AlessioCasco**
domains --> added cedexis

### CODE REVIEW

**Comment by mxxcon** [comment]
Where does this site fit with https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria ?
And regardless of that, I don't think Cedexis fits into domains registrars category.

**Comment by AlessioCasco** [comment]
I put it there since is where other CDN's providers are.
Cedexis is not a proper CDN, it's more likely a load balance between them

Let me know if you want me to move it

**Comment by mxxcon** [comment]
At first glace i see just CloudFlare listed there.
I think `developer` or `other` categories would be a better fit for cedexis.

**Comment by AlessioCasco** [comment]
Ok will update it and move to Developer

**Pull request merged**
