### PR TITLE
Add Balena

### PR DESCRIPTION
**Pull request by villasenor**
- Alexa ranking: 26,431 (https://www.alexa.com/siteinfo/balena.io)
- Balena applies to balena.io, balena-cloud.com, and all the Balena domains.

### CODE REVIEW

**Comment by ApCoder123** [comment]
SVGs are the preferred format for icons. You may wish to use this one instead:


Balena SVG

**Comment by villasenor** [comment]
@ApCoder123 Happy to update them, and agree that SVG is a better format. Maybe we should update the instructions in CONTRIBUTING.md though, because they reference PNG and that's why I used PNG. I will update all my PRs shortly.

**Comment by ApCoder123** [comment]
Yeah, I totally agree about updating the CONTRIBUTING.md guide and I've opened an issue to address this #5448

**Review by phallobst — APPROVED** [review]

**Comment by villasenor** [comment]
Updated to use SVG, thanks! @ApCoder123 @phallobst

**Review by ApCoder123 — APPROVED** [review]

**Pull request merged**
