### PR TITLE
Travis check for bad lang tags

### PR DESCRIPTION
**Pull request by stephengroat**
`lang` tags should only be used on `tfa: No`, have travis check for this and fix current bad instances

### CODE REVIEW

**Review by jamcat22 — COMMENTED** [review]
I'm not sure I agree with not having `lang` tags for sites with 2FA, mostly because it might aid in any future plans for a more internationally friendly design. Curious to hear other's thoughts on this.

**Comment by mxxcon** [comment]
@jamcat22 But then it's the same approach as removing twitter/facebook/etc for sites that do have tfa...why remove that information since it can be useful for the future as well. 😕

**Comment by jamcat22** [comment]
@mxxcon: I guess we could always add them back later if needed. 😄

**Comment by Carlgo11** [comment]
@stephengroat are you okay with f8c0697?

**Comment by stephengroat** [comment]
@carlgo11 of course! Thanks! The more comments the better! Isn't it a dream to have someone else comment your code for you?

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
