### PR TITLE
Remove DediServe

### PR DESCRIPTION
**Pull request by stephengroat**
blog entry deleted

### CODE REVIEW

**Comment by brycx** [comment]
Do they even support 2FA anymore? I had a look through their new blog and knowledge-base. Not a single mention of 2FA.

**Comment by Carlgo11** [comment]
If we're not sure then we could probably just delete it since https://www.alexa.com/siteinfo/dediserve.com.
Better not to list it than to give false information.

**Comment by brycx** [comment]
> If we're not sure then we could probably just delete it since [...]

Agreed.

**Review by brycx — DISMISSED** [review]

**Review by brycx — APPROVED** [review]

**Comment by Carlgo11** [comment]
`git push -f` is a godsend 😅

**Comment by mxxcon** [comment]
https://manage.dediserve.com/cart/ shows that you can setup 2fa during the signup process..

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
