### PR TITLE
Create psono.com.json

### PR DESCRIPTION
**Pull request by chickahoona**

### CODE REVIEW

**Comment by phallobst** [comment]
This is a self-hosted project, and also its Alexa rank is above 200K; therefore, this website does not qualify for inclusion in our list.

**Comment by chickahoona** [comment]
@phallobst We have a managed solution too with https://psono.pw that people can use free of charge.

**Comment by phallobst** [comment]
Unfortunately, the Alexa rank for both sites is way over 200K.

**Comment by chickahoona** [comment]
@phallobst I understand. Still thanks alot for your consideration. I hope that you don't mind if we reapply once we meet your requirements. As a German company its quite hard to gain some traction ;)

**Pull request closed without merging**
