### PR TITLE
Added Raizers to investing.yml

### PR DESCRIPTION
**Pull request by kartik95**
Referencing #2093 

Added Raizers to investing.yml

### CODE REVIEW

**Review by stephengroat — CHANGES_REQUESTED** [review]
Please correct the `img` to 
image

**Review by mxxcon — CHANGES_REQUESTED** [review]
@kartik95 our logos must always be 32x32
Also I don't think `investing` is the correct category for this. This is somewhat similar to kickstarter, so it should be moved to `other`

**Comment by stephengroat** [comment]
@mxxcon Kickstarter has much more of a product focus, while raizers is focused on giving investors equity in x company. I think that's more `investing`, right?

**Comment by kartik95** [comment]
Should I move Raizers to investing or other? Even imo, Raizers is best fit under investing.

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
