### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
\img\placeholder.png (3.85%))
\notes\img\internetbs.png (8.57%))
\img\utilities\telzio.png (36.3%))

### CODE REVIEW

**Review by mxxcon — APPROVED** [review]

**Comment by mxxcon** [comment]
What tools do you use to optimize?
Probably want to update your website to explicitly state if you optimize images using lossless or lossy methods. 
Also perhaps as an option make it optional to keep images' metadata? I can see there could be situations where that's important.

**Comment by dabutvin** [comment]
👍 

ImgBot is using https://github.com/dlemstra/Magick.NET to do the lossless compression. 

I definitely hear you, and we should state this explicitly on the website 
https://github.com/dabutvin/ImgBot/issues/31

I want to roll out support for reading configuration directly from the repo with a config file
I added your suggestion about metadata there
https://github.com/dabutvin/ImgBot/issues/2

I really appreciate the support and the feedback on ImgBot.

Happy to help by compressing those images
If you want more prs from ImgBot here, or any of your other projects, feel free to install the GitHub app.

https://github.com/apps/ImgBot

**Comment by mxxcon** [comment]
Intresting that imagemagik was able to compress placeholder.png even more than all the tools in [FileOptimizer](http://nikkhokkho.sourceforge.net/static.php?page=FileOptimizer)

**Review by Jawshy — APPROVED** [review]
👍

**Pull request merged**
