### PR TITLE
Update Unfuddle

### PR DESCRIPTION
**Pull request by Carlgo11**
As requested in #710

### CODE REVIEW

**Comment by dsoegijono** [comment]
@jdavis Requesting a new label (something like "update") because this is a good example for an updated site, for #519 (Recently Added section).

**Comment by jdavis** [comment]
@dsoegijono Hmm, Collaborators can't add new labels? I've just added one btw.

**Comment by dsoegijono** [comment]
@jdavis I don't think so. I can add/remove labels, but I don't see how to create a new label. Thanks!

**Comment by jdavis** [comment]
@dsoegijono Interesting. No problem though!

**Pull request merged**
