### PR TITLE
Add gatehub

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by Carlgo11** [comment]
No docs?

**Comment by stephengroat** [comment]
it's behind the signin system, no way to link from outside

**Comment by Carlgo11** [comment]
screenshots then?

**Comment by stephengroat** [comment]
screenshot 2017-04-30 at 20 07 28

**Review by Carlgo11 — APPROVED** [review]

**Review by fpigerre — APPROVED** [review]

**Pull request merged**
