### PR TITLE
Credit Karma added SMS 2SV

### PR DESCRIPTION
**Pull request by dan-petty-ck**
Credit Karma added SMS 2SV

### CODE REVIEW

**Comment by Carlgo11** [comment]
Any documentation that we can link to?
Also, is it 2SV or 2FA? Those are two different things and we don't list two step verification on this site.

**Comment by mxxcon** [comment]
I looked through all of my account settings to where how to enable it and didn't see any such settings. I searched through their documentation and also didn't see any articles mentioning 2fa.
I also tried to login on my phone which i've never done before and it didn't ask me for 2fa..

**Comment by dan-petty-ck** [comment]
The feature was out for a little while, but we just rolled it back.  It should be out again very shortly.  

Credit Karma Tax has had SMS Two Factor Authentication since roll out last year. 

 Documentation is at: 
https://help.creditkarma.com/hc/en-us/articles/115004664263-Why-do-I-need-to-enter-a-new-verification-code-when-I-log-in-from-a-new-device-
https://help.creditkarma.com/hc/en-us/articles/216489263-Credit-Karma-Tax-frequently-asked-questions

**Comment by mxxcon** [comment]
@dan-petty-ck so it's only for credit karma tax, not 'regular' credit karma?

**Comment by dan-petty-ck** [comment]
That's the way it's been for the last year (since it's inception, Credit Karma Tax has required all our members to use two factor authentication).  We had it launched for 'regular' Credit Karma last week, but rolled back because of some issues.  We'll have it back out again very shortly!

**Comment by dan-petty-ck** [comment]
Settings page is at:https://www.creditkarma.com/myprofile/security
Documentation is at: https://www.creditkarma.com/myprofile/security/otcfaq
image

**Review by stephengroat — APPROVED** [review]
`doc` behind auth, probably not worth pushing

**Comment by mxxcon** [comment]
@dan-petty-ck any updates on this?

**Comment by mxxcon** [comment]
#2947 supersedes this.

**Pull request closed without merging**
