### PR TITLE
Add CDN77

### PR DESCRIPTION
**Pull request by BorisBekr**

### CODE REVIEW

**Comment by BorisBekr** [comment]
Hi folks, somehow I managed to bloat my forked repo with unnecessary/erroneous commits 🤦‍♂️ I was just wondering if it's a problem and should I just redo it altogether from scratch? Thx for feedback

**Comment by Carlgo11** [comment]
Hi @BorisBekr, no the commits shouldn't be a problem. When it's merged it will just look like one single commit anyways.
That said, I can compress it into one commit right now if you want to.

**Comment by BorisBekr** [comment]
@Carlgo11 oh ok, whatever works best for you, thank you for clarifying :)

**Review by Carlgo11 — DISMISSED** [review]

**Review by kmpoppe — CHANGES_REQUESTED** [review]
Requested change done myself by commit 273e040

**Review by kmpoppe — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
