### PR TITLE
Add SpeedIT

### PR DESCRIPTION
**Pull request by Tobi7889**
Added a new Provider, that has Two-Factor Auth for Customercenter and on the Webhostingmanagement panel.

### CODE REVIEW

**Comment by smholloway** [comment]
You're missing an image. The site doesn't load. And you put the site in two PRs--pick one.

https://github.com/jdavis/twofactorauth/pull/864

**Comment by mxxcon** [comment]
@Tobi7889 you should also indicate what kind of 2FA you support, link to some documentation and last I checked `S` does not come before `A`, so please place the site in the right spot. ;)

**Comment by Tobi7889** [comment]
Changed :)

**Comment by mxxcon** [comment]
@Tobi7889 also add `software: yes` and a logo image.
You can't use github website to upload images. You have to use a desktop git client to do that.

**Comment by Tobi7889** [comment]
Complete change is commited :+1: 

Thanks for help and sorry for that work ;)

**Comment by Carlgo11** [comment]
It's not commited tho

**Comment by Tobi7889** [comment]
Uff, not here? Commit: d8bd0f8e823d76798e2aa3d1ec2e484b3f962ca9

**Comment by Carlgo11** [comment]
your commit needs to be pushed to Tobi7889:patch-1

**Comment by Tobi7889** [comment]
How i can do this? :)

**Comment by Tobi7889** [comment]
Oh okay, i found. It is commited: #f6cb6ba :)

**Comment by Carlgo11** [comment]
@Tobi7889 
`software` is not positioned correctly.

**Comment by Tobi7889** [comment]
corrected :)

**Comment by Walkman100** [comment]
The doc link: It seems as if the number at the end of `#accordian_item_734` changes with every page load.

**Comment by mxxcon** [comment]
@Walkman100 ya, but it's not a big deal. You won't end up in the wrong place with that link.

**Pull request merged**
