### PR TITLE
Added Hardware to Google

### PR DESCRIPTION
**Pull request by jamcat22**
Let's try this again.
See #832, #834, and #844.
Side note: For some reason, I cannot get rid of the other 6 commits. Anyone have a suggestion?)

### CODE REVIEW

**Comment by Carlgo11** [comment]
Great work @jamcat22! :smile:

**Comment by jdavis** [comment]
Before we merge this, let's fix up the history a bit.

This commit is the only one you want, right? https://github.com/jamcat22/twofactorauth/commit/33528ff88ae447434cd7b9376e5cbb7827fc319e

If so, you should have my repo added as an upstream, if you don't, do:

``` bash
$ git remote add upstream git@github.com:jdavis/twofactorauth.git
# Then fetch all
$ git fetch --all
# Create a new branch from my master
$ git checkout -b mainline remotes/upstream/master
# Apply the commit you care about
$ git cherry-pick 33528ff88ae447434cd7b9376e5cbb7827fc319e
# Force update this PR
$ git push origin patch-google2 --force
```

And you should be good to go. Let me know if there are any issues.

**Comment by jdavis** [comment]
Excellent.

**Comment by mxxcon** [comment]
Wait, how did @Carlgo11 deleted a branch in @jamcat22's repo?

**Comment by Carlgo11** [comment]
@mxxcon pro hacker yo. #anonops #twofactorauthsec #optfa #1337-haxor

**Comment by jdavis** [comment]
screen shot 2014-10-26 at 7 58 31 pm

**Comment by jamcat22** [comment]
:frowning: You spoiled it @jdavis! We were going to see @mxxcon's reaction! :smile:

**Comment by Carlgo11** [comment]
haha yes he added me. Helped him removing those nasty spam commits

**Comment by Carlgo11** [comment]
haha :+1: @jamcat22

**Pull request merged**
