### PR TITLE
Use Shields.io for badges, add license badge

### PR DESCRIPTION
**Pull request by jdavis**
Just a simple update to the README. Here's what it looks like instead:
screen shot 2014-11-01 at 12 44 08 pm

### CODE REVIEW

**Comment by mxxcon** [comment]
Also maybe this?
[Gitter](https://gitter.im/jdavis/twofactorauth?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by jdavis** [comment]
How about this one from Shields to keep the same style (I changed the color to orange)?
gitter.im

**Comment by Carlgo11** [comment]
And maybe one for IRC as well?

**Comment by jdavis** [comment]
Is there no pleasing you all?

How about this?
[irc](http://webchat.freenode.net/?channels=%232fa)

**Comment by Carlgo11** [comment]
haha yeah that looks good ;)

**Comment by jdavis** [comment]
Now:

screen shot 2014-11-01 at 2 58 03 pm

**Comment by mxxcon** [comment]
going a bit overboard with badges, no? ;)

**Comment by Carlgo11** [comment]
Yeah but it's fun isn't it? :P

**Comment by jdavis** [comment]
Oh! I forgot one:

badge

:wink:

**Pull request merged**
