### PR TITLE
Update backup.yml

### PR DESCRIPTION
**Pull request by Ritchie007**
Added Cubby which is a service provided by LogMe.In, so LogMe.In too is tfa enabled.

### CODE REVIEW

**Comment by zach-taylor** [comment]
Should probably link to www.cubby.com since that's the official website for it.

**Comment by Ritchie007** [comment]
There's also 4 or 5 other services supported by logMe.In acoounts, that use the same TFA.

---

Richard Migneron
@ : richard@migneron.com
iMessage: richard@migneron.com
Skype: rmigneron
T: +33 6 52 22 84 76
about.me/richardmigneron
"People who know what they are talking about don't need PowerPoint", Steve Jobs

**Comment by jdavis** [comment]
Also, this broke the build, Ritchie. If you could fix that and add a better link, that'd be great!

**Comment by RichJeanes** [comment]
Seems like this might start to fall under unified sign on sites like Google and Microsoft (#35)...

**Comment by Ritchie007** [comment]
Exactly, but LogMeIn has its own signin accounts:passwd + 2FA

**Comment by jdavis** [comment]
K, well this still broke the build and needs to be fixed before we consider it: https://travis-ci.org/jdavis/twofactorauth/builds/21136371

**Comment by jdavis** [comment]
Closing this for clean up, feel free to open a new pull request if the errors are fixed.

**Pull request closed without merging**
