### PR TITLE
Remove CampBX

### PR DESCRIPTION
**Pull request by spazvt**
CampBX exchange closed in ~Sept 2017.
Alexa ranking: 5M https://www.alexa.com/siteinfo/campbx.com

Therefore removing this website and its image.

### CODE REVIEW

**Review by mxxcon — CHANGES_REQUESTED** [review]
campbx seems to be active. https://twitter.com/CampBX/status/969145208528080896

**Comment by spazvt** [comment]
hmm you're right, they said 

> Bitcoin server rebuild is complete; platform is open again.

 on March 1st 2018 on Twitter. However, [I don't see any activity/discussion about them on reddit](https://www.reddit.com/search?q=campbx&sort=new&restrict_sr=&t=all) since they announced shutting down. They had a decent platform but no one cares about them anymore.

**Comment by mxxcon** [comment]
Reddit is not be-all-end-all of the universe but a bunch of navel-gazers.

**Comment by spazvt** [comment]
@mxxcon I split the BTCJam removal into a separate PR: https://github.com/2factorauth/twofactorauth/pull/3216

**Review by mxxcon — APPROVED** [review]

**Comment by spazvt** [comment]
per #3131 mods have decided to note remove sites with low traffic. And as @mxxcon pointed out, CampBX might one day come back to life (although not likely). Therefore I'll close this PR and leave them on the site.

**Pull request closed without merging**
