### PR TITLE
Add Mercado Pago

### PR DESCRIPTION
**Pull request by fainpablo**

### CODE REVIEW

**Comment by phallobst** [comment]
Is there no public documentation available?

**Comment by fainpablo** [comment]
Same case as Mercado Libre. They only require you to add your phone number to your account and, if you have Authy installed, you'll start generating tokens. The only reference I found is this one, where they explain what to do in case you changed your phone number. https://www.mercadolibre.com.ar/ayuda/Cambié-el-numero-de-celular_2401

**Comment by fainpablo** [comment]
Not sure this is the best option, but we may use the Authy's guide: https://authy.com/guides/mercadolibre/.

**Review by Carlgo11 — APPROVED** [review]
I think the Mercado Libre doc would just be confusing.
This is fine

**Review by phallobst — APPROVED** [review]

**Pull request merged**
