### PR TITLE
Add Smyths Toys

### PR DESCRIPTION
**Pull request by windmueller**
Smyths Toys is running hundreds of shops for toys and entertainment products. They also offer shipping when using their website. Sadly, the order history and personal data can not be secured with 2FA.

Because of legal issues in my country, I am not allowed to add the logo myself. The simplest way in my opinion would be to use the [favicon](https://www.smythstoys.com/favicon.ico).

### CODE REVIEW

**Review by Carlgo11 — COMMENTED** [review]
I'm not sure this meets any site criteria. Is there any sensitive data behind the login portal?

**Comment by windmueller** [comment]
When logged in, I can see

- Personal data like my address
- Stored alternative shipping addresses
- Payment methods
- Order history

In my opinion this is no different than Walmart or Zalando.

**Comment by fducasse** [comment]
hello what's the payment Module of zalando please

**Comment by Carlgo11** [comment]
@fducasse I don't think you're in the right place here. This PR isn't related to Zalando.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
From reading their shipping & delivery page it looks like their main audience is GB,IE,DE,CH,AT. A regions array would be good here.

**Review by Carlgo11 — APPROVED** [review]
Thank you! 🙂
Your contribution will be visible in around 10 minutes. Sometimes it takes longer due to server and browser cache.

**Pull request merged**
