### PR TITLE
Added Star Wars: The Old Republic, Hulu, and Netflix

### PR DESCRIPTION
**Pull request by tehroot**
Added twitter, fixed newline

### CODE REVIEW

**Comment by jdavis** [comment]
Try to use commit messages wisely from now on =]

**Comment by jdavis** [comment]
Some reason Travis didn't update and I didn't see the build failure before I merged. Be sure to either run `ruby verify.rb` or check that the Travis build succeeds before making a PR.

**Comment by tehroot** [comment]
I'll watch for it next time -t

**Comment by tehroot** [comment]
The semicolon threw it off.

**Pull request merged**
