### PR TITLE
Add Charles Schwab Bank

### PR DESCRIPTION
**Pull request by lark047**

### CODE REVIEW

**Comment by mxxcon** [comment]
It's already listed under `Investing` category.

**Comment by brycx** [comment]
@mxxcon Does it belong there? They provide both investment options and banking as far as I can tell.

**Comment by mxxcon** [comment]
What is it more known for, banking or investment? To me investment, but that's subjective.

**Comment by lark047** [comment]
The bank is a separate entity. I've been a customer for five years.

**Comment by mxxcon** [comment]
Does investment and banking have separate login systems?
Your `doc:` link has no mention of 2fa at all.

**Comment by lark047** [comment]
As far as I can tell they're the same. All logins are through https://www.schwab.com.

**Comment by Carlgo11** [comment]
If that's the case then this PR should be closed. Could someone confirm that their login systems aren't separate?

**Pull request closed without merging**
