### PR TITLE
Update Newegg

### LINKED ISSUE #2677: Newegg supports two factor auth
Newegg supports two factor auth through text, app, and e-mail.

### PR DESCRIPTION
**Pull request by stephengroat**
closes #2677

no doc currently available

### CODE REVIEW

**Comment by Carlgo11** [comment]
But you can confirm they support the methods listed in this PR?

**Comment by stephengroat** [comment]
Confirmed

**Comment by Carlgo11** [comment]
@stephengroat I think you accidentally left your email and phone number in that reply. ⚠️

**Comment by stephengroat** [comment]
@Carlgo11 thanks. it's published other places anyway. the google dialer spam detector is a necessity in my life these days :calling:

**Review by Jawshy — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
