### PR TITLE
Add MePIN

### PR DESCRIPTION
**Pull request by hasa**

### CODE REVIEW

**Comment by mxxcon** [comment]
Are you sure about "email" support?

**Comment by hasa** [comment]
@mxxcon Yes

**Comment by smholloway** [comment]
https://www.mepin.com/technical-overview/ says nothing about email--can you point me to some documentation, please?

**Comment by hasa** [comment]
It was mentioned as legacy method in previous version of developer doc ( in developer.mepin.com ), but not present in latest version. MePIN does not recommend E-Mail 2FA although it's supported, so I can also leave it out if you feel having a checkmark there is a problem.

**Comment by jdavis** [comment]
Yeah, @hasa, if you left off email, I think that'd be for the best. As @smholloway mentioned, since it says nothing about it and is only available in the previous version, I don't think it should be there.

Once you update that, it can be merged.

**Comment by hasa** [comment]
Thanks for input, I fixed the feature list to follow documentation.

**Comment by jdavis** [comment]
Great! Thanks.

**Pull request merged**
