### PR TITLE
Added NameSilo.com

### PR DESCRIPTION
**Pull request by elektron9**
Added 2-factor authentication information for NameSilo.com, a domain
registrar.

### CODE REVIEW

**Comment by RichJeanes** [comment]
If a site supports Google Authenticator, just add goog:yes under tfa:yes
Custom is for if a site uses email or their own code generating app.
Also, icons need to be 32x32 in size as per the guidelines in the README.

**Comment by RichJeanes** [comment]
Nice :thumbsup:

**Comment by mpdavis** [comment]
@elektron9 There is a merge conflict with this PR, can you update?

**Comment by RichJeanes** [comment]
Hmm, looks like there's still a merge conflict. Try pulling in the master again or making a local copy of your changes, then starting from scratch with a fresh copy of the master.

**Pull request closed without merging**
