### PR TITLE
zocle adds TFA

### PR DESCRIPTION
**Pull request by dawn360**
I have taken over the ticket from zhexiao.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Hi @dawn360,

okay there are a couple of things you need to change. Here's a list of them:
1. Remove the twitter handle as it's not needed when a site supports TFA
2. Compress `zocle.png`. Right now it's 5.9kb which is faaaar to large for a 32x32px image.
3. Capital Z on the `name:`? I'm guessing you know that better than I do :see_no_evil:
the `img` tag looks good tho so don't change that :smiley: 

And just a quick question, does Zocle support TFA through SMS for all regions or is it a only U.S. thing?

**Comment by dawn360** [comment]
SMS is available in all regions

**Comment by mxxcon** [comment]
Similar to the question I asked in the now-closed PR, @dawn360 Is it logical to hide documentation behind a login in? Seems like unnecessary hoops to jump through for your users and harder to find relevant answers using regular search engines.

**Comment by Carlgo11** [comment]
@mxxcon but the doc link doesn't require a login. I see it and I don't have any account on that site.

**Comment by Carlgo11** [comment]
great @dawn360! 
Merging your PR now.
For more information on what happens after a PR's been merged, read the [Merge FAQ](https://github.com/jdavis/twofactorauth/wiki/FAQ_Merge)

**Comment by mxxcon** [comment]
@Carlgo11 I'm talking about:

> [Here’s a quick tutorial how to enable Two-Step Verification on your Zocle account](http://university.zocle.com/knowledgebase/enabling-two-step-verification/)

From that link.

**Comment by Carlgo11** [comment]
Oh, yeah that's a bit odd...
'Hey we have documentation but we won't show you it!'

**Pull request merged**
