### PR TITLE
Update email.yml

### PR DESCRIPTION
**Pull request by afdezc**
hushicon
Added Hushmail to Email providers

### CODE REVIEW

**Comment by jdavis** [comment]
Are you able to add the image yourself? Or would you like one of us to?

**Comment by afdezc** [comment]
Can't see how to upload the image. If you could help me with that, it'd be great. Thank you!

**Comment by mxxcon** [comment]
@afdezc you can't upload directly from the website. You'll have to use a regular git client.

**Comment by mxxcon** [comment]
@afdezc are you going to send another pull request for this or did you give up?

**Comment by afdezc** [comment]
I'm trying to figure out how to do the image.

**Comment by afdezc** [comment]
Git client sends error when I try to sync.
screen shot 2014-05-15 at 9 02 42 am
screen shot 2014-05-15 at 9 03 13 am

**Comment by afdezc** [comment]
I think I managed to upload the image (please, can you confirm?). I also added email method for Hushmail, so I pull a new request.

**Comment by mxxcon** [comment]
At the top of this pull request you can click on "Files changed" to see what will actually get commited..and unfortunately there's still no image there. :(
According to the screenshot it looks like you are doing things correctly.. Looks like a correct branch, looks like correct files...but I'm not familiar with that client so I don't know what that `Git Error` means.
You also created another pull request at #496 is that intentional or mistake?

**Pull request closed without merging**
