### PR TITLE
Add cisco

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Review by fpigerre — APPROVED** [review]

**Comment by Jawshy** [comment]
I couldn't help but find an email address for them. Think it is worth adding? 

``` ruby
      email_address: web-help@cisco.com
```

**Comment by stephengroat** [comment]
i'm not 100% on the `email_address`, i'll leave it out

**Comment by RichJeanes** [comment]
What is an account on Cisco.com for? Why does it merit a listing?

**Comment by stephengroat** [comment]
Controls access to all of the licensed content you have available to you
from Cisco (iOS versions, etc)

**Comment by Carlgo11** [comment]
hm I'd say it doesn't qualify

**Comment by stephengroat** [comment]
also controls ordering under contract, worse than credit cards

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Don't think it fits under the site criteria.

**Comment by Jawshy** [comment]
Cisco supports TOTP 2FA. Cisco allows you to associate your account with a partner company or register your company as a partner, order services through Cisco's global network of certified partners, et cetera. This site may be reconsidered for listing. 
ciscodotcom2fa
ciscodotcom

**Comment by Carlgo11** [comment]
@Jawshy since the fork got deleted back in 2016 I think it's better if you just create another issue/pr regarding the issue.

**Pull request closed without merging**
