### PR TITLE
Update OneDrive

### PR DESCRIPTION
**Pull request by LeFouineur**

### CODE REVIEW

**Comment by Carlgo11** [comment]
This has already been addressed in #974

**Comment by LeFouineur** [comment]
Yes, I saw it after, but in #974 you use the link with English-US locale in hard.
It would be better to use the generic base url (https://onedrive.live.com) and then let the server deliver the correct localized version

**Comment by Carlgo11** [comment]
That would make the validitor fail

**Comment by mxxcon** [comment]
@Carlgo11 your pr also touches userify which was already addressed elsewhere. Plus @LeFouineur brings up valid point regarding language/locale.

**Comment by LeFouineur** [comment]
@Carlgo11, then we could put the one OneDrive uses after a server redirection: https://onedrive.live.com/about/auth, less clean, but will redirect to the correct localized page (at least while Microsoft doesn't change the structure), while also checking if you're already logged.

**Comment by Carlgo11** [comment]
@LeFouineur pretty sure redirects fail as awell

**Comment by LeFouineur** [comment]
One thing is a little "funny": https://onedrive.live.com gives a 200 HTTP/1.1 answer, so there shouldn't be a problem normally.
Could it be because of the html-proofer version used in the tests (v1.6.0), since they changed few things in the way they managed urls in the next versions (https://github.com/gjtorikian/html-proofer/compare/v1.6.0...2f7f0bd)

**Comment by Carlgo11** [comment]
@LeFouineur You're more than welcome to try and figure out what the problem is. https://travis-ci.org/jdavis/twofactorauth/builds/53698507#L208

**Comment by LeFouineur** [comment]
By updating to html-proofer 2.1.0 (#1006), there isn't an error anymore.
www.onedrive.com and https://onedrive.live.com both passed.
So there shouldn't be a problem by using https://onedrive.live.com anymore

**Comment by Carlgo11** [comment]
Will rerun Travis once #1006 is merged

**Comment by LeFouineur** [comment]
@Carlgo11, you can relaunch the test now. Normally, there shouldn't be any errors anymore.

**Comment by Carlgo11** [comment]
doing it now

**Comment by LeFouineur** [comment]
Will need to restart the test: It was executed while Travis had a load issue and was failing most of them.

**Pull request merged**
