### PR TITLE
Added MFA Provider - SecurePush

### PR DESCRIPTION
**Pull request by ghost**
Supports SMS & Dedicated mobile app & Public API
YAML Validated, image 32x32 PNG

### CODE REVIEW

**Comment by ZeevM3** [comment]
Where do i choose Category?
Not used to GIT interface, sorry.

**Comment by Carlgo11** [comment]
Right...
You don't just copy over the yaml output.
Add your provider to the list, validate (= no errors) and then push the commit

**Comment by mxxcon** [comment]
Wow @ZeevM3 there's so much gobbledygook on that website...

> All traffic to and from the API is encrypted, hashed, and secured by a unique cloaking technique.
> 
> 3th factor protection layer
> 
> Anti-Duplication Technology
> 
> Media Injection Protection
> 
> Auto Transport Technology
> 
> In-memory encryption
> 
> In-packet dynamic Sessions

You are going to lose potential customers once technically savvy people will see such nonsense on your site.

**Comment by ghost** [comment]
@mxxcon That's our very old site. Our new site is going live this month.

**Comment by Carlgo11** [comment]
Correction, that's your current site. We can only base out evaluation on what we see. Not promises of future updates.

So since the current site is so weird would you mind pointing me to where it says you support sms & software?

(also, no https? From all this talk about encryption one would think you'd at least have https)

**Comment by ghost** [comment]
@Carlgo11 Hi
You're absolutely right :) that's our current site, we're working on the new one hopefully launching this june. 
Unfortunately I have nowhere else to point you since that's the only site available at the moment, you can have a look at SPAuth in the Playstore to get a feel around.

Concerning API - You can wait for the new site or check some temp-manual on how one can use our API through VPN here https://manuals.securepush.com/

https - Again, new site. ;)

As i hope you don't judge a book by its cover, try not judge ones product by their landing page ;)

I'm the new CTO and i can assure you, things are nothing like the site you're watching.
Hope to hear more opinons in the future, very useful indeed.
Feel free to email me directly at zeev_m@securepush.com

**Comment by Carlgo11** [comment]
Hmm okay well it does indeed sound like you'll do some improvements for that company (and clearly for the better... :wink:).

However we need proof that the provider supports the different TFA types before we can add it.
I suggest we close this PR for now and reopen it again when your new site is online.

**Comment by ghost** [comment]
Great, i'll update you once the site is up. :)

**Pull request closed without merging**
