### PR TITLE
Add PushCoin school lunch payment system

### PR DESCRIPTION
**Pull request by RichJeanes**
@slisznia Look good?
I would like to use HTTPS for the doc link, but it looks like your certificate for the knowhow site has expired.

### CODE REVIEW

**Comment by slisznia** [comment]
How much time do you give me to update the cert? :) We are right in the
middle of a rollout, can it wait? :)

I understand and of course you're right the cert should be valid.  In
the meantime, can you use HTTP for now and I'll send you a git pull
request when a new HTTPS cert is installed?

Let me know.

Slawomir Lisznianski
Software Architect, PushCoin

**Comment by RichJeanes** [comment]
Absolutely, that's fine. You can submit a PR to update it at any time.

**Comment by Carlgo11** [comment]
School lunch payment?
Hehe Sweden master race 😋

**Comment by mxxcon** [comment]
@slisznia Is 2fa still not available for parents?

**Comment by slisznia** [comment]
We are working on TOTP for the parents. Admins had been using U2F and
are thrilled.

Slawomir Lisznianski
Software Architect, PushCoin

**Pull request merged**
