### PR TITLE
Update entry for Credit Karma

### PR DESCRIPTION
**Pull request by craighutch**
Credit Karma supports 2FA via SMS.
They also have a new logo image.

### CODE REVIEW

**Comment by mxxcon** [comment]
@kb3eua is it available for all of credit karma services? in #2872 it says that it's only for credit karma tax?

**Comment by craighutch** [comment]
@mxxcon It's just for [www.creditkarma.com](www.creditkarma.com)... I'm not using their tax service.

I enabled the 2FA feature, and when I login from an unrecognized device it does indeed send an SMS code and challenge me to provide it before allowing me to complete logging in.

**Comment by mxxcon** [comment]
Alright. But please update your commit. As travis-ci error indicated, no need for `facebook` and `twitter` if `tfa:yes`

**Comment by craighutch** [comment]
@mxxcon done

**Review by mxxcon — APPROVED** [review]

**Review by stephengroat — APPROVED** [review]
thanks for the pr @kb3eua

**Pull request merged**
