### PR TITLE
Add Synergy Wholesale

### PR DESCRIPTION
**Pull request by CameronHall**

### CODE REVIEW

**Comment by brycx** [comment]
Thanks for the PR @CameronHall. Please refer to guideline nr. 4 in CONTRIBUTING, as this PR does not meet this requirement. Unfortunately we cannot add this site right now.

**Comment by CameronHall** [comment]
@brycx thank you for your response. It looks like that guideline was only added recently.

Is it worthwhile removing those that fall outside the guideline? I've gone through the domains page and checked the Alexa ranking for each service provider. Here is a _hopefully complete_ list of those that fall outside the guideling.

### The following domains are in breach of guideline four.
[007names.com](https://www.alexa.com/siteinfo/007names.com) 718,680 
[crazydomains.com](https://www.alexa.com/siteinfo/crazydomains.com) 201,680
[inwx.com](https://www.alexa.com/siteinfo/inwx.com) 949,221
[10dollar.ca](https://www.alexa.com/siteinfo/10dollar.ca) 1,200,689
[domeny.tv](https://www.alexa.com/siteinfo/domeny.tv) 1,029,376
[easydns.com ](https://www.alexa.com/siteinfo/easydns.com) 209,278 
[fabulous.com](https://www.alexa.com/siteinfo/fabulous.com) 525,249
[internet.bs](https://www.alexa.com/siteinfo/internet.bs) 2,581,894
[metaname.net](https://www.alexa.com/siteinfo/metaname.net) 7,255,842 
[namespro.ca](https://www.alexa.com/siteinfo/namespro.ca) 312,446 
[nearlyfreespeech.net](https://www.alexa.com/siteinfo/nearlyfreespeech.net) 431,954 
[ns1.com](https://www.alexa.com/siteinfo/ns1.com) 239,942
[openprovider.co.uk](https://www.alexa.com/siteinfo/openprovider.co.uk) 15,476,388  
[pairdomains.com](https://www.alexa.com/siteinfo/pairdomains.com) 772,171
[pointhq.com](https://www.alexa.com/siteinfo/pointhq.com) 995,354
[register4less.com](https://www.alexa.com/siteinfo/register4less.com) 562,919
[ud-reselling.com](https://www.alexa.com/siteinfo/ud-reselling.com) 7,583,121

**Comment by Carlgo11** [comment]
@CameronHall if you read what the guideline says it states that "[a] new site, that is not already listed, has to be within the Alexa top 200k ranking. [...]" Those have already been listed and so they won't be removed.

**Comment by CameronHall** [comment]
@Carlgo11 can we please reopen this PR? Synergy Wholesale now ranks ~124k

**Review by dsoegijono — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
