### PR TITLE
Add cyon

### PR DESCRIPTION
**Pull request by zedpelin**
cyon.ch is a Swiss hosting provider supporting 2FA for their control panel my.cyon.

### CODE REVIEW

**Comment by Carlgo11** [comment]
It looks like you did something wrong when you added the site to hosting.yml.

Try doing this in your shell:

```
git checkout cyon
git remote add upstream https://github.com/2factorauth/twofactorauth/
git fetch upstream
git reset --hard upstream/master
git cherry-pick 0d899bb57fba18c75290b692225b7b5ba2b6319d
git push --set-upstream origin cyon
```

**Comment by zedpelin** [comment]
Thanks for the instructions. This is what I should have done in the first place :)

**Comment by Carlgo11** [comment]
No problem. Git is difficulty to use at first.

**Comment by fpigerre** [comment]
Thanks for the pull request @zedpelin! :+1:

**Pull request merged**
