### PR TITLE
Add Invio Solutions

### PR DESCRIPTION
**Pull request by gaigelama**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr @ExoUNX. i removed the extra whitespace and `hardware` tag. for `hardware`, this project refers to physical token. `software` refers to the smartphone-based TOTP apps. i didn't see the physical token mentioned in the `doc` link, let me know if i missed anything. thanks and add any more you can think of!

**Comment by gaigelama** [comment]
Thank you. Invio Solutions does support TOTP and Hardware (Yubikey.) You can find the documentation below. I apologize for not including the documentation link. Would you like to submit a new pull request?

Link to documentation:
https://billing.inviosolutions.com/knowledgebase.php?action=displayarticle&id=4158

**Comment by stephengroat** [comment]
@ExoUNX nah, i just updated. thanks!

**Comment by Carlgo11** [comment]
From their way of writing it seems like the 2FA only covers a specific section of their website called the 'billing panel'. If that's the case then it's not really 2FA 🤔

**Comment by gaigelama** [comment]
I would agree. Invio Solutions does however support 2FA on cPanel and Virtualizor as well. It currently isn't documented though.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Hi, I've tried to find stats on how popular the site is but it looks like it's too insignificant to be listed.
Would appreciate feedback on this.

Thanks!

**Pull request closed without merging**
