### PR TITLE
Corrected Windows Azure (now called Microsoft Azure)

### PR DESCRIPTION
**Pull request by jamcat22**
Windows Azure is now called Microsoft Azure. Their two factor authentication supports phone calls too. Also, the docs link was for a Microsoft Account, not Microsoft Azure.

### CODE REVIEW

**Comment by mxxcon** [comment]
Is Azure account different from microsoft/hotmail/outlook account? Always?

For example Gmail is always a Google account, but Google account doesn't always have to be Gmail.

**Comment by jamcat22** [comment]
Yes. They are completely separate. One is a corporate account and one is a consumer account.

They have completely separate logon systems and completely separate passwords.

**Comment by jdavis** [comment]
Cool, thanks for that @jamcat22. I want to get a confirmation by someone else before I continue. Possibly some Microsoft insiders like @alexiip or @theMagicalKarp :smile:

**Comment by theMagicalKarp** [comment]
I checked and everything looks correct. +1 ( ﾟヮﾟ)
It's a little confusing since the management and accounts portal both say **Windows Azure** but it's fo sho **Microsoft Azure** now.

**Comment by jdavis** [comment]
You're awesome, @theMagicalKarp! Thanks dude.

**Pull request merged**
