### PR TITLE
Add transfer wise

### PR DESCRIPTION
**Pull request by RichyHBM**
This pull request addresses issue #1840 by adding transferwise. Once #1839 is addressed, it will also display an exception for logging in via Facebook/Google.

### CODE REVIEW

**Comment by RichJeanes** [comment]
I would be happy to add TransferWise to the site if you will update this entry to a `tfa: No`.

**Comment by Carlgo11** [comment]
@RichJeanes [L152](https://github.com/2factorauth/twofactorauth/pull/1842/files#diff-97f3b3d0ce43462c24270f75398f77e3R152)?

**Comment by Carlgo11** [comment]
@RichyHBM Could you remove the exception? We usually don't display an exception when a site allows third party logins. We only count native logins (unless you're only able to use third party logins.)

**Comment by RichJeanes** [comment]
I guess my brain thought it was marked as yes because of the exception text. Dang mental autocorrect! Thanks, Carlgo!

**Comment by RichyHBM** [comment]
@Carlgo11 Removed the exception :)

**Comment by Carlgo11** [comment]
Hello again @RichyHBM,
could you update your fork? There seems to be a merge conflict.

**Comment by RichyHBM** [comment]
This seems to have already been resolved in #1923

**Pull request closed without merging**
