### PR TITLE
Updated CIBC

### PR DESCRIPTION
**Pull request by strattondev**
Updated CIBC in Banking

### CODE REVIEW

**Comment by mxxcon** [comment]
Your PR looks fine, however on their site it states:

> Before you complete a sensitive transaction that requires greater protection, you will be prompted to enter a one-time verification code. 

Does it mean it's not prompted every time, and would also does not qualify as `tfa:yes`?

**Comment by strattondev** [comment]
No, you're not prompted every time. I figured it would be valid as there are other banks with the same set-up of not entering 2fa all requests; Bank of America, UW Credit Union and Discover. That is what I gathered from my reading of other banks before updating CIBC to `tfa: Yes`.

**Comment by jamcat22** [comment]
The biggest difference is what 2FA is required to do. For example, Bank of America and Discover require 2FA before you can sign in, while it looks like CIBC only prompts for 2FA when performing certain transactions.

Right now our stance on this is that we only list websites that require 2FA for login, not just for certain transactions.

**Comment by Carlgo11** [comment]
> a site that prompts you for an authentication token following user login would be considered Two Factor Auth. A site that does not prompt you for a token upon login, but prompts you for a token when you try to perform a sensitive action would not be considered Two Factor Authentication

See [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions)

**Comment by strattondev** [comment]
@Carlgo11 that makes sense. 

I'm guessing if that is the case then CIBC should be updated to just `tfa: No` without the `status: status: https://www.cibc.com/ca/features/banking-enhancements.html?sf3204759=1` as their status page, or any supporting documentation that I can currently find, mentions 2fa for login? If so I'll update the commit, otherwise I can close the request.

**Comment by Carlgo11** [comment]
@strattonw that's right. `tfa: No` without a `status:` line.

**Comment by strattondev** [comment]
Updated as such.

**Comment by Carlgo11** [comment]
Great!

**Pull request merged**
