### PR TITLE
Add Docker to list of developer sites

### PR DESCRIPTION
**Pull request by colinthompson**
Docker does not support any form of 2FA at this time.

### CODE REVIEW

**Comment by mxxcon** [comment]
What's the point of having an account there?

**Comment by colinthompson** [comment]
Much like GitHub; it provides you with the ability to host your own repository of docker images.

**Comment by Carlgo11** [comment]
Yeah I think it fits the site criteria.

**Comment by colinthompson** [comment]
Thanks folks! Thanks also for running the site; it's a great resource.

**Comment by jdavis** [comment]
:+1: @colinthompson

**Pull request merged**
