### PR TITLE
Turbo tax

### LINKED ISSUE #4467: TurboTax needs an exception
Exceptions & Restrictions: Software 2FA requires also enabling SMS as an alternative login option.

My reasoning: SMS authentication is weaker than software token verification, and 2FA is only as strong as the weakest option enabled.

### PR DESCRIPTION
**Pull request by leggomyinfo**
Closes #4467

### CODE REVIEW

**Comment by phallobst** [comment]
You have included a change for the _Twitter_ entry here by mistake.

**Review by Carlgo11 — COMMENTED** [review]
But phone call 2FA doesn't require SMS as a backup?

**Comment by leggomyinfo** [comment]
@Carlgo11 Just tested it: right you are. Updated.

**Comment by leggomyinfo** [comment]
> You have included a change for the _Twitter_ entry here by mistake.

Still there? I couldn't find one.

**Comment by phallobst** [comment]
I must have been hallucinating regarding Twitter. All is fine.

**Comment by Carlgo11** [comment]
No I cleaned up the PR and removed the Twitter commits.

**Comment by leggomyinfo** [comment]
> No I cleaned up the PR and removed the Twitter commits.

Appreciate it @Carlgo11. I'll be more careful going forward.

**Review by Carlgo11 — APPROVED** [review]

**Comment by kmpoppe** [comment]
Closes #4467

**Review by kmpoppe — APPROVED** [review]

**Pull request merged**
