### PR TITLE
Add Aruba Cloud

### PR DESCRIPTION
**Pull request by simevo**
Italian cloud provider, with operations in cz, fr, de, uk and pl.
[Alexa ranks = #94,887](https://www.alexa.com/siteinfo/arubacloud.com)

### CODE REVIEW

**Review by Carlgo11 — DISMISSED** [review]
Images need to be 32 x 32 pixels and below 2.5KB.
See [Guidelines #2](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines)

**Review by kmpoppe — APPROVED** [review]
As you kindly allowed edits for maintainers, @simevo, I took the liberty to correct the Travis CI check errors. See commit comment for a detailled description.

**Comment by Carlgo11** [comment]
@simevo so what happens when you enable 2FA and try to use the main client?

**Comment by simevo** [comment]
You are asked to install the dedicated app ArubaOTP which works like FreeOTP & friends except it uses a different and incompatible format for the shared secret (18-digits base10).

**Comment by Carlgo11** [comment]
@simevo so 2FA is available everywhere?
Then why did you say it's only available on the control panel in the exception text?

**Comment by simevo** [comment]
ATM the 2FA is only available in the "CONTROL PANEL" not in the "CUSTOMER AREA" (admin stuff):
https://www.arubacloud.com/login.aspx

**Review by Jawshy — APPROVED** [review]

**Pull request merged**
