### PR TITLE
Add SRFax

### PR DESCRIPTION
**Pull request by villasenor**
- Alexa rank: 149,489 (https://www.alexa.com/siteinfo/srfax.com)

### CODE REVIEW

**Comment by phallobst** [comment]
Since there is not publicly accessible documentation available, can you provide us with screenshots of the setup process? Please remember to block out any personal information.

**Comment by villasenor** [comment]
@phallobst Unfortunately I no longer have an account with them, but it's very clearly labeled in the account settings once you log in. I could maybe sign up for a trial but not sure if that is necessary. Let me know!

**Comment by villasenor** [comment]
@40504 what URL were you using? Your browser is hiding the full path. The site looks to be up and functional on my end.
srfax

**Comment by phallobst** [comment]
I get the error message as well when trying to access the website from Germany. With a North American VPN connection, it works.

Regarding the 2FA options: This [Tech Radar review](https://www.techradar.com/reviews/srfax) page (dated 2020-05-14) indicates that `email`, `sms` and ` totp` are available. I can't say if this information is still accurate.

**Comment by Carlgo11** [comment]
Closing due to inactivity.

**Pull request closed without merging**
