### PR TITLE
Add River Financial

### PR DESCRIPTION
**Pull request by sampeiomichi**
Although the www.river.com site currently does not meet Guideline #4 (Alexa top 200K), the company River Financial is a service that should be listed on twofactorauth.org due to the nature of its business. Under Site Criteria, it would fall under Money (#3) as River Financial is a brokerage service for buying and selling Bitcoin.

### CODE REVIEW

**Comment by Carlgo11** [comment]
When a site is close to 200K but with a major social media following we can sometimes make an exception for that but since the site you want to add is ranked above 2M I’m afraid it will have to get a much better ranking before we can accept it.

**Comment by sampeiomichi** [comment]
We actually just bought a new domain and rebranded our product. Our old domain was alto.financial and our Twitter is https://twitter.com/RiverFinancial. We previously ranked about 1M on Alexa. Would this suffice?

**Comment by sampeiomichi** [comment]
> When a site is close to 200K but with a major social media following we can sometimes make an exception for that but since the site you want to add is ranked above 2M I’m afraid it will have to get a much better ranking before we can accept it.

We actually just bought a new domain and rebranded our product. Our old domain was alto.financial and our Twitter is https://twitter.com/RiverFinancial. We previously ranked about 1M on Alexa. Would this suffice?

**Comment by Carlgo11** [comment]
No but something around 250K would be.

Your product is simply not used by enough people to be listed here.

Sorry about the inconvenience.

**Pull request closed without merging**
