### PR TITLE
Add Kerio Connect

### PR DESCRIPTION
**Pull request by koalacurioso**

### CODE REVIEW

**Review by Jawshy — DISMISSED** [review]
Hi, @koalacurioso. It looks like your [file upload](https://github.com/koalacurioso/twofactorauth/commit/817296795b60411a1b6ce9abb57cc57fb336587c) was committed to your `master` branch rather than to your [`patch-1`](https://github.com/koalacurioso/twofactorauth/tree/patch-1) branch ([where Kerio Connect was added](https://github.com/koalacurioso/twofactorauth/commit/8cc1a5d08cc07babe5870cf25b9553b80740983e)). Could you please correct your PR?

**Comment by koalacurioso** [comment]
Have I done right? I'm new of GitHub, don't understand very well this system, seams complicated but it's only because is new to me, I suppose.

**Comment by Jawshy** [comment]
I've corrected your pull request.

**Review by Carlgo11 — APPROVED** [review]

**Comment by brycx** [comment]
Am I the only one getting a dead link report on this URL?

**Comment by Jawshy** [comment]
> 
> 
> Am I the only one getting a dead link report on this URL?

I get a redirect error in Firefox 63 and Edge 42, but I can connect using Tor Browser 8.

**Comment by mxxcon** [comment]
@koalacurioso is Kerio Connect login system separate from Kerio Control, Kerio Operator and Kerio Cloud? It seems like there's a unified login at https://kerio.cloud/login.php, no?

**Comment by koalacurioso** [comment]
Kerio Connect is a on premise Mail Server, Control is a on Premise Firewall and same thing for Operator that is an on premise VoIP solution. The kerio.cloud login is for reseller or clients to manage products license etc.

**Review by kmpoppe — APPROVED** [review]

**Pull request merged**
