### PR TITLE
Add Santander UK

### PR DESCRIPTION
**Pull request by xeonwales**
Added Santander UK

### CODE REVIEW

**Comment by RichJeanes** [comment]
Every site is required to have an accompanying logo. Please see [CONTRIBUTING](../blob/master/CONTRIBUTING.md) for details.

**Comment by Carlgo11** [comment]
Either the CONTRIBUTING or [the wiki](https://github.com/jdavis/twofactorauth/wiki/FAQ_New_SITE). The wiki might be easier to read

**Comment by RichJeanes** [comment]
Oh hey, look at that. Wiki. Wiki is good.

**Comment by Carlgo11** [comment]
@xeonwales are you going to add another commit to the PR?
If not then I will close the PR in a few days just to clean up the list of PRs.

**Pull request closed without merging**
