### PR TITLE
Added SMS support to Usabilla entry

### PR DESCRIPTION
**Pull request by josja**
Initially I forgot to add the SMS support to the Usabilla entry :/

### CODE REVIEW

**Comment by jamcat22** [comment]
Do they support SMS only? Or do they require Google Authenticator?

**Comment by josja** [comment]
We use SMS as fall back mechanism in case you loose your Google
Authenticator.

Hope this answers your question?

Regards, Joshua

**Comment by Carlgo11** [comment]
sounds like sms: No then

**Comment by josja** [comment]
Ah in that case I'll retract my pull request of course

Verstuurd vanaf mijn iPad

Op 28 aug. 2015 om 07:54 heeft Carlgo11 notifications@github.com het
volgende geschreven:

sounds like sms: No then

**Pull request closed without merging**
