### PR TITLE
Token2 data and icon

### PR DESCRIPTION
**Pull request by token2**

### CODE REVIEW

**Comment by mxxcon** [comment]
Generally, "Tok" comes before "Too", but that can be fixed later. :smile: 
Line 156 `hardware: Yes` must not be overly-indented.

**Comment by token2** [comment]
@mxxcon , #716 not closed, #715 was (re-forked from the scratch)

**Comment by token2** [comment]
@mxxcon , changed the order and indents

**Comment by token2** [comment]
@mxxcon , build failed again (complains about the tab character)

**Comment by mxxcon** [comment]
@token2 empty line 153 that separates token2 from toopher entries should not contain tabs(or generally any characters at all). YAML format can be picky about such things.

**Pull request closed without merging**
