### PR TITLE
Add Philips Hue

### PR DESCRIPTION
**Pull request by ApCoder123**
image
image
image

### CODE REVIEW

**Review by phallobst — CHANGES_REQUESTED** [review]
Please use the main site "philips-hue.com" for the domain instead of the login page.

**Comment by phallobst** [comment]
How about this icon:

**Comment by phallobst** [comment]
BTW: This is a good example why the SVG viewbox is useful sometimes. My example was _visually_ centered, but in your version the viewbox is set tightly around the logo, so it will be _geometrically_ centered, and therefore slightly below the visual middle.

**Comment by ApCoder123** [comment]
Thanks! I didn't realise that geometrically centering the icon would move it below the visual middle. Noted for next time.

**Review by phallobst — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
