### PR TITLE
Losslessy recompressed all the images through ImageOptim compression.

### PR DESCRIPTION
**Pull request by mxxcon**
Saved 44% on overall image size. From 329kb down to 146kb.

### CODE REVIEW

**Comment by RichJeanes** [comment]
Looks like domains/namecom.png broke.

**Comment by mxxcon** [comment]
@RichJeanes I think it's github previews.
It looks fine directly in my repo https://github.com/mxxcon/twofactorauth/blob/ImageCompression/img/domains/namecom.png
Unless it's a github bug...

**Comment by RichJeanes** [comment]
Weird. When i get to it through the link to the commit on this page I get this: 
https://github.com/mxxcon/twofactorauth/blob/8978d1ef3a9115e96e59e64f99257180625c647f/img/domains/namecom.png
But, yeah, clicking through your profile to it and the link you gave work fine...

**Comment by jdavis** [comment]
:+1: on the compression of pngs if we figure out the namecom.png issue.

**Pull request merged**
