### PR TITLE
Added Coinfloor

### PR DESCRIPTION
**Pull request by obi**

### CODE REVIEW

**Comment by mxxcon** [comment]
You need to include 32x32 png logo.
Where can we confirm that coinfloor supports all those claimed 2fa methods?

**Comment by obi** [comment]
Will do.

**Comment by obi** [comment]
Coinfloor uses Authy or Yubikey for authentication.  If you sign up for the site you will see both options presented. 

Authy allows for Software Token (the Authy App), SMS, Call 2FA.  Yubikey is a Hardware 2FA mechanism.

**Comment by Carlgo11** [comment]
@obi, I were just going to mention that. Nice work!

**Comment by obi** [comment]
Perfect!  Any idea when it will go live?

**Comment by Carlgo11** [comment]
@obi https://github.com/2factorauth/twofactorauth/wiki/FAQ_Merge

**Comment by obi** [comment]
Thanks :+1:

**Comment by fpigerre** [comment]
Thanks for the pull request @obi! :+1:

**Comment by obi** [comment]
Hi guys.

Is there any news on the merge into the live site of Coinfloor?

Thanks in advance

-O

**Comment by smholloway** [comment]
https://github.com/2factorauth/twofactorauth/wiki/FAQ_Merge

**Pull request merged**
