### PR TITLE
Update Santander PT

### PR DESCRIPTION
**Pull request by phallobst**

### CODE REVIEW

**Comment by Carlgo11** [comment]
"Since September, for access to the mobile APP or Netbanco, the Bank may request, in some cases, the introduction of an additional code sent by SMS to the customer's mobile phone."
Can anyone confirm that this applies to logging in?

**Comment by phallobst** [comment]
It is explained in the section "O que muda e de que forma pode ser afetado?":
> What changes and how can it be affected?
> 
> From September onwards, it may be necessary to enter a code sent by SMS to the mobile phone number you have previously indicated to the Bank to receive this type of messages, in the following situations:
> 
> When accessing the digital channels (NetBanco or App Santander) for the first time;
> Whenever more than 90 days have passed since the last strong authentication.

**Comment by Carlgo11** [comment]
September last year?

**Comment by phallobst** [comment]
I hope so, PSD2 was just around the corner...

**Review by Carlgo11 — APPROVED** [review]

**Review by jamcat22 — APPROVED** [review]

**Pull request merged**
