### PR TITLE
Update Vanguard details

### PR DESCRIPTION
**Pull request by jdavis**
This PR:
- This continues #892.
- Uses relative link for notes to test locally.
- Included a note for Vanguard as it doesn't appear Vanguard has external documentation (yet).
- Also moved some things to an `_include/` for less copying and pasting.
- A bit of tidying.

### CODE REVIEW

**Comment by jamcat22** [comment]
Shouldn't `phone: Yes` be `sms: Yes`?

**Comment by jamcat22** [comment]
Also, thanks for making the header into an include!

**Comment by jdavis** [comment]
@jamcat22 Yup, you're right. Thanks for pointing that out =]

**Comment by jdavis** [comment]
They just tweeted at me. I'll have to update the docs link for this: https://twitter.com/Vanguard_Group/status/540899685167140864

**Comment by jdavis** [comment]
Rebased and fixed based on that tweet from Vanguard.

**Pull request merged**
