### PR TITLE
Remove all sites over 200k alexa in security

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Review by spazvt — APPROVED** [review]
double-checked Alexa stats :+1:

**Comment by Carlgo11** [comment]
Seems like we've now agreed on Slack that we shouldn't remove existing sites over the 200k limit so could we close this one and #3132?

**Comment by mxxcon** [comment]
I'd say yes, close both.

**Comment by Carlgo11** [comment]
Seems like no one is opposed to closing so I'm closing this one and  #3132.

**Pull request closed without merging**
