### PR TITLE
Add Digg.com

### PR DESCRIPTION
**Pull request by DeliveryGuy**
Please add Digg.com for supporting multi factor auth.  Might not be relevant as they only allow external site logins.

### CODE REVIEW

**Comment by mxxcon** [comment]
This looks...not correct...?

**Comment by jdavis** [comment]
Wow such commits.

**Comment by RichJeanes** [comment]
I don't even. What is this?

**Comment by jdavis** [comment]
I think you might have selected the wrong set of branches for your pull request. We shouldn't have to do a pull request for merging master onto another branch =]

I'm closing this for now.

**Pull request closed without merging**
