### PR TITLE
Betvictor add software token

### PR DESCRIPTION
**Pull request by nhmarujo**

### CODE REVIEW

**Comment by nhmarujo** [comment]
Hi @Carlgo11 . Any idea of when this might be merged? Thanks 🙂

**Comment by jtagcat** [comment]
any docs/screenshot?

**Comment by kmpoppe** [comment]
Can confirm, 2FA via SMS and Software.
grafik

**Review by kmpoppe — APPROVED** [review]

**Comment by nhmarujo** [comment]
@vc7ee can you please approve this?

**Review by jtagcat — APPROVED** [review]

**Comment by jtagcat** [comment]
@nhmarujo Here you go, tough it needs an approval from a member of 2fa.. What I am currently unfortunately not.

**Comment by nhmarujo** [comment]
Thank you @vc7ee

**Comment by nhmarujo** [comment]
@Carlgo11 can you please help move this forward?

**Comment by Carlgo11** [comment]
@nhmarujo sorry, I don’t touch the betting category.

**Comment by nhmarujo** [comment]
No worries @Carlgo11 , I recall your view on this subject. I totally respect that 🙂 

@mxxcon can you help move this forward?

**Comment by nhmarujo** [comment]
@mxxcon can you please help move this forward?

**Review by dsoegijono — APPROVED** [review]

**Pull request merged**
