### PR TITLE
Add bitreserve.org

### PR DESCRIPTION
**Pull request by jrpereira**

### CODE REVIEW

**Comment by mxxcon** [comment]
@jrpereira Does it support voice phone calls?

**Comment by jrpereira** [comment]
It defaults to push notifications, fallback to SMS if Authy is unavailable, and allows requesting a phone call.

Here's a shot:
image

Note: the "Request a call" is not rolled out to all users yet, still A/B testing for how many people actually choose it.

**Comment by mxxcon** [comment]
@jrpereira then perhaps exclude phone call once it is decided conclusively yes or no..

**Comment by Carlgo11** [comment]
@jrpereira an update on this?

**Comment by Carlgo11** [comment]
Hello @jrpereira,
I'd appreciate if you'd give us an update on this topic. Does bitreserve.org support phone calls yet?
If not, could you remove that line?

Please reply before 2015-07-24 or I'll close this PR due to inactivity.

Thanks!
//Carl

**Comment by jamcat22** [comment]
If this PR isn't updated in a few days, I'll make a new one to make sure the site is added. Thanks!

**Comment by jamcat22** [comment]
Closing and adding to backlog of sites.

**Pull request closed without merging**
