### PR TITLE
Add ORCID

### PR DESCRIPTION
**Pull request by windmueller**
> The ORCID (Open Researcher and Contributor ID) is a nonproprietary alphanumeric code to uniquely identify scientific and other academic authors and contributors. (Wikipedia)

Alexa site rank is currently 5,369.

Logo usage should be fine according to their [Trademark and iD Display Guidelines](https://orcid.org/trademark-and-id-display-guidelines):

> Other individuals and organizations should not use the ORCID logo or member logo to give a graphic representation of ORCID. Instead, use the green iD icon to represent ORCID.

### CODE REVIEW

**Comment by phallobst** [comment]
Please replace the icon by this one with a smaller file size:
orcid

**Comment by windmueller** [comment]
Icon has been replaced.

**Comment by phallobst** [comment]
I wonder if ORCHID should be placed in "Identity Management" instead. Opinions on this?

**Comment by windmueller** [comment]
Good thinking. I moved it to that category.

**Review by phallobst — APPROVED** [review]

**Review by Jawshy — APPROVED** [review]

**Pull request merged**
