### PR TITLE
Update providers.yml

### PR DESCRIPTION
**Pull request by aaronashfield**
Added SAT Mobile ID from Secure Access Technologies Inc.
I am not sure how to submit the sat.png

### CODE REVIEW

**Comment by mxxcon** [comment]
You have to use a git client to add a logo.
github.com web interface doesn't support uploading binary files.

(And you really gotta stop using that amateurish seo-optimization of keyboard stuffing with the same color text and background at the button of each page. Google doesn't like that)

**Comment by jdavis** [comment]
I just went to the site and it doesn't load: https://www.SecureAccessTechnologies.com

:unamused:

**Comment by aaronashfield** [comment]
Thanks for the heads up. Please retry now.
AA.

**Comment by aaronashfield** [comment]
Hi, I am new to github.
I have downloaded the Git hub client, and added sat.png
I have also attached sat.png to this email.

Please let me know what is the process going forward, i.e. what do I need to do next to post the new provider?

sat

Regards,
AA.

**Comment by mxxcon** [comment]
in your desktop client you need to make sure you switch to your `patch-1` branch. Add your logo there. Commit that change. Push the change to your remote repo, which is github.com. Once you do that, it will automatically show up here.
Your attached image is 16x16. Logos MUST be 32x32 so that they look better on HiDPI screens like macbooks or Win8.

**Comment by aaronashfield** [comment]
Hi,
I created patch-1, added new 32x32 logo, and committed.
The new provider still does not display on the providers page... Any idea why?
AA.

**Comment by mxxcon** [comment]
@aaronashfield you shouldn't need to "create" that branch because it already exist as part of this pull request...
did you push your commit it to the remote repo?
As you can see it does not show up here, which it would automatically.
Additionally, website won't update until your commits get merged into this repo and then another step is taken to generate updated pages.

**Comment by aaronashfield** [comment]
Thank you for the feedback.
I re-installed github, and I think it should be ok now.
Can u please check if everything is fine? or if I need to do anything else?
AA.

**Comment by mxxcon** [comment]
@aaronashfield it looks like you created a new _repository_ named `patch-1` rather than a branch in `aaronashfield/twofactorauth` repository.

**Comment by aaronashfield** [comment]
Hi,
This is driving me nuts... Please help.
1- https://github.com/aaronashfield/SecureAuth/tree/patch-1  shows sat.png is there
2- https://github.com/aaronashfield/patch-1 shows sat.png is there
3- I have also attached sat.png... If it is not in the right place, can you please help put it there?
AA.
sat

**Comment by mxxcon** [comment]
@aaronashfield accept my pull request in your repo and it'll show up here.

**Comment by aaronashfield** [comment]
@mxxcon.  I accepted your request 18 days ago... However, when I go to the provider's page, my company is still not listed...
I though may be with time, it will get there, however, that does not seem to be the case.
Is there another step that I need to take?
AA

**Comment by jdavis** [comment]
Nope! I just lost this pull request in the sea. Check now, it should show up: http://twofactorauth.org/providers/

**Pull request merged**
