### PR TITLE
Moved Dwolla to 'In Progress' for 2FA

### PR DESCRIPTION
**Pull request by GoodVaibz**
https://twitter.com/dwolla/status/611186245029482496 Here is the tweet as evidence of our work on 2FA. We will be rolling out the feature in the near future

### CODE REVIEW

**Comment by mxxcon** [comment]
@vaibhav430 Please remove `Gemfile.lock` from your commit.

**Comment by GoodVaibz** [comment]
Sorry about that, hopefully this is better

**Comment by mxxcon** [comment]
It's not better. :) Now you are deleting all the content from the file. What we need is for you not to modify that file at all.

**Comment by GoodVaibz** [comment]
Sorry, I am a Git noob

**Comment by jamcat22** [comment]
Still modifies `Gemfile.lock`

**Comment by mxxcon** [comment]
Closing in favor of #1197

**Pull request closed without merging**
