### PR TITLE
Add qnap

### LINKED ISSUE #1365: QNAP (NAS)   (official build 4.2 and later)
I see that Synology is also on the list, but Qnap is missing. (If you have no idea what I am talking about: Qnap and Synology are 2 big NAS brands. Their software offers backups, file sharing, logging, web server,... all on a NAS in your home. In other words, it contains a lot of important data, and 2FA is a must for these things).
The latest build (4.2.0) allows 2 factor authentication via the google app.
Source: https://www.qnap.com/qts/4.2/en/security.php
Why I didn't make a pull request: I am worried about breaking the build (which is rule 1 in the contributing file). But I hope someone else is able to do this, so other users visiting the website can see that their QNAP device offers 2FA.

### PR DESCRIPTION
**Pull request by stephengroat**
Should close #1365

### CODE REVIEW

**Comment by stephengroat** [comment]
Will update with a fixed image later today, Google said it was 32x32

**Comment by Carlgo11** [comment]
Here's their logo in 32x32 pixels.
qnap

**Comment by stephengroat** [comment]
That should do it. thanks for the image help

**Comment by jamcat22** [comment]
Thanks for the PR @stephengroat!

**Pull request merged**
