### PR TITLE
Update sprint

### LINKED ISSUE #2864: Sprint needs updating
Sprint now uses SMS to provide customers 2FA

### PR DESCRIPTION
**Pull request by stephengroat**
fixes #2864

### CODE REVIEW

**Review by fpigerre — DISMISSED** [review]

**Comment by mxxcon** [comment]
docs site says

> You may also be required to complete the 2 step authentication process if you are making changes to your Sprint.com account, or purchasing a device either online or through Telesales.

That sounds more like 2factor authorization, not authentication?

**Comment by stephengroat** [comment]
I agree, that part is authorization. but the paragraph above seems to be authentication (to me)

>Important: If you have not logged in to your Sprint.com account for more than 6 months, you will be prompted to reset your password, which will require a two step authentication process.  You will receive a code (either by text message or email) which you will need to use to authenticate and complete the password reset process.

**Comment by jamcat22** [comment]
@stephengroat that paragraph to me suggests that another form of authentication is only used for resetting passwords, not for logging in to an account.

**Comment by Carlgo11** [comment]
I also agree with @mxxcon and @jamcat22 on that it looks like authorisation.

**Pull request closed without merging**
