### PR TITLE
Update Huntington Bank

### LINKED ISSUE #3181: Huntington Bank Supports 2fA
The website is incorrect as it states Huntington does not support 2FA.

I receive a call to my cell every time I log in.   Email OTP is also available.

thanks

### PR DESCRIPTION
**Pull request by kmpoppe**
Closes #3181
Replaces #3532

### CODE REVIEW

**Comment by Carlgo11** [comment]
While the author of #3181 states that the service supports phone and email 2FA no documentation link confirms this. That makes it rather impossible to review 😕

**Comment by kmpoppe** [comment]
Information requested via twitter.

**Comment by kmpoppe** [comment]
I received a reply from Huntington Bank that pointed me to a totally useless marketing page, that said absolutely nothing about 2FA, upon request to a real explanation on how to set up your account for 2FA I received this:
`Unfortunately we're unable to provided additional information or specifics for security reasons. Thank you.`
I'm not very inclined to pursue this matter further with that strange answer in mind.
So, what to do? I'd say leave the entry as it is (no 2FA) unless we get a screenshot-description on how to enable it. Opinions @2factorauth/collaborators ?

**Comment by Jawshy** [comment]
[These](https://www.huntington.com/SmallBusiness/online-banking/information-and-reporting) [three](https://www.huntington.com/Privacy-Security/password-security/secure-accounts) [webpages](https://www.huntington.com/Privacy-Security/prevent/cybersecurity-checklist) and this [PDF](https://www.huntington.com/-/media/pdf/privacy-security/Huntington_Cyber_Checklist.pdf?la=en) mention 2FA, but I couldn't find information about all of the 2FA options that Huntington Bank has implemented.

**Comment by Carlgo11** [comment]
Closing as we can't seem to find any proper documentation or confirmation by the business that they support 2FA.

**Pull request closed without merging**
