### PR TITLE
add booking.com

### PR DESCRIPTION
**Pull request by isotopp**

### CODE REVIEW

**Comment by Jawshy** [comment]
Travis CI log: 

```
1. Booking image not found.
```

@isotopp, the Travis CI build failed because booking.png needs to be inside img\transport not img. Also, the image file size is too large. I believe it needs to be under 2,500 bytes. You may wish to use the following image instead as it is lacks words (which are hard to read at these small sizes) and is a lot smaller in file size. 
booking

This appears to be their [official Facebook page](https://www.facebook.com/bookingcom/). Would you like to add that as well? 

``` ruby
      facebook: bookingcom
```

**Comment by Jawshy** [comment]
I also noticed that you are using the master branch on your fork. For future reference I just wanted to let you know that Two Factor Auth prefers a new branch for each site (see [CONTRIBUTING → New Sites](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#new-sites)). 

If you add "closes https://github.com/2factorauth/twofactorauth/issues/2011" the two will be associated and if this is merged the corresponding issue will be closed. Neat isn't it. (see [Closing issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/))

**Review by stephengroat — CHANGES_REQUESTED** [review]
image in the wrong directory (needs to be moved to `img/transport/`) and is the incorrect size

**Comment by Carlgo11** [comment]
I don't think I would put booking.com under transportation. Maybe `other`?

**Comment by Jawshy** [comment]
@isotopp, do you have the time to commit @stephengroat's [requested changes](https://github.com/2factorauth/twofactorauth/pull/2012#pullrequestreview-37683)? If not then this pull request may be closed.

**Comment by Carlgo11** [comment]
Closing due to #2171

**Pull request closed without merging**
