### PR TITLE
Update OneLogin

### PR DESCRIPTION
**Pull request by congriholdplantains**
Minor update to supported factors.

### CODE REVIEW

**Review by Carlgo11 — APPROVED** [review]
Looks like Travis-CI didn't receive the request for some reason. The PR looks fine however. 👍

**Comment by fpigerre** [comment]
Thanks for the pull request @congriholdplantains! 👍

**Review by stephengroat — DISMISSED** [review]
this pr is trying to merge into the `gh-pages` branch and not master.

could you please make a new pr that merges into `master`?

**Comment by fpigerre** [comment]
😮 That must have been why Travis-CI didn't receive the request properly.
Good catch @stephengroat! 👍

**Review by fpigerre — APPROVED** [review]

**Pull request merged**
