### PR TITLE
Added Office 365 and Sendloop

### PR DESCRIPTION
**Pull request by jamcat22**
See #448

### CODE REVIEW

**Comment by jamcat22** [comment]
Can someone tell me how to add a picture to my fork? Is it possible to do this on the web interface? I already searched Google and couldn't find the answer. Here are the pictures:

sendloop
office365

**Comment by mxxcon** [comment]
No, presently github does not allow uploading images. You have to use local git client to add these logos to your `patch-4` branch and then push your changes to your remote repo.

**Comment by jamcat22** [comment]
@mxxcon Well shoot. I can't get git to work on my computer. So there aren't any other ways besides git to upload img files?

EDIT: Never mind just got it to work! (This is so much easier than the web interface! How did I not know how to do this?)

**Comment by jdavis** [comment]
We can upload it for you :smile:

**Comment by mxxcon** [comment]
@jamcat22 good try, but logos gotta be 32x32 exactly..

**Comment by jamcat22** [comment]
@mxxcon Yeah just noticed that. Was trying to use GIMP 2 to scale the photos but I couldn't get it to work properly. Sorry.

Any suggestions for programs to use for resizing? (Sorry I'm such a n00b.)

**Comment by mxxcon** [comment]
@jamcat22 if you use Windows, http://www.getpaint.net/ is a pretty good choice. It's something in between overkill of Photoshop and uselessness of MS Paint. :)

**Comment by jamcat22** [comment]
Do those logos work now?

**Comment by mxxcon** [comment]
@jamcat22 sendloop logo looks squished and office logo looks blurry.
You can use these images
http://i.imgur.com/LS2ngzH.png
http://i.imgur.com/23qNiKF.png

**Comment by jamcat22** [comment]
@mxxcon How did you get them to look so great? :smile:

**Comment by jamcat22** [comment]
Ok all done.

**Pull request merged**
