### PR TITLE
Marking PersonalCapital as supporting TFA per https://www.personalcapita...

### PR DESCRIPTION
**Pull request by pc-elavassani**
Personal Capital supported TFA since inception; see https://www.personalcapital.com/safety-and-security

Please note that TFA will kick in only after user adds a financial institution.

### CODE REVIEW

**Comment by Carlgo11** [comment]
You need to move the image

**Comment by pc-elavassani** [comment]
Thanks! pushed the change to my branch.

**Comment by mxxcon** [comment]
@pc-elavassani you still have not address the question from #721

**Comment by pc-elavassani** [comment]
Are you referring to "sms or a voice call" or the image? We use voice call and the image is already there and looks ok. 

Please let me know if any other questions.

**Comment by Walkman100** [comment]
@pc-elavassani i doubt you meant to close this PR.

**Pull request closed without merging**
