### PR TITLE
Addition of sync.com

### PR DESCRIPTION
**Pull request by lgalarra**
I discovered that sync (Sync.com) also provides 2-factor authentication. Could you please add this information to the list.?

### CODE REVIEW

**Comment by RichJeanes** [comment]
Check your spacing. All indentation should be done with spaces. Tabs change depending on your platform.

**Comment by mxxcon** [comment]
As Rich mentioned, spacing is important. Also "S" does not come after "Z". :) Please try to put it in correct alphabetical position.

**Comment by fpigerre** [comment]
Hello @lgalarra,

Thanks for submitting this pull request! :+1: 
On [TwoFactorAuth.org](https://twofactorauth.org), documentation links for specific websites usually direct viewers towards a page that guides the user with regards to setting up two factor authentication.

Perhaps the following link from Sync.com's [knowledge-base](https://www.sync.com/help/https://www.sync.com/help/) might be more appropriate for the documentation link of this pull request.

[How do I setup Two Factor Authentication?](https://www.sync.com/help/how-do-i-setup-two-factor-authentication/)

Kind regards,
psgs :palm_tree:

**Comment by Carlgo11** [comment]
To summarize @psgs' comment.
Please change the `doc:` link to https://www.sync.com/help/how-do-i-setup-two-factor-authentication/

**Pull request merged**
