### PR TITLE
Other lds.org

### PR DESCRIPTION
**Pull request by ld3300**

### CODE REVIEW

**Comment by Carlgo11** [comment]
No... Just no...
This is not the place to list a religious site.

It can't possibly fit the site criteria.

**Comment by ld3300** [comment]
I'm not trying to push any religious ideas here, but the login for this site does contain personal information like full name, birthdate, membership record number, access to company email (as some members are also employees of the church corporation).  Also the logins for church leaders would expose all this information including intimate details about membership status for everyone in their congregations.  This is information that I feel matches the site criteria.  I will support your decision, but urge you to reconsider.

**Comment by Carlgo11** [comment]
I'll contact the owner of twofactorauth to get his point of view on this matter.
While we wait for his response I'll lock this PR. (I'll unlock it later when he have responded)

**Comment by mxxcon** [comment]
Carl, you are a bit over-reacting here.

**Pull request closed without merging**
