### PR TITLE
Add ManuFrog

### PR DESCRIPTION
**Pull request by cez81**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr @cez81

**Review by mxxcon — APPROVED** [review]

**Comment by gingerbeardman** [comment]
Image is pretty bad?

**Review by gingerbeardman — CHANGES_REQUESTED** [review]
Image quality is low?

**Review by Jawshy — DISMISSED** [review]
@cez81, would you like to use the following image instead? 
Edit: manufrog-v3

**Comment by cez81** [comment]
@Jawshy Thanks, much better. I have updated the PR.

**Review by stephengroat — APPROVED** [review]

**Comment by Carlgo11** [comment]
Seems like a rather small site with no big customers.

**Comment by cez81** [comment]
True,  can probably leave this one off the list.

**Comment by Carlgo11** [comment]
Closing this PR as ManuFrog is rather insignificant. Can be opened again if this is changed in the future.

**Pull request closed without merging**
