### PR TITLE
Moving SoftLayer from developer to hosting.

### PR DESCRIPTION
**Pull request by mxxcon**
SoftLayer is a hosting provider...or cloud service?...They offer both. :)

### CODE REVIEW

**Comment by philipithomas** [comment]
I have my jekyll sites set to deploy to S3 using a CI platform - if you want help integrating deployment into Travis let me know

**Comment by mxxcon** [comment]
@philipithomas i don't quiet follow you..?

**Comment by philipithomas** [comment]
I didn't look at the files and assumed this was a change to deployments :-)

**Comment by mxxcon** [comment]
@philipithomas actually the website gets built from `gh-pages` branch, not `master`. From what I read @jdavis does manual spot checks before pushing it live. It's up to him to decide. :)

**Comment by jdavis** [comment]
Yup, that is what I do just to be sure things are still okay.

I plan on "finishing" the international/exceptions stuff based on what you mentioned in #241 @mxxcon so all the changes from the last week will go through.

**Comment by mxxcon** [comment]
Is this good to merge or are we waiting for some site changes?

**Comment by jdavis** [comment]
No, we can totally merge. We might want to address the VPS/Hosting/Cloud thing though. Like you said, the line for those three are a bit blurry.

**Pull request merged**
