### PR TITLE
Add Matchbook

### PR DESCRIPTION
**Pull request by 40504**

### CODE REVIEW

**Comment by phallobst** [comment]
Were the changes to the other entries intentional?

**Comment by 40504** [comment]
Yes :)

**Comment by phallobst** [comment]
That didn't help much for _Cloudbet_, did it? Anyway, if you want to clean up, I suggest you do it in a separate PR in order to keep this one related to _Matchbook_ only.

**Comment by 40504** [comment]
Yep, by the way, "https://www.cloudbet.com/en/2_step_authentication" doesn't link to the expected destination.

**Comment by 40504** [comment]
I will create another PR

**Pull request closed without merging**
