### PR TITLE
Natwest revision

### PR DESCRIPTION
**Pull request by djrarky**
Natwest allow 2fa in their mobile app. 
They even allow you to use TouchID on iOS devices.

### CODE REVIEW

**Comment by djrarky** [comment]
WhatsApp always verify your phone via SMS before signing in.
https://www.whatsapp.com/faq/en/iphone/20902747

**Comment by Jawshy** [comment]
Hi, @StevenChorkley. Thanks for another pull request (PR). Could you please revert the WhatsApp and Costa Coffee changes as we like to have only one significant site change or addition per PR. 

You can make a new branch for each new site or updated site and then submit a pull request for each one. For more information see [here](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#new-sites). Thanks.

**Comment by djrarky** [comment]
Sure, sorry about that.

**Comment by jamcat22** [comment]
This PR is a duplicate of #2141, #2143, and #2144.

**Pull request closed without merging**
