### PR TITLE
Quickbooks now supports TFA

### PR DESCRIPTION
**Pull request by dthvt**
Quickbooks now supports 2FA using SMS, phone, and software.

### CODE REVIEW

**Comment by mxxcon** [comment]
Any doc links with this info?

**Comment by dthvt** [comment]
Sorry, didn't think to look for the doc.  I found this: https://community.intuit.com/articles/1164912-multi-factor-authentication-faq

**Comment by Carlgo11** [comment]
@dthvt I can only find support for email from what they describe on that page.
Also, add the doc to the YAML file.

**Comment by dthvt** [comment]
Well, I don't know what to say here guys.  Their documentation on their support site basically doesn't seem to mention this at all.  I found a few other threads that hint at things, but nothing like an explicit HOWTO.  

Mentions SMS support:

https://community.intuit.com/questions/1254922-how-do-i-turn-off-two-factor-authentication-my-credentials-are-secure-and-i-am-more-than-comfortable-with-having-it-off

Shows the current account management portal including TFA: 

https://community.intuit.com/articles/1266316-update-your-intuit-account-info-on-the-account-manager-

The fact that it supports SMS, Voice, & Google Auth were pulled from going into my account and setting up TFA and those being the available options.  I'm not sure what URL you think would best represent that in the YAML.

**Comment by smholloway** [comment]
I think the ideal doc link would tell a user how to enable 2FA with sections for each authentication method. https://community.intuit.com/articles/1164912-multi-factor-authentication-faq, which @dthvt already mentioned, is the best I could find with a little searching.

**Comment by mxxcon** [comment]
@smholloway ditto here. They just have this (pretty useless for our purposes) faq site. :confused:
Considering the info I think it's good enough.

**Comment by fpigerre** [comment]
Would you be able to add the documentation link to the `finance.yml` file please @dthvt?

**Comment by dthvt** [comment]
Updated.

**Pull request merged**
