### PR TITLE
Addsite.rb script finally here!

### PR DESCRIPTION
**Pull request by Carlgo11**
Big thanks to @ilyakatz for the making of this script and @psgs who assisted us. You're awesome guys :heart: 

So this ruby script adds new sites and providers to the yaml files. Hopefully this will help people not make yaml errors.
The script will also put all the sites/providers in an alphabetic order which is a solution to #837.

We feel like the script is done so I'm now making this merge request of the script branch.

If you can't tell already, I'm super excited about this :smile:

### CODE REVIEW

**Comment by ilyakatz** [comment]
and thanks to @Carlgo11 for pushing is forward!

There are a couple of things I'd like to do before we merge this
- YAML parser will reorganize current yml files (since some things are out of order and there are slight differences in formatting), so I'd like to run it for all the current files so people don't get confused 
- Add documentation on how to use it.

Anything else? Please add your comments and I'll be happy to make codes changes

**Comment by ilyakatz** [comment]
@Carlgo11 @psgs @jdavis @mxxcon @jamcat22 @dsoegijono can you please take a look at this and let me know if you have any concerns. please, please check out the branch locally and give it a try.

since there are formatting changes, i'd like to not have this PR live for too long to avoid conflicts in yml files

much obliged.

**Comment by fpigerre** [comment]
Wow, awesome work @ilyakatz!! I'll take a look and test this locally right away. :smiley:

**Comment by mxxcon** [comment]
@ilyakatz 
I don't know Ruby so wouldn't be able to tell you if your code is good/bad.

It would be nice to separate the script from updating all the yml files into separate PRs so we can deal with them independently.

I don't like that all `Yes` are switched to `true`. Yes, it's Boolean, but `Yes` is more natural English, which is the point of using yml in the 1st place.

Also it seems like line breaks have been removed from all entries, making it harder to read raw files.

**Comment by ilyakatz** [comment]
Thanks for your comment, @mxxcon. Want to learn ruby? It's a fun language ;)
- ok, i can separate the script from file updates, no problem.
- it is possible to keep Yes and No with a little bit of work - ruby parser reads Yes as true. I didn't think it was a problem since those who choose to update yml files still need to be at least a little bit tech savvy (even if just to fork and do a github PR)
- yes, so far I couldn't find a way to add line breaks when outputting the file, if this is a deal breaker, I will do more research

**Comment by jdavis** [comment]
Sorry for the delay everyone. I'm taking a look at this now.

**Comment by jdavis** [comment]
Comments:
1. +1 to the `Yes`  vs `true` in Yaml that @mxxcon mentioned.
2. To get rid of this commit 3f011fbe4c4259725dd4b68c2f4888e6f419197f, just do this while on the `script` branch: `git rebase jdavis/master`. Rebase is the best way to essentially put all your commits that differ from the given branch on top of the current branch.
3. Also, since you revert two different commits, you can run `git rebase --interactive jdavis/master` instead of the previous command and be sure to remove the original and reverted commits.

Once you do those, let me know and we'll go from there =D Also, don't worry about fixing up merge conflicts (besides the `true` vs `Yes` issue). Once we figure it out, I'll be able to handle that and do a manual merge.

**Comment by ilyakatz** [comment]
Ok, I'll look into what is needed to update yes/false. `Yes` and `No` are reserved words in YAML (http://www.yaml.org/refcard.html) so currently it works by internally translating those words into booleans. So when I use yaml parser to spit them out back into a file, it will use boolean values. One option is to add quotes around Yes/No, but that will break the code like  `{% if website.twitter %}`, so I will need to change that

**Comment by Carlgo11** [comment]
My opinion is that `true`/`false` fits better. Everyone else uses `true`/`false`.
Having `Yes`/`No` here just makes it trickier to add lines since the normal rules don't seem to apply in our project.

**Comment by ilyakatz** [comment]
Ok, I updated the script to spit out yes/no (in quotes, otherwise yaml converts it back to true/false, as described above). Could you guys test it out please

**Comment by Walkman100** [comment]
I think [Carlgo11](#issuecomment-64872130) raises a valid point about boolean values.

**Comment by ilyakatz** [comment]
I'm certainly in favor of true/false. However, you guys deals with committers much more, so if you think that community involvement will decrease if we use booleans, I would not object. 

@mxxcon @jdavis do you think that our committers do not understand booleans? 

P.S. Actually, I broke stuff with my last commit so don't test it yet. But I'd rather not do any more work before we agree boolean/words issue

**Comment by mxxcon** [comment]
@ilyakatz It's hard to say...Some make perfect PRs on the 1st try, while others need to make 4 different PRs because they keep botching it...or can't do it at all.
I don't think we have enough commit traffic to accurately state one way or the other. :disappointed:

So your issue is that after yaml files get chewed by your script, output will be `true/false` instead of `yes/no`?

**Comment by ilyakatz** [comment]
@mxxcon I can create an override such that all true/false values are converted to yes/no, the question is whether we want to do this since boolean is more correct. looks like we have a tie on preferences, so I would like to consider our audience.

if there is a continued tie, i will go ahead with yes/no to have less of an impact. we can revisit this later. i will need to refactor some code since current code assumes that the values are boolean (after they are parsed. eg [here](https://github.com/jdavis/twofactorauth/blob/master/index.html#L72))

**Comment by ilyakatz** [comment]
ok, I updated the code so that "yes/no" is used. however, i also added a fallback for true/false since if someone doesn't put quotes around "yes" or "no" it will be interpreted as true/false. 

how does everyone feel about this?

**Comment by ilyakatz** [comment]
note on the code, the last commit [https://github.com/jdavis/twofactorauth/commit/b16f8b4b54b2495b8c760733c4ab7226a4cf6ab9] is not as pretty as i hope it could make it to be, but looks like jekyll on github is very limited in terms of plugins you can add, so i could not add my own code to make it cleaner

**Comment by jdavis** [comment]
Hmm... I don't know if I prefer that option. I know @mxxcon had mentioned it and I agreed, but I really though that it would be easier. Sleuthing around it doesn't look like it is that straight forward to output `Yes/No` instead of `true/false`. How about we just go with true and false for simplicity sake?

**Comment by mxxcon** [comment]
Yes, quoting yes/no would make things needlessly complex.
So much effort by Ilya only to revert back to true/false? :disappointed_relieved:

**Comment by ilyakatz** [comment]
Ok, i'll go back to true/false. It was a good try

**Comment by Carlgo11** [comment]
I'm voting for sending @ilyakatz some cake when we're done with this.

**Comment by ilyakatz** [comment]
Ok, we're back to true/false. See if you like it. I think you guys deserve a cake more than I do because you're on the front lines a lot more taking all those pull requests :)

Anywho, please let me know what other changes you'd like me to make, if any

**Comment by Carlgo11** [comment]
Well are we done then? Who gets the honor of merging? :smile:

**Comment by ilyakatz** [comment]
## Did you guys try it out? I mean, I trust myself that it works, but “trust but verify” … ;)

PGP Key https://onename.io/katzmopolitan https://onename.io/katzmopolitan

**Comment by jdavis** [comment]
Let's not merge this yet, I'll give it one more review and do so.

**Comment by ilyakatz** [comment]
what's the verdict?

**Comment by jdavis** [comment]
@ilyakatz Still working through it =]

**Comment by jdavis** [comment]
Comments incoming.

**Comment by Carlgo11** [comment]
It's New Years eve josh, enjoy Seattle and not GitHub for a moment 😋 :fireworks:

**Comment by jdavis** [comment]
can't stop won't stop

**Comment by Carlgo11** [comment]
:+1:

**Comment by Walkman100** [comment]
Not sure where to put this, but since it's a ruby script:
https://travis-ci.org/jdavis/twofactorauth/builds/46014958#L196
I noticed the `verify.rb` script outputs an error if it finds a tab character, but it says

> found a tab character that violate in<b>t</b>en<b>d</b>ation

I'm pretty sure that's spelled wrong. I would've opened a PR, but I couldn't find `intendation` in `verify.rb` :confused:
Not that it's a big deal :stuck_out_tongue:

**Comment by ilyakatz** [comment]
hey folks, i will take a look at all the comments in the next few days. @Walkman100 the intendation is somewhere deep in the yaml library code :)

**Comment by Walkman100** [comment]
Ah okay. As I said, not a big deal, so never mind then

**Comment by Carlgo11** [comment]
Uhm so is this ready to be merged?

**Comment by jdavis** [comment]
@Carlgo11 As @ilyakatz mentioned, we are going to address the things I brought up and then it should be ready to merge.

**Comment by ilyakatz** [comment]
Hey guys, I'm finding it hard to find spare time to do open source work. Is there anyone who would be willing and able to help me finish this stuff off, if it's still relevant.

**Comment by mxxcon** [comment]
What about this branch then?

**Comment by Carlgo11** [comment]
Let me clone it tomorrow morning and then I can remove it.

Now Carlgo11 is Carlgone11 #bed #6am :zzz:

**Pull request closed without merging**
