### PR TITLE
Added FollowMyHealth

### PR DESCRIPTION
**Pull request by jamcat22**
Added FollowMyHealth to Health.
See #1046.

[Review on Reviewable](https://reviewable.io/reviews/jdavis/twofactorauth/1257)

### CODE REVIEW

**Comment by Carlgo11** [comment]
So they support Google, Yahoo and Microsoft authentication. 3 of 5 of the login methods supports some sort of TFA.

**Comment by Carlgo11** [comment]
Oh and please use your own fork for hosting the PR branches.

**Comment by jamcat22** [comment]
@Carlgo11

> So they support Google, Yahoo and Microsoft authentication. 3 of 5 of the login methods supports some sort of TFA.

Yes. And their own authentication supports email, sms, and software.

> Oh and please use your own fork for hosting the PR branches.

Sorry. When I did this at like 2am I didn't realize it was creating the branches on the main site instead of my fork.

**Comment by Carlgo11** [comment]
Whops, I must have mixed up the PRs. I thought this PR had `tfa: No`

**Comment by jamcat22** [comment]
So `looks-good`?

**Comment by mxxcon** [comment]
Less ugly logo? clipboard01

**Comment by Carlgo11** [comment]
It's pretty ugly in it's original form too, to be honest.

**Comment by mxxcon** [comment]
Perhaps use my logo, otherwise :+1:

**Comment by Carlgo11** [comment]
Your logo is still better than the one currently in the PR.
I just mean that the one who designed the logo should be fired :wink:

**Pull request merged**
