### PR TITLE
Changed social icons to 32x32

### PR DESCRIPTION
**Pull request by helwy**
Also modified the Reddit Icon, should I add it or keep the other one?
untitled

### CODE REVIEW

**Comment by zach-taylor** [comment]
Hi @HElwy there are some thumbs.db files that should not be in there. Otherwise, it looks great!

**Comment by helwy** [comment]
@zach-taylor should I make a new issue without them?

**Comment by jdavis** [comment]
You can always update this pull request and remove them.

**Comment by helwy** [comment]
@jdavis better?

**Comment by jdavis** [comment]
Yes, that's perfect. Great job, @HElwy.

**Pull request merged**
