### PR TITLE
Add Nordea Finland & fix Nordnet (FI) name

### PR DESCRIPTION
**Pull request by Carlgo11**

### CODE REVIEW

**Review by kmpoppe — APPROVED** [review]

**Review by jamiehowarth0 — APPROVED** [review]

**Comment by Carlgo11** [comment]
@jamiehowarth0 Your approval doesn't actually do anything.
Only maintainer approvals are counted.

**Comment by jamiehowarth0** [comment]
@Carlgo11 Sorry - was trying to be useful

**Comment by Carlgo11** [comment]
@jamiehowarth0 No worries 🙂

**Comment by jamiehowarth0** [comment]
@Carlgo11 is there a way I can apply to become a maintainer? There's a few PRs I'm happy reviewing in my spare time

**Review by phallobst — APPROVED** [review]

**Pull request merged**
