### PR TITLE
Adding RingCaptcha as provider

### PR DESCRIPTION
**Pull request by mcocaro**
-> twofactorauth git:(master) ✗ bundle exec rake verify
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby ./verify.rb
No errors. You're good to go!

### CODE REVIEW

**Comment by smholloway** [comment]
Can you point me to the docs that mention how RingCaptcha is used as a 2FA provider? I can't find any reference to authentication on the site.

**Comment by mxxcon** [comment]
@smholloway see https://my.ringcaptcha.com/docs/web `Launching a Verification widget`
@mcocaro your https://my.ringcaptcha.com/docs/api requires login. :disappointed:
Also do you provide 2fa _client_? Or is it all done over sms/phone call?

**Comment by mcocaro** [comment]
@mxxcon yes, the api docs are closed for logins only who use the rockstar plan (outside the US/CA free tier). It is only via SMS/Phone. 

@smholloway RingCaptcha provides a turnkey solution to integrate the 2-step-verification process (generates the pin code, sends an SMS/Voice to the phone number, validates the pin code entered) into any website, mobile app or API in general. It is compatible with Google Authenticator as it allows pin code over-writes.

**Comment by mxxcon** [comment]
If it's only sms/phone, then remove `software: yes` tag.

**Comment by mcocaro** [comment]
@mxxcon done!

**Comment by mcocaro** [comment]
@mxxcon @smholloway RingCaptch API docs do not require login now -> http://my.ringcaptcha.com/docs/api

is there anything else you'd like me to change in the PR?

**Comment by Carlgo11** [comment]
@mcocaro add the doc link then. `doc: http://my.ringcaptcha.com/docs/api`

**Comment by Carlgo11** [comment]
@mcocaro Add the doc please

**Comment by mcocaro** [comment]
@Carlgo11 Done! Thanks for the reminder, I had it on my other machine but never pushed the change.

**Comment by jamcat22** [comment]
Your PR was merged. You can find out what happens next on our [wiki](https://github.com/jdavis/twofactorauth/wiki/FAQ_Merge).

**Pull request merged**
