### PR TITLE
Add Paragon

### PR DESCRIPTION
**Pull request by Nicos18**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]

**Review by mxxcon — COMMENTED** [review]
How does this site fit into our https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria?

**Comment by Nicos18** [comment]
@mxxcon I think that it fits, because on that site are stored all of the license of the Paragon Software, and if someone stole the licenses, I would have problem with them

**Comment by mxxcon** [comment]
Does it also store your billing info like credit cards?
I'm thinking perhaps software licenses are not so sensitive? Paragon could always re-issue if a security incident were to happen... 🤔

**Comment by Nicos18** [comment]
@mxxcon it seems that it doesn't store billing info on the account, and that to make a purchase, it brings to a subdomain of paragon website

**Review by jamcat22 — CHANGES_REQUESTED** [review]
Doesn't seem to align with site criteria for being listed. If they supported 2FA, I could see arguing for listing them. Feel free to comment if anyone has another opinion.

**Comment by jamcat22** [comment]
Closing due to inactivity.

**Pull request closed without merging**
