### PR TITLE
Add detectify

### PR DESCRIPTION
**Pull request by thegeekkid**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]

**Comment by stephengroat** [comment]
thanks for the pr @thegeekkid!

**Comment by thegeekkid** [comment]
No problem!  Sorry about the extra spaces... that's what I get for not using vim.  Lol!

**Comment by Carlgo11** [comment]
psst @stephengroat, don't forget the `looks-good` label.

**Comment by Jawshy** [comment]
... and `new site`. :wink:

**Comment by JaneX8** [comment]
They do support HOTP/TOTP now.

**Pull request merged**
