### PR TITLE
Small svg

### PR DESCRIPTION
**Pull request by person1234-ux**

### CODE REVIEW

**Comment by person1234-ux** [comment]
did I just run all the svg files through a script that shrinks them. The answer to that question is yes

**Comment by phallobst** [comment]
Nobody is going to review 1200+ icons. As long as there is no _significant_ improvement in file size for some image, this PR is of not much use, I suppose.

**Comment by person1234-ux** [comment]
lots of insignificant changes bundled together make a significant change

**Comment by person1234-ux** [comment]
> Nobody is going to review 1200+ icons. As long as there is no _significant_ improvement in file size for some image, this PR is of not much use, I suppose.

Ok I will try to see if I can modify the script to only include significant changes.

**Pull request closed without merging**
