### PR TITLE
Add Mastodon

### PR DESCRIPTION
**Pull request by mabkenar**

### CODE REVIEW

**Review by stephengroat — CHANGES_REQUESTED** [review]
@mabkenar could you move the logo from `img/cloud` to `img/social`?

**Review by stephengroat — APPROVED** [review]
thanks for the work @mabkenar

**Review by Jawshy — APPROVED** [review]
Sorry for the delay.

**Comment by rugk** [comment]
@Jawshy BTW your work has been removed in without any real reason.

**Pull request merged**
