### PR TITLE
Adds HMRC

### PR DESCRIPTION
**Pull request by grahamlicence**
Adds HMRC online services (UK Gov tax)

### CODE REVIEW

**Comment by mxxcon** [comment]
hmrc
This logo is favicon from that website.

**Comment by RichJeanes** [comment]
Thanks for contributing! Did you try optimizing that logo? I was able to almost halve the file size just using pngcrush. Could you please use this version instead?
hmrc
@mxxcon They do use the black on white circle logo on the page itself. The white on black crown appears to be the site-wide UK government logo.

**Comment by grahamlicence** [comment]
Will do, added

**Comment by Carlgo11** [comment]
I think HMRC would fit better in the `other` category as IRS is there.

**Comment by grahamlicence** [comment]
Would IRS not be better under finance?

**Comment by Carlgo11** [comment]
No. We'll probably create a separate section for ministries/agencies at a later date but as of right now `other` is the best fitting one.

**Comment by grahamlicence** [comment]
OK moved to other

**Comment by Carlgo11** [comment]
Thank you :smile:

**Comment by RichJeanes** [comment]
Thank you for contributing! Your changes have been merged into the main branch but will not appear on the live website until the `master` branch is merged into the `gh-pages` branch, which happens periodically. There is nothing left here for you to do.

**Comment by gingerbeardman** [comment]
Had there really been no merge since July 2016?

**Comment by Carlgo11** [comment]
Check again. It looks there to me

**Comment by gingerbeardman** [comment]
My mistake @Carlgo11 

HMRC now support 2FA so I will update their entry!

**Pull request merged**
