### PR TITLE
Added FreeAgent

### PR DESCRIPTION
**Pull request by eddiejaoude**
No TFA :(

### CODE REVIEW

**Comment by Carlgo11** [comment]
Change `name:` to FreeAgent

**Comment by eddiejaoude** [comment]
Updated name

**Comment by Carlgo11** [comment]
:+1:

**Comment by mxxcon** [comment]
Perhaps instead of `other` category, it's suited for `finance` or `payments`?

**Comment by Carlgo11** [comment]
I think finance would fit best

**Comment by eddiejaoude** [comment]
Sure. I will move it to finance

**Comment by eddiejaoude** [comment]
Moved

**Comment by Carlgo11** [comment]
Okay looks good to me

**Pull request merged**
