### PR TITLE
Lossessly optimized all images

### PR DESCRIPTION
**Pull request by mxxcon**
Also updated a couple of ugly and old ones.

### CODE REVIEW

**Review by Jawshy — COMMENTED** [review]
I like how some of these images have already been compressed; [[1]](https://github.com/mxxcon/twofactorauth/commits/d8be6e6d645ab2d35de189c9a6cc3c177ba4de3a/img/backup/backblaze.png), [[2]](https://github.com/mxxcon/twofactorauth/commits/d8be6e6d645ab2d35de189c9a6cc3c177ba4de3a/img/backup/box.png), [[3]](https://github.com/mxxcon/twofactorauth/commits/d8be6e6d645ab2d35de189c9a6cc3c177ba4de3a/img/backup/crashplan.png). 😄 

The think that [Okta](https://www.okta.com/)'s [image](https://github.com/mxxcon/twofactorauth/blob/d8be6e6d645ab2d35de189c9a6cc3c177ba4de3a/img/identity/okta.png) should be on a white background (see their favicon). 

Other than the above this looks good (I didn't check the "Diff not rendered." images because then I would be here all night.)

**Comment by mxxcon** [comment]
Constantly improving compression tools allow to squeeze out more bytes.

**Comment by RichJeanes** [comment]
How much data did this actually cut? (Just curious)

**Comment by mxxcon** [comment]
1,010,687 vs 931,727
~80KB

**Comment by mxxcon** [comment]
Recreated PR in #2727

**Pull request closed without merging**
