### PR TITLE
Remove Hardware Token from Fidelity Investments

### PR DESCRIPTION
**Pull request by ghost**
I was just on the phone with a rep and he mentioned that they don't support hardware tokens, just the Symantec VIP shovelware.

### CODE REVIEW

**Comment by jamcat22** [comment]
Hello @ainola!

Did they say they wouldn't send a hardware token, or they wouldn't add an existing one?
Credential IDs for the software token and the hardware token are the same format, so even if they don't sell the hardware tokens anymore, you should be able to add one to your account.

**Comment by ghost** [comment]
They wouldn't send one. They said they only support the apps. But I guess it sounds like one could just call them up and give the serial to them anyway.

**Comment by Carlgo11** [comment]
Yup I think an exception isn't needed as it seems like one could just buy a hardware token from another place and give them the serial number.

**Comment by ghost** [comment]
Feel free to close, then!

**Pull request closed without merging**
