### PR TITLE
Stripe added U2F support

### PR DESCRIPTION
**Pull request by pifantastic**
Stripe now supports U2F for 2FA :)

### CODE REVIEW

**Comment by stephengroat** [comment]
thanks for the update @pifantastic. Do you know when the `doc` linked to stripe will be updated?

**Comment by pifantastic** [comment]
@stephengroat Hopefully today but definitely this week. I'm happy to follow up here once it's published.

**Comment by stephengroat** [comment]
thanks @pifantastic. a follow up would be great when the `doc` is updated!

**Comment by pifantastic** [comment]
@stephengroat the docs have been updated! 

https://support.stripe.com/questions/how-do-i-enable-two-step-verification#u2f

**Review by stephengroat — APPROVED** [review]
thanks for the pr and the work @pifantastic!

**Review by jamcat22 — APPROVED** [review]

**Comment by jamcat22** [comment]
Thanks @pifantastic! Your PR has been merged. You can find more information on what happens after a PR is merged and when changes go live on our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge).

**Pull request merged**
