### PR TITLE
Added Poloniex [Cryptocurrencies]

### PR DESCRIPTION
**Pull request by MickD**

### CODE REVIEW

**Comment by stephengroat** [comment]
@MickD thanks for the fix

**Comment by MickD** [comment]
No problem, added 1 more edit.

**Comment by Carlgo11** [comment]
@MickD please make one change per PR.

**Comment by MickD** [comment]
Sorry about that, I thought it would create a 2nd. So cancel this one and create a new one?

**Comment by Carlgo11** [comment]
That or remove the latest commit from the PR.

**Comment by stephengroat** [comment]
back to one commit and `looks-good`

**Comment by Jawshy** [comment]
I read the linked documentation on their support centre and I [couldn't find where it said two-factor authentication over email](https://poloniex.freshdesk.com/support/search/solutions?term=email&authenticity_token=fEUf%2BZDnQK8rTdSDgzxk0lacXHcgYvsHvCr0%2FwejlDA%3D) is supported. I could only find the [software token 2FA support](https://poloniex.freshdesk.com/support/solutions/articles/1000225338-how-do-i-to-setup-two-factor-authentication-).

**Comment by Jawshy** [comment]
> Sorry about that, I thought it would create a 2nd. So cancel this one and create a new one? 

@MickD, the best way to do that is to create a new branch for each new site added, removed, or changed. That way you can submit a new pull request for each site/branch. (See [CONTRIBUTING.md → New Sites](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#new-sites))

**Comment by MickD** [comment]
@Jawshy 
https://poloniex.freshdesk.com/support/solutions/articles/1000166423-how-do-i-withdraw-my-coins-
"Click the Withdraw button and confirm your withdrawal using the email we send"

**Comment by Jawshy** [comment]
@MickD, so email confirmation is only used for withdraw authorisation; not for login authentication? 

I ask because the people at Two Factor Auth define two-factor authentication "as any service provided as a redundant layer for account authentication." Not to be confused with authorisation such as of withdraws. See [CONTRIBUTING.md → A Note on Definitions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions).

**Comment by MickD** [comment]
I disagree with this definition. In our case, although you don't need to set up 2FA to create an account - lowering the bar to entry - until you have 2FA enabled on your account you need to authorize all sensitive actions via email. Just because this authentication step happens at a later time, doesn't make it any less valid as a "redundant layer for account authentication."

**Comment by stephengroat** [comment]
I think it's OK to add if the `email: Yes` tag is removed since email is used only for transaction auth but TOTP is used for login auth.

@Carlgo11, what do you think?

**Comment by Carlgo11** [comment]
No. Authorization not authentication.

**Comment by stephengroat** [comment]
signed up for an account. the TOTP is authentication, every time

**Pull request closed without merging**
