### PR TITLE
master

### PR DESCRIPTION
**Pull request by warlight**
adding provider TeddyID (teddyid.com)

### CODE REVIEW

**Comment by mxxcon** [comment]
What is this pull request?

**Comment by Carlgo11** [comment]
Junk.

**Comment by warlight** [comment]
What's wrong?

**Comment by mxxcon** [comment]
@warlight your pull request has no title, you submitted it into a branch rather than master, your clone is not up-to-date with the upstream repo.

It looks like you tried to submit teddyid? #887 already has that.

**Comment by warlight** [comment]
But #887 has no image. That is because it was cancelled.
I'm new at Github and working with git. Can you help me - describe the sequence of actions to add TeddyID on https://twofactorauth.org/?

**Comment by mxxcon** [comment]
Everything was fine about that pull request other than the missing logo, which you could've easily added.
Are you using some sort of github GUI client or command line?

**Comment by warlight** [comment]
I use intellij IDEA + Git Bash
#887 has no logo, but #889 has it, yes? I need to comment it in IDEA when I pull request, yes?
Now I need to repeat action but with comment?

**Comment by mxxcon** [comment]
you need to pull branch `patch-1` from YOUR repo. Then you need to add logo while still in `patch-1` branch. The you need to commit the added file. Then you need to push your local repo to github. If you do that properly, your added logo will automatically show up in #887

**Pull request closed without merging**
