### PR TITLE
Add Neolo

### PR DESCRIPTION
**Pull request by fainpablo**
While they don't specify the available methods in the documentation, they confirmed over email that any TOTP generator app is compatible. No hardware accepted yet.

### CODE REVIEW

**Comment by phallobst** [comment]
This page actually references _Google Authenticator_, but is about the "cPanel" account. I have no idea if this might be a better doc link.
https://c.neolo.com/knowledgebase/166/iComo-configurar-la-autenticacion-de-dos-factores.html

**Comment by fainpablo** [comment]
That's for accessing cPanel, as you mentioned. The one I'm talking about is the client area, where you can add or remove services to/from your account, manage payment methods, launch cPanel, etc.

I'm not quite sure whether we should add cPanel or not. I would say no because we may need to do the same for other hosting providers (like GoDaddy, Namecheap, etc.), and the URL of the cPanel is usually tied to the user domain or the server itself. Example: https://a2plcpnl0321.prod.iad2.secureserver.net:2083

What do you think?

**Comment by phallobst** [comment]
I think we can be reasonably sure that Neolo uses TOTP. Leave the doc page as it is, then.

**Comment by phallobst** [comment]
Maybe change the icon to this one? That is what they use as their favicon as well.
neolo

**Comment by fainpablo** [comment]
Done! ;)

**Review by phallobst — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
