### PR TITLE
Update developer.yml

### PR DESCRIPTION
**Pull request by HiDeveloperDev**
https://www.dropbox.com/s/fmxc00cqmqhi844/sec-logo.png

### CODE REVIEW

**Comment by mxxcon** [comment]
@HiDeveloperDev can you explain why it fits into `developer` category?

**Comment by jdavis** [comment]
Would you be able to clean up these issues, @HiDeveloperDev? I'm referring to #646, #647, and this one.

Also, what does SecSign do? Like @mxxcon  mentioned, an explanation would be great.

**Comment by HiDeveloperDev** [comment]
Hi JDavis,

Sorry for delay in response.

SecSign is a two-factor authentication developer, that offers free API for wordpress, Joomla, Java, .net, Perl, and now fingerprint for iOS 8.

Shouldn't it be "SecSign", caps matter? No it Shouldn't  matter
Also logo is missing..=====> I was not able to upload image in git i added it in droptbox. https://www.dropbox.com/s/fmxc00cqmqhi844/sec-logo.png

Thanks Again
Dev

**Comment by mxxcon** [comment]
> SecSign is a two-factor authentication developer, that offers free API for wordpress, Joomla, Java, .net, Perl, and now fingerprint for iOS 8.

Just because somebody offer an API, **I** don't think it fits into developer category. Compare to all the other entries there and see how different it is from SecSign.
SecSign it not targeted primarily at developers. It's primary user base are regular users..

> Shouldn't it be "SecSign", caps matter? No it Shouldn't matter

All over their website it's listed as "SecSign" and not "secsign".

**Comment by HiDeveloperDev** [comment]
Ok Ok 

Can you suggest category please -i will add there - yes name is SecSign

Thanks
Dev

**Comment by mxxcon** [comment]
You already created PR #647 which adds it to the providers category, which I think is good enough.

I will close this PR and PR #646 since it does not seem to fit into backups category.

**Comment by HiDeveloperDev** [comment]
ok ok 

Thanks

**Pull request closed without merging**
