### PR TITLE
Update ProtonMail

### PR DESCRIPTION
**Pull request by 40504**
https://protonmail.com/blog/protonme-domain/

### CODE REVIEW

**Comment by Carlgo11** [comment]
As the auth system will still only be on protonmail.com I don't think these domains are useful to add.

**Comment by 40504** [comment]
when is suitable to add them?

**Comment by phallobst** [comment]
While `additional-domains` are certainly useful for password managers, they also act as search keywords. I'd say add them anyway.

**Comment by 40504** [comment]
Ok, I get it, thank you for the explanations. You know better what to do with this PR :)

**Comment by Carlgo11** [comment]
@40504 as Michael mentioned, the additional-domains element is primarily meant for third party apps like password managers.
While we also use it for our search field on 2fa.directory I doubt anyone would search for these specific domains as they are only meant to handle SMTP traffic and anyone trying to access the domains through HTTP/HTTPS would be redirected to the primary domain, protonmail.com.

**Pull request closed without merging**
