### PR TITLE
Added StatusCake and Zapier (under Developer)

### PR DESCRIPTION
**Pull request by ahelpingchip**
StatusCake is a website uptime monitoring tool.
Zapier is an API/platform automation tool.

### CODE REVIEW

**Comment by mxxcon** [comment]
What are `doc` urls that talks about these sites' 2fa offering?

**Comment by ahelpingchip** [comment]
Zapier does not have 2FA.

StatusCake does have 2FA, but doesn't have any publicly accessible documentation that I can find.
- Should I just link directly to the settings page URL? (though you'd need an account)
- Should I just tweet asking about it, and link to their reply (if they do, hopefully)

**Comment by jdavis** [comment]
Ugh. Do you know anyone at StatusCake by chance? It might be worth it to reach out to them to update their documentation.

How do you know they have 2FA? I'm assuming you use it?

**Comment by ahelpingchip** [comment]
Yup, I do use it, but I don't personally know anyone there.

I decided to check if they had 2FA under my account settings, and surprise, it was there. Google did not find any mention of it anywhere.

**Comment by jdavis** [comment]
K, I'll merge them for now.

**Pull request merged**
