### PR TITLE
Token2 icon and data

### PR DESCRIPTION
**Pull request by token2**

### CODE REVIEW

**Comment by mxxcon** [comment]
You need to re-sync your fork with this repo, otherwise every pull request you'll make will have merge conflicts.

**Comment by token2** [comment]
@mxxcon , just checked again the master branch, says "jdavis:master is up to date with all commits from token2:master. " but when with patch-5, for example, the order is different

**Comment by mxxcon** [comment]
Are you copy/pasting the whole previously edited file or just add Token2's data into appropriate place?

**Comment by token2** [comment]
@mxxcon , yes I am copy pasting, shall I try editing in-place?

**Comment by mxxcon** [comment]
>  just checked again the master branch, says "jdavis:master is up to date with all commits from token2:master. "

That's your problem. you are comparing it backwards. Obviously `jdavis:master` will be up to date with your repo because it's more current.
If you simply go to https://github.com/token2/twofactorauth you'll see that it says

> This branch is 245 commits behind jdavis:master

Also do not copy/paste previously edited file because your copy is an old version. You need to make changes only relevant to Token2 entry.

**Comment by token2** [comment]
@mxxcon , clear now, thanks

**Comment by token2** [comment]
Closed #715, #716 should be fine, can you have a look?

**Pull request closed without merging**
