### PR TITLE
Add Deputy

### PR DESCRIPTION
**Pull request by ApCoder123**

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]

**Comment by phallobst** [comment]
Crikey! The icon looks like it has been designed with a chainsaw when you zoom in. The curves are totally rugged.

**Comment by ApCoder123** [comment]
Okay, I've cleaned it up a bit

**Review by phallobst — CHANGES_REQUESTED** [review]
This entry should rather go into the "Task" category.

**Review by phallobst — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
