### PR TITLE
Add Riot Games

### PR DESCRIPTION
**Pull request by sn00py1310**
Discussesd in #6312.

### CODE REVIEW

**Comment by Carlgo11** [comment]
LoL is already listed so that would need to be removed before this can be merged.

**Review by Carlgo11 — DISMISSED** [review]

**Comment by phallobst** [comment]
Do we really want to remove LoL which has 2FA support (albeit email only) and "hide" it in this entry without 2FA?

**Comment by Carlgo11** [comment]
@phallobst The auth system for LoL is the same as Riot Games so it's not actual 2FA but 2SV.

**Review by dsoegijono — COMMENTED** [review]
Looks like they've added it now? https://www.riotgames.com/en/news/multi-factor-authentication-has-arrived

**Comment by sn00py1310** [comment]
I used the Valorant documentation link because they have a different support page for every game, but the content seems to be the same.

**Review by phallobst — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
