### PR TITLE
Add Registro.br two factor authenticator

### PR DESCRIPTION
**Pull request by euivanw**
Alter for add Registro.br (Brazilian Company) in category Domains.

### CODE REVIEW

**Comment by RichJeanes** [comment]
You need to fix line 259 in that commit. Accidentally added a stray 'd' to Mint's entry.

**Comment by euivanw** [comment]
Corrected!

**Comment by RichJeanes** [comment]
Don't forget to commit the corrections to your branch!

**Comment by RichJeanes** [comment]
Seems to be duplicated with #147. Closing this PR for the sake of tidiness.

**Pull request closed without merging**
