### PR TITLE
Added Cloudshards and CrazyDomains

### PR DESCRIPTION
**Pull request by ramo-j**
Added Cloud shards to developers and crazydomains to domains.

It might be wise to create a separate section for hosting? Cloudshards would go there, as would things like AWS, rackspace, azure, and probably others.

### CODE REVIEW

**Comment by computmaxer** [comment]
I like the idea of moving some of them into a hosting section. @jdavis what do you think?

**Comment by jdavis** [comment]
@computmaxer I've been thinking about a Hosting section for awhile now. The hard part is that the dichotomy isn't exactly perfect. A lot of hosting sites offer domains and a lot of domain sites have hosting.

**Comment by RichJeanes** [comment]
Bump.
Any thoughts on this? I will say, the Developer and Domain sections seem to be getting a little out of control, not to mention Finance.  I can't even get the whole Finance list in one screen anymore.

**Comment by jdavis** [comment]
Yeah, we should break things up a bit.

**Pull request merged**
