### PR TITLE
Add Sparkasse [Banking]

### PR DESCRIPTION
**Pull request by Jawshy**
#### Changes:
- Added: [Sparkasse](https://www.sparkasse.de/) under banking. 
  - No TFA. [Twitter handle](https://twitter.com/sparkasse). [Facebook page](https://www.facebook.com/sparkasse). 

Closes https://github.com/2factorauth/twofactorauth/issues/2058.

### CODE REVIEW

**Review by stephengroat — CHANGES_REQUESTED** [review]
`lang: de` tag?

**Comment by Jawshy** [comment]
Thanks for reminding me, @stephengroat.

**Review by stephengroat — APPROVED** [review]

**Comment by Carlgo11** [comment]
Found an email address for them. `email_address: sparkasse@sparkassen-finanzportal.de`

**Comment by Jawshy** [comment]
Boom! Added.

**Comment by Carlgo11** [comment]
Boom Merged.

:wink:

**Pull request merged**
