### PR TITLE
Updated Mint

### PR DESCRIPTION
**Pull request by rworsnop**
They now have 2fa by email

### CODE REVIEW

**Comment by mxxcon** [comment]
I don't see where to enable it...

**Comment by rworsnop** [comment]
It's mandatory on my account, so there's nothing to enable or disable. Maybe they are rolling it out gradually so not all accounts see it yet.

I just tried TurboTax (already up-to-date on your site) and they have the same arrangement - I couldn't log in without using a code they'd emailed to me.

**Comment by jamcat22** [comment]
All Intuit products (except Mint Bills) have been migrated to Intuit Accounts. 2FA was only enforced on TurboTax's website, but now it is enforced on all websites using Intuit Accounts.

You can enable 2FA on your Intuit account at [this link](https://accounts.intuit.com/account-manager.html).

All Intuit products (except Mint Bills) support:
- Email (which is mandatory and only occurs when logging in to a new device)
- SMS or Phone Call (which is optional and occurs during every login)
- Google Authenticator (which is optional, requires a valid phone number, and occurs during every login)

screenshot_011316_091553_pm

**Comment by jamcat22** [comment]
@rworsnop Could you change the following:
- Remove the `twitter:` line (It's not needed for websites that provide 2FA.)
- Add `sms: Yes`
- Add `phone: Yes`
- Add `software: Yes`

**Comment by mxxcon** [comment]
Hmm, but my intuit account and mint accounts are separate..

**Comment by jamcat22** [comment]
They should have the same password. Try logging in to the [account manager](https://accounts.intuit.com/account-manager.html) with your Mint password.
Intuit began merging Mint accounts with Intuit IDs about 8 months ago.

These FAQ links should help. Figuring out a way to allow 2 FAQ links rn...
https://community.intuit.com/articles/1248382-multi-factor-authentication-faq
https://community.intuit.com/articles/1266316-update-your-intuit-account-info-on-the-account-manager-

**Comment by rworsnop** [comment]
Wow, what a convoluted way of managing accounts. Worked for me, though. I have updated the pull request.

**Comment by jamcat22** [comment]
Thanks @rworsnop!

**Pull request merged**
