### PR TITLE
Add Hotels and Accommodations Category with new site IHG, and move airbnb & hilton honors.

### PR DESCRIPTION
**Pull request by Rfosu2k2**
This is to resurect #3902  & continue on with #4024. This updates the section & adds in the _data\hospitality.yml & _img\hospitality.yml files.  This also includes the first hospitality website  IHG.com that does not have 2FA.

I was unable to find any documentation regarding the icon for categories, so I did not include the img for that.

### CODE REVIEW

**Comment by Rfosu2k2** [comment]
What are the merge conflicts that need to be corrected for this to be reviewed and approved?

**Comment by Carlgo11** [comment]
https://lmgtfy.com/?q=github+merge+conflicts

**Comment by kmpoppe** [comment]
Hi @rfosu2k2 and again, thank you for your contributions!
I think @Carlgo11 mistook your question as "what are merge" conflicts, which I think you already know by now.
The problem is, that through APIv2 (#4015) we first need to get all the other categories worked through for the new 2FA-methods before we start adding new categories.
I took myself the liberty to update the image you put in your PR for IHG. 
The last category we added was "VPN Providers", with that one I added all the providers I could find to the new category. I know for a fact that we do have _some_ hotel-chains on here already, would you be so kind as to update your branch so that these are removed from their respective data files and img-folders into the new one, so that we do not have to do another PR just for moving them.
This would also help us because we don't need to review the entries in the other categories first.
Thank you for your understanding and your continued assistance in this project!
// Kai

**Comment by Rfosu2k2** [comment]
Kai,

I can migrate over the other hotels/hospitality sites into this PR.  Thanks for updating the image.  If I have any questions in regards to specific entries I can will list those here for review.

I was able to discover the icons that are used for the categories(section) icons from #3694 and referencing https://semantic-ui.com/elements/icon.html.  Is this the correct page to use when adding icons for new categories(sections)?  If so, I found these 4 icons that could work for the Hospitality category with my preference being in order{bed, suitcase, building, building outline}.  Which one should we use, and I can update accordingly as "hotel" I put doesn't exist.

Are you still planing to move away from semantic-UI as referenced in this project? https://github.com/2factorauth/twofactorauth/projects/2#card-1157173

**Comment by kmpoppe** [comment]
Hi!
I didn't even see that `hotel` doesn't exist *facepalm*
I'd go for `bed` as the icon! That's most unambiguous, because we don't need an icon for IKEA's beds 😁
// Kai

**Comment by Rfosu2k2** [comment]
Edited the comment after you stated "bed" would replace "hotel", please review above comment for additional questions.

**Comment by kmpoppe** [comment]
grafik
Looks good to me!

**Comment by kmpoppe** [comment]
> Are you still planing to move away from semantic-UI as referenced in this project? https://github.com/2factorauth/twofactorauth/projects/2#card-1157173

As you probably saw, there isn't even an Issue attached to that card. Currently, our primary focus is the content of the site, visuals come second. And even though we've made some visual changes lately, there's not been an active discussion about any alternatives to Semantic UI so, for the time being, just ignore that point.

If we ever decide to change that, we'll give notice where needed.

// Kai

**Comment by Carlgo11** [comment]
Ah, sorry I misread what you asked!

I'm not sure about the category name. Ideally it should be something that's easy to understand even if you don't know a lot of English. "Hotel" is an example of something most people understand regardless of language but that would leave out sites like AirBnB 🤔

**Comment by kmpoppe** [comment]
The only other thing I could think of is `accommodation` which would include Hotels and AirBnB but then again I wonder if that would make the situation significantly better 😅

**Comment by Carlgo11** [comment]
https://youtu.be/usrl2FUWhEE?t=259

Yeah accommodation isn't an option

**Comment by kmpoppe** [comment]
@Carlgo11 How about `lodging`?

**Comment by Rfosu2k2** [comment]
I like lodging, but then does that leave out hotel reward sites such as Hilton honors, and IHG?

After reviewing all the sites listed in all the categories I could only find Hilton honors, and airbnb as the 2 currently listed that would be migrated into this new category.  Is there any others that I am missing?

Also, when adding into this category, are we limiting to just hotels/motels and associated reward sites directly affiliated with those lodgings?  Otherwise we possibly open up a bunch of sites that offer rewards to those sites such as this https://www.cashbackholic.com/.  Speaking of, should we have a "Reward site" type category?  I understand this could be a separate PR.

**Comment by kmpoppe** [comment]
Could you also move the Marriott, please?

**Comment by Rfosu2k2** [comment]
> Could you also move the Marriott, please?

I am unable to locate Marriott, could you tell me where it is located, and I can move that as well.

**Comment by Rfosu2k2** [comment]
I believe the merge conflict has been resolved, and this should be correct now.

**Review by kmpoppe — APPROVED** [review]
Looks good

**Comment by Carlgo11** [comment]
I don't think Lodging is a good name either. I'll try and think of something in the next few days.

**Comment by Rfosu2k2** [comment]
> I don't think Lodging is a good name either. I'll try and think of something in the next few days.

Here are other options I found @Carlgo11 :
- Boarding
- Lodge
- Hotel
- Resort
- Room and Board
- Quartering
- Bed and Breakfast
- Inn

**Comment by Rfosu2k2** [comment]
Looks like a pending update from #4238 could alter this PR.  Any chance we can move forward with this PR?

**Comment by Carlgo11** [comment]
@Rfosu2k2 @kmpoppe `Hotels and Accommodation` could that work?

**Comment by Rfosu2k2** [comment]
> @Rfosu2k2 @kmpoppe `Hotels and Accommodation` could that work?

I think that covers the category very well.  Shouldn't it be plural for both then? `Hotels and Accommodations`

**Comment by kmpoppe** [comment]
I'm totally fine with `Hotels and Accomodations` - section file `hotels.yml`?

**Comment by Rfosu2k2** [comment]
I have made the necessary changes, and updated all folders/flies accordingly.  I believe this is ready to merge.

**Comment by kmpoppe** [comment]
Hey @Rfosu2k2, could I ask for your support again, for you to add #4081 to this new category please?
// Kai

**Review by Carlgo11 — APPROVED** [review]

**Comment by Rfosu2k2** [comment]
Fixes #4081

**Comment by Rfosu2k2** [comment]
Fixes #4081

**Comment by Rfosu2k2** [comment]
Fixes #3902

**Pull request merged**
