### PR TITLE
Add Plivo.

### PR DESCRIPTION
**Pull request by ZacharyDuBois**
Add Plivo.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Compressed version:
plivo

**Comment by ZacharyDuBois** [comment]
@Carlgo11, What options are you using for OptiPNG. I am just using the defaults.

**Comment by Carlgo11** [comment]
@ZacharyDuBois https://tinypng.com/

**Comment by ZacharyDuBois** [comment]
@Carlgo11 Ah so not even OptiPNG :P Thanks :+1:

**Comment by Carlgo11** [comment]
No problem.

Your changes will be live within a couple of days (might take up to 2 weeks).

**Comment by mxxcon** [comment]
@ZacharyDuBois if you use osx, there's great https://imageoptim.com/, for windows there's http://css-ig.net/scriptpng

**Comment by ZacharyDuBois** [comment]
@mxxcon Awesome :) I was just using OptiPNG as suggested in the `CONTRIBUTING.md`.

**Comment by mxxcon** [comment]
It's not wrong, but these tools will squeeze out a bit more data. :smile:

**Pull request merged**
