### PR TITLE
Add a bank to banking.yml

### PR DESCRIPTION
**Pull request by ItayXD**
Add Discount Bank of Israel

### CODE REVIEW

**Comment by ItayXD** [comment]
32x32 image attcahed
idb

**Comment by mxxcon** [comment]
@ItayXD This is not how you upload images :) you have to upload it here https://github.com/ItayXD/twofactorauth/tree/patch-3/img/banking

**Review by mxxcon — CHANGES_REQUESTED** [review]
@ItayXD This is not how you upload images :) you have to upload it here https://github.com/ItayXD/twofactorauth/tree/patch-3/img/banking

**Comment by ItayXD** [comment]
The requested changes have been done, any chance to merge it?

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
