### PR TITLE
Add mercado libre

### PR DESCRIPTION
**Pull request by stephengroat**
#1484

### CODE REVIEW

**Comment by RichJeanes** [comment]
Just a little thing, but can you update the doc link to use HTTPS? Thank you!

**Comment by stephengroat** [comment]
Fixed. Good catch!

**Comment by RichJeanes** [comment]
Hmm, I also just noticed that they way the site is divided, each country they serve has a different TLD and this extends to the documentation sites. Does anyone think this is an issue since we can only link to one specific doc link? (Currently Argentina's `.com.ar`)

**Comment by stephengroat** [comment]
I chose `ar` because it was the first country listed on the www.mercadolibre.com

**Comment by sailenicolas** [comment]
Well, is .com.ar because the site is from Argentina. Check [Wikipedia](https://en.wikipedia.org/wiki/MercadoLibre.com) They also have [MercadoPagos.com](MercadoPagos.com) which is equivalent to "paypal"...

**Comment by stephengroat** [comment]
MercadoPago is owned by MercadoLibre, so at least by including MercadoLibre the parent company is included

**Comment by Carlgo11** [comment]
bump @2factorauth/core

**Pull request merged**
