### PR TITLE
Update EverBank

### PR DESCRIPTION
**Pull request by peterkeen**
EverBank does support SMS and Phone verification. I can't find any docs but I popped the verification screen this morning.

### CODE REVIEW

**Comment by Carlgo11** [comment]
It would be nice with a doc. Maybe you could ask them if they have one?

**Comment by mxxcon** [comment]
@peterkeen "popped the verification screen" does not sound the same as two factor authentication.. Can you provide more information?

**Comment by peterkeen** [comment]
When I tried to login this morning EverBank presented me with an "Account
Verification" screen. They gave me the option of either SMSing me a code or
giving me a code and having me type it into the phone.

Maybe this doesn't count as 2FA? I'll email them and see if I can get a
link to some documentation on how it works.

**Comment by mxxcon** [comment]
That is considered 2fa. I was thinking it was something like additional security questions, which are not 2fa.
But yes, a link to their docs would be nice.

**Comment by Carlgo11** [comment]
I also don't think `phone: Yes` is correct. Do they support phone calls as tfa?

**Comment by peterkeen** [comment]
The two options presented to me were:
1. They present me with a code on the screen and then call my registered
   phone number. I type the number into the phone.
2. They SMS me a code, I type it into the website

I emailed them and asked for a public link that talks about it, hopefully
they'll get back to me today or tomorrow.

**Comment by Carlgo11** [comment]
Okay phone is correct then.

Have you got any response from them?

**Comment by jamcat22** [comment]
I cannot seem to find a public link for this, but this discussion on Mint (a financial management tool) seems to agree that they require codes.

https://mint.lc.intuit.com/questions/989463-how-to-access-everbank-account-information

I would be willing to make a doc for it, but I would need screenshots to understand how the login process works, with personal info blacked out of course. :D

**Comment by peterkeen** [comment]
I got it again this morning and took screenshots.

Initial screen
screenshot 2014-11-05 08 51 14

Options selection
screenshot 2014-11-05 08 51 25

Text option
screenshot 2014-11-05 08 51 44

Call option
screenshot 2014-11-05 08 52 00

**Comment by mxxcon** [comment]
@peterkeen did they get back to you regarding docs link?

**Comment by peterkeen** [comment]
@mxxcon They did. Sounds like they're not interested in having public docs:

> Thank you for contacting us. 
> 
> We have an enhanced log in authentication process. When logging into the online banking, our system has sophisticated device identification implemented. If the system does not recognize the device, an additional security layer is required. The user will be prompted for a one-time verification code, where we will need to reach the user by phone or SMS text message to verify a code. The user can only select from phone number on file. If they cannot be reached by phone, we have multiple choice security questions based on noncredit data sources. We do not have a public link on more information on this feature. Normally, when trying to aggregate the Everbank account to a third party site, it will not work due to our security layers with logging into the online banking. 
> 
> We hope this information is helpful and that you are enjoying banking with EverBank. If you require additional assistance, we're available 24 hours a day, 7 days a week, at 888.882.EVER (3837). You can also contact us Monday through Friday, 8a.m. to 9 p.m. ET through email (service@everbank.com) or Twitter (@EverBankHelp). 
> 
> Thank you for choosing EverBank

**Comment by Carlgo11** [comment]
Their reply sounds like a joke...
"our system has a sophisticated device identification implemented" aka `session_start();` or cookies.

**Pull request merged**
