### PR TITLE
Add PrivacyPolicies

### PR DESCRIPTION
**Pull request by soodaayush**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Which [site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) would this fall under?
I created an account but can't see anything that could be seen as sensitive content.

**Comment by soodaayush** [comment]
I guess this would fall under sensitive data, since your email and password are disclosed to the website.

**Comment by Carlgo11** [comment]
2FA is meant to protect against an attacker using the username and password to gain access to systems; Not protect the username and password from being leaked. As such, usernames and passwords cannot on their own be seen as sensitive data in the site criteria context.

**Comment by soodaayush** [comment]
Then I guess this doesn't qualify then, will close this request.

**Pull request closed without merging**
