### PR TITLE
Logo optimizations

### PR DESCRIPTION
**Pull request by mxxcon**
Replaced wrong size logos and losslessly recompressed everything to save ~250kb

### CODE REVIEW

**Comment by jdavis** [comment]
Cool, I/we haven't forgotten about #480

**Comment by jdavis** [comment]
By the way, what do you use for image re/compression?

**Comment by mxxcon** [comment]
This time I used http://imageoptim.com
For Windows there's http://pnggauntlet.com
For Linux there's http://trimage.org

**Comment by jdavis** [comment]
Haha, I didn't even notice the branch name... Cool though, thanks for the info.

**Pull request merged**
