### PR TITLE
Add Gaijin Entertainment

### PR DESCRIPTION
**Pull request by jellemdekker**
Added [Gaijin.net](https://gaijin.net/en/), the universal sign-in platform for [Gaijin Entertainment](https://gaijinent.com/en/about/)'s games such as [War Thunder](https://warthunder.com/en), [Crossout](https://crossout.net/en) and [Star Conflict](https://star-conflict.com/en). Two-factor authentication is supported through email, SMS and Google Authenticator.

### CODE REVIEW

**Review by Jawshy — COMMENTED** [review]
Hi, @jellemdekker. 

The documentation mentions Google Authenticator (software), but I didn't find any documentation about email or SMS as an authentication method. 

How do you know Gaijin offers email and SMS as an authentication method?

**Comment by jellemdekker** [comment]
I wasn't able to find any official documentation on this. However, in the Security section on my Gaijin profile I made the following screenshots:

- [Three 2FA options listed](https://i.imgur.com/sWhn4qw.png)
- [Details on email 2FA option](https://i.imgur.com/FxsragY.png)
- [Details on SMS 2FA option](https://i.imgur.com/7BZ2olu.png)

**Review by mxxcon — CHANGES_REQUESTED** [review]
Their setup is pretty stupid.
To use email you MUST first verify it. To verify it you MUST first add and verify your phone number.
Similarly, with GoogleAuth, you MUST have verified phone number. 👎
@jellemdekker Please add `exception` that all forms of 2fa require a phone number

**Comment by jellemdekker** [comment]
Hmm strange, I didn't have to do that when I created my account a few years ago. I could just set up 2FA without a phone number. But I checked it again and you're right, a verified phone number is now required. Silly... I've added an exception in my changes.

**Review by Jawshy — APPROVED** [review]
Their implementation of 2FA is poor, but it checks out. 

Thanks for the pull request, @jellemdekker.

**Review by mxxcon — APPROVED** [review]

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
