### PR TITLE
added totp.me

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mxxcon** [comment]
Need a logo.
What kind of hardware do you support?

**Comment by ghost** [comment]
On 6 Sep 2014, at 02:43, mxxcon notifications@github.com wrote:

> Need a logo.

Cool, got one now.

> What kind of hardware do you support?

No idea. Anything that can compute TOTPs. I've changed Hardware to "No".

Thanks.

**Comment by Carlgo11** [comment]
@totpme just remove `hardware`

**Comment by ghost** [comment]
On 8 Sep 2014, at 01:18, Carlgo11 notifications@github.com wrote:

> @totpme just remove hardware

Done, thanks.

**Pull request merged**
