### PR TITLE
Add imgix.com

### PR DESCRIPTION
**Pull request by ollieza**
Added a site that does not support TFA - imgix.com, a real-time image processing and image CDN.

Twitter and Facebook usernames included but no email address could be found on their website or information about 2FA work in progress in their documentation.

I contacted their support about their lack of 2FA and was told:

>We completely agree that this is a secure practice and it is something we currently have on our roadmap. Unfortunately it doesn't look like it will be fully developed until Q4 of this year and we will likely be starting with Google Authenticator. I will keep you looped in as we roll this out.

The site's image `imgix.png` has been processed losslessly using imageoptim as per advice seen in another PR.

### CODE REVIEW

**Review by mxxcon — DISMISSED** [review]
Would `developer.yml` be a more appropriate category for this?

**Comment by brycx** [comment]
@mxxcon Seems we have other CDN's like CDNsun and MaxCDN in the hosting category. I think hosting fits well.

**Comment by ollieza** [comment]
@mxxcon possibly. I looked through `hosting.yml` and saw a couple of other CDN services. imgix.com is a developer tool but it is also a CDN service. I guess it's a bit of both....It's basically AWS CloudFront with some image processing and JS libraries.

**Comment by ollieza** [comment]
My vote is to move this to developer. I'll submit additional commits.

**Review by mxxcon — APPROVED** [review]

**Comment by mxxcon** [comment]
@brycx but that's the thing, do they consider themselves and/or do they stand out primarily as cdn or image manipulation service? :) At the end of the day it's not the end of the world if it's in either category.

**Comment by ollieza** [comment]
Primarily a image manipulation service. In fact they harness a third party CDN, Fastly, as part of their offering.

**Comment by brycx** [comment]
@mxxcon True, and I agree. 

@ollierattue You have me convinced.

**Review by brycx — APPROVED** [review]

**Comment by ollieza** [comment]
What's the timeline for a production deploy to https://twofactorauth.org ?

**Comment by brycx** [comment]
@ollierattue take a look at the [FAQ](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge).

**Pull request merged**
