### PR TITLE
Add Black Hills Federal Credit Union

### PR DESCRIPTION
**Pull request by psrdrgz**
Please add Black Hills Federal Credit Union

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr @psrdrgz. is there any documentation that we could link to with the `doc` tag?

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
The logo is too big. Here's a compressed version.
bhfcu

**Comment by psrdrgz** [comment]
Rebased changes.

**Comment by Carlgo11** [comment]
The doc link doesn't mention how the system works at all or what kind of 2FA they use.
I will need further information to make a decision on this.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
The doc link doesn't mention how the system works at all or what kind of 2FA they use.
I will need further information to make a decision on this.

**Comment by psrdrgz** [comment]
@Carlgo11, the little information that is provided about 2FA can be found under the question: What happened to my Security Questions?

"Security questions have been replaced in the new system with the current industry standard for login security. It's called Multi-Factor Authentication and it's the leading security practice. When you login for the first time on a browser or device, you'll need your Username and Password. To verify it's really you, the system will call, send a text or email you to make sure it's authorizing you to view your accounts."

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
