### PR TITLE
Add Looker

### PR DESCRIPTION
**Pull request by jsiegz**
Looker makes software that makes it easy and fun for non-technical users to access, manipulate, export, and look at any size data, without writing any code. For analysts and developers, Looker brings modularity and reusability to SQL.

### CODE REVIEW

**Comment by mxxcon** [comment]
@jsiegz do you have that doc info somewhere on your site and not in google docs?

**Comment by jsiegz** [comment]
Yes, it's [here](http://docs.looker.com/documentation/reference/operations-security/two_factor_auth.html) but our docs are not open to the public today. I am happy to share a login with someone if it helps, but I can't open our whole docs site to the world right now. If it's a prereq to have open docs I can put 2FA docs somewhere on our public website.

**Comment by Carlgo11** [comment]
It's funny to see how Americans like to only show stats on their own country.
The same with buying stuff from American companies.
It has nothing to do with 2FA. just a side note.

**Comment by mxxcon** [comment]
@jsiegz it's not a prereq, just would be nice for visitors to see something rather than "logic is required", but that's up to you to decide.
Otherwise :+1:

**Comment by jsiegz** [comment]
@mxxcon thanks, so I'll just send another pull request in a few months when our public docs site is up

**Comment by jsiegz** [comment]
@Carlgo11 I meant that I'd send a pull request with an updated docs link in a few months to replace the GDocs link. Is this okay to re-open and merge now?

**Comment by Carlgo11** [comment]
oh, my bad

**Pull request merged**
