### PR TITLE
Adding Snapchat

### PR DESCRIPTION
**Pull request by Vanhouttethomas**
Snapchat added a SMS login verfication method: https://support.snapchat.com/ca/login-verification

### CODE REVIEW

**Comment by mxxcon** [comment]
@Vanhoutte the logo needs to be part of the pull request.

**Comment by Vanhouttethomas** [comment]
@mxxcon 

snapchat
I currently only have a browser to work with :/
Losslessly compressed 32x32px png file.

**Comment by mxxcon** [comment]
I submitted pull request with snapchat logo into your repo. Accept it and it should automatically appear here.

**Comment by mxxcon** [comment]
Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jdavis/twofactorauth/1174)

**Pull request merged**
