### PR TITLE
Add Zurich Cantonal Bank

### PR DESCRIPTION
**Pull request by stephengroat**
#1407

### CODE REVIEW

**Comment by RichJeanes** [comment]
Little thing here, but can you make sure there is a newline at the end of the `banking.yml` file? It's in the project's `.editorconfig` file, but that seems to be something that not many people notice (myself included at first, to be fair). Perhaps that's something we should list in the contributing doc...

**Comment by stephengroat** [comment]
I'm pretty sure it has a newline at the end. Github's web editor shows a red x on the last list if it's missing a newline, but chops the last newline if it's there.

I did a pull to double check and saw it. Could you push something to the branch to show me exactly what to fix if it's not there?

**Comment by Carlgo11** [comment]
Looks like there wasn't a new line before you did your changes but maybe you could add one now?
Just edit the file and add an empty line at the end of the file.

**Comment by stephengroat** [comment]
Should be done

**Comment by Carlgo11** [comment]
Thanks!

**Comment by RichJeanes** [comment]
Hmm, might just be editor weirdness. Thank you for being so cooperative, though!

**Pull request merged**
