### PR TITLE
Add Kuna

### PR DESCRIPTION
**Pull request by 40504**

### CODE REVIEW

**Review by phallobst — CHANGES_REQUESTED** [review]
Please change the icon to this one with a transparent background:
kuna

**Comment by 40504** [comment]
but now the file is 1.1 kb even if passed through https://tinypng.com/

**Comment by 40504** [comment]
done

**Comment by 40504** [comment]
how did you do that icon to weight less?:)

**Comment by phallobst** [comment]
https://kuna.io/static-files/icons-8c45d375751fb3c113971983f41b4dd4/favicon-32x32.png + TinyPNG = Win! 😄

**Review by phallobst — APPROVED** [review]

**Comment by 40504** [comment]
👍

**Review by dsoegijono — APPROVED** [review]

**Pull request merged**
