### PR TITLE
Fixed typo for CloudEntr (does have 2FA)

### PR DESCRIPTION
**Pull request by clsy**
Added tfa line to CloudEntr.

### CODE REVIEW

**Comment by clsy** [comment]
Am not seeing changes on the site. Don't see newer pulls; identity section supposed to have 5 entries, latest pull #416 supposed to add SecureAuth to provider list. Is the website updated once a week? Thanks.

**Comment by jdavis** [comment]
The website is updated whenever I update it or one of the collaborators for that matter =]

I just updated it. Let me know if you see it :)

**Comment by clsy** [comment]
I see the changes. Thanks.

How do contributors update the website? Could I have refreshed the site? Thanks.

**Comment by jdavis** [comment]
Contributors themselves can't update the site by design (which is good).

Only people that have push access to the repository can update the `gh-pages` branch: https://github.com/jdavis/twofactorauth/tree/gh-pages

This is only people listed as "Collaborators" as well as me.

**Pull request merged**
