### PR TITLE
Bump gh-pages branch to current master

### PR DESCRIPTION
**Pull request by baloo**
The deployment is currently stuck on commit 5d69f916a01dfc621911c849b3df4eeb75705a37 which is also the current gh-pages branch. I think this is caused by a misconfiguration in the project settings. In case this is not, this PR bumps the gh-pages branch to master.

Please consider merging to deploy changes made since Aug 15.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Hello @baloo,
we're aware that the current live site is stalled however we have specific procedures on how master is merged with gh-pages.
You can read more about the merge process on [our wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge)

**Comment by baloo** [comment]
I didn't know about the procedure, thanks for pointing that out. Any idea when the next merge will occur? The procedure reads it's supposed to occur every week or so. I don't mean to be pushy, but I believe one of the intentions of this website is to list good actors. Not rewarding good efforts is kind of sad for actors :(.

**Comment by baloo** [comment]
@Carlgo11 any thoughts?

**Comment by Carlgo11** [comment]
Sorry for the delay @baloo,
there are currently only 3 people that know how to merge properly and it seems like all three (including me) have been very busy lately.

As the backlog is very big right now I think what we'll do is break it in to parts starting with the oldest unmerged commits. This means it will take even more time for the newest commits to be merged but makes the workload manageable :wink:

**Comment by baloo** [comment]
@Carlgo11 well, let me know if I can be of any help. I'd be happy to.

**Comment by baloo** [comment]
@Carlgo11 any chance I could help with that?

**Comment by Carlgo11** [comment]
Updated.

**Pull request closed without merging**
