### PR TITLE
Add Tangerine

### PR DESCRIPTION
**Pull request by schmeat**
Added Canadian Bank called Tangerine. Does not support any 2FA.

### CODE REVIEW

**Comment by Carlgo11** [comment]
you need to add a 32x32px logo. See the <a href="https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md">CONTRIBUTING.md</a>

**Comment by schmeat** [comment]
Sorry about that. I'm not sure how to do that easily but I do have the image right here.

tangerine

cheers

**Comment by RichJeanes** [comment]
Images can't be added from the website. You need to download and install the Git client to add the file to your pull.

**Comment by Carlgo11** [comment]
Please remove `hardware: No` and `software: No` since you've already stated the bank doesn't provide any form of tfa.

**Pull request merged**
