### PR TITLE
Added Metaname to Domains

### PR DESCRIPTION
**Pull request by neilstockbridge**

### CODE REVIEW

**Comment by RichJeanes** [comment]
Looks like you're missing the `tfa: Yes` tag. Other than that, if you could provide a doc link describing how to set it up on an account that, would be fantastic.

**Comment by neilstockbridge** [comment]
Cheers.  Both the `tfa` and `doc` tags should be present now.

**Comment by jamcat22** [comment]
Bump. It seems like this is following the correct format for Awesome 1.0. I see no reason why it shouldn't have been merged sooner.

**Comment by jdavis** [comment]
@jamcat22 There's just a merge conflict; it makes my job slightly harder as I have to manually resolve it. Other than that and school (time reasons basically), there's no reason why it hasn't been merged already =[

**Comment by jdavis** [comment]
YA HAPPY, @jamcat22? :smile:

But for real, thanks for helping out; I really appreciate it.

**Pull request merged**
