### PR TITLE
Add Infura

### PR DESCRIPTION
**Pull request by Yang-Nankai**
Infura is a blockchain infrastructure platform that provides developers with tools and APIs to interact with decentralized networks like Ethereum. It enables seamless integration for building decentralized applications (dApps) by offering scalable solutions for blockchain data retrieval, transaction management, and node access. Infura offers 2FA for the account login verification process. The website is ranked 91,417 on [Similarweb](https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/1m?webSource=Total&key=infura.io). The website provides documentation on how to turn on 2FA.

### CODE REVIEW

**Review by Carlgo11 — COMMENTED** [review]
As Infura is part of Metamask and the login uses Metamask, it would make more sense to list Metamask / Metamask Developer.

**Comment by Yang-Nankai** [comment]
I see that **Metamask** is not collected either. Do I need to collect **Metamask** and use **Infura.io** as its `additional domain`? @Carlgo11

**Comment by fletcherdodd** [comment]
> I see that **Metamask** is not collected either. Do I need to collect **Metamask** and use **Infura.io** as its `additional domain`? @Carlgo11

I would close this one off and add `infurio.io` as an aditional domain to the other listing.

**Comment by Yang-Nankai** [comment]
> I would close this one off and add `infurio.io` as an aditional domain to the other listing.

Thank you for doing this! I submitted the **MetaMask** item at #8308. 😄

**Pull request closed without merging**
