### PR TITLE
Add spanish translations

### PR DESCRIPTION
**Pull request by fainpablo**
Added spanish translations.

### CODE REVIEW

**Comment by fainpablo** [comment]
This is related to issue #4230.

**Comment by phallobst** [comment]
Could you translate the email subject as well? I've just added it to issue #4230, and you may have been quicker than me.

**Comment by fainpablo** [comment]
> Could you translate the email subject as well? I've just added it to issue #4230, and you may have been quicker than me.

Done! I just finally replaced "two step authentication" by "two factor authentication", considering most of the documentation on the support sites that have 2FA refers to "two factor".

**Comment by phallobst** [comment]
Although it is not strictly needed, it would be nice to keep the languages in alphabetical order. Could you move the "es" block below the "en" block?

**Comment by fainpablo** [comment]
My bad :) Consider it done.

**Review by phallobst — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]
Thank you! 🙏

**Pull request merged**
