### PR TITLE
Add Eneba

### PR DESCRIPTION
**Pull request by David9004**

### CODE REVIEW

**Review by jdavis — APPROVED** [review]

**Comment by phallobst** [comment]
Please rebase your branch to the current master.

**Comment by Carlgo11** [comment]
Closing due to inactivity.

**Comment by David9004** [comment]
damn this is my work email and i was busy.. So now i have to resubmit Eneba?

Deividas Jodelis
SEO Specialist

deividas.jodelis@eneba.com
Laisvės al. 59-II a., Kaunas, Lithuania
eneba.com <https://www.eneba.com/>

*This e-mail may contain information which is privileged or otherwise
protected against unauthorized disclosure. If you are not the intended
recipient, please notify the sender by phone or e-mail, and delete this
message from your system without distributing or retaining copies thereof,
or disclosing its content to any person. Notwithstanding anything in the
above, disclosure of this e-mail to any third party is conditional upon
written approval of the sender hereof. *

**Comment by Carlgo11** [comment]
I'll re-open the PR for you to make the changes.

If you're using command-line git, try:
```PWSH
git remote add upstream https://github.com/2factorauth/twofactorauth.git
git fetch upstream
git reset --hard upstream/master
git cherry-pick 9345262
git push origin master -f
```

**Comment by David9004** [comment]
Hi,

Sorry i'm not using the command line. Tried to use it, wasted some time and
had no success.. I tried doing all you said using the github app. Did it
work? Or maybe I have to re-add the website manually again and be done with
it.


Best,

Deividas Jodelis
SEO Specialist

deividas.jodelis@eneba.com
Laisvės al. 59-II a., Kaunas, Lithuania
eneba.com <https://www.eneba.com/>

*This e-mail may contain information which is privileged or otherwise
protected against unauthorized disclosure. If you are not the intended
recipient, please notify the sender by phone or e-mail, and delete this
message from your system without distributing or retaining copies thereof,
or disclosing its content to any person. Notwithstanding anything in the
above, disclosure of this e-mail to any third party is conditional upon
written approval of the sender hereof. *

**Comment by Carlgo11** [comment]
@David9004 I did the rebase and force-pushed to your repository.
Also changed the PNG to an SVG-file as those are prefered.

Your company should really invest in someone who knows how to make SVG objects. The [logo](https://cdn.eneba.com/branding/v2/logoFull.svg) is a mess >_<

**Review by Carlgo11 — APPROVED** [review]

**Comment by David9004** [comment]
Thanks!

Ha ha, I know it's a startup so first we make something and fix
afterwards.. :)

Thanks again for your help!

Best,

Deividas Jodelis
SEO Specialist

deividas.jodelis@eneba.com
Laisvės al. 59-II a., Kaunas, Lithuania
eneba.com <https://www.eneba.com/>

*This e-mail may contain information which is privileged or otherwise
protected against unauthorized disclosure. If you are not the intended
recipient, please notify the sender by phone or e-mail, and delete this
message from your system without distributing or retaining copies thereof,
or disclosing its content to any person. Notwithstanding anything in the
above, disclosure of this e-mail to any third party is conditional upon
written approval of the sender hereof. *

**Review by phallobst — APPROVED** [review]

**Pull request merged**
