### PR TITLE
Add Coda

### PR DESCRIPTION
**Pull request by 40504**

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Try this one:

**Comment by 40504** [comment]
> Try this one:
> 

so now on I should upload .svg files?

**Comment by Carlgo11** [comment]
@40504 yes SVGs are prefered over rasterized image formats.

**Comment by 40504** [comment]
OK👌

**Review by Carlgo11 — APPROVED** [review]

**Comment by phallobst** [comment]
I'm not so sure about "Social" as the category... This seems to fit better in "Communication".

**Review by phallobst — APPROVED** [review]

**Pull request merged**
