### PR TITLE
Add Oppaitime

### PR DESCRIPTION
**Pull request by spaghetti2514**
Supports software 2FA via TOTP and hardware 2FA via U2F tokens

screen shot 2018-05-16 at 7 42 00 pm

screen shot 2018-05-16 at 7 41 20 pm

### CODE REVIEW

**Review by mxxcon — COMMENTED** [review]
How does this site quality with our https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria

**Comment by mxxcon** [comment]
Actually looking at Alexa ranking, at this time the site is not ranking high enough for inclusion.

**Comment by spaghetti2514** [comment]
@mxxcon I believe it qualifies as a data site. I don't see anything on the contribution requirements about an Alexa ranking though?

**Comment by mxxcon** [comment]
We haven't updated the site yet, but for a bit now we've been restricting to adding Alexa 200k sites.

**Pull request closed without merging**
