### PR TITLE
Add Westpac [Banking]

### PR DESCRIPTION
**Pull request by yoyosamo**
Add Westpac (One of Australia's 'big four' banks) to Banking section.

- Add Westpac to banking.yml
- Add westpac.png icon

Westpac support a similar 2FA implementation as the Commonwealth Bank of Australia and Citibank Australia, with the additional option of a SecurID hardware token.

Many thanks 😄

### CODE REVIEW

**Comment by Jawshy** [comment]
> Westpac Protect™ SMS Code helps protect you by using your mobile phone to confirm certain transactions via text message when you bank online. _[...]_ 

> A SecurID® token is a small, portable device that generates a digital security code, which you use to securely authorise certain online transactions. _[...]_ 

According to the [documentation](https://www.westpac.com.au/security/how-we-protect-you/westpac-protect/) Westpac offers two-factor _authorization_ and not two-factor _authentication_. This is an important distinction because [twofactorauth.org](https://twofactorauth.org/) lists "... websites and whether or not they support \[[two-factor authentication](https://en.wikipedia.org/wiki/Two-factor_authentication)\]." Read [A Note on Definitions](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) for more information. 

Westpac can still certainly be listed, but as `tfa: No`.

**Comment by yoyosamo** [comment]
Thanks Jawsh,

While I understand and respect that distinction, in order to make it (and keep it consistent), one must go down the list (especially the Banking category) and review quite a few. 

I did read CONTRIBUTING.md, but chose to PR anyway, with the note regarding Comm. Bank and Citibank - many banks already listed have the same implementation, using 2FA only for certain actions.

Judging from a cursory look, sites already listed in the Banking section that only use the 2nd factor at certain times, and not at login include:
- [Bank of America](https://www.bankofamerica.com/privacy/online-mobile-banking-privacy/safepass.go) - "required [...] to authorize higher-value transfers.", "...help verify your identity before authorizing the transfer of funds..."
- [Citibank Australia](https://www.citibank.com.au/otp/) - "...anytime you want to perform select online transactions..."
- [Commonwealth Bank of Australia](https://www.commbank.com.au/security-privacy/netcode.html) - "...authorise certain NetBank activities and transactions..."
- [Natwest UK](http://personal.natwest.com/global/security-centre/stay-safe-online.html) - "following [certain] Online Banking transactions", "We will never ask you to use your card reader to log in to Online Banking"
- [Santander UK](http://www.santander.co.uk/uk/help-support/security-centre/our-approach-to-security) - "...unique codes to your mobile to security check: > payments that you have recently set up. > requests you make to amend some important details like your address."
- [State Bank of India](https://www.onlinesbi.com/personal/safe_online_banking.html) - "...for doing various transactions like adding third party, third party transfer etc. securely."

Should all these websites, and possibly others, be labelled as having _no_ 2FA, too?
While I understand that there is debate about it (and that I am only the new guy), I think that either way, consistency is key. 
Clearly some sort of review is necessary (I understand, a large undertaking), and either a swath of sites need to be removed entirely, or perhaps a note needs to be added to these 'authorisation' implementations. Maybe instead of a '⚠️' note, an ℹ️ could in introduced?

Since it is clear that these 'authorisation' PRs are being approved, something definitive needs to be done.

Many thanks again,
Sam

**Comment by Carlgo11** [comment]
@yoyosamo If you find another site on our list that actually doesn't support 2FA then you're more than welcome to make a PR removing it.
We won't however list two factor authorization sites on a two factor authentication list so I recommend you either set Westpac's `tfa`-tag to `No` or close this PR.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
[see prev. comment](https://github.com/2factorauth/twofactorauth/pull/2260#issuecomment-267786939)

**Comment by Carlgo11** [comment]
Closing due to inactivity.

**Comment by fpigerre** [comment]
Hello @yoyosamo,

You might be interested in the status of issue #1811.
We're currently working to resolve the 2FA status of a few websites that conflict with the definition of two factor authentication listed in [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions).
I'll be sure to list Westpac on twofactorauth.org once we've worked out the best solution for classifying banks.

Thanks,
psgs 🌴

**Comment by Jawshy** [comment]
@yoyosamo, would you like to reopen your pull request - and edit to `tfa: No` or allow maintainers to edit it?

**Pull request closed without merging**
