### PR TITLE
Add Filmweb

### PR DESCRIPTION
**Pull request by NullPiotrException**
Filmweb is a Polish equivalent of IMDB so I also added it to Entertainment. It's also the 2nd biggest movie database in the world (after IMDB).

[Alexa stats](https://www.alexa.com/siteinfo/filmweb.pl)

### CODE REVIEW

**Comment by stephengroat** [comment]
@einsteinsfool how does this apply to the [criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria)?

**Comment by NullPiotrException** [comment]
@stephengroat Imo yes, but you can decide yourself.
They store user's full name, email address, date of birth, sex, city and instant messenger number.
Obviously it also stores what movies, games, actors, series and TV channels they like.

Frankly, I just checked PR for IMDB and assumed they are the same. I don't have IMDB account so idk if they store some additional info to the ones above.

**Review by pawelci — APPROVED** [review]

**Comment by mxxcon** [comment]
imdb also has a paid plan so they collect payment info...does this site have that too?

**Comment by NullPiotrException** [comment]
No, but in an interview the CEO said that in Q1 2018 they will add paid accounts for users who don't want to see ads ([Polish source](http://www.wirtualnemedia.pl/artykul/filmweb-ogranicza-dostep-uzytkownikom-blokujacym-reklamy-szykuje-platne-profile-bez-reklam) - the news is even in the title, "preparing paid profiles without ads").
So I can close this issue, wait for them to introduce such accounts and then reopen it or just add Filmweb now.
What would you prefer, @mxxcon?

**Comment by mxxcon** [comment]
I think lets add it if/when they add such features. As of now I personally don't think it's worth doing that.

**Comment by NullPiotrException** [comment]
Understood. Closing.

**Pull request closed without merging**
