### PR TITLE
Add Phacility

### PR DESCRIPTION
**Pull request by michel-slm**

### CODE REVIEW

**Comment by mxxcon** [comment]
You are adding phacility, but your doc links is for phabricator?

**Comment by michel-slm** [comment]
@mxxcon Phacility is a hosted service by the Phabricator core developers. I could try and find a link on the Phacility site itself, but it would just point to Phabricator anyway. Should I add a comment to the yaml file to document this?

**Comment by michel-slm** [comment]
On https://admin.phacility.com/settings/panel/multifactor/ -- the "Help" link points to the Phabricator page I used. You'd need a free account to see this though.

**Comment by Carlgo11** [comment]
@michel-slm could you post a screenshot of the page here?

**Comment by michel-slm** [comment]
@Carlgo11 sure thing!

Here's the login page prompt for MFA credentials
phacility-mfa-1

And here's the link to Phabricator for documentation
phacility-mfa-2

**Comment by Carlgo11** [comment]
Great! Thanks.
You can remove the `doc` link and your PR should be good to go. :smile:

**Comment by michel-slm** [comment]
Updated, thanks!

**Comment by Carlgo11** [comment]
And thank you.

**Pull request merged**
