### PR TITLE
Added Education Added Oplerno Added Coursera Added Udemy Added Udacity

### PR DESCRIPTION
**Pull request by webhat**

### CODE REVIEW

**Comment by mxxcon** [comment]
@webhat missing logos and that's not a correct format for the current yaml files..

**Comment by webhat** [comment]
Thanks for the note, I noticed that I'd lost the images during a git reset so I re-added them.

**Comment by webhat** [comment]
@mxxcon what exactly's wrong with the yaml. It looks right to me...

**Comment by dsoegijono** [comment]
~~Icons need to be 32x32.~~ Check out [the guide](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#new-sites).

EDIT: You seem to have changed the icon when I was commenting. :)

**Comment by webhat** [comment]
@dsoegijono  :+1:

**Comment by mxxcon** [comment]
@webhat `goog: No` and `authy: Yes` are no longer used. Please look at https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md for the correct format.
Also please add line breaks between entries.
`doc: https://www.oplerno.com/` is also not a correct link. It should be pointing to a page that describes what kind of 2fa supported and/or how to enable it for users.
:smiley:
Coursera and Udacity logos look ugly stretched out pixelated.
You can use these files to crop and resize to get great results
http://s3.amazonaws.com/s3.userdata.www.universalsubtitles.org/teams/logo/cd2825021f6c59ca5d4dc5019a43d6896363783e.png
http://www.northstarcommunications.org/wp-content/uploads/2014/04/coursera-logo-nobg.png

**Comment by webhat** [comment]
I see, I wrote this ages ago and only now got round to pushing it. I'll make the changes.

**Comment by webhat** [comment]
I'll have to come back to this later, I'll reopen at that time.

**Comment by jdavis** [comment]
Awesome, we look forward to it. Thanks for all the effort, @webhat.

**Comment by webhat** [comment]
@jdavis there isn't any public documentation for oplerno's tfa.

**Comment by jdavis** [comment]
@webhat Darn. Is it simple to enable though?

**Comment by ibenrodriguez** [comment]
Oplerno uses Authy for their 2fa. There are two links with more info...

https://enroll.oplerno.com/users/enable-two-factor

https://www.authy.com/learn-more

**Comment by mxxcon** [comment]
@webhat grab these logos from my repo https://github.com/mxxcon/twofactorauth/tree/education/img/education/

**Comment by webhat** [comment]
@ibenrodriguez the first is not public, it requires you create an account.

**Comment by mxxcon** [comment]
@webhat can you please update education.yml file to be sorted alphabetically and have line breaks between entries?

**Comment by jdavis** [comment]
This got lost in the 4th of July + the fact that I'm moving across the country. Sorry about that @webhat. I'll merge it once you fix what @mxxcon mentioned. Seriously though, thanks a lot for your time.

**Comment by jdavis** [comment]
Actually, I'm going to merge this and do it myself... You've done enough @webhat.

**Comment by webhat** [comment]
Sorry, missed @mxxcon's question.

**Comment by jdavis** [comment]
Oh, no worries. I wanted to merge it because we went back and forth enough and put you through a lot, haha. I just wanted to get it closed.

I'm going the alphabetizing now, the site will be updated soon.

**Comment by jdavis** [comment]
Done =]

**Pull request merged**
