### PR TITLE
Add 'Attention' message to desktop- and mobile-table and update mobile-table button layout

### LINKED ISSUE #1450: Information disclosure concern - "Tell them to support 2FA" option
While it's a great idea in general, if a user were to only use this feature to notify their own sites it could easily translate to an inadvertent disclosure of a twitter user's affiliations.

Generally-speaking it would take some work to find out what banks a user might be registered with, whether they have cryptocurrencies, where their data is stored. Without at least a note about information disclosure here, this opens the door for a user to disclose that information to a potential attacker on their own. Knowing those sites don't support 2FA additionally reduces the difficulty threshold for a potential attacker.

### PR DESCRIPTION
**Pull request by kmpoppe**
Closes #1450.

### CODE REVIEW

**Comment by dsoegijono** [comment]
@kmpoppe Screenshots would be very helpful here.

**Comment by kmpoppe** [comment]
Will do later, Daphne! :)

**Comment by kmpoppe** [comment]
Desktop table:
grafik

Mobile table:
grafik

**Review by dsoegijono — DISMISSED** [review]

**Comment by Carlgo11** [comment]
I'm unsure about adding this message to all sites. How about just applying it to banking, finance and investment sites?

**Comment by RichJeanes** [comment]
Or some method of not showing it every time. Like a "Stop showing this message" kind of thing. Maybe a pop-up modal that only appears the first time a user clicks a social media button but not for any subsequent ones?

**Comment by Carlgo11** [comment]
@RichJeanes but how would that be saved?
If we start using cookies we have to add things like privacy notices and cookie settings.

**Comment by RichJeanes** [comment]
It could just be a per visit setting without using cookies, right? Set a local JavaScript variable or something? Please pardon my modern web programming ignorance.

**Comment by kmpoppe** [comment]
Yeah, that should work. Will try later.

Rich Jeanes <notifications@github.com> schrieb am Mi., 18. Sep. 2019, 16:46:

**Comment by kmpoppe** [comment]
A working copy of this branch can be visited at: http://2fa.poppe.work:4000/

**Comment by Carlgo11** [comment]
I'd like to wait to merge this PR until API v2 has been merged. It's much easier to fix any merge conflicts here than to do it with the v2 branch.

Assigning to myself in the meantime.

**Pull request closed without merging**
