### PR TITLE
add information for crypho

### PR DESCRIPTION
**Pull request by ennorehling**
Crypho requires 2FA and a strong passphrase for every login.

### CODE REVIEW

**Comment by mxxcon** [comment]
@badgerman Is there `docs:` url for this?

**Comment by ennorehling** [comment]
No, but there is no option of using the product without 2FA, so the signup process itself is the documentation, I guess?

**Comment by jamcat22** [comment]
You can remove the `twitter: getcrypho` line if you want. That is only used for websites that do not support 2FA.

**Comment by mxxcon** [comment]
so 2fa is actually mandatory?
What kind of `software` does it use for 2fa?

**Comment by Carlgo11** [comment]
Uhm... speaking of the signup process....

**Comment by ennorehling** [comment]
@Carlgo11 Oh, that's not good. It loads for me, though. Anything on the Javascript Console?
@mxxcon it uses TOTP, so Google Authenticator or any other app that implements that (I like Authy, myself).

**Comment by jamcat22** [comment]
@Carlgo11 and @mxxcon, 2FA was mandatory when I signed up.
image
image

**Comment by Carlgo11** [comment]
@ennorehling any doc link you could provide?

**Comment by jamcat22** [comment]
If this PR isn't updated in a few days, I'll make a new one to make sure the site is added. Thanks!

**Comment by jamcat22** [comment]
Closing and adding to backlog of sites.

**Pull request closed without merging**
