### PR TITLE
Add noez supporting 2FA

### PR DESCRIPTION
**Pull request by TuxCoding**

### CODE REVIEW

**Review by Jawshy — DISMISSED** [review]
Thanks for the pull request, @games647. 

Does the site have any documentation about how it has implemented two-factor authentication? 

As the site is in German could you add [`lang: de`](https://github.com/2factorauth/twofactorauth/blob/13b772d54ae1ee0c67a84708595a8ec791a44740/_data/languages.yml) on a new line below `software: Yes`?

**Comment by TuxCoding** [comment]
There is only a short description on the enable page, but that's requires authentication in order to access the page. 

The page basically says that you should download a OTP-APP, store the secret key in a safe place and then you need the 2fa code on every login attempt. 

Should I add it anyway?

**Comment by Jawshy** [comment]
Could you please capture and attach one or more screenshots that shows their implementation of 2FA?

**Comment by TuxCoding** [comment]
"2Factor"-page. Shows a short description.
enable-page

On "enable"-button click. Displays the QR-Code and the secret key in plain text.
enable

After you entered your credentials into the normal login form, you should enter the generated key.
post-login

**Review by Carlgo11 — APPROVED** [review]
Looks good

**Comment by TuxCoding** [comment]
Should I translate it somehow or copy the text here that you could a online translate service?

**Comment by Carlgo11** [comment]
No it's okay.

**Pull request merged**
