### PR TITLE
Add Robert Morris University

### PR DESCRIPTION
**Pull request by treed593**

### CODE REVIEW

**Comment by jamcat22** [comment]
Maybe use this logo instead?
2583702_mktg_logo 1

**Comment by jamcat22** [comment]
Awesome! Thanks for your PR!

**Comment by treed593** [comment]
Thanks for your suggestion!

**Comment by fpigerre** [comment]
Hello @treed593,

It seems the [link you added](https://sentry.rmu.edu/login/) is inaccessible.
Do you know if another link exists?

Thanks,
psgs :palm_tree:

**Comment by jamcat22** [comment]
It seems like they redirect when off-campus. The new link works!

**Comment by treed593** [comment]
Yea, its an HTTP redirect not a directory so the trailing slash killed it

**Comment by jamcat22** [comment]
Can you remove the new trailing slash on the link?

**Comment by jamcat22** [comment]
Sorry for earlier comment, my page hadn't updated. Thanks @treed593!

**Pull request merged**
