### PR TITLE
removed software from twitter

### PR DESCRIPTION
**Pull request by gingerbeardman**
no evidence at doc link to show that they support software

Edit: [Closes](https://help.github.com/articles/closing-issues-via-commit-messages/) https://github.com/2factorauth/twofactorauth/issues/2192 -- @Jawshy

### CODE REVIEW

**Review by Jawshy — APPROVED** [review]
[7b24cf8](https://github.com/2factorauth/twofactorauth/commit/7b24cf8376ac24e6536af2ebcb11ba29e7b39d93#diff-fc83a190dc0b0741a2cdb0168c2a8b9bR52) :thinking: - Anyway, thanks for the pull request, @gingerbeardman.

**Comment by gingerbeardman** [comment]
most welcome

**Comment by gingerbeardman** [comment]
Here's the post where Twitter introduced Login Verification back in 2013 (method hasn't changed)
https://blog.twitter.com/2013/getting-started-with-login-verification

The confusion I guess could be that they state having the mobile app as a stipulation for setting it up. I'm not really sure why though, as it's not involved in the authentication process?

**Comment by stephengroat** [comment]
It's hidden, but the software support is still there.

In the Twitter Android App, Settings->Account->Security->Login code generator. I'm assuming the sample is available on the iOS app according to [this](https://support.twitter.com/articles/20170409#login-code-generator)

**Comment by jamcat22** [comment]
Additionally, Twitter now allows you to setup any authenticator app that supports TOTP.
Twitter security settings page
"Setup a code authenticator app" screen

**Comment by gingerbeardman** [comment]
Awesome. Just set this up. Cheers

**Pull request closed without merging**
