### PR TITLE
Added flatex.de (1)

### PR DESCRIPTION
**Pull request by paradonym**
Category: Finance (flatex is an online broker for stocks and so on)
img: https://www.flatex.de/favicon.ico (written as png - needs to be converted)

### CODE REVIEW

**Comment by brycx** [comment]
Remember to commit the image for the site too:
> - ./_site/index.html
>*internal image /img/domains/flatex.png does not exist (line 21422)
> *internal image /img/domains/flatex.png does not exist (line 29328)

**Comment by paradonym** [comment]
I'm pretty new to Github - I've uploaded a matching file to repository /paradonym/twofactorauth - can I add this file here without creating just another pull request?

**Review by Jawshy — CHANGES_REQUESTED** [review]
Hi @paradonym. Thanks for submitting a pull request. 

You said that the category is finance, but you have added Flatex to _data/domains.yml. Could you please move the site to [_data/finance.yml](https://github.com/2factorauth/twofactorauth/blob/master/_data/finance.yml)? 

For the icon you can copy the [favicon](https://www.flatex.de/favicon.ico) and paste it into a image editing program. Save it as a PNG file and add it to this pull request by pushing a commit to the [patch-1 branch on your fork](https://github.com/paradonym/twofactorauth/tree/patch-1). 

If you need any help search [GitHub Help](https://help.github.com/) or let us know.

**Comment by paradonym** [comment]
replaced by #2952

**Comment by jamcat22** [comment]
Duplicate of #2952

**Pull request closed without merging**
