### PR TITLE
Add NetBenefits Exception to Fidelity

### PR DESCRIPTION
**Pull request by kubla36**
NetBenefits users do not get to use the two factor auth (tried to set up this week and was told no -- worse I have to send land mail to complain).

### CODE REVIEW

**Comment by mxxcon** [comment]
@kubla36 are there different login locations for NetBenefits accounts vs other accounts?
edit:
So it seems like there's www.netbenefits.com which redirects to https://nb.fidelity.com/public/nb/default/home
Then there's also https://login.fidelity.com/ftgw/Fas/Fidelity/IspCust/Login/Init and https://login.fidelity.com/ftgw/Fas/Fidelity/NBPart/Login/Init?ISPBypass=true

**Comment by kubla36** [comment]
I only have netbenfits through my company, and can only login through the
netbenefits web page.  When I called Fidelity, they told me that two factor
was not available for netbenefits (would not provide a token or validate
the VIP software code I downloaded).

Their FAQ does not state clearly but (
https://www.fidelity.com/security/soft-tokens/faqs) if you read between the
lines indicates that netbenefits login page does not support.

I've read other postings on the web (but cannot confirm since I cannot get
a code validated), that netbenefits sites never requires a second factor
even when they have one for the fidelity site.  Defeating the purpose
(hacker goes through the netbenefits site).

**Comment by jamcat22** [comment]
Hm. According to #1320, NetBenefits should support 2FA now. I wonder if they changed their system again.

**Comment by kubla36** [comment]
When I call they say two factor is not offered for netbenefits.  It could
be my particular company's arrangement?  I don't have a regular fidelity
account as mentioned by the person in #1320.

I'd note the security page for netbenfits does not mention two factor (
https://nb.fidelity.com/public/nb/default/resourceslibrary/articles/onlinesecurityatfidelity),
whereas the page for the fidelity site does (
https://www.fidelity.com/security/our-security-measures).

**Comment by Carlgo11** [comment]
I feel like we need some more information about Netbenefits' and Fidelity's TFA arrangements before we can do anything with this PR.
Maybe someone could contact them and ask?

**Comment by stephengroat** [comment]
The document provided by @kubla36 (https://www.fidelity.com/security/soft-tokens/faqs) now shows that netbenefits is supported by "VIP Access" aka 2FA (great rebranding name for 2FA too).

This should probably be closed

**Comment by kubla36** [comment]
I followed the instructions and they did not work.  I called Netbenefits
and they said they were rolling out a new service client by client
(July-August).  However, the service was _not_ "VIP Access", despite what
their FAQ at the Fidelity (not Netbenefits) site says online.  I requested
they update that in the FAQ.

Rather, they said it was going to be text message or email based for "high
risk transactions".

So depending on who you are as a Netbenefits customer, you may or may not
have access.  But soon there will be some form of 2FA.

**Comment by Carlgo11** [comment]
so no 2FA then. And the "high risk transactions" thing you mention is two factor **authorization** and not **authentication**.
Either set `tfa: No` or close the PR.

**Pull request closed without merging**
