### PR TITLE
Added StartJOIN

### PR DESCRIPTION
**Pull request by jamcat22**
Added StartJOIN to Other.
I thought that category suited it better than the original since it is a
crowdfunding platform, not a Bitcoin wallet.
See #1060.

[Review on Reviewable](https://reviewable.io/reviews/jdavis/twofactorauth/1254)

### CODE REVIEW

**Comment by Carlgo11** [comment]
So it's kickstarter with crypto currencies.
Isn't that a bit like finance then?

**Comment by mxxcon** [comment]
This is a bit of a grey area between finance and something else

**Comment by jamcat22** [comment]
Well Kickstarter is in Other, so I thought it would fit there.
It isn't really a Bitcoin wallet because you have to convert whatever it is to StartCOIN. It's also not really designed to hold money.

**Comment by Carlgo11** [comment]
Oh well is kickstarter is in `other` then I guess `other` is the right category.

**Pull request merged**
