### PR TITLE
Update Discover

### PR DESCRIPTION
**Pull request by johnspiegel**
## I asked them about it and got this in response:

Thank you for your message and for opening a new Online Savings Account.  I will be glad to answer your security questions.

The advanced security you have referred to is a program to protect card transactions for Discover credit card holders.  The program does not have any application to your Online Savings, as it is not associated with any credit or debit card transactions.

Your account does enjoy outstanding security in the online transactions and communications.  We employ state of the art encryption and cover your online transactions against all fraudulent activity.

If you have additional questions or need further assistance, please reply to this message or call us at 1-800-347-7000.  Banking Specialists are available 24 hours a day, 7 days a week.

We appreciate your business and the opportunity to be of service.

Thank you for choosing Discover Bank.

Sincerely,

Ralph 

Discover Bank Customer Service

---

DISCOVER and the other trademarks, logos and service marks used in this e-mail are the trademarks of Discover Financial Services or its respective third-party owners.

©2012 Discover Bank, Member FDIC

------- Original Message -------- 
Date : Jun 26, 02014 08:49 PM
Subject : Re: Other Website Questions

How can I enable "enhanced account security" with identification codes? Like talked about here: https://www.discover.com/credit-cards/help-center/faqs/enhancing-account-security.html#q2 

Thanks!

### CODE REVIEW

**Comment by mxxcon** [comment]
It's strange how they phrased _"is a program to protect card transactions"_. Makes it sound like it's not for your accounts but to confirm each purchase..

**Comment by jamcat22** [comment]
@mxxcon Yeah and then they go on to say that "_it is not associated with any credit or debit card transactions_"

**Comment by jdavis** [comment]
Is this good to be merged, @johnspiegel, @jamcat22, @mxxcon?

**Comment by jamcat22** [comment]
I think so.

**Pull request merged**
