### PR TITLE
Added link to Zapier roadmap status

### PR DESCRIPTION
**Pull request by myersjustinc**
It's a few months old, but I noticed it wasn't here yet.

### CODE REVIEW

**Comment by Carlgo11** [comment]
They don't say they are actively working on it. Just that it's planed for the future.

**Comment by myersjustinc** [comment]
Fair enough--saw similar posts used on other entries' "in progress" indications (such as for [Slack](https://twitter.com/SlackHQ/status/448214716192538625)) and figured it might count.

**Comment by mxxcon** [comment]
Which brings up a point regarding #Slack and the fact that they are not working on it, but instead https://twitter.com/SlackHQ/status/492192845038895105 I'll make PR to fix that.

**Comment by myersjustinc** [comment]
Also makes sense. I can close this one if you'd like, then.

**Pull request closed without merging**
