### PR TITLE
Add transport category & Update Semantic-UI

### PR DESCRIPTION
**Pull request by Carlgo11**

### CODE REVIEW

**Comment by Carlgo11** [comment]
yeah that's still not working. Hold on, I'll call the expert...

_Beeeeep... beeeeep... beeeeeep... You've managed to reach @psgs's voice mail. After the beep, please leave a message. beeep!
Hey @psgs I need your help... again._

**Comment by fpigerre** [comment]
Hello @carlgo11,

Unfortunately, I am currently unable to access GitHub, however, I would be
delighted to help as soon as I am able to.

Thanks,
psgs :palm_tree:

**Comment by mxxcon** [comment]
@Carlgo11 perhaps use https://jetsmarter.com/wp-content/themes/jetsmarter/favicon.png

**Comment by Carlgo11** [comment]
@mxxcon done

**Comment by jamcat22** [comment]
Awesome. I think it `looks-good`!

**Comment by fpigerre** [comment]
@Carlgo11, Were you going to pull Carlgo11/twofactorauth#3 in order to ensure that the categories list was legible?

**Comment by Carlgo11** [comment]
Oh I thought I had done that. Thanks @psgs :)

**Comment by Carlgo11** [comment]
So @RichJeanes @mxxcon could anyone merge this? I can confirm that it works locally.

**Comment by RichJeanes** [comment]
I can merge it, but I'd like to check it locally myself, too. I can do that when I get home from work tonight.

**Comment by Carlgo11** [comment]
great. Thanks

**Comment by mxxcon** [comment]
I have no problems with yaml and images, but I'm not in a position to comment on html/css/js.

**Comment by RichJeanes** [comment]
Why do I see the Providers page?
And I don't see a Transport Category or even Utilities...
Okay, what am I doing wrong here?

``` Bash
~/$ git clone git@github.com:Carlgo11/twofactorauth.git
~/$ cd twofactorauth
~/twofactorauth$ git checkout patch-transport
~/twofactorauth$ bundle exec jekyll serve
```

**Comment by RichJeanes** [comment]
Halp? Anyone?

**Comment by Carlgo11** [comment]
Does it work better if you use https instead of ssh?
Except from the icons not being properly displayed it works just fine for me.
pull again? reset --hard?
Just trying to figure out what to do :see_no_evil: 

Also, @psgs do you see icons being much smaller than they are on twofactorauth.org like I do?
localhost screenshot
twofactorauth.org screenshot

**Comment by jamcat22** [comment]
Is there a reason that the checks aren't centered anymore?

**Comment by Carlgo11** [comment]
I'm sure there is. I'm not very good at CSS though. @psgs? Can you help answer our questions?

**Comment by Carlgo11** [comment]
Sadly it looks like I forgot my laptop charger at work and I can't test locally on my PC so... I can't see whether we need to change anything else.

**Comment by Carlgo11** [comment]
Okay I found another laptop laying around #2manyComputers
One last thing @psgs, do you see that this version isn't as centered as the live version on twofactorauth.org?
(See my screenshots from [133626268](https://github.com/jdavis/twofactorauth/pull/1260#issuecomment-133626268) for comparison)

**Comment by fpigerre** [comment]
I don't think I quite see what you mean @Carlgo11.
The following screenshot illustrates what I can see of the main page when I run TwoFactorAuth locally.

Main Page Screenshot

Do you perhaps mean that the main section of the local version is wider than the version that is currently live?

**Comment by jamcat22** [comment]
@psgs What about making the Twitter button centered?

**Comment by Carlgo11** [comment]
@psgs yeah wider probably is a better word for it. I guessed maybe you had forgotten to add a div or something. If it's not a quick fix I'm guessing it's already anyways.
We'll probably have to get @jdavis in here to give his approval though.

**Comment by jamcat22** [comment]
Do we think it `looks-good`?

**Comment by fpigerre** [comment]
In my opinion, this pull request seems to look good :+1:

**Comment by jdavis** [comment]
There's definitely some tidying up that can be done but other than it looks good! Nicely done. :+1:

I'll be submitting a PR soon with some things I think could/should be adjusted.

**Pull request merged**
