### PR TITLE
Add Bluesky

### PR DESCRIPTION
**Pull request by eternalyperplxed**

### CODE REVIEW

**Comment by hkamran80** [comment]
Given that the default Bluesky provider is invite-only at the moment, should it be listed now or should we wait for general availability?

**Comment by eternalyperplxed** [comment]
Fair point, I've seen it being talked about frequently in the public discourse, but it may not have the user base to warrant listing.

**Comment by hkamran80** [comment]
As have I. I would recommend closing this PR for now, then reopen it when it goes GA.

**Comment by eternalyperplxed** [comment]
Sounds good, appreciate the feedback.

**Pull request closed without merging**
