### PR TITLE
Add LastPass Info

### PR DESCRIPTION
**Pull request by ianklatzco**
I added information for LastPass, a cloud-based password manager. Since there's no security section, I figured it fits under SaaS. There are a few alternate security methods, such as a fingerprint/card reader and a type of printable grid. 

Full info here: https://helpdesk.lastpass.com/security-options/multifactor-authentication-options/

PS please pardon me if I'm breaking any Github netiquette. I'm somewhat new here :3

### CODE REVIEW

**Comment by RichJeanes** [comment]
If you could make that icon 32x32 as per the README guidelines, that would be fantastic.
(Never mind on the icon comment! Saw the fix!)

**Comment by ianklatzco** [comment]
Would a 512/512 work?- Ian Klatzco.

**Comment by jdavis** [comment]
512x512 is too large =[

**Comment by RichJeanes** [comment]
Trying to keep it consistent to 32x32. If you're on Windows, you can just open the image in Paint and resize it. Mac and Linux, you can try GIMP, though it's a little more complex if you aren't familiar with it.

**Comment by RichJeanes** [comment]
A quick Google search found this tool if you aren't sure how to do it on your platform: http://www.picresize.com/

**Comment by jdavis** [comment]
As a side note, @RichJeanes, you've been promoted to Collaborator. Keep up the great work, dude. Seriously.

**Comment by ianklatzco** [comment]
lastpass (no access to my main pc, I'll commit it later tonight).

I'm not sure how to fix the newline error, though.

**Comment by ianklatzco** [comment]
https://github.com/jdavis/twofactorauth/pull/161 is a little more complete than this. Closing.

**Pull request closed without merging**
