### PR TITLE
Add Scrive.com

### PR DESCRIPTION
**Pull request by jonathanjouty**
[Alexa rank 110,926](https://www.alexa.com/siteinfo/scrive.com).
Unfortunately no documentation, but we should add some soon!

### CODE REVIEW

**Comment by Carlgo11** [comment]
Hi @jonathanjouty,
have you added any documentation yet?
If not, could you attach screenshots for setting up 2FA on the site? (With any personal information blurred out)

Once we get that, the PR can be merged.

**Comment by kmpoppe** [comment]
> Hi @jonathanjouty,
> have you added any documentation yet?

Is there a link in your help center for 2FA https://support.scrive.com/hc/en-us ?

> If not, could you attach screenshots for setting up 2FA on the site? (With any personal information blurred out)

**Comment by Rfosu2k2** [comment]
The last 90 days on alexa show it going from 100k -> 255k currently.  It does not meet guideline #4, and this request could potentially be closed based on not meeting that criteria.

**Comment by Carlgo11** [comment]
Closing as there's no documentation and the site is >200K on Alexa

**Pull request closed without merging**
