### PR TITLE
Update WiseBanyan with an exception

### PR DESCRIPTION
**Pull request by p4gs**
WiseBanyan doesn't enforce 2FA for initial login. It only enforces 2FA when an authenticated user attempts to update profile information, security information, or access tax documents. See more here: https://wisebanyan.com/faq/my-account/how-does-two-step-verification-work

### CODE REVIEW

**Comment by mxxcon** [comment]
According to our definition at https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions this is two-factor "authorization", not authentication. As such this entry should be updated to be `tfa: no`

**Comment by Carlgo11** [comment]
Hello @p4gs,
will you update your PR with the changes @mxxcon requested?

Please respond within a couple of days or I'll close this PR due to inactivity.

//@Carlgo11 :tay:

**Comment by p4gs** [comment]
Will do, sorry about the delay

**Comment by Carlgo11** [comment]
Don't think the exception text is needed.

**Comment by p4gs** [comment]
Removed exception text

**Pull request merged**
