### PR TITLE
Update OpenSRS TFA

### PR DESCRIPTION
**Pull request by helpquick**
OpenSRS now support TFA

### CODE REVIEW

**Comment by mxxcon** [comment]
@helpquick that URL talks about "Reseller" accounts. Does it mean it's not available to "non-reseller" accounts?

**Comment by helpquick** [comment]
@mxxcon I believe that if I give a user access to their domains directly on OpenSRS, they can enable 2FA if they want to... So, yes, they support it for non-resellers too.

**Comment by helpquick** [comment]
@mxxcon Original tweet I received back after asking them to support 2FA had this url in it: http://bit.ly/1XmdR0m which expands to the link I put in the edit.

**Comment by jamcat22** [comment]
Could you update your PR to not re-add iWelcome? Our revert #1382 might have messed up your PR.
If you want, you can also remove the `twitter:` line as it's not needed if a provider has TFA.

**Comment by Carlgo11** [comment]
@helpquick are you going to update the PR? If not I'll mark the PR as inactive.

**Comment by jamcat22** [comment]
@Carlgo11 It looks like it's fixed.

**Pull request merged**
