### PR TITLE
Add Google Fit to Health

### PR DESCRIPTION
**Pull request by whatinthenameofgod**

### CODE REVIEW

**Comment by mxxcon** [comment]
@whatinthenameofgod let's hold off on adding every possible Google service out there. Since they all use the same account, that's a lot of redundant data.
It's better to come up with some sort of unified and all-encompasing Google listing to address them all.

**Comment by whatinthenameofgod** [comment]
It would be helpful to have one Google line item, but at the same time, that account encompasses a lot of products that I think should be listed categorically where relevant.

Is there a way to have a higher-level, all-encompassing Google account and then have the Play Store, Fit, Fiber, etc listed in their relevant categories and just referencing the Google account?

This kind of model could be used for all-encompasses services like Microsoft, Apple.

**Comment by RichJeanes** [comment]
Well, unfortunately, that isn't a thing for Apple. See #975 about that. And I think there's a thing or two with Microsoft that isn't protected, too, isn't there?

**Comment by jamcat22** [comment]
@RichJeanes Microsoft protects everything that uses a Microsoft account. The only two products that are possibly not protected by Microsoft 2FA are Skype (when using a Skype account to login or when using Facebook sign-in) and HealthVault (when using Facebook sign-in or when using an OpenID to login).

@whatinthenameofgod We're looking for a way to do this without switching from our YAML structure.

I'll merge this PR right now, until we can come up with a better solution in the future.

**Pull request merged**
