### PR TITLE
Add raygun

### PR DESCRIPTION
**Pull request by harley1984**

### CODE REVIEW

**Comment by stephengroat** [comment]
thanks for the pr @harley1984!

I looked over the `doc` link and didn't see any explicit mention of `phone` support. does raygun support automated phone calls for 2fa?

**Comment by harley1984** [comment]
@stephengroat Ah is that what you mean by phone? I couldn't see any definition (or missed it). Sorry, we were thinking mobile app. No we do not support that and need to remove.

**Comment by stephengroat** [comment]
no problem. our `software` tag is for TOTP/HOTP type apps.

thanks!

**Review by stephengroat — APPROVED** [review]

**Review by jamcat22 — APPROVED** [review]

**Comment by jamcat22** [comment]
Thanks for the PR @harley1984!

**Pull request merged**
