### PR TITLE
Added Box

### PR DESCRIPTION
**Pull request by danieltaylor**

### CODE REVIEW

**Comment by jdavis** [comment]
Then add in the icon and you are good as gold.

**Comment by jdavis** [comment]
I did it for you, great work though =D

**Comment by danieltaylor** [comment]
@jdavis Thanks, can we go higher res on the icon though?  It looks a bit pixelated.

**Comment by jdavis** [comment]
We're discussing increasing the icon size in #84. Go there to watch the updates =]

**Pull request closed without merging**
