### PR TITLE
chunkhost supports 2fa

### PR DESCRIPTION
**Pull request by SergeyTsalkov**

### CODE REVIEW

**Comment by mxxcon** [comment]
Is there docs link that describes their implementation?

**Comment by SergeyTsalkov** [comment]
Nope, just a link in the control panel to enable! It's google auth based.

**Comment by jdavis** [comment]
We'll need either a link or a custom note regarding the 2FA.

**Comment by mxxcon** [comment]
@jdavis it looks like @SergeyTsalkov is employed by ChunkHost, so I imagine he's familiar with what they offer. :smiley:
Having said that, yes, it would be nice to have it documented somewhere..Not only for this site but for other ChunkHost customers.

Also this pull request is now too much out of sync with `master` to automatically merge.

**Comment by jdavis** [comment]
I can do a manual merge. I just didn't know if he had a link handy, haha. I wasn't questioning that it was available, just wanted a doc link for the users =]

**Comment by jdavis** [comment]
Sorry for the delay!

**Pull request merged**
