### PR TITLE
Add NS1

### PR DESCRIPTION
**Pull request by natedaly**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr @natedaly

**Review by Carlgo11 — APPROVED** [review]

**Comment by natedaly** [comment]
Curious why this hasn't shown up on the site yet. It was merged almost 3 weeks ago.

**Comment by mxxcon** [comment]
@natedaly the site haven't been updated yet.

**Comment by jamcat22** [comment]
@natedaly, for more information on our merging process, please see our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge).

**Pull request merged**
