### PR TITLE
Add TransIP to hosting

### PR DESCRIPTION
**Pull request by JasperV**

### CODE REVIEW

**Review by Jawshy — DISMISSED** [review]
Thanks for submitting a pull request, @JasperV. ~Could you please add `lang: nl` on a new line below `doc`?~

**Comment by Carlgo11** [comment]
@Jawshy I don't think that's needed as they already have 2FA

**Comment by Jawshy** [comment]
Oh, of course.

**Comment by Carlgo11** [comment]
Oh come on GitHub. Do what I want! >_<

**Comment by Carlgo11** [comment]
Fine I'll make a separate PR with the changes. See #2271

**Pull request closed without merging**
