### PR TITLE
added Pinboard, fixed typo

### PR DESCRIPTION
**Pull request by briankelly**
Added pinboard.in to the list (no 2FA, yet), and fixed a small typo in
CONTRIBUTING.

### CODE REVIEW

**Comment by mxxcon** [comment]
@briankelly do you think it fits https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria ?

**Comment by briankelly** [comment]
@mxxcon Yes.

> The following is a rough criteria and explanations for what sites should be on 2FA.org. If one of the following Criteria is met, it belongs on 2FA.org:
> 1. Personal Info/Image: Any site that deals with personal info or a person's image. An example of a site with Personal Info would be their Amazon account and a site regarding Personal Image would be one like Twitter.
> 2. Data: This means data that is either important or sensitive. It also is any data relating to Criteria 1.
> 3. Money: Any site that deals with money.
> 4. Control: This is a more general Criteria that includes sites that give access to things that might infringe upon Criteria 1, 2, and 3. An example of this is a site that allows remote access.
>    If you have any questions regarding whether or not a site matches one of the Criteria, just open an Issue and we'll take a look.

Pinboard holds a ton of private bookmarks and metadata (comments, notes). It can also archive tweets, and full-text of webpages. It's private by default, but users can optionally make some of their shares public. I consider it to hold similar levels of private info as would be stored in Evernote.

**Comment by Carlgo11** [comment]
To me that doesn't sound like private information. What do you guys think?

**Comment by Walkman100** [comment]
> It can also archive tweets, and full-text of webpages.

If the archived full-text webpages' content is saved through the browser rather than saving the publicly available copy using Pinboards servers, then I'd say it could contain private information, If a user decides to, for example, save their PayPal credit card list through Pinboard (however stupid that is).

**Comment by briankelly** [comment]
First sentence description from of the service, from https://pinboard.in:

> Pinboard is a fast, no-nonsense bookmarking site for people who value privacy and speed.

Accessing someone's list of private bookmarks could be very damaging to that user. This alone should make it relevant to include Pinboard on twofactorauth.org according to "Criteria 2. Data".

**Comment by briankelly** [comment]
@mxxcon, any more questions on Pinboard? This site is a strong candidate for 2FA. Ask other users of it, like @marcoarment.

**Comment by Walkman100** [comment]
Could you explain whether archived full-text webpages content is saved through the users browser or saved through Pinboards servers? (Just something I want to know, not really important)

**Comment by mxxcon** [comment]
@Walkman100 on their site it states:

> For an additional fee, Pinboard offers an archiving service which saves a copy of everything you bookmark, gives you full-text search, and automatically checks your account for dead links.

that sounds like service does everything, not your browser.

I'm on the fence with such an entry.. If you had such "very damaging" bookmarks, why would you store them on an external service..

**Comment by briankelly** [comment]
> Could you explain whether archived full-text webpages content is saved through the users browser or saved through Pinboards servers?

@Walkman100 I believe the archived webpages are saved by Pinboard's servers crawling the bookmarks that users save, directly. 

> I'm on the fence with such an entry.. If you had such "very damaging" bookmarks, why would you store them on an external service..

@mxxcon Couldn't you apply that to argument to any cloud service that stores private information? 

I'm not sure I follow why you are opposed to adding another service, like Evernote, that stores private information on the user's behalf, from having 2FA.

**Comment by mxxcon** [comment]
@briankelly I'm not opposed to ALL services having 2FA. I'm on the fence regarding listing _this_ service on this site.
While technically it can have the same content, I'd consider a free-form Evernote capable of storing a lot more sensitive info than a bookmarking service. And if I had my own version of Snowden document dumps, I wouldn't use either and instead used something more secure.

**Comment by briankelly** [comment]
@mxxcon Thanks for the explanation. You want to make sure that Pinboard.in is _generally_ storing enough private information to warrant inclusion on twofactorauth.org.

While determining this is clearly subjective for less well-known cloud apps, I'd argue that Pinboard outwardly advertising itself as a _private_ bookmarking service places it in the category of requiring more authentication than a password. Another data point worth mentioning is that the site is only available over HTTPS.

Regarding the free-form text capabilities, see below.

Pinboard note taking capabilities

**Comment by briankelly** [comment]
Hi, all. I'm checking in again on this. What additional information do you need to determine if https://pinboard.in should be included on this site?

Given that it meets the criteria specified, I would like to see it added.

**Comment by briankelly** [comment]
Another ping on this… Still waiting for the PR to be merged.

**Comment by Carlgo11** [comment]
Hello @briankelly, 
sorry for the long wait.
I must have accidentally skipped your notifications.

I just read through the conversation above and I definitely think that pinboard.in should be added.

When it comes to the PR there's just one thing I need you to fix. The logo you added is quite large for it's actual size (32x32px). Here's a more compressed version of the logo:
pinboard 1
When you've added that I think the PR is good to go.

Thanks!

//Carl

**Comment by Carlgo11** [comment]
Oh and you need to update. 
I suggest you copy the text 

```
name: Pinboard
url: https://pinboard.in/
twitter: Pinboard
img: pinboard.png
tfa: No
```

And then update your current local version with the remote by doing the following:

```
git remote add upstream https://github.com/jdavis/twofactorauth.git
git reset --hard upstream/master
git pull upstream
(Add your code to _data/other.yml)
(Add the image I provided)
git add _data/other.yml
git add _img/other/pinboard.png
git commit -m "Add Pinboard"
git push --force --set-upstream https://github.com/briankelly/twofactorauth master
```

The code should work. I'm pretty much writing out of my memory right now so tell me if you receive any errors and we'll work that out. :smiley:

**Comment by jamcat22** [comment]
If this PR isn't updated in a few days, I'll make a new one to make sure the site is added. Thanks!

**Comment by Carlgo11** [comment]
So basically all the inactive PRs then?
my "is:open is:pr label:inactive -assignee:jamcat22 " is shrinking rapidly

**Comment by jamcat22** [comment]
Yep. Don’t close them all yet though.

**Comment by Carlgo11** [comment]
I won't. I've put a reminded for Friday.
Maybe sooner if I get bored. (like Thursday evening)

**Comment by briankelly** [comment]
Hi guys. Thanks for bringing this one back up. I'll get the updated PR in
tomorrow, Weds, July 22.

**Comment by Carlgo11** [comment]
Great @briankelly!
You've just made @jamcat22's life a little bit easier. :wink:

**Comment by jamcat22** [comment]
Yay! :smile:

**Comment by jamcat22** [comment]
@briankelly Thanks! `looks-good`

**Comment by briankelly** [comment]
Everything should be good to go. Let me know if you need anything else to merge this PR.

**Comment by Carlgo11** [comment]
@briankelly as I mentioned:

> When it comes to the PR there's just one thing I need you to fix. The logo you added is quite large for it's actual size (32x32px). Here's a more compressed version of the logo:
> pinboard 1
> When you've added that I think the PR is good to go.

**Comment by briankelly** [comment]
@Carlgo11 hmm, I think you might be mistaken. The image I have pushed in the PR is only 2.4 KB. Look below. It's 32x32.

image

**Comment by Carlgo11** [comment]
I know it's 2.4kb. We try to not make logos larger than 2.5kb(+-0.3) so your logo is in the gray area.

If you think about it, a 2.4kb image that's just 32x32px is actually quite big for its actual size

**Comment by briankelly** [comment]
@Carlgo11 ah, got it. Just committed your version. Should be GTG

**Pull request merged**
