### PR TITLE
new section remote control and add teamviewer

### PR DESCRIPTION
**Pull request by victorhaggqvist**
closing #172

### CODE REVIEW

**Comment by jdavis** [comment]
Hey Victor, by remote control do you mean like VNC viewer type apps?

**Comment by victorhaggqvist** [comment]
Yep, like LogMeIn, TeamViewer, VNC and RDP stuff. Maybe it could be "Remote Control & VPN" also.

**Comment by RichJeanes** [comment]
@jdavis So do we want to add a "Remote Access" section or lump these into Developer for now?

**Comment by jdavis** [comment]
I think Remote Access has enough usage that it could be another category.

**Comment by jdavis** [comment]
I think the 'desktop' icon would be a good choice for it as well: http://semantic-ui.com/elements/icon.html

**Comment by jdavis** [comment]
It looks like all of these are added. Sorry for not getting to your PR first.

**Pull request closed without merging**
