### PR TITLE
Correcting Chase info

### PR DESCRIPTION
**Pull request by mxxcon**
Correct wrong info from 62f3bd3. Chase does offer tfa.

### CODE REVIEW

**Comment by jdavis** [comment]
By chance is there a better URL for Chase for the info on 2FA?

**Comment by mxxcon** [comment]
Looking for better URL.

**Comment by jdavis** [comment]
Awesome, you're a champ.

**Comment by computmaxer** [comment]
@mxxcon This PR has merge conflicts, please pull in the latest master to resolve.

**Comment by mxxcon** [comment]
@computmaxer I'm sorry, I can't seem to figure out on which file there's merge conflict

**Pull request closed without merging**
