### PR TITLE
Add Wells Fargo

### PR DESCRIPTION
**Pull request by todd**

### CODE REVIEW

**Comment by zach-taylor** [comment]
Hi @todd this PR has merge conflicts, can you please pull in the latest updates and resolve them? Also, I think we want to stick with png's for the logos.

**Comment by todd** [comment]
Give that a whirl.

**Comment by zach-taylor** [comment]
@jdavis do you think that image is too big?

**Comment by todd** [comment]
Oops, didn't include the resized image. My bad.

**Comment by jdavis** [comment]
Nice work, Mr. Todd! Thanks for taking care of that image.

**Comment by todd** [comment]
:heart:

**Pull request merged**
