### PR TITLE
Add BBVA Argentina and update BBVA Compass

### PR DESCRIPTION
**Pull request by fainpablo**

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
I think this one works better for the small 32x32 size that we use.
logo

**Comment by fainpablo** [comment]
You bet! I just pushed the updated icon.

**Review by Carlgo11 — APPROVED** [review]

**Comment by phallobst** [comment]
Should "BBVA Compass" and "BBVA Argentina" use the same icon? Maybe we could substitute these two by a single "bbva.png".

**Comment by fainpablo** [comment]
Good catch. Looks like they're using the same branding worldwide now. I've just updated the logo and the reference on both BBVA Argentina and Compass.

**Review by phallobst — APPROVED** [review]

**Pull request merged**
