### PR TITLE
Add Login.gov

### PR DESCRIPTION
**Pull request by Sunit-Kulkarni**
Added US Government's new Single Sign on Feature. So far it works on USAjobs website and should soon be rolling out to more services. Finally OPM learned its lesson since the 2015 hack debacle.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Wow finally a shared authentication standard between agencies? 😮
*\*Hoping for a digital ID and signing standard 🙏\**

**Review by jamcat22 — CHANGES_REQUESTED** [review]
Let’s use login-gov.png as the file name to avoid any file extension issues.

**Comment by jamcat22** [comment]
Just for some background, Login.gov is also currently used for applying to and managing [Trusted Traveler Programs](https://ttp.cbp.dhs.gov/). It was created by [18F](https://18f.gsa.gov/), an office within the U.S. government’s [General Services Administration](https://www.gsa.gov/) that’s structured around building technology solutions much like a startup would. I highly recommend reading some of their [blog posts](https://18f.gsa.gov/blog/), and if you’re feeling in the mood to contribute, see some of their [GitHub projects](https://github.com/18f) (including [Login.gov’s project](https://github.com/18F/identity-idp)). It’s definitely interesting to see such a different and more open source approach taken to tech-related government service development. 🙂

**Comment by Sunit-Kulkarni** [comment]
Cool Stuff. Now if only i can find a photo that when i resize it to 32 x 32 it stays below 2500 bytes. I've done this before without a hitch.

**Comment by jamcat22** [comment]
Try using [tinypng.com](https://tinypng.com)

**Comment by Sunit-Kulkarni** [comment]
Alrighty. All is good to go! Thanks for the tinypng trick!

**Comment by Sunit-Kulkarni** [comment]
Nice catch! Nearly forgot about that one.

**Review by jamcat22 — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
