### PR TITLE
Add MLP

### PR DESCRIPTION
**Pull request by phallobst**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Michael! :disappointed:
ssllabs report

**Comment by Carlgo11** [comment]
What's Sm@rt-TAN and is it a relevant thing to also list?

**Comment by phallobst** [comment]
The method is called "Sm@rt-TAN plus" (so fancy!), but you actually use a TAN generator (together with your bank card) - so that's the `custom-hardware` one.

**Review by Carlgo11 — APPROVED** [review]
My Little Pony Credit Union

**Pull request merged**
