### PR TITLE
add spark post

### PR DESCRIPTION
**Pull request by jae-63**

### CODE REVIEW

**Comment by mxxcon** [comment]
Please delete _data/.communication.yml.swp file

**Comment by jae-63** [comment]
hopefully I've successfully removed this stray .swp file

**Comment by Carlgo11** [comment]
Isn't 1.8KB a bit big for the logo? How about this one: sparkpost logo
It's just 322B

**Comment by jae-63** [comment]
That's fine, but there are lots of other 2KB logos elsewhere in that
directory.

Do you need/want me to make the replacement?

**Comment by Carlgo11** [comment]
So why not lead by example?
Yes, please replace the logo

**Comment by jae-63** [comment]
OK, hopefully I did that (replaced the GIF with your smaller version) correctly.   I have lots of experience with SCCS, RCS, CVS, SVN, and Mercurial .  But I'm not too good at Git yet.

**Comment by jae-63** [comment]
I realize that there was some confusion, but I believe that this is now ready to be merged-in.   Thanks in advance for that ...

**Pull request merged**
