### PR TITLE
Add State Farm

### PR DESCRIPTION
**Pull request by rjonesxmoz**

### CODE REVIEW

**Comment by stephengroat** [comment]
@rjonesxmoz could you include an image in the `banking` folder for the State Farm logo? I should be `32x32` and as small as possible (definitely under 2.5k)

**Comment by rjonesxmoz** [comment]
I get an error when trying to upload but here is a 32x32 crushed PNG for the StateFarm logo. Im excited about this, hopefully we can encourage them to add 2FA! crazy a bank+insurance company doesnt have it yet.

http://imgur.com/a/bhOrM

**Comment by stephengroat** [comment]
should be fixed! thanks for the image

**Review by stephengroat — APPROVED** [review]

**Comment by fpigerre** [comment]
Thanks for the pull request @rjonesxmoz! 👍

**Comment by rjonesxmoz** [comment]
When do merged sites go live so I can start tweeting them about adding 2 factor auth?

**Comment by Carlgo11** [comment]
@rjonesxmoz check out our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge) for more information on how the merge process works.

**Pull request merged**
