### PR TITLE
Update fidelity logo in /notes

### PR DESCRIPTION
**Pull request by mxxcon**

### CODE REVIEW

**Comment by Carlgo11** [comment]
32nkc_co?

Also, is it just on my end or is your image 15KB? That should have made Travis fail 🤔

**Comment by Carlgo11** [comment]
Ah, just noticed it's for notes. That explains it!

But it doesn't looks like the notes page uses any logo?

**Comment by mxxcon** [comment]
Unless you have some filtering, I see logos on https://twofactorauth.org/notes/

**Comment by Carlgo11** [comment]
Ah, I only looked at https://twofactorauth.org/notes/fidelity/.

**Review by Carlgo11 — APPROVED** [review]

**Review by fpigerre — APPROVED** [review]

**Pull request merged**
