### PR TITLE
Add Nintendo Network to Gaming

### PR DESCRIPTION
**Pull request by whatinthenameofgod**

### CODE REVIEW

**Comment by Carlgo11** [comment]
It doesn't seem like their Twitter handle is monitored. also, it looks like "Nintendo Network" is only accessible through the Wii U and 3DS (and not the general Internet).

I don't know how we stand towards "hidden networks" being listed on the site but will let the other contributors have their say on that.

**Comment by esnard** [comment]
Actually Nintendo Network can be browsed on the general Internet:
- https://miiverse.nintendo.net/
- https://eshop.nintendo.net/ ([example URL](https://eshop.nintendo.net/JP/ja/titles/20010000006506/aocs))
- https://www.nintendo.com/eshop/buy-digital/

**Comment by whatinthenameofgod** [comment]
And here, too: 

https://supermariomakerbookmark.nintendo.net/

**Comment by whatinthenameofgod** [comment]
Also here... https://id.nintendo.net/login

**Comment by jamcat22** [comment]
Should we remove the Twitter handle, as it's not monitored?

**Comment by whatinthenameofgod** [comment]
You're right. That would require Nintendo actually listening to its fans. Oooo yes shots fired!

I'll remove it in the morning.

**Comment by mxxcon** [comment]
I say keep it. One of the uses for this site is public shaming. If Nintendo doesn't monitor their own twitter account it's their loss. Let them loose reputation in public eyes.

**Comment by fpigerre** [comment]
Thanks for the pull request @whatinthenameofgod! :+1:

**Pull request merged**
