### PR TITLE
Add Cognalys

### PR DESCRIPTION
**Pull request by anishmenon**
Docs section edited.

### CODE REVIEW

**Comment by Carlgo11** [comment]
You need a 32x32px logo. Use git out your workstation to add the logo since you can't upload files on github.

**Comment by anishmenon** [comment]
Can i fork and commit ?

**Comment by Carlgo11** [comment]
You don't need to create a new PR every time you add something. If you push to the same branch you're PR is about then it'll automatically be pushed to the PR.

**Comment by Carlgo11** [comment]
@anishmenon fork what?

**Comment by anishmenon** [comment]
When a git clone and commit changes after it says permission denied .

**Comment by Carlgo11** [comment]
Maybe you're trying to push to our repo instead of yours then.

```
git clone https://github.com/anishmenon/twofactorauth.git
git checkout patch-2
```

**Comment by anishmenon** [comment]
Can you please tell me the right way to contribute . Without Ruby

**Comment by anishmenon** [comment]
Ok

**Comment by anishmenon** [comment]
Branch patch-2 set up to track remote branch patch-2 from origin.
Switched to a new branch 'patch-2'

To https://github.com/anishmenon/twofactorauth.git
   68a54d4..d430f88  master -> master

**Comment by Carlgo11** [comment]
@anishmenon There are lots of documentation on how to use git.  
https://google.com/search?q=how+to+use+git

Git is a wonderful tool that would probably help you in your line of work as well. I suggest you check it out more deeply.

**Comment by anishmenon** [comment]
Thanks for that  . I'm new to contribution . That's why i got doubts . I think I've committed it can you please check ?

**Comment by Carlgo11** [comment]
no @anishmenon, it hasn't been push here. If it had, there would be another notice here saying you've added another commit.

**Comment by anishmenon** [comment]
This is my terminal output 

To https://github.com/anishmenon/twofactorauth.git
   d430f88..11e5f5a  master -> master

Already on 'patch-2'
Your branch is up-to-date with 'origin/patch-2'

**Comment by anishmenon** [comment]
@Carlgo11  . Can you please check

https://github.com/anishmenon/twofactorauth/tree/patch-2

**Comment by smholloway** [comment]
@anishmenon You're being very disrespectful of @Carlgo11 's time. While it would be nice to teach everyone git and the GitHub workflow, there's simply not enough time. Luckily, hundreds of articles have been written on how to do it. Please read how to create a pull request on GitHub before asking anymore questions.

**Comment by smholloway** [comment]
Read [how to contribute](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#new-sites). Your pull request should only touch one `.yml` file and add a 32x32 png.

More directly: remove your file ending in a tilde (`~`) and pick _one_ category for your service.

**Comment by anishmenon** [comment]
@smholloway   . Please check that i've created new category for cognalys 'mobile number verification' . and deleted all other duplicates and committed

**Comment by smholloway** [comment]
Wow. This is the least care that I've seen in a pull request to twofactorauth.org.
- You broke the `developer.yml` file. This breaks the build--you've broken the first guideline from `CONTRIBUTING.md`.
- You checked in a garbage `developer.yml~` file.
- You added a line to the `security.yml` file.

Beyond that, Cognalys is not a new category. And from what I can tell, Cognalys doesn't fit the [site criteria](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria).

Are you trying to get [added to the 2FA provider page](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#new-providers)?

**Comment by anishmenon** [comment]
Please find .

https://github.com/jdavis/twofactorauth/pull/949

i've fixed all issues . wish to see merged .

**Pull request closed without merging**
