### PR TITLE
Added Ping Identity to Providers

### PR DESCRIPTION
**Pull request by allynf**
Documentation is here: http://documentation.pingidentity.com/pingid/pingidAdminGuide/

### CODE REVIEW

**Comment by Carlgo11** [comment]
@allynf I don't see anything about phone calls or SMS on that site?

**Comment by Carlgo11** [comment]
Okay never mind. I found a doc about it. Looks good!

Thanks for contributing! :smiley:

**Comment by smholloway** [comment]
Ping is a single sign on provider (SSO), isn't it? I don't think we have any SSOs in the provider section; it might be a better fit in a new section (`Identity` or `SSO` or something) on the main page.

**Comment by jamcat22** [comment]
@smholloway They also provide 2FA for websites. (https://www.pingidentity.com/en/products/capabilities/multi-factor-authentication.html)

**Comment by smholloway** [comment]
Oh, I followed the `pingIdAdminGuide` link in the comments instead of the `url` link in the PR. PingID is the 2FA offering--got it :+1:

**Comment by jdavis** [comment]
Thanks for taking a look at this, @smholloway, @Carlgo11, and @jamcat22.

**Pull request merged**
