### PR TITLE
Update TransferWise to have TFA for SMS and Phone

### PR DESCRIPTION
**Pull request by tyiu**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr @tyiu

**Comment by Carlgo11** [comment]
The doc link doesn't mention how the authentication works. Are you required to use 2FA every time you log in? Is it only when performing certain actions?

**Comment by tyiu** [comment]
@Carlgo11 They have a different doc explaining how it works, but not how to enable it: https://transferwise.com/help/topics/4/topics/19/questions/2597959/what-is-2-step-login

Should I link to that URL instead?

To answer your question, you are required to use 2FA every time you log in after you have enabled it. They also claim, in that URL, that "In order to keep your money safe, setting up 2-step is mandatory when using certain features of your account, including uploading money and setting up account numbers."

**Comment by Carlgo11** [comment]
@tyiu No the current doc link is fine. I just wanted to know how they have implemented 2FA.
One last thing. They don't mention 2FA via phone calls. Do they actually support that?

**Comment by tyiu** [comment]
@Carlgo11 Sounds good. Yes, they can call you with a code. Just tried it out!

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
