### PR TITLE
Update Steam

### LINKED ISSUE #4554: Steam Guard 2FA
Although the website lists software token, Steam Guard also works with email, so that should be checked as well

https://support.steampowered.com/kb_article.php?ref=4020-ALZM-5519#enableemail

### PR DESCRIPTION
**Pull request by Jawshy**
Resolves https://github.com/2factorauth/twofactorauth/issues/4554

### CODE REVIEW

**Comment by Carlgo11** [comment]
I think the email option is just as a backup.

**Comment by CKingX** [comment]
Not quite. Steam Guard only asks it once per computer/browser even after you logout. But, if you try to login to a different computer on Steam or in a different browser, it will require you to enter the code on the email. But, you do need to verify your email for this to work.

**Review by Carlgo11 — APPROVED** [review]

**Comment by phallobst** [comment]
Should the doc be updated to https://support.steampowered.com/kb_article.php?ref=4020-ALZM-5519 as well? The explain both options there:
- How do I enable Steam Guard via email?
- How do I enable Steam Guard via my smartphone?

**Comment by CKingX** [comment]
Might as well

**Comment by phallobst** [comment]
Please merge the _master_ branch into yours to resolve the _workflow_ check failure.

**Comment by Jawshy** [comment]
Done.

**Review by phallobst — APPROVED** [review]

**Pull request merged**
