### PR TITLE
Add Bugsnag

### PR DESCRIPTION
**Pull request by martin308**
[Bugsnag](https://bugsnag.com) supports 2FA

### CODE REVIEW

**Comment by Carlgo11** [comment]
@martin308 the logo is too big.
Here's a compressed version:
bugsnag 1

**Comment by Carlgo11** [comment]
@martin308 Are you going to fix this?

**Comment by martin308** [comment]
Totally, sorry for the drive by PR :( I will get this fixed up tomorrow

**Comment by martin308** [comment]
@Carlgo11 does that look better?

**Comment by martin308** [comment]
Thanks @Carlgo11 :smile:

**Pull request merged**
