### PR TITLE
Update status for Vanguard

### PR DESCRIPTION
**Pull request by russelldavis**
The New York Times article says Vanguard has committed to adding 2FA by the end of 2014.

### CODE REVIEW

**Comment by Carlgo11** [comment]
@russelldavis Can you make the link https?

**Comment by mxxcon** [comment]
Oh hey! That article mentions this site and @jdavis :smile:

**Comment by jdavis** [comment]
I really want to link to something saying this, I just don't know if this article is the best thing.

Yeah @mxxcon, he emailed me this past week and said he wanted to chat because he was going to include security stuff in his weekly financial post. There definitely have been an influx of issues/tweets since then, so that's great of Ron.

**Comment by jdavis** [comment]
I just Tweeted at them so I'll see if I can get a better confirmation than that article.

**Comment by jdavis** [comment]
K, they tweeted back. The link should be this instead: https://twitter.com/Vanguard_Group/status/499260535360466944

**Comment by russelldavis** [comment]
Updated.

**Comment by jdavis** [comment]
Great. Thanks @russelldavis. Once we fix our Travis issues tonight, I'll merge this.

**Comment by jdavis** [comment]
Rerunning the Travis build. It should succeed now.

**Comment by jdavis** [comment]
Thanks for the update and patience, @russelldavis!

**Comment by mxxcon** [comment]
(ahem, didn't we want only tweets for "in progress", not "coming soon"?)

**Comment by jdavis** [comment]
Oh yeah, I didn't read it as "coming soon". That's my bad.

**Pull request merged**
