### PR TITLE
Added Vultr to Cloud

### PR DESCRIPTION
**Pull request by kulinacs**
Added the site Vultr to the Cloud category

### CODE REVIEW

**Comment by kulinacs** [comment]
Just realized it didn't build. Will reopen when fixed

**Comment by jamcat22** [comment]
Hello @kulinacs!

Could you use this compressed logo instead?
vultr

Thanks!

**Comment by kulinacs** [comment]
Updated with new icon

**Comment by Carlgo11** [comment]
What kind of hardware based TFA do they support?

**Comment by kulinacs** [comment]
Yubikey exclusively.

**Comment by Carlgo11** [comment]
Okay thanks for the clarification :)

**Comment by RichJeanes** [comment]
Perhaps a proper doc link would include how to enable 2FA?
https://www.vultr.com/docs/using-two-factor-authentication-to-login-to-vultr-control-panel

**Pull request merged**
