### PR TITLE
Add Newgrounds [Social]

### PR DESCRIPTION
**Pull request by Jawshy**
#### Changes:
- Added: [Newgrounds](https://www.newgrounds.com/) under entertainment. 
  - No TFA. Dodgy HTTPS support. [Twitter handle](https://twitter.com/Newgrounds). [Facebook page](https://www.facebook.com/newgrounds/). 

> **Newgrounds** is an American entertainment and social media website and company. 

\- [From Wikipedia, the free encyclopedia](https://en.wikipedia.org/wiki/Newgrounds)

### CODE REVIEW

**Review by stephengroat — COMMENTED** [review]
how does this site apply to the criteria?

**Comment by Jawshy** [comment]
[Personal image](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) - similar to sites like DeviantArt.

**Review by stephengroat — APPROVED** [review]

**Comment by Carlgo11** [comment]
Is it entertainment though?

**Comment by Jawshy** [comment]
@Carlgo11, I would consider it to be. Consider YouTube - one of the sites under entertainment - it allows anyone to share (nearly) any genre or type of video. Newgrounds can be used to share videos, games, music, art, and literature. Do you have a suggestion for a different category?

**Comment by mxxcon** [comment]
To me newgrounds is first and foremost a gaming site.. hmm

**Comment by Carlgo11** [comment]
Or social maybe?

**Comment by Jawshy** [comment]
It doesn't really fit any one category 100%.

**Comment by Carlgo11** [comment]
You've described it as a similar site to devianart and since that site is in social I just assumed social would fit the best

**Comment by Carlgo11** [comment]
still think social fits the best. Please move it to that category

**Comment by Jawshy** [comment]
Moved.

**Pull request merged**
