### PR TITLE
Add vodafone

### PR DESCRIPTION
**Pull request by stephengroat**
no easy link to direct link to support doc, it uses too much js

### CODE REVIEW

**Comment by mxxcon** [comment]
Where can we see anything related to their 2fa?
And i guess this is for internal employees? https://ca.vodafone.com/tfa/symtfa.jsp

**Comment by stephengroat** [comment]
You can search "why have i been asked to verify my identity and or " in vodafone support or view this lovely YouTube video - https://youtu.be/hyOg4XCFkE8

**Comment by Carlgo11** [comment]
**mmmmmmerge conflict!** :loudspeaker:

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
@2factorauth/collaborators

**Pull request merged**
