### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by euivanw**
Add Registro.br (Brazillian Company) in category Domains.

### CODE REVIEW

**Comment by euivanw** [comment]
registrobr

**Comment by jdavis** [comment]
Hang tight and we'll try to get around to this when we add the International page.

**Comment by Carlgo11** [comment]
Can we close this one?

**Comment by RichJeanes** [comment]
Considering it is a modification to main.yml? I think so...
@ivanwhm If you still want to see this added, then submit a new PR from an up to date fork and we'll review it. As soon as we figure out a good region flagging system...

**Pull request closed without merging**
