### PR TITLE
Add SecSign

### PR DESCRIPTION
**Pull request by HiDeveloperDev**

### CODE REVIEW

**Comment by dsoegijono** [comment]
Can you add the image? Also, you don't have to open a new PR every time. Just add a commit to this branch.

**Comment by HiDeveloperDev** [comment]
Hi Dsoegijono,

I could not find upload section in img folder :( . the image icon is below

https://www.dropbox.com/s/fmxc00cqmqhi844/sec-logo.png

Thanks again for your quick reply

**Comment by dsoegijono** [comment]
@HiDeveloperDev I see. I'll try to see if I can add the image for you. Otherwise, we'll have to wait for someone more experienced in Git. :)

**Comment by HiDeveloperDev** [comment]
sure thanks again :)

**Comment by jdavis** [comment]
:+1:

**Pull request merged**
