### PR TITLE
Add Delighted

### PR DESCRIPTION
**Pull request by mkdynamic**
Could not find an appropriate section for our business (we help companies get feedback from their customers), so added a new one "SaaS". Let me know if you can think of something better.

Also, the icon PNG I added is 32x32 for Retina support (we do that for our real favicon). Is that legit?

### CODE REVIEW

**Comment by mpdavis** [comment]
I would say that SaaS is a good section to add things like this to.   

Do you guys have any 2FA docs that are available publicly?  If not, it isn't a huge deal.

**Comment by mkdynamic** [comment]
@mpdavis We don't have any docs on 2FA unfortunately.

**Comment by computmaxer** [comment]
@mkdynamic This PR has merge conflicts, please pull in the latest master to resolve. Thanks!

**Comment by mkdynamic** [comment]
@computmaxer You prefer me to merge master or rebase and force push?

**Comment by mpdavis** [comment]
@mkdynamic Merging master is fine.

**Comment by mkdynamic** [comment]
Done. Thanks folks.

**Comment by mpdavis** [comment]
+1

**Comment by jdavis** [comment]
It's missing a t in Delighted =]

**Comment by mpdavis** [comment]
I just fixed it directly on master.  That Github editor is so handy.

**Comment by mkdynamic** [comment]
Oops, thanks! Yea, I have a theory that Github editor's biggest impact on open source is better README's/comments and less typos :)

**Pull request merged**
