### PR TITLE
Added timetotrade

### PR DESCRIPTION
**Pull request by DomBlack**
Added timetotrade, which supports TOTP, HOTP, SMS and Yubikey 2FA methods.

### CODE REVIEW

**Comment by computmaxer** [comment]
Can you find a link to their TFA documentation and add it to this PR? Thanks!

**Comment by DomBlack** [comment]
They don't have a page on their wiki, but the initial setup screen explains the process quite well before you click "Setup".

**Comment by jdavis** [comment]
I have to login to view the link, https://www.timetotrade.eu/user/security/, is there any other link that you can find?

**Comment by DomBlack** [comment]
Not that you can access without a login. It's why I originally didn't link to it.

**Comment by mpdavis** [comment]
@DomBlack There is a merge conflict with this PR, can you update it?

**Comment by RichJeanes** [comment]
I don't mean to nit-pick but would you mind making the icon 32x32 as per the README Guidelines?

**Comment by jdavis** [comment]
The icon hasn't been fixed in almost 3 months. I'm closing this.

**Pull request closed without merging**
