### PR TITLE
Cloudinary now supports TFA

### PR DESCRIPTION
**Pull request by ranrub**

### CODE REVIEW

**Comment by Carlgo11** [comment]
the `doc` isn't public :\

**Comment by Carlgo11** [comment]
Add the logo here instead. Commits pushed to `patch-1` will automatically be pushed to this PR.

**Comment by ranrub** [comment]
It's the signup link with instructions, indeed available only for signed-in users. Do these need to be publicly available? I can just remove it if so (many services don't have a doc).

**Comment by Carlgo11** [comment]
@ranrub I'm not sure what our standpoint is on non-public doc links.
Let's wait on another collaborator to answer that.  
Meanwhile you could add that 32x32px logo :)

**Comment by smholloway** [comment]
How can we approve the addition if we can't validate the claim that the service supports 2FA?

**Comment by mxxcon** [comment]
@smholloway If @ranrub could post a screenshot from that docs url, i think that should be good enough.

**Comment by ranrub** [comment]
Here's the screen shot requested:
screen shot 2015-02-06 at 9 23 31 am

**Comment by Carlgo11** [comment]
@ranrub what about the 32x32 px logo?

_You can't add the logo on github. Use a git client to upload it to your branch_

**Comment by mxxcon** [comment]
Looks like the original repo was deleted? @ranrub Do you still want this added?

**Comment by dsoegijono** [comment]
Removed looks-good label. Doesn't seem to have icon.

**Comment by dsoegijono** [comment]
Actually, as @mxxcon mentioned, repo was deleted. Closing this PR unless @ranrub wants to reopen.

**Comment by Carlgo11** [comment]
@dsoegijono it doesn't have a icon in the files changes because it's just an update.
but yeah. seems reasonable to close the pr if the branch is deleted. :+1:

**Pull request closed without merging**
