### PR TITLE
Add ICUK to hosting category

### PR DESCRIPTION
**Pull request by simonp22**

### CODE REVIEW

**Comment by mxxcon** [comment]
Can you please explain why this qualifies as a utility?

**Comment by simonp22** [comment]
ICUK is a provider of telecoms and broadband utilities, as well as hosting and domains.
If you think this would fit better in another category, let me know and I will correct this.

**Comment by mxxcon** [comment]
I don't think this what people would expect from `utility` category. I think `hosting` or maybe even `other` would be a better fit for this.

**Comment by simonp22** [comment]
Now moved ICUK to the hosting category

**Pull request merged**
