### PR TITLE
Added email provider Posteo.

### PR DESCRIPTION
**Pull request by rose85dol**

### CODE REVIEW

**Comment by Carlgo11** [comment]
`"Alternatively, you could use special hardware, such as a Yubikey."` Looks like they support hardware as well

**Comment by rose85dol** [comment]
It's TOTP, so yes, you can use TOTP (RFC6238) compatible hardware.

Would love to have the columns "FIDO U2F ready" and "TOTP (RFC6238)"!

**Comment by Carlgo11** [comment]
This has been brought up already and we've decided not to add this (at least for now).

**Comment by mxxcon** [comment]
@Carlgo11 I'd be hesitant to add `hardware` parameter.
While it says it support Yubikey, it sounds more like Yubikey implemented some mechanism to program TOTP into your yubikey device...at least that's my understanding. As such I'm not sure if we'd have to mark every other site with `hardware: yes`.

**Comment by Carlgo11** [comment]
@mxxcon Companies add the craziest "security" ideas nowadays don't they?
What happened to the, "don't try to make your own login system"?!

And they describe their security in vague and incomprehensible ways.
I've even got the response from big companies "your password is safe but we can't tell you how". Right...

**Comment by RichJeanes** [comment]
Not sure whether this is a concern for the purposes of this site, but they allow for multiple devices to be set up by showing the secret key again. I've never seen any other site that allows this. I guess if you set up multiple devices at once, there's no way they could stop you, but I've never seen or heard of a site re-revealing your secret key to you...

**Comment by Carlgo11** [comment]
@RichJeanes developers do the craziest things :wink:

**Comment by Carlgo11** [comment]
As far as 2FA the site seems to have it tho so I'd say it's ready to merge.

**Comment by RichJeanes** [comment]
I would have to agree.

**Comment by Carlgo11** [comment]
We sure are productive today!

**Comment by RichJeanes** [comment]
For sure. I've been away for a while but recently got a job with some downtime so I'm trying to get back into programming and contributing to projects.

**Comment by beerisgood** [comment]
Using a Nitrokey Pro works too!

So i would say the checkbox for hardware tokens can be set on the list.

**Pull request merged**
