### PR TITLE
Update steam

### PR DESCRIPTION
**Pull request by Efreak**
Steam supports SMS. Also added other notes.

### CODE REVIEW

**Comment by smholloway** [comment]
:shipit:

**Comment by Carlgo11** [comment]
Wait I can't see any settings for that
screenshot

**Comment by jamcat22** [comment]
^

**Comment by smholloway** [comment]
A couple links show that SMS should be an option: https://steamcommunity.com/discussions/forum/8/598199244885956607/, https://support.steampowered.com/kb_article.php?ref=8625-WRAH-9030#nosms

**Comment by Carlgo11** [comment]
Well it's not :P

**Comment by mxxcon** [comment]
Maybe Geo-restricted to US only?

**Comment by Carlgo11** [comment]
Maybe so. Anyone using steam that could test?

**Comment by mxxcon** [comment]
I'll test in a few

**Comment by jamcat22** [comment]
When I test there isn't an sms option. The phone number option seems to only be there to deactivate your software token.

**Comment by mxxcon** [comment]
https://goo.gl/photos/XHraMVHRvq4HnmaZ8

**Comment by jamcat22** [comment]
@mxxcon Yep. The SMS isn't used for a code though, just to deactivate Steam Guard if you loose your phone or reset your password.
image
image
image

**Comment by Carlgo11** [comment]
Can it be considered TFA then?

**Comment by RichJeanes** [comment]
I mean, technically Steam Guard is only TFA when you use the app. Email is just a second knowledge factor, but we've had that discussion before.

**Comment by smholloway** [comment]
Sorry for the premature merge :flushed:

**Comment by Efreak** [comment]
Ah. My bad. I don't actually have a phone to use, so I couldn't test it. Regardless, the warning should still be relevant (though it should probably be reworded). I'll update with a new patch to remove the SMS check if it hasn't already been done.

**Pull request merged**
