### PR TITLE
Add Quest Diagnostics

### PR DESCRIPTION
**Pull request by hkamran80**

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Looks like a U.S.-only service.

**Comment by hkamran80** [comment]
I didn't add the `regions` array because of this sentence on their [locations page](https://www.questdiagnostics.com/locations/search).
> Quest Diagnostics has headquarters in the U.S. and operations in India, Ireland, and Mexico.

**Comment by hkamran80** [comment]
Never mind. MyQuest is U.S.-only.

**Comment by Carlgo11** [comment]
Let's do br, ie, mx and us then.

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
