### PR TITLE
Add Simple Invoices

### PR DESCRIPTION
**Pull request by laurentperrier**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
even though low on alexa ranking, includes `tfa` so looks good to me

**Comment by laurentperrier** [comment]
Thanks Stephen. What's the next step to get this deployed to the website?

**Comment by Carlgo11** [comment]
@laurentperrier For information on how our work process is layed out, check out our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge).

**Comment by Carlgo11** [comment]
Unfortunately, as the site is ranked above 200K on [Alexa](https://www.alexa.com/siteinfo) it doesn't meet our guidelines of [new site additions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines).

Sorry for the delay in our response.

**Pull request closed without merging**
