### PR TITLE
Add ChargePoint

### PR DESCRIPTION
**Pull request by hkamran80**

### CODE REVIEW

**Review by Carlgo11 — COMMENTED** [review]
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33.93 33.93" style="background:#ef7622;fill:#fff" ><path d="M20.37 18.43c-1.16 0-1.83.58-1.9 2.75 0 1.33-.76 1.66-1.42 1.66-1.17 0-1.58-1.16-1.58-4V15.1c0-2.25.08-3.91 1.58-3.91.83 0 1.41.58 1.41 1.58 0 1.58.67 2.17 1.91 2.17 1.08 0 1.83-.67 1.83-2.17s-.91-4.58-5.24-4.58c-4.57 0-5.4 2.58-5.48 6.08H0V18h11.48v.5c0 4 .5 7.25 5.48 7.25 4.41 0 5.24-3.5 5.24-5.17.09-1.41-.66-2.16-1.83-2.16z"/></svg>
```

**Review by Carlgo11 — APPROVED** [review]

**Comment by hkamran80** [comment]
Where did you find those regions? I was looking, but I couldn't find them.

**Comment by Carlgo11** [comment]
I found it at the top of their homepage:

**Comment by hkamran80** [comment]
> I found it at the top of their homepage: 

Oh. Don't know how I missed that.
Thanks for adding the regions!

**Pull request merged**
