### PR TITLE
added inwx.com

### PR DESCRIPTION
**Pull request by McGrummel**
added inwx.com who provides 2FA

### CODE REVIEW

**Comment by Carlgo11** [comment]
1. You need a logo. The logo should be 32 x 32 px
2. The link should be in https and not http
3. We need a document of some sort. (add `doc:`)
4. The twitter account should not start with an @ since that will be added automatically.

**Comment by McGrummel** [comment]
Updated the domains.yml, but cannot upload the png to imagefolder.
inwx

**Comment by Carlgo11** [comment]
@McGrummel Why not?
Also, logo is 32x31

**Comment by Carlgo11** [comment]
You can't upload images directly from github website. You have to use a desktop git client to add files.

**Comment by Carlgo11** [comment]
@mxxcon This wasn't ready to merge o.o

`invaild` != `looks-good`

**Comment by mxxcon** [comment]
wait, i didn't commit this one

**Comment by Carlgo11** [comment]
@mxxcon

**Comment by mxxcon** [comment]
I commited #780 
This RP was actually completely empty for me :confused: that's why i thought you marked it as invalid...

**Comment by Carlgo11** [comment]
That's true but it says you've merged this PR as well. I don't know how but it says that

**Comment by mxxcon** [comment]
screenshot
see 0 files changed and no commits..
Github must be losing it's mind

**Comment by Carlgo11** [comment]
Same for me. Meh, let's just forget this ever happened. No harm done so.. yeah.

**Comment by mxxcon** [comment]
And I don't see this listed in https://github.com/jdavis/twofactorauth/commits/master

**Comment by Carlgo11** [comment]
Because there's nothing there. somehow the PR is merged though

**Comment by McGrummel** [comment]
Sorry about that. I've deleted this issue an started another try #781. Now it will work. I hope :-)

**Pull request merged**
