### PR TITLE
Update Ukraine (Hosting)

### PR DESCRIPTION
**Pull request by Nanotraktor**
Add phone auth option for ukraine.com.ua

### CODE REVIEW

**Comment by mxxcon** [comment]
@Nanotraktor screenshot on their website only shows google authenticator, sms and "etoken pass" device. It says nothing about phone calls. Can you please confirm this?

**Comment by Nanotraktor** [comment]
This feature was recently added without additional news. 
Here screenshot of login (with process of calling) page of https://adm.tools/hosting/  (hosting panel of www.ukraine.com.ua ): http://rghost.ru/8YCQsprX9.view

**Comment by mxxcon** [comment]
Btw, if you have contacts at that site, they don't use correct terminology. They use "authorization" instead of "authentication". They have somewhat different meaning, both in English and Russian...
For example see https://stackoverflow.com/questions/6556522/authentication-versus-authorization

**Comment by Nanotraktor** [comment]
> They have somewhat different meaning, both in English and Russian...

Yes, most likely it is mistake. I`ll send report to administrators. 
Thanks!

**Comment by fpigerre** [comment]
Thanks for the pull request @Nanotraktor! :+1:

**Pull request merged**
