### PR TITLE
addition of TSB Bank

### PR DESCRIPTION
**Pull request by djrarky**

### CODE REVIEW

**Comment by Jawshy** [comment]
@StevenChorkley, could you also include their Facebook page? 

``` ruby
      facebook: TSBbankUK
```

Here's a logo with transparency, and also meets the dimension (32² px) and file size (2,500 bytes) requirements: 
tsb

**Comment by djrarky** [comment]
Thank you. Done!

**Comment by stephengroat** [comment]
@StevenChorkley thanks for the pr!

**Review by stephengroat — APPROVED** [review]

**Comment by djrarky** [comment]
Forgive me, pr?

**Comment by stephengroat** [comment]
pull request :+1: the more, the merrier

**Comment by djrarky** [comment]
My first pull request - can't wait till it's merged.

Thanks for the help!

**Comment by Carlgo11** [comment]
And it's now merged! Thanks again for your contribution @StevenChorkley! 😄

**Pull request merged**
