### PR TITLE
Added comment on Godaddy.com restrictions

### PR DESCRIPTION
**Pull request by token2**

### CODE REVIEW

**Comment by mxxcon** [comment]
You saying that based on what?

**Comment by token2** [comment]
http://support.godaddy.com/help/article/7502/enabling-two-step-authentication
->> NOTE: At this time, only U.S.-based numbers can receive validation codes

**Comment by mxxcon** [comment]
Oh, ok :smiley: but then why did you include Canada in your edit?

**Comment by token2** [comment]
Sorry, my bad (had a friend in Canada who said it works for him). He could be using a US cellphone :)

**Comment by jdavis** [comment]
Should the comment be updated to reflect this? Also, try to use less ambiguous wording since we know for sure that it is only US numbers. :smile:

**Comment by jdavis** [comment]
Let me know when you've updated the wording, @token2 :smile:

**Comment by dsoegijono** [comment]
Updated wording looks good.

**Pull request merged**
