### PR TITLE
Rename Garena Online to Garena Offline

### PR DESCRIPTION
**Pull request by Carlgo11**
It looks like "Garena Online" no longer is "Online". _*Pun intended*_
Their domain garena.com seems to have been bought up by another company from Singapore (doing god knows what. But it isn't gaming related)

And no, this PR doesn't rename Garena Online. It removes the site completely. Just having fun with the header here at 6am.

//@Carlgo11 :tay:

### CODE REVIEW

**Comment by jamcat22** [comment]
Login link at the top still works...

**Comment by jamcat22** [comment]
Their [business page](http://corporate.garena.com/ourbusiness.php) still mentions gaming too, and their Garena+ desktop client still works.

**Comment by mxxcon** [comment]
According to Wikipedia it was founded in Singapore..

**Comment by jamcat22** [comment]
See #1543.

**Pull request closed without merging**
