### PR TITLE
Add Synchrony Bank

### PR DESCRIPTION
**Pull request by Sunit-Kulkarni**
This is the largest issuing bank of credit cards in the united states.

### CODE REVIEW

**Review by conorgil — APPROVED** [review]
I ran this locally and seems fine to me. 

- Doc link works
- Image looks good
- all HTTPS links

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
The doc link you provided states that voice calls are provided as well. Please add `phone: Yes` 😄

**Comment by Sunit-Kulkarni** [comment]
Good catch. Just added it!

**Review by Carlgo11 — APPROVED** [review]
Looking good!

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
