### PR TITLE
Added karriere.at, easybank.at and ING-DiBa Austria.

### PR DESCRIPTION
**Pull request by tgamauf**
- Added two austrian banks: easybank.at and ING-DiBa Austria
- Added an austrian career website: karriere.at

### CODE REVIEW

**Comment by stephengroat** [comment]
Thanks for the pr @eega

Could you make 3 separate pull requests for each site? We like to do the additions individually. Thanks!

**Comment by tgamauf** [comment]
I'll try, however, I didn't do feature branches, so you will have to accept each one before I can do the next.
I'm open for suggestions, though, if there is a better way to do this.

**Comment by mxxcon** [comment]
branches is the way to go to make parallel pull requests.

**Comment by tgamauf** [comment]
Ok, I rolled back my changes, put them in branches and submitted a pull request for each of the branches. Should be ok now :)

**Comment by jamcat22** [comment]
Duplicate of #2663, #2664, #2665, and #2666.

**Pull request closed without merging**
