### PR TITLE
Add Hostens

### PR DESCRIPTION
**Pull request by cez81**
https://billing.hostens.com/knowledgebase/article/29/how-to-enhance-account-security-/

### CODE REVIEW

**Review by seitsu — COMMENTED** [review]
I think you should add "doc: https://billing.hostens.com/knowledgebase/article/29/how-to-enhance-account-security-/" to your commit.

**Comment by cez81** [comment]
Yes, you're right

**Review by seitsu — APPROVED** [review]
Looks good to me

**Review by Carlgo11 — APPROVED** [review]
What a cute logo! 🐹

**Review by jamcat22 — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
