### PR TITLE
Update Humble Bundle

### PR DESCRIPTION
**Pull request by schlagi123**
Add exception to Humble Bundle implementation

### CODE REVIEW

**Comment by mxxcon** [comment]
Is exception for this really necessary? 🤔

**Comment by jamcat22** [comment]
Please see #2581 for more discussion on the topic of classifying software implementations. As of right now, we don’t mark specific implementations unless there’s a specific limitation associated with it.
Here are a couple examples:
- A banking website offers push notifications for 2FA, but they’re only implemented on their iOS app, not their Android app.
- A social networking website offers Google Authenticator-based 2FA, but they require that you register an SMS-capable phone number first.
- A gaming website offers 2FA through Authy, but they restrict the feature to accounts on a paid plan.

Feel free to comment if there’s a specific limitation to Humble Bundle you’d like to note.

Thanks!

**Comment by schlagi123** [comment]
When I use 2FA the best case is, that I need only one app for token generation and that I am independent of the implementation (I can change the App). Examles for such services are Google, Nextcloud or Github, because I can choose the authenticator app (e. g. Authy, freeOTP, ...). For Humble Bundle I must use Authy. When my preferd authenticator app is another app, then it is the same restriction as for Steam (I need an extra app).

**Comment by stephengroat** [comment]
While it would be nice if everyone used an OATH backed standard like TOTP of HOTP, Authy is a two factor authentication service provider. Their app covers multiple entities, so they get a little exception for that.
Steam is a little different because they use their own Steam app, making it implementation specific

**Comment by jamcat22** [comment]
@schlagi123 thanks for comparing to Steam, as I had not noticed this earlier. Steam’s exception should actually be reworded to not mention the fact that it requires the Steam app, while still explaining that it’s 1 account per phone number. Others, including Blizzard, Garena, Square Enix, and Trion Worlds to name a few, require their own apps to use 2FA but do not specify this in an exception, due to reasons outlined in the aforementioned #2581 issue.

#2067 includes a proposal to include an optional dropdown with the software implementation checkmark to allow for explaining the specific software implementation used without crowding the columns or including an exception message on every service that supports something other than Google Authenticator.

**Pull request closed without merging**
