### PR TITLE
Remove Laybuy

### PR DESCRIPTION
**Pull request by fletcherdodd**
Another BNPL service gone into receivership, as per the notice on their website.

### CODE REVIEW

**Comment by hkamran80** [comment]
Is Laybuy NZ fully under Klarna or is it still a separate service? We might consider removing the other regions if its authentication system is still separate.

**Comment by fletcherdodd** [comment]
> Is Laybuy NZ fully under Klarna or is it still a separate service? We might consider removing the other regions if its authentication system is still separate.

Good point, didn't see that announcement. I would assume they merge into one authenication system, but I can make changes and remove other regions for now. Or remove it and add it back later if it's not merged into Klarna completely

**Comment by hkamran80** [comment]
Let's remove the other regions for now. If Klarna merges it, which they very likely will, we can remove the entry then.

**Comment by fletcherdodd** [comment]
Welp, it's just out of the minimum site ranking

**Comment by hkamran80** [comment]
Guess it's getting removed then

**Review by hkamran80 — APPROVED** [review]

**Pull request merged**
