### PR TITLE
Update Huntington Bank

### LINKED ISSUE #3181: Huntington Bank Supports 2fA
The website is incorrect as it states Huntington does not support 2FA.

I receive a call to my cell every time I log in.   Email OTP is also available.

thanks

### PR DESCRIPTION
**Pull request by stephengroat**
closes #3181

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
>A cursory look at the huntington site doesn't show two factor auth options for retail customers, but for small business there seems to be one: https://www.huntington.com/SmallBusiness/online-banking/information-and-reporting
>
>Huntington could possibly be added with exceptions.
 https://github.com/2factorauth/twofactorauth/issues/3181#issuecomment-393181125

**Comment by stephengroat** [comment]
https://www.huntington.com/Privacy-Security/password-security/secure-accounts

**Comment by Carlgo11** [comment]
I don't see anything on that page about them even using 2FA.

**Comment by Carlgo11** [comment]
Why was the PR closed?

**Pull request closed without merging**
