### PR TITLE
Added Skrill and Payoneer to payments

### PR DESCRIPTION
**Pull request by semencov**
Two popular (at least in Europe) payment systems with unreasonable gap in security. Wish they will consider of the implementation of 2FA.

### CODE REVIEW

**Comment by helwy** [comment]
@semencov Can you find 32x32 icons for them? It is part of the guidelines now

**Comment by jdavis** [comment]
+1 to what @HElwy said =]

**Comment by semencov** [comment]
I'll try, otherwise I'll render some from vector (at least I found one for Skrill) tonight.

**Comment by semencov** [comment]
Updated to 32x32.

**Comment by jdavis** [comment]
Thanks for updating the images!

**Pull request merged**
