### PR TITLE
Making more clear for Coinkite

### PR DESCRIPTION
**Pull request by nvk**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Well the documentation link doesn't work anymore. Have any proof of Coinkite supporting sms & hardware?

**Comment by nvk** [comment]
We even support Paper OTP :)

Here https://coinkite.com/settings/2fa

settings coinkite 2015-07-15 17-05-11

**Comment by Carlgo11** [comment]
Okay so I see Software, SMS and paper there. But hardware?

**Comment by nvk** [comment]
You can add smart cards to be Mutlsig Co-Signers http://blog.coinkite.com/post/116127008376

**Comment by mxxcon** [comment]
Carl, paper is "hardware"☺
@nvk is there docs link we can use?

**Comment by nvk** [comment]
The docs are on the 2FA setup internal page https://coinkite.com/settings/2fa but some info here too https://coinkite.com/iforget 

@mxxcon  that's true!

**Comment by Carlgo11** [comment]
Paper is considered hardware? That's odd...
Okay then

**Comment by nvk** [comment]
Even though we have smart cards as co-signing for transactions which is essentially 2 factor authentication because you are using a secondary system to authenticate an action, the idea of hardware 2FA is that is a device (chip, paper cards, etc) that provide offline form of OTP/TOTP

**Comment by mxxcon** [comment]
Carl, would you say it's "software"? :) Paper codes are a legitimate 2nd factor...

**Comment by Carlgo11** [comment]
I would say it's a category we haven't yet added.

**Comment by RichJeanes** [comment]
We've been calling it hardware. At least, that's what we went with when I ran into it with Coinify (#1023), though I did specify using the exception flag.

**Comment by Carlgo11** [comment]
Okay

**Pull request merged**
