### PR TITLE
Add ftsafe.com to providers.yml

### PR DESCRIPTION
**Pull request by FeitianSmartcardReader**

### CODE REVIEW

**Comment by mxxcon** [comment]
Like I asked in the previous PR, please point out where do you offer email, sms and voice calls.
Also letter F does not come after letter Y :smiley:  ...would be nice to have entries in alphabetical order.

**Comment by FeitianSmartcardReader** [comment]
Hi

We have another cloud platform which support SMS/voice/mails website called cloudentify:
https://www.cloudentify.com/portal/

The app can download from AppStore:
https://appsto.re/cn/P_4BZ.i

Thanks,

**Comment by FeitianSmartcardReader** [comment]
Hi 

The english website can found below:
https://www.cloudentify.net:8443/portal/index.jsp?language=en_US

**Comment by mxxcon** [comment]
Even with that site I do not see that it supports email or voice call.
I don't see reference from ftsafe.com to cloudentify.net.

**Comment by Carlgo11** [comment]
@mxxcon what do you mean? It's `A B C D Y F H Q R Z`. Haven't you learned the alphabet?
:wink:

**Comment by Carlgo11** [comment]
@FeitianSmartcardReader the logo you added is 17kb...
I compressed it and got it down to 360 bytes.
feitian 1
Please use that image instead.

**Comment by FeitianSmartcardReader** [comment]
Thanks,
Changed to small size icon, please check, thanks

**Comment by FeitianSmartcardReader** [comment]
Hi

http://ftsafe.com/solution/saas

This is our service. And we opened a new website for this service.
We are same company, you can check the contact info and you will understand.

For voice and sms, we work with SMS gateway, we have our own cloudentify identification platform which can integrated SMS, voice and Mail into our platform.

We have exist case study for our customer.

Thanks

**Comment by mxxcon** [comment]
In that case I think it's better suited for `Identity Management` category, rather than provider.

**Comment by FeitianSmartcardReader** [comment]
Thanks for your feedback.
We are  for manufacturer and R&D company. we provide hardware token for customer, like OTP(one time password) tokens/display cards, PKI smart cards, PKI tokens, and also we provide identification platform for our customer, which support mobile OTP(one time password accordance OATH standard), Voice, SMS, mails. FIDO, OTP,QR code, voice token and so on. and we made our own mobile Apps and hardware device to support all of these function.

So we are provider for authentication solution for sure, let me know your thought, looking forward to your reply, thanks

**Comment by FeitianSmartcardReader** [comment]
Hi Guys, I need your help on this. Thanks a lot, ;-)

**Comment by mxxcon** [comment]
I'm on the fence here if it should be listed as provider or identity management, so I'll defer to others.

**Comment by FeitianSmartcardReader** [comment]
Got it, good to know this. So what's your definition of provider? Provide hardware, software with 2 factor authentication solution for users? that's what we do. ;-)

**Comment by mxxcon** [comment]
What is your businesses' primary product, 2fa solutions or SAML/SSO products or card readers or vpn or something else? Your website lists many various things.

**Comment by FeitianSmartcardReader** [comment]
Sorry the web make you confuse. 

Our business is we do authentication hardware(OTP,PKI, Smartcard), software (mobile OTP, mobile secure browser (using PKI card + mobile reader)) and we also do two factor authentication solutions(cloudentify) which can using our hardware product and, Voice, SMS, mails. FIDO, OTP,QR code and more new authentication elements to do authentication.

The authentication hardware can be found below:
http://www.ftsafe.com/product

The cloudentify platform can found below:
https://www.cloudentify.net:8443/portal/index.jsp?language=en_US

And all our product can using to provide best service for customer do two factor authentication on their system, like VPNs, bankings, enterprise, government and so on.

Hope the explanation  can give you a good review of our company and products.

**Comment by FeitianSmartcardReader** [comment]
Hi Guys

Hope everything well. May I know your answer? BTW, please ignore my github account, since I was a smartcard reader technical people, then I made that name.  All good, thanks

**Comment by Carlgo11** [comment]
@FeitianSmartcardReader please have patience. All collaborators do this on our spare time.

**Comment by FeitianSmartcardReader** [comment]
Thank you very much, I totally understand. Thanks ;-)

**Comment by jamcat22** [comment]
The providers page is being removed. You can read more about that on #1177.

**Pull request closed without merging**
