### PR TITLE
Add Saxo Bank

### PR DESCRIPTION
**Pull request by niclashedam**
This adds Saxo Bank to the list.
Saxo Bank provides different platforms depending on the client type. This represents the platform used by private persons.

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
You've taken a WEBP image and renamed it to PNG. You need to provide a proper PNG image that's 32x32 pixels and less than 2.5KB

**Comment by niclashedam** [comment]
Sorry for the mistake. I was a little too quick.
I have replaced it with a compressed PNG that is within the boundaries.

**Comment by kmpoppe** [comment]
Source branch and fork of 2fa is gone.

**Pull request closed without merging**
