### PR TITLE
Added joscor.com as a site with 2FA support

### PR DESCRIPTION
**Pull request by 01000101**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Does the site meet the <a href="https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria">site criterias</a>?

**Comment by 01000101** [comment]
Honestly, the site criteria section is difficult to follow (for me at
least).  Joscor is about helping people improve their network security and
provides tutorials.  There are also computer/network/development services
offered there.

**Comment by Carlgo11** [comment]
hm well it's a bit tricky for me to make a conclusion when the anti-bot captcha in the registration section turns anti-human ;)

Is the site like a forum?

**Comment by 01000101** [comment]
Haha! It's sort of a forum in that there are discussions but I do not allow
anyone to post without moderation.  Mostly it's me and a few others
creating tutorials and guides on programming and security.  More akin to a
security blog.  I'll see what I can do about the captcha.

**Comment by Carlgo11** [comment]
Okay well it sounds like the site doesn't qualify for being listed on our site.
A site listed here must have some kind of critical/personal information about the user.
It's great that your site supports tfa :+1:  but we won't list it here.  

Once again, thank you for supporting tfa! #TFAEVERYWHERE! :)

**Comment by mxxcon** [comment]
It seems like this site is just a Wordpress blog with a bunch of tutorials (with a heavy lean toward wwpass, company where you work..)
Doesn't seem like pass the site criteria. :-1:

**Pull request closed without merging**
