### PR TITLE
Added CDC Federal Credit Union as per #742

### PR DESCRIPTION
**Pull request by RichJeanes**

### CODE REVIEW

**Comment by Carlgo11** [comment]
What is with all these "credit unions"?!
Why does the Centers for Disease Control need a credit union?!
Isn't the CDC a part of the U.S. government as well?

**Comment by RichJeanes** [comment]
Maybe they're just OCD about the cleanliness of their money, okay? /s
But seriously, I don't know. It is kind of ridiculous.

**Comment by Carlgo11** [comment]
lel, yeah well anyways. The PR looks good.

**Comment by mxxcon** [comment]
credit unions are kinda similar to employment unions...

**Pull request merged**
