### PR TITLE
Update Wells Fargo status

### PR DESCRIPTION
**Pull request by Carlgo11**
As per #1582.

It looks like they don't have any docs that are up to date so I left the doc tag out.

### CODE REVIEW

**Comment by mxxcon** [comment]
But RSA SecureID has software tokens, can't those be used as well?

**Comment by Carlgo11** [comment]
@mxxcon updated the PR.

**Comment by mxxcon** [comment]
:+1: 
Maybe add info from PR1582 into a separate notes page the way we have for Chase, Fidelity and a couple of other sites?

**Comment by Carlgo11** [comment]
Is that really necessary?

**Comment by jamcat22** [comment]
I'm going to merge this, and create a doc page for it later on.

**Pull request merged**
