### PR TITLE
Update ING (Luxembourg)

### PR DESCRIPTION
**Pull request by Stevoisiak**

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
I think it's better to keep url as short as possible. That way the site can redirect the user more easily.
Plus, sites often change their URL structure causing our links to become invalid.

**Comment by Stevoisiak** [comment]
I made this PR because I wasn't able to figure out the policy for language-specific URLs. The general trend seemed to be use the English site when available.

**Comment by Carlgo11** [comment]
That is true but URL cleanliness is also a rule of thumb.

**Comment by Stevoisiak** [comment]
Makes sense. The policies on page language and URL cleanliness should probably be included somewhere in the [contributing guide](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).

**Comment by Carlgo11** [comment]
Closing as discussed in https://github.com/2factorauth/twofactorauth/pull/2358#issuecomment-277482157

**Pull request closed without merging**
