### PR TITLE
Rename+Update American Funds

### LINKED ISSUE #3972: American Funds does support 2FA
American Funds does supports 2FA - Data needs to be corrected.

### PR DESCRIPTION
**Pull request by phallobst**
Fixes #3972

### CODE REVIEW

**Comment by kmpoppe** [comment]
Hi @phallobst Michael,
where did you get the information about the 2fa methods from? The documentation you linked just says "we've got something new now" but doesn't really describe how it works, or am I reading something wrong?
// Kai

**Comment by phallobst** [comment]
Well it says
> To establish this new security feature, we’ll ask you to provide an email address or text-enabled phone number when you log in to your account.

I just assumed that email and SMS would be the channels they would use.

**Comment by phallobst** [comment]
There is also a video on here:
https://www.capitalgroup.com/individual/service-and-support/use-your-account/get-started.html
They mention text message and email. May be use this link instead then? But a video is not as accessible as a text page.

**Review by kmpoppe — APPROVED** [review]
Just too blind to see the obvious. Thanks for pointing it out to me!
// Kai

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
