### PR TITLE
add venmo to payments

### PR DESCRIPTION
**Pull request by ilyakatz**

### CODE REVIEW

**Comment by jdavis** [comment]
Hey @ilyakatz, we've changed up the format a bit. If you fixed that, I'd be able to merge it just fine.

**Comment by ilyakatz** [comment]
@jdavis updated

**Comment by jdavis** [comment]
Perfect, @ilyakatz. I know a few people that should see this ;) @cassidoo, @jwbixby

**Comment by cassidoo** [comment]
Aww yeah.  Awesome. :)

**Comment by cassidoo** [comment]
Just an update, we're working on step-up auth and two factor as we speak!  Woo hoo! :)
@ilyakatz @jdavis

**Comment by jdavis** [comment]
That's awesome, @cassidoo. Hopefully things are going well in the big NYC; you're latest video of the Brooklyn bridge on Instagram was mesmerizing :eyes:.

If you want it to be updated to say "IN PROGRESS!", just Tweet at me from the Venmo twitter handle and we can update it.

**Comment by cassidoo** [comment]
Ha, thanks!!  It's great over here. :)
I'll see if the bosses upstairs will let me tweet that.  Might have to wait until the project is closer to the finish.

**Pull request merged**
