### PR TITLE
Make header stick to viewport

### PR DESCRIPTION
**Pull request by dsoegijono**
To make it easier to switch between categories. Also made the categories dropdown scrollable (not pretty but functional).

### CODE REVIEW

**Comment by dsoegijono** [comment]
[GIF] in action:
sticky header

**Comment by jamcat22** [comment]
@dsoegijono Love it!

**Comment by jamcat22** [comment]
Does the menu highlight change depending on which section you're looking at?

**Comment by dsoegijono** [comment]
@jamcat22 It doesn't. It can be a future enhancement, I think.

**Comment by jamcat22** [comment]
Ok

**Comment by Carlgo11** [comment]
:+1:

**Comment by mxxcon** [comment]
How would it work on mobile?

**Comment by dsoegijono** [comment]
@mxxcon I'll add a GIF of a resized browser when I get home from work

**Comment by dsoegijono** [comment]
sticky header iphone6
@mxxcon GIF should show what it might look like on mobile (iPhone 6 Safari). I used Mac OS Safari's responsive design tool.

**Pull request merged**
