### PR TITLE
Add Oculus

### PR DESCRIPTION
**Pull request by spinnerich**

### CODE REVIEW

**Review by phallobst — APPROVED** [review]

**Comment by ApCoder123** [comment]
SVGs are the preferred image type. Please use this icon instead:
Oculus SVG

**Comment by 40504** [comment]
image


It's looking a little darkest:) maybe 🤔 other one with black background and white elipse, I'll try to create one

**Comment by 40504** [comment]
used for official channels of oculus: Twitter, YouTube

**Comment by Carlgo11** [comment]
@40504 the background on 2fa.directory lists are rather bright anyways. I don't think Arun's image would look bad when live.

**Comment by 40504** [comment]
@Carlgo11 or this one,  like favicon ->

**Comment by ApCoder123** [comment]
image
@40504 I think that it would look fine on the green background on the site

**Review by ApCoder123 — APPROVED** [review]

**Pull request merged**
