### PR TITLE
Add Plaid

### PR DESCRIPTION
**Pull request by nagey**
https://www.alexa.com/siteinfo/plaid.com

Rank is 33,177

image

### CODE REVIEW

**Review by phallobst — APPROVED** [review]
Not quite sure about the "Cloud Computing" category, but I have no better suggestion either.

**Comment by nagey** [comment]
> Not quite sure about the "Cloud Computing" category, but I have no better suggestion either.

I chose cloud since finance seemed to be personal finance stuff. Cloud seemed to make sense since plaid is an api as a service, and I figure anything that’s “as a service” if you squint hard enough, you can call cloud. :shrug:

**Comment by dsoegijono** [comment]
I agree that Cloud doesn't seem to be the right section. I'd say Finance makes more sense. Or maybe even Developer since Plaid is mostly for app integration?

**Comment by ApCoder123** [comment]
Please rebase your branch to the current master.

**Pull request closed without merging**
