### PR TITLE
Add Google Cloud Platform to developers section

### PR DESCRIPTION
**Pull request by icco**

### CODE REVIEW

**Comment by mpdavis** [comment]
Is there any reason to have this listed separately than Gmail as it is the same account?  Perhaps combine them to just a Google account?  Otherwise the list would be littered with entries for Gmail, Google Cloud, G+, and every other service Google offers.

**Comment by computmaxer** [comment]
I agree with @mpdavis on this one.

**Comment by zach-taylor** [comment]
Yeah I think its being discussed on #35 how to deal with that kind of stuff.

**Comment by jdavis** [comment]
I'm going to add it for right now as soon as I add a icon.

As I mentioned in #35, I'm going to think on it and see what I can come up with.

**Pull request closed without merging**
