### PR TITLE
Add Protonmail

### PR DESCRIPTION
**Pull request by ghost**
www.protonmail.com / www.protonmail.ch

### CODE REVIEW

**Comment by RichJeanes** [comment]
Hey @levle. Thanks for contributing!

I am going to make one request, though. Can you submit this PR again, but make the changes from a new branch on your fork, instead of on the `master` branch? That will make sure the PR only includes your changes.

**Comment by Carlgo11** [comment]
Well we already have protonmail listed...

**Comment by RichJeanes** [comment]
Oh, so we do. An even better point. Haha :laughing:

**Comment by mxxcon** [comment]
This pull request can't be accepted since it includes a lot of unnecessary commits.
If there are updates to protonmail entry, please submit a new pull request with only those changes.

**Pull request closed without merging**
