### PR TITLE
Update gaming.yml

### PR DESCRIPTION
**Pull request by Veruco**
Updated League of Legends, uses 2-step verification through email.

### CODE REVIEW

**Comment by zach-taylor** [comment]
Hi @Veruco do you have a source for this that could be put under doc: ?

**Comment by Veruco** [comment]
Nope, not at the moment.

**Comment by jdavis** [comment]
K, if you can find a source, feel free to resubmit your pull request with the doc string updated.

Cheers.

**Comment by Veruco** [comment]
Is this okay for the doc?
http://na.leagueoflegends.com/en/news/riot-games/announcements/email-verification-here

**Comment by jdavis** [comment]
Yup! That's perfect. Add it as the `doc:` string and then make a new pull request.

Thanks!

**Comment by jdavis** [comment]
Or you can add it to this pull request, I can reopen it.

**Comment by RichJeanes** [comment]
@jdavis So are we looking for 2 Factor anything or specifically for logins? From that post it sounds like Riot will alert you via email when something changes on your account and require you to go through the email to change things like password but it doesn't seem to act like Steam Guard, emailing you a OTP for login. Though the post says they are working on SMS protection.

**Comment by Veruco** [comment]
2-step verification through email OTP for any account changes is available.  SMS 2-step verification is on the public beta environment.  2FA on login is still under development.

**Comment by RichJeanes** [comment]
That's why I want Josh's opinion on this. It's awesome that they have that extra layer of security but I know he has specific goals for this site and I'm not sure if this lands in the "Has 2FA" category or the "Working on 2FA" category for him.

**Comment by jdavis** [comment]
Oh, I didn't read the actual blog post. I should have assumed less. So if the 2FA for login is still coming, then this should wait.

If they want to be "In Progress", I'd like a tweet (@HopefulJosh) saying it is being worked on since the campaign started and from Riot's Twitter.

Sorry for not actually reading the post :disappointed:

**Comment by jdavis** [comment]
I'm closing for now. Feel free to re-open a PR for when more info is known.

**Pull request closed without merging**
