### PR TITLE
Add Hurricane Electric to Domains section

### PR DESCRIPTION
**Pull request by dupuy**
They also act as an IPv6 tunnel broker and ISP, but no categories for that

### CODE REVIEW

**Comment by mxxcon** [comment]
That doc link has a message that it can't be enabled..

**Comment by dupuy** [comment]
Wasn't really documentation - just a forum post, so I have removed it.

**Comment by mxxcon** [comment]
@dupuy can you confirm yourself that HE have 2fa?

**Comment by dupuy** [comment]
Yes, I use it myself (why I added it).

**Comment by gene1wood** [comment]
@dupuy Can you point out where to enable 2FA on he.net? I'm an existing he.net customer but am unable to find where in their UI 2FA is set?

Is the 2FA specific to their tunnelbroker.net site ( mentioned in https://forums.he.net/index.php?topic=3385.msg19501#msg19501 ) and not to Hurricane Electric in general?

**Pull request merged**
