### PR TITLE
Add Capital One note

### PR DESCRIPTION
**Pull request by ghost**
Add notes about Capital One's SwiftID, the 2FA mobile software application which accepts and responds to push notifications. 

reference to #2891

### CODE REVIEW

**Comment by pdg137** [comment]
There's no information about SwiftID or two-factor available in [CapitalOne's help page](https://www.capitalone.com/support-center/search/).

**Comment by ghost** [comment]
Not sure what having an entry in Capital One’s site has to do with the
change. The location of their documentation is in a hyperlink off of the
notes page. The current capital one row links to that same SwiftID page and
I kept that link. The main reason for the update was due to the
shortcomings of trying to get that to work with their technical support and
statements about it not always available.

**Comment by pdg137** [comment]
Right, I am agreeing with you that SwiftID does not seem to be a well-supported feature, since they don't link to it from their help page.  The term "SwiftID" is not actually mentioned anywhere in the Android app, either.

**Comment by ghost** [comment]
Ok. Thanks. Obviously I hadn’t understood.

**Review by DavidCao22 — DISMISSED** [review]

**Comment by DavidCao22** [comment]
I don't have any official authority or write access, just wanted to get this merged. Spent a while looking for this info. It would've been nice to have merged in, so I'm trying to help it along and save time for others in the future.

Some layout changes need to be made since the UI has changed since the PR was put up, but I could take care of that after the merge.

**Comment by kmpoppe** [comment]
The question is, if this project is the right place to put these critics about Capital One. Through APIv2 (#4015) we can now add `proprietary` (software) as a 2fa-method, which would mean SwiftID.
Information and the way Capital One handles these software problems with change on short notice, so we would be adding information that could be out of date relatively soon.
I'd think that extending the exception with something like "If SwiftID doesn't work, you should use SMS instead" would be sufficient. @Carlgo11 ?

**Comment by Carlgo11** [comment]
I agree with @kmpoppe. The amount of information in this PR could easily be compressed into an exception text. Furthermore, what happened to the documentation link? I can't find anything about SwiftID on their site any longer 🤔

**Comment by Carlgo11** [comment]
Closing as the source is gone

**Pull request closed without merging**
