### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by dylancasey**
Adding Yahoo to mail providers with 2FA support.

### CODE REVIEW

**Comment by mpdavis** [comment]
There isn't actually a yahoo.png as referenced.  @dylancasey Can you add a yahoo.png?

**Comment by dylancasey** [comment]
Ooops..sorry. Can you use this one: https://www.google.com/s2/favicons?domain=http://yahoo.com or do you need me to upload one?

**Comment by mpdavis** [comment]
Having a 16x16 png added to twofactorauth/img/email is preferred.  Thanks!

**Comment by mpdavis** [comment]
Yahoo was added in https://github.com/jdavis/twofactorauth/pull/115

**Pull request closed without merging**
