### PR TITLE
Add osu!

### PR DESCRIPTION
**Pull request by yuna0x0**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Could you provide some sort of documentation link or screenshot of the setup/login process? (with any personal information blurred out)

**Comment by yuna0x0** [comment]
osu! doesn't have clear documentation about 2FA, but you must receive an email verification code every time you log in from a new device.

screenshot

**Review by Carlgo11 — APPROVED** [review]
:+1:

**Review by jtagcat — CHANGES_REQUESTED** [review]
png a bit big

**Review by jtagcat — APPROVED** [review]

**Review by kmpoppe — APPROVED** [review]

**Pull request merged**
