### PR TITLE
Update Uplay in gaming gaming.yml

### PR DESCRIPTION
**Pull request by berserkovich**
Uplay now supports 2FA

### CODE REVIEW

**Comment by Carlgo11** [comment]
The doc link you provided isn't a documentation link.
Can you try and find one that is a valid documentation page?

**Comment by berserkovich** [comment]
http://forums.ubi.com/showthread.php/1463703-Secure-your-account-with-2-Step-Verification
is this one good enough?

**Comment by RichJeanes** [comment]
If there's no official Support site article, then I'd say that link works.

**Comment by berserkovich** [comment]
Official support gave me that link :)

**Pull request merged**
