### PR TITLE
`url` Deleted Based on `domain`: The `C`s

### PR DESCRIPTION
**Pull request by johntheholman**
- Removes the `url` key if the `domain` key is the same
- Small updates to some files based on the `editorconfig`
- This is only looking at the `C` files (as seen when hitting the `v3/all.json` endpoint)

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Please fix the following unreachable links:
* callcentric.com
* cointiger.com
* copaair.com
* caisse-epargne.fr
* cgd.pt
* cpp.edu
* jep.coop

**Comment by johntheholman** [comment]
These work:
- callcentric.com
- copaair.com
- cgd.pt
- jep.coop

**Comment by Carlgo11** [comment]
```SH
$ curl https://jep.coop/ --connect-timeout 10 -I
HTTP/2 403

$ curl https://callcentric.com --connect-timeout 10 -I
curl: (28) Failed to connect to callcentric.com port 443 after 9689 ms: Connection timed out

$ curl https://copaair.com/ --connect-timeout 10 -I
curl: (28) Connection timeout after 10001 ms

$ curl https://cgd.pt/ --connect-timeout 10 -I
curl: (7) Failed to connect to cgd.pt port 443 after 380 ms: Connection refused
```

**Comment by Carlgo11** [comment]
As the requested changes haven't been resolved yet I'm going to label this PR as inactive.
> **Warning**
> Unless there's activity within the next 7 days I'll close the PR.

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
