### PR TITLE
Add Infomaniak in Hosting

### PR DESCRIPTION
**Pull request by fbonzon**

### CODE REVIEW

**Comment by RichJeanes** [comment]
Is there a reason that the doc link redirects to https://www.infomaniak.ch/fr/support/faq/1940 a Swiss domain which is in French?

**Comment by fbonzon** [comment]
They have a "short link" for every FAQ entry. See "Link to this FAQ:" at the bottom of the page.

Should I change to the full link with the English version? This URL:

https://www.infomaniak.ch/en/support/faq/1940

**Comment by fbonzon** [comment]
Infomaniak is Swiss company, I guess the redirection is expected. The .com domain is a synonym.

**Comment by RichJeanes** [comment]
It's just a little jarring to go from the home page link in English to that, so I'd say, yeah, go with the full link to the English.

**Comment by fbonzon** [comment]
Done.

If you prefer, there is also the blog post entry, at the time the feature was introduced: https://news.infomaniak.com/en/activer-double-authentification-infomaniak/

**Pull request merged**
