### PR TITLE
google drive and wallet

### PR DESCRIPTION
**Pull request by victorhaggqvist**

### CODE REVIEW

**Comment by jdavis** [comment]
Darn, it looks like there's an indentation issue as the build status notes.

**Comment by victorhaggqvist** [comment]
now it should be good, even lited it my self

**Comment by RichJeanes** [comment]
I feel like this falls under the "Gmail" entry seeing as both Drive and Wallet use the same Google Account.

**Comment by jdavis** [comment]
Yeah, I'm merging it for right now, but the idea is still churning as I discussed in #35

**Pull request merged**
