### PR TITLE
Add Flatex

### PR DESCRIPTION
**Pull request by paradonym**
commit 5d83b7f; wrongly placed flatex.png in /img/domains/flatex.png
eb2a820 removes the file again (couldn't remove a commit somehow)

commit fd0ef0a: flatex in _data/finance
commit e617104: /img/finance/flatex.png (where I hope it belongs to, because of flatex being in _data/finance/)

All of this replaces /pull/2951 which is wrong...

### CODE REVIEW

**Review by Jawshy — COMMENTED** [review]
@paradonym, can you confirm that Flatex does not offer [two-factor authentication](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions)? I ask because authentication via an SMS code is mentioned at the bottom of [this page](https://www.flatex.de/en/service/insurance-app/).

**Comment by paradonym** [comment]
@Jawshy looking at this page "An offer of Jung, DMS & Cie. AG" it looks like advertising to a different product from a different company. (this is an insurance document management app, which is something completely different than anything which has to do with online stocks and markets brokerage-accounts, which is what Flatex stands for)
Looking at the "Trade" "Investment" "Credit" and "Academy" points (the brokerage-account) it's just a customer-number + password you need to login (you'd see this if you open an account).

**Comment by mxxcon** [comment]
Wouldn't Investing or Legal be better categories for this?

**Comment by paradonym** [comment]
@mxxcon I'm unsure, investing for me as a millenial means things like crowdfunding, profit sharing contracts and so on. But the stocks markets with all it's products - stocks, bonds, forex and so on... Technically - yes - could be
Maybe it's better, can it be moved without just another pull?

**Comment by mxxcon** [comment]
If you make an edit in our repo, it's be reflected here.

**Comment by paradonym** [comment]
I hope it's done now...

unfortunately the earlier commits failed, because my last commit was moving the image... all the previous ones just seem to say that the picture isn't available

**Review by Carlgo11 — APPROVED** [review]

**Review by jamcat22 — APPROVED** [review]
Thanks for the PR @paradonym!

**Pull request merged**
