### PR TITLE
Add N26 (Number26)

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by mxxcon** [comment]
Perhaps use their fav icon? https://n26.com/wp-content/themes/number26/dist/img/icons/favicon-32x32-v2.png

I've never heard of this service. How big is it?

**Comment by nicolasleger** [comment]
I took the image from their Twitter, favicon is better.

It is a German startup that now has the license banking.
See http://www.reuters.com/article/germany-number-idUSL8N1A75WF?type=companyNews

**Comment by nicolasleger** [comment]
I updated the image with the official favicon. Thanks

**Comment by Carlgo11** [comment]
@mxxcon?

**Comment by mxxcon** [comment]
I guess semantically speaking this PR is ok, but I have no idea on German market and how big this site is.

**Comment by RichJeanes** [comment]
https://www.similarweb.com/website/n26.com

**Comment by Carlgo11** [comment]
Looks like it's pretty popular

**Pull request merged**
