### PR TITLE
Update Mixpanel - tfa

### PR DESCRIPTION
**Pull request by jbwyme**
https://pbs.twimg.com/media/ByggSiqCIAA9ELf.png

### CODE REVIEW

**Comment by mxxcon** [comment]
"generated on mobile device" sounds like a mobile app rather than `sms`. @jbwyme can you confirm?

**Comment by jbwyme** [comment]
We use Authy (https://www.authy.com/) but we force the SMS (
https://docs.authy.com/#section-Forcing_SMS) when sending the auth tokens.

**Comment by mxxcon** [comment]
So a user would need both Authy app and support sms or only sms?

**Comment by jbwyme** [comment]
Only sms. You can optionally use the Authy app if you have it installed but it's not required and you'll still receive an sms.

**Comment by Carlgo11** [comment]
@jbwyme so you can use the Authy app instead of reciving texts?

**Comment by mxxcon** [comment]
@Carlgo11 no, SMS is a required part.

**Comment by jbwyme** [comment]
@Carlgo11 @mxxcon With the normal Authy workflow it will only send SMS when the user doesn't have the Authy app installed (and you'd use the app instead). However, you can "force" the SMS which means it'll get sent even if the user does have the Authy app installed. We chose the "force" option so that we have a consistent experience which is particularly helpful for customer support.

**Comment by dsoegijono** [comment]
Shouldn't `software` be marked as `yes` seeing as it works with the Authy app? Even if the SMS is still sent.

**Comment by mxxcon** [comment]
@dsoegijono but then again, it seems to also work w/o..
Afaik we've never had a situation where one of the methods was optional and another mandatory.. :confused:

**Comment by dsoegijono** [comment]
@mxxcon Hmm I think Software should be marked Yes, but add an exception that SMS is mandatory? I think pretty much all of the options listed on the site are optional (like Authy here). This issue is similar as Twitter, and we have listed Software even though SMS is mandatory there too.

**Comment by jbwyme** [comment]
I can mark Software as yes... If you have the Authy app you can ignore the
SMS and use the code the app gives you so I suppose that makes SMS optional
(with the exception that you still received one).

On Sat, Sep 27, 2014 at 11:59 PM, Daphne Soegijono <notifications@github.com

**Comment by Carlgo11** [comment]
I agree with @dsoegijono. Add software

**Comment by Carlgo11** [comment]
In the meantime I'll remove the looks good tag so no one will accidentally merge. Like me for example ;)

**Comment by jbwyme** [comment]
Alright updated so that `software: true`

**Comment by Carlgo11** [comment]
Is there any documentation on how to use Authy on your site? Most sites have some kind of document explaining for their customers how to enable TFA.

**Comment by jbwyme** [comment]
Not at the moment, it just lives in the project settings. If active, it'll
prompt everyone on the project to setup their TFA when they login if they
haven't already.

**Comment by Carlgo11** [comment]
Well I guess it's good to go then.
Remember to add the doc when you make one

**Comment by Walkman100** [comment]
Can't the image ( https://pbs.twimg.com/media/ByggSiqCIAA9ELf.png ) be linked to as the doc?

**Pull request merged**
