### PR TITLE
Add Kobo

### PR DESCRIPTION
**Pull request by nagromc**

### CODE REVIEW

**Comment by mxxcon** [comment]
Wouldn't `retail` be a better category for this?

**Comment by nagromc** [comment]
Well, I was not sure about that. These are e-books. Can we talk about retail when it's not physical? Just tell me and I'll update my PR.

**Comment by Carlgo11** [comment]
Yup, retail.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Move to retail category

**Review by Carlgo11 — APPROVED** [review]

**Review by stephengroat — APPROVED** [review]

**Pull request merged**
