### PR TITLE
Add DBS Bank Singapore

### PR DESCRIPTION
**Pull request by ChristopherZhong**
Signed-off-by: Christopher Zhong <1946052+ChristopherZhong@users.noreply.github.com>

### CODE REVIEW

**Comment by brycx** [comment]
Are there docs available which are a bit more descriptive? This one just has a list of things that you can use and for what purposes. If more descriptive docs are available but only for registered users, please take a screenshot and post it here. Remember to blur out any personal information. Thanks.

**Comment by ChristopherZhong** [comment]
> Are there docs available which are a bit more descriptive? This one just has a list of things that you can use and for what purposes. If more descriptive docs are available but only for registered users, please take a screenshot and post it here. Remember to blur out any personal information. Thanks.

Is this [link](https://www.dbs.com.sg/personal/landing/digitaltoken2/index.html) more appropriate?

**Comment by mxxcon** [comment]
Hmm....
Actually reading the current and your original url (https://www.dbs.com.sg/ibanking/help/2fa-login.html) a bit closer, unless I'm misunderstanding something, it seems like according to our [definition](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) this site would be `tfa: no`.
They only ask for username and password to login(authenticate). Other methods come into play only when you perform specific operations(authorization).
Correct me if I'm wrong in this aspect..

**Comment by ChristopherZhong** [comment]
> Hmm....
> Actually reading the current and your original url (https://www.dbs.com.sg/ibanking/help/2fa-login.html) a bit closer, unless I'm misunderstanding something, it seems like according to our [definition](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) this site would be `tfa: no`.
> They only ask for username and password to login(authenticate). Other methods come into play only when you perform specific operations(authorization).
> Correct me if I'm wrong in this aspect..

Yes. Upon further exploration, it appears that `tfa: no`. I will update it

**Review by dsoegijono — APPROVED** [review]

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
