### PR TITLE
Update Simplii

### PR DESCRIPTION
**Pull request by sarahmrrp**
Added support for 2FA

### CODE REVIEW

**Review by Carlgo11 — COMMENTED** [review]
From reading [this page](https://simplii.intelliresponse.com/index.jsp?requestType=NormalRequest&source=3&id=2286&sessionId=eff4be9f-516e-11ed-bb3e-73b23b154f85&question=I+was+asked+to+give+a+one-time+verification+code.+What+is+this+and+why+is+it+required) it looks like these codes are only required for certain actions and not for logging in. Is this correct?

**Comment by sarahmrrp** [comment]
> From reading [this page](https://simplii.intelliresponse.com/index.jsp?requestType=NormalRequest&source=3&id=2286&sessionId=eff4be9f-516e-11ed-bb3e-73b23b154f85&question=I+was+asked+to+give+a+one-time+verification+code.+What+is+this+and+why+is+it+required) it looks like these codes are only required for certain actions and not for logging in. Is this correct?

Unless I have my card saved in my browser, I get prompted for a 2FA code every time,

**Comment by Carlgo11** [comment]
Unless you have your card saved? Could you clarify what you mean?

**Comment by sarahmrrp** [comment]
Unless you select "Save bank card" in your browser (like a "remember me" features) it will ask you for 2FA when logging in.

**Review by Carlgo11 — APPROVED** [review]
Thanks for the clarification. Your contribution will be public in about 10 minutes.

**Pull request merged**
