### PR TITLE
Add ZenPayroll to finance.yml

### PR DESCRIPTION
**Pull request by marcusbryan**

### CODE REVIEW

**Comment by marcusbryan** [comment]
Didn't have the image in place before I sent this commit.

**Comment by Carlgo11** [comment]
There's no changes o.o

**Comment by marcusbryan** [comment]
I evidently screwed something up there.

**Comment by Carlgo11** [comment]
indeed :smile:

**Comment by mxxcon** [comment]
@marcusbryan still need logo.. :wink:

**Pull request merged**
