### PR TITLE
ThreatSim.com

### PR DESCRIPTION
**Pull request by veverkap**
Adding in security section.
Adding in site Threatsim

### CODE REVIEW

**Comment by mpdavis** [comment]
@veverkap This PR has merge conflicts from the security section added in #171.  Can you update?

**Comment by veverkap** [comment]
Can you retry?

**Comment by mpdavis** [comment]
It looks like you removed the wrong part.  This no longer contains the info for ThreatSim.

**Comment by veverkap** [comment]
Okay, I'll redo it :)

**Pull request closed without merging**
