### PR TITLE
Update TurboTax

### PR DESCRIPTION
**Pull request by veratu**
Fixed TurboTax URL / auth types.

### CODE REVIEW

**Comment by mxxcon** [comment]
Don't you think the original URL is more useful to users how to enable 2fa vs marketing fluff on the new URL?

**Comment by veratu** [comment]
The original link was specific to Google Authenticator, which is only 1 of several 2fa's the product supports, and I'm working to influence the marketing fluff people to have links underneath each topic to individual URLs with more info/instructions on all of the 2fa capabilities instead of just the one.

**Comment by jamcat22** [comment]
How about [this](https://ttlc.intuit.com/questions/2902682-what-is-two-step-verification)? It links to both Google Auth, and SMS.

Do you have anything to show email auth?

**Comment by veratu** [comment]
You mean a screenshot of the email auth?  Or a link on their site?  You can see their email auth experience by just going to turbotax.com (do it in an incognito window if you're an existing user, that will force their 2fa process), and when you sign in you'll see a screen that offers SMS or Email 2fa.   Once you are inside, you can set additional items on your account to be permanent 2fa via SMS or Google Authenticator.

**Comment by veratu** [comment]
I updated the URL to the what is two factor auth link.  Let's go with that one.

**Comment by veratu** [comment]
Are we good to merge this now?

**Pull request merged**
