### PR TITLE
Remove travis_wait from .travis.yml

### PR DESCRIPTION
**Pull request by Carlgo11**
Removed the `travis_wait` arg since that isn't really needed anyways.

### CODE REVIEW

**Comment by mxxcon** [comment]
Is there some drawback in having `travis_wait` there?

**Comment by Carlgo11** [comment]
The travis_wait arg was a thing we tried when Travis failed all the time. It never worked since it apparently only applies to the bundle command.

**Comment by RichJeanes** [comment]
But it was timing out on the bundle command. I thought it did help? We're just timing out on a different part now.

**Comment by Carlgo11** [comment]
No the bundle command never timed out. It was the html-proofer that timed out.

**Comment by RichJeanes** [comment]
You sure? I seem to remember it dying sporadically...

**Pull request merged**
