### PR TITLE
Update Experian

### PR DESCRIPTION
**Pull request by aarontorres0**

### CODE REVIEW

**Comment by phallobst** [comment]
Was this supposed to go into the `Equifax` entry?

**Comment by aarontorres0** [comment]
I tend to get both of these companies mixed up and did it here too. Should be the domain for Experian.

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
@aarontorres0 can you confirm that 2FA is supported on Experian.com?

**Comment by aarontorres0** [comment]
Yes, I can confirm. I just enabled it yesterday and my options were to receive a text message or phone call.

**Pull request merged**
