### PR TITLE
Add mysqa.org.uk

### PR DESCRIPTION
**Pull request by ohheyrj**
Added mysqa.org.uk, scottish exam board portal. Alexa ranking:
image

### CODE REVIEW

**Comment by Carlgo11** [comment]
Oh wow another Annand 👀
image

**Review by Carlgo11 — APPROVED** [review]

**Comment by ohheyrj** [comment]
Oh! We are a rare bunch! @Carlgo11

**Comment by phallobst** [comment]
How about this icon? It looks better IMHO.
mysqa

**Comment by ohheyrj** [comment]
@phallobst yup, agree, I will update and push again

**Comment by ohheyrj** [comment]
Updated the logo

**Review by phallobst — APPROVED** [review]

**Pull request merged**
