### PR TITLE
Add solar.web

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by Jawshy** [comment]
How does the site fit the [criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria)?

**Comment by stephengroat** [comment]
provides remote access to solar inverters

**Review by Jawshy — APPROVED** [review]

**Comment by RichJeanes** [comment]
What level of access? Are we talking they can see my power consumption levels? They can turn my power off levels? They can make the inverters explode levels?

**Comment by stephengroat** [comment]
see power levels, run updates, and, on 2+ source inverters, chose source(s)
to turn on and off.

**Pull request merged**
