### PR TITLE
Add SaferVPN.com

### PR DESCRIPTION
**Pull request by spazvt**
* add SaferVPN service provider, originally added by @deadr0ck to fork
https://github.com/acceptbitcoincash/acceptbitcoincash

### CODE REVIEW

**Review by stephengroat — DISMISSED** [review]
@spazvt usually we only try to affect 1 entry per pull request, but we'll let this one slide

could you remove the `ShadeYou` entry? it's currently ranking ~980k on Alexa, a little too low to list right now

**Comment by spazvt** [comment]
shadeyou.com removed (now at 6M+ ranking). @stephengroat what's the website traffic threshold you usually use to decide whether a website gets added?

A: 200k appears to be the threshold.

**Comment by spazvt** [comment]
safervpn.com is listed as 30k globally and 2200 in Australia. https://www.alexa.com/siteinfo/safervpn.com

@stephengroat please let me know if any other changes needed.

**Review by mxxcon — CHANGES_REQUESTED** [review]
Consider using this image as their logo
safervpn

**Review by mxxcon — DISMISSED** [review]

**Review by mxxcon — APPROVED** [review]

**Review by brycx — APPROVED** [review]

**Pull request merged**
