### PR TITLE
Add GamersGate

### PR DESCRIPTION
**Pull request by morguldir**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Duplicate of #2405 however I think this should be the primary one as the other one is closed.
In the future @Criminalllz, try to use just one PR.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Try this image instead. It's smaller
gamersgate

**Comment by morguldir** [comment]
@Carlgo11 I messed up and didnt reset my local repo and it included the previous pull request aswell. And i made a new pr to only include the add-gamersgate.

**Review by stephengroat — APPROVED** [review]
thanks for the pr @Criminalllz!

**Comment by Carlgo11** [comment]
Maybe retail would fit better?
@2factorauth/collaborators thoughts?

**Comment by stephengroat** [comment]
@Carlgo11 i think it's better in `gaming`, otherwise anyone that sells anything should be `retail`, right?

**Comment by fpigerre** [comment]
Given that GamersGate's front page is almost solely dedicated to selling items (with prices listed), I think it would be best if it was placed in the `retail` category. It does seem like the website does have some "Achievements" and "Friends" features, however, and not only sells games but also strategy guides.

screen shot 2017-03-01 at 18 18 38

**Review by mxxcon — APPROVED** [review]

**Comment by mxxcon** [comment]
I think either category is good enough for the site.
Right now I'm leaning more towards `gaming` though.
If they were selling gaming-related apparel or hardware or some other stuff, then I'd be leaning more towards `retail`.

**Comment by Carlgo11** [comment]
From looking on their description about themselves it seems like their main feature is selling games.

**Review by Carlgo11 — APPROVED** [review]
Moved GamersGate to `retail`.

**Review by fpigerre — APPROVED** [review]

**Pull request merged**
