### PR TITLE
Add Golem

### PR DESCRIPTION
**Pull request by windmueller**
Golem is a german news site. Accounts are also used for the forum and subscriptions.

### CODE REVIEW

**Comment by windmueller** [comment]
I am not allowed to use the logo. How do I fix the failing checks?

**Comment by windmueller** [comment]
The logo can be found in the Wikipedia: https://upload.wikimedia.org/wikipedia/de/thumb/d/dd/Golem-de-Logo_2011-05-08.svg/640px-Golem-de-Logo_2011-05-08.svg.png

**Comment by Carlgo11** [comment]
@stovocor what is golem.de and what can someone do with access to an account there?
Keep in mind that we don't list forums here.

**Comment by windmueller** [comment]
Golem is a portal for IT news. It offers premium subscriptions and therefor needs to store personal data like my address or credit card details.

**Review by phallobst — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
