### PR TITLE
Added token2.com

### PR DESCRIPTION
**Pull request by token2**
PNG image below

token2

### CODE REVIEW

**Comment by Carlgo11** [comment]
You haven't added an icon yet. Add it or close the pr

**Comment by token2** [comment]
Hello,
I have added it as a url, for some reason I could not upload it directly

**Comment by Carlgo11** [comment]
@token2 The token2.png doesn't load for me.

(Could possibly be a GitHub bug)

**Comment by dsoegijono** [comment]
@Carlgo11 It doesn't load for me either under the "Files changed" tab, but if I click View it loads.

**Comment by Carlgo11** [comment]
Good news and bad news.

Good news: the logo works now.
Bad news: There's a merge conflict.

**Pull request closed without merging**
