### PR TITLE
Added ProtonMail

### PR DESCRIPTION
**Pull request by Carlgo11**

### CODE REVIEW

**Comment by mxxcon** [comment]
I don't know if it's correct to include that pastebin..
They plan to implement it, that's great. But at the moment they don't have it. When they'll add it, we'll update the site.

**Comment by Carlgo11** [comment]
@mxxcon ok

**Comment by Carlgo11** [comment]
But actually, we have other sites that don't already have 2fa.

**Comment by dsoegijono** [comment]
I think @mxxcon means (and I agree if that's true) that the entry is fine, but the `status:` part is unnecessary. We'll just change it to `tfa: Yes` when they've implemented it.

**Comment by mxxcon** [comment]
yes, what @dsoegijono said. :smile:

**Comment by dsoegijono** [comment]
Ping @Carlgo11. Can you remove the pastebin? I think it'll be good to merge then.

**Comment by Carlgo11** [comment]
@dsoegijono Ok. had to make a new pr for that though. Long story...
#693

**Pull request closed without merging**
