### PR TITLE
Add CheckMail

### PR DESCRIPTION
**Pull request by mikepultz**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the addition @mikepultz

**Comment by Carlgo11** [comment]
checkmail
Please use this image instead. It's 67% smaller. I tried to push this to your PR but apparently it's locked.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
checkmail
Please use this image instead. It's 67% smaller. I tried to push this to your PR but apparently it's locked.

**Comment by stephengroat** [comment]
@mikepultz could you update the image?

**Comment by mikepultz** [comment]
hey @stephengroat,

Sorry for the late reply- I've updated the image to your smaller version.

Thanks,

Mike

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
