### PR TITLE
Add Yodlee MoneyCenter financial aggregation site

### PR DESCRIPTION
**Pull request by marvingreenberg**
Add Yodlee Labs - Beta/incubator version of MoneyCenter

### CODE REVIEW

**Comment by ilyakatz** [comment]
I would say this isn't exactly true, Yodlee does asks for answers to verification questions when you login from a new device

**Comment by marvingreenberg** [comment]
So does vanguard and some of the other financial web sites. But it isn't 2FA since it isn't requiring me to HAVE something (like my phone or a key fob) in addition to knowing something.

**Comment by ilyakatz** [comment]
@marvingreenberg  cool, thanks

**Comment by RichJeanes** [comment]
So these sites have two independent account systems even though one was spawned from the other?

**Comment by marvingreenberg** [comment]
The newer yodleemoneycenter.com needs a new account set up - I think yodlee is trying to redesign from ground up, but kept the older renamed site (thankfully) for existing users.

**Comment by ilyakatz** [comment]
@marvingreenberg this PR is not mergeable, would you mind updating it and we'll merge it in?

**Comment by jdavis** [comment]
Hmm, is there a way to just have one of these instead of both sites? If yodleemoneycenter.com is the newer one, could we just have that one?

**Comment by jdavis** [comment]
Thanks for that update, @marvingreenberg. I just noticed it now.

**Pull request merged**
