### PR TITLE
Remove Bitcoins Norway & Coinapult

### PR DESCRIPTION
**Pull request by spazvt**
I reviewed all crytocurrency sites per @stephengroat's threshold of requiring an [Alexa rank](https://www.alexa.com/siteinfo/) of 200k or better.

* bitcoinsnorway.com: [602k globally and 7914 in Norway](https://www.alexa.com/siteinfo/bitcoinsnorway.com).
  * Highest rank during 2017 bubble: ~300k.
* coinapult.com: [620k globally](https://www.alexa.com/siteinfo/coinapult.com).
  * Highest rank during 2017 bubble: ~250k.

Note that I intentionally left in place the following crypto sites:
* anxpro.com: 298k globally. Highest 2017: ~100k. https://www.alexa.com/siteinfo/anxpro.com
* bitlish.com: 330k globally. Highest 2017: 330k. Surprisingly, it has been gaining even in spring 2018 while all other crypto exchange traffic is falling. https://www.alexa.com/siteinfo/bitlish.com
* satoshitango.com: 483k globally. Highest 2017: ~160k. https://www.alexa.com/siteinfo/satoshitango.com

Let me know if you would like for me to remove those as well.

Related PRs to remove low-traffic cryptocurrency exchange websites: #3191 #3192

### CODE REVIEW

**Comment by mxxcon** [comment]
If there are some changes with low traffic sties, then ya, might as well remove them.
But if the data is still accurate and the site is still around, let's not go too much out of the way w/ removing exiting sites since effort have been done to add and review them in the first place.

**Comment by spazvt** [comment]
ok, I was just applying the policy that seemed to be applied to the rest of the site in current cleanup PRs (#3132 #3131).

**Comment by conorgil** [comment]
Why is there a threshold for which sites to include on twofactorauth.org? Can you point my to any documentation or other issues where it might have been discussed? Thanks!

**Comment by spazvt** [comment]
@conorgil You're right, there's nothing listed in `CONTRIBUTING.md` but here are the comments/PRs which indicate that >200k ranking is a policy when adding new sites:

* Carlgo11: ["Although we usually don't add sites ranked >200k on alexa.com, ..."](https://github.com/2factorauth/twofactorauth/pull/3057#pullrequestreview-111382500)
* stephengroat: ["could you remove the ShadeYou entry? it's currently ranking ~980k on Alexa, a little too low to list right now"](https://github.com/2factorauth/twofactorauth/pull/2861#pullrequestreview-84323167)
* PRs: #3132 #3131

Since I've recently requested several crypto sites be added, I was just trying to apply the policies I had seen, to try to help clean up. But per @mxxcon it appears that there's no threshold at which a site should be removed once listed.

**Comment by conorgil** [comment]
@spazvt thanks for the links! I have seen a few of those before and know generally that there is a ~200k limit.

My question about the 200k limit was less intended for you and more intended for the core maintainers to understand **why** that policy is in place and how it came to be. I don't understand why the community would actively reject entries just because the sites have low traffic numbers. I see twofactorauth.org as the main resource to quickly look up whether any given site has 2FA support or not. If that is the goal of the project, then entries for all sites that support 2FA should be welcome and encouraged regardless of how big/small it is because it is a net increase in information, thus benefitting the entire community.

If people feel that this issue is not the best place to have this conversation, then I am totally open to moving it into another issue dedicated to the topic. I am trying to better understand the conversations and thinking that lead to the policy since I cannot find it documented anywhere. Any/all related info is appreciated so that I can better understand. Thanks!

**Comment by mxxcon** [comment]
> My question about the 200k limit was less intended for you and more intended for the core maintainers to understand why that policy is in place and how it came to be. I don't understand why the community would actively reject entries just because the sites have low traffic numbers.

Because core maintainers have limited amount of time and attention to review every single site out there. Because we were seeing issues and PRs from what essentially were essentially fly-by-night sites intended as another place to advertise their site and not as a resource for users.
To help address these problems and to maximize value and impact of each PR/site _for now_ we decided to cut off at 200k. In the future we might increase or completely remove this threshold.

**Comment by kenman345** [comment]
@mxxcon have you considered writing some Travis-CI test to notify us of the alexa rank using the API? Seems 1,000 hits per month are allowed for free. 
https://aws.amazon.com/awis/

In the code samples section, it pretty much  has a ready to go ruby script that can be used once you load Travis with the keys it needs. https://aws.amazon.com/awis/getting-started/

**Comment by mxxcon** [comment]
I have not. I didn't think Alexa had any free API access.

**Comment by spazvt** [comment]
per #3131 mods have decided to not remove sites with low traffic.

**Comment by kenman345** [comment]
I’m sorry but that makes no sense. I can understand not adding new sites
below a thread as a means of not going crazy to maintain but if a sites
listed why add more work to remove them? Obviously someone cared enough to
add it in the first place.

**Comment by mxxcon** [comment]
@kenman345 that's exactly what's happening. We are keeping already-added sites.

**Comment by kenman345** [comment]
Check your master branch, it’s got a few commits mentioning Alexa rank in
the removal commit

**Pull request closed without merging**
