### PR TITLE
Add ReadMe

### PR DESCRIPTION
**Pull request by kanadgupta**
[Alexa Rank: #24,914](https://www.alexa.com/siteinfo/readme.io)

### CODE REVIEW

**Review by kmpoppe — CHANGES_REQUESTED** [review]
Hi @kanadgupta and thank you for your contribution.

Unfortunately, you have not set this PR as writeable by maintainers.

Please change the image in your PR to this slightly better quality one:
readme

**Comment by kanadgupta** [comment]
Hi @kmpoppe our logo is cut off using your image:

image

I uploaded another one - please review when you get a chance!

image


Not sure why you are unable to edit the PR, it looks good on my end. Sorry about that!
image

**Comment by kmpoppe** [comment]
Hi @kanadgupta, thanks for the new image. Yet, this one has a size of 2.17k - even though this is below the limit of 2500 bytes, that we set, compression would be helpful. Using tinypng.com you can reduce the size to 488 bytes.
I still get a permission denied error when I try to push to your branch, but no worries, this happens from time to time.
// Kai

**Comment by kanadgupta** [comment]
I compressed the image based on your feedback. And I believe the permissions issue is because the repo I forked belongs to the @readmeio organization. I just added you as a collaborator.

**Review by kmpoppe — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
