### PR TITLE
Add united-domains

### PR DESCRIPTION
**Pull request by seitsu**
This is different to the US and the reselling website, which are both already included.

### CODE REVIEW

**Comment by mxxcon** [comment]
Do they use different login systems?
Do they have different logos? Because right now you are using the same logo for both entries.

**Comment by seitsu** [comment]
@mxxcon Yes, it is different to #2546 and #2798. All of them are using different login systems as they are different companies. The logo of #2546 (udreselling.png) seems similar to #2824 (united-domains.png), but it is different.

**Comment by seitsu** [comment]
@mxxcon Any idea how to proceed with this request?

**Comment by mxxcon** [comment]
I guess perhaps rename it to be `united-domains DE` or maybe even write it out as a domain `united-domains.de`? to clearer differentiate it from the other entries.

**Comment by seitsu** [comment]
@mxxcon Ok, I renamed it to united-domains.de.

**Comment by seitsu** [comment]
@mxxcon / @Jawshy  Can we proceed with that?

**Review by mxxcon — APPROVED** [review]

**Review by Jawshy — APPROVED** [review]
The united-domains.de FAQ article said that a phone number is required so I added that as an exception.

**Comment by Jawshy** [comment]
Thanks for the pull request, @seitsu.

**Pull request merged**
