### PR TITLE
Add Lunch Money

### PR DESCRIPTION
**Pull request by larsonsamj**

### CODE REVIEW

**Review by hkamran80 — DISMISSED** [review]

**Review by hkamran80 — CHANGES_REQUESTED** [review]
Lunch Money's security page mentions two-factor authentication, but could you provide some screenshots of the 2FA setup process, login process, or management screen. Please blur or crop out any personal or sensitive information.

**Comment by larsonsamj** [comment]
Here is what my setup looks like.
image

when logging in:
image

**Comment by hkamran80** [comment]
Perfect, thank you!

**Review by hkamran80 — APPROVED** [review]

**Comment by hkamran80** [comment]
Thank you! Your contribution will be visible in around 10 minutes, although it may take longer due to [server and browser caching](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Caching).

**Pull request merged**
