### PR TITLE
adding UKFast to hosting companies

### PR DESCRIPTION
**Pull request by gavtaylor**

### CODE REVIEW

**Comment by jamcat22** [comment]
Is there a docs link?

Also, you can delete the Twitter. That is only used when the website does not support 2FA.

**Comment by gavtaylor** [comment]
Ive removed twitter and added SMS, I missed it off.

there are instructions how to configure TFA on an updates page but you must be logged in to view them so I didnt think it was right to add as a docs link as all the other examples are public facing pages. I can pop it on if you think its still relevant - https://my.ukfast.co.uk/account/updates.php#update_1715

SMS is mentioned on a blog post here http://www.ukfast.co.uk/blog/2015/02/12/backtobasics-two-factor-authentication/

**Comment by Carlgo11** [comment]
@gavtaylor could you take a screenshot of the instructions that you need to be logged in to view?

**Comment by gavtaylor** [comment]
hi, here's a screenshot of the update, its more of a new feature notice than instructions on how to set it up tho. Ive also taken one of the option in the settings where you can select the method you want to use. I had to crop it tho as its a security settings page and contains details like my username, mobile number etc. hope thats ok.

screenshot-201503072008
2fa-options

**Pull request merged**
