### PR TITLE
added MakePlans (online appointment booking)

### PR DESCRIPTION
**Pull request by espen**

### CODE REVIEW

**Comment by espen** [comment]
Two-facktor authentication using Time-based One-time Password (TOTP) algorithm specified in RFC 6238.

**Comment by espen** [comment]
Done. Sorry I didn't notice the order in the file and it wasn't mentioned in the readme.

**Comment by jdavis** [comment]
What is MakePlans? I've never heard of it or used it before?

**Comment by espen** [comment]
@jdavis it is an online appointment booking SaaS. Can be used by doctors, hairdressers, spas or anything which require an appointment to be booked. Each client has it own booking site which can be customized. More info at http://www.makeplans.net/

**Comment by jdavis** [comment]
I think it's a great site but I don't think it falls under #394 which is trying to figure out the criteria to be on 2FA.org.

I don't think any of the data is that critical if compromised.

**Comment by espen** [comment]
MakePlans stores sensitive and personal health data and payment information. The application is certified by the Norwegian Department of Health (Norsk Helsenett) to store this type of data.

**Pull request closed without merging**
