### PR TITLE
Add Adobe ID

### PR DESCRIPTION
**Pull request by therealmarv**
Creative Cloud offers syncing of images (unlimited) and also files.
I would use their service it if they would offer 2FA.
Images (private or commercial) and creative creations need a good protection.

### CODE REVIEW

**Comment by mxxcon** [comment]
Hmm, i'm not sure if Backup is the correct category for it. While Creative Cloud does offer image syncing, I don't think it's the primary product.
Also see #819.

**Comment by therealmarv** [comment]
Well it is a multipurpose product. You can put binary files into it (like Dropbox/GDrive), you can work collaborative on files there (covering most of Adobe products), you can sync your Lightroom image sets to it (which is not a 100% backup but a sync which is two way and in a very good quality). Same login is also used for downloading their products. So it is most similar to a Google Account with various sync products underneath. In my opinion every service which syncs your images in one way or another needs a good protection.

**Comment by mxxcon** [comment]
@therealmarv Yes, every service should have 2fa for user accounts. However, this site is not intended to list every single possible site out there.

When people think about Creative Cloud, image syncing is not the 1st thing that comes to mind. I think it's all of the Adobe applications.

If this site is going to be added, I think it should not go into backup category, but rather into "other" category.

**Comment by therealmarv** [comment]
I'm fine with moving it to another category. No problem with that.

**Comment by jamcat22** [comment]
I say it `looks-good`.

**Comment by Carlgo11** [comment]
Yeah, like #819 I don't think this should be added to the list.

**Comment by therealmarv** [comment]
I see that on #819 everybody is ok with Adobe. I do not care about downloading their products. The main reason for this PR is beeing able to use the Creative Cloud with your professional or private images together with iPad/Android Creative Cloud apps and 2FA protected image syncing.

**Comment by jamcat22** [comment]
Why don't we just change it to Adobe then? They also have document cloud which would be important to protect. All of their products use the same account system, so why don't we just add Adobe itself instead of their individual products?

**Comment by therealmarv** [comment]
@jamcat22 good point. I'm not into every corner of their products but you are right. They all use the same  so called **Adobe ID** 
image
 for Creative Cloud and DC (Document Cloud) and maybe also other things...

I will correct that as soon as I can...

**Comment by jamcat22** [comment]
@therealmarv Are you still going to update this?

**Comment by Carlgo11** [comment]
Just added the "Inactive" label to make it easier to close in case the contributor doesn't reply within a reasonable amount of time.

**Comment by therealmarv** [comment]
@jamcat22 @Carlgo11 updated it now. Thanks for reminding me.

**Comment by jamcat22** [comment]
@therealmarv Thanks! See the [wiki](https://github.com/jdavis/twofactorauth/wiki/FAQ_Merge) for more info on what happens after a request is merged.

**Comment by therealmarv** [comment]
:+1: :)

**Pull request merged**
