### PR TITLE
Change URLs to HTTPS

### PR DESCRIPTION
**Pull request by NullPiotrException**
Ran `grep -rnw . -e 'http:/'` in the repo directory and changed all occurrences of "http://" to "https://" if the page was accessible via HTTPS.

Sometimes I changed the URL entirely if it was outdated.

### CODE REVIEW

**Comment by conorgil** [comment]
@einsteinsfool awesome! How did you verify that the URL was accessible via HTTPS? Did you write a little script or something? Care to share so that others can use it in the future?

**Comment by NullPiotrException** [comment]
@conorgil Thanks.
Frankly, I manually checked all http URLs.
I wrote now a script for others but it's not perfect and returns some false positives when websites do have HTTPS but redirect to HTTP.

```
#!/bin/bash

grep -r . -e 'http:/' | while read -r line ; do
        link=$(echo $line | grep -oP "http://[^\s\"\`]+")
        if [ -z "$link" ]; then
                continue
        fi
        link=${link/http/https}
        header=$(curl -s --head --request GET -m 3 $link)

        if [[ -n "$header" && $header != *"Moved"* ]]; then
                echo $link
        fi
done
```
The line with curl command could be changed to remove these false positives. But I don't know how to perfectly check if website fully works on HTTPS.

These are the false positives:

- https://www.crunchyroll.com/
- https://www.dell.com
- https://help.epicgames.com/customer/en/portal/articles/2879127-what-is-two-factor-sign-in-and-how-do-i-opt-in
- https://wargaming.net/
- https://www.bochk.com
- https://cloudatcost.com
- https://its.umich.edu/accounts-access/uniqnames-passwords/two-factor-authentication

**Comment by conorgil** [comment]
@einsteinsfool Ah ok gotcha. I did kinda the same thing for #3103. I should really just take the time to write a full script to check for redirects back to HTTP, etc, etc, so that we can stop doing it by hand. One day! haha

**Comment by kmpoppe** [comment]
@einsteinsfool Are you still around?

**Comment by NullPiotrException** [comment]
@kmpoppe Yes. Will probably make a new PR and link to this one because of conflicts. I'm not good with git.
But only if it gets merged. I don't want to waste my time just for new conflicts arrive.

**Comment by kmpoppe** [comment]
@einsteinsfool Splendid! I took myself the time (albeit destroying my work yesterday and now starting with a slightly different approach) to build a small application to check every entry for HTTP/HTTPS and possibly other things like shorter documentation URLs. 
I just wanted to ask, if you were alright with closing this PR (as it has so many conflicts now) and put the ball into my playing field whilst I come up with a solution that is usable on a more automated level so that you don't have to spend so much time (as you have the first time, and I would like to apologize for not working through this earlier!)
// Kai

**Comment by NullPiotrException** [comment]
No problem. Thank you for an extremely kind reply. I appreciate it.
And of course good job automating the solution! I wasn't able to do it so I decided to help by doing it manually.

**Comment by kmpoppe** [comment]
@einsteinsfool Please don't get me wrong, your help is much appreciated! And in light of this being purely voluntary work, every contribution helps! See you on the next Pull Request!

**Comment by NullPiotrException** [comment]
I didn't get you wrong. I wasn't being sarcastic, don't worry. :-)
I know manual solution is better than nothing but automated one is even better.

**Pull request closed without merging**
