### PR TITLE
Update Scaleway

### PR DESCRIPTION
**Pull request by itslukej**
Scaleway now supports 2FA (since 06/13)

### CODE REVIEW

**Comment by stephengroat** [comment]
@2factorauth/collaborators 

since scaleway is already listed under `cloud`, should the `hosting` entry be removed?

**Comment by Carlgo11** [comment]
@stephengroat does it fit best under cloud or hosting?
I'm okay with whatever category you choose as long as it's just one :wink:

**Comment by itslukej** [comment]
It's in both at the moment 🤔

**Comment by Carlgo11** [comment]
I'm well aware of that @itslukej. That's why @stephengroat suggested we remove one of them.

**Comment by itslukej** [comment]
Didn't see that. oops. Scaleway labels itself as a cloud hosting platform, so it should probably be in `cloud` only. 👍

**Comment by Carlgo11** [comment]
Haha, "cloud hosting". Great! That gives us no help at all in choosing a category 😄 
If you think cloud fits the best I say let's change this PR to removing Scaleway from hosting.

Would you like to make the changes @itslukej or shall I do it?

**Comment by itslukej** [comment]
Done ^

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
Thanks @itslukej!
I also removed the image as it's no longer used.

Someone will get around to approving the PR in a few hours. Then it will be merged and eventually end up on the live site.
You can look more closely at the process from PR to update on our site here: https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge

**Pull request merged**
