### PR TITLE
MediaTemple is working on 2factor. Added link to tweet from them

### PR DESCRIPTION
**Pull request by rtvenge**
Also looks like my text editor trimmed some trailing whitespace. :)

I let MediaTemple know about this pull request.

### CODE REVIEW

**Comment by Carlgo11** [comment]
We've had a lot of similar PRs in the past and we've agreed not to add a status before they show that they're actively working on adding TFA.

Thanks for your PR though :+1:

**Comment by rtvenge** [comment]
I reread the tweet after I did this pull request. Makes perfect sense.

**Comment by rtvenge** [comment]
[Tweet](https://twitter.com/mediatemplehelp/status/586231956926529536) from MediaTemple: 

> mediatemplehelp: @rtvenge As soon as we have more info, we'll be sure to update the world! #StayTuned *DK

So we wait… :/

**Comment by mxxcon** [comment]
@rtvenge let's close this PR in the mean time? If they'll reply quickly enough, we can re-open this. If it'll take days/weeks/month, then this PR will be out of sync and will be easier to just create a new one. And if they won't reply at all... :(

**Comment by rtvenge** [comment]
no worries, thanks!

**Pull request closed without merging**
