### PR TITLE
Update eBay

### PR DESCRIPTION
**Pull request by djrarky**
As per #2455

### CODE REVIEW

**Review by stephengroat — CHANGES_REQUESTED** [review]
because of [the specific twitter advice from the official AskeBay account](https://twitter.com/AskeBay/status/844014526492303362), I don't think it's a good idea to update this yet with `sms: Yes`. if anything, update with `tfa: No` or some strange `exception`

**Comment by djrarky** [comment]
I think an exception might be a good idea, I activated 2fa with the link in the issue thread just before I made the pull request to test. 

What do you think? I can make the change tonight.

**Comment by Carlgo11** [comment]
I just signed enabled SMS 2FA so it seems to work okay as long as you know the link to enable it.
@stephengroat what's your reasoning for not adding `SMS: Yes`?

**Comment by stephengroat** [comment]
according to [their tweet](https://github.com/2factorauth/twofactorauth/issues/2455#issuecomment-288090016), this isn't really a supported feature yet. i don't know if we should update until it's actually supported

**Review by Carlgo11 — APPROVED** [review]

**Comment by stephengroat** [comment]
Closing since it's not officially supported yet #2455

**Pull request closed without merging**
