### PR TITLE
Ensure contribution link displays on resize

### LINKED ISSUE #571: Menu bar on narrow screen
This might be related to #548 and/or #529.

As seen [here (iPhone + Safari)](https://cloud.githubusercontent.com/assets/867840/3262717/edc533f6-f268-11e3-8710-fdc345d8af24.png), the menu bar isn't fully visible on narrow screens. Even when content is wider, and I try to scroll right, the menu bar stays fixed. You probably don't want a horizontal scroll for the menu bar, so the menu should be somehow squeezed if the screen is too narrow? I was thinking only show icons instead of labels, but not sure if icons are descriptive enough (also, there's currently no icon for "Categories").

### PR DESCRIPTION
**Pull request by fpigerre**
Ensure that the GitHub contribution link displays correctly when the
window is resized. This issue fixes #571.

resize

### CODE REVIEW

**Comment by Carlgo11** [comment]
Wow @psgs, fancy seeing you here! 😀

**Comment by fpigerre** [comment]
Fancy seeing you here @Carlgo11 :+1:

**Comment by Carlgo11** [comment]
@jdavis any comments? You're the css master so... :wink:

**Comment by jdavis** [comment]
Looks good =]

**Pull request merged**
