### PR TITLE
Add UK Companies House

### PR DESCRIPTION
**Pull request by rubenarakelyan**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]

**Comment by Carlgo11** [comment]
Does this login page differ from any other gov.uk login page or can the same credentials be used for multiple ministries?
Might be a stupid question but I just want to make sure the addition is relevant.

**Comment by fpigerre** [comment]
Since this website forms a part of the overall [gov.uk](https://www.gov.uk/) domain, this website might also work better as part of a more general entry for [twofactorauth.org](https://twofactorauth.org).

**Comment by Carlgo11** [comment]
@psgs it depends on how independent the different subdomains are but that was my first instinct as well.

**Comment by rubenarakelyan** [comment]
Companies House logins are separate from other GOV.UK sites, which use either Government Gateway or GOV.UK Verify. Not all of them support 2FA yet either.

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
I compressed the logo by 64%.
When pushing to the right branch I used the latest history of the main repo causing GitHub to think that all commits committed since the original's history parted with the main repo was commits that should be listed here.
To fix that massive log of commits in this PR I reset to the main repo's history and then cherry-picked the real commits of this PR. That way this PR is up to date with our master branch. Does does however mean that the time line of the commits are a bit wacky. Sorry about that! :disappointed:

**Pull request merged**
