### PR TITLE
Add Authentify Inc

### PR DESCRIPTION
**Pull request by andrew-rolfe**
Please commit the addition of Authentify as another 2FA provider

### CODE REVIEW

**Comment by jdavis** [comment]
Cool, thanks for this, Andrew.

**Comment by mxxcon** [comment]
@andrew-rolfe `phone` means that they will actually call you and a voice will talk to you...
It is different and separate from SMS.
Can you confirm that they support phone calls?
(and I'm 18 seconds too late)

**Comment by jdavis** [comment]
Doh, sorry, @mxxcon.

**Comment by jdavis** [comment]
Looking at this page: http://www.authentify.com/demos/demo_center.html

It looks like they offer SMS messages as well as some voice recognition feature. Although it doesn't seem like they give you the OTP over the phone.

**Comment by andrew-rolfe** [comment]
Yes – we provide both automated voice calls and SMS … we also provide a mobile phone application

**Comment by mxxcon** [comment]
Looks like they perform user's voice print analysis...not exactly what I had in mind, but I guess technically that still qualifies as "phone" :)

**Comment by andrew-rolfe** [comment]
We do not provide an OTP directly – We provide the secure channel (voice or SMS to any phone, or data sent directly to registered smart phone application with digital certificates) which an Enterprise can utilize to send or retrieve an OTP … also allows them to choose whichever OTP algorithm they wish instead of us prescribing it..
But in general, since a man in the middle attack will still compromise a web session if using OTP entered via the compromised web channel, we promote using OOB (out of band) contact with the end user via the phone (voice, SMS, or data) and responding using the phone (speech reco, SMS response, or signed data response) as the entry device.  In that way the bad guy would have to compromise two channels.

Andy--

**Comment by andrew-rolfe** [comment]
We do also provide separate “human” verification as well via voice biometrics during the voice call, or via voice capture within the mobile smartphone app.
Other biometrics will also be utilized within the mobile phone app like Samsung’s and Apple’s fingerprint reader when available.

The biometrics are multi-factor – so you are correct = over and beyond 2FA
The access to the phone or phone app with certificate are the more formal 2FA solutions

Andy--

**Comment by andrew-rolfe** [comment]
Anything else you need from me on this?

Andy--

From: Andy Rolfe
Sent: Wednesday, June 18, 2014 3:10 PM
To: 'jdavis/twofactorauth'; jdavis/twofactorauth
Subject: RE: [twofactorauth] Please commit the addition of Authentify as another 2FA provider (#589)

We do also provide separate “human” verification as well via voice biometrics during the voice call, or via voice capture within the mobile smartphone app.
Other biometrics will also be utilized within the mobile phone app like Samsung’s and Apple’s fingerprint reader when available.

The biometrics are multi-factor – so you are correct = over and beyond 2FA
The access to the phone or phone app with certificate are the more formal 2FA solutions

Andy--

From: Andy Rolfe
Sent: Wednesday, June 18, 2014 3:06 PM
To: 'jdavis/twofactorauth'; jdavis/twofactorauth
Subject: RE: [twofactorauth] Please commit the addition of Authentify as another 2FA provider (#589)

We do not provide an OTP directly – We provide the secure channel (voice or SMS to any phone, or data sent directly to registered smart phone application with digital certificates) which an Enterprise can utilize to send or retrieve an OTP … also allows them to choose whichever OTP algorithm they wish instead of us prescribing it..
But in general, since a man in the middle attack will still compromise a web session if using OTP entered via the compromised web channel, we promote using OOB (out of band) contact with the end user via the phone (voice, SMS, or data) and responding using the phone (speech reco, SMS response, or signed data response) as the entry device.  In that way the bad guy would have to compromise two channels.

Andy--

From: Andy Rolfe
Sent: Wednesday, June 18, 2014 2:58 PM
To: 'jdavis/twofactorauth'; jdavis/twofactorauth
Subject: RE: [twofactorauth] Please commit the addition of Authentify as another 2FA provider (#589)

Yes – we provide both automated voice calls and SMS … we also provide a mobile phone application

**Comment by jdavis** [comment]
Nope! It is merged and ready. I always test master locally and then push up to the gh-pages branch which is what controls what is seen on the website. I'll post again once it is updated.

**Comment by jdavis** [comment]
Okay, everything looked good so it should be listed now: http://twofactorauth.org/providers/

**Comment by andrew-rolfe** [comment]
OK – thank you Josh!
BTW – I was really happy to see you guys doing some due diligence on the stated capabilities.  Glad you are actively investigating and keeping us honest.

Andy--

**Comment by jdavis** [comment]
No problem. :smile:

**Pull request merged**
