### PR TITLE
Fix file permission

### PR DESCRIPTION
**Pull request by hongchangwu**
png file should not be executable :/

### CODE REVIEW

**Comment by mxxcon** [comment]
@hongchangwu while you are doing that, perhaps look though other png files and make sure they don't have the same?

**Comment by RichJeanes** [comment]
Yeah, I did that a little while ago. There were two or three that I fixed back then. Don't know how it happens.

**Comment by hongchangwu** [comment]
@mxxcon yeah will do a quick scan

**Comment by hongchangwu** [comment]
Seems like this file is the only offender 

```
$ find ./img -executable -name '*.png'
./img/entertainment/sling.png
```

**Pull request merged**
