### PR TITLE
Update the status of Kayako 2fa

### PR DESCRIPTION
**Pull request by jmedwards**
Available since 4th July 2016 on all plans. Source: me, co-founder

### CODE REVIEW

**Comment by RichJeanes** [comment]
As per Travis,

```
<------------ ERROR ------------>
1. Kayako should not contain a 'sms' tag when it's value isn't 'YES'.
2. Kayako should not contain a 'phone' tag when it's value isn't 'YES'.
3. Kayako should not contain a 'twitter' tag as it supports TFA.
```

Also, please include a `doc` link to available documentation for enabling 2FA on an account.

For additional information, please consult our [CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md) or the [Wiki](https://github.com/2factorauth/twofactorauth/wiki).

**Comment by RichJeanes** [comment]
@jmedwards Bump?

**Comment by Jawshy** [comment]
I would like to submit a new pull request with the suggested changes if that's okay.

**Comment by RichJeanes** [comment]
Sure. Go ahead and I'll close this one for you.

**Pull request closed without merging**
