### PR TITLE
use better external check system

### PR DESCRIPTION
**Pull request by stephengroat**
https://github.com/gjtorikian/html-proofer/issues/376#issuecomment-332770021

### CODE REVIEW

**Comment by Carlgo11** [comment]
@stephengroat is this ready to be merged?

**Comment by stephengroat** [comment]
yup, moves off of `osx` and seems to be stable (it has been made the official recommendation in `html-proofer`)

**Review by jamcat22 — APPROVED** [review]
Looks good to me if no more changes are required.

**Comment by stephengroat** [comment]
tested with a merge of current master and it still looks good

**Pull request merged**
