### PR TITLE
Add tilaa.com

### PR DESCRIPTION
**Pull request by djkrul**

### CODE REVIEW

**Comment by Carlgo11** [comment]
no doc?

**Comment by djkrul** [comment]
Docs are integrated in our dashboard, so I can't add an external link. Is that required? Lots of other providers don't have a doc link either.

**Comment by Carlgo11** [comment]
It's not obligatory but highly recommended.
Can you provide a screenshot?

**Comment by djkrul** [comment]
Sure:

2fa_screenshot

**Comment by mxxcon** [comment]
@djkrul if you use google auth and yubikey, why do you require sms?

**Comment by djkrul** [comment]
@mxxcon SMS is required as a fallback mechanism to disable 2FA in case the 2FA device itself is lost.

Please read this for more background info:
http://blog.tilaa.com/post/128110588046/two-factor-authentication-and-session-management

**Comment by Carlgo11** [comment]
That links looks like a pretty good doc link. Add it?

**Comment by djkrul** [comment]
@Carlgo11 Good idea! I just updated my pull request to include a doc link

**Pull request merged**
