### PR TITLE
Add ProduBanco

### LINKED ISSUE #6979: Add ProduBanco
### Site name

ProduBanco

### Site URL

https://www.produbanco.com.ec/

### Documentation URL

https://www.produbanco.com.ec/media/677613/manual-activaci%C3%B3n-token-digital2021.pdf

### Recovery Documentation URL

_No response_

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [X] Proprietary Software (Authy, Duo, etc.)
- [ ] U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [X] SMS tokens
- [ ] Email tokens

### Regions served

Ecuador (only)

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Similarweb](https://www.similarweb.com/).
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md).
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues) or [pull request](https://github.com/2factorauth/twofactorauth/pulls).

### Additional information

2FA is only possible via SMS or the third-party, proprietary app made by "Entrust"

 * https://play.google.com/store/apps/details?id=com.entrust.identityGuard.mobile&gl=US

### PR DESCRIPTION
**Pull request by hkamran80**
Resolves #6979

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
1. Here's a SVG for you to use instead: logo
2. Regions don't need to be listed in `regions.yml` for them to be used in entries. `regions.yml` is used by Jekyll to generate regional pages and a region needs to have at least 10 entries specifically targeting said region before it can be listed in `regions.yml`.

**Comment by hkamran80** [comment]
> Here's a SVG for you to use instead

How did you find this? Did you find a full-size logo, then remove the wordmark?

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
@hkamran80 Yes. I searched for `ProduBanco filetype:svg` on Google, clicked on images and found one with the logo. Then I opened the file in Inkscape (though any SVG-editing tool can be used) and removed the text parts.
`ctrl+shift+R` to resize the ViewBox and then a run through [SVGOMG](https://jakearchibald.github.io/svgomg/) and Voilà! :wink:

**Comment by hkamran80** [comment]
@Carlgo11 Cool! Thanks for sharing!

**Pull request merged**
