### PR TITLE
Add Runtastic [Health]

### PR DESCRIPTION
**Pull request by Jawshy**
#### Changes:
- Added: [Runtastic](https://www.runtastic.com/) under health. 
  - No TFA. [Twitter handle](https://twitter.com/Runtastic). 

See also: https://github.com/2factorauth/twofactorauth/pull/1960.

### CODE REVIEW

**Comment by stephengroat** [comment]
want to add the `facebook: runtastic` tag too?

**Comment by Jawshy** [comment]
It has been done. 

On another note, see https://github.com/2factorauth/twofactorauth/issues/1996.

**Review by stephengroat — CHANGES_REQUESTED** [review]
Could you merge with master? Seems like the PR got a bit stale. You can merge through the web UI now!

**Review by Carlgo11 — APPROVED** [review]

**Comment by Jawshy** [comment]
All good now?

**Comment by Carlgo11** [comment]
yes

**Pull request merged**
