### PR TITLE
Updates Userify in cloud.yml

### PR DESCRIPTION
**Pull request by perpetual-hydrofoil**
Add'l comments for old pull request:
https://github.com/2factorauth/twofactorauth/pull/1563#issuecomment-177316781

### CODE REVIEW

**Comment by mxxcon** [comment]
What's the point of this pull request if you make exactly the same change in #1563?

**Comment by perpetual-hydrofoil** [comment]
Trying to make patch-4 branch cleaner than patch-3, sorry for the extra pull req.

**Comment by perpetual-hydrofoil** [comment]
Thanks!

**Comment by Carlgo11** [comment]
No problem. The changes will be public within a couple of days.
For more information on how this process works you can take a look at out [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_Merge).

**Comment by perpetual-hydrofoil** [comment]
Ah cool! btw thanks for pushing 2FA. (If only my banks could handle TOTP..)

**Pull request merged**
