### PR TITLE
Add Admiral (UK)

### PR DESCRIPTION
**Pull request by hassankhan**
Add [Admiral UK](https://admiral.com).

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Add appropriate region tags please

**Comment by hassankhan** [comment]
Hi @Carlgo11, thanks for the feedback. I think I've updated it correctly now 👍

**Review by Carlgo11 — APPROVED** [review]
Yup, looks good! :+1:

**Comment by hassankhan** [comment]
May also be an idea to add some documentation regarding the `regions` property in the `CONTRIBUTING.md`, could be handy for future contributors

**Review by phallobst — APPROVED** [review]

**Pull request merged**
