### PR TITLE
Added site: Canada Revenue Agency [Finance]

### PR DESCRIPTION
**Pull request by tfriesen**
New site: Canada Revenue Agency. Handles federal and provincial taxation for all Canadian citizens and residents.

### CODE REVIEW

**Comment by Jawshy** [comment]
You may prefer to use this icon over the current one. It's smaller and it's the site's current favicon. 
canadarevenueagency

**Comment by tfriesen** [comment]
I would prefer that icon, thank-you.

**Comment by Carlgo11** [comment]
We have places all IRS-related sites in the `other` category. Please move CRA there too.

**Comment by tfriesen** [comment]
It is done.

**Comment by Carlgo11** [comment]
Whops there's a merge conflict :cry:

**Comment by stephengroat** [comment]
This series of emails when I got wifi working on a plane was amazing. I
thought something had crashed at work, instead just 50 merge conflicts

**Comment by Carlgo11** [comment]
@stephengroat sounds like fun!

**Review by Carlgo11 — APPROVED** [review]

**Comment by stephengroat** [comment]
Just as an FYI, I can no longer merge these changes in. Squash and merge is grayed out or "Required statuses" are blocking

screenshot 2016-09-14 at 21 01 18

**Comment by Carlgo11** [comment]
@stephengroat try and approve it as well. Maybe it will work then

**Review by stephengroat — APPROVED** [review]

**Comment by Carlgo11** [comment]
haha well this is odd

**Pull request merged**
