### PR TITLE
Add German bank 'Comdirect'

### PR DESCRIPTION
**Pull request by joyofdata**

### CODE REVIEW

**Comment by jamcat22** [comment]
@joyofdata Thanks for the PR!

Could you remove the "." before "comdirect"? I know that's how it's stylized, but removing the dot will make sure it's in the right place alphabetically.

**Comment by joyofdata** [comment]
@jamcat22: :thumbsup:

**Comment by jamcat22** [comment]
Thanks @joyofdata!

**Comment by joyofdata** [comment]
Why is the code not deployed yet?

**Comment by RichJeanes** [comment]
As per the [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_Merge), changes will not show on the live site until `master` is merged into `gh-pages`.

**Pull request merged**
