### PR TITLE
Add Beam [Entertainment]

### PR DESCRIPTION
**Pull request by 2Cubed**
Add [Beam](https://beam.pro) under Entertainment.

### CODE REVIEW

**Comment by Jawshy** [comment]
[Travis CI log](https://travis-ci.org/2factorauth/twofactorauth/builds/159122235): 

```
1. Beam: The YAML tag 'sms' should either have a value set to 'Yes' or not be used at all. (Current value: 'false')
```

@2Cubed, you may like to use this icon instead. It's a similar icon, but significantly smaller in file size. 
beam

**Comment by 2Cubed** [comment]
@Jawshy Fixed. Thanks for the tips.

**Comment by Jawshy** [comment]
No worries. However, you now have `tfa` set to `Yes`, without any type(s) of TFA being specified. If the site uses TFA see [FAQ_New_TFA_SITE](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_TFA_SITE) else see [FAQ_New_SITE](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_SITE).

**Comment by stephengroat** [comment]
@2Cubed and @Jawshy , thanks for the work. looks good

**Comment by Jawshy** [comment]
Does Beam have any documentation regarding the use of software two-factor authentication? I did some searching but I couldn't find any official documentation; mostly just forum posts by users asking about TFA for an app and more TFA options.

**Comment by 2Cubed** [comment]
@Jawshy Not as far as I know. It's fairly straightforward, though - in `Account` settings, under `Security`, there's an `Enable Two-Factor Authentication` button.

cc: @MattJustMatt @connor4312 @ProbablePrime

**Comment by Carlgo11** [comment]
Screenshot?

**Comment by 2Cubed** [comment]
image

**Comment by connor4312** [comment]
(Beam dev)

No official docs yet, @Jawshy. I've pinged our community team to look at adding one to our knowledgebase. I'll follow up when we get one added.

Also, thanks @2Cubed for PRing us! 😄

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
