### PR TITLE
Added Bitcoin-Central, Bitpay, BTC-E, Coinkite, 

### PR DESCRIPTION
**Pull request by jamcat22**
and Eclipse Mining Consortium

Also corrected capitalization. See pull request #448

### CODE REVIEW

**Comment by mxxcon** [comment]
Still not much luck on those logos? :)

**Comment by jamcat22** [comment]
See #448 comment 2

**Comment by jamcat22** [comment]
Might take a day to brute force it. :(

**Comment by mxxcon** [comment]
@jamcat22 accept my PR into your branch for these logos and then update yaml file to link to them.

**Comment by jamcat22** [comment]
@mxxcon Just out of curiosity, where are you getting these logos?

**Comment by mxxcon** [comment]
@jamcat22 looked on each website in corp relations sections, they usually have high res assets for media. otherwise just google for company name + logo and then crop/resize to proper sizes.

**Comment by jamcat22** [comment]
@mxxcon Ok cool.

**Comment by jdavis** [comment]
Is this good to merge?

**Comment by jamcat22** [comment]
It should be good.

**Pull request merged**
