### PR TITLE
Add Fidelity Investments

### PR DESCRIPTION
**Pull request by gfbarros**

### CODE REVIEW

**Comment by computmaxer** [comment]
This is related to #140.
@jdavis what do you think, should we merge this?

**Comment by zach-taylor** [comment]
Looks good to me

**Comment by computmaxer** [comment]
Reason I was questioning it is because it sounds like they have some kind of solution if you call them to turn it on and this PR shows that they do not support it at all.

**Comment by gfbarros** [comment]
Unless they already offer it to everyone, shouldn't we push for that?

Pardon my grammar, sent from a mobile device.

**Comment by jdavis** [comment]
Yeah, I think this is fine to merge. It's ridiculous to hide a security feature behind a phone call.

**Pull request merged**
