### PR TITLE
Add BLACKLIST.md to show removed sites

### PR DESCRIPTION
**Pull request by jdavis**
I think this will help provide documentation on why we remove/don't list a site.

### CODE REVIEW

**Comment by mxxcon** [comment]
"blacklist" sounds like they are being punished...Unless you want to add such site there as well?

**Comment by jdavis** [comment]
Hmm, I suppose I can see that. Any ideas on what we can call it then?

**Comment by mxxcon** [comment]
excluded?
not applicable?
unlisted? (delisted also sounds negative)

**Comment by jdavis** [comment]
Yeah, I like excluded/exclusion. How's that?

**Comment by mxxcon** [comment]
:+1:

**Pull request merged**
