### PR TITLE
Add Rumble Network Discovery

### LINKED ISSUE #6393: Add rumble.run
### Site name

Rumble Network Discovery

### Site URL

https://rumble.run

### Documentation URL

https://www.rumble.run/docs/managing-your-team/

### Supported 2FA methods

- [ ] TOTP (RFC-6238, Google Authenticator)
- [X] Proprietary Software (Authy, Duo, etc.)
- [X] FIDO2/U2F/WebAuthn security keys
- [X] Proprietary hardware (Yubico OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

### Eligibility

- [X] I have checked that the site meets 2fa.directory's [contributing guidelines and site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [X] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [X] The site does not contain or promote content that violates 2fa.directory's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.
- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### Additional information

Category: Security

### PR DESCRIPTION
**Pull request by fletcherdodd**

### CODE REVIEW

**Comment by fletcherdodd** [comment]
#6393

**Comment by fletcherdodd** [comment]
This request needs to be linked to the #6393 issue

**Comment by Carlgo11** [comment]
@fletcherdodd tip for future PRs: If you comment `resolves #{issue number}` or `closes #{issue number}` in the PR description it will automatically link the two.

**Comment by fletcherdodd** [comment]
> @fletcherdodd tip for future PRs: If you comment `resolves #{issue number}` or `closes #{issue number}` in the PR description it will automatically link the two. 

Didn't know that, thanks

**Review by Carlgo11 — APPROVED** [review]

**Review by phallobst — APPROVED** [review]

**Pull request merged**
