### PR TITLE
Adding 101domain to list of supporting Domain Registrars

### PR DESCRIPTION
**Pull request by tresni**
I use them for one domain so figured I should find out.  The software clients for VIP Access work (even though everything says "Security Card.")

### CODE REVIEW

**Comment by jdavis** [comment]
Cool, this looks good to me, :+1:. I'll give it a bit of time to let others see it.

**Comment by mxxcon** [comment]
It looks like they are using Symantec VIP system, so maybe match its features?

**Comment by jdavis** [comment]
What do you mean, @mxxcon? VIP has hardware and software and both are added for 101domain.

**Comment by mxxcon** [comment]
my fault. for some reason i remembered they also do sms and phone. sorry. :)

**Comment by jdavis** [comment]
Ah, I gotcha. I actually had to double check VIP as well. I was a little unsure on the software side based on 101's docs.

**Pull request merged**
