### PR TITLE
Add Render (render.com)

### PR DESCRIPTION
**Pull request by anurag**
Render is a top 200K site and supports TOTP 2FA.

### CODE REVIEW

**Comment by Carlgo11** [comment]
@anurag as you might have seen the build failed. I did some debugging and the problem seems to be with your certificate chain as it is sending the old DST Root CA X3 that just expired (UTC time).

I suggest you update the chain or generate a new certificate from LE.

You can verify that your website certificate works by doing: 
```sh
echo | openssl s_client -showcerts -servername render.com -connect render.com:443 2>/dev/null | openssl x509 -inform pem -noout -text
```
If the final certificate no longer has an expiry timestamp of `Sep 30 12:23:23.689 2021 GMT` then everything is working.

**Comment by anurag** [comment]
My output for the command you mentioned shows an expiry date of  Dec 29 11:23:22 2021 GMT:

```
echo | openssl s_client -showcerts -servername render.com -connect render.com:443 2>/dev/null | openssl x509 -inform pem -noout -text
```

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:9c:c6:42:72:6b:3d:24:16:64:80:1e:20:ef:3f:4d:65:b3
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Let's Encrypt, CN=R3
        Validity
            Not Before: Sep 30 11:23:23 2021 GMT
            Not After : Dec 29 11:23:22 2021 GMT
        Subject: CN=render.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:ba:f6:a7:73:89:a2:d4:88:8d:c3:04:96:f3:40:
                    32:12:17:45:f5:a5:8a:cb:98:d1:80:db:1b:e2:fe:
                    08:f7:39:58:7e:b2:95:15:f7:40:6e:d2:de:58:ec:
                    d6:57:d5:e8:78:79:80:78:15:ad:19:5c:66:45:ff:
                    05:44:e9:37:af:9e:4f:cb:e6:e2:c5:4b:82:90:ab:
                    31:32:b5:1d:05:64:1b:aa:69:17:60:19:cf:c0:a8:
                    83:4e:ab:8e:78:e2:5a:a0:55:9a:af:85:4e:6c:3d:
                    03:3b:d4:a3:a0:0e:f2:5d:60:4d:72:05:95:dd:49:
                    43:89:aa:b6:4e:92:64:9d:b6:65:a6:41:7f:40:67:
                    91:b8:bd:10:8d:34:36:6c:2d:c6:c1:71:0b:af:63:
                    03:c5:40:be:01:6a:92:44:a5:1c:79:f5:9c:2f:fc:
                    48:30:c4:1d:14:44:f7:b6:63:81:b7:50:04:02:5b:
                    3a:73:a6:6c:16:68:29:c1:c3:d0:0e:0b:da:17:44:
                    36:bd:33:bb:b1:9d:e2:f5:92:46:e6:9f:df:a0:ec:
                    8d:75:50:21:53:df:d8:56:ea:8f:ae:94:8a:98:08:
                    38:c7:be:59:e0:c0:3d:98:97:47:2f:fa:a7:60:ad:
                    bf:70:1d:44:87:d1:74:69:44:82:47:e6:09:f4:d6:
                    0c:c1
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                39:6F:30:ED:EE:67:6B:09:B9:3F:2B:85:7C:95:F5:2B:BB:19:2B:3F
            X509v3 Authority Key Identifier: 
                keyid:14:2E:B3:17:B7:58:56:CB:AE:50:09:40:E6:1F:AF:9D:8B:14:C2:C6

            Authority Information Access: 
                OCSP - URI:http://r3.o.lencr.org
                CA Issuers - URI:http://r3.i.lencr.org/

            X509v3 Subject Alternative Name: 
                DNS:render.com
            X509v3 Certificate Policies: 
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org

            1.3.6.1.4.1.11129.2.4.2: 
                ......v.. .....l.s...",
..M^lO.=a.N/XM.....|6..6.....G0E. Q..?H?....l.K41l.I..X......<F....!..7.^W..ab5....`Or..L..$.2.JH..l..v..\./.w0".T..0.V..M..3.../ ..N.d....|6..).....G0E.!...G..}jc..?l.....e.Kx?J..=a@..#.. _|....[..d[<......b5..s..`.d| .{
    Signature Algorithm: sha256WithRSAEncryption
         6f:f9:f4:67:3c:f3:93:ec:c3:08:fb:26:4c:e4:c6:74:4d:89:
         10:5f:c1:ec:ef:11:08:a6:7e:e3:76:8a:18:76:7a:1b:17:d2:
         7e:76:ee:78:88:84:57:20:55:26:11:92:d9:59:d7:1f:d3:f6:
         30:d2:59:da:67:bc:4c:7c:93:64:28:d5:13:f6:59:f1:a3:7b:
         3e:6f:6d:93:f6:9d:bc:c8:e7:53:c6:50:29:48:1b:60:3b:b8:
         06:20:a4:48:ab:ae:60:d3:4a:4c:b3:a1:c9:80:53:4d:f5:e5:
         c3:67:4c:ea:f3:9d:5f:38:bd:e9:81:4a:17:09:b1:6e:46:a5:
         4c:2c:54:86:95:7b:cd:7b:38:a8:d3:36:9e:4e:83:53:c6:e3:
         ea:26:2a:80:fe:58:77:2a:eb:1e:b5:26:21:d4:6d:af:7b:5b:
         c7:14:10:1f:dd:c8:ab:ef:b6:40:c4:60:a0:76:56:75:a9:ce:
         8e:a2:51:af:df:a9:79:ed:e7:c9:f3:33:73:66:1a:c9:08:f4:
         3e:ca:f7:4a:e2:3f:02:6d:8b:58:cf:31:99:d5:b0:91:d3:2c:
         f1:30:40:9a:f8:92:5e:0e:64:a7:9b:97:30:76:df:8e:26:42:
         63:6d:74:0d:06:8d:e3:b7:71:23:c8:ad:d6:8b:fa:eb:da:c0:
         1c:9f:7d:8c
```

**Comment by anurag** [comment]
I believe the issue is related to `httpclient`: https://github.com/nahi/httpclient/issues/445.

@Carlgo11 my guess is the test is going to fail for any site using Let's Encrypt certificates, because `httpclient` uses an old hard-coded CA.

**Comment by anurag** [comment]
As a follow up, I've tested my changes with the fix in this PR: https://github.com/2factorauth/twofactorauth/pull/6150

**Review by Carlgo11 — COMMENTED** [review]
I minimized the SVG and removed the `additional-domains` array as it just contained a subdomain.

Could you provide a documentation page for enabling 2FA on Render accounts?

**Comment by anurag** [comment]
> I minimized the SVG and removed the `additional-domains` array as it just contained a subdomain.
> 
> Could you provide a documentation page for enabling 2FA on Render accounts?

Thanks! We don't have a specific docs page, because the dashboard UI has been self-explanatory to our users (developers). Okay to merge without?

Image 2021-10-01 at 8 06 55 AM

**Review by ApCoder123 — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]
Thanks the screenshot is sufficient :+1:

**Comment by anurag** [comment]
Thanks!

**Pull request merged**
