### PR TITLE
Move "Music" to "Entertainment"

### PR DESCRIPTION
**Pull request by Carlgo11**
And added spotify, youtube, vimeo, twitch.

### CODE REVIEW

**Comment by mxxcon** [comment]
@Carlgo11 please update your .gitingore file to exclude _Thumbs.db_ files.
Afaik LastPass does not use sms or phone calls for 2FA

**Comment by Carlgo11** [comment]
@mxxcon They use Authy which use sms and phone calls https://www.authy.com/

**Comment by Carlgo11** [comment]
I failed didn't I? :/

@mxxcon Should I redo all this and post a new pull request?

**Comment by mxxcon** [comment]
@Carlgo11 They don't use Authy specifically.
LastPass uses Google Authenticator TOTP, which by extension includes Authy because it also supports that method.
However, afaik that does not enable sms or phone calls. That happens only if software/site/service implements Authy's native 2FA method. TOTP is generally computed on the device, no Authy's server-side component is involved...afaik.

At this point don't do another pull request. Just update this one deleting all thumbs.db files.

**Comment by Carlgo11** [comment]
nope I failed once again. sorry but new pr needed :(

**Comment by jdavis** [comment]
@Carlgo11 For future reference, you can update a pull request by doing a `git push --force`. Any changes you make to the history will be updated on GitHub. It allows you to rebase, squash, etc. You can even undo all commits if you messed up too much.

**Pull request closed without merging**
