### PR TITLE
Add Countly

### PR DESCRIPTION
**Pull request by 40504**

### CODE REVIEW

**Comment by phallobst** [comment]
This seems to be a self-hosted software package - at least I can see no login page. We don't list those [see EXCLUSION.md].

**Comment by 40504** [comment]
https://try.count.ly/login it's possible to use both

**Comment by phallobst** [comment]
Is there an official link to that login page? I can't see it... The "try" part might indicate that it's just a demo installation on their site.

**Comment by 40504** [comment]
on the premium, https://count.ly/pricing, is available on both, self and cloud

**Comment by phallobst** [comment]
I'm still not quite sure if it meets our requirements, to be honest.

**Comment by Carlgo11** [comment]
As our site is focused on aiding normal consumers in choosing services and not focused on enterprise customers it would mean the enterprise edition of Countly is out of our scope. Since the non-enterprise edition is self-hosted it's out of scope as well.

Sorry for the inconvenience!

**Pull request closed without merging**
