### PR TITLE
Add Authenticator Plus

### PR DESCRIPTION
**Pull request by MufriA**
Authenticator Plus is a mobile app similar to Google Authenticator with backup/sync features (authenticatorplus.com)

$ ruby verify.rb
No errors. You're good to go!

### CODE REVIEW

**Comment by mxxcon** [comment]
@MufriA ~~why google logo?~~ Good catch.

**Comment by MufriA** [comment]
@mxxcon Google logo was 16 px so I have included 32 px icon, i wanted to create new PR for it however it got included in pending PR i supposed.

I should learn how github PR works.

**Comment by mxxcon** [comment]
@MufriA yup, surprising didn't notice small logo sooner.
 PRs are per branch. :)
That's why it's smart not to commit directly into `master`, but rather into a separate branch. Keep change sets compartmentalized. :)

**Comment by MufriA** [comment]
@mxxcon ah got it, should i create new PR or PR can be merged partially?

**Comment by mxxcon** [comment]
I think it's fine as is.

**Pull request merged**
