### PR TITLE
Zocle doc URL

### PR DESCRIPTION
**Pull request by mxxcon**

### CODE REVIEW

**Review by fpigerre — APPROVED** [review]

**Comment by Carlgo11** [comment]
The new URL doesn't work for me.
screenshot_2017-09-11_13-00-06

`Unable to communicate securely with peer: requested domain name does not match the server’s certificate.`

__Edit__: Seems like their cert is only valid for www and @, not \* or the university subdomain

**Comment by mxxcon** [comment]
@2factorauth/collaborators bump?

**Review by Jawshy — CHANGES_REQUESTED** [review]
For me, the [old `doc`](http://university.zocle.com/2015/03/30/new-security-feature-two-step-verification/) link redirects to [here](https://zocle.com/zocle-university//2015/03/30/new-security-feature-two-step-verification/) and I cannot access the [new link](https://university.zocle.com/knowledgebase/enabling-two-step-verification/). I receive `university.zocle.com took too long to respond.` `ERR_CONNECTION_TIMED_OUT`. 

EDIT: `https://zocle.com/knowledgebase/enabling-two-step-verification/` works.

**Comment by mxxcon** [comment]
Ya... 🤦‍♂️ they keep changing their domains

**Review by Jawshy — APPROVED** [review]

**Review by jamcat22 — APPROVED** [review]

**Pull request merged**
