### PR TITLE
Added health section (refork)

### PR DESCRIPTION
**Pull request by JimmyW7**
Reforked after last re-organization of data files.

### CODE REVIEW

**Comment by jdavis** [comment]
And all we need are icons and this will get merged instantly.

**Comment by JimmyW7** [comment]
Working on that now

**Comment by JimmyW7** [comment]
Done

**Comment by zach-taylor** [comment]
Wouldn't this still need an entry in main.yml?

**Comment by jdavis** [comment]
I'm manually fixing this now. It had some Yaml issues too. I'll merge it
and close this soon.

**Comment by jdavis** [comment]
Great work, @JimmyW7 and thanks for being persistent/understanding. :+1:

**Pull request closed without merging**
