### PR TITLE
Add chime

### PR DESCRIPTION
**Pull request by stephengroat**
#2359

### CODE REVIEW

**Comment by mxxcon** [comment]
Should we somehow distinguish it from https://chime.aws ?

**Comment by stephengroat** [comment]
it's calling itself "Amazon Chime," I think that's good enough

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
I suggest using this logo instead.
It's better for lower resolutions and the one that Chime uses as their favicon.
chimebank

**Comment by stephengroat** [comment]
image updated

**Review by Carlgo11 — APPROVED** [review]

**Review by jamcat22 — APPROVED** [review]

**Pull request merged**
