### PR TITLE
add Netgear and Icon to "other" list

### PR DESCRIPTION
**Pull request by Zeik0s**
feel free to change the category, if it should be more specific.

### CODE REVIEW

**Comment by phallobst** [comment]
Please rebase your branch to the current master.

**Comment by Zeik0s** [comment]
I hope i did as you wish.

**Comment by Carlgo11** [comment]
@Zeik0s 
```PWSH
# Resetting your branch to the most up to date version of our repository:
git remote add upstream https://github.com/2factorauth/twofactorauth.git
git fetch upstream
git reset --hard upstream/master

# Adding back your commits:
git cherry-pick e08361b
git cherry-pick c15d4b4

# Pushing the changes to GitHub:
git push origin master:master -f
```

**Comment by Carlgo11** [comment]
Thank you! 👏

**Comment by Zeik0s** [comment]
No, **thank you** for learning how to properly rebase my forked repo :)

**Comment by Carlgo11** [comment]
There are many ways to do it but this is how I do it 😅

Looking at your pull request,
as you haven't specified any documentation URL I guess you couldn't find a page describing how to set up 2FA on Netgear?

**Comment by Zeik0s** [comment]
Didn't find one last time, but now i did and added it.

**Review by Carlgo11 — APPROVED** [review]

**Review by phallobst — COMMENTED** [review]
Reading the doc page, it seems that only SMS is available. Can you confirm or deny this?

**Comment by Zeik0s** [comment]
I can't because when i wanted to login to my account now they didn't ask me for either of those two things. Also for a new created account they didn't even provide the option to provide a phone number. And for my old account i had no option to check my 2fa settings, as if they completed 2fa on their login flow at all. 

So what to do now? The request for sure shouldn't be merged, should i change it to state that Netgear doesn't support 2fa or close the request completely?

**Comment by Carlgo11** [comment]
I feel bad for all the work you put in @Zeik0s 😞
Sounds like they either use 2-step verification instead of 2-factor authentication, or they just stopped doing 2FA 🤷 

Either way, the options now are to 1. close the PR or 2. repalce the `tfa` and `doc` tags with social media tags to get them to support 2FA (again?)

**Comment by Zeik0s** [comment]
Thought about it, since the situation is not clear at all, i will for now close this PR.

**Pull request closed without merging**
