### PR TITLE
Updates to Symantec VIP offering

### PR DESCRIPTION
**Pull request by kunala**
Added compatibility changes as seen on Symantec website

### CODE REVIEW

**Comment by Carlgo11** [comment]
Can you give us a link where they mention this?

**Comment by kunala** [comment]
Here is the link: http://www.symantec.com/content/en/us/enterprise/fact_sheets/b-vip_intelligent_authentication_DS_21213685.en-us.pdf

**Comment by mxxcon** [comment]
Hmm..that document is from 2011, I wonder if it is still current or if they removed those methods?
https://idprotect.vip.symantec.com/orderstart.v lists only mobile app, desktop app and physical tokens, no mention of sms, phone call or email
Then I also found https://knowledge.verisign.com/support/identity-protection-support/index?page=content&id=SO19454
But again, it's from 2012..not sure if still current. I guess we need to contact Symantec to find out for sure.

**Comment by kunala** [comment]
Yea there's some unclarity with the specs. Actually I work at Symantec, and
the product does support the out of band. :)

**Comment by jdavis** [comment]
Okay, if @kunala works at Symantec and can testify that the data is accurate, I'd say this looks good to me? :+1: 

@kunala You should contact the team to get some up-to-date documentation for your users =]

**Comment by kunala** [comment]
Yea, will do. Trying to revamp a lot of the usability on the products. Really open to suggestions for this to make it a lot better and easier to integrate.

**Pull request merged**
