### PR TITLE
Add Rocket.Chat

### PR DESCRIPTION
**Pull request by nitrohorse**

### CODE REVIEW

**Comment by mxxcon** [comment]
are there any links that describe this 2fa?

**Comment by nitrohorse** [comment]
@mxxcon Documentation is unfortunately limited from what I can find on their website. The PR for adding 2FA on Rocket.Chat's repo has some details: https://github.com/RocketChat/Rocket.Chat/pull/6476

**Comment by Carlgo11** [comment]
Isn't Rocket.Chat self hosted?

**Comment by nitrohorse** [comment]
@Carlgo11 yeah, it can be [self hosted](https://rocket.chat/docs/installation/paas-deployments/) or one can use [Rocket.Chat's Cloud service](https://rocket.chat/cloud).

**Comment by Carlgo11** [comment]
Our policy is to not list self-hosted services however since you mention they offer a hosted version as well I guess it could work? 🤔 
@2factorauth/collaborators thoughts?

**Comment by jtagcat** [comment]
I'd let in every service, who has an official hosted version.

**Comment by Carlgo11** [comment]
Closing as the fork is no longer available.

**Pull request closed without merging**
