### PR TITLE
Contributing: Add "lang" field to example

### PR DESCRIPTION
**Pull request by Stevoisiak**
Added the 'lang' tag to the example new site

### CODE REVIEW

**Comment by fpigerre** [comment]
Hi @Stevoisiak,

At the moment, the `lang` tag currently isn't required for websites that only use English. This is so that the majority of websites that are listed don't need a `lang` tag. If a website uses a different language, however, such as german, the `lang: de` tag is appended to that website's entry.

Thanks,
psgs 🌴

**Comment by Stevoisiak** [comment]
@psgs I updated my PR to explain the `lang` tag is only used for non-English websites.

**Comment by Carlgo11** [comment]
Maybe add a note that [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) codes should be used?

**Comment by Stevoisiak** [comment]
@Carlgo11 Added the ISO 639-1 specifier

**Comment by RichJeanes** [comment]
Perhaps include the link that Carlgo11 provided in the document so people know what that means.

**Comment by Stevoisiak** [comment]
@RichJeanes I can't use hyperlinks inside a code block.  I'll have to mention ISO 639-1 below the code block instead.

**Comment by RichJeanes** [comment]
That's fine. I just think it would be helpful to include it somewhere.

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
