### PR TITLE
Added identity managemet and provider

### PR DESCRIPTION
**Pull request by wakwanza**
Added new identity management service and provider

### CODE REVIEW

**Comment by mxxcon** [comment]
@wakwanza It seems like both of them should be under `Providers`. Both sites seem to offer various two-factor authentication clients.
`Identity Management` section is more for password managers...
Also please make sure that logos are located in correct directories.

**Comment by wakwanza** [comment]
Sure i have updated the logos directories and will push that change.I will update the Providers  although from saaspass functionality seems akin to a passsword/login wallet for various services more like lastpass.Correct me if im wrong of the difference between ıd management vs provider.

**Comment by mxxcon** [comment]
Identity Management are _consumers_ of two-factor authentication. You would login _into_ `Identity Management` using solutions from `Providers` section.
`Providers` are various two-factor authentication clients...Google Authenticator, other OTP clients, physical RSA tokens, etc.
Saaspass seems to support TOTP and bluetooth proximity authentication. It does not store your actual usernames and passwords like LastPass does.

**Comment by wakwanza** [comment]
Great.Pushing changes according to saaspass as provider.

**Comment by wakwanza** [comment]
Any other changes to get the commit ready to merge.Im not sure about the size of the images is there a specific px ratio.

**Comment by jdavis** [comment]
Thanks for this @wakwanza, the gh-pages branch will be updated soon. Thanks for your patience as well.

**Pull request merged**
