### PR TITLE
Add BW Bank

### PR DESCRIPTION
**Pull request by Scriptkiddi**

### CODE REVIEW

**Review by Carlgo11 — COMMENTED** [review]
How does this site differ from http://www.lbbw.de/de/?

**Comment by Scriptkiddi** [comment]
it doesnt its just an alternative url the bank uses did i miss 2factorauth offering this site already?

**Comment by Carlgo11** [comment]
No but https://www.bw-bank.de links to http://www.lbbw.de at the bottom of the page. So which one is the main page for the bank?

**Comment by stephengroat** [comment]
from the [about page of lbbw](http://www.lbbw.de/en/ueber_uns/unternehmensprofil/unternehmensprofil.jsp), that is a group that owns bw-bank and seems to be a seperate enough entity (with seemingly seperate auth, at least on IP addresses)

**Comment by Scriptkiddi** [comment]
i would go with bw-bank.de since the online banking site listens under banking.bw-bank.de

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
