### PR TITLE
Added name.com

### PR DESCRIPTION
**Pull request by sudeepkodavati**
*Added Name.com 
*It uses VeriSign for tfa.

### CODE REVIEW

**Comment by jdavis** [comment]
Awesome. Would you be able to grab the Name.com favicon to add? http://www.convertico.com/ works pretty well!

**Comment by sudeepkodavati** [comment]
*Added the png for name.com.

**Comment by jdavis** [comment]
I had to double check what the heck it was.. That is a strange 2FA solution.

**Comment by jdavis** [comment]
Nice work though! Cheers!

**Pull request closed without merging**
