### PR TITLE
Add BB&T Bank

### PR DESCRIPTION
**Pull request by expertsnipo**
2fa not supported by BB&T

### CODE REVIEW

**Comment by expertsnipo** [comment]
Not sure why Travis CI build failed. I am successfully running the site with my changes locally.
bbt1

**Review by mxxcon — CHANGES_REQUESTED** [review]
@expertsnipo please make sure your copy of `.travis.yml` matches what we have in our repo.
If you want to experiment with it, please do it in a separate branch, not in master.

**Comment by mxxcon** [comment]
I think something goofy is going on with TravisCI itself. 🤔

**Comment by expertsnipo** [comment]
It seems so.

**Comment by Carlgo11** [comment]
Nope. Fails locally for me as well. Doing a cherry pick would probably help.

**Comment by Carlgo11** [comment]
So the problem is the `&`. In HTML that's used for symbols. 
What we could do is change it to `&amp;`. Then it will show up as `&` on the site but it will show up as `&amp;` in the data.json. :confused:

**Comment by expertsnipo** [comment]
Updated with the requested changes. I assumed the yaml wouldn't be directly interpreted into HTML - my mistake.

**Review by expertsnipo — COMMENTED** [review]
Is this good to go? I reverted the .travis.yml file a few days ago.

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
