### PR TITLE
Add Front App

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Thanks for the commit @nicolasleger :smile:

**Comment by mxxcon** [comment]
Perhaps use their official image? https://frontapp.com/assets/img/icons/favicon-32x32.png

**Comment by nicolasleger** [comment]
I updated the image with the official favicon. Thanks

**Comment by RichJeanes** [comment]
I'm getting an HTTPS certificate error on that support link. It looks like a chain cert issue. Anyone else seeing that?

**Comment by Jawshy** [comment]
@RichJeanes, for me Chrome shows the site's certificate as valid and trusted. Firefox initially showed an error, but upon trying again it shows no issues or errors.

**Comment by RichJeanes** [comment]
Hmm, that's strange. I only see the certificate issue on one PC, but I don't see it on my phone. Must just be my machine. Thanks for verifying that for me though.

**Comment by Jawshy** [comment]
It gets stranger. I tried accessing the site on Chrome for Android and it reports that the "server's certificate is not trusted". 

Edit: My phone doesn't have the certificate installed whereas by desktop does have the certificate.

**Comment by mxxcon** [comment]
Looks like they fixed the cert chain issue. They are not providing intermediate cert, whereas before they didn't.

**Pull request merged**
