### PR TITLE
Sorted payments.yml and added Square.

### PR DESCRIPTION
**Pull request by mxxcon**
Square is that smartphone credit card swipe thingie.

### CODE REVIEW

**Comment by jdavis** [comment]
For some reason the icon doesn't load for me...

**Comment by mxxcon** [comment]
@jdavis seems like usual github glitches :/
That image is here https://github.com/mxxcon/twofactorauth/blob/Square/img/payments/squareup.png

**Comment by jdavis** [comment]
Ahh, okay. Strange.

**Comment by jdavis** [comment]
It loads now too, btw. Thanks for this @mxxcon. You're pretty awesome and very close to becoming an official Collaborator =]

**Pull request merged**
