### PR TITLE
Add Temple University

### PR DESCRIPTION
**Pull request by LeoNel**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Hello @LeoNelson,
it looks like the build failed.

Here's the log output:

```
<------------ ERROR ------------>

1. Temple University: The YAML tag 'hardware' should either have a value set to 'Yes' or not be used at all. (Current value: 'false')

2. Temple University image not found.
```

**Comment by stephengroat** [comment]
Here's an image that you can add to img/education

temple

**Comment by Carlgo11** [comment]
Closing due to inactivity

**Comment by stephengroat** [comment]
pushed a pr to his `patch-1` branch.

give it a week to see if he'll merge it in.

**Pull request closed without merging**
