### PR TITLE
Zimbra Blog post about TFA

### PR DESCRIPTION
**Pull request by jorgedlcruz**

### CODE REVIEW

**Comment by RichJeanes** [comment]
Is it fair to mark this site as `tfa: yes` when they say that 2FA support is a tech preview stage feature?

**Comment by jorgedlcruz** [comment]
Well, the TFA feature is there and works already on the ZCS 8.7 Beta, which will be released this month, as the note said ZCS supports TFA starting in ZCS 8.7.

We can wait until is GA if you want.

**Comment by Carlgo11** [comment]
bump.
Can anyone confirm that it looks good?

**Comment by jamcat22** [comment]
Thanks for the PR @jorgedlcruz! While it has been merged, it may take awhile before your changes appear on the main website. For more info about this process, check out our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_Merge).

**Pull request merged**
