### PR TITLE
Add Bugzilla@Mozilla

### LINKED ISSUE #1837: Please add Bugzilla@Mozilla
https://bugzilla.mozilla.org.

They have 2FA with TOTP.

### PR DESCRIPTION
**Pull request by tnorthcutt**
Closes #1837

### CODE REVIEW

**Comment by mxxcon** [comment]
Does bugzilla@mozilla qualify with our criteria of being listed?

**Comment by kaidl** [comment]
I would say yes as there's a lot of personal info in the form of bug comments etc contained by this site, and if someone took over a bugzilla account from its owner the account owner's image might get hurt in the process.

**Comment by mxxcon** [comment]
@tnorthcutt could you please run that logo file through apps like ImageOptim/Trimage or similar tool to compress it a bit more? It's just over the size limit of our CI check.

**Comment by tnorthcutt** [comment]
@mxxcon done, but it looks like that didn't kick off a new build in TravisCI

**Comment by mxxcon** [comment]
I tried to find any docs that describe what kind of 2fa they use, but couldn't. All i could find were news articles about last year's breach. :/
Perhaps use `doc: https://bugzilla.mozilla.org/userprefs.cgi?tab=mfa`?

**Comment by kaidl** [comment]
TOTP

**Comment by Carlgo11** [comment]
Can confirm that they support TOTP 2FA.
screenshot_1

screenshot_2

**Comment by Carlgo11** [comment]
Actually, I think Bugzilla would fit better in the `other` category as it's not really a developer tool but a bug reporting tool for Mozilla products only.
Please change the category to `other`.

**Comment by RichJeanes** [comment]
@Carlgo11 Shouldn't 713dbc9 have failed TravisCI for not having a corresponding image in the `other` folder the same way that 6ab204d did? Am I missing something or does `verify.rb` need some debugging?

**Comment by Carlgo11** [comment]
@RichJeanes I ran the script locally and then it yields an error.
When looking at the Travis log the SHA1 sum doesn't match up with the one on GitHub so to me it looks like the issue is on Travis' side rather than the script itself.

**Pull request merged**
