### PR TITLE
Add adafruit

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by mxxcon** [comment]
They have online store, but does it store payment info? Beside that is there sensitive that's contained in your account?

**Comment by stephengroat** [comment]
Payment info & addresses are stored, that's it.

**Review by fpigerre — APPROVED** [review]

**Comment by Jawshy** [comment]
A conflict has arisen, @stephengroat. Could you please resolve it?

**Comment by stephengroat** [comment]
cleared

**Comment by Jawshy** [comment]
`looks-good` but now Travis is stuck. 

> ```
>           — Waiting for status to be reported
> ```

**Review by Jawshy — APPROVED** [review]
`looks-good` & Travis passed.

**Comment by mxxcon** [comment]
just fyi, you don't need to make another commit to kick off travis, you can just go to its ui and restart it there. https://travis-ci.org/2factorauth/twofactorauth

**Pull request merged**
