### PR TITLE
Add Dominion

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by jamcat22** [comment]
Their logo is almost impossible to crop down to a square, but try using this one instead:
dom

Also, while it seems like both their @DomVAPower and @DomEastOhio accounts reply to questions, do you think that their Virginia division is the best one to ask?

**Comment by stephengroat** [comment]
Logo updated.

I've from VA, so my bias is pretty obvious here. I'm willing to change it either way!

**Comment by jamcat22** [comment]
I think the VA account is fine. Thanks for changing the image!

**Comment by fpigerre** [comment]
Thanks for the pull request @stephengroat! :+1:

**Pull request merged**
