### PR TITLE
Add Metrological to Developer

### PR DESCRIPTION
**Pull request by JasperV**
+ update TransIP with more details

### CODE REVIEW

**Review by Jawshy — CHANGES_REQUESTED** [review]
Thanks again for submitting another pull request, @JasperV. 

Please use the site's landing page - not their login page - for the `url`. 

Does the site have any public documentation for how they have implemented two-factor authentication?

**Comment by JasperV** [comment]
Hi, @Jawshy 
I have updated the site url as requested.

No, they do not have any documentation on this.

**Comment by Carlgo11** [comment]
@JasperV can you provide us with screenshots of the process then? **(With personal information blurred out)**

**Comment by Carlgo11** [comment]
Hello again @JasperV,
could you please provide us with the screenshots as requested earlier?
If I don't get any response within a couple of days I'll have to close this PR due to inactivity.

Thanks!
//Carl

**Comment by JasperV** [comment]
Hi @Carlgo11, sorry for my delayed response. I will do my best to add the screenshots this week. Where should I add them?

**Comment by Carlgo11** [comment]
Great!
You can add them using GitHub's native attachment posting.
screenshot

**Comment by JasperV** [comment]
image
@Carlgo11, here is the screenshot. When you toggle the Two-step authentication, a QR code is generated in place. There is not anymore to it. Hope this is acceptable.

**Review by Jawshy — APPROVED** [review]
Thanks, @JasperV.

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
