### PR TITLE
Add Orbit bhyve

### PR DESCRIPTION
**Pull request by stephengroat**
An IoT sprinkler

### CODE REVIEW

**Review by Jawshy — COMMENTED** [review]
How does this site meet the [criteria](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria)? I am guessing 4 (Control), but is it significant enough to warrant listing?

**Comment by stephengroat** [comment]
Yes and i think that any control item should be listed. Even if it only scales to the 10s of thousands, that's a lot of sprinklers firing off

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
I don't think meets the criteria.

**Comment by stephengroat** [comment]
how not? it directly controls relays that control sprinkler systems for
homes

**Comment by Carlgo11** [comment]
> This criteria is more general, in that it includes sites that give access to things that may infringe upon criteria 1, 2, or 3. An example of this is a website that allows remote access to a device.

While it may cause some inconvenience I wouldn't say it could cause any long term effects if someone got remote access to your outdoor sprinkler system.

**Comment by stephengroat** [comment]
you can flood yards, crack foundations, etc. it's actually pretty powerful

**Comment by Carlgo11** [comment]
Maybe we can come back to this in the future. As of right now I'd say it's too insignificant to be on our list.
Control to this app also doesn't affect criteria 1 and 2.

**Pull request closed without merging**
