### PR TITLE
Add Postal and Shipping category

### PR DESCRIPTION
**Pull request by mmomjian**
Name was selected because this category includes both governmental mail services and private shippers. I attempted to run a local test which seems to have worked fine (see below)

image

### CODE REVIEW

**Comment by Carlgo11** [comment]
Would `Post & Logistics` work? The word "post" is common in many more languages.

**Comment by mmomjian** [comment]
Sounds good, but I'm unsure what "logistics" means as an American. If I was searching for this category I would probably look for "mail, delivery, shipment/shipping, postal service", etc. How about "Post and shipping" or "post and delivery"?

**Comment by Carlgo11** [comment]
Logistics is the handling of the object from sender to reciever; Including packaging, transporting, storing and delivery.
Shipping is the transporting part of the chain.

Companies like DHL, UPS, FedEx, USPS etc. are logistics companies while companies like AeroLogic, Atlast Air, American Airlines etc. are shipping companies.

**Comment by Carlgo11** [comment]
Actually, yeah "Post & Shipping" could be better. Let's do that :+1:

**Comment by mmomjian** [comment]
Done!

**Review by Carlgo11 — APPROVED** [review]

**Review by phallobst — APPROVED** [review]

**Pull request merged**
