### PR TITLE
Added thexyz domain

### PR DESCRIPTION
**Pull request by ptoone**
I have added Thexyz Webmail!

### CODE REVIEW

**Comment by mxxcon** [comment]
missing a logo..

**Comment by mxxcon** [comment]
your doc link is pointing to a PR announcement..is there a link that describes how to enable 2fa?

**Comment by ptoone** [comment]
I have it, just can't seem to upload. Here is a link to it: https://securecloud.thexyz.com/index.php/s/Ua69N0n5ShRYbvT

**Comment by mxxcon** [comment]
The logo needs to be part of this pull request.

**Comment by ptoone** [comment]
This link is better: https://www.thexyz.com/yubikey/

**Comment by ptoone** [comment]
Should be good now, thanks!!

**Comment by ptoone** [comment]
thexyz

**Comment by mxxcon** [comment]
You need to upload that logo to `patch-3` branch in YOUR repo. Not in the comments here.
If you are still having difficulties figuring out how to do that, perhaps some of your coworkers can guide you through the steps. Git/github is not the most obvious thing.

**Comment by ptoone** [comment]
You'd think one of us could figure it out! Is it okay now?

**Comment by mxxcon** [comment]
Nope, as you can see below, automated check still fails. It verifies that 32x32 image is included in a pull request.

**Comment by ptoone** [comment]
Why does it fail. Can you see what I'm doing wrong?

**Comment by mxxcon** [comment]
with THIS specific pull request branch `patch-3` in YOUR repo is missing a logo. You need to upload it here https://github.com/thexyz/twofactorauth/tree/patch-3/img/email and its filename should be `thexyz.png`. Once you upload the logo into the right place, it'll automatically show up here.

**Pull request closed without merging**
