### PR TITLE
Add Provident Metals

### PR DESCRIPTION
**Pull request by phallobst**
See #4036

### CODE REVIEW

**Review by Jawshy — APPROVED** [review]

**Comment by Carlgo11** [comment]
I feel like a precious metal dealer falls outside of the kind of sites we list here.
It's not really for the general public consumer.

**Comment by phallobst** [comment]
Well, it is listed under "Investing", not "Retail", so it's not supposed to target the general consumer anyway. I don't really see the fundamental difference between investing in stocks vs. commodities like gold or silver. These websites easily meet the necessary criteria (personal info, money).

**Comment by Carlgo11** [comment]
> Well, it is listed under "Investing", not "Retail", so it's not supposed to target the general consumer anyway. I don't really see the fundamental difference between investing in stocks vs. commodities like gold or silver. These websites easily meet the necessary criteria (personal info, money).

But it is. Everything on the site is there for that purpose.
image

**Comment by jamcat22** [comment]
In the US at least, metals and commodities are typically invested in or purchased outright by general consumers all the time. There are tons of commercials (as an example, [this one](https://www.youtube.com/watch?v=YXqWDQB0utA) is a commercial I've seen a ton over the years) on TV and online video that target potential consumer buyers, and the FTC (one of the main federal consumer protection agencies in the US) has even had to create a page on [investing in gold](https://www.consumer.ftc.gov/articles/0134-investing-gold) to help combat common scams that consumer buyers fall into. Provident Metals is directly targeted towards consumers. Businesses typically don't directly buy commodities that they invest in, they typically use commodities exchanges, index funds, or futures trading.

(To be clear, **I'm not saying that investing in commodities is right for everyone**, just like investing in individual stocks or bonds is not right for everyone. You should talk to an investment or retirement advisor to learn what's best for you and your long-term goals.)

**Comment by Carlgo11** [comment]
Hmm 🤔 the more you know ⭐️

Alright I have no objections then.

**Review by jamcat22 — APPROVED** [review]

**Pull request merged**
