### PR TITLE
Update US Mobile

### PR DESCRIPTION
**Pull request by lucschober**

### CODE REVIEW

**Review by hkamran80 — COMMENTED** [review]
Could you please attach some screenshots of the 2FA options menu? I see email and SMS, but not TOTP. Please blur or crop out any personal or sensitive information.

**Comment by lucschober** [comment]
Sure thing. It's _very_ new. I don't see an official announcement yet. The docs also haven't been updated, but it's there.

Edit: It's confirmed in mobile release notes for [Android](https://play.google.com/store/apps/details?id=com.usmobile.dashboard) and [iOS](https://apps.apple.com/us/app/us-mobile/id1460013401)

usm-2fa

**Comment by hkamran80** [comment]
Perfect, thank you!

**Review by hkamran80 — APPROVED** [review]

**Comment by hkamran80** [comment]
Thank you! Your contribution will be visible in around 10 minutes, although it may take longer due to [server and browser caching](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Caching).

**Pull request merged**
