### PR TITLE
Updating porkbun domains software field

### PR DESCRIPTION
**Pull request by adnrs96**
This PR adds the missing software information as discussed in the comments of PR #2121.

### CODE REVIEW

**Comment by Jawshy** [comment]
Thanks, @adnrs96.

**Comment by adnrs96** [comment]
@Jawshy Welcome.
I wanted to ask a question. I observed hardware and sms fields in the yaml file for other websites.What are they for? Like companies providing hosting will have the hardware field as yes?

**Comment by Jawshy** [comment]
The purpose of those fields are described [here](https://github.com/2factorauth/twofactorauth/wiki/FAQ_Categories). I hope that answers your question.

**Comment by Jawshy** [comment]
That wiki page appears to be out-of-date as it is missing the `email` field which is used for electronic mail based authentication.

**Comment by adnrs96** [comment]
Yeah it did answer my question. Thanks.

**Pull request merged**
