### PR TITLE
Add Greenhost

### PR DESCRIPTION
**Pull request by mrtndwrd**
Greenhost is a shared webhosting and cloud hosting provider that offers 2FA using TOTP tokens to log into their hosting platform. 

Source: https://greenhost.net/2016/03/01/spring-news/

### CODE REVIEW

**Review by Jawshy — COMMENTED** [review]
Do you know if Greenhost has any documentation about their implementation of two-factor authentication?

**Comment by mrtndwrd** [comment]
What kind of documentation are you looking for? As far as I know that post I linked is the only thing about it on the website.

**Comment by Jawshy** [comment]
A help article about how to enable two-factor authentication would be a good example of documentation.

**Comment by mrtndwrd** [comment]
No, that's not currently available. It's explained on the page where you can configure it though.

**Comment by Jawshy** [comment]
No worries. I used the post you linked as the `doc`. I also committed a fix for the incorrect YAML field, and resized the image to comply with the image dimension and size requirements. 

Thanks for the pull request, @mrtndwrd.

**Comment by mrtndwrd** [comment]
Thanks! So now we wait for another person to approve the review or something?

**Review by mxxcon — DISMISSED** [review]

**Comment by mrtndwrd** [comment]
Hello all, does anything need to happen before this can be merged?

**Comment by Jawshy** [comment]
Hi, @mrtndwrd. Thanks for the bump. I was thinking that Greenhost would be better suited under [hosting/VPS](https://twofactorauth.org/#hosting). What do other people think?

**Comment by mrtndwrd** [comment]
Oh, that makes total sense! I missed that category

[Edit by @jamcat22: Cleaned quoted email.]

**Comment by jamcat22** [comment]
Are we moving this to the `Hosting/VPS` category?

**Review by mxxcon — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
