### PR TITLE
Adding Wealthfront

### PR DESCRIPTION
**Pull request by gregschwartz**
`ruby verify.rb` shows no errors, and testing it looks right.

### CODE REVIEW

**Comment by mxxcon** [comment]
should it be under `banking`, `finance` or `investing`? :confused:

**Comment by gregschwartz** [comment]
Hmm. Actually you're right, it should be under investing. (Looks like
you're using "finance" more for aggregation than individual services. And I
don't think it's banking; you cannot, for example, write checks from
there.)

**Comment by gregschwartz** [comment]
Updated.

**Comment by jdavis** [comment]
Yup, the investing section is a better fit. This looks good to me even though the icon is 34x34 instead of 32x32 :smile:

**Comment by gregschwartz** [comment]
Whoops! I must have made a typo when I resized it. 

Thanks!

**Pull request merged**
