### PR TITLE
Add Aha! to Developer

### PR DESCRIPTION
**Pull request by dsoegijono**
[Aha!](http://aha.io) is a roadmapping software, a project management tool. Thought it fits better under Developer. Or should it be moved elsewhere?

### CODE REVIEW

**Comment by jdavis** [comment]
Re-doing @jamcat22's #454, eh I see? :wink: And yes, Developer looks good.

**Comment by jamcat22** [comment]
@jdavis I totally forgot about that. Thanks for doing that @dsoegijono!

**Comment by dsoegijono** [comment]
@jdavis Oops! I actually didn't see @jamcat22's pull request! Seems that I missed a few methods for Aha! Should I create a new branch to fix this?

**Comment by jdavis** [comment]
Yup, a new PR will make it easy to update the methods.

**Pull request merged**
