### PR TITLE
add note about 401k.fidelity.com/NetBenefits not honoring 2FA.

### PR DESCRIPTION
**Pull request by jsled**

### CODE REVIEW

**Comment by mxxcon** [comment]
@jsled do you have background on that info?

**Comment by jsled** [comment]
Just personal experience from this evening, which some cursory googling shows others experience as well.  I sent a quick toot to @Fidelity on twitter, but might follow up more formally if they don't respond.

**Comment by mxxcon** [comment]
Yes, it would be nice to make sure if it's an oversight on their end to correct it.

**Comment by w3ua** [comment]
They are working on this. Can't disclose any more details ;) You just can make an educated guess what technology they are evaluating. Please be patient.

**Comment by jsled** [comment]
Thanks for the note @w3ua . Just for completeness, I'll link to my twitter response / inquiry, which has had no followup: https://twitter.com/Fidelity/status/507185359391047680

**Comment by jdavis** [comment]
I just got an email about this from another person that uses Fidelity and they also mention that Fidelity 2FA isn't available for 401K plans. Their 2FA is only available for their investment accounts. I'm going to merge this and then update it.

**Pull request merged**
