### PR TITLE
Add Protectimus

### PR DESCRIPTION
**Pull request by nickfor**
Hi, I just added a new provider to the list - Protectimus (https://www.protectimus.com). Provider supports phone, sms, hardware, software and email.

Thank you in advance

### CODE REVIEW

**Comment by Carlgo11** [comment]
@nickfor you need to add a 32x32px logo. you also need to remove `tfa: yes` as that's not needed for providers.

#How2YAML

**Comment by smholloway** [comment]
Please fix the spacing so this PR does not break the build. I believe the `name` line is the offender.

Looking at [Protectimus Solutions](https://www.protectimus.com/solutions) You should have `hardware`, `software`, `sms`, and `email`. I do not see that Protectimus supports `phone` (phone call/interactive voice response); please omit `phone` or change the value to `No`. Or change `phone` to `sms` because Protectimus does seem to support SMS.

**Comment by nickfor** [comment]
protectimus

**Comment by Carlgo11** [comment]
@nickfor you need to add it to the branch. Use git on your workstation to do this

**Comment by nickfor** [comment]
Carlgo11, I have added the logo to the branch and made all necessary changes. Hope everything is OK now.

**Comment by Carlgo11** [comment]
@jdavis could you run Travis again? It seems to have failed to run this time.

**Comment by nickfor** [comment]
@jdavis could you please run Travis again? :)

@Carlgo11 Anything else I need to add/change?

**Comment by jdavis** [comment]
Sorry for the delay! I just reran it!

**Comment by nickfor** [comment]
Thanks, jdavis! Any actions required from my side? What next?

**Comment by Carlgo11** [comment]
@nickfor I just marked your pull request as `looks-good`. That's the first of two verifications by a collaborator in order for your pull request to be accepted. Once it's been accepted it will take a few days (might up to a week) for your changes to be displayed on the actual page.

Right now you just have to wait for it to be accepted and merged.

Thank you for contributing to our project. It helps a lot!

//@carlgo11

**Comment by mxxcon** [comment]
@nickfor are you fine with the attached logo or would you rather use this favicon from your website? favicon

**Comment by nickfor** [comment]
Great!
@mxxcon favicon looks better. We can use it instead of the attached logo. Thanks

**Comment by nickfor** [comment]
I don’t want to be seen as a killjoy but when can I approx expect to see my changes on https://twofactorauth.org/providers/ ? :)

**Comment by mxxcon** [comment]
@nickfor we were waiting for you to update the icon...

**Comment by Carlgo11** [comment]
Hi @nickfor,

Your PR have been accepted and merged. It will take a few days before the live site shows your site since the owner, Josh, has to manually update the site.
Please have patience, we're all volunteers and do this in our spare time.

Thank you for your contribution. All contributions helps a lot! :cake:

//@Carlgo11

**Pull request merged**
