### PR TITLE
Added Elder Scrolls Online to the Gaming Section

### PR DESCRIPTION
**Pull request by tazinator**
Added information about Elder Scrolls Online for the Gaming section.

### CODE REVIEW

**Comment by mxxcon** [comment]
That doc link says they don't have tfa...?

**Comment by tazinator** [comment]
It works like steam does. Sends an email on unrecognized devices with a
code. They need to be a bit more detailed on that doc.

**Comment by tazinator** [comment]
At the moment I am trying to get them to update their page with more
details but its a slow going process. However I have enclosed a screenshot
of the process at work if proof is needed before you guys accept the update.

**Comment by jdavis** [comment]
I don't see a screenshot =]

If that page were to be updated then that'd be enough. Or since they don't have documentation for it, you can write a note like what we did for Fidelity and use that as the `doc` link:  https://github.com/jdavis/twofactorauth/tree/master/notes

**Comment by tazinator** [comment]
Odd, wonder if the Github redirect doesn't parse larger attachments.

Here is the link to it instead

https://docs.google.com/file/d/0B-hKQSYzBk7qR3dnNEZ2cERNUEU/edit?usp=docslist_api

I'll take a look at the note you referenced when I get home today if you
would rather me do it that way as well. Github isn't playing well on the
phone at the moment so I can't see it clearly heh.

**Comment by jdavis** [comment]
Cool, thanks @tazinator.

**Comment by jdavis** [comment]
Oh, and it looks like I don't have permission to see that attachment. If it is an image, just drag and drop it into the comment box once you have access on a laptop/desktop.

**Comment by tazinator** [comment]
Urgh, tech is just not my friend today it seems.

Okay, this link to it works, tested it on Tor.

https://drive.google.com/file/d/0B-hKQSYzBk7qR3dnNEZ2cERNUEU/edit?usp=sharing

Sorry about that, I thought that folder was set to "Anyone with link"
permissions but apparently not and the GDrive app doesnt allow for easy
permission changes.

**Comment by jdavis** [comment]
Cool.

Do you plan on making a note for it?

**Comment by tazinator** [comment]
Yea I'll do that tonight at some point. This way it puts down any confusion.

**Comment by jdavis** [comment]
:+1:

**Comment by tazinator** [comment]
Should be good to go now. Added the note page and pointed the doc location to it. Let me know if you'd prefer anything else changed/added.

**Comment by jdavis** [comment]
Awesome, looks good, @tazinator.

**Comment by tazinator** [comment]
Many thanks. Keeping an eye out for any others I can add later.

**Comment by jdavis** [comment]
Great :+1:

**Pull request merged**
