### PR TITLE
Add Watchman Monitoring

### PR DESCRIPTION
**Pull request by YesThatAllen**
Lists Watchman Monitoring, a tool used by IT Professionals to discover issues on the computers they care about.

### CODE REVIEW

**Comment by Carlgo11** [comment]
Thanks for the PR @YesThatAllen! :smiley: 

What do you think about the `developer` category? Maybe that fits Watchman better?
And we only use the exceptions tag on special occasions when TFA isn't available for everyone. Please remove that tag.

**Comment by Jawshy** [comment]
~~@YesThatAllen, would you also like to add the [company's support email](https://www.watchmanmonitoring.com/contact/)?~~ 

``` ruby
      email_address: support@watchmanmonitoring.com
```

**Comment by Jawshy** [comment]
@YesThatAllen, my apologises. `email_address` is not required when `tfa` is `Yes`. Please revert and sorry for the trouble.

**Comment by YesThatAllen** [comment]
Noted, and the PR is updated. Thanks!

As for Category.. I'd looked at `developer` (and all the rest) before settling on `other`.
There are a number of other sites in the Other category which could be put in to an "IT Professional" category, I'm not sure where y'all are at with expanding categories, but I figure that's for a separate issue.

**Comment by YesThatAllen** [comment]
> use the exceptions tag on special occasions when TFA isn't available for everyone

I'd been following usage in `Apple iCloud` and `RepairShopr`, which list limitations on how 2fa works on those sites.

**Comment by stephengroat** [comment]
I'm not trying to be annoying but this site (https://www.domaintally.com/www/watchmanmonitoring.com) is ranking lower on Alexa (1,340,460) than #2050. I don't disagree that maybe this site should be listed above liftopia, but a discussion or policy should be had/made about it

**Review by Carlgo11 — APPROVED** [review]

**Review by stephengroat — APPROVED** [review]

**Pull request merged**
