### PR TITLE
Add Nextcloud

### PR DESCRIPTION
**Pull request by rugk**
Same as https://github.com/Nitrokey/dongleauth/pull/167

### CODE REVIEW

**Comment by Carlgo11** [comment]
@rugk we don't use SVG files here. Only PNG files. See our [guidelines](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) for more information.

**Comment by rugk** [comment]
Yeah, no problem, but why do you close the PR, because of that? That's totally unnecessary and I've already adjusted it.
So here is the new PR: https://github.com/2factorauth/twofactorauth/pull/3547

**Comment by Carlgo11** [comment]
No, I closed the PR because it used a SVG instead of PNG and it’s a self hosted service. We don’t list self hosted sites/services.

**Comment by rugk** [comment]
How senseless…

**Comment by mxxcon** [comment]
@rugk It's not senseless. It's a long-standing problem that nobody seems to be willing to address but only complain about. It's been discussed multiple times in the past.
If you can come up with a way for us to accurately yet easily represent 2fa status of self-hosted services in all the possible different combinations that can arise from the use of external plugins and custom configurations then we'll be more than happy to list self-hosted apps.

**Pull request closed without merging**
