### PR TITLE
Update ESL

### PR DESCRIPTION
**Pull request by 40504**

### CODE REVIEW

**Review by hkamran80 — CHANGES_REQUESTED** [review]
The tests are failing because the filename is `esl.com.json`, but the domain is `play.eslgaming.com`. Please change the filename and location.

**Comment by 40504** [comment]
@hkamran80 Done ✅

**Comment by hkamran80** [comment]
Could you also move the file to the `p` directory because the domain starts with `play`?

**Comment by 40504** [comment]
@hkamran80  please check it

**Review by hkamran80 — APPROVED** [review]

**Pull request merged**
