### PR TITLE
Add True Key in identity

### PR DESCRIPTION
**Pull request by mtrepanier**

### CODE REVIEW

**Comment by stephengroat** [comment]
Thanks for the pr @mtrepanier. I was thinking that maybe updating the `doc` tag to something more MFA-targeted would helpful. would you be willing to update the url to (https://help.truekey.com/hc/en-us/articles/218580447-How-can-I-add-additional-factors-)?

**Comment by mtrepanier** [comment]
Sure make total sense, will do it

**Comment by mtrepanier** [comment]
@stephengroat corrected the doc url, thanks

**Comment by mtrepanier** [comment]
Thanks for merging my `PR` do you know when it's going to be live?  Thanks

**Comment by Carlgo11** [comment]
@mtrepanier it's live now. It usually takes between a day or two to up to a couple of weeks.
Done manually whenever I have time.

**Pull request merged**
