### PR TITLE
Add FreeDNS [Domains]

### PR DESCRIPTION
**Pull request by Jawshy**
Resolves https://github.com/2factorauth/twofactorauth/issues/1338. 
See also: https://github.com/2factorauth/twofactorauth/issues/1612 Task 1. 
#### Changes:
- Added: [FreeDNS](https://freedns.afraid.org/) under domains. 
  - No 2FA/TFA. The logo used was modified from the [original](http://tinozplace.com/freedns.jpg) to better display at a lower resolution.

### CODE REVIEW

**Comment by Carlgo11** [comment]
So is this PR still a work in progress?

**Comment by Jawshy** [comment]
Yes, as I cannot find documentation for the TFA.

**Comment by Carlgo11** [comment]
I'll close the PR for now then. You can reopen it or make a new one when everything's sorted 😉

**Comment by Jawshy** [comment]
Updated.

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
Can I get a second pair of eyes on this?

**Comment by mxxcon** [comment]
Is that their logo? I can't find any on their website..

**Review by mxxcon — APPROVED** [review]

**Comment by Jawshy** [comment]
> Is that their logo? I can't find any on their website..

When I submitted this pull request they definitely used that logo on their site, but now I cannot find it. Since then they appear to be using a new logo, see [here](https://freedns.afraid.org/pricing/). 

_Goes to make a new PR._

**Pull request merged**
