### PR TITLE
Add CyberGhost FB handle

### PR DESCRIPTION
**Pull request by spazvt**
add Facebook handle for CyberGhost.

-------------------------
Originally, I also added the CrypticVPN.com service provider, originally added by @deadr0ck to fork
https://github.com/acceptbitcoincash/acceptbitcoincash
However, @stephengroat pointed out that crypticvpn.com has very low traffic per alexa.com and therefore is too small to list on the 2FA site. Therefore I have removed it.

### CODE REVIEW

**Review by Carlgo11 — DISMISSED** [review]
Please remove the twitter handle for CrypticVPN.
No, we won't change our script just so that it fits the format of a fork.

**Comment by spazvt** [comment]
ok I'll fix this in early January.

**Review by stephengroat — CHANGES_REQUESTED** [review]
@spazvt could you remove the `CrypticVPN` entry? it's currently ranking ~1.2m on Alexa, too low for us to list right now

**Comment by spazvt** [comment]
review comments fixed. please re-review, @Carlgo11 and @stephengroat.

please squash merge.

**Review by mxxcon — APPROVED** [review]

**Review by stephengroat — APPROVED** [review]

**Pull request merged**
