### PR TITLE
Re-add data.json

### LINKED ISSUE #1520: Programmatic Access
Hello!

In the future, making separate category based .json files accessible, each containing the website data located on [twofactorauth.org](https://twofactorauth.org), might improve programmatic access as well as helping in creating options for users who disable JavaScript.

Such a system could easily be implemented through Jekyll once the new layout has been merged with the `master` branch.
Do you think adding such files to the website would be a welcome enhancement? Could this perhaps be expanded into some form of API without the need for a back-end?

Thankyou,
psgs :palm_tree:

### PR DESCRIPTION
**Pull request by Carlgo11**
data.json was removed in #1575.
This PR adds it again, now edited to work with our new website layout.
This PR also fixes #1520.

### CODE REVIEW

**Comment by jamcat22** [comment]
What about if the site has a `doc` or `status` link?

**Comment by jamcat22** [comment]
Oh! Forgot to ask about `exception` tags.

**Comment by Carlgo11** [comment]
@jamcat22 I've tried to list exceptions but it seems really really hard to change to format to json for that array. I can either just output the data of the exceptions array or just skip the exceptions tag.
Which one do you prefer?

If I outputed the raw data it would look like this:
`exceptions: "{"text"=>"SMS-capable phone required."}",`
If you choose to list the exception's value as raw text then we'd have to replace the double quotation marks with single quotations.
dr. evil double quotation

**Comment by Carlgo11** [comment]
Fixed it because I'm fabulous like that :information_desk_person:

**Comment by Carlgo11** [comment]
The only thing I haven't done is to refactor the code.
I didn't find any good tool for that supporting jekyll's liquid language. Maybe someone else knows a good tool and could do it? *cough\* @psgs *cough*
If so please make a PR to my patch-data.json branch. If not then, well it works so IMHO this PR is good to go.

**Comment by Carlgo11** [comment]
@psgs I see that you added the `pending` label again. Can I take that as that you'll try and push a PR to my fork with a reformatted version of this script?

**Comment by fpigerre** [comment]
Hello @Carlgo11,
Yes, I am taking a look at the script and will likely open a pull request within the next few days.

**Comment by fpigerre** [comment]
I have looked at the code and played around with it a little, however, I don't think we will be able to effectively refactor the code without somehow generating the JSON data using a script (this could be done either at runtime or using a webhook that is triggered when a commit is pushed to `master` or `gh-pages`).
Since this is the case, I think we should merge this pull request.

**Comment by Carlgo11** [comment]
So `looks-good`?

**Comment by Carlgo11** [comment]
or just that

**Comment by fpigerre** [comment]
Yes, this pull request `looks-good`.

**Comment by Carlgo11** [comment]
:laughing:

**Comment by fpigerre** [comment]
:stuck_out_tongue_closed_eyes:

**Pull request merged**
