### PR TITLE
Add Threat X

### PR DESCRIPTION
**Pull request by stusmall**

### CODE REVIEW

**Comment by mxxcon** [comment]
Is there docs link that describe how to enable it?

**Comment by stusmall** [comment]
Unfortunately not on our public site that we could link to.

**Comment by Carlgo11** [comment]
Hello @stusmall,
could you provide us with proof that the site supports two factor authentication?

It for example be screenshots (**with personal information and QR codes obfuscated**) 

Thanks!
//Carl

**Comment by stusmall** [comment]
No problem.  

2fa

**Comment by Carlgo11** [comment]
Great! Thanks 😄

**Review by Carlgo11 — APPROVED** [review]

**Comment by stusmall** [comment]
Thanks for the quick review on this and also huge thanks for running this project.

**Review by jamcat22 — APPROVED** [review]

**Pull request merged**
