### PR TITLE
Add Joomla

### PR DESCRIPTION
**Pull request by itxchandan**

### CODE REVIEW

**Comment by thibaultmol** [comment]
@chandanndeep I think it's good, only need to remove joomla.png from the domains folder and Travis will give a green light 👍

**Comment by mxxcon** [comment]
Thank you for this PR, however at this point in time we do not list self-hosted applications.

**Comment by kilasuit** [comment]
I think that's a seriously silly **IDEA**

This site should enable people to see both SaaS and Self hosted applications that allow **ANY** form of MFA to be enabled - please rethink this @mxxcon

**Comment by mxxcon** [comment]
@kilasuit We do list saas. We have salesforce and other products there.
I addressed your other point in the issue you opened.

**Comment by itxchandan** [comment]
I removed the logo from the domains folder. Waiting from your side

**Pull request closed without merging**
