### PR TITLE
moved music to entertainment

### PR DESCRIPTION
**Pull request by Carlgo11**
So sorry but I derped last time. Had to make a new pr. This on the other hand shouldn't have any extra unwanted things

### CODE REVIEW

**Comment by mxxcon** [comment]
I swear I'm not picking on you. But youtube logo is 32x25 :smile:

**Comment by Carlgo11** [comment]
@mxxcon I don't even... Thank you for pointing that out ;)

You sir deserve cake :cake:

**Comment by Carlgo11** [comment]
(The Travis CI fails because of a hardcoded check in the img/music dir)

**Comment by jdavis** [comment]
You'll need to update the main.yml file here to fix the Travis failure: https://github.com/Carlgo11/twofactorauth/blob/8a48eaf6a9fa8df13af67387c5682414a873ad48/_data/main.yml#L62-L64

Change it to Entertainment as well as pick [an icon](http://semantic-ui.com/elements/icon.html) for it that correlates with it. Be sure to alphabetize it as well =]

**Comment by Carlgo11** [comment]
@jdavis "YouTube image not found." I can't see that there's anything wrong with the youtube part :/
https://travis-ci.org/jdavis/twofactorauth/builds/31092669#L149

**Comment by jdavis** [comment]
Well, now the failure is due to this commit because you fixed the previous issue: https://github.com/Carlgo11/twofactorauth/commit/eabb40e7e97e2a868764fad6f5097fb85e1423a4

The Yaml has the file as being `youtube.png` but the filename is actually `youtube.PNG`. I suspect you will have the same issues with Twitch based off of this commit: https://github.com/Carlgo11/twofactorauth/commit/8a48eaf6a9fa8df13af67387c5682414a873ad48

I'd move both files to lowercase to fix this as all of the other extensions are lowercase as well.

Cheers!

**Comment by Carlgo11** [comment]
I suggest an ice cream party after this :ice_cream:

**Comment by jdavis** [comment]
Cool, at least there are no errors this time =] I'm going to have to wait until I get home to double check things and merge it then.

**Comment by jdavis** [comment]
Everything looks good locally, I'm merging this =]

**Pull request merged**
