### PR TITLE
Add 007names

### LINKED ISSUE #1624: 007names.com supports software token 2FA
Can use Google Authenticator or any other authenticator app

### PR DESCRIPTION
**Pull request by stephengroat**
Closes #1624

### CODE REVIEW

**Comment by stephengroat** [comment]
Updated png with 52% compressed

**Comment by fpigerre** [comment]
Thanks for the pull request @stephengroat :smile: 
Would you be able to remove the `www.` from the `www.007names.com` URLs by any chance?

**Comment by stephengroat** [comment]
Sure, but do you want me to? On their [whois records](http://www.whois.com/whois/007names.com), they even list it with the www

**Comment by fpigerre** [comment]
Oh. In that case, this pull request seems ready to be merged :smiley:

**Pull request merged**
