### PR TITLE
Add CloudConvert

### PR DESCRIPTION
**Pull request by josiasmontag**
[CloudConvert](https://cloudconvert.com) is a popular online file conversion service (Alexa Rank [~5000](https://www.alexa.com/siteinfo/cloudconvert.com)).

### CODE REVIEW

**Comment by Carlgo11** [comment]
Hi @josiasmontag,
please add a documentation link as described in [CONTRIBUTING.md#New Sites](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#adding-a-site-that-supports-tfa)

**Comment by josiasmontag** [comment]
CloudConvert does not have any public docs about 2FA. It is a menu in the security settings and explained there. 

Screenshot at Mar 19 11-04-04

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Thanks for the screenshot. 👍 

I don't think "Cloud Computing" is a fitting category for CloudConvert.
Cloud Computing is intended for services like AWS, Microsoft Azure and DigitalOcean. Virtual serves and similar.

CloudConvert seems to be more of a productivity tool. Since we don't have such a category at the moment I think the "Other" category would be the best fit.

**Comment by josiasmontag** [comment]
I have moved it to the "Other" category.

**Review by Carlgo11 — APPROVED** [review]
Great, thanks! 😄

**Review by jtagcat — APPROVED** [review]

**Review by kmpoppe — APPROVED** [review]

**Pull request merged**
