### PR TITLE
Update urls from http to https

### PR DESCRIPTION
**Pull request by conorgil**
I am looking through the current list of sites and doing some cleanup. This PR updates sites from HTTP to HTTPS (if they support it).

I ran `bundle exec rake` locally and everything passed.

Does the LinkChecker just use a regex to check format, or does it actually make requests? Seemed too quick for the latter, but I haven't dug into it yet to understand what is going on under the hood.

### CODE REVIEW

**Review by mxxcon — COMMENTED** [review]
linkchecker actually makes requests to sites. that's why in travis log you can see various errors.

how much verification did you do with this?
while many sites do support https, some don't have proper sites, have different content or worse yet redirect back to http.

**Comment by conorgil** [comment]
@mxxcon great to hear that it actually makes requests! I'll have to dig into the details to understand how that is all setup (I'm not a ruby guy).

I actually made all of the changes manually after verifying that the HTTPS URLs worked as expected. I was thinking about writing a script to do it, but got bored and just did it while watching a movie instead :) I did notice a bunch of sites that redirect from HTTPS back to HTTP. Bonkers. I did **not** update those URLs and left them as HTTP.

It looks like the Travis checks all passed. Were you just pointing out that I can see errors in the log if there were errors, or that there are errors somewhere and I missed them?

**Comment by conorgil** [comment]
related to #2914

**Comment by fpigerre** [comment]
Hello @conorgil,

Although the primary Travis CI check passed fine, the second check that we run actually failed whilst checking a number of sites. This second check is the one that verifies all the links that aren't local (don't belong to the twofactorauth.org domain). Although this check failed, we actually allow it to fail within the Travis CI parameters as websites go down all the time, and it would be annoying if, for every pull request made, all sites listed were required to be online and working. That's why the check doesn't show up in the "All checks have passed" box on GitHub.

If you take a look at the [builds page](https://travis-ci.org/2factorauth/twofactorauth/builds/361973101) for this pull request, you'll notice two builds that were completed. The log for the second check can be found [here](https://travis-ci.org/2factorauth/twofactorauth/jobs/361973107).

Thankyou very much for all the effort you've put in here,
psgs 🌴

**Comment by conorgil** [comment]
@psgs oh, ok. Thanks for explaining! I am taking a look at each error and making issues for relevant things as I go.

I am noticing that @stephengroat just closed two of those issues as already fixed. I gotta say I kinda feel like I'm wasting my time a bit here, gents. If some of those links are already fixed, then why aren't they merged and live?

I'll finish going through each link to help clean things up, but I'll also think on better ways to automate this. It is pretty painful.

**Comment by stephengroat** [comment]
@conorgil sorry for closing! issue are great, but the duplication is a pain to deal with. if you make an issue, can you check that there's not already an outstanding issue or PR first? that way we can avoid the maintenance overhead of closing dupes

as far as the link checker used in `html-proofer` goes, it's not 100% (at all). different thing can throw it off (IP block lists, Cloudflare (and other DDOS prevention tools), user agent checks, etc.). i think it'd be great to automate it too, but right now, there's not enough consistency in the results to allow it

**Comment by conorgil** [comment]
@stephengroat No no! Don't apologize for closing. I totally get that duplication is just useless noise. Since I saw you close some, I started checking for existing issues to avoid dupes.

== Start rant ==
My frustration is that I spent all that time manually verifying and updating 100+ links from HTTP to HTTPS and the feedback I got was "go check this list of errors. Stuff broke" (to be fair, @psgs said it is an incredibly nice way). I really want to get involved in this project and I have no problem whatsoever fixing stuff to get clean PRs. However, I hope you can see how with zero context and being new to the project I could have expected that all of those errors in there were caused by my changes. So, I start looking through those URLs, but quickly realize that the list of errors is almost **entirely** composed of URLs that I didn't change. So, those errors were already known. I am almost done with the list and have only found a single URL that I changed in the list of errors. It just doesn't really seem like a good use of my time if the list of errors isn't maintained below some set threshold.

I totally hear you on the inconsistency with DDOS and other junk like that, but there has to be a better way to main this than by hand. Manual does not work. Example: #2615 has been open since July 2017. That is...a long time.
== End rant ==

I am going to finish this list and then actually work to get these broken URLs fixed, merged, and live so that the error list can be as small as possible. That will make this more manageable until it can be automated somehow.

**Comment by conorgil** [comment]
## Sites that showed up in the errors, but were not changed in my PR:

1. http://www.dell.com
   1. got a 403 Forbidden. That is just weird
2. https://bittrex.com
   1. got a 503 Service Unavailable. Seems to work fine for me when I try it now. Maybe a glitch.
3. https://coinify.com/merchants
   1. gets a 404, but it looks like they made their 404 page their homepage. Weird and clever
   2. Probably makes sense to update this URL to https://coinify.com
4. https://docs.connectwise.com/ConnectWise_Control_Documentation/Get_started/Administration_page/Security_page/Enable_two-factor_authentication_for_host_accounts
   1. Does some weird redirect loop to pick up an "authtoken". Yea, real secure... Anyways, it redirects 4 times and the current limit is set to 3.
5. https://docs.payza.com/docs/personal-manual-advanced-security#section-how-do-i-set-up-2-factor-authentication
   1. got a timeout
6. https://facebook.com/hellowallet/
   1. This facebook group/page/whatever does not exist. Issue created #3107
7. https://help.ea.com/en-us/help/account/origin-login-verification-information/
   1. honestly, not sure on this one
8. https://help.mail.ru/enmail-help/settings/2auth
   1. gets a 404. Issue created #3108
9. https://help.xero.com/nz/MyXero_Two-Step_About
   1. got a 403 in the error log, but works fine for me now
10. https://huit.harvard.edu/twostep
    1. Not sure on this one. Works fine in Chrome, but gets an SSL cert error on CLI using httpie
11. https://jet.com
    1. got a 403, but works fine for me in Chrome and CLI httpie
12. https://kb.builtwith.com/account-management/how-to-enable-2fa-on-builtwith/
    1. got a response code 0. Never seen that before. This works for me in Chrome, but SSL error on CLI using httpie
13. https://knowledgelayer.softlayer.com/procedure/configure-portal-account-one-time-password-access-manage
    1. got a 403. Issue created #3110
14. https://my.gov.au
    1. hit redirect limit, but it only redirects 3 times. Not sure whats up there
15. https://sl.se/
    1. response code of 0. No clue. SSL cert issues I think
16. https://support.bittrex.com/hc/en-us/articles/115000198612-How-do-I-troubleshoot-backup-remove-disable-enable-Two-Factor-Authentication-2FA-
    1. got a 503, but works fine for me now
17. https://www.addiko.hr/sites/addiko.hr/files/content/addiko_bank_uputa_za_koristenje_tokena_mtokena.pdf
    1. 404s
18. https://www.aircanada.com/
    1. Got a 403, but works fine for me
19. https://www.ankama.com
    1. Hit redirect limit, but only appears to redirect once. Dunno whats up
20. https://www.costco.com
    1. Got a timeout, but works fine for me
21. https://www.csn.se/bas/vanligaFragor.do
    1. Cert error in Travis log. I also get a cert error using httpie, but it loads fine in Chrome
22. https://www.domaintools.com/
    1. Got a timeout, but works fine for me
23. https://www.easyjet.com
    1. Got a 403, but works fine for me in Chrome and httpie
24. https://www.immobilienscout24.de
    1. Got a timeout, but works fine for me
25. https://www.litebit.eu/
    1. Got a 503 in Travis error logs. I also get a 503 from httpie, but it works fine in Chrome. They are playing user-agent games
26. https://www.lowes.com
    1. Got a 403, but works fine for me in Chrome and httpie
27. https://www.neteller.com/
    1. hit redirect limit. Redirects 5 times
28. https://www.payza.com/
    1. Got a timeout. I also get a timeout. Broken link. Issue created 
29. https://www.rackspace.com/knowledge_center/article/myrackspace-two-factor-authentication
    1. 404s. Issue created #3113
30. https://www.rakuten.com/
    1. Got a timeout, but works for me
31. https://www.thebay.com
    1. Got a 403, but works fine for me in Chrome and httpie

## Sites that showed up in the errors that I did change in my PR

1. https://na.square-enix.com/
   1. hit redirect limit. Redirects 4 times
2. https://www.macys.com/
   1. Got a timeout, but works fine for me in both Chrome and httpie
3. https://www.wayfair.com
   1. Got a 403, but works fine for me in Chrome and httpie

**Comment by mxxcon** [comment]
@conorgil I think you might have misinterpreted what @psgs was saying. He was not saying "go check that list and fix it". He was simply giving more insights into how our travis-ci is setup to check links.

I don't know if there's an automated way to fix those things. Sites change their structure with some regularity. How can you automatically know what a new URL of an article is?
Sometimes they have the foresight to include 301 redirects to new articles, but often they don't bother or simply can't.
It's a manual process which maintainers neglected for longer than we should've. 😅

**Comment by conorgil** [comment]
Perhaps I did misinterpret. Well, its all done anyways. No harm, no foul.

Let me know what (if anything) you'd like to get fixed in this PR before we can merge it and get it live.

**Review by mxxcon — APPROVED** [review]

**Review by fpigerre — APPROVED** [review]

**Pull request merged**
