### PR TITLE
adding bitium to identity section

### PR DESCRIPTION
**Pull request by andrewarrow**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Change the url to https

**Comment by andrewarrow** [comment]
@Carlgo11 hi I changed the url to https and in the docs we say at the bottom:

"Hardware Tokens
Bitium also integrates with various hardware authenticators ( RSA-Token, YubiKey, RFC 2289, RFC 4426, OATH HOTP, OATH TOTP, Mobile Phones, etc.) to provide convenient, secure, token-based 2FA. Please contact support for more information."

is that ok?  thanks!

**Comment by Carlgo11** [comment]
Looks okay to me

**Comment by jdavis** [comment]
Cool, nice job @Carlgo11 and @andrewarrow.

**Pull request merged**
