### PR TITLE
Add Wykop

### PR DESCRIPTION
**Pull request by NullPiotrException**
[Wykop.pl](https://www.wykop.pl) is a Polish Reddit so I also added it to Social.
Logo is a scaled version from [their website](https://www.wykop.pl/dla-programistow) where they added it specifically for devs to use (so no copyright claims).
They don't have 2FA documented anywhere, unfortunately.
Used it and it works.

[Alexa stats](https://www.alexa.com/siteinfo/wykop.pl)

### CODE REVIEW

**Review by stephengroat — DISMISSED** [review]
thanks for the pr @einsteinsfool!

**Comment by stephengroat** [comment]
@einsteinsfool thanks for the additional info, but we prefer 1 site to be modified per a pr.

could you split your additional work off onto a separate branch for us?

**Comment by NullPiotrException** [comment]
Sure. I didn't know if I make new commits, it would update the PR. Sorry. Wanted to make another PR. I'll try to fix that.

**Comment by NullPiotrException** [comment]
Done. Can you review again, @stephengroat ? Sorry again.

Also, can I somehow make 2 separate PRs or do I have to wait for one to get merged before I make another?

**Comment by RichJeanes** [comment]
You can create a branch for each change you want to make on your fork of the repo, then make a PR for each of those instead of working directly on the `master` branch.

**Comment by NullPiotrException** [comment]
Thanks.
But I guess now that I already added something to master I have to wait for it to be merged. Or close this PR and make 2 separate branches for each PR. Otherwise, if I make a new branch now it will also contain this PR because it's on my master.
So I guess I'll just wait for this to be merged and next time I'll make new branches.

**Comment by stephengroat** [comment]
@einsteinsfool if you want to make a new branch from `twofactorauth`'s master, try

```
git clone https://github.com/2factorauth/twofactorauth
cd twofactorauth
git push https://github.com/einsteinsfool/twofactorauth master:new-branch-name
```

**Comment by NullPiotrException** [comment]
@stephengroat Did it, thanks for teaching me!

**Comment by stephengroat** [comment]
@einsteinsfool np

**Review by pawelci — APPROVED** [review]

**Comment by conorgil** [comment]
Bummer there are no docs. Aside from that, looks good to me. @stephengroat @RichJeanes good to merge?

**Review by Carlgo11 — APPROVED** [review]

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
