### PR TITLE
Add Hook Mobile provider info

### PR DESCRIPTION
**Pull request by ell20**

### CODE REVIEW

**Comment by mxxcon** [comment]
To be consistent, please make your logo 32x32(right now it's 32x18). You can add transparent pixels to empty areas.

**Comment by ell20** [comment]
I've changed the icon size. Should be 32x32 now.

**Comment by mxxcon** [comment]
@ell20 can you provide a bit more description on what your service does? I see there's PINHook  product, but I don't see much documentation on your site beyond 1 paragraph.

**Comment by jamcat22** [comment]
Do we want to merge this?

**Comment by mxxcon** [comment]
Without more info I don't feel comfortable merging this. Seems like an incomplete product.

**Pull request closed without merging**
