### PR TITLE
Add carriers category + add AT&T

### PR DESCRIPTION
**Pull request by Carlgo11**
Had to add some website to the category so I added AT&T.
inb4 carriers spam.

I made this PR at request from @wilsonmar in #723.

### CODE REVIEW

**Comment by jdavis** [comment]
The only thing I wonder about is adding another category. Would Communication work for the carriers?

**Comment by Carlgo11** [comment]
@jdavis bring that up in #723 instead.

**Comment by jdavis** [comment]
@Carlgo11 I did https://github.com/jdavis/twofactorauth/issues/723#issuecomment-54007619

:smile:

**Comment by mxxcon** [comment]
Maybe instead of communication, `utilities`? Then we can add cable, internet, electric, etc..

**Comment by Carlgo11** [comment]
meh I'm closing this pr. I don't see the necessarity of tfa for carriers.

**Comment by wilsonmar** [comment]
I beg to differ about the necessity of TFA for carriers.
Google Amazon and others use mobile phones for TFA.
Yet, ATT doesn't even allow speciali characters in their 8 character
passwords.
This means my cell account can get hacked easily.

**Comment by jamcat22** [comment]
Agree with @wilsonmar on this one. Carriers hold a lot of data. If someone had access to your ATT or Verizon accounts, they could forward voicemails, change login data, get bill pay details, see texts (depending on carrier), see calls and times, change your plan, change your call in PIN code (for talking to a customer service person), and even cancel your account (locking you out of almost everything if you are using phone or text 2FA).

Remember the CloudFlare hack? http://cl.ly/image/3g1X141s2s3J2G2Z0e0O/o and http://blog.cloudflare.com/the-four-critical-security-flaws-that-resulte/ and http://blog.cloudflare.com/post-mortem-todays-attack-apparent-google-app/

The hacker used social engineering tactics to forward Mathew's voicemails to his phone. This allowed him to reset Mathew's Google password and get around Google two factor authentication.

Maybe if ATT had two factor authentication, the rep would have had to ask for a code and this would have stopped the hacker from logging in online and taking control of his account.

I do not think we need to add another category, but I think we should definitely add these carriers to the communication section.

**Comment by mxxcon** [comment]
I also agree it should be added.
(any comments regarding making it utilities category rather?)

**Comment by dsoegijono** [comment]
@mxxcon Other than carriers, what would be added to utilities?

**Comment by jamcat22** [comment]
@dsoegijono @mxxcon Said, "Maybe instead of communication, utilities? Then we can add cable, internet, electric, etc.." on this comment. https://github.com/jdavis/twofactorauth/pull/761#issuecomment-55281125

**Comment by dsoegijono** [comment]
@jamcat22 @mxxcon Oops, sorry, should have read the thread more thoroughly. I thought Communication was better because it should cover cable, internet, phone. Didn't think about electric though; if electric should be added to the site then I agree with "Utilities" so we don't have too many categories.

**Comment by sif** [comment]
I'm going to vote for inclusion of carriers. For Virgin Mobile, you only need 4-6 number digits to login the account and that's very, very bad.

**Comment by Carlgo11** [comment]
Okay I just pushed this PR to https://github.com/jdavis/twofactorauth/tree/patch-6
I let you guys change the code to your satisfaction. There's currently too many voices for me to feel comfortable making changes in the code. Especially when I don't share the same opinion ;)

Happy code-knocking.

**Comment by mxxcon** [comment]
Should this one be closed in favor of #1024?

**Comment by Carlgo11** [comment]
yes

**Pull request closed without merging**
