### PR TITLE
Added WebFaction and Raiffeisen Bank

### PR DESCRIPTION
**Pull request by iBobik**

### CODE REVIEW

**Comment by mxxcon** [comment]
:+1: @iBobik could you please rename Raiffeisen's image to have a more descriptive filename. No point making it obscure to save a few chars. :smiley:

**Comment by iBobik** [comment]
@mxxcon Done :-)

**Comment by Carlgo11** [comment]
What about changing `raiffeisenbank_cz.png` to `raiffeisenbank.png`

**Comment by iBobik** [comment]
I think this is not good idea, because RB is in many countries, usually technologicaly separated.

**Comment by Carlgo11** [comment]
oh, very well then.

**Pull request merged**
