### PR TITLE
Add MIT

### PR DESCRIPTION
**Pull request by Sunit-Kulkarni**
Adding the world renowned institution also know as MIT

### CODE REVIEW

**Review by mxxcon — CHANGES_REQUESTED** [review]
Logo image must be 32x32

**Comment by Sunit-Kulkarni** [comment]
That should do it.

**Review by mxxcon — APPROVED** [review]

**Review by Carlgo11 — APPROVED** [review]
If I approve MIT will MIT approve me? :wink:

**Comment by Sunit-Kulkarni** [comment]
I'm sure they'll approve you! Just put this on the application :)

**Pull request merged**
