### PR TITLE
Resorted developer entries and added PythonEverywhere service.

### PR DESCRIPTION
**Pull request by mxxcon**

### CODE REVIEW

**Comment by zach-taylor** [comment]
Hi @mxxcon, it looks like it should PythonAnywhere rather than PythonEverywhere, is that right?

**Comment by mxxcon** [comment]
@zach-taylor wow, i'm a dope. :D

**Comment by mxxcon** [comment]
Why did it fail this commit on health.yml, a file that I didn't touch...?

**Comment by mpdavis** [comment]
I believe there was a broken master for a short amount of time causing a few builds to fail.  PR has merge conflicts now, so after you fix them, another build should run and pass.

**Pull request closed without merging**
