### PR TITLE
Add RBCommons.com to the Developer list.

### PR DESCRIPTION
**Pull request by chipx86**
RBCommons supports 2FA through SMS and software tokens, and includes
documentation on getting set up.

### CODE REVIEW

**Comment by RichJeanes** [comment]
I'm going to be picky and ask for three things, if you don't mind.
1) Remove the Twitter handle (only needed to tweet at them if they don't have TFA)
2) Capitalize your `Yes`'s for SMS and software
3) Run the icon through an optimizer like [TinyPNG](https://tinypng.com/)
Please and thank you!

**Comment by chipx86** [comment]
Thanks for the feedback! I appreciate pickiness with changes :) I'll post an update shortly.

I ran the PNG through ImageOptim, but that didn't do nearly as good a job as TinyPNG. Updating to use that one.

**Comment by mxxcon** [comment]
It's not that big of a deal for 32x32, but TinyPNG is a lossy compressor, while ImageOptim is lossless.

**Comment by Carlgo11** [comment]
@mxxcon ImageOptim looks like a mac-only program.

**Comment by mxxcon** [comment]
Carl, yes it is. For Windows PNGSlim/ScriptPNG/FastIO use the same and more tools. The only thing you are missing out is a nice gui. :)

**Comment by mxxcon** [comment]
+looks-good 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- _data/developer.yml @ r1
- img/developer/rbcommons.png @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jdavis/twofactorauth/1153)

**Comment by Carlgo11** [comment]
@mxxcon and for Linux?

**Comment by mxxcon** [comment]
Not as many, but look through http://en.css-ig.net/ he cover some tools that are very likely to be for linux too.

**Comment by chipx86** [comment]
Thanks! :)

**Pull request merged**
