### PR TITLE
Added GoCardless to Payments

### PR DESCRIPTION
**Pull request by SeanHood**
They don't support 2FA :(

### CODE REVIEW

**Comment by jdavis** [comment]
Hey @SeanHood, we're back at PRs. We changed up the site a bit, so if you could adhere to that, we would be able to merge this.

**Comment by SeanHood** [comment]
Okay, will get this updated as with #357

**Comment by jdavis** [comment]
Hmm, it looks like the image isn't working correctly. I even downloaded it but was still unable to view it.

**Comment by SeanHood** [comment]
Re done the images for this and #357

**Comment by jdavis** [comment]
Great. It works now. Sorry for being so picky, @SeanHood.

**Pull request merged**
