### PR TITLE
Add Vanguard Australia

### PR DESCRIPTION
**Pull request by jimmyvanau**

### CODE REVIEW

**Review by Carlgo11 — APPROVED** [review]
Thanks for the pull request @jimmyvanau!
I tried removing the URL tag as it isn't needed in cases where https://{domain} points to the same place as the URL tag; However, it looks like the root domain serves an expired certificate so the URL tag had to be added back.

TL;DR you did everything right and I accidentally broke your pull request at first :sweat_smile:

**Comment by jimmyvanau** [comment]
@Carlgo11 lol I got lucky. Noted for next time. I'll report the expired cert. Cheers

**Comment by phallobst** [comment]
You have added a new, unrelated entry to this PR. Could you open a new PR for "NAB", i.e. from a separate branch?

**Comment by jimmyvanau** [comment]
@phallobst Hmm, sorry I'm not sure what's happening with Ubisoft. Should I close PR and create a new one?

**Comment by phallobst** [comment]
You could either try to `rebase`, or create new PRs here, preferably each with its own branch. Using the `master` branch for PRs is usually not a good idea.

**Comment by Carlgo11** [comment]
I've removed the invalid commits.

**Comment by jimmyvanau** [comment]
Thanks so much @Carlgo11 🙏🏼

**Review by phallobst — APPROVED** [review]

**Pull request merged**
