### PR TITLE
Update Nuget

### PR DESCRIPTION
**Pull request by jamiehowarth0**

### CODE REVIEW

**Comment by Carlgo11** [comment]
@jamiehowarth0 there's no need to create an issue if you're going to create a pull request anyway.

**Comment by phallobst** [comment]
Should we add an exception text here since you need an external account to log in?

**Comment by jamiehowarth0** [comment]
Maybe there should be a way to specify that a site relies on another site's ID scheme for authentication? (e.g. Papercall relies on multiple auth providers without having it's own)

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
Microsoft owned site uses Microsoft account to authenticate. Since it's the only way to authenticate and it isn't a third party I don't see any need to specify the auth system further.

**Review by phallobst — APPROVED** [review]

**Pull request merged**
