### PR TITLE
Add DailyMotion

### PR DESCRIPTION
**Pull request by Nicos18**

### CODE REVIEW

**Comment by stephengroat** [comment]
@Nicos18 how does this apply to the [criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria)?

**Comment by Nicos18** [comment]
@stephengroat I saw that the in the entertainment category there is Vimeo, which is basically the same type of service as Dailymotion

**Comment by stephengroat** [comment]
@Nicos18 i think vimeo was included because it has billing associated with the account. does dailymotion have any billing or other criteria associated with the account.

**Comment by Nicos18** [comment]
@stephengroat I didn't find anything about billings/subscriptions etc.

**Comment by stephengroat** [comment]
@Nicos18 I'm closing this as it doesn't seem to fit the criteria. thanks for all of the other work!

**Pull request closed without merging**
