### PR TITLE
Add Volksbanken Raiffeisenbanken

### PR DESCRIPTION
**Pull request by phallobst**

### CODE REVIEW

**Comment by phallobst** [comment]
What happened during the check here? I see no apparent error. Or is it related to #4165?

**Comment by Rfosu2k2** [comment]
> What happened during the check here? I see no apparent error. Or is it related to #4165?

This is from the error log:
- ./_site/index.html
  *  14318:161: ERROR: htmlParseEntityRef: expecting ';' (line 14318)
  *  5075:161: ERROR: htmlParseEntityRef: expecting ';' (line 5075)
rake aborted!
HTML-Proofer found 2 failures!

**Comment by phallobst** [comment]
Ah, the dreaded HTML entities... I'll fix that.

**Comment by phallobst** [comment]
Re-submitted as #4174

**Pull request closed without merging**
