### PR TITLE
Add Charles Schwab exception

### PR DESCRIPTION
**Pull request by dsoegijono**
For #914. How's the wording?

### CODE REVIEW

**Comment by mxxcon** [comment]
Not remembering what happened in 914, when I read that exception is sounded very strange and out of context. Perhaps expand/elaborate it a bit?

**Comment by Carlgo11** [comment]
How about `Password length limited to 8 characters when for TFA to be available` instead of `Password length limited to 8 characters.`

**Comment by jamcat22** [comment]
But the password length is limited to 8 characters even if you don't use 2FA.

**Comment by Carlgo11** [comment]
Oh okay. Then yeah, it looks good

**Comment by dsoegijono** [comment]
Sorry I was away for the holidays. If @mxxcon doesn't think the note is clear enough, maybe it should be reworded @Carlgo11 @jamcat22 ? Although at the moment, I can't think of what to put without writing a long paragraph of explanation. =/

**Pull request merged**
