### PR TITLE
add t-online

### PR DESCRIPTION
**Pull request by luh2**

### CODE REVIEW

**Comment by Carlgo11** [comment]
Isn't that T-Mobile's logo?

**Comment by luh2** [comment]
As well. Same company at large. Don't quite get all the dependencies, but it's the correct logo.

**Comment by Carlgo11** [comment]
Okay thank you for clearing that out! 😄

**Comment by stephengroat** [comment]
Do we want to add the `lang: de` tag to this as well?

**Review by stephengroat — CHANGES_REQUESTED** [review]
Could you merge with master? Seems like the PR got a bit stale. You can merge through the web UI now!

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
*cough\* @stephengroat

**Review by stephengroat — APPROVED** [review]

**Pull request merged**
