### PR TITLE
Add AirBank

### PR DESCRIPTION
**Pull request by ondrejfuhrer**
Hello guys, adding a Czech bank to the banking list 👍 Thanks for such a great service.

### CODE REVIEW

**Review by mxxcon — DISMISSED** [review]
As you can see travis-ci checks are failing. Either move your entry into banking category or move your logo file into finance directory.

**Comment by ondrejfuhrer** [comment]
@mxxcon Ah, my bad 😊

**Comment by Carlgo11** [comment]
@ondrejfuhrer could you provide any documentation supporting this?

**Comment by ondrejfuhrer** [comment]
Hey @Carlgo11 , I was trying to find any documentation regarding that, but unfortunately I was not able to do so. The only thing I found is regarding transaction confirmation (some articles, etc.) but they don't mention there, that the same approach could be also used to login authentication as well.

Theoretically, I can write to that bank support if they could provide me with anything, but that will take time. 

Is that a requirement to have it in this list?

**Comment by ondrejfuhrer** [comment]
Hey @Carlgo11 , spoke with the support, they actually mention that in this FAQ, is that enough? Should it be in the `doc` parameter?

https://www.airbank.cz/co-vas-nejvic-zajima/jake-bezpecnostni-prvky-u-nas-mame

**Review by Carlgo11 — COMMENTED** [review]
That link you provided looks good. Could you please add it as a `doc: `tag?
Thanks :smiley:

**Comment by ondrejfuhrer** [comment]
@Carlgo11 Added 👍

**Review by Carlgo11 — DISMISSED** [review]

**Review by Carlgo11 — APPROVED** [review]

**Comment by ondrejfuhrer** [comment]
I don't want to be pushy, but is there any reason why this is still waiting to be merged? It's been approved for more then a month.

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
