### PR TITLE
Add unity supporting 2fa (Fixes #2222)

### LINKED ISSUE #2222: Add Unity
They support 2FA via SMS:
https://twitter.com/unity3d/status/806137455955111940
https://support.unity3d.com/hc/en-us/articles/208764976-How-do-I-enable-Two-Factor-Authentication-on-my-account-

### PR DESCRIPTION
**Pull request by TuxCoding**

### CODE REVIEW

**Comment by mxxcon** [comment]
How does this site fit into our criteria? https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria

**Comment by TuxCoding** [comment]
>Any site that deals with money.

You can buy certain packages with personal information. You have access to private analytics, organization management and more.

**Review by stephengroat — APPROVED** [review]
thanks for the pr @games647

**Comment by mxxcon** [comment]
@games647 You can buy certain packages, but does it save your credit card in your account?

**Comment by TuxCoding** [comment]
>@games647 You can buy certain packages, but does it save your credit card in your account?

I don't think so, but it saves billing details
billing

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
