### PR TITLE
Recompress all PNG to save space & change name.com's doc link.

### PR DESCRIPTION
**Pull request by mxxcon**

### CODE REVIEW

**Comment by Walkman100** [comment]
The Travis-CI build failure is because of the HTML-proofer failure on the link https://www.name.com/services/namesafe
It seems the images all validated though.

**Comment by Carlgo11** [comment]
Just change name's url to http://www.name.com/

**Comment by Walkman100** [comment]
Or even better, http://www.name.com/services/two-step-verification

**Comment by jamcat22** [comment]
Name.com now uses Google Authenticator instead of Norton VIP

**Comment by mxxcon** [comment]
They might, but this PR is about images. :smile: I updated name.com just so that it builds cleanly.
We can address name.com stuff in another PR

**Comment by jamcat22** [comment]
Sounds good

**Comment by Carlgo11** [comment]
Can we just merge this then change the other name.com stuff?

**Pull request merged**
