### PR TITLE
Added TickTick, UltraViolet

### PR DESCRIPTION
**Pull request by Terrance**
Neither of these support 2FA yet.

### CODE REVIEW

**Comment by jdavis** [comment]
Hey @OllieTerrance. What are these sites? How big are they?

**Comment by Terrance** [comment]
[UltraViolet](https://www.uvvu.com) is a site for managing an online DVD collection.  It's pretty big in the UK now (most DVDs come with a free UV copy); not sure what it's like elsewhere.

[TickTick](https://ticktick.com) is a cross-platform to-do list app.  Heard about it on Lifehacker, seems fairly popular over there, especially since Astrid shut down.

**Comment by jdavis** [comment]
Do these sites have important enough info to warrant 2FA?

**Comment by RichJeanes** [comment]
I think that's very much a grey area distinction that needs to be made. Some people might argue that sites like Reddit shouldn't be on the site for that criterion.
A to-do app I'd say probably not (my opinion but, again, the Reddit argument) but I'm not sure if Ultraviolet stores any kind of payment information or anything.

**Comment by RichJeanes** [comment]
Then again, Wunderlist is already on the site.

**Comment by Terrance** [comment]
Yeah, I guess it's more whether they store "valuable information", depending on your definition of the term.  I agree to-do list apps don't really fit for this.  UltraViolet doesn't seem to store payment information, but it could still become something valuable if you own a lot of movies you don't want to lose.

**Comment by jdavis** [comment]
How about we start a criteria of what should be on the site? What about a simple question like "If this account were compromised, could this ruin my life (maybe year)?"

**Comment by Terrance** [comment]
Well, these are the kinds of things I'd consider:
- banking, finance and payment websites
- any sites holding payment information
- sites holding personal information (postal address, NI number / SSN etc.)
- email accounts
- social and IM networks (corporate network platforms?)
- domains and hosting
- cloud storage/sync, code repository hosting
- remote desktop

**Comment by jdavis** [comment]
Yeah, for the most part, those are the main ones. Can we generalize it even more though? Something like this for sites that deal with any of the following:
- Money
- Data (sensitive/important)
- Personal Info
- Control (remote desktop, hosting servers, basically anything that would allow someone to control something that they shouldn't)

**Comment by jdavis** [comment]
@OllieTerrance I think TickTick would be fine to add to the Other section, but I'm going to have to say no on the UltraViolet based on the [Criteria](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#contributing) that we nailed down.

**Pull request closed without merging**
