### PR TITLE
Add DomainFactory

### PR DESCRIPTION
**Pull request by szepeviktor**
See https://forum.df.eu/forum/allgemein/datensicherheit-und-privatsph%C3%A4re/306-zwei-faktor-authentifizierung

### CODE REVIEW

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Hello @szepeviktor,
thanks for the pull request!

As DomainFactory first and foremost advertise themselves as a domain registrar I think the domain category is better suited for them.
Multiple categories is something we're looking into but for now we try to list companies under their main service.

**Comment by szepeviktor** [comment]
Okay.
Starting migration....

**Comment by szepeviktor** [comment]
# 🛑 

Critical Error :) https://github.com/2factorauth/twofactorauth/blob/master/_data/domains.yml#L91-L96

**Comment by Carlgo11** [comment]
Sorry for the inconvenience 😅

**Pull request closed without merging**
