### PR TITLE
Add BeerAdvocate

### LINKED ISSUE #4377: Add BeerAdvocate as supporting 2FA
https://www.beeradvocate.com

### PR DESCRIPTION
**Pull request by phallobst**
Closes #4377

No proper documentation found yet, I sacrified myself for an account :smile:

### CODE REVIEW

**Comment by phallobst** [comment]
beeradvocate-2fa

**Comment by Carlgo11** [comment]
Is it just a forum? Because we don’t list forums.

**Comment by phallobst** [comment]
Well, the forum is certainly a big part of that community, but there are other aspect as well (e.g. rankings, geo locations). I'm not quite sure where the threshold is for a website to be included.

**Comment by Carlgo11** [comment]
Yeah I'm going to close this PR as the majority of the site is just a forum. Sorry :/

**Pull request closed without merging**
