### PR TITLE
Add Domino Data Lab

### PR DESCRIPTION
**Pull request by szuckerman**
Add Domino (dominodatalab.com) to TFA.

### CODE REVIEW

**Comment by stephengroat** [comment]
@szuckerman could you try updating the `img` with this one? it's ~50% smaller

domino

**Review by szuckerman — COMMENTED** [review]
Sure, I'll add it now.

**Comment by szuckerman** [comment]
Sure; I'll add it now.

**Review by stephengroat — APPROVED** [review]
thanks for the pr @szuckerman

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
