### PR TITLE
Add Videoguys Australia [Retail]

### PR DESCRIPTION
**Pull request by Jawshy**
#### Changes:
- Added: [Videoguys Australia](https://www.videoguys.com.au/) under retail. 
  - No TFA. [Twitter handle](https://twitter.com/vidguys).

### CODE REVIEW

**Comment by mxxcon** [comment]
How big, significant is this site?

**Comment by Jawshy** [comment]
The company is a large supplier of video and audio equipment for both consumers and professionals in Australia. I will point out that they are not as notable as many of the other sites current listed under this category. None-the-less, because their website stores personally identifiable and other sensitive information I believe it meets the [site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) 1 and 2.

**Comment by stephengroat** [comment]
As an aside, maybe using a site like domaintally to evaluate websites would be another good way to automate site evaluation. Free API, provides info like this (https://www.domaintally.com/www/videoguys.com.au)

**Comment by Carlgo11** [comment]
Nah I say it's not big enough to be listed as a retail store.
For comparison, we have around x10 times more daily views.

**Comment by Jawshy** [comment]
@Carlgo11, thanks for helping to clear that up. I'll keep that in mind for any future PRs. :+1:

**Pull request closed without merging**
