### PR TITLE
Update ClouDNS info

### PR DESCRIPTION
**Pull request by boyanpeychev**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
Thanks for the pr

**Review by mxxcon — APPROVED** [review]

**Comment by boyanpeychev** [comment]
Thank you too.
How often http://twofactorauth.org is updated?

**Comment by jamcat22** [comment]
@boyanpeychev, while we don't currently have a standardized schedule for pushing changes to the live site, we try to do this within a reasonable amount of time. You can learn more about how our merges work on our [wiki page](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Merge).

**Comment by boyanpeychev** [comment]
Thank you for the provided link @jamcat22
Guys you are doing great job. Good luck with the project!

**Pull request merged**
