### PR TITLE
Update Userify - status

### PR DESCRIPTION
**Pull request by jdavis**
The tweet doesn't exist anymore.

### CODE REVIEW

**Comment by mxxcon** [comment]
There's this tweet https://twitter.com/userify/status/570787153321394176
Although it seems a little ambiguous and out of context.

**Comment by Carlgo11** [comment]
Even tho it's fixed in #974

**Comment by Carlgo11** [comment]
Let's hope for an answer: https://twitter.com/2faorg/status/573973469039321088

**Comment by perpetual-hydrofoil** [comment]
Still in progress w/ version due out in two weeks (hopefully!). btw, thanks for keeping me honest! :)

**Comment by Carlgo11** [comment]
Adding this to #974

**Pull request merged**
