### PR TITLE
Add bitcoin.de

### PR DESCRIPTION
**Pull request by silsha**

### CODE REVIEW

**Comment by mxxcon** [comment]
@silsha what hardware does it support? I see only mention of google authenticator-compatible clients..

**Comment by silsha** [comment]
@mxxcon They support yubikey hardware tokens (see last paragraph in https://www.bitcoin.de/de/faq/was-ist-die-2-step-verification-2-faktor-authentifizierung/46.html - english faq seems to be incomplete).

**Comment by Walkman100** [comment]
Any comments on the image name?

**Comment by Carlgo11** [comment]
oh right @silsha change the image name to bitcoin.de.png or something similar.

**Comment by silsha** [comment]
renamed the file in bitcoinde.png

**Comment by Carlgo11** [comment]
ready for merge

**Pull request merged**
