### PR TITLE
Update to namebase.io

### PR DESCRIPTION
**Pull request by johntheholman**
Added documentation for recovering an account with 2FA

### CODE REVIEW

**Review by phallobst — APPROVED** [review]

**Comment by johntheholman** [comment]
@phallobst what is the preference for these types of links? Should we try to go to the specific answer if on a very tall page? Or does a link to the page that contains the answer more what we are looking for?

**Comment by phallobst** [comment]
If there is a suitable answer with an HTML anchor (like here), we would prefer to use it.

**Comment by johntheholman** [comment]
Sounds good. I will have some more updates coming soon then 😄 . Thanks @phallobst.

**Comment by johntheholman** [comment]
One last question (for now), if `documentation` also contains `recovery` information should this be left to just `documentation` or should we duplicate the URL to the `recovery` key? In this particular scenario there are no anchor tags to differentiate the two links from each other.

**Comment by phallobst** [comment]
If the recovery information is on the same page (even with its own anchor), we only use `documentaton`.

**Pull request merged**
