### PR TITLE
Add Cloudbet

### PR DESCRIPTION
**Pull request by dleshem**
Alexa rank: [31,948](https://www.alexa.com/siteinfo/cloudbet.com)

### CODE REVIEW

**Comment by phallobst** [comment]
The icon looks rather strange. Was it upscaled from 16px? Maybe there is a better one available.

**Comment by dleshem** [comment]
> The icon looks rather strange. Was it upscaled from 16px? Maybe there is a better one available.

Yes, didn't find a high-res version with transparent background. How critical is this?

**Comment by phallobst** [comment]
Not actually critical, but how about this one? It is used on Twitter and Facebook as well.
cloudbet

**Comment by dleshem** [comment]
> Not actually critical, but how about this one? It is used on Twitter and Facebook as well.
> cloudbet

Thanks, done!

**Review by Jawshy — CHANGES_REQUESTED** [review]
Cloudbet appears twice in betting. Also, you've got the old icon for Poalim as a new commit.

**Comment by dleshem** [comment]
Damn, this got all screwed up. I'll just create a new PR.

**Pull request closed without merging**
