### PR TITLE
Add mLab

### PR DESCRIPTION
**Pull request by nitrohorse**

### CODE REVIEW

**Review by stephengroat — APPROVED** [review]
thanks for the pr @trance-with-me

**Comment by nitrohorse** [comment]
Glad to help :smile:

**Review by jamcat22 — COMMENTED** [review]
Please use this icon:

It's 30% smaller. In the future, I recommend using [TinyPNG](tinypng.com) to compress image files. 😄

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
When https://github.com/2factorauth/twofactorauth/pull/2376#pullrequestreview-22865308 is resolved this PR is good to go.

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
