### PR TITLE
Fix Twitter handles

### PR DESCRIPTION
**Pull request by Carlgo11**
I made a script that checks all twitter handles. It's not really done for publishing yet but the result of it is.
Twitter handles are changed where ever possible and those that are either completely removed from twitter or have suspended accounts have had their handles removed from the lists.

I also removed OptionsHouse as it's been merged with E*TRADE and OptionsXpress as it's been merged with Charles Schwab.

### CODE REVIEW

**Comment by kmpoppe** [comment]
Like the PR! The changes to Sierra were already proposed by Stephen in #3714 but not merged because it was unclear whether they really changed existence. Might be worth checking out.

**Comment by Carlgo11** [comment]
@kmpoppe sierratradingpost.com links to sierra.com. On the bottom of that site there’s a copyright note with the name Sierra Trading Post, inc.
Right above that note there’s also a link to @ sierra on Twitter.

**Comment by jtagcat** [comment]
Next up: enter a domain name to check if it is eligable for the list, automatically scrape it's twitter, facebook and email, scrape 2fa details and link to it
After that: run the thing over all top 200k, Having GUI for everything
Nice ;)

**Comment by Carlgo11** [comment]
@vc7ee keep dreaming 😝

**Comment by kmpoppe** [comment]
@Carlgo11 @vc7ee You two have no idea what I have up my sleeve 😜

**Review by kmpoppe — DISMISSED** [review]

**Review by kmpoppe — DISMISSED** [review]
Dismissed my own approval by committing to the branch 🤦‍♂️

**Comment by RichJeanes** [comment]
What's with the empty `twitter.rb` file?

**Comment by Carlgo11** [comment]
That would have been RubyMine automatically adding the file upon creation.
I've removed the file now.

**Review by kmpoppe — APPROVED** [review]

**Review by RichJeanes — APPROVED** [review]

**Pull request merged**
