### PR TITLE
HTTP links to HTTPS

### PR DESCRIPTION
**Pull request by Carlgo11**
Sorry about the commit spam. I blame the client I used.

### CODE REVIEW

**Comment by Carlgo11** [comment]
I've tested all the links. I've also ignored the ones with invalid ssl certs

**Comment by mxxcon** [comment]
https://frostbox.com cert mismatch
https://www.lloydsbank.com/ cert mismatch and if you ignore and follow through it redirects to http
https://twofactorauth.org/notes/internetbs/ this site doesn't support https :smile:
https://help.iwantmyname.com/customer/portal/articles/1139898 cert mismatch
https://support.maxcdn.com/tutorials/enabling-2-step-verification/ cert is revoked outright
https://support.dashlane.com/customer/portal/articles/1099221-protect-your-account-using-two-factor-authentication cert mismatch
https://blog.bitly.com/post/90381427894/introducing-2-step-verification-for-all-users doesn't work.

**Comment by Carlgo11** [comment]
Lol guess I did this a little too fast xD
I'll fix it

**Comment by jdavis** [comment]
Would you mind doing a squash of these commits into a single one? Just rebase it against origin/master interactively, squash them, and then do a force push.

**Comment by jdavis** [comment]
Also, now there is a merge conflict, so rebasing is a must. Thanks @Carlgo11!

**Pull request closed without merging**
