### PR TITLE
Added Garena to gaming.yml

### PR DESCRIPTION
**Pull request by mxxcon**

### CODE REVIEW

**Comment by mxxcon** [comment]
I don't have an account with them, but I did find this https://play.google.com/store/apps/details?id=com.garena.android.authenticator
Also should this be under gaming or social?

**Comment by jdavis** [comment]
I think Gaming is the perfect section.

**Comment by jdavis** [comment]
Darn, it looks like there isn't a better link out there. Do you think the `/account` link is fine?

**Comment by mxxcon** [comment]
Look at the 1st screenshot in that PlayStore link..
https://lh4.ggpht.com/VOcHYMqq0nGlLDs3QBXP3_-xPr8JSMK46YEgQS3xYLQ5l27-CmwAacmiHPExGWjIcFw=h900-rw

**Comment by jamcat22** [comment]
Can you add

`exceptions:
     text: "Mobile phone and a level 3 or higher account required for 2FA."`

garenaaccount
garena2fa

**Pull request merged**
