### PR TITLE
Add Credit Karma

### PR DESCRIPTION
**Pull request by hongchangwu**
Justification: site contains social security number, credit scores, credit reports

### CODE REVIEW

**Comment by Carlgo11** [comment]
Hehe, the logo is executable. (again) :smile:

**Comment by hongchangwu** [comment]
@Carlgo11 oops I think it happens automatically when I copy the file from Windows to Linux. Let me fix it

**Comment by RichJeanes** [comment]
Yeah, that would make sense. Fles coming from a file system without file permissions automatically have 777, I think.

**Comment by Carlgo11** [comment]
Feels a bit odd. Would be better if they had all rights for the owner but only read for group and everyone else.

**Comment by RichJeanes** [comment]
Either that or they copy the parent directory permissions, which is why they would have +x, since directories typically do.

**Comment by mxxcon** [comment]
This logo is based on their favicon creditkarma

**Comment by hongchangwu** [comment]
@mxxcon fair point, this is the icon used in their website. The other one is their app icon.

**Comment by mxxcon** [comment]
grr. i think github mangled transparency. bleh. doesn't really matter.

**Comment by hongchangwu** [comment]
Fixed transparency

**Pull request merged**
