### PR TITLE
Add Seafile

### PR DESCRIPTION
**Pull request by luetyk**
I have added an entry for cloud computing service Seafie.

### CODE REVIEW

**Review by mxxcon — COMMENTED** [review]
Is this a self-hosted software or a service?

**Comment by luetyk** [comment]
It is a software prepared for self-hosting (just like OwnCloud), but Seafile company also provide their servers (like Dropbox). But primary goal of this is to build a private cloud.

**Comment by brycx** [comment]
@luetyk Can you provide a link that shows them offering access to own servers? I can't seem to find anything but license subscriptions.

**Comment by mxxcon** [comment]
@luetyk At this point in time we do not list self-hosted software projects due to complexities of how to display various 2fa plugins/modules with conflicting features.
However, if you'd like to update this PR with the saas aspect of Seafile, that's ok.

**Review by Carlgo11 — CHANGES_REQUESTED** [review]
Please update the PR as requested in https://github.com/2factorauth/twofactorauth/pull/3209#issuecomment-417012398

**Pull request closed without merging**
