### PR TITLE
Added Findmyshift

### PR DESCRIPTION
**Pull request by mark-findmyshift**
Thanks guys, hope it's all OK!

### CODE REVIEW

**Review by Jawshy — CHANGES_REQUESTED** [review]
Thanks for the pull request, @mark-findmyshift. Does Findmyshift have any public documentation about how two-factor authentication is implemented on the website?

**Comment by mark-findmyshift** [comment]
@Jawshy Not at this stage, but we hope to have a help article up in the next week or so.

**Comment by Carlgo11** [comment]
Let's wait for that article to go alive before we merge.

**Comment by mark-findmyshift** [comment]
No problem, I'll let you know when it's up. Thanks!

**Comment by mark-findmyshift** [comment]
Hey guys, two factor authentication documentation is now up: https://www.findmyshift.com/help/what-is-two-factor-authentication

**Comment by Carlgo11** [comment]
Great! So could you add it to this PR @mark-findmyshift?

**Review by Carlgo11 — APPROVED** [review]
All good

**Comment by mark-findmyshift** [comment]
Thanks!

**Review by gingerbeardman — APPROVED** [review]

**Review by Jawshy — APPROVED** [review]

**Pull request merged**
