### PR TITLE
Update 1Password

### LINKED ISSUE #7369: Update [1Password]
### Site name

1Password

### Site URL

https://1password.com

### Update reason

The methods of 2FA that it supports have changed.

### Additional information

Hi. As per 2023-01-24, it's possible to just use security key as 2FA on 1Password. Check out release notes for build 1428 (webpage) here:
https://app-updates.agilebits.com/product_history/B5#v1428

### Issue Eligibility

- [X] The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/twofactorauth/issues).
- [X] The issue I'm creating is not a duplicate of an existing [pull request](https://github.com/2factorauth/twofactorauth/pulls)

### PR DESCRIPTION
**Pull request by hkamran80**
Resolves #7369

### CODE REVIEW

**Comment by Carlgo11** [comment]
@hkamran80 have you checked this yourself? I only have 1 key so I can't verify  :eyes:

**Comment by hkamran80** [comment]
@Carlgo11 I don't use 1Password, so I'm going off the release notes

**Comment by Carlgo11** [comment]
Which release notes?

**Comment by hkamran80** [comment]
These [release notes](https://app-updates.agilebits.com/product_history/B5#v1428) were mentioned in the #7369

**Comment by Carlgo11** [comment]
Oh! :sweat_smile:

**Review by Carlgo11 — APPROVED** [review]

**Pull request merged**
