### PR TITLE
Add Telzio

### PR DESCRIPTION
**Pull request by petefox**

### CODE REVIEW

**Review by mxxcon — COMMENTED** [review]
Perhaps `communication` is a better category for this?
Also if tfa:yes, you don't need twitter and facebook attributes.

**Comment by stephengroat** [comment]
@PeteFox please also remember to alphabetize the `.yml` file that you add to by the `name` tag

**Comment by petefox** [comment]
@mxxcon I did look at Communications, but it seems like all other VoIP and telecom providers are placed in Utilities.

**Comment by stephengroat** [comment]
i agree with @PeteFox. seems like that's where we've listed `VoIP.ms` and some other VoIP providers.

maybe we should revisit in the future? for now, I'm approving

**Review by stephengroat — APPROVED** [review]

**Review by mxxcon — APPROVED** [review]

**Pull request merged**
