### PR TITLE
Slack now support 2FA

### PR DESCRIPTION
**Pull request by didlix**
https://slack.zendesk.com/hc/en-us/articles/204509068-Enabling-two-factor-authentication

### CODE REVIEW

**Comment by jdavis** [comment]
@didlix Would you be able to add a `doc:` value as well pointing to their documentation? I think this site would be best: https://slack.zendesk.com/hc/en-us/articles/204509068

**Comment by RichJeanes** [comment]
Also, their Twitter tag can now be removed and `software: Yes` needs to be added.

**Comment by mxxcon** [comment]
Does keeping twitter tag interfere with anything? If not, then I think we should keep them just in case for the future..

**Comment by Carlgo11** [comment]
omg ;-; #ninjad

**Comment by Carlgo11** [comment]
actually, I'm closing this PR since it needs more work and mine's complete. Hope that's okay with everyone.
It just feels a lot easier to do it like that.

See #1041

**Pull request closed without merging**
